bigcommerce/checkout-sdk-js

packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-initialize-options.ts, packages/core/src/payment/strategies/bluesnapv2/bluesnapv2-payment-options.ts, packages/core/src/payment/strategies/mollie/mollie-initialize-options.ts
Fix JS syntax highlighting for some payment strategies.
The final MD files are messed up.
=> docs(payment): INT-0000: Add missing backticks

packages/core/src/payment/create-payment-strategy-registry.ts, packages/core/src/payment/payment-request-options.ts, packages/core/src/payment/payment-strategy-type.ts, packages/core/src/payment/strategies/worldpay/index.ts, packages/core/src/payment/strategies/worldpayaccess/index.ts, packages/core/src/payment/strategies/worldpayaccess/worldpayaccess-payment-options.ts, packages/core/src/payment/strategies/worldpayaccess/worldpayaccess-payment-strategy.spec.ts, packages/core/src/payment/strategies/worldpayaccess/worldpayaccess-payment-strategy.ts
Added support to handle iFrames and collect device data for Access Worldpay
In order to support 3DS1 and 3DS2 we need to use iframes to handle 3DS data collection and support frictionless and challenge verification.
https://drive.google.com/file/d/1zfe8vvwITn2uoZ-RKOjXuabQcnK2fpcf/view?usp=sharing
=> feat(payment): INT-6115 Worldpay - 3DS support for Access Worldpay

package-loader-rule.js, scripts/webpack/index.js, scripts/webpack/package-loader-rule.js, webpack-common.config.js
Move webpack package loader definition to a separate file.
At the moment for every package we need to add a rule object with a path in webpack config. 
This PR eases that process by updating package list with package name.
- build
=> chore(common): CHECKOUT-000 Update ts loader for packages in webpack

packages/core/src/payment/strategies/mollie/mollie-initialize-options.ts, packages/core/src/payment/strategies/mollie/mollie-payment-strategy.spec.ts, packages/core/src/payment/strategies/mollie/mollie-payment-strategy.ts, packages/core/src/payment/strategies/mollie/mollie.mock.ts
Reverts bigcommerce/checkout-sdk-js#1560
Repeat of https://github.com/bigcommerce/checkout-sdk-js/pull/1510. We had to revert that since it broke the checkout-js build - presumably because https://github.com/bigcommerce/checkout-js/pull/938 hadn't been merged yet.
For when we're ready to merge both PRs - cc @bc-alejandroRodriguez
=> Revert "Revert "fix(payment): INT-5854 [Mollie] Klarna is not available if cart contains digital products""

packages/core/src/payment/create-payment-strategy-registry.ts, packages/core/src/payment/strategies/klarnav2/index.ts, packages/core/src/payment/strategies/klarnav2/klarnav2-payment-strategy.spec.ts, packages/core/src/payment/strategies/klarnav2/klarnav2-payment-strategy.ts, packages/core/src/payment/strategies/klarnav2/klarnav2-token-updater.spec.ts, packages/core/src/payment/strategies/klarnav2/klarnav2-token-updater.ts
I switched to use PaymentMethodRequestSender.loadPaymentMethod function instead paymentMethodActionCreator.loadPaymentMethod(gateway_id) to avoid the klarnav1 payment method adding.
we noticed that when we use loadPaymentMethod(gateway_id) function, load Klarna v1 payment_methods
=> feat(payment): INT-6342 fix klarna issue adding klarna v1 payment_method

packages/core/src/payment/strategies/stripev3/stripev3-error.spec.ts, packages/core/src/payment/strategies/stripev3/stripev3-error.ts, packages/core/src/payment/strategies/stripev3/stripev3-initialize-options.ts, packages/core/src/payment/strategies/stripev3/stripev3-payment-strategy.spec.ts, packages/core/src/payment/strategies/stripev3/stripev3-payment-strategy.ts, packages/core/src/payment/strategies/stripev3/stripev3.ts
Alteration of error message when stripe 3DS auth fails
To give more information to the user about the failure
@bigcommerce/checkout @bigcommerce/payments @bigcommerce/apex-integrations 
https://github.com/bigcommerce/checkout-js/pull/940
=> Fix(payment): STRIPE-53 Give more information on payment authentication with 3ds failure error message

packages/core/src/checkout-buttons/strategies/braintree/braintree-paypal-button-strategy.spec.ts, packages/core/src/checkout-buttons/strategies/braintree/braintree-paypal-button-strategy.ts
Removed `PAYPAL-1149.braintree-new-card-below-totals-banner-placement` experiment
It was turned on for all stores more than 10 months ago.
Unit tests
=> refactor(payment): PAYPAL-1611 removed PAYPAL-1149.braintree-new-card-below-totals-banner-placement experiment

packages/core/src/checkout-buttons/checkout-button-options.ts, packages/core/src/checkout-buttons/create-checkout-button-registry.ts, packages/core/src/checkout-buttons/strategies/checkout-button-method-type.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/index.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-credit-button-options.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-credit-button-strategy.spec.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-credit-button-strategy.ts, packages/core/src/payment/strategies/paypal-commerce/paypal-commerce-script-loader.spec.ts, packages/core/src/payment/strategies/paypal-commerce/paypal-commerce-script-loader.ts, packages/core/src/payment/strategies/paypal-commerce/paypal-commerce-sdk.ts, packages/core/src/payment/strategies/paypal-commerce/paypal-commerce.mock.ts
Added PayPalCommerceCredit checkout button strategy
It is a part of PayPalCommerce button strategy separation. We as developers want to have clearer vision of whats functionality related for current feature.
Unit tests
Manual tests
Screenshot of the result:
=> feat(payment): PAYPAL-1386 added PayPalCommerceCredit checkout button strategy

packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-credit-button-strategy.spec.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-credit-button-strategy.ts, packages/core/src/payment/strategies/paypal-commerce/paypal-commerce-script-loader.spec.ts, packages/core/src/payment/strategies/paypal-commerce/paypal-commerce-script-loader.ts, packages/core/src/payment/strategies/paypal-commerce/paypal-commerce-sdk.ts, packages/core/src/payment/strategies/paypal-commerce/paypal-commerce.mock.ts
Updated paypal button rendering implementation in PayPalCommerceCreditButtonStrategy by by changing funding source eligibility check to configured button eligibility check.
Because `isFundingEligible` method is not suitable for our needs. We should check configured button eligibility instead
Unit tests
Manual tests
=> fix(payment): PAYPAL-0000 updated paypal button rendering implementation in PayPalCommerceCreditButtonStrategy

packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-alternative-methods-button-strategy.spec.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-alternative-methods-button-strategy.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-credit-button-strategy.spec.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-credit-button-strategy.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-v2-button-strategy.spec.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-v2-button-strategy.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-venmo-button-strategy.spec.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-venmo-button-strategy.ts, packages/core/src/payment/strategies/paypal-commerce/paypal-commerce-credit-card-payment-strategy.spec.ts, packages/core/src/payment/strategies/paypal-commerce/paypal-commerce-payment-processor.spec.ts, packages/core/src/payment/strategies/paypal-commerce/paypal-commerce-payment-processor.ts, packages/core/src/payment/strategies/paypal-commerce/paypal-commerce-script-loader.spec.ts, packages/core/src/payment/strategies/paypal-commerce/paypal-commerce-script-loader.ts
Fixed PayPalCommerce zoid issue.
Zoid issue - is an implementation (or a bug) on PayPal side, what destroys all paypal components on the page if the script was loaded couple times in the same time.
It should help us to avoid a lot of Sentry issues with 'Zoid destroyed all components' message.
To avoid an issue when PayPal removes its own components.
Unit tests
Manual tests
=> fix(payment): PAYPAL-1639 fixed paypal commerce zoid issue

packages/core/src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.spec.ts, packages/core/src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.ts
StripeUPE always requires to get a postal code and in some countries is not needed so i deleted the validation in the _mapStripePaymentData function
StripeUPE unable to process payments for billing address where no zip/postal code is required
Before change:
After change:
Proof of other payment methods working
=> fix(payment): STRIPE-130 Stripe UPE making postal code not always required to make purchase

packages/core/src/payment/create-payment-strategy-registry.spec.ts, packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-processor.spec.ts, packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-processor.ts, packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2.mock.ts, packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2.ts, packages/core/src/payment/strategies/amazon-pay-v2/create-amazon-pay-v2-payment-processor.spec.ts
1. Add the new `estimatedOrderAmount` parameter.
2. Add some missing tests.
1. Because Amazon Pay will use this value to assess transaction risk and prevent buyers from selecting payment methods that can't be used to process the order.
2. To increase code coverage.
Amazon Pay script logs the result:
=> feat(payment): INT-6407 AmazonPayV2: Add the new `estimatedOrderAmount` parameter

packages/core/src/payment/strategies/bluesnapv2/bluesnapv2-payment-strategy.ts
Complete the order inside iframe.
We notice the following behavior related with Bluesnap,
After select a payment method for Bluesnap (Credit cards or any other APMs) and click on continue, now Bluesnap opens a new tab and the tab where originally was generating the purchase keeps loading and display a blank iframe. 
To clarify, you are able to complete the order on new tab displayed, but the fact that process left a tab loading a blank iframe seems like bad user experience.
The behavior was tested on store of Integrations and Staging. And were tested on different browsers (Chrome, Safari, Firefox) to see this is not related with browser configuration, but for all of them happens the same.
Before:
After:
ping @bigcommerce/payments @bigcommerce/apex-integrations
=> fix(payment) INT-6328 Bluesnap open a new tab insted of using iframe to complete order

packages/core/src/payment/create-payment-strategy-registry.spec.ts, packages/core/src/payment/create-payment-strategy-registry.ts, packages/core/src/payment/instrument/supported-payment-instruments.ts, packages/core/src/payment/payment-strategy-type.ts, packages/core/src/payment/strategies/bnz/bnz-payment-strategy.spec.ts, packages/core/src/payment/strategies/bnz/bnz-payment-strategy.ts, packages/core/src/payment/strategies/bnz/index.ts
Added bank of New Zealand payment strategy
As a Merchant I want to be able to accept payments through Bank of New Zealand.
=> feat(payment): INT-6310 added bank of new zealand strategy

package-lock.json, package.json, packages/core/src/checkout-buttons/checkout-button-options.ts, packages/core/src/checkout-buttons/create-checkout-button-registry.ts, packages/core/src/checkout-buttons/strategies/checkout-button-method-type.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/index.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-inline-checkout-button-options.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-inline-checkout-button-strategy.spec.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-inline-checkout-button-strategy.ts, packages/core/src/payment/strategies/paypal-commerce/paypal-commerce-request-sender.ts, packages/core/src/payment/strategies/paypal-commerce/paypal-commerce-sdk.ts, packages/core/src/payment/strategies/paypal-commerce/paypal-commerce.mock.ts
Added PayPalCommerce inline checkout button strategy
PayPal requested BC PayPal team to integrate their new feature Inline (Accelerated) Checkout.
Accelerated checkout button replaces out BC 'Check Out' button on the cart page and the customer goes trough PayPal checkout flow.
Unit tests
Manual tests
Here are some screenshots of the result:
=> feat(payment): PAYPAL-1474 added PayPalCommerceInlineCheckoutButtonStrategy

packages/core/src/bodl/bodl-emitter-service.ts, packages/core/src/bodl/bodl-events-service.spec.ts, packages/core/src/bodl/bodl-service.ts, packages/core/src/bodl/bodl-window.ts, packages/core/src/bodl/create-bodl-service.spec.ts, packages/core/src/bodl/create-bodl-service.ts, packages/core/src/bodl/index.ts, packages/core/src/bodl/is-bodl-enabled.ts, packages/core/src/bodl/noop-bodl-service.ts, packages/core/src/bundles/checkout-sdk.ts
Added Bodl Events Service, that triggers 2 events: Checkout Begin and Order Purchased 
1) Storefront will inject bodl events library (EventEmitter) into DOM, that will an interface to emit events and subscribe on events. This part is for emitting events.
2) had to update tslib, had an issue with VSCode interfaces 
more: https://stackoverflow.com/questions/58329178/the-syntax-requires-an-imported-helper-named-spreadarrays
unit
@bigcommerce/checkout @bigcommerce/payments @bigcommerce/storefront-team
=> feat(storefront): STRF-9858 Bodl Service: Checkout Begin and Order Purchased

packages/core/src/payment/instrument/supported-payment-instruments.ts
Adds worldpayacces to support vaulting
We need to support vaulting for Worldpay Access
=> feat(payment): INT-5494 Worldpayaccess - Support vaulting

packages/core/src/checkout-buttons/checkout-button-options.ts, packages/core/src/checkout-buttons/checkout-button-strategy-action-creator.ts, packages/core/src/checkout-buttons/create-checkout-button-registry.spec.ts, packages/core/src/checkout-buttons/create-checkout-button-registry.ts, packages/core/src/checkout-buttons/strategies/checkout-button-method-type.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-strategy.spec.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-strategy.ts
Removed unnecessary paypal commerce V2 button strategy code, that left as a part of paypal commerce button strategies separation
It is a final step of paypal commerce button strategies separation.
Unit tests
CI tests
=> refactor(payment): PAYPAL-1541 remove unnecessaru paypal commerce button strategy code

packages/core/src/hosted-form/iframe-content/hosted-input.spec.ts, packages/core/src/hosted-form/iframe-content/hosted-input.ts
Using a numeric keypad to enter numbers.
Speed up the checkout.
Before:
After:
Copied the newly generated html code, then made a static page for testing on mobile. Page source code:
```
Card number:<br>
<input id="card-number" placeholder="" autocomplete="cc-number" aria-label="Credit Card Number" inputmode="numeric" pattern="[0-9]*" value=""><br>
Name:<br>
<input id="card-name" placeholder="" autocomplete="cc-name" aria-label="Name on Card" inputmode="text" value="">
```
https://user-images.githubusercontent.com/88361607/189790937-d5ba8968-97f7-4385-a121-55955c1993e7.mov
=> feat(checkout): CHECKOUT-6860 Use numeric keypad

packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-inline-checkout-button-strategy.spec.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-inline-checkout-button-strategy.ts
Updated 'experience' button option in PayPalCommerceInlineCheckoutButtonStrategy
PayPal requested to make this changes due to PayPal SDK update from their side. Accelerated checkout button doesn't work without this update.
Unit tests
Manual tests
=> feat(payment): PAYPAL-1673 updated 'experience' button option in PayPalCommerceInlineCheckoutButtonStrategy

packages/core/src/cart/buy-now-cart-request-body.ts, packages/core/src/cart/cart-request-sender.spec.ts, packages/core/src/cart/cart-request-sender.ts, packages/core/src/cart/cart.ts, packages/core/src/cart/errors/buy-now-cart-creation-error.ts, packages/core/src/cart/errors/index.ts, packages/core/src/cart/index.ts, packages/core/src/checkout-buttons/create-checkout-button-registry.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-options.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-strategy.spec.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-strategy.ts
Added Buy Now implementation for PayPalCommerceButtonStrategy
Due the task: https://bigcommercecloud.atlassian.net/browse/PAYPAL-1625
Unit tests
Manual tests
=> feat(payment): PAYPAL-1625 added Buy Now implementation for PayPalCommerceButtonStrategy

packages/core/src/analytics/analytics-extra-items-manager.ts, packages/core/src/analytics/analytics-step-tracker.spec.ts, packages/core/src/analytics/analytics-step-tracker.ts, packages/core/src/analytics/create-step-tracker.ts, packages/core/src/payment/create-payment-strategy-registry.ts, packages/core/src/payment/strategies/bolt/bolt-payment-strategy.spec.ts, packages/core/src/payment/strategies/bolt/bolt-payment-strategy.ts
GA doesn't work with Bolt Checkout if we navigate to the confirmation page from any page other than the checkout page.
Added `_setExtraItemsForAnalytics()` method for set up extra data to LocalStorage for GA
According to task [BOLT-282](https://bigcommercecloud.atlassian.net/browse/BOLT-282)
Validation is not available in the test environment
Need to check in the production environment
=> feat(payment): BOLT-282 fixed analytics feature for Bolt Checkout

packages/core/src/checkout-buttons/strategies/paypal-commerce/get-valid-button-style.spec.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/get-valid-button-style.ts
Added default height value for PayPal buttons if height is not provided
To avoid issues with PayPal size when height is not provided from BE
Manual tests
Unit tests
=> feat(payment): PAYPAL-1690 added default height value for PayPal buttons if height is not provided

packages/core/src/customer/customer-actions.ts, packages/core/src/customer/customer-reducer.spec.ts, packages/core/src/customer/customer-reducer.ts, packages/core/src/customer/customer.ts, packages/core/src/customer/strategies/stripe-upe/stripe-upe-customer-strategy.spec.ts, packages/core/src/customer/strategies/stripe-upe/stripe-upe-customer-strategy.ts, packages/core/src/customer/strategies/stripe-upe/stripe-upe-customer.mock.ts, packages/core/src/customer/strategies/stripe-upe/stripeupe-customer-initialize-options.ts
- Add `stripeLinkAuthenticated` to the customer's data state and its corresponding actions to update it.
- Also add `| undefined ` to StripeUPE `getStyles` function.
- It was suggested to move this state to the `checkout-sdk` from `checkout-js` to avoid adding more states handled by the checkout component.
- `getStyles` function may also  have to return `undefined` on newer implementations of the function due to additional validations.
https://github.com/bigcommerce/checkout-js/pull/1017
=> feat(payment): STRIPE-25 Stripe Link State

packages/core/src/bodl/bodl-emitter-service.ts, packages/core/src/bodl/bodl-events-service.spec.ts, packages/core/src/bodl/bodl-window.ts
Changed usage of BODL event names directly to public methods on the library.
To avoid discrepancy on event names between clients of the library.
https://github.com/bigcommerce/bodl-events/pull/25/files#diff-ea794abbd2f1d06c91f25f33458480aac092e4448178a154e7f50cdd6019528fR14
=> refactor(checkout): STRF-10042 Incapsulate BODL event names into public methods

packages/core/src/checkout-buttons/create-checkout-button-registry.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-venmo-button-options.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-venmo-button-strategy.spec.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-venmo-button-strategy.ts
Added Buy Now functionality to PayPalCommerceVenmo button strategy
Due the task: https://bigcommercecloud.atlassian.net/browse/PAYPAL-1627
Manual tests
Unit tests
=> feat(payment): PAYPAL-1627 added Buy Now implementation for PayPalCommerceVenmo button strategy

packages/core/src/checkout-buttons/create-checkout-button-registry.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-alternative-methods-button-options.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-alternative-methods-button-strategy.spec.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-alternative-methods-button-strategy.ts
Added Buy Now implementation for PayPalCommerce alternative methods button strategy
Due the task: https://bigcommercecloud.atlassian.net/browse/PAYPAL-1628
Manual tests
Unit tests
=> feat(payment): PAYPAL-1628 added Buy Now implementation for PayPalCommerce alternative methods button strategy

packages/core/src/payment/strategies/square/square-payment-strategy.ts, packages/core/src/payment/strategies/square/square-script-loader.ts
Added a try/catch with a reject msg and refactored it to return an error if the provider scripts path fails.
Square is having degraded performance on their API and it is causing all checkouts to fail if a store has square enabled.
https://drive.google.com/file/d/1rbZXSOWFunQXrnk07fGcP06YOFA1KV9w/view?usp=sharing
=> fix(payment): INT-6478 SquareV2 - Fail Gracefully when payment provider unavailable

packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-inline-checkout-button-strategy.spec.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-inline-checkout-button-strategy.ts
Fixed the issue with passing fake data as customer address from last session in PayPalCommerceInlineCheckoutButtonStrategy by clearing billing and consignment address before creating PayPal order
Sometimes user can skip accelerated checkout in an unfinished state. In this case, fake data, that used to operate with shipping options before getting valid data from paypal, saves in checkout state. The user gets prev saved fake data from prev session in current one.
This code fixes this issue.
Manual tests
Unit tests
Before:
Fake data can be found in shipping address section
After:
The user sees prefilled shipping address from user's paypal account
=> fix(payment): PAYPAL-1725 fixed the issue with passing fake data as customer address from last session in PayPalCommerceInlineCheckoutButtonStrategy

packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-inline-checkout-button-strategy.spec.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-inline-checkout-button-strategy.ts
We used some 'Fake' data to fill all required empty fields to make an ability to create paypal order. We removed 'Fake' data implementation in this PR.
We found a way how to avoid using 'Fake' data in Checkout SDK.
Unit tests
Manual tests
=> refactor(payment): PAYPAL-1742 removed Fake data implementation due to BE changes

packages/core/src/checkout-buttons/create-checkout-button-registry.ts, packages/core/src/checkout-buttons/strategies/braintree/braintree-paypal-credit-button-options.ts, packages/core/src/checkout-buttons/strategies/braintree/braintree-paypal-credit-button-strategy.spec.ts, packages/core/src/checkout-buttons/strategies/braintree/braintree-paypal-credit-button-strategy.ts
Quick payment button for BraintreePaypalCredit provider
According to task [PAYPAL-1631](https://bigcommercecloud.atlassian.net/browse/PAYPAL-1631)
https://user-images.githubusercontent.com/99336044/197715660-511068ae-d7d6-4431-8b88-2f9890a449dd.mov
=> feat(payment): PAYPAL-1631 BraintreePayPalCredit on PDP

packages/core/src/payment/strategies/worldpayaccess/worldpayaccess-payment-strategy.spec.ts, packages/core/src/payment/strategies/worldpayaccess/worldpayaccess-payment-strategy.ts
**worldpayaccess-payment-strategy.ts**
- Insert form in the hidden iframe with the script 
Payments with WorldpayAccess were not working on Firefox due to an iframe not being injected properly.
This iframe contains a hidden form needed to retrieve device data requested by Worldpay's 3DS verification. Due to this error, the payment can not be processed
[Video](https://drive.google.com/file/d/1sWq1uNEbLiWfF6wTVk_6xVc0lOIgQTZb/view?usp=sharing)
=> fix(payment): INT-6772 WorldpayAcces supported in firefox

packages/core/src/payment/create-payment-strategy-registry.ts, packages/core/src/payment/strategies/digitalriver/digitalriver-payment-strategy.spec.ts, packages/core/src/payment/strategies/digitalriver/digitalriver-payment-strategy.ts, packages/core/src/payment/strategies/digitalriver/digitalriver.ts
Support PayPal as APM for Digital River
As a merchant using Digital River, I want to be able to accept payment with PayPal.
AC:
When enabled on Digital River account, PayPal displays within the DR drop-in component on my checkout page.
Shopper can pay with PayPal.
Merchant can void PayPal transaction from CP.
Merchant can capture PayPal transaction from CP.
Merchant can fully refund PayPal transaction from CP.
Merchant can partially refund PayPal transaction from CP.
reflect the correct billing address on the order in BC (if Paypal address is different from what was entered on the checkout form)
For a digital order , the tax must be calculated based on the billing address on the PayPal account
https://user-images.githubusercontent.com/104527753/195113173-aafd0cf8-9b59-4073-9a25-6c067f72326 …
=> feat(payment): INT-6675 [Digital River] Update billingAddress from paypal

packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-inline-checkout-button-strategy.spec.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-inline-checkout-button-strategy.ts, packages/core/src/payment/strategies/paypal-commerce/paypal-commerce-sdk.ts
Added condition to submit payment in `onComplete` method for auth&capture transactions for PayPalInlineCheckoutButtonStrategy
We should not make secondary submit payment request for 'Authentication only' transaction types because it causes an error on BigPay side. Order data will be updated after 'Capture Funds' for transaction in CP by using Webhooks. 
bcapp: https://github.com/bigcommerce/bigcommerce/pull/49407
Unit tests
Manual tests
QA tests
=> fix(payment): PAYPAL-1758 added condition to submit payment in onComplete method for auth&capture transaction only for PayPalInlineCheckoutButton

packages/core/src/checkout-buttons/checkout-button-options.ts, packages/core/src/checkout-buttons/checkout-button-strategy-action-creator.spec.ts, packages/core/src/checkout-buttons/checkout-button-strategy-action-creator.ts
Added currencyCode param to loadPaymentMethod request to make an ability to load payment method for specific currencyCode 
The main point that we can't get valid payment method configuration for wallet payment button on Product Details Page, because we don't created buy now cart and quota to get currency from there.
bcapp: https://github.com/bigcommerce/bigcommerce/pull/49198
Unit tests
Manual tests
**Before:**
USD:
GBP:
**After:**
USD:
GBP:
Default currency:
=> feat(payment): PAYPAL-1737 added currencyCode param to loadPaymentMethod request

packages/core/src/checkout-buttons/strategies/amazon-pay-v2/amazon-pay-v2-button-strategy.spec.ts, packages/core/src/checkout-buttons/strategies/amazon-pay-v2/amazon-pay-v2-button-strategy.ts, packages/core/src/customer/strategies/amazon-pay-v2/amazon-pay-v2-customer-strategy.spec.ts, packages/core/src/customer/strategies/amazon-pay-v2/amazon-pay-v2-customer-strategy.ts, packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-processor.spec.ts, packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-processor.ts, packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-strategy.spec.ts, packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-strategy.ts
Render the Amazon Pay button in a container created programmatically.
To allow the Amazon Pay script to handle this new container instead of handling the container passed by the client. See issue #1652
=> fix(payment): INT-6848 AmazonPayV2: Render the button in a container created programmatically

packages/core/src/payment/payment-strategy-action-creator.spec.ts, packages/core/src/payment/payment-strategy-action-creator.ts
Add a validation to force to use PaymentStrategy V1 when the methodId is apple pay and gateway is mollie.
This to use the MolliePaymentStrategy.
As a momentarily solution to support Apple Pay on Mollie, and meanwhile an enhancement to support Mollie as PaymentStrategy V2.
=> feat(payment): INT-5953-T Force to use Payment Strategy V1 when Mollie and Apple pay

packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-processor.spec.ts, packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-processor.ts, packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-strategy.spec.ts, packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-strategy.ts
1. I changed the logic to bind the edit button in the payment strategy when the `APB` experiment is `ON`.
2. Put US merchant functionality behind its own experiment. 🇺🇸
3. Fixes a bug introduced in #1655 🐞 
1. The logic is wrong. The buyer must be able to edit regardless of the `APB` experiment value. We should only validate the presence of the `paymentToken` and a `containerId`.
2. This will allow us to release the enhancement to US merchants only.
3. Simulated mouse click on the pay button doesn't work.
https://user-images.githubusercontent.com/4843328/198750934-5e7e2dea-cc04-4299-b173-3c9aaf3f1d48.mp4
👉 https://github.com/bigcommerce/bigcommerce/pull/49563
=> fix(payment): INT-6890 AmazonPayV2: Change `isReadyToPay` logic

packages/core/src/customer/strategies/stripe-upe/stripe-upe-customer-strategy.spec.ts, packages/core/src/customer/strategies/stripe-upe/stripe-upe-customer-strategy.ts, packages/core/src/payment/create-payment-strategy-registry.ts, packages/core/src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.spec.ts, packages/core/src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.ts, packages/core/src/payment/strategies/stripe-upe/stripe-upe.mock.ts, packages/core/src/payment/strategies/stripe-upe/stripe-upe.ts, packages/core/src/shipping/strategies/stripe-upe/stripe-upe-shipping-initialize-options.ts, packages/core/src/shipping/strategies/stripe-upe/stripe-upe-shipping-strategy.spec.ts, packages/core/src/shipping/strategies/stripe-upe/stripe-upe-shipping-strategy.ts, packages/core/src/shipping/strategies/stripe-upe/stripe-upe-shipping.mock.ts
Persisting data to use when checkout is reloaded, to achieve this we are forcing to load again shipping and customer steps on checkout to refill Stripe components and preserve Stripe behavior, in addition to improving the user experience, we make these steps auto-skip once it finishes loading
For **STRIPE-183**, Link Enrollment Opt-In Disappears If Shopper Navigates Away From Checkout because the information is not persisting & for **STRIPE-195** I want to allow shoppers whose email address is both enrolled in Link and has a merchant registered account to skip the sign-in prompt if they successfully authenticate with Link so that they are not asked to authenticate with two different accounts 
[VIDEO STRIPE-183](https://drive.google.com/file/d/1ccuz-hfTxp-3mSgfiJpM2V6CImRdA91P/view?usp=shar …
=> feat(payment): STRIPE-183 persisting stripe components when reloads the page

packages/core/src/bodl/bodl-emitter-service.ts, packages/core/src/bodl/bodl-events-service.spec.ts, packages/core/src/bodl/bodl-window.ts, packages/core/src/checkout/checkout.ts, packages/core/src/checkout/checkouts.mock.ts, packages/core/src/order/order.ts, packages/core/src/order/orders.mock.ts, packages/core/src/payment/strategies/googlepay/googlepay.mock.ts
- We are changing name for base price field, adding sale price and purchase price
- Channel id for both events
- Tax total for order purchased
- Rename sku
Updated BODL payload to match desired structure: [link](https://docs.google.com/document/d/13qlYa9gtuVcjs2iBZ-jWP74W1GPRQw9J496t7QYbbJg/edit#heading=h.1m5ajudz3zss)
Should be merged after [bcapp PR](https://github.com/bigcommerce/bigcommerce/pull/49561) is merged
=> feat(checkout): STRF-10153 Data Layer Updates - Field Additions and Changes

packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-strategy.spec.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-strategy.ts
Removed 'Fake' data implementation from PayPalCommerceButtonStrategy
We used 'Fake' data to fill all required empty fields in onShippingAddressChange and onShippingOptionChange callbacks to create an order trough bigpay. But we don't need to mock the data for onShippingAddressChange and onShippingOptionChange to pass bigpay validation anymore, due to the bigpay mapper update
Unit tests
Manual tests
https://user-images.githubusercontent.com/25133454/199940641-b1e8d3a2-db21-464d-82ae-e1d9d3d407bb.mov
=> refactor(payment): PAYPAL-1756 removed 'Fake' data implementation from paypal commerce button strategy

packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-credit-button-strategy.spec.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-credit-button-strategy.ts
Removed 'Fake' data implementation from PayPalCommerceCreditButtonStrategy
We used 'Fake' data to fill all required empty fields in onShippingAddressChange and onShippingOptionChange callbacks to create an order trough bigpay. But we don't need to mock the data for onShippingAddressChange and onShippingOptionChange to pass bigpay validation anymore, due to the bigpay mapper update
Unit tests
Manual tests
https://user-images.githubusercontent.com/25133454/199946944-5fe03621-4057-40da-9fe9-32b031c45adc.mov
=> refactor(payment): PAYPAL-1757 removed 'Fake' data implementation from paypal commerce credit button strategy

packages/core/src/bodl/analytics-steps.ts, packages/core/src/bodl/bodl-emitter-service.ts, packages/core/src/bodl/bodl-events-service.spec.ts, packages/core/src/bodl/bodl-service.ts, packages/core/src/bodl/bodl-window.ts, packages/core/src/bodl/create-bodl-service.ts, packages/core/src/bodl/noop-bodl-service.ts, packages/core/src/customer/customer-request-options.ts, packages/core/src/customer/strategies/bolt/bolt-customer-strategy.spec.ts, packages/core/src/customer/strategies/bolt/bolt-customer-strategy.ts
Add additional BODL analytics events emitors to checkout.
Checkout-js PR: [https://github.com/bigcommerce/checkout-js/pull/1024](https://github.com/bigcommerce/checkout-js/pull/1024)
Because of task: [https://bigcommercecloud.atlassian.net/browse/BOLT-386](https://bigcommercecloud.atlassian.net/browse/BOLT-386)
Manual tested
=> feat(payment): BOLT-386 Add BODL analytics tracking events

packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-inline-checkout-button-options.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-inline-checkout-button-strategy.spec.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-inline-checkout-button-strategy.ts
Removed unnecessary business logic from PayPalCommerceInlineCheckoutButton strategy
The business logic was moved to the place where PayPalCommerceInlineCheckoutButton strategy should be initialised. This change should make current strategy more abstract and easier to maintain.
https://github.com/bigcommerce/bigcommerce/pull/49605
Unit tests
Manual tests
Cornerstone theme:
Merchant's theme:
=> refactor(payment): PAYPAL-1773 removed unnecessary business logic from PayPalCommerceInlineCheckoutButton strategy

packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-strategy.spec.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-strategy.ts
Added ability for skip checkout to work on PDP (paypalcommerce).
According to task https://bigcommercecloud.atlassian.net/browse/PAYPAL-1722
smart-payment-buttons PR: https://github.com/bigcommerce/smart-payment-buttons/pull/12
bcapp PR: https://github.com/bigcommerce/bigcommerce/pull/49657
Tested on dev and int
=> feat(payment): PAYPAL-1722 added skip checkout functionality to PDP

packages/core/src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.spec.ts, packages/core/src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.ts, packages/core/src/payment/strategies/stripe-upe/stripe-upe.ts
If the customer add postal code, we don't need to request in card
Merchant reports that wants to hide the postal code field in the payment form
=> fix(payment): STRIPE-167 Adding Postal Code to stripe card element if not obtained in billing

packages/core/src/payment/strategies/digitalriver/digitalriver-payment-strategy.spec.ts, packages/core/src/payment/strategies/digitalriver/digitalriver-payment-strategy.ts, packages/core/src/payment/strategies/digitalriver/digitalriver.ts
Implementation on Digital River of the availability/hide for PayPay APM using the 'disabledPaymentMethods'  behind the the experiment 'PROJECT-4802.digital_river_paypal_support'.
This implement a way to control the "disabledPaymentMethods" on the checkout strategy for Digital River.
When the experiment is on (true) PayPal will be disabled in the checkout for Digital River.
There is no side effect since it only controls the availability for PayPal on the checkout with Digital River.
This is needed to control the availability of the PayPal flow on Digital River as requested.
[Video Proof](https://drive.google.com/file/d/1a2pYhHrAywUL2QFRoMPnU4XATrTvSIyV/view?usp=sharing)
[feat(payment): INT-6443 experiment creation: 'PROJECT-4802.digital_river_paypal_support'](https://github.com/bigcommerce/ …
=> feat(payment): INT-6443 Hide payPal onDigital River behind an experiment

packages/core/src/bodl/bodl-emitter-service.ts, packages/core/src/bodl/bodl-events-service.spec.ts, packages/core/src/bodl/bodl-window.ts
**Event: Purchase**
- Rename event from ‘purchase’ to ‘order_purchased’.
- Rename ‘id’ field to ‘event_id’
- Rename ‘transaction_id’ to ‘order_id’.
- Rename ‘coupon’ to ‘coupon_codes’. Transform to array
**Event: Checkout**
- Rename ‘id’ field to ‘event_id’
- Rename ‘coupon’ to ‘coupon_codes’. Transform to array
Product requirement
Unit tests
=> chore(analytics): DATA-10422 Rename fields for BODL events

packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-credit-button-strategy.spec.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-credit-button-strategy.ts
Added ability for skip checkout to work on PDP (paypalcommercecredit).
According to task https://bigcommercecloud.atlassian.net/browse/PAYPAL-1723
Tested on int and dev
=> feat(payment): PAYPAL-1723 added ability to skip checkout page  on PDP (paypalcommercecredit)

packages/core/src/hosted-form/hosted-form.ts, packages/core/src/payment-integration/create-payment-integration-service.ts, packages/core/src/payment-integration/default-payment-integration-service.spec.ts, packages/core/src/payment-integration/default-payment-integration-service.ts, packages/payment-integration-api/src/hosted-form/hosted-field-type.ts, packages/payment-integration-api/src/hosted-form/hosted-form-options.ts, packages/payment-integration-api/src/hosted-form/hosted-form.ts, packages/payment-integration-api/src/hosted-form/hosted-input-events.ts, packages/payment-integration-api/src/hosted-form/iframe-content.ts, packages/payment-integration-api/src/hosted-form/index.ts, packages/payment-integration-api/src/index.ts, packages/payment-integration-api/src/payment-integration-service.ts, packages/payment-integration-api/src/payment/index.ts
Add `HostedForm` to the payment integration JS API.
Unblock refactoring subsequent payment methods, such as `credit-card-payment-method`, which depends on `HostedForm`, `HostedFormOptions`, `HostedFieldType`, and `HostedFormFactory`.
- Added one unit test.
- CI checks.
=> refactor(checkout): CHECKOUT-7107 Refactor `hosted-form`

packages/core/src/payment/strategies/klarnav2/klarna-supported-countries.ts
Added the Greece country code to support the capability to show klarna widget in greek
As a Merchant I want to present the Klarna payment step in greek
Greece purchase flow with all the different locales cases [video](https://drive.google.com/file/d/1lHSw15qiclOAojvimd2Lawu1y_JEZ7wq/view?usp=sharing)
https://github.com/bigcommerce/bigpay/pull/6339
Greece purchase flow with all the different locales cases [video](https://drive.google.com/file/d/1lHSw15qiclOAojvimd2Lawu1y_JEZ7wq/view?usp=sharing)
=> feat(payment): INT-6727 add Klarna support for greece

packages/core/src/payment/strategies/mollie/mollie-payment-strategy.spec.ts, packages/core/src/payment/strategies/mollie/mollie-payment-strategy.ts
Logged in shoppers who saved their card previously are not able to select the option of using a different card and entering their new credit card details.
When the shopper selects “use a different card” they should see the credit card fields 
https://user-images.githubusercontent.com/104527753/203615753-1b3be81e-4fe2-4cfb-8de1-edf9049227a7.mov
https://user-images.githubusercontent.com/104527753/203615803-0205ef7e-3f38-41a6-bf89-76d34ff4de47.mov
- https://github.com/bigcommerce/checkout-js/pull/1110
=> fix(payment): INT-6928 [Mollie] No Ability To Use A Different Card To Pay

packages/core/src/bodl/bodl-emitter-service.ts, packages/core/src/bodl/bodl-events-service.spec.ts, packages/core/src/bodl/bodl-service.ts, packages/core/src/bodl/noop-bodl-service.ts
Add new Bodl analytics event to Bolt customer suggestion initialization
Because of task: [https://bigcommercecloud.atlassian.net/browse/BOLT-408](https://bigcommercecloud.atlassian.net/browse/BOLT-408)
=> feat(payment): BOLT-408 Add BODL event for customer suggestion init

packages/adyen-integration/src/adyenv2/adyenv2-payment-strategy.ts, packages/adyen-integration/src/adyenv2/adyenv2.ts, packages/adyen-integration/src/adyenv3/adyenv3-payment-strategy.ts, packages/adyen-integration/src/adyenv3/adyenv3.ts
Added adyen credit card es translation fix.
‘Fecha de caducidad’ instead of  ‘Fecha de expiración’
Due to the https://bigcommercecloud.atlassian.net/browse/ADYEN-629
=> fix(payment): ADYEN-629 added adyen credit card es translation fix

packages/offline-integration/src/create-offline-payment-strategy.spec.ts, packages/offline-integration/src/offline-payment-strategy.spec.ts, packages/offline-integration/src/offline-payment-strategy.ts
Add payment method data to the offline payment method order creation payload.
Otherwise, instead of "Awaiting payment," the newly placed order would be "pending".
- CI checks.
- Manual testing:
https://user-images.githubusercontent.com/88361607/208001487-e750095e-e4fc-4764-bdfb-125bdfe85f7c.mov
=> fix(checkout): CHECKOUT-6406 Fix payload for offline payment method

packages/core/src/payment/strategies/stripe-upe/stripe-upe-initialize-options.ts, packages/core/src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.ts, packages/core/src/payment/strategies/stripe-upe/stripe-upe.mock.ts, packages/core/src/payment/strategies/stripe-upe/stripe-upe.ts
Render Submit Button after the payment form and input elements have fully loaded.
So that shoppers know that they have additional information to fill in prior to trying to submit payment.
On loading
Loaded
[#1080](https://github.com/bigcommerce/checkout-js/pull/1080)
=> feat(payment): STRIPE-178 Render Submit button after Stripe elements are loaded

packages/core/src/payment/payment-strategy-action-creator.spec.ts, packages/core/src/payment/payment-strategy-action-creator.ts, packages/core/src/payment/payment-strategy-registry.spec.ts, packages/core/src/payment/payment-strategy-registry.ts, packages/core/src/payment/strategies/mollie/mollie-payment-strategy.spec.ts
Skip `RegistryV1` and enforce `RegistryV2` for `SquareV2` payment method.
`SquareV2` shares the same method id with `SqaureV1`. As a result, `checkout-sdk` always resolves to the old Square payment method.
This PR enfoces the use of the new `Square` monorepo pacakge.
- CI checks.
=> feat(checkout): CHECKOUT-0000 Enforce RegistryV2 for SquareV2

packages/core/src/payment/strategies/bolt/bolt-payment-strategy.spec.ts, packages/core/src/payment/strategies/bolt/bolt-payment-strategy.ts, packages/core/src/payment/strategies/bolt/bolt.mock.ts, packages/core/src/payment/strategies/bolt/bolt.ts
Fix issue with empty Bolt payment fields after disabling store credits
Checkout-js changes: [https://github.com/bigcommerce/checkout-js/pull/1117](https://github.com/bigcommerce/checkout-js/pull/1117)
Because of task: [https://bigcommercecloud.atlassian.net/browse/BOLT-268](https://bigcommercecloud.atlassian.net/browse/BOLT-268)
Before:
https://user-images.githubusercontent.com/9430298/205292685-ae7ce077-bce6-4cea-8c16-078c62152da4.mov
After:
https://user-images.githubusercontent.com/9430298/205292732-77c8321a-263a-4ebe-b5bf-331e51191705.mov
Test:
=> fix(payment): BOLT-268 Bolt payment fields with store credits

packages/external-integration/project.json, packages/external-integration/src/create-external-payment-strategy.ts, packages/external-integration/src/external-payment-strategy.ts, packages/external-integration/src/index.ts, packages/sezzle-integration/.eslintrc.json, packages/sezzle-integration/README.md, packages/sezzle-integration/jest.config.js, packages/sezzle-integration/project.json, packages/sezzle-integration/src/create-sezzle-payment-strategy.spec.ts, packages/sezzle-integration/src/create-sezzle-payment-strategy.ts, packages/sezzle-integration/src/index.spec.ts, packages/sezzle-integration/src/index.ts, packages/sezzle-integration/src/sezzle-payment-strategy.spec.ts, packages/sezzle-integration/src/sezzle-payment-strategy.ts, packages/sezzle-integration/tsconfig.json, packages/sezzle-integration/tsconfig.lib.json, packages/sezzle-integration/tsconfig.spec.json, tsconfig.base.json, workspace.json
Create a sezzle strategy to redirect to Sezzle using window.location.replace
Sezzle deprecated POST method, now we require to redirect using GET method
[Video](https://drive.google.com/file/d/1XCA_47V988tWV878Jcd4QEJt8AEij0c2/view?usp=sharing)
=> feat(payment): INT-6957 Sezzle - Use window.location.replace to redirect

packages/core/src/customer/create-customer-strategy-registry.ts, packages/core/src/customer/customer-request-options.ts, packages/core/src/customer/strategies/paypalcommerce/index.ts, packages/core/src/customer/strategies/paypalcommerce/paypalcommerce-customer-initialize-options.ts, packages/core/src/customer/strategies/paypalcommerce/paypalcommerce-customer-strategy.spec.ts, packages/core/src/customer/strategies/paypalcommerce/paypalcommerce-customer-strategy.ts
Added PayPalCommerceCustomer strategy
To add PayPal Commerce button to the customer step
Here is a screenshot of the PayPal button in customer step and a video of the result:
https://user-images.githubusercontent.com/25133454/207329128-0a3e051d-a49a-4d0c-adc6-e850b0c23051.mov
bigcommerce: https://github.com/bigcommerce/bigcommerce/pull/50236
checkout-js: https://github.com/bigcommerce/checkout-js/pull/1123
=> feat(payment): PAYPAL-1836 added PayPalCommerceCustomer strategy

packages/core/src/payment/payment-strategy-registry.ts, packages/offsite-integration/src/create-offsite-payment-strategy.ts
Fix v1 payment registry automatically registering offsite/hosted strategies.
Since offsite payment registry has been moved to a separate package we need to remove the fallback in V1 registry. Also set the type for strategy to setup correctly, since as of now the fallback loads credit-card strategy.
- circle
=> fix(payment): CHECKOUT-000 Fix default setup for offsite payment strategy

packages/core/src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.ts
No exception is thrown when retrieving shipping address when there are only digital products in the order.
Trying to purchase digital products results in an error "Unable to proceed because shipping address data is unavailable" on payment step
https://user-images.githubusercontent.com/69487174/209418303-9723d6d4-81ea-4552-8e51-92855db6a2f7.mov
ping @bigcommerce/payments @bigcommerce/apex-integrations @bigcommerce/kyiv-payments-team
=> fix(payment): STRIPE-281 Fixed error when making purchases with only digital products

packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-alternative-methods-button-strategy.spec.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-alternative-methods-button-strategy.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-strategy.spec.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-strategy.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-credit-button-strategy.spec.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-credit-button-strategy.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-inline-checkout-button-strategy.spec.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-inline-checkout-button-strategy.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-venmo-button-strategy.spec.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-venmo-button-strategy.ts, packages/core/src/payment/strategies/paypal-commerce/paypal-commerce-credit-card-payment-strategy.ts, packages/core/src/payment/strategies/paypal-commerce/paypal-commerce-hosted-form.spec.ts, packages/core/src/payment/strategies/paypal-commerce/paypal-commerce-hosted-form.ts, packages/core/src/payment/strategies/paypal-commerce/paypal-commerce-payment-processor.ts, packages/core/src/payment/strategies/paypal-commerce/paypal-commerce-request-sender.spec.ts, packages/core/src/payment/strategies/paypal-commerce/paypal-commerce-request-sender.ts, packages/core/src/payment/strategies/paypal-commerce/paypal-commerce-sdk.ts
Passing vaulting data to order creation request for PayPal Commerce
To make hosted Credit Cards component work with vaultings.
Unit tests
Manual tests
=> feat(payment): PAYPAL-1808 passing vaulting data to order creation request for PayPal Commerce CC

packages/core/src/customer/strategies/paypalcommerce/paypalcommerce-customer-strategy.spec.ts, packages/core/src/customer/strategies/paypalcommerce/paypalcommerce-customer-strategy.ts
Fixed the issue with createOrder props in PayPalCommerceCustomerStrategy
It was an issue with PayPalCommerceCustomerStrategy create order request params. The implementation for createOrder method in PayPalCommerceRequestSender were changed in one of the prev merged PR.
Unit tests
CI tests
=> fix(payment): PAYPAL-000 fixed the issue with createOrder props in PayPalCommerceCustomerStrategy

packages/core/src/payment/strategies/klarnav2/klarna-supported-countries.ts
Added the Czech Republic country code to support the capability to show Klarna widget in Czech
As a Merchant, I want to present the Klarna payment step in Czech
support cs-CZ [video](https://drive.google.com/file/d/1AUx4VMFcnkSL-5mNtyoQD_rcDlxzDjRA/view?usp=sharing)
support en-CZ [video](https://drive.google.com/file/d/144A7Z1J_eS-GgpemXVVPSFSby52-Jrs5/view?usp=sharing)
support browser locale (cs) [video](https://drive.google.com/file/d/1P2TbraOXP1c4hHw3FRcrSKcuaSQ0vCE0/view?usp=sharing)
https://github.com/bigcommerce/bigpay/pull/6375
=> feat(payment): INT-6729 add Klarna support for Czech Republic

packages/core/src/cart/errors/cart-consistency-error.ts, packages/core/src/cart/errors/index.ts, packages/core/src/checkout/checkout-store-error-selector.ts, packages/core/src/order/order-request-sender.spec.ts, packages/core/src/order/order-request-sender.ts
Throw `CartInconsistencyError` when server detects inconsistent projection data.
To notify browser clients about the error so they can handle it accordingly when it is thrown.
Unit + Manual
https://user-images.githubusercontent.com/667603/209246970-95ba9508-7912-4243-ad3e-189c8fb787d6.mov
=> CHECKOUT-7148: Throw `CartConsistencyError` when server detects inconsistent projection data

.circleci/config.yml
Update CircleCI config to use new context when building artifact.
This is the [new context](https://bigcommerce.slack.com/archives/C04HQKQ6ES0/p1673220267636719?thread_ts=1673217936.859679&cid=C04HQKQ6ES0) we should use.
CircleCI
=> CHECKOUT-7148: Update CircleCI config to use new context when building artifact

packages/core/src/payment-integration/create-payment-integration-selectors.ts, packages/core/src/payment/instrument/instrument-action-creator.spec.ts, packages/core/src/payment/instrument/instrument-action-creator.ts, packages/core/src/payment/instrument/instrument-request-sender.ts, packages/core/src/shipping/shipping-address-selector.ts, packages/payment-integration-api/src/payment-integration-selectors.ts
In case of multi-shipping, we want to send an array of addresses to the `trusted_shipping_address` endpoint instead of a single address.
This is required to allow vaulting cards with multi-shipping.
Screenshots
**Before**
**After (with multiple addresses)**
**After (with single address)**
=> feat(payment): PAYMENTS-8378 Send multiple addresses to trusted_shipping_address endpoint in case of multi-shipping

package-lock.json, package.json
Update bigpay-client-js version to 5.21.0
Needed for [this PR](https://github.com/bigcommerce/checkout-sdk-js/pull/1745).
Unit tests
=> feat(payment): PAYMENTS-8378 Update bigpay-client-js version to 5.21.0

packages/core/src/payment/strategies/bolt/bolt-script-loader.spec.ts, packages/core/src/payment/strategies/bolt/bolt-script-loader.ts
Fix error on loading Bolt track.js script
Because of tack: [https://bigcommercecloud.atlassian.net/browse/BOLT-362](https://bigcommercecloud.atlassian.net/browse/BOLT-362)
Before:
After:
Test:
=> fix(payment): BOLT-362 fix Bolt track.js error in console

packages/core/src/customer/strategies/bolt/bolt-customer-initialize-options.ts, packages/core/src/customer/strategies/bolt/bolt-customer-strategy.ts
Modify BODL analytics event for Bolt suggestion on customer step
Because of task: [https://bigcommercecloud.atlassian.net/browse/BOLT-437](https://bigcommercecloud.atlassian.net/browse/BOLT-437)
Checkout-sdk-js test:
Checkout-js test:
[BOLT-437]: https://bigcommercecloud.atlassian.net/browse/BOLT-437?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BOLT-437]: https://bigcommercecloud.atlassian.net/browse/BOLT-437?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(payment): BOLT-437 Modify analytics event for Bolt suggestion on customer step

packages/core/src/customer/create-customer-strategy-registry.ts, packages/core/src/customer/customer-request-options.ts, packages/core/src/customer/strategies/braintree/braintree-paypal-customer-options.ts, packages/core/src/customer/strategies/braintree/braintree-paypal-customer-strategy.spec.ts, packages/core/src/customer/strategies/braintree/braintree-paypal-customer-strategy.ts, packages/core/src/customer/strategies/braintree/index.ts
Create braintree-paypal customer button strategy
Checkout-js PR: [https://github.com/bigcommerce/checkout-js/pull/1140](https://github.com/bigcommerce/checkout-js/pull/1140)
Because of task:  [https://bigcommercecloud.atlassian.net/browse/PAYPAL-1839](https://bigcommercecloud.atlassian.net/browse/PAYPAL-1839)
Manual testing a unit test
=> feat(payment): PAYPAL-1839 Create braintreepaypal customer button strategy

packages/adyen-integration/src/adyenv2/adyenv2-payment-strategy.ts, packages/adyen-integration/src/adyenv3/adyenv3-payment-strategy.ts
Fixed 3ds2 for vaulted Adyen cards
Due to the  https://bigcommercecloud.atlassian.net/browse/ADYEN-688
=> fix(checkout): ADYEN-688 fixed 3ds2 redirect for vaulted cards

.github/CODEOWNERS, packages/squarev2-integration/src/mocks/squarev2-web-payments-sdk.mock.ts, packages/squarev2-integration/src/squarev2-payment-processor.spec.ts, packages/squarev2-integration/src/squarev2-payment-processor.ts
Exempt the postal code input field from validation if it hasn't been rendered yet.
There are regions that do not prompt for a postal code, so we need to allow buyers from those regions to continue as long as the other fields are valid. For those regions that prompt for a postal code, as soon as the input is displayed, events will be fired and the field will start to be validated.
https://user-images.githubusercontent.com/4843328/211678871-ab7f4e6a-76ed-4225-9da2-adca82ecd733.mov
[INT-7103]: https://bigcommercecloud.atlassian.net/browse/INT-7103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(payment): INT-7103 SquareV2: Assume that `postalCode` is valid unless it changes

packages/core/src/billing/billing-address-reducer.spec.ts, packages/core/src/billing/billing-address-reducer.ts, packages/core/src/checkout/checkout-store-state.ts, packages/core/src/checkout/checkouts.mock.ts, packages/core/src/checkout/create-checkout-store-reducer.ts, packages/core/src/checkout/create-internal-checkout-selectors.ts, packages/core/src/checkout/internal-checkout-selectors.ts, packages/core/src/customer/map-to-internal-customer.ts, packages/core/src/order-billing-address/index.ts, packages/core/src/order-billing-address/order-billing-address-reducer.spec.ts, packages/core/src/order-billing-address/order-billing-address-reducer.ts, packages/core/src/order-billing-address/order-billing-address-selector.spec.ts, packages/core/src/order-billing-address/order-billing-address-selector.ts, packages/core/src/order-billing-address/order-billing-address-state.ts, packages/core/src/order-billing-address/order-billing-address.mock.ts, packages/core/src/order/order-selector.spec.ts, packages/core/src/order/order-selector.ts, packages/core/src/order/order.ts, packages/core/src/payment/strategies/affirm/affirm-payment-strategy.spec.ts, packages/payment-integration-api/src/order/order-billing-address.ts, packages/payment-integration-api/src/order/order.ts
Merge billing address returned from load order endpoint with existing address in state.
Since load order call returns a billing address without an id, it causes side effects since we replace the existing object. In order to maintain reference to the existing id we need to merge the two objects.
- Circle
=> fix(billing): CHECKOUT-7214 Merge billing address as compared to replace

packages/core/src/order-billing-address/order-billing-address-reducer.spec.ts, packages/core/src/order-billing-address/order-billing-address-reducer.ts
Fix issue with offsite payment completion
Fix issue with offsite payment method such as BarclayCard not being able to be finalised.
- Circle
- Manual
https://user-images.githubusercontent.com/7134802/213689204-851ab1ff-4666-4a8c-95b8-488a42cf0a18.mov
=> fix(payment): CHECKOUT-000 Fix issue with offsite payment completion

packages/core/src/shipping/strategies/stripe-upe/stripe-upe-shipping-strategy.spec.ts, packages/core/src/shipping/strategies/stripe-upe/stripe-upe-shipping-strategy.ts, packages/core/src/shipping/strategies/stripe-upe/stripe-upe-shipping.mock.ts
Destroy the StripeShippingElement and create another when the element exists
StripeShippingElement is created in blank the first time since there is no previous shipping info and when the StripeLink user logs out and returns to the step, the last StripeShippingElement is called (because we have one element already created), and the Stripe get method doesn't accept parameters by default, that's why the fields will render in the blank(because last StripeShippingElement was created with no parameters filled by default), To fix this we are deleting the previous element created and creating it again with new default values, with this approach we can prevent it from leaving blank
https://drive.google.com/file/d/1YZSS76WX_nUta-Qqk8D15q4gg-GsEz6c/view?usp=sharing …
=> feat(payment): STRIPE-194 Clear Prefilled Shipping Address Information If Shopper Logs Out Of Link

packages/core/src/customer/create-customer-strategy-registry.ts, packages/core/src/customer/customer-request-options.ts, packages/core/src/customer/strategies/braintree/braintree-paypal-credit-customer-options.ts, packages/core/src/customer/strategies/braintree/braintree-paypal-credit-customer-strategy.spec.ts, packages/core/src/customer/strategies/braintree/braintree-paypal-credit-customer-strategy.ts, packages/core/src/customer/strategies/braintree/index.ts
Create Braintree PayPal Credit customer button strategy
Related PRs:
checkout-js: [https://github.com/bigcommerce/checkout-js/pull/1171](https://github.com/bigcommerce/checkout-js/pull/1171)
BCapp: [https://github.com/bigcommerce/bigcommerce/pull/50845](https://github.com/bigcommerce/bigcommerce/pull/50845)
Because of task: [https://bigcommercecloud.atlassian.net/browse/PAYPAL-1840](https://bigcommercecloud.atlassian.net/browse/PAYPAL-1840)
Checkout-sdk-js unit test:
BCapp unit tests:
=> feat(payment): PAYPAL-1840 Create braintreepaypalcredit customer button strategy

packages/adyen-integration/src/adyenv2/adyenv2-payment-strategy.ts, packages/adyen-integration/src/adyenv2/adyenv2.ts, packages/adyen-integration/src/adyenv3/adyenv3-payment-strategy.ts, packages/adyen-integration/src/adyenv3/adyenv3.ts
We can’t force the Adyen widget to show the correct placeholder for selected vaulted card because the Adyen widget doesn’t know what card brand was chosen inside the vaulted card select. We decided just hide wrong placeholder to not distract user with wrong typing advice 
Due to the https://bigcommercecloud.atlassian.net/browse/ADYEN-502
https://user-images.githubusercontent.com/79574476/214330159-b4acfdab-bdce-4ef6-946c-10ead95a1c80.mov
=> fix(checkout): ADYEN-502 hide wrong placeholder text for the vaulted validation fields

package-lock.json, package.json, packages/core/src/checkout-buttons/strategies/checkout-button-method-type.ts, packages/core/src/payment/payment-request-transformer.ts
Added temporary PayPalCommerceAlternativeMethods transformer to PayPalCommerceAlternativeMethodsV2
PayPalCommerceAlternativeMethods gateway should be sent to BigPay without transforming to PayPalCommerce gateway. We have only one possible way how to make it as smooth as possible, transform temporary gateway to what we need. 
This code will be removed in the future.
Unit tests
Manual tests
Here is a screenshot of payment method gateway sent to the BigPay:
bigpay-client-js: https://github.com/bigcommerce/bigpay-client-js/pull/155
bigcommerce: https://github.com/bigcommerce/bigcommerce/pull/50776
=> feat(payment): PAYPAL-1882 sending PPC APM V2 gateway instead of PPC APM

packages/core/src/cart/buy-now-cart-request-body.ts, packages/core/src/cart/cart-request-sender.spec.ts, packages/core/src/cart/cart-request-sender.ts, packages/core/src/cart/cart.ts, packages/core/src/checkout-buttons/strategies/braintree/braintree-paypal-button-strategy.spec.ts, packages/core/src/checkout-buttons/strategies/braintree/braintree-paypal-credit-button-strategy.spec.ts, packages/core/src/checkout-buttons/strategies/braintree/braintree-venmo-button-strategy.spec.ts, packages/core/src/checkout-buttons/strategies/googlepay/googlepay-braintree-button-strategy.spec.ts, packages/core/src/checkout-buttons/strategies/googlepay/googlepay-button.mock.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-alternative-methods-button-strategy.spec.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-strategy.spec.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-credit-button-strategy.spec.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-venmo-button-strategy.spec.ts, packages/core/src/payment-integration/create-payment-integration-service.ts, packages/core/src/payment-integration/default-payment-integration-service.spec.ts, packages/core/src/payment-integration/default-payment-integration-service.ts, packages/payment-integration-api/src/cart/buy-now-cart-request-body.ts, packages/payment-integration-api/src/cart/cart-source.ts, packages/payment-integration-api/src/cart/cart.ts, packages/payment-integration-api/src/cart/index.ts, packages/payment-integration-api/src/errors/buy-now-cart-creation-error.ts, packages/payment-integration-api/src/index.ts, packages/payment-integration-api/src/payment-integration-service.ts, packages/payment-integrations-test-utils/src/index.ts, packages/payment-integrations-test-utils/src/test-utils/buy-now-cart-request-body.mock.ts, packages/payment-integrations-test-utils/src/test-utils/carts.mock.ts, packages/payment-integrations-test-utils/src/test-utils/checkouts.mock.ts, packages/payment-integrations-test-utils/src/test-utils/index.ts, packages/payment-integrations-test-utils/src/test-utils/payment-integration-service.mock.ts
Added CartRequestSender to payment integration api package
We don't have an ability to migrate PayPalCommerce strategies to their own package because payment-integration-api package doesn't have buy now cart creation method what core package has.
Unit tests
=> feat(payment): PAYPAL-1898 added CartRequestSender to payment integration api package

packages/core/src/payment/strategies/paypal-commerce/paypal-commerce-script-loader.ts, packages/paypal-commerce-integration/src/paypal-commerce-script-loader.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-script-loader.ts
Fixed the issue with wrong PayPal Sdk configuration to make APMs work in payment step in Checkout Page. 
PayPal APMs does not work on Checkout page due to the mistake in preparing PayPal Sdk configuration. PayPal alternative payment methods don't work in payment step on Checkout page in cases when PayPal Hosted Checkout feature is enabled. 
Unit tests
Manual tests
Here is a screenrecord of the result:
https://user-images.githubusercontent.com/25133454/214807269-bdd97714-09af-4176-95c1-818bf4c8c4ef.mov
=> fix(payment): PAYPAL-1923 fixed the issue with wrong paypal sdk configuration

packages/core/src/checkout-buttons/strategies/braintree/braintree-paypal-button-options.ts, packages/core/src/checkout-buttons/strategies/braintree/braintree-paypal-credit-button-options.ts, packages/core/src/checkout-buttons/strategies/braintree/get-valid-button-style.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/get-valid-button-style.spec.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/get-valid-button-style.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-alternative-methods-button-options.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-alternative-methods-button-strategy.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-options.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-strategy.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-credit-button-options.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-credit-button-strategy.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-venmo-button-options.ts, packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-venmo-button-strategy.ts, packages/core/src/checkout-buttons/strategies/paypal/paypal-button-options.ts, packages/core/src/payment/strategies/paypal-commerce/paypal-commerce-payment-processor.ts, packages/core/src/payment/strategies/paypal-commerce/paypal-commerce-sdk.ts, packages/core/src/payment/strategies/paypal/paypal-sdk.ts
Renamed several PayPal Commerce interfaces to fix the issue with doc files
Due to the issues with docs in dev env
Doc generating command passed successfully:
=> fix(payment): PAYPAL-1929 renamed several PayPal Commerce interfaces to fix the issue with doc files

packages/core/src/payment/strategies/braintree/braintree-hosted-form.ts
Fixed an issue when we could not proceed checkout after trying to place order with an empty CVV for stored card
According to task [PAYPAL-1763](https://bigcommercecloud.atlassian.net/browse/PAYPAL-1763)
https://user-images.githubusercontent.com/99336044/213465895-fb60736b-a316-4f01-a8d0-9b5e15006e09.mov
[PAYPAL-1763]: https://bigcommercecloud.atlassian.net/browse/PAYPAL-1763?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(payment): PAYPAL-1763 fixed an issue when we could not proceed checkout after trying to place order with an empty CVV for stored card

packages/core/src/checkout-buttons/create-checkout-button-registry.ts, packages/core/src/checkout-buttons/strategies/amazon-pay-v2/amazon-pay-v2-button-options.ts, packages/core/src/checkout-buttons/strategies/amazon-pay-v2/amazon-pay-v2-button-strategy.spec.ts, packages/core/src/checkout-buttons/strategies/amazon-pay-v2/amazon-pay-v2-button-strategy.ts, packages/core/src/checkout-buttons/strategies/amazon-pay-v2/amazon-pay-v2-button.mock.ts, packages/core/src/checkout-buttons/strategies/amazon-pay-v2/amazon-pay-v2-config-request-sender-mock.ts, packages/core/src/checkout-buttons/strategies/amazon-pay-v2/amazon-pay-v2-config-request-sender.ts, packages/core/src/checkout-buttons/strategies/amazon-pay-v2/amazon-pay-v2-request-sender.ts, packages/core/src/checkout-buttons/strategies/amazon-pay-v2/errors/amazon-pay-v2-config-creation-error.ts, packages/core/src/checkout-buttons/strategies/amazon-pay-v2/index.ts, packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-processor.spec.ts, packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-processor.ts, packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2.mock.ts, packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2.ts
Added Buy Now functionality for amazon pay on the Product Details Page
According to task [PAYPAL-1635](https://bigcommercecloud.atlassian.net/browse/PAYPAL-1635)
Testing with dependent PR
https://user-images.githubusercontent.com/99336044/210571152-d0df58f2-190a-4c6f-9967-66ab3fef6cf4.mov
Testing the rest of the Amazon flow to make sure that everything works correctly with our changes
- Amazon button flow
https://user-images.githubusercontent.com/99336044/211554560-ed067fbc-6033-4015-a0cf-ce40351b85db.mov
https://user-images.githubusercontent.com/99336044/211554616-9b0ade8b-7c25-46a1-a77e-906874036877.mov
- Amazon payment flow
https://user-images.githubusercontent.com/99336044/211575527-22ee341d-efc9-462b-a9ed-a6f326661e15.mov
https://user-images.githubusercontent.com/99336044/211575649-a3 …
=> fix(payment): PAYPAL-1635 Buy Now feature for amazon pay

packages/payment-integration-api/src/errors/index.ts, packages/payment-integration-api/src/index.ts
Added an ability to use BuyNowCartCreationError from payment-integration-api
To use it in other packages
Unit tests
=> feat(payment): PAYPAL-000 added an ability to use BuyNowCartCreationError from payment-integration-api

packages/core/src/payment-integration/default-payment-integration-service.spec.ts, packages/core/src/payment-integration/default-payment-integration-service.ts, packages/payment-integration-api/src/payment-integration-service.ts
Added an ability to loadCheckout by provided id in payments-integration-api
It is not possible to migrate PayPal Commerce to its own package due to the implementation issues. 
Unit tests
=> feat(payment): PAYPAL-000 added an ability to loadCheckout by provided id in payments-integration-api

packages/core/src/customer/strategies/bolt/bolt-customer-strategy.spec.ts, packages/core/src/customer/strategies/bolt/bolt-customer-strategy.ts, packages/core/src/payment/errors/index.ts, packages/core/src/payment/strategies/bolt/bolt-payment-strategy.spec.ts, packages/core/src/payment/strategies/bolt/bolt-payment-strategy.ts, packages/core/src/payment/strategies/braintree/braintree-credit-card-payment-strategy.ts, packages/core/src/payment/strategies/braintree/braintree-paypal-payment-strategy.spec.ts, packages/core/src/payment/strategies/braintree/braintree-paypal-payment-strategy.ts, packages/core/src/payment/strategies/braintree/braintree-visacheckout-payment-strategy.ts, packages/core/src/payment/strategies/cardinal/cardinal-client.spec.ts, packages/core/src/payment/strategies/cardinal/cardinal-client.ts, packages/core/src/payment/strategies/cba-mpgs/cba-mpgs-payment-strategy.spec.ts, packages/core/src/payment/strategies/cba-mpgs/cba-mpgs-payment-strategy.ts, packages/core/src/payment/strategies/googlepay/googlepay-checkoutcom-initializer.spec.ts, packages/core/src/payment/strategies/googlepay/googlepay-checkoutcom-initializer.ts, packages/core/src/payment/strategies/googlepay/googlepay-stripe-upe-initializer.ts, packages/core/src/payment/strategies/paypal-commerce/paypal-commerce-hosted-form.spec.ts, packages/core/src/payment/strategies/paypal-commerce/paypal-commerce-hosted-form.ts, packages/core/src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.spec.ts, packages/core/src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.ts, packages/payment-integration-api/src/errors/index.ts, packages/payment-integration-api/src/errors/payment-method-failed-error.ts, packages/payment-integration-api/src/index.ts
Make an ability to use PaymentMethodFailedError from core package in integration checkout-sdk packages
because of task: [https://bigcommercecloud.atlassian.net/browse/PAYPAL-1934](https://bigcommercecloud.atlassian.net/browse/PAYPAL-1934)
=> feat(payment): PAYPAL-1934 move PaymentMethodFailedError to integration package

packages/apple-pay-integration/src/apple-pay-button-strategy.spec.ts, packages/apple-pay-integration/src/apple-pay-button-strategy.ts, packages/apple-pay-integration/src/apple-pay-customer-strategy.spec.ts, packages/apple-pay-integration/src/apple-pay-customer-strategy.ts, packages/core/src/checkout-buttons/strategies/apple-pay/apple-pay-button-strategy.spec.ts, packages/core/src/checkout-buttons/strategies/apple-pay/apple-pay-button-strategy.ts, packages/core/src/customer/strategies/apple-pay/apple-pay-customer-strategy.spec.ts, packages/core/src/customer/strategies/apple-pay/apple-pay-customer-strategy.ts
Puts recommended shipping option before non-recommended ones in the applepay shipping method dropdown.
Before this change, when Merchant has selected the `Least expensive, excluding pickup in store` option in the checkout settings in the Control Panel. While shopper is paying via ApplePay, `Pickup in store` is the default selected option in the ApplePay payment modal.
The expectation is for `Pickup in store` to not be the default selected option. 
The issues occurs because triggering the selection of the recommended option here: https://github.com/bigcommerce/checkout-sdk-js/pull/1793/files#diff-1e21ac0b56385d124ac395b7ea974cf5c4b5bfe4975ad290180a53c6e6cfb4abR317
Doesn't select the appropriate select option in applepay modal. It continues to show the shipping option list received from the …
=> fix(payment): PAYMENTS-8239 puts recommended shipping option first in the applepay payment modal

.circleci/config.yml, .gitignore, jest.preset.js, nx.json, package-lock.json, package.json, packages/core/jest.config.js, packages/core/project.json, packages/core/src/spam-protection/google-recaptcha-script-loader.spec.ts
- Move lint to a separate process
- Remove test artifact uploads
- Split test runs into two jobs one for core package and one for the rest of the packages
- Split test runs of core package into two parallel streams
At the moment circlet CI runs take around 10 mins approximately, we can optimise this and have a quicker turn around in our CI steps.
- Circle
Updated CI times for PRs
@bigcommerce/checkout @icatalina
=> chore(common): CHECKOUT-6271 Make changes to circle config

package.json
Add a `build:link` command to skip nx cache.
When a developer runs the `build` command for the second time locally, nx only builds modified files due to its cache mechanism. This will result in `checkout-sdk` not functioning properly when it is linked to `checkout-js`. 
- Manual testing: Custom console log can be seen on a VM store after running `npm run build:link`.
=> fix(checkout): CHECKOUT-0000 Add skip-nx-cache build command

packages/core/src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.ts, packages/core/src/payment/strategies/stripe-upe/stripe-upe.mock.ts
Render Submit Button after the payment form and input elements have fully loaded.
Found a bug that didn't render the pay button if you changed step and go back to the payment
Bug
https://user-images.githubusercontent.com/106765049/211430384-02361724-f2ae-4bfd-9ee5-319116493c10.mov
Bug Fixed
https://user-images.githubusercontent.com/106765049/211428828-69587e7f-a549-40e2-b518-30f1635447d5.mov
Coverage
[STRIPE-289]: https://bigcommercecloud.atlassian.net/browse/STRIPE-289?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(payment): STRIPE-289 Loading Submit button after card loads

packages/core/src/payment/create-payment-strategy-registry.ts, packages/core/src/payment/payment-methods.mock.ts, packages/core/src/payment/strategies/braintree/braintree-payment-processor.ts, packages/core/src/payment/strategies/braintree/braintree-venmo-payment-strategy.spec.ts, packages/core/src/payment/strategies/braintree/braintree-venmo-payment-strategy.ts, packages/core/src/payment/strategies/braintree/index.ts
Add Braintree venmo strategy for payment step
PR BCapp: [https://github.com/bigcommerce/bigcommerce/pull/50862](https://github.com/bigcommerce/bigcommerce/pull/50862)
Because of task: [https://bigcommercecloud.atlassian.net/browse/PAYPAL-1913](https://bigcommercecloud.atlassian.net/browse/PAYPAL-1913)
Checkout-sdk-js test:
BCapp test:
=> feat(payment): PAYPAL-1913 Create braintreevenmo payment strategy

packages/core/src/payment/strategies/braintree/braintree-venmo-payment-strategy.spec.ts, packages/core/src/payment/strategies/braintree/braintree-venmo-payment-strategy.ts
Fix build issue related to incorrect import
Because of build issue after merge [https://github.com/bigcommerce/checkout-sdk-js/pull/1785](https://github.com/bigcommerce/checkout-sdk-js/pull/1785)
=> feat(payment): PAYPAL-1913 fix build issue with error import

packages/core/src/payment/strategies/stripev3/stripev3-payment-strategy.spec.ts, packages/core/src/payment/strategies/stripev3/stripev3-payment-strategy.ts
The `client_token` is sent in the hosted form flow to reuse the payment intent created during initialization and not create a new one.
For Stripe V3, while having `PROJECT-5205.stripe.L3Data` set as on, if we generate orders using vaulted cards then validate the payment on Stripe dashboard, L2/L3 section appear as null. 
https://user-images.githubusercontent.com/69487174/214392681-a9c4cb52-3b62-4d21-9472-197b12e123f5.mov
https://github.com/bigcommerce/bigpay/pull/6576
ping @bigcommerce/payments @bigcommerce/apex-integrations @bigcommerce/kyiv-payments-team 
[STRIPE-287]: https://bigcommercecloud.atlassian.net/browse/STRIPE-287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(payment): STRIPE-287 Fixed error when using vaulted card L2/L3 field appear as null on dashboard

.circleci/config.yml
- Remove small as a resource for test core jobs
- Restore old approve pipeline
- Need to remove small as resource since fresh node install fails most of the time, causing flakiness to the pipeline.
- Restoring old approve pipeline, since now we need to wait for CDN build to complete which is not required for NPM release.
- circle
=> chore(common): CHECKOUT-000 Remove small resource and restore old approve pipeline

packages/paypal-commerce-integration/src/index.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/create-paypal-commerce-credit-button-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/create-paypal-commerce-credit-button-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-button-initialize-options.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-button-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-button-strategy.ts
Added PayPalCommerceCreditButtonStrategy to paypal-commerce-integration package
As part of paypal commerce migration from core to paypal-commerce-integration package
Unit tests
Manual tests
=> refactor(payment): PAYPAL-1889 added PayPalCommerceCreditButtonStrategy to paypal-commerce-integration package

packages/paypal-commerce-integration/src/index.ts, packages/paypal-commerce-integration/src/paypal-commerce-venmo/create-paypal-commerce-venmo-button-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-venmo/create-paypal-commerce-venmo-button-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-venmo/paypal-commerce-venmo-button-initialize-options.ts, packages/paypal-commerce-integration/src/paypal-commerce-venmo/paypal-commerce-venmo-button-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-venmo/paypal-commerce-venmo-button-strategy.ts
Added PayPalCommerceVenmoButtonStrategy to paypal commerce integration package
As part of migration paypal commerce code from core to paypal commerce integration package
Unit tests
Manual tests
=> refactor(payment): PAYPAL-1891 added PayPalCommerceVenmoButtonStrategy to paypal commerce integration package

packages/paypal-commerce-integration/src/index.ts, packages/paypal-commerce-integration/src/paypal-commerce-alternative-methods/create-paypal-commerce-alternative-methods-button-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-alternative-methods/create-paypal-commerce-alternative-methods-button-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-alternative-methods/paypal-commerce-alternative-methods-button-initialize-options.ts, packages/paypal-commerce-integration/src/paypal-commerce-alternative-methods/paypal-commerce-alternative-methods-button-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-alternative-methods/paypal-commerce-alternative-methods-button-strategy.ts
Added PayPalCommerceAlternativeMethodsButtonStrategy to paypal-commerce-integration
As part of PayPalCommerce code migration from core to paypal-commerce-integration package
Unit tests
Manual tests
=> feat(payment): PAYPAL-1892 added PayPalCommerceAlternativeMethodsButtonStrategy to paypal-commerce-integration

packages/core/src/checkout-buttons/strategies/checkout-button-method-type.ts, packages/core/src/payment/payment-request-transformer.ts
Removed unnecessary PayPalCommerceAlternativeMethods v2 transformation in payment request transformer file
The transformer used to speed up a process of refactoring paypal commerce code in other project. We don't need this code anymore.
Unit tests
=> refactor(payment): PAYPAL-1921 removed unnecessary PayPalCommerceAlternativeMethods v2 transformation in payment request transformer file

packages/core/src/payment/strategies/paypal-commerce/paypal-commerce-script-loader.spec.ts, packages/core/src/payment/strategies/paypal-commerce/paypal-commerce-script-loader.ts, packages/paypal-commerce-integration/src/paypal-commerce-script-loader.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-script-loader.ts
Provided buyer-country to the paypal sdk config for dev mode
We as a developers or QA engineers should have an ability to test tricky features without VPN. This feature should help us save some time on development and testing our country based features.
Unit tests
Manual tests
Here how a script url looks like without dev mode:
Dev mode + US store:
Dev mode + UA store:
=> feat(payment): PAYPAL-1959 provided buyer-country to the paypal sdk config for dev mode

packages/core/src/checkout-buttons/strategies/braintree/braintree-paypal-button-strategy.ts, packages/core/src/checkout-buttons/strategies/braintree/braintree-paypal-credit-button-strategy.ts, packages/core/src/customer/strategies/braintree/braintree-paypal-credit-customer-strategy.ts, packages/core/src/customer/strategies/braintree/braintree-paypal-customer-strategy.ts, packages/core/src/payment/strategies/braintree/braintree-sdk-creator.ts, packages/core/src/payment/strategies/braintree/braintree.ts
Added intent param to Braintree SDK and to the paypal order creation config
Sometimes Braintree SDK intent may differ from intent param that was set in CP.
We should have an ability to pass the same intent as we have in Braintree CP settings to Braintree SDK. 
Unit tests
Manual tests
https://user-images.githubusercontent.com/25133454/217488291-3f5c8b66-a4fb-4cd9-b305-e9783e647233.mov
=> fix(payment): PAYPAL-1930 added intent param to Braintree SDK config and to the paypal order creation config

packages/core/src/config/config.ts, packages/core/src/config/configs.mock.ts, packages/payment-integration-api/src/config/config.ts, packages/payment-integrations-test-utils/src/test-utils/config.mock.ts
Add `checkoutUXSettings` to the `CheckoutSettings` interface.
We will introduce a few UX options to merchants in the following weeks.
- https://github.com/bigcommerce/bigcommerce/pull/51091
CI checks.
=> feat(checkout): CHECKOUT-7231 Add checkoutUXSettings to interface

packages/core/src/config/config.ts, packages/core/src/config/configs.mock.ts, packages/payment-integration-api/src/config/config.ts, packages/payment-integrations-test-utils/src/test-utils/config.mock.ts
The name should be `checkoutUserExperienceSettings`, not `CheckoutUserExperienceSettings`.
So it is consistent with the other names of the interface.
CI checks.
=> feat(checkout): CHECKOUT-7231 Update checkoutUserExperienceSettings

packages/apple-pay-integration/src/apple-pay-button-initialize-options.ts, packages/apple-pay-integration/src/apple-pay-button-strategy.spec.ts, packages/apple-pay-integration/src/apple-pay-button-strategy.ts, packages/apple-pay-integration/src/mocks/apple-pay-button.mock.ts, packages/apple-pay-integration/src/mocks/apple-pay-payment.mock.ts
Added ability for applepay to work with buyNowCart functionality on product detail page
The aim is to make applepay button work with buy now cart that will be created on click. Because in moment of click there is a possibility that the store doesn't have checkout object yet.
https://user-images.githubusercontent.com/56301104/215708251-0f98f0ff-b45b-4fa1-a712-6f0cd1b099e3.mov
https://user-images.githubusercontent.com/56301104/215708271-75200192-aae2-4e82-ade0-62ac7786b19d.mov
@bigcommerce/checkout @bigcommerce/payments @animesh1987
=> feat(payment): PAYPAL-1634 added ability for applepay spb to work with buyNowCart on PDP

packages/core/src/payment-integration/default-payment-integration-service.spec.ts, packages/core/src/payment-integration/default-payment-integration-service.ts, packages/payment-integration-api/src/payment-integration-service.ts
Pass options to `loadPaymentMethod`
We need to send the `method` param to be able to load a specific payment method from a gateway. e.g:
`/api/storefront/payments/bluesnapdirect?method=cc`
`/api/storefront/payments/bluesnapdirect?method=sepa`
`/api/storefront/payments/bluesnapdirect?method=ideal`
Unit
👉 #1811
[INT-7044]: https://bigcommercecloud.atlassian.net/browse/INT-7044?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(payment): INT-7044 BlueSnapDirect: Pass options to `loadPaymentMethod`

packages/core/src/checkout-buttons/strategies/googlepay/googlepay-adyenv3-button-strategy.spec.ts, packages/core/src/checkout-buttons/strategies/googlepay/googlepay-authorizenet-button-strategy.spec.ts, packages/core/src/checkout-buttons/strategies/googlepay/googlepay-checkoutcom-button-strategy.spec.ts, packages/core/src/checkout-buttons/strategies/googlepay/googlepay-cybersourcev2-button-strategy.spec.ts, packages/core/src/checkout-buttons/strategies/googlepay/googlepay-orbital-button-strategy.spec.ts, packages/core/src/checkout-buttons/strategies/googlepay/googlepay-stripe-button-strategy.spec.ts, packages/core/src/checkout/checkout-store-selector.spec.ts, packages/core/src/checkout/checkout-store-selector.ts, packages/core/src/config/config.ts, packages/core/src/config/index.ts, packages/core/src/payment-integration/default-payment-integration-service.spec.ts, packages/core/src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.ts, packages/payment-integration-api/src/config/config.ts
Add `getUserExperienceSettings` to `CheckoutStoreSelector`.
Developers can easily read user experience settings in the feature.
Sample usage: `data.getUserExperienceSettings()?.walletButtonsOnTop` will return the flag of using wallet buttons at the top of the checkout page.
Added one unit test.
=> feat(checkout): CHECKOUT-7231 Add getUserExperienceSettings selector

packages/paypal-commerce-integration/src/index.ts, packages/paypal-commerce-integration/src/paypal-commerce-venmo/create-paypal-commerce-venmo-cuastomer-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-venmo/create-paypal-commerce-venmo-customer-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-venmo/paypal-commerce-venmo-customer-initialize-options.ts, packages/paypal-commerce-integration/src/paypal-commerce-venmo/paypal-commerce-venmo-customer-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-venmo/paypal-commerce-venmo-customer-strategy.ts
Add PayPal Commerce Venmo customer strategy which will be used as button on customer step
PayPal Commerce Venmo button was added to make ability for shoppers to use venmo payment method on first step and simplify checkout process.
PR for checkout-js: [https://github.com/bigcommerce/checkout-js/pull/1189](https://github.com/bigcommerce/checkout-js/pull/1189)
https://user-images.githubusercontent.com/9430298/217316025-da535674-8ab6-4330-a387-244731bf6e11.mov
=> feat(payment): PAYPAL-1838 Create paypalcommercevenmo customer button strategy

packages/paypal-commerce-integration/src/index.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/create-paypal-commerce-credit-customer-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/create-paypal-commerce-credit-customer-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-customer-initialize-options.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-customer-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-customer-strategy.ts
Add PayPal Commerce Credit (PayLater) customer strategy which will be used as button on customer step
PayPal Commerce Credit (PayLater) button was added to make ability for shoppers to use PayLater payment method on first step and simplify checkout process.
PR for checkout-js: [https://github.com/bigcommerce/checkout-js/pull/1190](https://github.com/bigcommerce/checkout-js/pull/1190)
PR for BCapp: [https://github.com/bigcommerce/bigcommerce/pull/51145](https://github.com/bigcommerce/bigcommerce/pull/51145)
=> feat(payment): PAYPAL-1837 Create paypalcommercecredit customer button strategy

packages/apple-pay-integration/src/apple-pay-customer-strategy.ts, packages/core/src/customer/strategies/apple-pay/apple-pay-customer-strategy.ts
Move Apple Pay buttons styles to `checkout-js`'s SCSS file.
Following this PR, a `checkout-js` PR will be created.
Those inline styles make it impossible for `checkout-js` to manage the appearance of an Apple Pay wallet button.
After moving styles to `checkout-js`.
=> refactor(checkout): CHECKOUT-7291 Remove ApplePay button style

packages/core/src/payment/strategies/stripe-upe/stripe-upe-script-loader.ts, packages/core/src/payment/strategies/stripe-upe/stripe-upe.ts, packages/core/src/shipping/strategies/stripe-upe/stripe-upe-shipping-strategy.spec.ts, packages/core/src/shipping/strategies/stripe-upe/stripe-upe-shipping-strategy.ts, packages/core/src/shipping/strategies/stripe-upe/stripe-upe-shipping.mock.ts
- Add a Stripe phone field
- Temporarily delete the unmount as the Stripe team has a bug with their new component
- Add pending unit testing
It's required by Stripe to support new fields
**BEFORE:**
**AFTER:**
https://github.com/bigcommerce/checkout-js/pull/1100
=> feat(payment): STRIPE-200 add stripe phone field

packages/paypal-commerce-integration/src/index.ts, packages/paypal-commerce-integration/src/paypal-commerce-integration-service.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-integration-service.ts, packages/paypal-commerce-integration/src/paypal-commerce/create-paypal-commerce-button-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-button-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-button-strategy.ts
Replaced PayPalCommerceCommon name with PayPalCommerceIntegrationService
The new name seems to be more clear as a prev one
Unit tests
=> refactor(payment): PAYPAL-1919 replaced PayPalCommerceCommon name with PayPalCommerceIntegrationService

packages/paypal-commerce-integration/src/paypal-commerce-integration-service.ts, packages/paypal-commerce-integration/src/paypal-commerce/create-paypal-commerce-customer-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-button-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-customer-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-customer-strategy.ts
Updated PayPalCommerceCustomerStrategy with PayPalCommerceIntegrationService
Unit tests
Manual tests
=> refactor(payment): PAYPAL-1973 updated PayPalCommerceCustomerStrategy with PayPalCommerceIntegrationService

packages/paypal-commerce-integration/src/paypal-commerce-alternative-methods/create-paypal-commerce-alternative-methods-button-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-alternative-methods/paypal-commerce-alternative-methods-button-initialize-options.ts, packages/paypal-commerce-integration/src/paypal-commerce-alternative-methods/paypal-commerce-alternative-methods-button-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-alternative-methods/paypal-commerce-alternative-methods-button-strategy.ts
Updated PayPalCommerceAlternativeMethodsButtonStrategy with PayPalCommerceIntegrationService
Unit tests
=> refactor(payment): PAYPAL-1978 updated PayPalCommerceAlternativeMethodsButtonStrategy with PayPalCommerceIntegrationService

packages/paypal-commerce-integration/src/paypal-commerce-venmo/create-paypal-commerce-venmo-customer-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-venmo/paypal-commerce-venmo-customer-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-venmo/paypal-commerce-venmo-customer-strategy.ts
Updated PayPalCommerceVenmoCustomerStrategy with PayPalCommerceIntegrationService
Unit tests
=> refactor(payment): PAYPAL-1982 updated PayPalCommerceVenmoCustomerStrategy with PayPalCommerceIntegrationService

packages/paypal-commerce-integration/src/paypal-commerce-venmo/create-paypal-commerce-venmo-button-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-venmo/paypal-commerce-venmo-button-initialize-options.ts, packages/paypal-commerce-integration/src/paypal-commerce-venmo/paypal-commerce-venmo-button-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-venmo/paypal-commerce-venmo-button-strategy.ts
Updated PayPalCommerceVenmoButtonStrategy with PayPalCommerceIntegrationService
Unit tests
=> refactor(payment): PAYPAL-1981 updated PayPalCommerceVenmoButtonStrategy with PayPalCommerceIntegrationService

packages/core/src/customer/strategies/googlepay/googlepay-adyenv2-customer-strategy.spec.ts, packages/core/src/customer/strategies/googlepay/googlepay-authorizenet-customer-strategy.spec.ts, packages/core/src/customer/strategies/googlepay/googlepay-bnz-customer-strategy.spec.ts, packages/core/src/customer/strategies/googlepay/googlepay-braintree-customer-strategy.spec.ts, packages/core/src/customer/strategies/googlepay/googlepay-checkoutcom-customer-strategy.spec.ts, packages/core/src/customer/strategies/googlepay/googlepay-customer-strategy.ts, packages/core/src/customer/strategies/googlepay/googlepay-cybersourcev2-customer-strategy.spec.ts, packages/core/src/customer/strategies/googlepay/googlepay-orbital-customer-strategy.spec.ts, packages/core/src/customer/strategies/googlepay/googlepay-stripe-customer-strategy.spec.ts, packages/core/src/customer/strategies/googlepay/googlepay-stripe-upe-customer-strategy.spec.ts, packages/core/src/payment/strategies/googlepay/googlepay-payment-strategy.spec.ts, packages/core/src/payment/strategies/googlepay/googlepay-payment-strategy.ts
Update payment data request on googlepay wallet button click 
We've found that Google Pay does not include coupon discount at the 'Customer' step of checkout.
That is why we need to update payment data request on googlepay wallet button click
**Before fix:**
https://user-images.githubusercontent.com/79574476/218151786-bacaa63a-82f6-4c4e-b267-d525a6a6be28.mov
**After fix:**
https://user-images.githubusercontent.com/79574476/218151769-9ca95fb7-be10-4c10-96a9-781739f1e677.mov
=> fix(checkout): ADYEN-588 update payment data request on wallet button click googlepay

packages/paypal-commerce-integration/src/paypal-commerce-credit/create-paypal-commerce-credit-customer-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-customer-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-customer-strategy.ts
Updated PayPalCommerceCreditCustomer strategy with PayPalCommerceIntegrationService
Unit tests
=> refactor(payment): PAYPAL-1980 updated PayPalCommerceCreditCustomer strategy with PayPalCommerceIntegrationService

packages/paypal-commerce-integration/src/paypal-commerce-credit/create-paypal-commerce-credit-button-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-button-initialize-options.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-button-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-button-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-customer-strategy.ts
Updated PayPalCommerceCreditButtonStrategy with PayPalCommerceIntegrationService
Unit tests
=> refactor(payment): PAYPAL-1979 updated PayPalCommerceCreditButtonStrategy with PayPalCommerceIntegrationService

packages/core/src/payment-integration/create-payment-integration-service.ts, packages/core/src/payment-integration/default-payment-integration-service.spec.ts, packages/core/src/payment-integration/default-payment-integration-service.ts, packages/payment-integration-api/src/payment-integration-service.ts
Add applyStoreCredit to PaymentIntegrationService
To get ability to use `storeCreditActionCreator.applyStoreCredit` from `PaymentIntegrationService`
Unit test result:
=> feat(payment): BOLT-463 add applyStoreCredit to PaymentIntegrationService

packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-customer-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-integration-service.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-integration-service.ts, packages/paypal-commerce-integration/src/paypal-commerce-types.ts, packages/paypal-commerce-integration/src/utils/get-valid-button-style.spec.ts, packages/paypal-commerce-integration/src/utils/get-valid-button-style.ts
Removed layout and tagline styles property from PayPalCommerceButtons config
The layout and tagline properties does not do anything for PayPalCommerce buttons after buttons were separated into their own strategies, so the removed styles properties are not in use anymore. 
Unit tests
=> refactor(payment): PAYPAL-1983 removed layout and tagline styles property from PayPalCommerceButtons config

packages/paypal-commerce-integration/src/paypal-commerce-alternative-methods/paypal-commerce-alternative-methods-button-initialize-options.ts, packages/paypal-commerce-integration/src/paypal-commerce-alternative-methods/paypal-commerce-alternative-methods-button-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-button-initialize-options.ts, packages/paypal-commerce-integration/src/paypal-commerce-venmo/paypal-commerce-venmo-button-initialize-options.ts, packages/paypal-commerce-integration/src/paypal-commerce-venmo/paypal-commerce-venmo-button-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-button-initialize-options.ts, packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-button-strategy.spec.ts
Removed `initializesOnCheckout` page property from PayPalCommerce initialize button options
`InitializeOnCheckoutPage` property was added to detect where PayPalCommerce button strategy is in use. However, due to our progress, checkout buttons are used outside checkout page, though, `initializeOnCheckoutPage` will always have false value for button strategies. So we can remove this method because it has static value.
Unit tests
=> refactor(payment): PAYPAL-1971 removed initializesOnCheckout page property from PayPalCommerce initialize button options

packages/analytics/.eslintrc.json, packages/analytics/README.md, packages/analytics/jest.config.js, packages/analytics/project.json, packages/analytics/src/analytics-extra-items-manager.spec.ts, packages/analytics/src/analytics-extra-items-manager.ts, packages/analytics/src/extra-items-data.ts, packages/analytics/src/index.ts, packages/analytics/tsconfig.json, packages/analytics/tsconfig.spec.json, packages/core/src/analytics/analytics-step-tracker.spec.ts, packages/core/src/analytics/analytics-step-tracker.ts, packages/core/src/analytics/analytics-tracker-ga.spec.ts, packages/core/src/analytics/create-step-tracker.ts, packages/core/src/payment/create-payment-strategy-registry.ts, packages/core/src/payment/strategies/bolt/bolt-payment-strategy.spec.ts, packages/core/src/payment/strategies/bolt/bolt-payment-strategy.ts, packages/payment-integration-api/src/index.ts, tsconfig.base.json, workspace.json
Move `AnalyticsExtraItemsManager` interface to paymant-integration-api package
to get ability to use `AnalyticsExtraItemsManager` interfaces in other payment integration packages
Unit tests:
=> feat(payment): BOLT-465 move AnalyticsExtraItemsManager to payment-integration-api package

packages/core/src/payment/strategies/googlepay/googlepay-stripe-upe-initializer.spec.ts, packages/core/src/payment/strategies/googlepay/googlepay-stripe-upe-initializer.ts
Make StripeUPE  Google Pay compatible with Buy Now cart
Fixed GooglePayStripeUPEInitializer to make it work with buyNowCart
To Make StripeUPE Google Pay compatible with Buy Now cart
Unit tests
=> fix(payment): PAYPAL-1993 make StripeUPE  Google Pay compatible with Buy Now cart

packages/core/src/payment/strategies/googlepay/googlepay-cybersourcev2-initializer.spec.ts, packages/core/src/payment/strategies/googlepay/googlepay-cybersourcev2-initializer.ts
Fixed GooglePayCybersourceV2Initializer to make it work with buyNowCart
To Make CyberSourceV2 Google Pay compatible with Buy Now cart
Unit tests
=> fix(payment): PAYPAL-1997 make CyberSourceV2 Google Pay compatible with Buy Now cart

packages/core/src/payment/strategies/googlepay/googlepay-orbital-initializer.spec.ts, packages/core/src/payment/strategies/googlepay/googlepay-orbital-initializer.ts
Make Orbital  Google Pay compatible with Buy Now cart
Fixed GooglePayOrbitalInitializer to make it work with buyNowCart
To Make Orbital Google Pay compatible with Buy Now cart
Unit tests
=> fix(payment): PAYPAL-1998 make Orbital  Google Pay compatible with Buy Now cart

packages/core/src/payment/strategies/googlepay/googlepay-stripe-initializer.spec.ts, packages/core/src/payment/strategies/googlepay/googlepay-stripe-initializer.ts
Make Stripe Google Pay compatible with BuyNow cart
Fixed GooglePayStripeInitializer to make it work with buyNowCart
Fixed GooglePayStripeUPEInitializer to make it work with buyNowCart
Unit tests
=> fix(payment): PAYPAL-1999 make Stripe Google Pay compatible with BuyNow cart

packages/core/src/payment/strategies/googlepay/googlepay-adyenv2-initializer.spec.ts, packages/core/src/payment/strategies/googlepay/googlepay-adyenv2-initializer.ts, packages/core/src/payment/strategies/googlepay/googlepay-adyenv3-initializer.spec.ts, packages/core/src/payment/strategies/googlepay/googlepay-adyenv3-initializer.ts
Fixed GP initialization issue for adyenV2 and adyenV3 when we go through Buy Now Flow
When we go through Buy Now Flow to place an order from PDP we don't have `outstandingBalance` and `currencyCode` we get from `checkout` object. We don't have cart and we work with one item that has its own quate which creates by click on button. Information about collecting these variables is available here [googlepay-button-strategy.ts#L209](https://github.com/bigcommerce/checkout-sdk-js/blob/master/packages/core/src/checkout-buttons/strategies/googlepay/googlepay-button-strategy.ts#L209)
Unit tests
Manual tests
=> fix(payment): PAYPAL-1991 fixed GooglePay for adyenV2 and adyenV3 (Buy Now flow)

packages/core/src/payment/strategies/googlepay/googlepay-authorizenet-initializer.spec.ts, packages/core/src/payment/strategies/googlepay/googlepay-authorizenet-initializer.ts
Fixed GP initialization issue for authorizenet when we go through Buy Now Flow
When we go through Buy Now Flow to place an order from PDP we don't have `outstandingBalance` and `currencyCode` we get from `checkout` object. We don't have cart and we work with one item that has its own quate which creates by click on button. Information about collecting these variables is available here [googlepay-button-strategy.ts#L209](https://github.com/bigcommerce/checkout-sdk-js/blob/master/packages/core/src/checkout-buttons/strategies/googlepay/googlepay-button-strategy.ts#L209)
Unit tests
Manual tests
=> fix(payment): PAYPAL-1995 fixed GooglePay for Authorize Net (Buy Now flow)

packages/core/src/payment/strategies/googlepay/googlepay-checkoutcom-initializer.spec.ts, packages/core/src/payment/strategies/googlepay/googlepay-checkoutcom-initializer.ts
Fixed GP initialization issue for checkoutcom when we go through Buy Now Flow
When we go through Buy Now Flow to place an order from PDP we don't have `outstandingBalance` and `currencyCode` we get from `checkout` object. We don't have cart and we work with one item that has its own quate which creates by click on button. Information about collecting these variables is available here [googlepay-button-strategy.ts#L209](https://github.com/bigcommerce/checkout-sdk-js/blob/master/packages/core/src/checkout-buttons/strategies/googlepay/googlepay-button-strategy.ts#L209)
Unit tests
Manual tests
=> fix(payment): PAYPAL-1996 fixed GooglePay for CheckoutCom (Buy Now flow)

packages/core/src/customer/strategies/braintree/braintree-paypal-credit-customer-options.ts, packages/core/src/customer/strategies/braintree/braintree-paypal-credit-customer-strategy.spec.ts, packages/core/src/customer/strategies/braintree/braintree-paypal-credit-customer-strategy.ts, packages/core/src/customer/strategies/braintree/braintree-paypal-customer-options.ts, packages/core/src/customer/strategies/braintree/braintree-paypal-customer-strategy.spec.ts, packages/core/src/customer/strategies/braintree/braintree-paypal-customer-strategy.ts
Set the height of the PayPal buttons at the top of the checkout page to `36px` rather than `40px`.
So we can provide a standardised wallet button UI to shoppers.
=> refactor(checkout): CHECKOUT-7304 Change PayPal wallet buttons height

packages/core/src/customer/strategies/stripe-upe/stripe-upe-customer-strategy.ts, packages/core/src/payment/strategies/stripe-upe/stripe-upe.ts, packages/core/src/shipping/strategies/stripe-upe/stripe-upe-shipping-strategy.spec.ts, packages/core/src/shipping/strategies/stripe-upe/stripe-upe-shipping-strategy.ts
Split name input into First and Last name
To have a better input field design
[stripe_doc](https://stripe.com/docs/js/elements_object/create_address_element)
Noticed that there was a missing space in the stripe-upe-payment-strategy.ts so I added it to be more readable
[1200](https://github.com/bigcommerce/checkout-js/pull/1200)
=> fix(shipping): STRIPE-202 Split name input into First and Last name

packages/paypal-commerce-integration/src/paypal-commerce-alternative-methods/paypal-commerce-alternative-methods-button-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-alternative-methods/paypal-commerce-alternative-methods-button-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-button-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-button-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-types.ts, packages/paypal-commerce-integration/src/paypal-commerce-venmo/paypal-commerce-venmo-button-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-venmo/paypal-commerce-venmo-button-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-button-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-button-strategy.ts
Load default checkout on PayPal Commerce button cancel callback call
To avoid potential errors between BuyNow and Default flows we should load default checkout on cancel operation after Buy Now cart creation for each PayPal Commerce button. 
...
=> feat(payment): PAYPAL-1985 added loadDefaultCheckout onCancel to avoid potential errors

packages/core/src/payment/strategies/braintree/braintree-hosted-form.spec.ts, packages/core/src/payment/strategies/braintree/braintree-hosted-form.ts, packages/core/src/payment/strategies/braintree/braintree-payment-options.ts, packages/core/src/payment/strategies/braintree/braintree.ts
This is the following PR for the POC to expose the interface for Braintree real-time host form filed validation
https://github.com/bigcommerce/checkout-sdk-js/pull/1848
RealReal would like the Braintree host form filed to have the real-time validation interface. This PR expose it.
Unit tests
Error status
=> feat(payment): PAYMENTS-8527 expose interface for Braintree real time host form filed validation

packages/core/src/payment/strategies/stripev3/stripev3-payment-strategy.spec.ts, packages/core/src/payment/strategies/stripev3/stripev3-payment-strategy.ts
The stripe component for the hosted form flow was initialized
When I try to place an order using a 3DS vaulted card, a message error appears.
https://user-images.githubusercontent.com/69487174/221064151-95dcd7a3-0819-4cd0-9ec8-fd0008e3a508.mov
@bigcommerce/checkout @bigcommerce/apex-integrations @bigcommerce/kyiv-payments-team 
[INT-7463]: https://bigcommercecloud.atlassian.net/browse/INT-7463?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(provider): INT-7463 Fixed problem with cards vaulted with 3ds in the hosted form flow

packages/payment-integration-api/src/hosted-form/index.ts, packages/payment-integration-api/src/hosted-form/is-stored-credit-card-form-fields.spec.ts, packages/payment-integration-api/src/hosted-form/is-stored-credit-card-form-fields.ts, packages/payment-integration-api/src/index.ts
Added isStoredCreditCardFormFields typeguard to payment-integration-api package
We have a lot of hosted form implementation in different packages like paypal commerce and braintree where we should have an ability to detect what form is rendered. So I made a decision to create common typeguard to avoid code duplication in different packages.
Unit tests
=> feat(payment): PAYPAL-000 added isStoredCreditCardFormFields typeguard to payment-integration-api package

packages/paypal-commerce-integration/src/paypal-commerce-venmo/paypal-commerce-venmo-button-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-venmo/paypal-commerce-venmo-button-strategy.ts
Fixed venmo button appearance when gold color applied
Because gold color is invalid for venmo button
According to task https://bigcommercecloud.atlassian.net/browse/PAYPAL-1962
=> feat(payment): PAYPAL-1962 fixed paypal venmo button

packages/core/src/hosted-form/hosted-form-options.ts, packages/core/src/hosted-form/iframe-content/hosted-input-events.ts, packages/core/src/payment/strategies/braintree/braintree-hosted-form.ts, packages/core/src/payment/strategies/braintree/braintree.ts
As above
We have a feature to expose errors on blur for hosted forms added for braintree form in https://github.com/bigcommerce/checkout-sdk-js/pull/1883 PR.
But since Braintree form component uses the HOC for HostedForm we need to expose the errors as part of interface.
- Cirlce
=> fix(payment): CHECKOUT-000 Expose hosted form error to exported typings

packages/core/src/hosted-form/iframe-content/hosted-input-events.ts
Fix exported type
Exported the wrong type in https://github.com/bigcommerce/checkout-sdk-js/pull/1903 as part of hosted form.
- cirlce
=> fix(payment): CHECKOUT-000 Fix exported type

packages/adyen-integration/src/adyenv2/adyenv2-payment-strategy.ts, packages/adyen-integration/src/adyenv2/adyenv2.ts, packages/adyen-integration/src/adyenv3/adyenv3-payment-strategy.ts, packages/adyen-integration/src/adyenv3/adyenv3.ts, packages/payment-integration-api/src/payment-integration-selectors.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-button-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-customer-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-inline/paypal-commerce-inline-button-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-integration-service.ts, packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-button-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-customer-strategy.ts, packages/squarev2-integration/src/squarev2-payment-strategy.ts, packages/squarev2-integration/src/types.ts
Add generic type for `getPaymentMethod` & `getPaymentMethodOrThrow` in payment-integration-api
Because this methods return instance of `PaymentMethod` and this interface has generic type for `initializationData`
[https://github.com/bigcommerce/checkout-sdk-js/blob/master/packages/payment-integration-api/src/payment/payment-method.ts](https://github.com/bigcommerce/checkout-sdk-js/blob/master/packages/payment-integration-api/src/payment/payment-method.ts)
If we want to describe correct type for `PaymentMethod.initializationData` we need to call this methods with generic type.
`unknown` - by default, for cases when we need `PaymentMethod` but don't use `initializationData` from it
unit tests
=> refactor(payment): BOLT-000 add generic type for getPaymentMethod

packages/core/src/config/config.ts, packages/core/src/config/configs.mock.ts, packages/payment-integration-api/src/config/config.ts, packages/payment-integrations-test-utils/src/test-utils/config.mock.ts
Add `floatingLabelEnabled` to the `UserExperienceSettings` interface.
We've updated the BCapp to allow merchants to toggle floating label usage.
https://github.com/bigcommerce/bigcommerce/pull/51713
https://github.com/bigcommerce/checkout-settings-ui/pull/92
[place holder] a `checkout-js` PR uses this PR to display floating labels.
CI.
=> feat(checkout): CHECKOUT-7250 Add `floatingLabelEnabled` to `UserExperienceSettings` interface

packages/paypal-commerce-integration/src/index.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit-card/create-paypal-commerce-credit-cards-payment-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit-card/create-paypal-commerce-credit-cards-payment-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit-card/paypal-commerce-credit-cards-payment-initialize-options.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit-card/paypal-commerce-credit-cards-payment-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit-card/paypal-commerce-credit-cards-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-integration-service.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-integration-service.ts, packages/paypal-commerce-integration/src/paypal-commerce-request-sender.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-request-sender.ts, packages/paypal-commerce-integration/src/paypal-commerce-types.ts
Added PayPalCommerceCreditCardsPaymentStrategy to paypal-commerce-integration package
We are moving related to paypal commerce code from core package to paypal-commerce-integration package, to avoid any custom code in core. 
Unit tests
Manual tests
CI tests
=> refactor(payment): PAYPAL-1893 added PayPalCommerceCreditCardsPaymentStrategy to paypal-commerce-integration package

packages/core/src/checkout-buttons/strategies/amazon-pay-v2/amazon-pay-v2-button-options.ts, packages/core/src/checkout-buttons/strategies/amazon-pay-v2/amazon-pay-v2-button-strategy.spec.ts, packages/core/src/checkout-buttons/strategies/amazon-pay-v2/amazon-pay-v2-button-strategy.ts, packages/core/src/checkout-buttons/strategies/amazon-pay-v2/amazon-pay-v2-button.mock.ts, packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-processor.ts, packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2.ts
Added ability to change style for amazonpay button from Page Builder on PDP
To make amazon SPB customisable 
@bigcommerce/checkout @bigcommerce/payments @bc-peng @animesh1987
=> feat(payment): PAYPAL-2004 added ability to change style for amazonpay button

.circleci/config.yml
Update resource class for test-packages job in CI
At the moment the job fails intermittently, as CPU/memory is maxed out 
- CI
=> chore(common): CHECKOUT-7279 Update resource class for running tests

packages/payment-integrations-test-utils/src/test-utils/billing-address.mock.ts, packages/payment-integrations-test-utils/src/test-utils/index.ts
Added billing address mock to payment-integrations-test-utils package
To have an ability to use billing address mock in different integration packages
CI tests
=> refactor(payment): PAYPAL-000 added billing address mock to payment-integrations-test-utils package

packages/apple-pay-integration/src/apple-pay-button-strategy.ts
Added className attribute
To make applepay button styles configurable from page builder
=> feat(payment): PAYPAL-2195 added buttonClassName

packages/core/src/checkout-buttons/strategies/googlepay/googlepay-braintree-button-strategy.spec.ts, packages/core/src/checkout-buttons/strategies/googlepay/googlepay-button-options.ts, packages/core/src/checkout-buttons/strategies/googlepay/googlepay-button-strategy.ts, packages/core/src/checkout-buttons/strategies/googlepay/googlepay-button-types.ts, packages/core/src/customer/strategies/googlepay/googlepay-customer-strategy.ts, packages/core/src/payment/strategies/googlepay/googlepay-adyenv2-initializer.ts, packages/core/src/payment/strategies/googlepay/googlepay-adyenv3-initializer.ts, packages/core/src/payment/strategies/googlepay/googlepay-authorizenet-initializer.ts, packages/core/src/payment/strategies/googlepay/googlepay-bnz-initializer.ts, packages/core/src/payment/strategies/googlepay/googlepay-braintree-initializer.ts, packages/core/src/payment/strategies/googlepay/googlepay-braintree.ts, packages/core/src/payment/strategies/googlepay/googlepay-checkoutcom-initializer.ts, packages/core/src/payment/strategies/googlepay/googlepay-cybersourcev2-initializer.ts, packages/core/src/payment/strategies/googlepay/googlepay-orbital-initializer.ts, packages/core/src/payment/strategies/googlepay/googlepay-payment-processor.spec.ts, packages/core/src/payment/strategies/googlepay/googlepay-payment-processor.ts, packages/core/src/payment/strategies/googlepay/googlepay-payment-strategy.ts, packages/core/src/payment/strategies/googlepay/googlepay-stripe-initializer.ts, packages/core/src/payment/strategies/googlepay/googlepay-stripe-upe-initializer.ts, packages/core/src/payment/strategies/googlepay/googlepay.mock.ts, packages/core/src/payment/strategies/googlepay/googlepay.ts
Fixed google pay button for safari and mozilla
Google pay button didn't work on PDP in Safari and Mozilla. Safari and Mozilla showed developer issue. The reason was that we need to loadPaymentData from googleClient before any API calls. 
So we are passing to google client creation
```
paymentDataCallbacks: {
onPaymentDataChanged(callbackTrigger): // callback that triggers multiple times (we usecallbackTrigger  === INITIALIZE to createBuyNowCart) and then return newTransactionInfo object that contains new totalPrice and googlepay popup being updated with new price
},
```
Such way we are avoiding issue that doesn't allow us to make api right after click on googlepay button. 
Tested on Dev And Integration
https://user-images.githubusercontent.com/56301104/230553647-a8740498-6e09-4550-86ba-afb …
=> feat(payment): PAYPAL-2050 fixed google pay button for safari and mozilla

packages/payment-integrations-test-utils/src/index.ts
Added export for getBillingAddress method in payment-integration-test-utils
To make an ability to use this method in different integration packages
Unit tests
=> refactor(payment): PAYPAL-0000 added export for getBillingAddress method in payment-integration-test-utils

packages/paypal-commerce-integration/src/index.ts, packages/paypal-commerce-integration/src/paypal-commerce-alternative-methods/create-paypal-commerce-alternative-methods-payment-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-alternative-methods/create-paypal-commerce-alternative-methods-payment-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-alternative-methods/paypal-commerce-alternative-methods-payment-initialize-options.ts, packages/paypal-commerce-integration/src/paypal-commerce-alternative-methods/paypal-commerce-alternative-methods-payment-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-alternative-methods/paypal-commerce-alternative-methods-payment-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-integration-service.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-integration-service.ts, packages/paypal-commerce-integration/src/paypal-commerce-request-sender.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-request-sender.ts, packages/paypal-commerce-integration/src/paypal-commerce-types.ts
Added PayPalCommerceAlternativeMethodsPaymentStrategy to paypal-commerce-integration package
As part of paypal commerce code migration from core package to paypal-commerce-integration package
Unit tests
Manual tests
=> refactor(payment): PAYPAL-1894 added PayPalCommerceAlternativeMethodsPaymentStrategy to paypal-commerce-integration package

packages/paypal-commerce-integration/src/index.ts, packages/paypal-commerce-integration/src/paypal-commerce-venmo/create-paypal-commerce-venmo-payment-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-venmo/create-paypal-commerce-venmo-payment-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-venmo/paypal-commerce-venmo-payment-initialize-options.ts, packages/paypal-commerce-integration/src/paypal-commerce-venmo/paypal-commerce-venmo-payment-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-venmo/paypal-commerce-venmo-payment-strategy.ts
Added PayPalCommerceVenmo payment strategy to paypal-commerce-integration package
As part of paypal commerce code migration from core package to paypal-commerce-integration package
Unit tests
CI tests
=> refactor(payment): PAYPAL-2365 added PayPalCommerceVenmo payment strategy to paypal-commerce-integration package

packages/core/src/payment/strategies/braintree/braintree-payment-processor.ts, packages/core/src/payment/strategies/braintree/braintree-paypal-payment-strategy.spec.ts, packages/core/src/payment/strategies/braintree/braintree-paypal-payment-strategy.ts
Added `shippingAddressEditable` option to Braintree payment configuration.
`shippingAddressEditable` is optional, because it is `true` by default on Braintree side
To remove an ability to change shipping address by shoppers who use braintree in payment section of checkout page
Unit tests
Manual tests
Before:
https://user-images.githubusercontent.com/25133454/234507334-8419ef8d-8660-4fd4-9d9b-d5484a67ecba.mov
After:
https://user-images.githubusercontent.com/25133454/234507271-46fd0aa1-8cf2-4a74-989b-80eb4bec95e4.mov
=> fix(payment): PAYPAL-2036 added shippingAddressEditable option to Braintree payment configuration

packages/bluesnap-direct-integration/src/bluesnap-direct-ecp-payment-strategy.spec.ts, packages/bluesnap-direct-integration/src/bluesnap-direct-ecp-payment-strategy.ts, packages/bluesnap-direct-integration/src/create-bluesnap-direct-credit-card-payment-strategy.ts, packages/bluesnap-direct-integration/src/create-bluesnap-direct-ecp-payment-strategy.spec.ts, packages/bluesnap-direct-integration/src/create-bluesnap-direct-ecp-payment-strategy.ts, packages/bluesnap-direct-integration/src/index.ts, packages/bluesnap-direct-integration/src/is-bluesnap-direct-ecp-instrument.ts, packages/core/src/order/order-request-body.ts, packages/core/src/payment/payment.ts, packages/payment-integration-api/src/index.ts, packages/payment-integration-api/src/order/order-request-body.ts, packages/payment-integration-api/src/payment/index.ts, packages/payment-integration-api/src/payment/payment.ts
Add a payment strategy for [ACH/ECP with BlueSnap](https://developers.bluesnap.com/reference/ach-ecp).
**UPDATE:** Also reverted #1917 due to #1946 which solved the problem.
To offer shoppers an alternative to credit card payments.
https://user-images.githubusercontent.com/4843328/227052142-e4caff0a-a9c8-4458-a039-64af68b77e34.mp4
👉 https://github.com/bigcommerce/checkout-js/pull/1218
[INT-7173]: https://bigcommercecloud.atlassian.net/browse/INT-7173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(payment): INT-7173 BlueSnapDirect: Create payment strategy for ACH/ECP

packages/braintree-integration/src/braintree-integration-service.ts, packages/braintree-integration/src/braintree-paypal/braintree-paypal-customer-strategy.spec.ts, packages/braintree-integration/src/braintree-paypal/braintree-paypal-customer-strategy.ts, packages/braintree-integration/src/braintree.ts, packages/core/src/checkout-buttons/strategies/braintree/braintree-paypal-button-strategy.spec.ts, packages/core/src/checkout-buttons/strategies/braintree/braintree-paypal-button-strategy.ts, packages/core/src/checkout-buttons/strategies/braintree/braintree-paypal-credit-button-strategy.spec.ts, packages/core/src/checkout-buttons/strategies/braintree/braintree-paypal-credit-button-strategy.ts, packages/core/src/customer/strategies/braintree/braintree-paypal-credit-customer-strategy.spec.ts, packages/core/src/customer/strategies/braintree/braintree-paypal-credit-customer-strategy.ts, packages/core/src/payment/strategies/braintree/braintree-sdk-creator.ts, packages/core/src/payment/strategies/braintree/braintree.ts
Fixed PayLater SPB. Added 'enable-funding' field to getPaypalCheckout request in order to display PayLater SPB properly
Button didn't display for EUR currency for Germany
BCAPP PR: https://github.com/bigcommerce/bigcommerce/pull/52308
=> feat(payment): PAYPAL-2013 fixed braintree paylater button

package-lock.json, package.json
Bump **bigpay-client-js** to newer version
To keep up to date
https://github.com/bigcommerce/bigpay-client-js/pull/185
...
=> chore(deps): bump @bigcommerce/bigpay-client from 5.22.0 to 5.23.0

packages/core/src/checkout-buttons/checkout-button-options.ts, packages/core/src/checkout-buttons/create-checkout-button-registry.spec.ts, packages/core/src/checkout-buttons/create-checkout-button-registry.ts, packages/core/src/checkout-buttons/strategies/checkout-button-method-type.ts, packages/core/src/checkout-buttons/strategies/googlepay/googlepay-button-strategy.ts, packages/core/src/checkout-buttons/strategies/googlepay/googlepay-button.mock.ts, packages/core/src/checkout-buttons/strategies/googlepay/googlepay-worldpay-access-button-strategy.spec.ts, packages/core/src/customer/create-customer-strategy-registry.ts, packages/core/src/customer/customer-request-options.ts, packages/core/src/customer/strategies/googlepay/googlepay-customer-method-type.ts, packages/core/src/customer/strategies/googlepay/googlepay-customer-mock.ts, packages/core/src/customer/strategies/googlepay/googlepay-customer-strategy.ts, packages/core/src/customer/strategies/googlepay/googlepay-worldpayaccess-customer-strategy.spec.ts, packages/core/src/payment/create-payment-strategy-registry.spec.ts, packages/core/src/payment/create-payment-strategy-registry.ts, packages/core/src/payment/payment-request-options.ts, packages/core/src/payment/payment-strategy-type.ts, packages/core/src/payment/strategies/googlepay/googlepay-payment-strategy.ts, packages/core/src/payment/strategies/googlepay/googlepay-worldpay-access-initializar.spec.ts, packages/core/src/payment/strategies/googlepay/googlepay-worldpay-access-initializer.ts, packages/core/src/payment/strategies/googlepay/googlepay.mock.ts, packages/core/src/payment/strategies/googlepay/index.ts
Created and modified files necessary for google pay initialization. Also unit tests were added.
As a Merchant I want to enable Google Pay with Worldpay Access so that I can offer shoppers Google Pay as a payment method to my shoppers.
https://github.com/bigcommerce/checkout-js/pull/1263
@bigcommerce/checkout @bigcommerce/payments  
[INT-7573]: https://bigcommercecloud.atlassian.net/browse/INT-7573?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(payment): INT-7573 Create Access Worldpay GooglePay strategy

packages/paypal-commerce-integration/src/create-paypal-commerce-integration-service.spec.ts, packages/paypal-commerce-integration/src/create-paypal-commerce-integration-service.ts, packages/paypal-commerce-integration/src/paypal-commerce-alternative-methods/create-paypal-commerce-alternative-methods-button-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-alternative-methods/create-paypal-commerce-alternative-methods-payment-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit-card/create-paypal-commerce-credit-cards-payment-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/create-paypal-commerce-credit-button-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/create-paypal-commerce-credit-customer-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/create-paypal-commerce-credit-payment-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-venmo/create-paypal-commerce-venmo-button-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-venmo/create-paypal-commerce-venmo-customer-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-venmo/create-paypal-commerce-venmo-payment-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce/create-paypal-commerce-button-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce/create-paypal-commerce-customer-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce/create-paypal-commerce-payment-strategy.ts
Payment strategies have been refactored by moving  PayPalCommerceIntegrationService method in the separate file.
To avoid code duplication in several places and make it easier to maintain in the future.
All tests has been passed.
=> refactor(payment): PAYPAL-2414 added PayPalCommerceIntegrationService method creation

packages/bolt-integration/src/bolt-customer-strategy.ts
fix error after initialization Bolt on customer step
This issue blocks payment process on checkout page with Bolt
Before:
After:
Unit test and manual testing
=> fix(payment): BOLT-577 Bolt initialization error on customer step

packages/core/src/payment/strategies/googlepay/googlepay-payment-strategy.spec.ts, packages/core/src/payment/strategies/googlepay/googlepay-payment-strategy.ts
Fixed Google pay 3ds2 redirect flow for the adyen v3
3ds redirect doesn't work with adyen v3 googlepay
=> fix(checkout): PI-101 Googlepay 3ds2 redirect flow for the adyen v3

packages/core/src/payment/instrument/instrument.mock.ts, packages/core/src/payment/instrument/instrument.ts, packages/core/src/payment/instrument/map-to-bank-instrument.spec.ts, packages/core/src/payment/instrument/map-to-bank-instrument.ts
Updated `AccountInstrument` type
`BankInstrument` doesn't have an `externalId`, it is the legacy
`externalId` can only have an instrument with type `account`
All tests passed 
=> feat(payment): PAYPAL-2451 Updated AccountInstrument type

packages/core/src/payment/instrument/index.ts, packages/core/src/payment/instrument/instrument.ts
Renaming instrument
To make it more compatible and ready to use him like common interface for other packages
=> fix(payment): PAYPAL-2451 renaming instrument

packages/core/src/payment/strategies/braintree/braintree-hosted-form.ts, packages/core/src/payment/strategies/braintree/braintree.ts
Add an `internalLabel` for each braintree hosted field
In a Braintree Hosted Form, there is no option to add an `area-label` attribute for each field.
For screen reader uses `internalLabel`
Screen reader can read default values in **hosted form**
You can see it here: https://braintree.github.io/braintree-web/current/module-braintree-web_hosted-fields.html#~field
Default values can change via `internalLabel`
Have been tested with [Google Chrome Screen Reader extension](https://chrome.google.com/webstore/detail/screen-reader/kgejglhpjiefppelpmljglcjbhoiplfn?hl=en).
=> feat(payment): PAYPAL-2560 Add internalLabel for braintree hosted form

packages/paypal-commerce-integration/src/paypal-commerce-alternative-methods/paypal-commerce-alternative-methods-payment-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-alternative-methods/paypal-commerce-alternative-methods-payment-strategy.ts
Remove unnecessary code for `paypal-commerce-alternative-methods-payment-strategy.ts` to prevent loading redundant `Credit cart` filed in payments list on Checkout by calling `checkoutService.loadPaymentMethod`
To fix problem with appearing redundant method
https://github.com/bigcommerce/checkout-sdk-js/assets/99336044/db322966-fd49-49be-9c0c-65826cf15d8e
=> fix(payment): PAYPAL-2552 Wrong Load of Credit card filed on Payment step of checkout page

packages/paypal-commerce-integration/src/paypal-commerce-venmo/paypal-commerce-venmo-payment-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-venmo/paypal-commerce-venmo-payment-strategy.ts
We should inform the user that PayPal Venmo does not supports in theirs region instead of giving users an ability to continue what causes an order creation error on submit.
Because the order creation error occurs when the users try to submit order in regions where PayPal Venmo is not eligible.
Unit tests
Manual tests
=> fix(payment): PAYPAL-2575 fixed the issue with PayPalCommerceVenmo button eligibility

packages/braintree-integration/src/braintree-integration-service.spec.ts, packages/braintree-integration/src/braintree-integration-service.ts, packages/braintree-integration/src/braintree-local-payment-methods/braintree-local-methods-options.ts, packages/braintree-integration/src/braintree-local-payment-methods/braintree-local-methods-payment-strategy.spec.ts, packages/braintree-integration/src/braintree-local-payment-methods/braintree-local-methods-payment-strategy.ts, packages/braintree-integration/src/braintree-local-payment-methods/create-braintree-local-methods-payment-strategy.spec.ts, packages/braintree-integration/src/braintree-local-payment-methods/create-braintree-local-methods-payment-strategy.ts, packages/braintree-integration/src/braintree-script-loader.spec.ts, packages/braintree-integration/src/braintree-script-loader.ts, packages/braintree-integration/src/braintree.mock.ts, packages/braintree-integration/src/braintree.ts, packages/braintree-integration/src/index.ts
Created payment strategy for braintree local methods
To add ability to submit order and payment via braintree local methods
=> feat(payment): PAYPAL-2449 added braintree-local-methods payment strategy

packages/adyen-integration/src/adyenv3/adyenv3-payment-strategy.spec.ts, packages/adyen-integration/src/adyenv3/adyenv3-payment-strategy.ts, packages/adyen-integration/src/adyenv3/adyenv3.ts
Adding to Adyen component, the Klarna Widget configuration, so Klarna widget will appear when customer wants to pay with Klarna.
To enable Klarna widget
Videos showing actions after clicking on "CONTINUE WITH KLARNA" button.
Before changes:
https://github.com/bigcommerce/checkout-sdk-js/assets/130039975/415e84bb-9403-4c66-b19e-74ad1bcb5d1c
After changes:
https://github.com/bigcommerce/checkout-sdk-js/assets/130039975/1a0d96f5-b6c2-426a-a49f-89fd9bb20729
=> feat(payment): PI-88 [Adyen] Klarna widget update

packages/core/src/customer/strategies/stripe-upe/stripe-upe-customer.mock.ts, packages/core/src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.spec.ts, packages/core/src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.ts, packages/core/src/payment/strategies/stripe-upe/stripe-upe.mock.ts, packages/core/src/payment/strategies/stripe-upe/stripe-upe.ts, packages/core/src/shipping/strategies/stripe-upe/stripe-upe-shipping.mock.ts
The payment intent is retrieved if an error is caught at the time of confirming the payment
Some cards with 3DS2 skip the 3ds verification https://site-admin.stripe.com/guides/strong-customer-authentication#exemptions-to-strong-customer-authentication  which is causing an error to occur on the frontend but the charges are being completed on Stripe's side.
https://github.com/bigcommerce/checkout-sdk-js/assets/69487174/98df6726-587b-4ed8-96d1-88ad62f38c79
ping @bigcommerce/payments @bigcommerce/apex-integrations @bigcommerce/kyiv-payments-team
=> fix(payment): INT-7650 retrieve payment intent if an error is caught at the time of confirming the payment

package-lock.json, package.json, packages/braintree-integration/src/braintree-local-payment-methods/braintree-local-methods-payment-strategy.ts
Fixed preloader  in braintree lpm strategy and bumped bigpay-client-js version
When click cancel on LPM popup preloader doesn't disappear 
Tested on dev and integration env
=> feat(payment): PAYPAL-2449 fixed preloader in braintree LPM payment strategy

packages/adyen-integration/src/adyenv2/adyenv2-payment-strategy.spec.ts, packages/adyen-integration/src/adyenv2/adyenv2-payment-strategy.ts, packages/adyen-integration/src/adyenv2/adyenv2.ts, packages/adyen-integration/src/adyenv3/adyenv3-payment-strategy.spec.ts, packages/adyen-integration/src/adyenv3/adyenv3-payment-strategy.ts, packages/adyen-integration/src/adyenv3/adyenv3.ts
Autofilling of holderName to be configurable.
Checkbox is available in Adyen Settings in CP allowing merchants to avoid auto populating of billing name to the card holder name
Checkbox state is enabled by default for both existing and new merchants
At the moment, Merchants using Adyen will see that the credit card holder name is being autofilled from the Shoppers selected billing address at checkout.
We send shopperName from billing address, holderName (from card) is sent directly as is to card form (for Adyen V3)
=> feat(payment): PI-120 Autofilling of holderName to be configurable

packages/core/src/bodl/bodl-emitter-service.ts, packages/core/src/bodl/bodl-events-service.spec.ts, packages/core/src/bodl/bodl-window.ts
- Emit `shipping_details_provided` BODL event with the correct payload
- Emit `payment_details_provided` BODL event with the correct payload
- Update unit tests
As a phase 3 of GA4 integration implementation we need to implement these 2 events. So that we need those events to be emitted by BODL with proper payload. Previously both events were triggered with some minimal mock data
- Manually on dev store
- Unit tests
[DATA-10908]: https://bigcommercecloud.atlassian.net/browse/DATA-10908?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DATA-10928]: https://bigcommercecloud.atlassian.net/browse/DATA-10928?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(analytics): data-10908, data10928 Add shipping and payment details provided events for BODL

packages/core/src/bodl/bodl-events-service.spec.ts
- Fix `BodlEmitterService › #stepCompleted(step) › Shipping Step › tracks products` test
- Fix `BodlEmitterService › #selectedPaymentMethod(method) › tracks products` test
A few tests failed after merging another [PR](https://github.com/bigcommerce/checkout-sdk-js/pull/2019). See the [failed build](https://app.circleci.com/pipelines/github/bigcommerce/checkout-sdk-js/10053/workflows/e8794211-22e8-4b0b-aa7d-14474374c045/jobs/32170). This has happened because the PR was merged without rebasing changes from master previously. There were some changes to the files related to these tests, so they worked locally, but failed once merged into master. This should fix them
Ran unit tests locally
=> fix(test): DATA-10908 Fix failing bodl unit tests

packages/core/src/payment/strategies/braintree/braintree-script-loader.spec.ts, packages/core/src/payment/strategies/braintree/braintree-script-loader.ts, packages/core/src/payment/strategies/braintree/braintree-sdk-creator.ts
Fixed issue when `teardown` is called twice
To fix showing popup with unnecessary message for customer
Additional changes: bump braintree version for loading script to avoid version conflicts
Before
https://github.com/bigcommerce/checkout-sdk-js/assets/99336044/0f1aa84c-6bd5-48d2-95fe-dd6b2120bd81
After
https://github.com/bigcommerce/checkout-sdk-js/assets/99336044/a90d8935-8bad-410a-b34c-a533ca5525a6
=> fix(payment): PAYPAL-2634 fixed issue when teardown is called twice

packages/braintree-integration/src/braintree-script-loader.spec.ts, packages/braintree-integration/src/braintree-script-loader.ts, packages/core/src/payment/strategies/braintree/braintree-script-loader.spec.ts, packages/core/src/payment/strategies/braintree/braintree-script-loader.ts, packages/core/src/payment/strategies/braintree/braintree-sdk-creator.ts
Reverted 
https://github.com/bigcommerce/checkout-sdk-js/pull/2025
https://github.com/bigcommerce/checkout-sdk-js/pull/2017
Due to the incident on production
CI tests
Unit tests
=> fix(payment): PAYPAL-2502 revert braintree sdk bump version

packages/core/src/checkout/checkout-service.spec.ts, packages/core/src/checkout/checkout-service.ts, packages/core/src/extension/errors/extension-not-found-error.ts, packages/core/src/extension/errors/index.ts, packages/core/src/extension/errors/invalid-extension-config-error.ts, packages/core/src/extension/extension-action-creator.spec.ts, packages/core/src/extension/extension-action-creator.ts, packages/core/src/extension/extension-actions.ts, packages/core/src/extension/extension-iframe.spec.ts, packages/core/src/extension/extension-iframe.ts, packages/core/src/extension/extension-selector.spec.ts, packages/core/src/extension/extension-selector.ts, packages/core/src/extension/extension.mock.ts, packages/core/src/extension/extension.ts, packages/core/src/extension/index.ts
- Retrieve all extension configs from the checkout state.
- Render an extension’s iframe based its config.
Efficiently utilize extensions.
- CI checks.
@bigcommerce/checkout @bigcommerce/team-payments
=> feat(checkout): CHECKOUT-7537 Render extensions

packages/core/src/bodl/bodl-emitter-service.ts, packages/core/src/bodl/bodl-events-service.spec.ts, packages/core/src/order/index.ts, packages/core/src/order/order-params.ts, packages/core/src/order/order-request-sender.spec.ts, packages/core/src/order/order-request-sender.ts, packages/core/src/payment/strategies/affirm/affirm-payment-strategy.ts
- Include categories when loading order by default
- Update `BODL` line item transform logic to handle `line.item.categories`
- Update unit tests
1. `BODL` only looked for `categoryNames` in line items. This works for checkout, since the `checkout` request includes `categoryNames` by default. However, for the `order` request, there is no `categoryNames` key in line items, but there is `categories` key instead with different structure. So we need to handle it on BODL end. 2. Another part is that categories were not included for `order` request by default. They were included only for the `affirm-payment-strategy` though. BODL should work with any payment method, and it should include categories for the `purchase` event. So that we need to always include categories when loading order.
- …
=> fix(order): DATA-11056 Populate category names for BODL purchase event

.github/CODEOWNERS, .github/PULL_REQUEST_TEMPLATE.md
Update checkout team github name in codeowners.
Conform to new standards for team names.
N/A
=> chore(common): CHECKOUT-000 Update team name

packages/core/src/bodl/bodl-emitter-service.ts, packages/core/src/bodl/bodl-events-service.spec.ts, packages/core/src/order/index.ts, packages/core/src/order/order-params.ts, packages/core/src/order/order-request-sender.spec.ts, packages/core/src/order/order-request-sender.ts, packages/core/src/payment/strategies/affirm/affirm-payment-strategy.ts
Reverts bigcommerce/checkout-sdk-js#2032
There are some e2e tests in checkout-js failing with this version of sdk. We are going to investigate this with @bc-peng as per discussion with @animesh1987. For now reverting
=> Revert "fix(order): DATA-11056 Populate category names for BODL purchase event"

packages/core/src/payment/strategies/braintree/braintree-sdk-creator.ts
Fixed issue when `teardown` is called twice
To fix showing popup with unnecessary message for customer
Part of rolled back PR [https://github.com/bigcommerce/checkout-sdk-js/pull/2025](https://github.com/bigcommerce/checkout-sdk-js/pull/2025)
=> fix(payments): PAYPAL-2634 fixed issue when teardown is called twice

packages/braintree-integration/src/braintree-paypal-ach/braintree-paypal-ach-payment-strategy.spec.ts, packages/braintree-integration/src/braintree-paypal-ach/braintree-paypal-ach-payment-strategy.ts, packages/braintree-integration/src/braintree.mock.ts
Added braintree ach vaulting instrument confirmation feature
To avoid creating a new instrument with the same data in cases where customer tries to use untrusted vaulting instrument to make Braintree ACH transaction
Unit tests
Manual tests
checkout-js: https://github.com/bigcommerce/checkout-js/pull/1360
=> feat(payment): PAYPAL-2690 added braintree ach vaulting instrument confirmation feature

package-lock.json, package.json, packages/core/src/hosted-form/iframe-content/hosted-input-validator.ts
Closes: #1153 
- Bumps yup to 1.1.1.
- Make the previously implicit dependency on regenerator-runtime explicit
- [CVE-2020-7707: Prototype Pollution in property-expr (Critical severity)](https://github.com/advisories/GHSA-6fw4-hr69-g3rv)
- ✅ Tests pass
=> core(deps): GITHUB-1972 bump yup to 1.1.1

packages/paypal-commerce-integration/src/paypal-commerce-request-sender.ts, packages/paypal-commerce-integration/src/paypal-commerce-types.ts
Added TS interface for response of updateOrder method in paypal-commerce-request-sender.ts
All tests have been passed.
=> feat(payment): PAYPAL-2476 added TS interface for updateOrder method in PPCP request sender

package-lock.json, package.json
Bump @bigcommerce/bigpay-client from v5.24.2 to v5.24.4. Pulls in [these changes](https://github.com/bigcommerce/bigpay-client-js/compare/v5.24.2...v5.24.4). Those are just minor dependency updates and no big changes.
Keeping up to date
CI
=> chore(common): BIG-0 Bump @bigcommerce/bigpay-client from v5.24.2 to v5.24.4

packages/core/src/checkout-buttons/strategies/amazon-pay-v2/amazon-pay-v2-button-strategy.ts, packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-processor.spec.ts, packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-processor.ts
Fix Amazon Pay button for buy now flow on PDP
To keep up-to-date data during the quota creation process
https://github.com/bigcommerce/checkout-sdk-js/assets/99336044/999b12ee-4570-4b08-b912-0c5f2134b4c4
=> fix(payment): PAYPAL-2719 fix amazon pay button for buy now flow

packages/core/src/order/order.ts, packages/core/src/order/orders.mock.ts
This PR adds an `OrderFee` interface and a `fees` field to the `Order` interface in `order.ts`.
This adds some interfaces for fees specific to the Orders domain to provide separation between Checkout and Orders, as each domain's definitions of fees are likely to drift further apart over time.
N/A
@bigcommerce/team-checkout @bigcommerce/team-orders
=> feat(orders): ORDERS-5715 add OrderFee interface, add fees field to Order interface

packages/core/src/bundles/extension.ts, packages/core/src/extension/create-extension-service.ts, packages/core/src/extension/extension-client.ts, packages/core/src/extension/extension-origin-event.ts, packages/core/src/extension/extension-service.spec.ts, packages/core/src/extension/extension-service.ts, packages/core/src/extension/index.ts, packages/core/src/extension/initialize-extension-service.spec.ts, packages/core/src/extension/initialize-extension-service.ts, webpack-common.config.js, webpack.config.js
Add client extension service
Add a client extension service that is shipped out as a separate bundle that extensions can import and use for messaging to and from with checkout.
- CI
=> feat(checkout): CHECKOUT-7595 Add client extension service

packages/braintree-integration/src/braintree-integration-service.spec.ts, packages/braintree-integration/src/braintree-integration-service.ts, packages/braintree-integration/src/braintree-local-payment-methods/braintree-local-methods-payment-strategy.spec.ts, packages/braintree-integration/src/braintree-local-payment-methods/braintree-local-methods-payment-strategy.ts, packages/braintree-integration/src/braintree-local-payment-methods/create-braintree-local-methods-payment-strategy.ts, packages/braintree-integration/src/braintree-paypal-ach/braintree-paypal-ach-payment-strategy.spec.ts, packages/braintree-integration/src/braintree-paypal-ach/braintree-paypal-ach-payment-strategy.ts, packages/braintree-integration/src/braintree-paypal/braintree-paypal-customer-strategy.spec.ts, packages/braintree-integration/src/braintree-paypal/braintree-paypal-customer-strategy.ts, packages/braintree-integration/src/braintree-script-loader.spec.ts, packages/braintree-integration/src/braintree-script-loader.ts, packages/braintree-integration/src/braintree.mock.ts, packages/braintree-integration/src/braintree.ts
Added an ability to switch braintree sdk version to alpha due to the settings in cp
To use braintree sdk apha version if braintree axo feature is enabled
checkout-sdk (core part): https://github.com/bigcommerce/checkout-sdk-js/pull/2065
Unit tests
Manual tests
Screenshots:
=> feat(payment): PAYPAL-2725 added an ability to switch braintree sdk version (package part)

package-lock.json, package.json
Bump bigpay-client version from 5.24.4 to 5.25.1
The release contains:
- dependency updates;
- braintreeacceleratedcheckout to braintree mapper;
To keep bigpay-client-js dependency up to date
Manual tests
Unit tests
Made several orders with different payment methods and everything working as expected
=> chore(payment): PAYPAL-2726 bump bigpay-client version from 5.24.4 to 5.25.1

packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-payment-initialize-options.ts, packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-payment-strategy.spec.ts, packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-payment-strategy.ts, packages/braintree-integration/src/braintree-accelerated-checkout/create-braintree-accelerated-checkout-payment-strategy.spec.ts, packages/braintree-integration/src/braintree-accelerated-checkout/create-braintree-accelerated-checkout-payment-strategy.ts, packages/braintree-integration/src/braintree-integration-service.spec.ts, packages/braintree-integration/src/braintree-integration-service.ts, packages/braintree-integration/src/braintree-script-loader.spec.ts, packages/braintree-integration/src/braintree-script-loader.ts, packages/braintree-integration/src/braintree.mock.ts, packages/braintree-integration/src/braintree.ts, packages/braintree-integration/src/index.ts
Added BraintreeAcceleratedCheckout payment strategy
To be able to use and render Braintree PayPal Connect Component in paywall
Unit tests
Manual tests
=> feat(payment): PAYPAL-2726 added BraintreeAcceleratedCheckout payment strategy

packages/core/src/payment-integration/default-payment-integration-service.spec.ts, packages/core/src/payment-integration/default-payment-integration-service.ts, packages/payment-integration-api/src/payment-integration-service.ts
Add loadCurrentOrder to PaymentIntegrationService
To get ability to use `orderActionCreator.loadCurrentOrder` from PaymentIntegrationService
=> feat(payment): PI-585 Make an ability to use loadCurrentOrder action from core package in integration checkout-sdk packages

packages/core/src/payment/strategies/braintree/braintree-script-loader.spec.ts, packages/core/src/payment/strategies/braintree/braintree-script-loader.ts
Updated braintree sdk to newest alpha version
PayPal provided new alpha version for AXO
Unit tests
Manual tests
=> feat(payment): PAYPAL-2725 updated braintree sdk to newest alpha version (core part)

packages/braintree-integration/src/braintree-integration-service.ts, packages/braintree-integration/src/braintree-script-loader.spec.ts, packages/braintree-integration/src/braintree-script-loader.ts
Updated braintree sdk to newest alpha version
PayPal provided new alpha version for AXO
Unit tests
Manual tests
=> feat(payment): PAYPAL-2725 updated braintree sdk to newest alpha version (package part)

packages/core/src/checkout/checkout-store-state.ts, packages/core/src/checkout/checkouts.mock.ts, packages/core/src/checkout/create-checkout-store-reducer.ts, packages/core/src/checkout/create-internal-checkout-selectors.ts, packages/core/src/checkout/internal-checkout-selectors.ts, packages/core/src/common/error/errors/missing-data-error.ts, packages/core/src/index.ts, packages/core/src/payment-integration/create-payment-integration-selectors.ts, packages/core/src/payment-integration/create-payment-integration-service.ts, packages/core/src/payment-integration/default-payment-integration-service.spec.ts, packages/core/src/payment-integration/default-payment-integration-service.ts, packages/core/src/payment-provider-customer/index.ts, packages/core/src/payment-provider-customer/payment-provider-customer-actions-creator.ts, packages/core/src/payment-provider-customer/payment-provider-customer-actions.ts, packages/core/src/payment-provider-customer/payment-provider-customer-reducer.ts, packages/core/src/payment-provider-customer/payment-provider-customer-selector.ts, packages/core/src/payment-provider-customer/payment-provider-customer-state.ts, packages/core/src/payment-provider-customer/payment-provider-customer.ts, packages/payment-integration-api/src/index.ts, packages/payment-integration-api/src/payment-integration-selectors.ts, packages/payment-integration-api/src/payment-integration-service.ts, packages/payment-integration-api/src/payment-provider-customer/index.ts, packages/payment-integration-api/src/payment-provider-customer/payment-provider-customer.ts, packages/payment-integrations-test-utils/src/test-utils/payment-integration-service.mock.ts
Added PaymentProviderCustomer state
To be able to save provider specific data and use those data in separate strategies.
Unit tests
Manual tests
// Info: the screenshots a bit out dated after the review, but it works almost the same (naming changed)
Here are some screenshots/proofs that it works (hardcoded only for example):
=> feat(payment): PAYPAL-2731 added PaymentProviderCustomer state

packages/core/src/payment-provider-customer/payment-provider-customer.ts, packages/payment-integration-api/src/payment-provider-customer/payment-provider-customer.ts
Updated Braintree Accelerated Checkout Customer interface key naming
To match our naming with PayPal Connect to avoid dev confusion in the future
Unit tests
=> fix(payment): PAYPAL-000 updated Braintree Accelerated Checkout Customer interface key naming

packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-customer-strategy.spec.ts, packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-customer-strategy.ts, packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-payment-strategy.spec.ts, packages/braintree-integration/src/braintree-accelerated-checkout/create-braintree-accelerated-checkout-customer-strategy.spec.ts, packages/braintree-integration/src/braintree-accelerated-checkout/create-braintree-accelerated-checkout-customer-strategy.ts, packages/braintree-integration/src/braintree-integration-service.spec.ts, packages/braintree-integration/src/braintree-integration-service.ts, packages/braintree-integration/src/braintree-local-payment-methods/braintree-local-methods-payment-strategy.spec.ts, packages/braintree-integration/src/braintree-paypal-ach/braintree-paypal-ach-payment-strategy.spec.ts, packages/braintree-integration/src/braintree-paypal/braintree-paypal-customer-strategy.spec.ts, packages/braintree-integration/src/braintree-script-loader.spec.ts, packages/braintree-integration/src/braintree.ts, packages/braintree-integration/src/index.ts, packages/braintree-integration/src/mocks/braintree.mock.ts, packages/braintree-integration/src/mocks/paypal.mock.ts
Added Braintree Accelerated Checkout customer strategy
To authenticate user with PayPal Connect after user clicks on "Continue" (as Guest) or after login
Unit tests
CI tests
Manual tests
=> feat(payment): PAYPAL-2727 added Braintree Accelerated Checkout customer strategy

packages/core/src/checkout/checkout-store-selector.spec.ts, packages/core/src/checkout/checkout-store-selector.ts
Add an ability to use getPaymentProviderCustomer method on the client side
To be able to use getPaymentProviderCustomer method in checkout js project
Unit tests
Manual tests
=> feat(payment): PAYPAL-000 add an ability to use getPaymentProviderCustomer method on the client side

packages/core/src/checkout/checkout-service.spec.ts, packages/core/src/checkout/checkout-service.ts, packages/core/src/checkout/checkout-store-selector.spec.ts, packages/core/src/checkout/checkout-store-selector.ts, packages/core/src/extension/extension-action-creator.spec.ts, packages/core/src/extension/extension-action-creator.ts, packages/core/src/extension/extension-command-handler.ts, packages/core/src/extension/extension-messenger.spec.ts, packages/core/src/extension/extension-messenger.ts, packages/core/src/extension/index.ts
- Task 1: Make `getExtensionByRegion` a public selector to enable `checkout-js` consumption.
- Task 2: Move extension experiment check to `ExtensionService#renderExtension`.
- Task 3: Map command type to handler signature in `handleExtensionCommand`.
Improve code structure and developer experience.
- CI checks.
=> refactor(checkout): CHECKOUT-7634 Improvements for extension

packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-customer-strategy.spec.ts, packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-customer-strategy.ts, packages/core/src/payment-provider-customer/payment-provider-customer.ts, packages/payment-integration-api/src/payment-provider-customer/payment-provider-customer.ts
Added country to each PayPal Connect customer address to use it on client side (BT AXO)
To be able to get country name without any extra effort on client side
Unit tests
Manual tests
=> feat(payment): PAYPAL-2804 added country to each PayPal Connect customer address to use it on client side (BT AXO)

packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-customer-strategy.spec.ts, packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-customer-strategy.ts, packages/braintree-integration/src/braintree-accelerated-checkout/create-braintree-accelerated-checkout-customer-strategy.ts
Save customers data to local storage after authentication (Braintree AXO)
To be able to use PayPal Connect profile data in shipping and billing steps of checkout when customer reloads the page.
Unit tests
Manual tests
=> feat(payment): PAYPAL-2797 save customers data to local storage after authentication (Braintree AXO)

packages/payment-integrations-test-utils/src/test-utils/payment-integration-service.mock.ts
Added getPaymentProviderCustomer method mocks to PIS state mock in payment-integration-test-utils package
To be able to use those methods in test files in integration packages
Unit tests
CI
=> test(payment): PAYPAL-2737 added getPaymentProviderCustomer method mocks to PIS state mock in payment-integration-test-utils package

packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-payment-initialize-options.ts, packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-payment-strategy.spec.ts, packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-payment-strategy.ts, packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-utils.spec.ts, packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-utils.ts
Updated Braintree AXO strategy with vaulted instruments implementation
PayPal team request us to add vaulted instruments implementation to give PayPal Connect customers an ability to use PP saved instruments
Unit tests
Manual tests
=> feat(payment): PAYPAL-2737 updated Braintree AXO strategy with vaulted instruments implementation

packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-utils.spec.ts, packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-utils.ts, packages/braintree-integration/src/braintree.ts, packages/braintree-integration/src/mocks/braintree.mock.ts, packages/core/src/payment-provider-customer/payment-provider-customer.ts, packages/payment-integration-api/src/customer/index.ts, packages/payment-integration-api/src/index.ts, packages/payment-integration-api/src/payment-provider-customer/payment-provider-customer.ts
Updated PayPal Connect address mapper to receive CustomerAddress instead of Address
To avoid interface updates on the client side (checkout-js)
Unit tests
CI
=> feat(payment): PAYPAL-000 updated paypal connect address mapper to receive CustomerAddress instead of Address

packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-customer-strategy.spec.ts, packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-customer-strategy.ts, packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-payment-strategy.spec.ts, packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-payment-strategy.ts, packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-utils.spec.ts, packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-utils.ts, packages/braintree-integration/src/braintree.ts
Added shipping and billing address selected with PayPal AXO address after OTP
I as a customer want to have shipping and billing addresses preselected with data from PayPal Connect Profile to speed up checkout process. Therefore if I want to change the address I can use Edit button, select any address in the Address select component or fill shipping form with new address as well.
Unit tests
Manual tests
https://github.com/bigcommerce/checkout-sdk-js/assets/25133454/c9b4c9d7-0e09-4891-93c0-8ba5760866d1
=> feat(payment): PAYPAL-2828 added shipping and billing address selected with PayPal AXO address after OTP

packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-customer-strategy.spec.ts, packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-customer-strategy.ts, packages/braintree-integration/src/braintree-accelerated-checkout/create-braintree-accelerated-checkout-customer-strategy.ts, packages/braintree-integration/src/braintree.ts
Updated `BraintreeAcceleratedCheckout` customer  strategy with a condition to check when to run PayPal Connect authentication flow in BT customer strategy
We should run PayPal Connect authentication flow for 20% of store shoppers. The calculations to whom we should run authentication flow is implemented on BE side, so the BE should return `shouldRunAuthenticationFlow` flag `true/false` in payment method `initializationData`, when the email set in quota.
Unit tests
Manual tests
=> feat(payment): PAYPAL-2827 add a condition to check when to run PayPal Connect authentication flow in BT customer strategy (A/B testing coverage)

packages/bluesnap-direct-integration/src/bluesnap-direct-3ds.spec.ts, packages/bluesnap-direct-integration/src/bluesnap-direct-3ds.ts, packages/bluesnap-direct-integration/src/bluesnap-direct-credit-card-payment-strategy.spec.ts, packages/bluesnap-direct-integration/src/bluesnap-direct-credit-card-payment-strategy.ts, packages/bluesnap-direct-integration/src/create-bluesnap-direct-credit-card-payment-strategy.ts, packages/bluesnap-direct-integration/src/mocks/bluesnap-direct-sdk.mock.ts, packages/bluesnap-direct-integration/src/types.ts, packages/credit-card-integration/src/credit-card-payment-initialize-options.ts, packages/payment-integrations-test-utils/src/test-utils/payment-integration-service.mock.ts, packages/payment-integrations-test-utils/src/test-utils/payments.mock.ts
Bluesnapdirect 3ds challenge for stored cards without hosted fields
Because 3ds challenge doesn't appear for stored cards without bluesnap hosted fields. That's why we need to implement manual trigger of 3ds challenge for stored card without card number validation
Tested manually/units
=> feat(checkout): PI-286 bluesnapdirect 3ds for stored cards without hosted fields

packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-customer-strategy.spec.ts, packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-customer-strategy.ts
Fixed backup payment method loading for Braintree accelerated checkout strategies
There was an error detected due to the A/B testing feature. When the main payment method (`braintree`) is disabled we should load backup one (`braintreeacceleratedcheckout`), but I forgot to cover case with braintree connect initialization method, that it tries to get payment method that did not loaded before.. So this Pr fixes that issue.
Unit tests
Manual tests
=> fix(payment): PAYPAL-000 fixed backup payment method loading for braintree accelerated checkout strategies

packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-customer-strategy.spec.ts, packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-customer-strategy.ts
Removed unnecessary method call in sign in BT AXO customer strategy
It does not work as we expected, so we don't need this method call anymore
Unit tests
Manual tests
=> refactor(payment): PAYPAL-2730 removed unnecessary method call in sign in BT AXO customer strategy

packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-utils.spec.ts, packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-utils.ts, packages/braintree-utils/src/braintree.ts
Clean up prev provider customer data from checkout state for cases when the customer comes back to customer step and updates an email with new one, that does not recognized in PP Connect system
Recognized by PP COnnect customer returns to customer step to update the email field -> customer can see the data from PayPal Connect like vaulted instruments in payment step. So we should clean up provider customer data for cases, if the email was changed.
Unit tests
Manual tests
=> fix(payment): PAYPAL-2868 clean up prev provider customer data from checkout state BT AXO

packages/braintree-utils/src/braintree-integration-service.spec.ts, packages/braintree-utils/src/braintree-integration-service.ts, packages/braintree-utils/src/braintree.ts
Added styles for PayPal Connect Credit Card component
All default PayPal Connect Credit Card component styles are ok for us, but we should update white component background and make it transparent to avoid differences between payment paywall and component background colors
Unit tests
Manual tests
=> feat(payment): PAYPAL-2856 added styles for PayPal Connect Credit Card component

packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-utils.spec.ts, packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-utils.ts, packages/braintree-integration/src/braintree-accelerated-checkout/create-braintree-accelerated-checkout-customer-strategy.ts, packages/braintree-integration/src/braintree-accelerated-checkout/create-braintree-accelerated-checkout-payment-strategy.ts
Added session id to the local storage after customer's OTP BT AXO
To be able to trigger OTP after customer comes back to checkout page (only for customers who already triggered authentication flow before)
Unit tests
=> feat(payment): PAYPAL-2876 added session id to the local storage after customer's OTP BT AXO

packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-utils.spec.ts, packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-utils.ts, packages/braintree-utils/src/braintree-integration-service.spec.ts, packages/braintree-utils/src/braintree-integration-service.ts, packages/braintree-utils/src/braintree.ts
Added riskCorrelationId to data collector for PayPal Analytics
PayPal wants to match device session id on FE side to match the session with the Analytics data that we send to PayPal on BE side. So we should add riskCorrelationId option to the data collector config to make it works
Unit tests
Here is an example of device data:
`"{"device_session_id":"516559b8ab0214fa7a1648bc8542e2bd","fraud_merchant_id":null,"correlation_id":"9106fa8b-8196-4def-9944-ec3ab79a1f79"}"`
As you can see `correlation_id` is already there.
=> feat(payment): PAYPAL-2853 added riskCorrelationId to data collector for PayPal Analytics

packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-payment-strategy.spec.ts, packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-payment-strategy.ts, packages/braintree-integration/src/braintree-accelerated-checkout/create-braintree-accelerated-checkout-customer-strategy.ts, packages/braintree-integration/src/braintree-accelerated-checkout/create-braintree-accelerated-checkout-payment-strategy.ts
Trigger authentication flow on BT AXO payment method initialization for customers who triggered the flow before and leave the checkout page to update the cart or reload a page.
To get valid PayPal Connect Profile data and you them in checkout flow
Unit tests
Manual tests
https://github.com/bigcommerce/checkout-sdk-js/assets/25133454/28e62fc6-11b2-41e7-8079-0458f6130061
=> feat(payment): PAYPAL-2851 trigger authentication flow on BT AXO payment method initialization

packages/bluesnap-direct-integration/src/bluesnap-direct-constants.ts, packages/bluesnap-direct-integration/src/bluesnap-direct-hosted-form.spec.ts, packages/bluesnap-direct-integration/src/bluesnap-direct-hosted-form.ts, packages/bluesnap-direct-integration/src/bluesnap-direct-hosted-input-validator.spec.ts, packages/bluesnap-direct-integration/src/bluesnap-direct-hosted-input-validator.ts
Fixed validation for stored bluesnap direct card verification fields
Due to the absence UI notifications in validation error cases 
manually/units
Before: 
After:
=> fix(checkout): PI-657 fixed validation for stored bluesnap direct card verification fields

packages/core/src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.spec.ts, packages/core/src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.ts
Jira issue: https://bigcommercecloud.atlassian.net/browse/PI-520
As a merchant, I want Address Line and Zip/Post Code responses for failures to manually review orders and see if I want to accept them. Currently, we only provide when they match and not when they don’t - Even though Stripe has the information and sends it via webhooks. 
SportsShoes have requested this information, it's part of their internal fraud review process. Orders can be flagged for review for a number of reasons (e.g. high value order, high risk items etc). Having AVS details helps the staff to decide what to do with the order. 
...
=> feat(checkout): PI-520 Stripe UPE - Provide AVS results

packages/core/src/bodl/create-bodl-service.ts
Fixed the console error on `npm run bundle-dts` command run
It might be better to reduce amount of errors in our development process to did not miss more valuable errors in the future
Manual tests in console
Before:
After:
=> fix(common): PAYPAL-000 fixed the console error on npm run bundle-dts command run

packages/braintree-utils/src/braintree-integration-service.ts
Updated PayPal Connect LS axo value to sandbox
To be able to test PayPal Connect on sandbox env
Unit tests
Manual tests
=> feat(payment): PAYPAL-2888 updated PayPal Connect LS axo value to sandbox

packages/core/src/payment/strategies/braintree/braintree-paypal-payment-strategy.ts
Async call fix
To avoid tokenization error
Before
https://github.com/bigcommerce/checkout-sdk-js/assets/99336044/838a23fc-3370-4871-86fd-58c759b73588
After
https://github.com/bigcommerce/checkout-sdk-js/assets/99336044/ae7a2b4d-3897-427f-ba32-38894b5cb5a4
=> fix(payment): PAYPAL-2881 asynchronous call fix

packages/bluesnap-direct-integration/src/bluesnap-direct-3ds.spec.ts, packages/bluesnap-direct-integration/src/bluesnap-direct-3ds.ts, packages/bluesnap-direct-integration/src/bluesnap-direct-credit-card-payment-strategy.spec.ts, packages/bluesnap-direct-integration/src/bluesnap-direct-credit-card-payment-strategy.ts, packages/bluesnap-direct-integration/src/bluesnap-direct-hosted-form.spec.ts, packages/bluesnap-direct-integration/src/bluesnap-direct-hosted-form.ts, packages/bluesnap-direct-integration/src/bluesnap-direct-script-loader.spec.ts, packages/bluesnap-direct-integration/src/bluesnap-direct-script-loader.ts, packages/bluesnap-direct-integration/src/create-bluesnap-direct-credit-card-payment-strategy.ts
Fixed not working 3ds challenge for the stored card case when new card form was selected previously
Due to the 3ds issue
BEFORE FIX:
Order placed without 3ds challenge
https://github.com/bigcommerce/checkout-sdk-js/assets/79574476/84800dcf-2365-4840-9429-5ff84cd074fa
AFTER FIX:
Order placed with 3ds challenge
https://github.com/bigcommerce/checkout-sdk-js/assets/79574476/2cf43ce0-642f-4b4a-8eae-648c94417800
=> feat(payment): PI-474 load bluesnap script ONLY if it wasn't loaded before

packages/core/src/config/config.ts, packages/core/src/config/configs.mock.ts, packages/payment-integration-api/src/config/config.ts, packages/payment-integrations-test-utils/src/test-utils/config.mock.ts
Add `isExpressPrivacyPolicy` to `checkoutSettings`.
`checkout-js` can utilize this to display and obtain consent for the privacy policy.
https://github.com/bigcommerce/bigcommerce/pull/54381
- CI checks.
=> feat(checkout): CHECKOUT-7648 Add isExpressPrivacyPolicy

packages/apple-pay-integration/src/apple-pay-payment-strategy.ts
Fixed the issue with braintree initialization in apple pay payment strategy
There was an issue with apple pay braintree initialization due to the async merge of two different PRs in the same time
Unit tests
=> fix(payment): PAYPAL-000 fixed the issue with braintree initialization in apple pay payment strategy

packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-payment-strategy.spec.ts, packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-payment-strategy.ts
Provided customer device data on any place order for BT AXO
To give PayPal an ability to match transaction with the right customer on their end. Otherwise we have some unexpected behaviour while working with BT AXO.
Unit tests
Manual tests
=> feat(payment): PAYPAL-2913 provided customer device data on any place order for BT AXO

packages/braintree-utils/src/braintree-script-loader.spec.ts, packages/braintree-utils/src/braintree-script-loader.ts, packages/core/src/payment/strategies/braintree/braintree-script-loader.spec.ts, packages/core/src/payment/strategies/braintree/braintree-script-loader.ts
Removed unnecessary 2770 experiment because we dont need it here anymore (Braintree SDK)
2770 is a dynamic ab testing experiment, so we don't need to relay on it to set Braintree SDK version
Unit tests
Manual tests
=> fix(payment): PAYPAL-2908 removed unnecessary 2770 experiment because we dont need it here anymore (Braintree SDK)

packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-utils.spec.ts, packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-utils.ts, packages/braintree-utils/src/braintree-integration-service.spec.ts, packages/braintree-utils/src/braintree-integration-service.ts
Covered Braintree AXO sandbox switcher with test mode condition
We should prevent to enable PayPal Connect sandbox mode on production
Unit tests
Manual tests
=> refactor(payment): PAYPAL-2923 covered Braintree AXO sandbox switcher with test mode condition

packages/core/src/shipping/create-shipping-strategy-registry.spec.ts, packages/core/src/shipping/create-shipping-strategy-registry.ts, packages/core/src/shipping/shipping-request-options.ts, packages/core/src/shipping/strategies/braintree/braintree-accelerated-checkout-initialize-options.ts, packages/core/src/shipping/strategies/braintree/braintree-accelerated-checkout-shipping-strategy.spec.ts, packages/core/src/shipping/strategies/braintree/braintree-accelerated-checkout-shipping-strategy.ts, packages/core/src/shipping/strategies/braintree/index.ts
Create shipping strategy for Braintree Accelerated checkout
To check logged in user and show OTP modal for PayPal Connect users
https://github.com/bigcommerce/checkout-sdk-js/assets/9430298/dfb0a7d0-8186-4744-bccc-f8a41b765652
=> feat(payment): PAYPAL-2728 create shipping strategy for Braintree AXO

packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-utils.spec.ts, packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-utils.ts, packages/braintree-utils/src/braintree.ts, packages/braintree-utils/src/index.ts, packages/braintree-utils/src/mocks/braintree.mock.ts
Preset billing address fields from PP card info
To setup correct billing address for preset payment instrument
Manually tested and unit test
https://github.com/bigcommerce/checkout-sdk-js/assets/9430298/2c14a897-b3e7-412a-bb33-4a5759a6ccf7
=> feat(payment): PAYPAL-2932 add PayPal billing addresses

.github/CODEOWNERS
Extended codeowners file with `team-integrations` and `team-paypal` ownership
To make `team-integrations` and `team-paypal` able to work with integrations as owners
=> chore(payment): PAYPAL-000 extended codeowners file with team-integrations and team-paypal

packages/core/src/checkout-buttons/strategies/braintree/braintree-paypal-button-strategy.spec.ts, packages/core/src/checkout-buttons/strategies/braintree/braintree-paypal-button-strategy.ts, packages/core/src/checkout-buttons/strategies/braintree/braintree-paypal-credit-button-strategy.ts, packages/core/src/checkout-buttons/strategies/braintree/braintree-venmo-button-strategy.ts, packages/core/src/payment/strategies/braintree/braintree-script-loader.ts, packages/core/src/payment/strategies/braintree/braintree-sdk-creator.ts, packages/core/src/payment/strategies/googlepay/googlepay-braintree-initializer.ts
Fixed the issue with braintree buttons rendering on PDP page.
There was a problem with getting `storeConfig` to get access to feature flags. Therefore we should change `getStoreConfigOrThrow` to more calm `getStoreConfig` to get store config if it's available. It does not brake anything, because the reason why we need storeConfig is to understand whenever to load Braintree Alpha version for PayPal Connect that used only on Checkout Page.
Unit tests
Manual tests
Before: 
There are console errors and the braintree buttons failed to render
After:
There are no console errors and the braintree buttons rendered sucessfuly
=> fix(payment): PAYPAL-2928 fixed the issue with braintree buttons rendering on PDP page

packages/paypal-commerce-integration/src/mocks/get-paypal-commerce-payment-method.mock.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-customer-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-customer-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-payment-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-types.ts, packages/paypal-commerce-integration/src/paypal-commerce-venmo/paypal-commerce-venmo-customer-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-venmo/paypal-commerce-venmo-customer-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-venmo/paypal-commerce-venmo-payment-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-customer-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-customer-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-payment-strategy.ts
Added PayPal payment buttons styles coming from backend in:
- PDP (product details page);
- Cart page + mini cart popup (in header) + Add to cart (PDP add to cart modal);
- Checkout on top;
- Checkout in payment step (Complete order button);
This PR depends to https://github.com/bigcommerce/bigcommerce/pull/52892
Because now we don't have a possibility to change PayPal styles in different places.
=> feat(payment): PAYPAL-2576 added specific button styles for each PayPal buttons

packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-processor.ts, packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2.mock.ts
The incorrect Amazon Pay button was added to the platform. It needs to be switched to the button with microtext across all BC’s surfaces (PDP, cart page, checkout page etc). 
Per Amazon team, button with microtext performs better conversion rates.
Before:
Amazon Pay button without microtext:
Expected result:
Amazon Pay button with microtext is displayed across all BC surfaces (PDP, cart page, checkout page etc)
=> feat(payment): PI-567 Amazon Pay Button needs to be changed to one with microtext

packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-payment-strategy.ts
Prefill full phone number in BT AXO instead of slicing country code num
we should pass full phone number to the BT AXO CC form, because PayPal will remove hardcoded country code from their implementation.
Unit tests
Manual tests
=> fix(payment): PAYPAL-3061 prefill full phone number in BT AXO instead of slicing country code num

packages/core/src/payment/strategies/braintree/braintree.ts, packages/core/src/payment/strategies/googlepay/googlepay-braintree-initializer.ts, packages/core/src/payment/strategies/googlepay/googlepay-payment-processor.ts, packages/core/src/payment/strategies/googlepay/googlepay-payment-strategy.ts, packages/core/src/payment/strategies/googlepay/googlepay.ts
Fix an issue with 3DSecure
3DSecure doesn't work without the `bin` parameter
Example with payment strategy:
https://github.com/bigcommerce/checkout-sdk-js/assets/99336044/94cfe710-0667-4ba2-baea-6bdf1018fb99
Tested for client and button strategy
=> feat(payment): PAYPAL-2926 Unable to place order via GooglePay with 3D secure 

packages/core/src/payment/strategies/braintree/braintree.ts
=> chore(payment): PAYPAL-000 fix interface

packages/paypal-commerce-integration/src/paypal-commerce-integration-service.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-integration-service.ts
Checkout page crashing fixed
Because sometimes an error and blank page appears when proceeding past Billing/Shipping step.
=> feat(payment): PAYPAL-2987 checkout page crashing fixed

packages/core/src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.spec.ts, packages/core/src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.ts
Check if container exists before mounting payment fields inside.
Because of error when payment provider was switched before current provider had been loaded
https://github.com/bigcommerce/checkout-sdk-js/assets/9430298/18ed0b4f-a2d6-42e0-bb4f-e90fa558ecb6
=> fix(payment): PI-758 check if Stripe container exists before mount

packages/paypal-commerce-integration/src/paypal-commerce-alternative-methods/create-paypal-commerce-ratepay-payment-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-alternative-methods/paypal-commerce-alternative-methods-payment-initialize-options.ts, packages/paypal-commerce-integration/src/paypal-commerce-alternative-methods/paypal-commerce-ratepay-payment-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-alternative-methods/paypal-commerce-ratepay-payment-strategy.ts
Added loading spinner to ratepay strategy
To show loading process
=> feat(payment): PAYPAL-2946 added loading spinner to ratepay strategy

packages/core/src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.spec.ts, packages/core/src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.ts
Add Cart ID property to Stripe UPE payment submit request
Need this data to fix duplication of Stripe payment intents on BigPay side
=> feat(payment): PI-889 Add cart ID to stripe upe payment submit

packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-utils.spec.ts, packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-utils.ts
Added sessionId to local storage even for unrecognised guest users for Gary flow Braintree AXO
To call `lookup` method for each cases when the user probably might use PayPal Connect. This fix fixes the behaviour with Braintree PayPal Connect Credit Card form for guest users who leave and return to the checkout page after passing customer step.
Unit tests
Manual tests
Before:
https://github.com/bigcommerce/checkout-sdk-js/assets/25133454/0e93b646-cbf2-4f2b-907b-9ef45b417efa
After:
https://github.com/bigcommerce/checkout-sdk-js/assets/25133454/6e16f6df-0aac-43b6-9999-fb0747be156e
=> feat(payment): PAYPAL-3098 added sessionId to local storage even for unrecognised guest users for Gary flow Braintree AXO

packages/core/src/payment/strategies/braintree/braintree-credit-card-payment-strategy.spec.ts, packages/core/src/payment/strategies/braintree/braintree-credit-card-payment-strategy.ts
Removed the logic that stops trigger 3DS for Braintree nonHostedForm СС for transactions when the customer saves the instrument for future usage.
Some merchants had an issue with triggering 3DS for cases when the customer wants to place an order and save the card data for future usages. Therefore there was an error during placing order, because 3DS verification is not passed for current transaction.
Unit tests
Manual tests
Before:
https://github.com/bigcommerce/checkout-sdk-js/assets/25133454/2fd82db6-24d6-4802-9d5d-dd33287a629f
After:
https://github.com/bigcommerce/checkout-sdk-js/assets/25133454/e8cb6fd5-4f5c-4c9a-a9fa-7328583927b8
=> fix(payment): PAYPAL-2986 trigger 3DS for Braintree when the HostedForm feature turned off

packages/paypal-commerce-integration/src/paypal-commerce-alternative-methods/paypal-commerce-alternative-methods-payment-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-alternative-methods/paypal-commerce-alternative-methods-payment-strategy.ts
Polling mechanism removed from PPCP APM.
Because we don't need this method anymore.
=> feat(payment): PAYPAL-2507 polling mechanism removed from PPCP APM

packages/core/src/customer/create-customer-strategy-registry.ts, packages/google-pay-integration/src/factories/customer/create-google-pay-braintree-customer-strategy.spec.ts, packages/google-pay-integration/src/factories/customer/create-google-pay-braintree-customer-strategy.ts, packages/google-pay-integration/src/index.ts
Move googlepay-braintree from core to google-pay-integration package
To separate the logic of integrations
https://github.com/bigcommerce/checkout-sdk-js/assets/99336044/e7d2bc2a-3bfc-48d3-9b0b-24f9f8f20f72
=> feat(payment): PAYPAL-3056 GP Braintree customer strategy

packages/braintree-integration/src/braintree-paypal/braintree-paypal-customer-strategy.spec.ts, packages/braintree-integration/src/braintree-paypal/braintree-paypal-customer-strategy.ts, packages/core/src/customer/strategies/braintree/braintree-paypal-credit-customer-strategy.spec.ts, packages/core/src/customer/strategies/braintree/braintree-paypal-credit-customer-strategy.ts, packages/payment-integration-api/src/checkout-buttons/default-checkout-button-height.ts, packages/payment-integration-api/src/checkout-buttons/index.ts, packages/payment-integration-api/src/index.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-customer-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-customer-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-venmo/paypal-commerce-venmo-customer-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-venmo/paypal-commerce-venmo-customer-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-customer-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-customer-strategy.ts
Updated all PayPal buttons on checkout page to have the same default button height
We have different buttons height for different providers like google pay, paypal commerce, braintree, apple pay buttons and etc. We should make all buttons with the same height to reduce styling mismatch.
Unit tests
=> fix(payment): PAYPAL-3090 updated all paypal buttons on checkout page to have the same default button height

packages/squarev2-integration/src/squarev2-payment-strategy.spec.ts, packages/squarev2-integration/src/squarev2-payment-strategy.ts
Added `vault_payment_instrument` and `set_as_default_stored_instrument` to `submitPayment` payload in Square v2 payment strategy.
[PI-633](https://bigcommercecloud.atlassian.net/browse/PI-633)
As a part of stored credit cards implementation for Square v2.
manual + unit tests
[PI-633]: https://bigcommercecloud.atlassian.net/browse/PI-633?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(payment): PI-633 add vaulted instrument data to square v2 payment strategy

packages/paypal-commerce-integration/src/paypal-commerce-ratepay/paypal-commerce-ratepay-payment-strategy.ts
Fixed date of birth ratepay field processing
To send correct data
**Before:**
**After:**
=> feat(payment): PAYPAL-00 hotfix ratepay date of birth field data

packages/paypal-commerce-integration/src/paypal-commerce-ratepay/paypal-commerce-ratepay-payment-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-ratepay/paypal-commerce-ratepay-payment-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-types.ts
Stop polling mechanism when corresponding status recieved
To cancel polling calls
Tested on dev and integration environment
=> feat(payment): PAYPAL-3146 stop polling mechanism when corresponding status recieved

packages/core/src/payment/strategies/braintree/braintree-paypal-payment-strategy.spec.ts, packages/core/src/payment/strategies/braintree/braintree-paypal-payment-strategy.ts
=> feat(payment): PAYPAL-3133 messaging logo type to be set to 'inline' for checkout paywall page

packages/core/src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.spec.ts, packages/core/src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.ts
Add error message for cases when Stripe has confirmed payment but on BC side something go wrong, additional payment request failed and order status has not changed yet.
To show to shoppers that payment was accepted, but they should wait while BC will receive confirmation from stripe. To prevent unnecessary payment retries from shopper and to prevent double charging.
https://github.com/bigcommerce/checkout-sdk-js/assets/9430298/be187e6d-4107-4dcb-b294-54bd7bcd00c3
=> fix(payment): PI-924 Add additional  message while waiting confirmation from Stripe

packages/paypal-commerce-integration/src/paypal-commerce-credit-card/paypal-commerce-credit-cards-payment-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit-card/paypal-commerce-credit-cards-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-integration-service.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-integration-service.ts, packages/paypal-commerce-integration/src/paypal-commerce-script-loader.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-script-loader.ts, packages/paypal-commerce-integration/src/paypal-commerce-types.ts
We changed a way how we load paypal sdk script to try to avoid zoid issues that occur due to the multiple script loading with different configurations.
Prev implementation had extra step with loading paypal script from CDN that we used to trigger paypal sdk script loading process. So the reason why we update that is to reduce amount of steps to get paypal sdk working properly, plus it might reduce amount of time spent on wallet buttons rendering process.
Unit tests
Manual tests
QA regression
=> refactor(payment): PAYPAL-3164 updated paypal sdk script loading in a new way

packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-payment-strategy.spec.ts, packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-payment-strategy.ts, packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-utils.spec.ts, packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-utils.ts, packages/core/src/shipping/strategies/braintree/braintree-accelerated-checkout-shipping-strategy.spec.ts, packages/core/src/shipping/strategies/braintree/braintree-accelerated-checkout-shipping-strategy.ts
Connect OTP window should not be shown for the shopper anymore in the same cart session until he will click on continue button in customer step
Connect OTP window re-appeared at the shipping/billing step when shopper initially closed it at the customer step of the checkout
Unit tests
Manual tests
https://github.com/bigcommerce/checkout-sdk-js/assets/25133454/2aa189e0-3d99-404f-8cbc-00b36bc598f0
=> fix(payment): PAYPAL-3190 updated implementation to avoid trigger OTP if the shopper canceled PayPal Connect OTP window

packages/apple-pay-integration/src/apple-pay-customer-strategy.ts, packages/braintree-integration/src/braintree-paypal/braintree-paypal-customer-strategy.spec.ts, packages/braintree-integration/src/braintree-paypal/braintree-paypal-customer-strategy.ts, packages/core/src/checkout/checkout-service.ts, packages/core/src/customer/strategies/amazon-pay-v2/amazon-pay-v2-customer-strategy.ts, packages/core/src/customer/strategies/braintree/braintree-paypal-credit-customer-strategy.ts, packages/core/src/payment/payment-method-action-creator.spec.ts, packages/core/src/payment/payment-method-action-creator.ts, packages/core/src/payment/payment-method-actions.ts, packages/google-pay-integration/src/google-pay-customer-strategy.spec.ts, packages/google-pay-integration/src/google-pay-customer-strategy.ts, packages/payment-integration-api/src/payment-integration-service.ts
- Add method to load button payment method config in parallel
- Refactor exisiting payment strategies to leverage pre-fetched configs
Right now we have method to fetch button payment method config one at a time in sequence, which are blocking and cause a delay in rendering the buttons. 
Add a method to fetch button configs in parallel so buttons can be rendered quicker.
- CI
- Manual
=> feat(payment): CHECKOUT-7901 Add method to load button payment method config in parallel

packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-customer-initialize-options.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-customer-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-customer-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-types.ts, packages/paypal-commerce-integration/src/paypal-commerce-venmo/paypal-commerce-venmo-customer-initialize-options.ts, packages/paypal-commerce-integration/src/paypal-commerce-venmo/paypal-commerce-venmo-customer-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-venmo/paypal-commerce-venmo-customer-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-customer-initialize-options.ts, packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-customer-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-customer-strategy.ts
Added onClick callback for each PayPalCommerce customer strategy
To be able to track wallet button click event for buttons implemented in PPCP customer strategies
Unit tests
=> feat(payment): PAYPAL-3229 added onClick callback for each PayPalCommerce customer strategy

packages/braintree-integration/src/braintree-paypal/braintree-paypal-customer-options.ts, packages/braintree-integration/src/braintree-paypal/braintree-paypal-customer-strategy.spec.ts, packages/braintree-integration/src/braintree-paypal/braintree-paypal-customer-strategy.ts, packages/braintree-utils/src/paypal.ts, packages/core/src/customer/strategies/braintree/braintree-paypal-credit-customer-options.ts, packages/core/src/customer/strategies/braintree/braintree-paypal-credit-customer-strategy.spec.ts, packages/core/src/customer/strategies/braintree/braintree-paypal-credit-customer-strategy.ts, packages/core/src/payment/strategies/paypal/paypal-sdk.ts
Added onClick callback for all Braintree customer strategies
To be able to track wallet button click event for buttons implemented in customer strategies
Unit tests
Manual tests
=> feat(payment): PAYPAL-3229 added onClick callback for all Braintree customer strategies

packages/core/src/customer/strategies/googlepay/googlepay-adyenv2-customer-strategy.spec.ts, packages/core/src/customer/strategies/googlepay/googlepay-authorizenet-customer-strategy.spec.ts, packages/core/src/customer/strategies/googlepay/googlepay-bnz-customer-strategy.spec.ts, packages/core/src/customer/strategies/googlepay/googlepay-braintree-customer-strategy.spec.ts, packages/core/src/customer/strategies/googlepay/googlepay-checkoutcom-customer-strategy.spec.ts, packages/core/src/customer/strategies/googlepay/googlepay-customer-initialize-options.ts, packages/core/src/customer/strategies/googlepay/googlepay-customer-mock.ts, packages/core/src/customer/strategies/googlepay/googlepay-customer-strategy.ts, packages/core/src/customer/strategies/googlepay/googlepay-cybersourcev2-customer-strategy.spec.ts, packages/core/src/customer/strategies/googlepay/googlepay-orbital-customer-strategy.spec.ts, packages/core/src/customer/strategies/googlepay/googlepay-stripe-customer-strategy.spec.ts, packages/core/src/customer/strategies/googlepay/googlepay-stripe-upe-customer-strategy.spec.ts, packages/core/src/customer/strategies/googlepay/googlepay-worldpayaccess-customer-strategy.spec.ts, packages/google-pay-integration/src/google-pay-customer-initialize-options.ts, packages/google-pay-integration/src/google-pay-customer-strategy.spec.ts, packages/google-pay-integration/src/google-pay-customer-strategy.ts
Added onClick callback for GooglePay customer strategies
To be able to track GooglePay wallet button click event for buttons implemented in customer strategy
Unit tests
Manual tests
=> feat(payment): PAYPAL-3229 added onClick callback for GooglePay customer strategies

packages/apple-pay-integration/src/apple-pay-customer-initialize-options.ts, packages/apple-pay-integration/src/apple-pay-customer-strategy.spec.ts, packages/apple-pay-integration/src/apple-pay-customer-strategy.ts, packages/apple-pay-integration/src/mocks/apple-pay-wallet-button-mock.ts
Added onClick callback to ApplePayCustomerStrategy
To be able to track Apple Pay wallet button click event
Unit tests
Manual tests
https://github.com/bigcommerce/checkout-sdk-js/assets/25133454/47c6f326-c4ba-48b3-8554-7fdb0f2176a5
=> feat(payment): PAYPAL-3229 added onClick callback to ApplePayCustomerStrategy

packages/core/src/customer/strategies/amazon-pay-v2/amazon-pay-v2-customer-initialize-options.ts, packages/core/src/customer/strategies/amazon-pay-v2/amazon-pay-v2-customer-strategy.spec.ts, packages/core/src/customer/strategies/amazon-pay-v2/amazon-pay-v2-customer-strategy.ts, packages/core/src/customer/strategies/amazon-pay-v2/amazon-pay-v2-customer.mock.ts, packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-processor.spec.ts, packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-processor.ts, packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2.ts
Added onClick callback to AmazonPay customer strategy
To be able to track wallet button click event for button implemented in customer strategy
Unit tests
Manual tests
=> feat(payment): PAYPAL-3229 added onClick callback to AmazonPay customer strategy

packages/paypal-commerce-integration/src/paypal-commerce-ratepay/paypal-commerce-ratepay-payment-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-ratepay/paypal-commerce-ratepay-payment-strategy.ts
Fixed phone country code field
To send correct data
=> feat(payment): PAYPAL-3281 fixed phone country code field

packages/google-pay-integration/src/gateways/google-pay-gateway.ts, packages/google-pay-integration/src/google-pay-paypal-commerce/google-pay-paypal-commerce-gateway.spec.ts, packages/google-pay-integration/src/google-pay-paypal-commerce/google-pay-paypal-commerce-gateway.ts
We need to add dynamic gateway name from PPCP api: `allowedPaymentMethods[0].tokenizationSpecification.parameters.gateway`. 
Because now it works only in sandbox mode because of hardcoded `paypalsb` name.
=> feat(payment): PAYPAL-3337 PPCP GooglePay setGatewayIdentifier added

packages/core/src/form/form-field.ts, packages/payment-integration-api/src/form/form-fields.ts
Added `inputDateFormat` for date input 
To be able to set appropriate date format for Date Picker
=> feat(payment): PAYPAL-3280 added inputDateFormat for date input

packages/bluesnap-direct-integration/src/bluesnap-direct-sepa-payment-strategy.spec.ts, packages/bluesnap-direct-integration/src/bluesnap-direct-sepa-payment-strategy.ts, packages/bluesnap-direct-integration/src/create-bluesnap-direct-sepa-payment-strategy.spec.ts, packages/bluesnap-direct-integration/src/create-bluesnap-direct-sepa-payment-strategy.ts, packages/bluesnap-direct-integration/src/index.ts, packages/bluesnap-direct-integration/src/is-bluesnap-direct-ecp-instrument.ts, packages/bluesnap-direct-integration/src/is-bluesnap-direct-sepa-instrument.ts, packages/core/src/order/order-request-body.ts, packages/core/src/payment/payment.ts, packages/core/src/payment/strategies/checkoutcom-custom/checkoutcom-sepa/checkoutcom-sepa-payment-strategy.ts, packages/payment-integration-api/src/index.ts, packages/payment-integration-api/src/order/order-request-body.ts, packages/payment-integration-api/src/payment/index.ts, packages/payment-integration-api/src/payment/payment.ts
BluesnapDirect SEPA implemantation
https://github.com/bigcommerce/checkout-js/pull/1545
Due the Bluesnap requirement
=> feat(payment): PI-853 BluesnapDirect added Sepa payment strategy

packages/core/src/payment/payment-method-config.ts
Add new option to provider config to control visibility of card holder name field
This option will be used in checkout-js PR:
[https://github.com/bigcommerce/checkout-js/pull/1609](https://github.com/bigcommerce/checkout-js/pull/1609)
=> feat(payment): PI-1148 Hide card holder name from hosted fields form

packages/paypal-commerce-integration/src/mocks/get-paypal-sdk.mock.ts, packages/paypal-commerce-integration/src/paypal-commerce-alternative-methods/create-paypal-commerce-alternative-methods-payment-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-alternative-methods/paypal-commerce-alternative-methods-payment-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-alternative-methods/paypal-commerce-alternative-methods-payment-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-constants.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/create-paypal-commerce-credit-payment-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-payment-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-payment-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-integration-service.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce/create-paypal-commerce-payment-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-payment-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-payment-strategy.ts, packages/ui/src/loading-indicator/loading-indicator-styles.ts, packages/ui/src/loading-indicator/loading-indicator.ts
PPCP Payment step loading indicator keeps after submitting payment.
Also added `setStyleAttribute` method to `LoadingIndicator` class.
Because we don't have any indicators after submitting payment which might be a bad user experience. 
https://github.com/bigcommerce/checkout-sdk-js/assets/130665807/1d1cd74a-2ec5-47a8-b2cf-4da4fd9bc229
=> fix(payment): PAYPAL-3124 PPCP loading indicator keeps after submit

packages/paypal-commerce-integration/src/paypal-commerce-alternative-methods/paypal-commerce-alternative-methods-payment-strategy.ts
Removed error throw from onCancel callback for PayPal AMP payment strategy
To reduce customers confusion about the error on APM popup close
Unit tests
=> fix(payment): PAYPAL-3367 removed error throw from onCancel callback for PayPal AMP payment strategy

.github/CODEOWNERS
Fixed a mistake in codeowners file due BT analytics
To be able to update braintree connect tracker as a codeowner
-
=> fix(payment): PAYPAL-3360 fixed a mistake in codeowners file due BT analytics

packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-customer-strategy.ts, packages/core/src/analytics/braintree-connect-tracker/braintree-connect-tracker-service.ts, packages/core/src/analytics/braintree-connect-tracker/braintree-connect-tracker.spec.ts, packages/core/src/analytics/braintree-connect-tracker/braintree-connect-tracker.ts, packages/core/src/payment/create-payment-strategy-registry.ts, packages/core/src/payment/strategies/braintree/braintree-credit-card-payment-strategy.spec.ts, packages/core/src/payment/strategies/braintree/braintree-credit-card-payment-strategy.ts
- updated Braintree AXO events trigger order;
- added an ability to trigger Braintree Connect event for A/b control group;
Due to updated requirements from PayPal side
Unit tests
Manual tests by BC PayPal team
Manual tests by PayPal team
=> fix(payment): PAYPAL-3660 updated Braintree AXO events trigger order

packages/core/src/payment/instrument/supported-payment-instruments.ts, packages/squarev2-integration/src/squarev2-payment-processor.spec.ts, packages/squarev2-integration/src/squarev2-payment-processor.ts, packages/squarev2-integration/src/squarev2-payment-strategy.spec.ts, packages/squarev2-integration/src/squarev2-payment-strategy.ts, packages/squarev2-integration/src/types.ts
Added new tokens to `submitPayment` payload when storing new credit card.
To enable storing credit cards with 3ds feature.
BE part: https://github.com/bigcommerce/bigpay/pull/7697
Unit + manual tests.
=> feat(payment): PI-1076 add 3ds support for storing cards in square v2

packages/td-bank-integration/.eslintrc.json, packages/td-bank-integration/src/td-online-mart-payment-strategy.spec.ts, packages/td-bank-integration/src/td-online-mart-payment-strategy.ts
Added vaulted credit cards support in checkout page. 
Due to work with TD Bank integration.
=> feat(payment): PI-1021 [TD Bank][FE] Vaulted instruments implementation on Checkout 

package-lock.json, package.json
Update @bigcommerce/bigpay-client from v5.26.0 to v5.26.2
Changelog: https://github.com/bigcommerce/bigpay-client-js/compare/v5.26.0...v5.26.2
That contains various dependabot PRs
Keeping dependencies up to date
CI
=> chore(payment): BIG-0 Update @bigcommerce/bigpay-client from v5.26.0 to v5.26.2

packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-customer-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-customer-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-venmo/paypal-commerce-venmo-customer-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-venmo/paypal-commerce-venmo-customer-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-customer-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-customer-strategy.ts
Added a condition to load PPCP payment methods only if they are not exist in checkout state
There is no need to make extra load for payment method in customer strategy, because it loads in parallel on checkout-js side.
checkout-sdk: https://github.com/bigcommerce/checkout-sdk-js/pull/2258 
Unit tests
CI tests
Manual tests
=> fix(payment): CHECKOUT-7901 added a condition to load PPCP payment methods only if they are not exist in checkout state

packages/paypal-commerce-integration/src/mocks/index.ts, packages/paypal-commerce-integration/src/paypal-commerce-alternative-methods/paypal-commerce-alternative-methods-payment-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-alternative-methods/paypal-commerce-alternative-methods-payment-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-payment-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-ratepay/create-paypal-commerce-ratepay-payment-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-ratepay/paypal-commerce-ratepay-payment-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-venmo/paypal-commerce-venmo-payment-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-venmo/paypal-commerce-venmo-payment-strategy.ts
Fixed eslint warnings in paypal-commerce-integration package.
Also removed unnecessary console.warn - we don't need them anymore
To keep code as clean as possible
Unit tests
Link command run
Before:
After:
=> fix(payment): PAYPAL-000 fixed eslint warnings in paypal-commerce-integration package

packages/td-bank-integration/src/td-online-mart-payment-strategy.spec.ts, packages/td-bank-integration/src/td-online-mart-payment-strategy.ts, packages/td-bank-integration/src/td-online-mart.ts
Add browser info to payments request payload
Need this info for 3DS flow on TD Bank side
unity tests and manually tested
=> feat(payment): PI-1318 TDBank add  browser info

packages/payment-integration-api/src/payment-provider-customer/index.ts, packages/payment-integration-api/src/payment-provider-customer/payment-provider-customer.ts
Updated PaymentProviderCustomer with PPCP AXO related interface
To be able to save PayPalCommerce related PaymentProviderCustomer data into checkout state
Unit tests
Ci tests
Manual test in separate PR with the feature, that uses this interface
=> feat(payment): PAYPAL-3409 updated PaymentProviderCustomer with PPCP AXO related interface

packages/paypal-commerce-integration/src/paypal-commerce-alternative-methods/paypal-commerce-alternative-methods-payment-initialize-options.ts, packages/paypal-commerce-integration/src/paypal-commerce-alternative-methods/paypal-commerce-alternative-methods-payment-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-alternative-methods/paypal-commerce-alternative-methods-payment-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-types.ts
Added `onClick` and `onInit` options to handle validation process
To validate a form with mandatory fields, as for the checkbox "Terms and Conditions"
@bigcommerce/team-payments
=> feat(payment): PAYPAL-3300 Added onClick and onInit options to handle validation process with mandatory terms and conditions

packages/core/src/customer/strategies/amazon-pay-v2/amazon-pay-v2-customer-initialize-options.ts, packages/core/src/customer/strategies/amazon-pay-v2/amazon-pay-v2-customer-strategy.spec.ts, packages/core/src/customer/strategies/amazon-pay-v2/amazon-pay-v2-customer-strategy.ts, packages/core/src/customer/strategies/amazon-pay-v2/amazon-pay-v2-customer.mock.ts, packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-processor.spec.ts, packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-processor.ts, packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2.ts
This reverts commit 2a4e0ec52b76cba5b5b4c0680778cfd8fff82164.
This reverts commit https://github.com/bigcommerce/checkout-sdk-js/commit/2a4e0ec52b76cba5b5b4c0680778cfd8fff82164. 
Due to the https://github.com/bigcommerce/checkout-sdk-js/issues/2310
To fix this issue fast we need to revert commit. For adding working onClick handler on the customer step button need deeper and more time consuming refactoring 
Implementation should be similar to the https://github.com/bigcommerce/checkout-sdk-js/blob/master/packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-processor.ts#L104
[Amazon Docs](https://developer.amazon.com/docs/amazon-pay-checkout/amazon-pay-script.html?environmentSpecificKeys=true#render-the-amazon-pay-button)
Tested manully/units …
=> Revert "feat(payment): PAYPAL-3229 added onClick callback to AmazonPay customer strategy (#2271)"

package-lock.json, package.json
Bump bigpay-client-js to v5.27.0
As part of PPCP AXO develompment
bigpay-client-js: https://github.com/bigcommerce/bigpay-client-js/pull/279
Manual tests
CI
=> chore(payment): PAYPAL-3445 bump bigpay-client-js to v5.27.0

packages/payment-integration-api/src/payment/payment.ts
Updated WithPayPalConnectInstrument interface with an optional order_id
To be able to pass order id in payment payload for successful place order with PPCP AXO payment method
Unit tests
Manual tests
CI
=> feat(payment): PAYPAL-3416 updated WithPayPalConnectInstrument interface with an optional order_id

packages/paypal-commerce-integration/src/index.ts, packages/paypal-commerce-integration/src/paypal-commerce-accelerated-checkout/create-paypal-commerce-accelerated-checkout-customer-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-accelerated-checkout/create-paypal-commerce-accelerated-checkout-payment-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-accelerated-checkout/create-paypal-commerce-accelerated-checkout-payment-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-accelerated-checkout/paypal-commerce-accelerated-checkout-payment-initialize-options.ts, packages/paypal-commerce-integration/src/paypal-commerce-accelerated-checkout/paypal-commerce-accelerated-checkout-payment-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-accelerated-checkout/paypal-commerce-accelerated-checkout-payment-strategy.ts, packages/paypal-commerce-utils/src/mocks/get-paypal-axo-sdk.mock.ts, packages/paypal-commerce-utils/src/mocks/get-paypal-connect-authentication-result.mock.ts, packages/paypal-commerce-utils/src/mocks/index.ts, packages/paypal-commerce-utils/src/paypal-commerce-accelerated-checkout-utils.spec.ts, packages/paypal-commerce-utils/src/paypal-commerce-types.ts
Added PayPalCommerceAcceleratedCheckout payment strategy
To be able to place order with PayPal Connect AXO payment method
Unit tests
Manual tests
CI
https://github.com/bigcommerce/checkout-sdk-js/assets/25133454/84325928-ec6c-4cac-937f-9ea00a3ff180
https://github.com/bigcommerce/checkout-sdk-js/assets/25133454/ab03767d-78da-484d-b137-34c673672d23
=> feat(payment): PAYPAL-3416 added PayPalCommerceAcceleratedCheckout payment strategy

packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-payment-strategy.spec.ts, packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-payment-strategy.ts, packages/braintree-integration/src/map-to-braintree-shipping-address-override.spec.ts, packages/braintree-integration/src/map-to-braintree-shipping-address-override.ts, packages/braintree-utils/src/index.ts, packages/braintree-utils/src/utils/index.ts, packages/braintree-utils/src/utils/is-braintree-accelerated-checkout-customer.spec.ts, packages/braintree-utils/src/utils/is-braintree-accelerated-checkout-customer.ts, packages/core/src/index.ts, packages/core/src/payment-provider-customer/index.ts, packages/core/src/payment-provider-customer/payment-provider-customer-selector.ts, packages/core/src/payment-provider-customer/payment-provider-customer.ts, packages/core/src/payment/strategies/braintree/braintree-credit-card-payment-strategy.ts, packages/core/src/shipping/strategies/braintree/braintree-accelerated-checkout-shipping-strategy.ts, packages/payment-integration-api/src/index.ts, packages/payment-integration-api/src/payment-provider-customer/index.ts, packages/payment-integration-api/src/payment-provider-customer/payment-provider-customer.ts, packages/paypal-commerce-integration/src/paypal-commerce-accelerated-checkout/paypal-commerce-accelerated-checkout-payment-strategy.ts, packages/paypal-commerce-utils/src/index.ts, packages/paypal-commerce-utils/src/utils/index.ts, packages/paypal-commerce-utils/src/utils/is-paypal-commerce-accelerated-checkout-customer.spec.ts, packages/paypal-commerce-utils/src/utils/is-paypal-commerce-accelerated-checkout-customer.ts
Covered PayPal Connect `paymentProviderCustomer` checkout state object with type guards
To avoid any build errors when new paymentProviderCustomer type added
Unit tests
CI
=> refactor(payment): PAYPAL-3466 covered paypal connect paymentProviderCustomer checkout state object with type guards

packages/adyen-integration/src/adyenv2/adyenv2-payment-strategy.spec.ts, packages/adyen-integration/src/adyenv2/adyenv2-payment-strategy.ts, packages/adyen-integration/src/adyenv3/adyenv3-payment-strategy.spec.ts, packages/adyen-integration/src/adyenv3/adyenv3-payment-strategy.ts
FE validation of Blik and SEPA Direct Debit APM’s allow to trigger /payment request when empty strings are provided, so I added a check for empty values.
before:
now:
=> feat(payment): PI-429 [Adyen] Improve FE validation for APMs on checkout

packages/paypal-commerce-utils/src/paypal-commerce-sdk.spec.ts, packages/paypal-commerce-utils/src/paypal-commerce-sdk.ts, packages/paypal-commerce-utils/src/paypal-commerce-types.ts
Update paypal-commerce-sdk configuration
To use PayLater Messages separately
Manual
=> feat(payment): PAYPAL-3470 Update paypal-commerce-sdk configuration to use PayLater Messages separately

packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-payment-strategy.spec.ts, packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-payment-strategy.ts, packages/braintree-integration/src/map-to-braintree-shipping-address-override.spec.ts, packages/braintree-integration/src/map-to-braintree-shipping-address-override.ts, packages/braintree-utils/src/index.ts, packages/braintree-utils/src/utils/index.ts, packages/braintree-utils/src/utils/is-braintree-accelerated-checkout-customer.spec.ts, packages/braintree-utils/src/utils/is-braintree-accelerated-checkout-customer.ts, packages/core/src/index.ts, packages/core/src/payment-provider-customer/index.ts, packages/core/src/payment-provider-customer/payment-provider-customer-selector.ts, packages/core/src/payment-provider-customer/payment-provider-customer.ts, packages/core/src/payment/strategies/braintree/braintree-credit-card-payment-strategy.ts, packages/core/src/shipping/strategies/braintree/braintree-accelerated-checkout-shipping-strategy.ts, packages/payment-integration-api/src/index.ts, packages/payment-integration-api/src/payment-provider-customer/index.ts, packages/payment-integration-api/src/payment-provider-customer/payment-provider-customer.ts, packages/paypal-commerce-integration/src/paypal-commerce-accelerated-checkout/paypal-commerce-accelerated-checkout-payment-strategy.ts, packages/paypal-commerce-utils/src/index.ts, packages/paypal-commerce-utils/src/mocks/get-paypal-connect-authentication-result.mock.ts, packages/paypal-commerce-utils/src/paypal-commerce-accelerated-checkout-utils.spec.ts, packages/paypal-commerce-utils/src/paypal-commerce-accelerated-checkout-utils.ts, packages/paypal-commerce-utils/src/paypal-commerce-types.ts, packages/paypal-commerce-utils/src/utils/index.ts, packages/paypal-commerce-utils/src/utils/is-paypal-commerce-accelerated-checkout-customer.spec.ts, packages/paypal-commerce-utils/src/utils/is-paypal-commerce-accelerated-checkout-customer.ts
Fixed the issue with PaymentProviderCustomer compare type 
checkout-js project build throws an error that PaymentProviderCustomer types does not match the required types that checkout form uses in different places (CustomerAddress instead of AddressRequestBody or Address). So this Pr contains all needed changes to fix the issue.
Unit tests
Manual tests
CI tests
Checkout-js local build success screenshot:
=> fix(payment): PAYPAL-3466 fixed the issue with PaymentProviderCustomer compare type 

packages/paypal-commerce-utils/src/mocks/get-paypal-connect-authentication-result.mock.ts, packages/paypal-commerce-utils/src/paypal-commerce-accelerated-checkout-utils.ts, packages/paypal-commerce-utils/src/paypal-commerce-types.ts
Updated PPCP AXO integration with last changes in PP SDK
To make valid mapping PayPal Connect data to BC data shape
Unit tests
Manual tests
=> refactor(payment): PAYPAL-3467 updated PPCP AXO integration with last changes in PP SDK

packages/core/src/analytics/analytics-step-tracker.spec.ts, packages/core/src/analytics/analytics-step-tracker.ts
- Make `product_id` field a string for `Checkout Started` and `Order Completed` events
- Rename `orderId` field to `order_id` for `Order Completed` event
- Make `order_id` field a string  for `Order Completed` event
- Rename `shippingMethod` field to `shipping_method` for `Checkout Step Completed` event
- Rename `paymentMethod` field to `payment_method` for `Checkout Step Completed` event
- Do not populate `brand` field if brand is missing for a product
- Assign default value `single-product-option` for the `variant` field in products payload in order to make it consistent with other events. [Related PR](https://github.com/bigcommerce/bigcommerce/pull/56279)
- Update unit tests
There are several inconsistencies between payload we generate and Segment specification. So that we need to …
=> fix(checkout): DATA-11638 Fix payloads for Segment events

.github/CODEOWNERS, packages/core/src/analytics/index.ts, packages/core/src/analytics/paypal-commerce-connect-tracker/create-paypal-commerce-connect-tracker.spec.ts, packages/core/src/analytics/paypal-commerce-connect-tracker/create-paypal-commerce-connect-tracker.ts, packages/core/src/analytics/paypal-commerce-connect-tracker/index.ts, packages/core/src/analytics/paypal-commerce-connect-tracker/paypal-commerce-connect-tracker-service.ts, packages/core/src/analytics/paypal-commerce-connect-tracker/paypal-commerce-connect-tracker.spec.ts, packages/core/src/analytics/paypal-commerce-connect-tracker/paypal-commerce-connect-tracker.ts, packages/core/src/bundles/checkout-sdk.ts, packages/paypal-commerce-integration/src/paypal-commerce-accelerated-checkout/paypal-commerce-accelerated-checkout-customer-strategy.ts, packages/paypal-commerce-utils/src/mocks/get-paypal-axo-sdk.mock.ts, packages/paypal-commerce-utils/src/mocks/get-paypal-commerce-payment-method.mock.ts, packages/paypal-commerce-utils/src/mocks/get-paypal-connect.mock.ts, packages/paypal-commerce-utils/src/mocks/index.ts, packages/paypal-commerce-utils/src/paypal-commerce-types.ts, packages/paypal-commerce-utils/src/utils/index.ts, packages/paypal-commerce-utils/src/utils/is-paypal-commerce-connect-window.spec.ts, packages/paypal-commerce-utils/src/utils/is-paypal-commerce-connect-window.ts
Added PayPalCommerceConnectTracker for analytics
To be able to track different paypal commerce related events on UI side
Manual tests
Unit tests
CI
Payment method selected event (on a paywall):
Wallet button selected event:
Email submitted event:
Order placed event:
=> feat(payment): PAYPAL-3424 added PayPalCommerceConnectTracker for analytics

packages/core/src/checkout/create-checkout-service.ts
This adds a[ zero-width space character](https://en.wikipedia.org/wiki/Zero-width_space) into the `process.env.NODE_ENV` warning text so that it is not statically replaced. This is how the [Vite documentation](https://vitejs.dev/guide/env-and-mode.html#production-replacement) recommends fixing this issue (see the first bullet point under "Production Replacement").
Fixes #2138 
When using Vite, env variables like `process.env.NODE_ENV` are statically replaced, even inside of strings. This means that that instead of a well-formed warning string being produced, invalid Javascript is actually created.
https://stackblitz.com/edit/vitejs-vite-t7xh32?file=main.js
Baseline reproduction of the issue. If you use devtools you can see the relevant error being thrown and jumping into the source you'll …
=> fix(checkout): Prevent Vite From Creating Syntax Errors

packages/core/src/payment/instrument/supported-payment-instruments.ts, packages/google-pay-integration/src/google-pay-paypal-commerce/google-pay-paypal-commerce-script-loader.ts, packages/google-pay-integration/src/google-pay-paypal-commerce/types.ts, packages/payment-integration-api/src/hosted-form/hosted-field-type.ts, packages/payment-integration-api/src/hosted-form/hosted-form-options.ts, packages/payment-integration-api/src/hosted-form/index.ts, packages/payment-integration-api/src/hosted-form/is-credit-card-vaulted-form-fields.ts, packages/payment-integration-api/src/index.ts, packages/paypal-commerce-integration/src/mocks/get-paypal-sdk.mock.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit-card/paypal-commerce-credit-cards-payment-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit-card/paypal-commerce-credit-cards-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-integration-service.ts, packages/paypal-commerce-integration/src/paypal-commerce-script-loader.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-script-loader.ts, packages/paypal-commerce-integration/src/paypal-commerce-types.ts, packages/paypal-commerce-integration/tsconfig.json
PPCP Credit Cards payment strategy. Card Fields api have been implemented instead of HostedFields api.
=> feat(payment): PAYPAL-3227 PPCP Card Fields implemented

packages/paypal-commerce-integration/src/paypal-commerce-accelerated-checkout/paypal-commerce-accelerated-checkout-customer-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-accelerated-checkout/paypal-commerce-accelerated-checkout-customer-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-accelerated-checkout/paypal-commerce-accelerated-checkout-payment-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-accelerated-checkout/paypal-commerce-accelerated-checkout-payment-strategy.ts, packages/paypal-commerce-utils/src/paypal-commerce-accelerated-checkout-utils.spec.ts, packages/paypal-commerce-utils/src/paypal-commerce-accelerated-checkout-utils.ts, packages/paypal-commerce-utils/src/paypal-commerce-types.ts
Updated PPCP AXO credit card component form background transparent
PP have white background for PP Connect Card Component that does not fit for us, because cornerstone has light gray background and the customer may see white color of the form. It might be an issue for different themes, so it might be better to make them transparent.
Unit tests
Manual tests
Before:
After:
=> feat(payment): PAYPAL-3493 updated PPCP AXO credit card component form background transparent

packages/paypal-commerce-utils/src/paypal-commerce-sdk.spec.ts, packages/paypal-commerce-utils/src/paypal-commerce-sdk.ts
Updated PPCP AXO SDK option `data-client-metadata-id` with `uuidv4` value
This change is required for properly working PayPal Connect on production
Unit tests
Manual tests
CI
Result:
=> feat(payment): PAYPAL-3497 updated PPCP AXO SDK option data-client-metadata-id with uuidv4 value

packages/paypal-commerce-integration/.eslintrc.json, packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-payment-initialize-options.ts, packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-payment-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-payment-strategy.ts, packages/paypal-commerce-utils/src/index.ts, packages/paypal-commerce-utils/src/utils/is-paypal-commerce-provider-error.spec.ts, packages/paypal-commerce-utils/src/utils/is-paypal-commerce-provider-error.ts
Added restart flow for PPCP
To avoid `INSTRUMENT_DECLINED` error
https://github.com/bigcommerce/checkout-sdk-js/assets/56301104/bb8c385c-19a5-456f-a442-b97c8df6af54
=> feat(payment): PAYPAL-3439 added restart flow for PPCP

packages/bluesnap-direct-integration/src/bluesnap-direct-apm/bluesnap-direct-apm-payment-strategy.spec.ts, packages/bluesnap-direct-integration/src/bluesnap-direct-apm/bluesnap-direct-apm-payment-strategy.ts, packages/core/src/payment/instrument/instrument.ts, packages/core/src/payment/instrument/supported-payment-instruments.ts, packages/payment-integration-api/src/payment/payment.ts
Implementation of the stored ACH/ECP for Bluesnap Direct
Due to the product requirements
https://github.com/bigcommerce/checkout-sdk-js/assets/79574476/957f4cbf-67a2-4a06-8f52-d1738457cd8e
https://github.com/bigcommerce/checkout-sdk-js/assets/79574476/6f7fe20d-27df-4577-90e7-51c9eaa04494
https://github.com/bigcommerce/checkout-sdk-js/assets/79574476/b57589ea-701f-42e5-8691-22bd8ed5e3a7
=> feat(payment): PI-1313 stored ecp for bluesnap

packages/braintree-utils/src/braintree.ts, packages/paypal-commerce-integration/src/paypal-commerce-accelerated-checkout/create-paypal-commerce-accelerated-checkout-customer-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-accelerated-checkout/paypal-commerce-accelerated-checkout-customer-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-accelerated-checkout/paypal-commerce-accelerated-checkout-customer-strategy.ts, packages/paypal-commerce-utils/src/paypal-commerce-types.ts
Updated PayPalCommerceAcceleratedCheckoutCustomerStrategy to load it with ppcp credit cards method id
Because we could not trigger PayPalCommerceAcceleratedCheckoutCustomerStrategy for cases if PPCP AXO experiment did not rollout to 100% for the store
Unit tests
Manual tests
CI
=> feat(payment): PAYPAL-3560 updated PayPalCommerceAcceleratedCheckoutCustomerStrategy to load it with ppcp credit cards method id

packages/google-pay-integration/src/gateways/google-pay-gateway.spec.ts, packages/google-pay-integration/src/gateways/google-pay-gateway.ts, packages/google-pay-integration/src/google-pay-button-strategy.spec.ts, packages/google-pay-integration/src/google-pay-button-strategy.ts, packages/google-pay-integration/src/google-pay-customer-strategy.spec.ts, packages/google-pay-integration/src/google-pay-customer-strategy.ts, packages/google-pay-integration/src/google-pay-payment-processor.spec.ts, packages/google-pay-integration/src/google-pay-payment-processor.ts, packages/google-pay-integration/src/google-pay-payment-strategy.spec.ts, packages/google-pay-integration/src/google-pay-payment-strategy.ts
Rewrote the implementation of loading the checkout instance in a different way to avoid opening GP on another page with the error, as this doesn't work in Safari.
The reason that it's not working is because Google Pay tries to open a popup window when you call `loadPaymentData` after making the request `loadCheckout`.This is a specific behavior related to how Safari handles actions. In Chrome, we always see a popup and are not redirected to another page
Before
The example shows how the GP button worked on the customer step. The same behavior occurs in other places where we use the GP button
https://github.com/bigcommerce/checkout-sdk-js/assets/99336044/e0f5777c-03e6-44fe-b250-30ebda1967bd
After
https://github.com/bigcommerce/checkout-sdk-js/assets/99336044/237110ff-8991-46a9-b3d8-1f942f990 …
=> feat(payment): PAYPAL-3405 GooglePay not working 404 (iOS devices)

packages/paypal-commerce-utils/src/create-paypal-commerce-accelerated-checkout-utils.spec.ts, packages/paypal-commerce-utils/src/create-paypal-commerce-accelerated-checkout-utils.ts, packages/paypal-commerce-utils/src/create-paypal-commerce-fastlane-utils.spec.ts, packages/paypal-commerce-utils/src/create-paypal-commerce-fastlane-utils.ts, packages/paypal-commerce-utils/src/mocks/get-paypal-fastlane-authentication-result.mock.ts, packages/paypal-commerce-utils/src/mocks/get-paypal-fastlane-sdk.mock.ts, packages/paypal-commerce-utils/src/mocks/get-paypal-fastlane.mock.ts, packages/paypal-commerce-utils/src/mocks/index.ts, packages/paypal-commerce-utils/src/paypal-commerce-fastlane-utils.spec.ts, packages/paypal-commerce-utils/src/paypal-commerce-fastlane-utils.ts, packages/paypal-commerce-utils/src/paypal-commerce-sdk.spec.ts, packages/paypal-commerce-utils/src/paypal-commerce-sdk.ts, packages/paypal-commerce-utils/src/paypal-commerce-types.ts, packages/paypal-commerce-utils/src/utils/index.ts, packages/paypal-commerce-utils/src/utils/is-paypal-fastlane-customer.spec.ts, packages/paypal-commerce-utils/src/utils/is-paypal-fastlane-customer.ts, packages/paypal-commerce-utils/src/utils/is-paypal-fastlane-window.spec.ts, packages/paypal-commerce-utils/src/utils/is-paypal-fastline-window.ts
Updated paypal-commerce-utils package with PayPal Fastlane support:
- added Fastlane interfaces;
- updated PayPal Commerce Sdk configuration with Fastlane script;
- covered all utils methods related to Connect and Fasline into one PayPal Fastline Utils class;
P.s.: we should keep Connect related code while transforming all related code to use Fastlane.
will remove it when Fastlane experiment be rollout to 100%
As part of PayPal Connect rebranding to PayPal Fastlane
Unit tests
CI
=> feat(payment): PAYPAL-3576 updated paypal-commerce-utils package with PayPal Fastlane support

packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-utils.spec.ts, packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-utils.ts, packages/core/src/payment-integration/create-payment-integration-selectors.ts, packages/payment-integration-api/src/index.ts, packages/payment-integration-api/src/payment-integration-selectors.ts, packages/payment-integration-api/src/payment/index.ts, packages/payment-integration-api/src/payment/instrument.ts, packages/payment-integrations-test-utils/src/test-utils/payments.mock.ts, packages/paypal-commerce-integration/src/paypal-commerce-accelerated-checkout/paypal-commerce-accelerated-checkout-payment-strategy.spec.ts, packages/paypal-commerce-utils/src/paypal-commerce-accelerated-checkout-utils.spec.ts, packages/paypal-commerce-utils/src/paypal-commerce-accelerated-checkout-utils.ts
Added `getInstruments` to payment integration selectors
To be able to get the instruments
=> feat(payment): PAYPAL-3453 Added getInstruments to payment integration selectors

packages/paypal-commerce-utils/src/paypal-commerce-fastlane-utils.spec.ts, packages/paypal-commerce-utils/src/paypal-commerce-fastlane-utils.ts
Updated PayPal to BC instrument mapper with untrustedShippingCardVerificationMode
To fix failed merge build
Unit tests
CI
=> fix(payment): PAYPAL-3573 updated PayPal to BC instrument mapper with untrustedShippingCardVerificationMode

packages/payment-integration-api/src/payment-integration-service.ts, packages/payment-integration-api/src/payment/payment.ts, packages/paypal-commerce-integration/src/paypal-commerce-accelerated-checkout/paypal-commerce-accelerated-checkout-payment-strategy.ts, packages/paypal-commerce-utils/src/paypal-commerce-types.ts
Updated PaymentInstrumentPayload interface with generic
This feature gives developers an ability to provide custom formatted payload interface to payment submit method from provider specific package. It should help us to keep all custom interfaces inside our own packages and remove all provider specific code from core type packages (payment integration api).
I have build the project in different ways using `npm run build`, `npm run bundle:watch`, `npm run bundle-dts`, different commands to check lint issues and tests and they are all passed successfully
And CI tests as well
=> refactor(payment): PAYPAL-3647 updated PaymentInstrumentPayload interface with generic

packages/core/src/shipping/create-shipping-strategy-registry.spec.ts, packages/core/src/shipping/create-shipping-strategy-registry.ts
Updated shipping registry with PayPal Commerce Fastlane shipping strategy instead of accelerated checkout
As part of PP Connect rebrending process. PayPal Commerce Fastlane shipping strategy contains both Connect and Fastlane features to be able to switch between them based on the value of related experiment
Unit tests
Manual tests
CI
=> refactor(payment): PAYPAL-3575 updated shipping registry with paypal commerce fastlane shipping strategy instead of accelerated checkout

packages/paypal-commerce-integration/src/paypal-commerce-credit-card/create-paypal-commerce-credit-cards-payment-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit-card/paypal-commerce-credit-cards-payment-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit-card/paypal-commerce-credit-cards-payment-strategy.ts, packages/paypal-commerce-utils/src/paypal-commerce-sdk.spec.ts, packages/paypal-commerce-utils/src/paypal-commerce-sdk.ts
Updated paypal-commerce-credit-cards-payment-strategy to support PayPal Connect and Fastlane initialization
As part of PayPal Connect to Fastlane rebranding
Unit tests
CI
=> feat(payment): PAYPAL-3683 updated paypal-commerce-credit-cards-payment-strategy to support PayPal Connect and Fastlane initialization

packages/stripe-integration/src/stripe-upe/stripe-upe-initialize-options.ts, packages/stripe-integration/src/stripe-upe/stripe-upe-payment-strategy.spec.ts, packages/stripe-integration/src/stripe-upe/stripe-upe-payment-strategy.ts, packages/stripe-integration/src/stripe-upe/stripe-upe.mock.ts, packages/stripe-integration/src/stripe-upe/stripe-upe.ts
Add ability to hide Stripe terms text
To hide terms text for saving credit card when shopper don't select save credit card option
Checkout-js PR: [https://github.com/bigcommerce/checkout-js/pull/1733](https://github.com/bigcommerce/checkout-js/pull/1733)
Experiment disabled
https://github.com/bigcommerce/checkout-sdk-js/assets/9430298/5493da42-f4e4-4813-b2fb-f3f82ceec230
Experiment enabled
https://github.com/bigcommerce/checkout-sdk-js/assets/9430298/ff09a364-13cc-4856-9d6c-dffdde66df17
=> feat(payment): PI-1679 toggle Stripe terms text

packages/braintree-utils/src/braintree-integration-service.spec.ts, packages/braintree-utils/src/braintree-integration-service.ts
Updated `axoEnv` sandbox key to `fastlaneEnv` in `braintree-integration-service` file
Due to updates on PayPal side
Unit tests
CI
=> feat(payment): PAYPAL-3745 updated axoEnv sandbox key to fastlaneEnv in braintree-integration-service file

packages/paypal-commerce-utils/src/paypal-commerce-fastlane-utils.spec.ts, packages/paypal-commerce-utils/src/paypal-commerce-fastlane-utils.ts
Updated `axoEnv` sandbox key to `fastlaneEnv` in `paypal-commerce-fastlane-utils` file
Due to last changes on PayPal side
Unit tests
CI
=> feat(payment): PAYPAL-3743 updated axoEnv sandbox key to fastlaneEnv in paypal-commerce-fastlane-utils file

packages/paypal-commerce-integration/src/paypal-commerce-credit-card/paypal-commerce-credit-cards-payment-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit-card/paypal-commerce-credit-cards-payment-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-types.ts
Added billing address data to the submit payload for PPCP credit card form action
To avoid different mistakes and detect fraud payments on PayPal side
Unit tests
Manual tests
CI
=> feat(payment): PAYPAL-3784 added billing address data to the submit payload for PPCP credit card form action

packages/td-bank-integration/src/td-online-mart-payment-strategy.spec.ts, packages/td-bank-integration/src/td-online-mart-payment-strategy.ts, packages/td-bank-integration/src/td-online-mart.ts
Adding additional card token for TD bank
Need additional token for instrument saving
=> feat(payment): PI-1753 Pass an additional Single-Use Token to bigpay

packages/td-bank-integration/src/td-online-mart-payment-strategy.spec.ts, packages/td-bank-integration/src/td-online-mart-payment-strategy.ts
Fix vaulting options for TD bank
To use correct payload for vaulting instruments
=> fix(payment): PI-1138 TD Bank vaulting options

packages/paypal-commerce-integration/src/paypal-commerce-fastlane/paypal-commerce-fastlane-payment-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-fastlane/paypal-commerce-fastlane-payment-strategy.ts, packages/paypal-commerce-utils/src/mocks/get-paypal-connect.mock.ts, packages/paypal-commerce-utils/src/mocks/get-paypal-fastlane.mock.ts, packages/paypal-commerce-utils/src/paypal-commerce-types.ts
Updated execute tokenize method with getPaymentToken in paypal-commerce-fastlane-payment-strategy
PayPal Commerce Fastlane does not have tokenize sdk method as Connect had due to refactoring on PayPal side
Unit tests
Manual tests
CI
=> feat(payment): PAYPAL-3744 updated execute tokenize method with getPaymentToken in paypal-commerce-fastlane-payment-strategy

packages/core/src/analytics/braintree-analytic-tracker/braintree-analytic-tracker.ts, packages/core/src/analytics/paypal-commerce-analytic-tracker/paypal-commerce-analytic-tracker.ts
Removed hardcoded payment method id value in braintree and paypal commerce analytic trackers
To avoid data mistakes in PayPal analytic
Unit tests
CI
=> fix(payment): PAYPAL-3838 removed hardcoded payment method id value in braintree and paypal commerce analytic trackers

.circleci/config.yml
Adding GItleaks (secret scanner).
For secrets detection to prevent accidental commits of secrets
Passing of existing CI builds with gitleaks succesfully running as part of the process.
=> chore(common): CHECKOUT-0 - Add Gitleaks to CircleCI

.circleci/config.yml
Changing config to not scan forked branches
Forked PRs can break how circleci runs
refer to ci test passing
=> chore(common): CHECKOUT-0 Don't scanned forked

packages/core/src/embedded-checkout/resizable-iframe-creator.spec.ts, packages/core/src/embedded-checkout/resizable-iframe-creator.ts
Adds support in the `ResizeableIframeCreator` for bare and www versions of the domain passed to `embedCheckout` .
Fixes #2425 
If the embed checkout url that is passed to `embedCheckout` is a bare url missing the www subdomain whilst the store loads with a redirect to the www subdomain, the resulting `MessageEvent` that is posted will be ignored by the `ResizeableIframeCreator`.
I used the [`IframeEventListener`'s handling](https://github.com/bigcommerce/checkout-sdk-js/blob/b4e9bee3c0fa999210cca52089f21469679b0663/packages/core/src/common/iframe/iframe-event-listener.ts#L16-L19) of this functionality as a baseline for this change.
The test that has been included as part of this PR fails without the associated change.
=> fix(embedded-checkout): Handle www redirects on embed checkout links

packages/core/src/payment/instrument/supported-payment-instruments.ts
Add TD Online Mart to list of available instruments
To use TD Online Mart vaulted instruments on checkout
=> fix(payment): PI-1835 add TDBant to supported instruments

packages/td-bank-integration/src/td-online-mart-payment-strategy.spec.ts, packages/td-bank-integration/src/td-online-mart-payment-strategy.ts, packages/td-bank-integration/src/td-online-mart.ts
Add checks of input container existing before mounting TD Bank card fields
Remove unused token for credit card saving
To fix issues with fields validation and update payloads after BE refactoring
https://github.com/bigcommerce/checkout-sdk-js/assets/9430298/a625f9d0-0547-44d5-aef3-0899e82a847a
=> fix(payment): PI-1841 Check fields containers before mount

packages/core/src/payment/strategies/braintree/braintree-payment-processor.spec.ts, packages/core/src/payment/strategies/braintree/braintree-payment-processor.ts, packages/core/src/payment/strategies/braintree/braintree.ts
Added collectDeviceData flag to Braintree sdk
Because users getting some 2099 checkout errors with braintree. This is due to a 3DS error because the deviceData was not collected. Braintree support sent us this solution to prevent this errors. Once this is set up, customers won't receive any more 2099 errors during their transactions.
=> feat(payment): PAYPAL-3881 added collectDeviceData flag to braintree sdk

packages/paypal-commerce-integration/src/paypal-commerce-credit-card/paypal-commerce-credit-cards-payment-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit-card/paypal-commerce-credit-cards-payment-strategy.ts
Sending billing address using PayPal Card Fields submit method only with order creation.
Because there is an error if we send billing address when it's additional security step. 
All tests have been passed.
=> feat(payment): PAYPAL-3910 send billing address only with order creation

packages/td-bank-integration/src/td-online-mart-payment-strategy.spec.ts, packages/td-bank-integration/src/td-online-mart-payment-strategy.ts
Add nonce value for TD Bank vaulted instruments with untrusted shipping address
To skip verification by card number, because TD Online Mart does not support it
Vaulted instruments:
Instrument with trusted shipping address:
Instrument with untrusted shipping address:
=> fix(payment): PI-1899 additional token for instrument verification

packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-payment-initialize-options.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-payment-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-payment-strategy.ts
Turned required params to optional
Manual
=> feat(payment): PAYPAL-000 turned required params to optional

packages/paypal-commerce-integration/src/paypal-commerce-fastlane/paypal-commerce-fastlane-customer-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-fastlane/paypal-commerce-fastlane-customer-strategy.ts
Added try catch to PayPal Commerce Fastlane Customer Strategy initialization method
To catch an error and does not do anything with it to avoid blocking customer from checkout. So when PayPal Fastlane fails to initialize, it does not show an error modal, so the user can continue the checkout.
Unit tests
Manual tests
CI
=> feat(payment): PAYPAL-3878 added try catch to PayPal Commerce Fastlane Customer Strategy initialization method

packages/braintree-integration/src/braintree-fastlane/braintree-fastlane-customer-strategy.spec.ts, packages/braintree-integration/src/braintree-fastlane/braintree-fastlane-customer-strategy.ts
Added try catch to BraintreeFastlaneCustomerStrategy initialize method
To catch an error and does not do anything with it to avoid blocking customer from checkout. So when PayPal Fastlane fails to initialize, it does not show an error modal, so the user can continue the checkout.
Unit tests
Manual tests
CI
=> feat(payment): PAYPAL-3896 added try catch to BraintreeFastlaneCustomerStrategy initialize method

packages/braintree-utils/src/utils/index.ts, packages/braintree-utils/src/utils/is-braintree-connect-profile-data.spec.ts, packages/braintree-utils/src/utils/is-braintree-connect-profile-data.ts, packages/braintree-utils/src/utils/is-braintree-fastlane-profile-data.spec.ts, packages/braintree-utils/src/utils/is-braintree-fastlane-profile-data.ts, packages/core/src/shipping/strategies/braintree/braintree-accelerated-checkout-shipping-strategy.spec.ts, packages/core/src/shipping/strategies/braintree/braintree-accelerated-checkout-shipping-strategy.ts
Update Braintree Accelerated Checkout shipping strategy to support Fastlane + Connect
To integrate fastlane
Unit tests passed
=> feat(payment): PAYPAL-3587 Update Braintree Accelerated Checkout shipping strategy to support Fastlane + Connect

packages/core/src/checkout-buttons/create-checkout-button-registry.spec.ts, packages/core/src/checkout-buttons/create-checkout-button-registry.ts, packages/google-pay-integration/src/factories/button/create-google-pay-authorizenet-button-strategy.spec.ts, packages/google-pay-integration/src/factories/button/create-google-pay-authorizenet-button-strategy.ts, packages/google-pay-integration/src/factories/button/create-google-pay-checkoutcom-button-strategy.spec.ts, packages/google-pay-integration/src/factories/button/create-google-pay-checkoutcom-button-strategy.ts, packages/google-pay-integration/src/factories/button/create-google-pay-cybersource-button-strategy.spec.ts, packages/google-pay-integration/src/factories/button/create-google-pay-cybersource-button-strategy.ts, packages/google-pay-integration/src/factories/button/create-google-pay-orbital-button-strategy.spec.ts, packages/google-pay-integration/src/factories/button/create-google-pay-orbital-button-strategy.ts, packages/google-pay-integration/src/factories/button/create-google-pay-stripe-button-strategy.spec.ts, packages/google-pay-integration/src/factories/button/create-google-pay-stripe-button-strategy.ts, packages/google-pay-integration/src/factories/button/create-google-pay-worldpayaccess-button-strategy.spec.ts, packages/google-pay-integration/src/factories/button/create-google-pay-worldpayaccess-button-strategy.ts, packages/google-pay-integration/src/google-pay-button-initialize-options.ts, packages/google-pay-integration/src/google-pay-button-strategy.spec.ts, packages/google-pay-integration/src/google-pay-button-strategy.ts, packages/google-pay-integration/src/index.ts
Updated version of the https://github.com/bigcommerce/checkout-sdk-js/pull/2037
1. Add Google Pay button strategy for Worldpay Access
2. Refactor existing logic for:
- Authorize Net
- Checkout Com
- Cybersource / BNZ
- Orbital
- Stripe v3 / Stripe UPE
To checkout using Google Pay through Worldpay Access
Tested manually/units
#1967 and #1994
@bigcommerce/checkout @bigcommerce/payments @bigcommerce/apex-integrations 
[INT-7698]: https://bigcommercecloud.atlassian.net/browse/INT-7698?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(payment): INT-7698 GooglePay: Add button strategy

packages/klarna-integration/src/klarnav2/create-klarnav2-payment-strategy.ts, packages/klarna-integration/src/klarnav2/klarnav2-payment-strategy.spec.ts, packages/klarna-integration/src/klarnav2/klarnav2-payment-strategy.ts
Add current store path for Klarna remote checkout request
To fix issue with headless store redirection
Without experiment
https://github.com/bigcommerce/checkout-sdk-js/assets/9430298/527b6098-d286-4483-85a9-471b988f7390
With experiment enabled
https://github.com/bigcommerce/checkout-sdk-js/assets/9430298/8b910732-b5a8-4e5b-9edc-9bd13909d195
=> fix(payment): PI-1823 Add shop path to the remote checkout request

packages/paypal-commerce-integration/src/paypal-commerce-credit-card/paypal-commerce-credit-cards-payment-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit-card/paypal-commerce-credit-cards-payment-strategy.ts
There was an issue with Credit Card fields text styling. For dark theme text had white color, so for fields with white background the text was "invisible" for customers. Unfortunately, **PayPal does not support background-color for field styling**, so we decided to change text color to black (for default, valid and focus field state) and red (for invalid field state).
Customers does not see white text on a field with white background
Unit tests
Manual tests
CI
Before:
After:
=> fix(payment): PAYPAL-3736 fixed PayPalCommerce Credit Card fields style issue

packages/apple-pay-integration/src/apple-pay-customer-strategy.spec.ts, packages/apple-pay-integration/src/apple-pay-customer-strategy.ts
Fix issue with apple pay button clicked twice
If a user clicks on apple pay button twice it can block the user due to an error `Apple Pay: Page already has an active payment session` as reported here https://help.noibu.com/hc/en-us/articles/11383689403149-Apple-Pay-Page-already-has-an-active-payment-session#:~:text=The%20active%20payment%20session%20error,a%20single%20time%20per%20transaction.
- CI
- Manual
=> fix(payment): CHECKOUT-8132 Fix issue with apple pay button clicked twice

packages/braintree-integration/src/braintree-fastlane/braintree-fastlane-customer-strategy.spec.ts, packages/braintree-integration/src/braintree-fastlane/braintree-fastlane-customer-strategy.ts, packages/braintree-integration/src/braintree-fastlane/braintree-fastlane-payment-strategy.spec.ts, packages/braintree-integration/src/braintree-fastlane/braintree-fastlane-payment-strategy.ts, packages/core/src/shipping/strategies/braintree/braintree-accelerated-checkout-shipping-strategy.spec.ts, packages/core/src/shipping/strategies/braintree/braintree-accelerated-checkout-shipping-strategy.ts, packages/core/src/shipping/strategies/paypal-commerce/paypal-commerce-fastlane-shipping-strategy.spec.ts, packages/core/src/shipping/strategies/paypal-commerce/paypal-commerce-fastlane-shipping-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-fastlane/paypal-commerce-fastlane-customer-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-fastlane/paypal-commerce-fastlane-customer-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-fastlane/paypal-commerce-fastlane-payment-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-fastlane/paypal-commerce-fastlane-payment-strategy.ts
Added a switch to turn off Fastlane for Store Members
PayPal team does not have Store Member support for Fastlane in their roadmap, so we should be able to turn off the feature for all stores at once and remove implementation if everything ok.
Unit tests
Manual tests
CI
PayPal Commerce Fastlane:
https://github.com/bigcommerce/checkout-sdk-js/assets/25133454/df1808a7-64aa-42be-9749-2b8f55837bbc
Braintree Fastlane:
https://github.com/bigcommerce/checkout-sdk-js/assets/25133454/e42a1a38-284b-4445-ab13-4a8462b5b025
=> feat(payment): PAYPAL-4001 added a switch to turn off Fastlane for Store Members

packages/paypal-commerce-integration/src/paypal-commerce-credit-card/paypal-commerce-credit-cards-payment-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-types.ts
Added `await` for PPCP Card Fields `render` method.
Because without await we can see pre-loaders which breaks layout.
Before changes:
https://github.com/bigcommerce/checkout-sdk-js/assets/130665807/8bc1f7af-b342-49ff-a851-25a29ee026f9
After changes:
https://github.com/bigcommerce/checkout-sdk-js/assets/130665807/3baf3196-0ecd-449b-bf93-f4d558403cc9
=> feat(payment): PAYPAL-3997 PPCP Card fields render method is awaited

packages/core/src/payment-integration/create-payment-integration-service.ts, packages/core/src/payment-integration/default-payment-integration-service.spec.ts, packages/core/src/payment-integration/default-payment-integration-service.ts, packages/payment-integration-api/src/payment-integration-service.ts, packages/payment-integrations-test-utils/src/test-utils/payment-integration-service.mock.ts
Updated `PaymentIntegrationService` to include:
- `validateCheckout` - so the `validate` method from the core package can be used
- `loadPaymentMethods` - to load available payments methods after `forgetCheckout` method is used
Needed for moving Afterpay payment strategy to a separate package.
Unit + manual tests.
=> feat(payment): PI-1606 add validateCheckout and loadPaymentMethods to Payment Integration Service

packages/core/src/checkout/checkout-action-creator.spec.ts, packages/core/src/checkout/checkout-action-creator.ts, packages/core/src/shipping/shipping-addresses.mock.ts
TODO: 
set shouldSaveAddress to false for existing customer addresses while loadCheckout
so sending consignments/billing address update request, for an existing address, will set shouldSaveAddress to false, get rid of create address again.
in checkout.js (do not do any changes) use this changed sdk, print address in AddressSelect:
before change this field is missed, so sending request to backend, it will be by default true, which causes problem.
it's already set shouldSaveAddress to false.
=> fix(checkout): CHECKOUT-8183 set shouldSaveAddress to false for existing customer addresses while loadCheckout

packages/paypal-commerce-integration/src/paypal-commerce-credit-card/paypal-commerce-credit-cards-payment-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit-card/paypal-commerce-credit-cards-payment-strategy.ts
Sending `set_as_default_stored_instrument` flag with already vaulted instrument
=> feat(payment): PAYPAL-4032 PPCP Card Fields shouldSetAsDefaultInstrument flag send

packages/adyen-utils/src/adyenv2/adyenv2-script-loader.spec.ts, packages/adyen-utils/src/adyenv2/adyenv2-script-loader.ts, packages/adyen-utils/src/adyenv3/adyenv3-script-loader.spec.ts, packages/adyen-utils/src/adyenv3/adyenv3-script-loader.ts, packages/core/src/payment/strategies/adyenv2/adyenv2-script-loader.spec.ts, packages/core/src/payment/strategies/adyenv2/adyenv2-script-loader.ts, packages/core/src/payment/strategies/adyenv3/adyenv3-script-loader.spec.ts, packages/core/src/payment/strategies/adyenv3/adyenv3-script-loader.ts
Added SRI hashes for the adyen styles and scripts
Due to the PCI4 requirements
Units/manually
Adyen v2
https://github.com/bigcommerce/checkout-sdk-js/assets/79574476/f9b1e510-dcee-4d35-9d66-9434dc4b6454
https://github.com/bigcommerce/checkout-sdk-js/assets/79574476/454fc4fd-1f13-43e9-a090-f6b252d010f7
Adyen v3
https://github.com/bigcommerce/checkout-sdk-js/assets/79574476/c9e2726a-9aa8-42de-9707-4ce99fa7aeed
https://github.com/bigcommerce/checkout-sdk-js/assets/79574476/0f9c9d14-ebea-4503-aa0c-9ddc09e97bd1
=> feat(payment): PI-1916 Added SRI hashes for the adyen styles and scripts

packages/core/src/payment/strategies/braintree/braintree-hosted-form.spec.ts, packages/core/src/payment/strategies/braintree/braintree-hosted-form.ts, packages/core/src/payment/strategies/braintree/braintree.ts
Added validation for credit card name field
Buyer cannot checkout via Credit Card if the Name on Card field was not filled out. And we didn't get/show any information about it for the customers.
Before:
https://github.com/bigcommerce/checkout-sdk-js/assets/99336044/27bbaded-8602-4d62-b2fb-a22e1ebf6a5e
After:
https://github.com/bigcommerce/checkout-sdk-js/assets/99336044/5d187235-8dec-4048-ade4-becab2162f2f
=> feat(payment): PAYPAL-3976 Broken validation of card fields if the Name on Card field was not filled out

packages/core/src/shipping/shipping-request-options.ts, packages/core/src/shipping/strategies/braintree/braintree-accelerated-checkout-shipping-initialize-options.ts, packages/core/src/shipping/strategies/braintree/braintree-accelerated-checkout-shipping-strategy.spec.ts, packages/core/src/shipping/strategies/braintree/braintree-accelerated-checkout-shipping-strategy.ts, packages/core/src/shipping/strategies/paypal-commerce/paypal-commerce-fastlane-shipping-initialization-options.ts, packages/core/src/shipping/strategies/paypal-commerce/paypal-commerce-fastlane-shipping-strategy.spec.ts, packages/core/src/shipping/strategies/paypal-commerce/paypal-commerce-fastlane-shipping-strategy.ts
Updated shipping initialise options with braintreefastlane and paypalcommercefastlane options
To be able to pass provider specific options from UI
Unit tests
CI
Checkout and checkout-sdk builds passed successfully:
=> refactor(payment): PAYPAL-4070 updated shipping initialise options with braintreefastlane and paypalcommercefastlane options

packages/braintree-integration/src/braintree-fastlane/braintree-fastlane-payment-strategy.spec.ts, packages/braintree-integration/src/braintree-fastlane/braintree-fastlane-payment-strategy.ts, packages/braintree-integration/src/braintree-fastlane/braintree-fastlane-utils.ts, packages/braintree-integration/src/braintree-fastlane/is-braintree-connect-card-component.ts, packages/braintree-integration/src/braintree-fastlane/is-braintree-fastlane-card-component.ts, packages/braintree-utils/src/braintree.ts, packages/braintree-utils/src/mocks/braintree.mock.ts, packages/paypal-commerce-integration/src/paypal-commerce-fastlane/paypal-commerce-fastlane-payment-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-fastlane/paypal-commerce-fastlane-payment-strategy.ts, packages/paypal-commerce-utils/src/mocks/get-paypal-fastlane.mock.ts, packages/paypal-commerce-utils/src/paypal-commerce-types.ts
Updated PayPalPaymentComponent with PayPalCardComponent from paypal sdk
Because PayPalPaymentComponent renders billing address form on payment step while PayPalCardComponent does not. In short they are almost the same.
Unit tests
Manual tests
CI
Braintree Fastlane Gary and Ryan flows:
https://github.com/bigcommerce/checkout-sdk-js/assets/25133454/6d9cfacb-b2cc-49ed-af8a-828de3f8f663
https://github.com/bigcommerce/checkout-sdk-js/assets/25133454/67503b32-e371-40e2-8a50-6387b2b5365f
PayPal Commerce Fastlane Gary and Ryan flows:
https://github.com/bigcommerce/checkout-sdk-js/assets/25133454/f6f33207-a740-4b54-aaab-0bb1fb5f90f4
https://github.com/bigcommerce/checkout-sdk-js/assets/25133454/8b48c135-cb4f-425f-91ca-4abc3737324c
View of the component for US based customers:
=> feat(payment): PAYPAL-4082 updated PayPalFastlaneComponent with PayPalCardComponent from paypal sdk

packages/core/src/shipping/strategies/paypal-commerce/paypal-commerce-fastlane-shipping-initialization-options.ts, packages/core/src/shipping/strategies/paypal-commerce/paypal-commerce-fastlane-shipping-strategy.spec.ts, packages/core/src/shipping/strategies/paypal-commerce/paypal-commerce-fastlane-shipping-strategy.ts, packages/paypal-commerce-utils/src/mocks/get-paypal-commerce-payment-method.mock.ts, packages/paypal-commerce-utils/src/mocks/get-paypal-fastlane.mock.ts, packages/paypal-commerce-utils/src/paypal-commerce-fastlane-utils.spec.ts, packages/paypal-commerce-utils/src/paypal-commerce-fastlane-utils.ts, packages/paypal-commerce-utils/src/paypal-commerce-types.ts
Added paypal fastlane shipping selector implementation to paypal commerce fastlane shipping strategy
To be able to use PayPal Fastlane shipping selector on the UI, so the customer will be able to select between addresses from Fastlane address book.
Unit tests
Manual tests
CI
How it works:
https://github.com/bigcommerce/checkout-sdk-js/assets/25133454/cf646690-0022-40eb-979c-10f7bb380445
The flow should not work for customers who canceled authentication:
https://github.com/bigcommerce/checkout-sdk-js/assets/25133454/af03bc1b-d028-40c7-ae99-457191ecb8af
=> feat(payment): PAYPAL-4067 added paypal fastlane shipping selector implementation to paypal commerce fastlane shipping strategy

packages/braintree-integration/src/braintree-fastlane/braintree-fastlane-utils.spec.ts, packages/braintree-integration/src/braintree-fastlane/braintree-fastlane-utils.ts
Preselect billing with firstName and lastName for only digital items in cart
To preselect all needed data for digital items
Unit tests
**Before**
https://github.com/bigcommerce/checkout-sdk-js/assets/56301104/793fb326-1bf5-4f41-a1b8-dc2ba01b6869
**Digital Item Only**
https://github.com/bigcommerce/checkout-sdk-js/assets/56301104/3b7a30cc-cfb5-4b87-a7fb-d92af20ad7b5
**Physical Item Only**
https://github.com/bigcommerce/checkout-sdk-js/assets/56301104/16ff1343-7c0d-4623-81c5-25127a0b58cc
**Physical and Digital Items**
https://github.com/bigcommerce/checkout-sdk-js/assets/56301104/1ce5f06e-a97e-48fd-8b70-2ffdaec4fc3f
=> feat(payment): PAYPAL-4108 preselect billing with firstName and lastName for only digital items in cart

packages/braintree-integration/src/braintree-paypal-credit/braintree-paypal-credit-customer-strategy.spec.ts, packages/braintree-integration/src/braintree-paypal-credit/braintree-paypal-credit-customer-strategy.ts, packages/braintree-integration/src/braintree-paypal/braintree-paypal-customer-strategy.spec.ts, packages/braintree-integration/src/braintree-paypal/braintree-paypal-customer-strategy.ts, packages/braintree-utils/src/braintree-integration-service.ts, packages/braintree-utils/src/braintree.ts, packages/core/src/checkout-buttons/strategies/braintree/braintree-paypal-button-strategy.spec.ts, packages/core/src/checkout-buttons/strategies/braintree/braintree-paypal-button-strategy.ts, packages/core/src/checkout-buttons/strategies/braintree/braintree-paypal-credit-button-strategy.spec.ts, packages/core/src/checkout-buttons/strategies/braintree/braintree-paypal-credit-button-strategy.ts, packages/core/src/customer/strategies/braintree/braintree-paypal-credit-customer-strategy.spec.ts, packages/core/src/customer/strategies/braintree/braintree-paypal-credit-customer-strategy.ts, packages/core/src/payment/strategies/braintree/braintree-sdk-creator.ts
Update Braintree SDK commit parameter
According to the new ways of passing parameters for correct initialization process. According to a upgraded PayPal documentation
Manual testing
=> feat(payment): PAYPAL-4111 Update Braintree SDK commit parameter

.github/CODEOWNERS, packages/cardinal-integration/.eslintrc.json, packages/cardinal-integration/README.md, packages/cardinal-integration/jest.config.js, packages/cardinal-integration/project.json, packages/cardinal-integration/src/cardinal-client.spec.ts, packages/cardinal-integration/src/cardinal-client.ts, packages/cardinal-integration/src/cardinal-script-loader.spec.ts, packages/cardinal-integration/src/cardinal-script-loader.ts, packages/cardinal-integration/src/cardinal-three-d-secure-flow-v2.spec.ts, packages/cardinal-integration/src/cardinal-three-d-secure-flow-v2.ts, packages/cardinal-integration/src/cardinal-three-d-secure-flow.spec.ts, packages/cardinal-integration/src/cardinal-three-d-secure-flow.ts, packages/cardinal-integration/src/cardinal.mock.ts, packages/cardinal-integration/src/cardinal.ts, packages/cardinal-integration/src/index.ts, packages/cardinal-integration/tsconfig.json, packages/cardinal-integration/tsconfig.lib.json, packages/cardinal-integration/tsconfig.spec.json, packages/core/src/payment/strategies/cardinal/cardinal-three-d-secure-flow-v2.ts, packages/payment-integrations-test-utils/src/test-utils/address.mock.ts, packages/payment-integrations-test-utils/src/test-utils/payment-integration-service.mock.ts, packages/squarev2-integration/src/squarev2-payment-processor.spec.ts, tsconfig.base.json, workspace.json
Refactored Cardinal to use Payment Integration API and created a separate package.
Note: due to differences in types/interfaces, the strategies in core package still need to use the non-refactored Cardinal.
- For better separation between payment integrations and core Checkout SDK
- As a preparation for refactoring Cardinal-dependent strategies (eg. Cybersource)
=> feat(payment): PI-1584 move Cardinal to separate package

packages/core/src/checkout-buttons/create-checkout-button-registry.spec.ts, packages/core/src/checkout-buttons/create-checkout-button-registry.ts, packages/google-pay-integration/src/factories/button/create-google-pay-authorizenet-button-strategy.spec.ts, packages/google-pay-integration/src/factories/button/create-google-pay-authorizenet-button-strategy.ts, packages/google-pay-integration/src/factories/button/create-google-pay-checkoutcom-button-strategy.spec.ts, packages/google-pay-integration/src/factories/button/create-google-pay-checkoutcom-button-strategy.ts, packages/google-pay-integration/src/factories/button/create-google-pay-cybersource-button-strategy.spec.ts, packages/google-pay-integration/src/factories/button/create-google-pay-cybersource-button-strategy.ts, packages/google-pay-integration/src/factories/button/create-google-pay-orbital-button-strategy.spec.ts, packages/google-pay-integration/src/factories/button/create-google-pay-orbital-button-strategy.ts, packages/google-pay-integration/src/factories/button/create-google-pay-stripe-button-strategy.spec.ts, packages/google-pay-integration/src/factories/button/create-google-pay-stripe-button-strategy.ts, packages/google-pay-integration/src/factories/button/create-google-pay-worldpayaccess-button-strategy.spec.ts, packages/google-pay-integration/src/factories/button/create-google-pay-worldpayaccess-button-strategy.ts, packages/google-pay-integration/src/gateways/google-pay-gateway.spec.ts, packages/google-pay-integration/src/gateways/google-pay-gateway.ts, packages/google-pay-integration/src/google-pay-button-initialize-options.ts, packages/google-pay-integration/src/google-pay-button-strategy.spec.ts, packages/google-pay-integration/src/google-pay-button-strategy.ts, packages/google-pay-integration/src/google-pay-payment-processor.spec.ts, packages/google-pay-integration/src/index.ts
Fixed version of the reverted PR https://github.com/bigcommerce/checkout-sdk-js/pull/2432
1. Add Google Pay button strategy for Worldpay Access
2. Refactor existing logic for:
- Authorize Net
- Checkout Com
- Cybersource / BNZ
- Orbital
- Stripe v3 / Stripe UPE
- Worldpay Access
Due to the GooglePay refactoring
Tested manually/units
=> refactor(payment): PI-1558 removed googlepay buttons from checkout button registry v1

README.md
updated links to docs resources to camel case
Links to docs seems to be case sensitive ie.
`https://github.com/bigcommerce/checkout-sdk-js/blob/master/docs/classes/checkoutservice.md#executespamcheck`
Would 404, 
where as, 
`https://github.com/bigcommerce/checkout-sdk-js/blob/master/docs/classes/CheckoutService.md#executespamcheck`
is OK
`https://github.com/bigcommerce/checkout-sdk-js/blob/master/docs/classes/checkoutservice.md#executespamcheck`
Would 404, 
where as, 
`https://github.com/bigcommerce/checkout-sdk-js/blob/master/docs/classes/CheckoutService.md#executespamcheck`
is OK
=> chore(common): CHECKOUT-00 updated links in README.md

packages/core/src/cart/cart.ts
Update docs per #387
To improve understanding that cart.discountAmount is a cart-level discount while cart.discounts is  customer-entered coupons.
Verified update on local build
=> chore(common): CHECKOUT-00 update cart discountAmount and discount docs

packages/paypal-commerce-integration/src/paypal-commerce-fastlane/paypal-commerce-fastlane-payment-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-fastlane/paypal-commerce-fastlane-payment-strategy.ts, packages/paypal-commerce-utils/src/paypal-commerce-types.ts
Updated PayPalCommerceFastlanePaymentStrategy with a little feature to pre-populate cardholder name with customer fullname from billing info
To speed up purchase process with Fastlane
Manual tests
Unit tests
CI
https://github.com/bigcommerce/checkout-sdk-js/assets/25133454/6ce066a0-6d3e-419d-9c7a-1927e41f4e91
=> feat(payment): PAYPAL-4137 prepopulate cardholder name with customer billing info on Fastlane Card Component

packages/google-pay-integration/src/google-pay-button-strategy.spec.ts, packages/google-pay-integration/src/google-pay-button-strategy.ts
Avoiding calling of `updateAddress` for `digitalItems`
If we try to place order with digital item we get an error by clicking on Pay button in the GP modal window
We need to get rid of `updateAddress` request for  `digitalItems` on PDP
Before
https://github.com/bigcommerce/checkout-sdk-js/assets/99336044/d6ff1cb2-f25e-48c5-b103-714f024acdb2
After
https://github.com/bigcommerce/checkout-sdk-js/assets/99336044/bfa573de-00b0-4ccd-8531-30804bdb1f42
=> feat(payment): PAYPAL-4123 Avoiding calling of updateAddress for digitalItems

packages/apple-pay-integration/src/apple-pay-customer-strategy.spec.ts, packages/apple-pay-integration/src/apple-pay-customer-strategy.ts, packages/apple-pay-integration/src/apple-pay-payment-strategy.spec.ts, packages/apple-pay-integration/src/apple-pay-payment-strategy.ts
Added `try {} catch {}` to solve the applepay issue with braintree initialization process when credit card feature is disabled
To get the collect data the credit card feature must to be enabled otherwise the request for getting braintree data will be failed. In this case we can not be able to use braintree integration for collecting data because we do not have clientToken for correct initialization
This is a temporary solution for a quick fix
Manual testing
=> feat(payment): PAYPAL-4051 Apple Pay throws an error in checkout due to attempting to load Braintree information

packages/paypal-commerce-integration/src/paypal-commerce-fastlane/paypal-commerce-fastlane-payment-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-fastlane/paypal-commerce-fastlane-payment-strategy.ts, packages/paypal-commerce-utils/src/paypal-commerce-types.ts
Updated getPaymentToken method payload with customer fullname in PPCP Fastlane Payment strategy
To reduce issues with missing data on PayPal side
Unit tests
Manual tests
CI
https://github.com/bigcommerce/checkout-sdk-js/assets/25133454/e0dff09b-f6ac-4da6-90bb-12bfac655497
=> feat(payment): PAYPAL-4140 updated getPaymentToken method payload with customer fullname in PPCP Fastlane Payment strategy

packages/braintree-integration/src/braintree-fastlane/braintree-fastlane-utils.ts, packages/braintree-utils/src/braintree.ts, packages/braintree-utils/src/mocks/braintree.mock.ts, packages/braintree-utils/src/utils/index.ts, packages/braintree-utils/src/utils/is-braintree-connect-name.spec.ts, packages/braintree-utils/src/utils/is-braintree-connect-name.ts, packages/core/src/payment/strategies/braintree/braintree.ts, packages/core/src/shipping/strategies/braintree/braintree-fastlane-shipping-initialize-options.ts, packages/core/src/shipping/strategies/braintree/braintree-fastlane-shipping-strategy.spec.ts, packages/core/src/shipping/strategies/braintree/braintree-fastlane-shipping-strategy.ts
Added BT Fastlane address shipping selector
To implement paypal fastlane shipping address selector
Unit tests
**Fastlane User**
https://github.com/bigcommerce/checkout-sdk-js/assets/56301104/dfb3652f-4537-4da9-8b11-87e2eea128cc
**Non Fastlane User**
https://github.com/bigcommerce/checkout-sdk-js/assets/56301104/ee537ed1-e786-4071-ad8e-01db40b26177
**Fastlane Refreshed Page**
https://github.com/bigcommerce/checkout-sdk-js/assets/56301104/1acdb75c-1fb9-4ad9-b1c2-12acbce0c047
**Fastlane Changed To Non Fastlane**
https://github.com/bigcommerce/checkout-sdk-js/assets/56301104/827873f5-f3de-4c71-b512-10c3a88e7c2a
**Canceled OTP**
https://github.com/bigcommerce/checkout-sdk-js/assets/56301104/5236c483-2e88-4b1c-956e-f66fc5ad67d6
=> feat(payment): PAYPAL-4068 added BT Fastlane address shipping selector

packages/braintree-integration/src/braintree-fastlane/braintree-fastlane-customer-strategy.ts, packages/braintree-integration/src/braintree-fastlane/braintree-fastlane-utils.spec.ts, packages/braintree-integration/src/braintree-fastlane/braintree-fastlane-utils.ts
Navigate to payment step when shipping and billing is defined
To improve BT Fastlane Experience
https://github.com/bigcommerce/checkout-sdk-js/assets/56301104/91b36f86-07c2-462b-bfbb-3013828ae5de
=> feat(payment): PAYPAL-4173 navigate to payment step when shipping and billing is defined

docs/interfaces/BraintreeThreeDSecureOptions.md, packages/braintree-utils/src/braintree.ts, packages/core/src/payment/strategies/braintree/braintree-payment-options.ts, packages/core/src/payment/strategies/braintree/braintree-payment-processor.spec.ts, packages/core/src/payment/strategies/braintree/braintree-payment-processor.ts, packages/core/src/payment/strategies/braintree/braintree.mock.ts, packages/core/src/payment/strategies/braintree/braintree.ts
Add the additionalInformation object containing the acsWindowSize property to the Braintree configuration
To allow control of the 3D Secure iframe window size - as per #2520 
Verified with different configurations giving correctly sized iframe
=> feat(payment): PAYPAL-2520 Add 3d secure iframe window size property

packages/core/src/embedded-checkout/resizable-iframe-creator.ts
Solution is instead of using iframe.allowPaymentRequest = true use allow="payment" in following file checkout-sdk-js/packages/core/src/embedded-checkout/resizable-iframe-creator.ts (line no. 27)
I have not removed  iframe.allowPaymentRequest = true for now. I have just added iframe.allow = payment as new line.
Apple Safari has given 17 release and now it supports apple pay. 
But in embedded checkout we need to pass allow="payment" as attribute in iframe. Right now the attribute is iframe.allowPaymentRequest = true. allowPaymentRequest attribute is deprecated and now It's allow="payment"
To support apple pay using embedded checkout on Safari browser.
=> fix(embedded-checkout): ISSUE-2189 Update Iframe property in embedded checkout to allow apple pay

packages/core/project.json, packages/core/src/bundles/checkout-sdk.ts, packages/hosted-form-v2/api-extractor/hosted-form-v2-iframe-content.json, packages/hosted-form-v2/api-extractor/hosted-form-v2-iframe-host.json, packages/hosted-form-v2/project.json, packages/hosted-form-v2/src/bundles/hosted-form-v2-iframe-content.ts, packages/hosted-form-v2/src/bundles/hosted-form-v2-iframe-host.ts, packages/hosted-form-v2/src/common/types/card-validator.d.ts, packages/hosted-form-v2/src/common/types/webpack.d.ts, packages/hosted-form-v2/src/create-hosted-form-service.ts, packages/hosted-form-v2/src/hosted-form.spec.ts, packages/hosted-form-v2/src/index.ts, packages/hosted-form-v2/src/payment/bigpay-client.d.ts, packages/hosted-form-v2/tsconfig.json, webpack-common.config.js
Fix the build issue that is preventing `api-extractor` from compiling types defined in `hosted-form-v2` package. The problem is due to `api-extractor` not able to reference monorepo packages, such as `@bigcommerce/hosted-form-v2`. To fix this, I've created a new `build-dts` task within `hosted-form-v2` so that it can call `api-extractor` without referencing the monorepo package from `core`.
This is an incremental step towards making `hosted-form-v2` a standalone package that can be used for Checkout, Manual Orders, and My Account.
CircleCI
=> CHECKOUT-8284: Fix build issue affecting `hosted-form-v2` package

docs/interfaces/BraintreeThreeDSecureOptions.md, packages/core/src/payment/strategies/braintree/braintree-payment-options.ts, packages/core/src/payment/strategies/braintree/braintree-payment-processor.spec.ts, packages/core/src/payment/strategies/braintree/braintree-payment-processor.ts
Add challengeRequested property to pass to Braintree sdk
Give the choice as to whether to force a 3D Secure challenge where possible. See issue here - #2518 
See in Braintree with challengeRequested set to true
And when challengeRequested is set to false
=> feat(payment): PAYPAL-2518 Add challengeRequested property to 3D Secure

packages/core/src/shipping/strategies/paypal-commerce/paypal-commerce-fastlane-shipping-strategy.spec.ts, packages/core/src/shipping/strategies/paypal-commerce/paypal-commerce-fastlane-shipping-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-fastlane/paypal-commerce-fastlane-customer-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-fastlane/paypal-commerce-fastlane-customer-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-fastlane/paypal-commerce-fastlane-payment-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-fastlane/paypal-commerce-fastlane-payment-strategy.ts
Updated PPCP Fastlane strategies to trigger the flow only for Guests
PayPal Fastlane does not support store member experience
Unit tests
Manual tests
CI
The result of the work:
On sign up and sign in customer does not get Fastlane experience
https://github.com/bigcommerce/checkout-sdk-js/assets/25133454/2f182853-f98d-4d0a-b0fa-cbc54a689ccf
https://github.com/bigcommerce/checkout-sdk-js/assets/25133454/bcaf0e59-29b0-4752-b86f-503e22f41b8e
=> refactor(payment): PAYPAL-3598 updated PPCP Fastlane strategies to trigger the flow only for Guests

packages/braintree-integration/src/braintree-fastlane/braintree-fastlane-customer-strategy.spec.ts, packages/braintree-integration/src/braintree-fastlane/braintree-fastlane-customer-strategy.ts, packages/braintree-integration/src/braintree-fastlane/braintree-fastlane-payment-strategy.spec.ts, packages/braintree-integration/src/braintree-fastlane/braintree-fastlane-payment-strategy.ts, packages/core/src/shipping/strategies/braintree/braintree-fastlane-shipping-strategy.spec.ts, packages/core/src/shipping/strategies/braintree/braintree-fastlane-shipping-strategy.ts
Updated Braintree Fastlane strategies to run the flow only for guest users
PayPal Fastlane does not support store member experience
Unit tests
Manual tests
CI
The result of the work:
On sign up and sign in customer does not get Fastlane experience
https://github.com/bigcommerce/checkout-sdk-js/assets/25133454/2f182853-f98d-4d0a-b0fa-cbc54a689ccf
https://github.com/bigcommerce/checkout-sdk-js/assets/25133454/bcaf0e59-29b0-4752-b86f-503e22f41b8e
=> refactor(payment): PAYPAL-4251 updated Braintree Fastlane strategies to run the flow only for guests

packages/paypal-commerce-integration/src/paypal-commerce-credit-card/paypal-commerce-credit-cards-payment-initialize-options.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit-card/paypal-commerce-credit-cards-payment-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit-card/paypal-commerce-credit-cards-payment-strategy.ts
Added onCreditCardFieldsRenderingError callback to ppcp cc payment strategy to let handle an error on UI side
Sometimes, when customer quickly switches between different checkout steps, the async credit card initialization process can occur an error related to missing container for PayPal field. Therefore, it shows developer's related error for a customer who should not see it. Hence, the error can be handled on UI side in the way how it should be in merchant's dev perspective.
Unit tests
CI
Before:
https://github.com/bigcommerce/checkout-sdk-js/assets/25133454/b10777ca-8031-4101-85c6-ca1aea641a0f
After:
https://github.com/bigcommerce/checkout-sdk-js/assets/25133454/c32b6fc3-8ec9-4d46-a52b-d91240fbbec1
=> feat(payment): PAYPAL-4231 added onCreditCardFieldsRenderingError callback to ppcp cc payment strategy to let handle an error on UI side

packages/mollie-integration/src/create-mollie-payment-strategy.ts
Mollie ApplePay fix
Mollie ApplePay works via Mollie Redirect, so our ApplePay implementation is not working with Mollie.
I've changed Mollie payment strategy resolver to fix this problem
Before fix:
https://github.com/bigcommerce/checkout-sdk-js/assets/79574476/88e7c41a-6853-4283-8870-bdf3498d73cb
After fix:
https://github.com/bigcommerce/checkout-sdk-js/assets/79574476/d865b987-307a-4457-8afd-2adcbd3781f6
=> fix(payment): PI-831 fixed mollie ApplePay redirect

packages/td-bank-integration/src/td-online-mart-payment-strategy.spec.ts, packages/td-bank-integration/src/td-online-mart-payment-strategy.ts
Added additional check for digital items in the cart to decide whether or not to add verification nonce to `submitPayment` payload in TD Bank.
With both digital and physical items in the cart, the `trustedShippingAddress` value is set to true, so the verification nonce wasn't added to the `submitPayment` payload. However, verification nonce seems to be required for payments when there are digital items in the cart.
Unit + manual testing
Before:
After:
=> fix(payment): PI-2161 [TDOnlineMart] fix issue with vaulted card payment when mixed products in the cart

packages/paypal-commerce-integration/src/paypal-commerce-alternative-methods/paypal-commerce-alternative-methods-payment-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-alternative-methods/paypal-commerce-alternative-methods-payment-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-integration-service.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-integration-service.ts
Added patch method on PayPal order creation for non instant payment methods for PPCP APMs
Non instant payment methods has a bit different flow of submitting an order, so we should firstly patch the order to send request to the bank and then submit it after approval.
Unit tests
Manual tests
CI
=> feat(payment): PAYPAL-3273 added patch method on paypal order creation for non instant payment methods PPCP

packages/core/src/checkout-buttons/strategies/braintree/braintree-paypal-button-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-button-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-payment-strategy.ts
Corrected amount parameter
For the right calculation of PayLater Messaging amount
Manual
=> feat(payment): PAYPAL-4292 Pay Later messaging at payment step of Checkout is based off of Order subtotal instead of grand total

packages/core/src/checkout-buttons/create-checkout-button-initializer.spec.ts, packages/core/src/checkout-buttons/create-checkout-button-initializer.ts
Updated `createCheckoutButtonInitializer` with default initialization config param for `createCheckoutStore` function
There was an issue that host option provided to `createCheckoutButtonInitializer` did not use in checkout api requests. Default request sender uses window.location.origin param as default when getHost method from store state returns empty string. The main problem is Headless stores do not have a chance to change default host, so checkout api calls fails due to the wrong domain origin, however payment api requests work as expected.
Unit tests
Manual tests
Before this fix paypal commerce request used host option provided into createCheckoutButtonInitializer, while checkout-settings request used `window.location.origin`:
After the fix, all requests uses the same host and api …
=> feat(checkout): PAYPAL-4200 provided initial state config for store creation on createCheckoutButtonInitializer

packages/core/src/cart/cart.ts, packages/core/src/currency/currency.ts, packages/core/src/currency/index.ts
Fix linter issue with Currency type
Fix linter issue after moving cyrrencyService to integration package.
Rollback [Currency type file remove](https://github.com/bigcommerce/checkout-sdk-js/pull/2551/files#diff-cf124d541c75e573d964722fa2590f77d2518c56f76014943a4953cb3555e760)
PR: [https://github.com/bigcommerce/checkout-sdk-js/pull/2551](https://github.com/bigcommerce/checkout-sdk-js/pull/2551)
Before:
After:
=> fix(payment): STRIPE-385 Fix linter issue

packages/braintree-integration/src/braintree-visa-checkout/braintree-visa-checkout-customer-strategy.spec.ts, packages/braintree-integration/src/braintree-visa-checkout/braintree-visa-checkout-customer-strategy.ts, packages/braintree-integration/src/braintree-visa-checkout/braintree-visa-customer-initialize-options.ts, packages/braintree-integration/src/braintree-visa-checkout/create-braintree-cisa-checkout-customer-strategy.spec.ts, packages/braintree-integration/src/braintree-visa-checkout/create-braintree-visa-checkout-customer-strategy.ts, packages/braintree-integration/src/index.ts
Move BraintreeVisaCheckout customer strategy to braintree-integration package
According to the new integration API
https://github.com/bigcommerce/checkout-sdk-js/assets/99336044/5eac91aa-12b7-4cd9-8e3c-0dbffe444f59
With styles updates
=> feat(payment): PAYPAL-2613 Move BraintreeVisaCheckout customer strategy to braintree-integration package

.circleci/config.yml, package-lock.json, package.json
Update to use node 20.
Node 18 is already in maintenance mode, so it makes sense to move to next active version.
- CI
=> chore(common): CHECKOUT-8410 Update to use node20

packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-button-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-button-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-customer-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-customer-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-types.ts, packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-button-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-button-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-customer-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-customer-strategy.ts
Reverted PPCP onShippingAddressChange and onShippingOptionChange callbacks
To support Pay Now With Venmo Button
Unit tests
https://github.com/bigcommerce/checkout-sdk-js/assets/56301104/ef892de3-a481-4f27-97e6-6c7d47e31d88
https://github.com/bigcommerce/checkout-sdk-js/assets/56301104/79ccca7b-f8bf-4787-a9c0-bd26227b9a70
https://github.com/bigcommerce/checkout-sdk-js/assets/56301104/47041435-b7fb-4271-9ee0-8258a3efc8ce
https://github.com/bigcommerce/checkout-sdk-js/assets/56301104/c6d3f0d9-0b74-4fd4-a194-784e353e558a
=> feat(payment): PAYPAL-4284 reverted PPCP onShippingAddressChange and onShippingOptionChange callbacks

packages/google-pay-integration/src/factories/customer/create-google-pay-tdonlinemart-customer-strategy.spec.ts, packages/google-pay-integration/src/factories/customer/create-google-pay-tdonlinemart-customer-strategy.ts, packages/google-pay-integration/src/index.ts
checkout-js part: https://github.com/bigcommerce/checkout-js/pull/1910
Add Google Pay on TD Online Mart in button payment step
As a merchant I want to be able to offer my shoppers Google Pay wallet through TD Online Mart
Work on backend part of this project is not started yet. Therefore added part of the code will not execute before BE part will be ready.
=> feat(payment): PI-2284 Add Google Pay on TD Online Mart - checkout customer step

packages/core/src/billing/billing-address-action-creator.spec.ts, packages/core/src/billing/billing-address-action-creator.ts
Fix issue with billing address creation, when a user logs in from control panel.
We have an issue if a login happens from control panel we assign the guest cart to shopper but billing address object is not created, when the checkbox `billing address is same as shipping is unchecked`.
Which leads to an issue in billing step of checkout, since we try and use customer address id as billing address id for update. Hence add a check and for billing address.
- CI
- Screencast
https://github.com/bigcommerce/checkout-sdk-js/assets/7134802/0a262b9c-9b49-46d1-b00e-66f67340d922
=> fix(billing): CHECKOUT-8392 Fix issue with billing address creation

packages/braintree-integration/src/braintree-fastlane/braintree-fastlane-customer-strategy.ts
Fixed the issue with Braintree Fastlane initialization process by changing provided initial method id with valid payment id for current flow
The main problem was due to A/B testing process where braintreeacceleratedcheckout payment method does not load on the page, so we should use braintree payment method for such purposes. There was a mistake in one of the prev PRs.
Unit tests
Manual tests
CI
=> fix(payment): PAYPAL-4379 fixed the issue with Braintree Fastlane initialization process

packages/core/src/shipping/strategies/paypal-commerce/paypal-commerce-fastlane-shipping-strategy.spec.ts, packages/core/src/shipping/strategies/paypal-commerce/paypal-commerce-fastlane-shipping-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-fastlane/paypal-commerce-fastlane-customer-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-fastlane/paypal-commerce-fastlane-customer-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-fastlane/paypal-commerce-fastlane-payment-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-fastlane/paypal-commerce-fastlane-payment-strategy.ts, packages/paypal-commerce-utils/src/paypal-commerce-types.ts
Updated PayPalCommerce Fastlane strategies with Fastlane flag to be able to turn on/off Fastlane custom styling
To set Fastlane styling provided from CP only if merchant turned on the feature in settings
Manual tests
Unit tests
CI
=> feat(payment): PAYPAL-4440 updated ppcp fastlane strategies with fastlane flag to be able to turn on/off fastlane custom styling

packages/braintree-integration/src/braintree-fastlane/braintree-fastlane-customer-strategy.spec.ts, packages/braintree-integration/src/braintree-fastlane/braintree-fastlane-customer-strategy.ts, packages/braintree-integration/src/braintree-fastlane/braintree-fastlane-payment-strategy.spec.ts, packages/braintree-integration/src/braintree-fastlane/braintree-fastlane-payment-strategy.ts, packages/braintree-utils/src/braintree.ts, packages/braintree-utils/src/utils/get-fastlane-styles.ts, packages/core/src/payment/strategies/braintree/braintree.ts, packages/core/src/shipping/strategies/braintree/braintree-fastlane-shipping-strategy.spec.ts, packages/core/src/shipping/strategies/braintree/braintree-fastlane-shipping-strategy.ts
Updated Braintree Fastlane strategies with isFastlaneStylingEnabled flag
To be able to turn on/off Fastlane styling settings provided by merchant through configuration from CP
Unit tests
Manual tests
CI
=> feat(payment): PAYPAL-4441 updated Braintree Fastlane strategies with isFastlaneStylingEnabled flag

packages/stripe-integration/src/stripe-upe/stripe-upe-payment-strategy.ts
Added `name` field to the Stripe `billing_details` object
Before:
After:
=> feat(payment): STRIPE-329 added name to Stripe billing_details object

packages/paypal-commerce-utils/src/paypal-commerce-fastlane-utils.spec.ts, packages/paypal-commerce-utils/src/paypal-commerce-fastlane-utils.ts
Fixed region for fastlane for Thailand (PPCP)
To avoid error
https://github.com/user-attachments/assets/2f0e0fb6-e825-4c0e-a2cd-6c417691d436
=> feat(payment): PAYPAL-4498 fixed region for fastlane for Thailand

packages/google-pay-integration/src/gateways/google-pay-gateway.ts
Fix of email passing
Because destructurization of the object will return an wrong email value in case `getBillingAddress` returns an empty string for email, but `response.email` has a non-empty value
Manual testing
=> feat(payment): PAYPAL-4524 Google Pay payments fail with error "Order is missing an email address"

packages/core/src/checkout/checkout-action-creator.spec.ts, packages/core/src/checkout/checkout-service.spec.ts, packages/core/src/checkout/checkout-store-error-selector.spec.ts, packages/core/src/checkout/checkout-store-selector.spec.ts
Removed almost all ts-ignore from core/src/checkout folder
This tech dept was created during jest dependency update. So to keep checkout sdk as clean as possible, we should do some work in this area.
Lint & Test & Build commands passed locally
CI
=> refactor(checkout): PAYPAL-4527 removed almost all ts-ignore from core/src/checkout folder

packages/core/src/billing/billing-address-action-creator.spec.ts
Removed ts-ignore and updated tests in core/src/billing folder
To reduce tech debt after updating jest to v26
Test & lint & build commands passed locally
CI
=> refactor(payment): PAYPAL-4531 removed ts-ignore and updated tests in core/src/billing folder

packages/google-pay-integration/src/utils/items-require-shipping.ts
Remove experiment code for CHECKOUT-4936_enable_custom_item_shipping
This codepath has been ramped up for a few years now, so good idea to remove it.
- CI
=> chore(common): CHECKOUT-8523 Remove experiment code for CHECKOUT-4936_enable_custom_item_shipping

packages/stripe-integration/src/stripe-upe/stripe-upe-script-loader.ts
Fix issue with display payment methods after Stripe PI change
After Stripe PI changed this changes also should be applied on FE side before fetching updates form new PI
Before:
https://github.com/user-attachments/assets/a5d06038-6433-4c2c-95fe-c6a204ba0b30
After:
https://github.com/user-attachments/assets/74dbf49b-cd2e-4317-b1b8-565fa1bd458b
=> fix(payment): STRIPE-421 payment method issue after PI change

packages/stripe-integration/src/stripe-upe/create-stripe-upe-payment-strategy.ts
Added Klarna id to the Stripe gateway. 
Related PR: https://github.com/bigcommerce/checkout-js/pull/1956
Because we cannot open Klarna tab without this fix.
Before:
https://github.com/user-attachments/assets/d09e87c1-d413-461b-b583-516177ab2680
After:
https://github.com/user-attachments/assets/c5159738-c8f3-4f5b-b103-c2d4dd936e92
=> fix(payment): STRIPE-384 added Klarna id to the Stripe gateway

packages/stripe-integration/src/stripe-upe/stripe-upe-payment-strategy.spec.ts, packages/stripe-integration/src/stripe-upe/stripe-upe-payment-strategy.ts, packages/stripe-integration/src/stripe-upe/stripe-upe.ts
- Remove saving instrument checkbox for Stripe Link stored cards.
- Remove other payment methods for Stripe Link authorised shopper.
- We can't save instrument that was already saved for Stripe Link shopper account.
- For Stripe Link authorised shopper we should show only Stripe Link payment method
Before:
https://github.com/user-attachments/assets/0030845a-418d-4cf1-bc9a-eb8edbc6ec77
After:
https://github.com/user-attachments/assets/fbfa9f4b-bf2e-435d-bf05-0d7ba4d87b9e
Regression:
Basic Stripe Link for store visitor
https://github.com/user-attachments/assets/54d2ff75-96cd-4e8e-abcb-0735fa0b2d6f
Store authorised shopper without Stripe Link
https://github.com/user-attachments/assets/17b57f83-da88-4566-940a-acbcef59b10b
=> fix(payment): STRIPE-422 Fix saving  Stripe Link instrument

packages/paypal-commerce-integration/src/paypal-commerce-fastlane/paypal-commerce-fastlane-customer-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-fastlane/paypal-commerce-fastlane-customer-strategy.ts
Removed `PAYPAL-4142.disable_paypal_fastlane_one_click_experience` experiment usage from ppcp fastlane customer strategy
As part of experiments cleanup after Fastlane rollout
Unit tests
CI
=> refactor(payment): PAYPAL-4167 removed PAYPAL-4142.disable_paypal_fastlane_one_click_experience experiment usage from ppcp fastlane customer strategy

packages/stripe-integration/src/stripe-upe/stripe-upe-payment-strategy.spec.ts, packages/stripe-integration/src/stripe-upe/stripe-upe-payment-strategy.ts, packages/stripe-integration/src/stripe-upe/stripe-upe.ts
- Remove saving instrument checkbox for Stripe Link stored cards.
- Remove other payment methods for Stripe Link authorised shopper.
- We can't save instrument that was already saved for Stripe Link shopper account.
- For Stripe Link authorised shopper we should show only Stripe Link payment method
Before:
https://github.com/user-attachments/assets/0030845a-418d-4cf1-bc9a-eb8edbc6ec77
After:
https://github.com/user-attachments/assets/fbfa9f4b-bf2e-435d-bf05-0d7ba4d87b9e
Regression:
Basic Stripe Link for store visitor
https://github.com/user-attachments/assets/54d2ff75-96cd-4e8e-abcb-0735fa0b2d6f
Store authorised shopper without Stripe Link
https://github.com/user-attachments/assets/17b57f83-da88-4566-940a-acbcef59b10b
=> fix(payment): STRIPE-422 Fix saving Stripe Link instrument

packages/paypal-commerce-integration/src/paypal-commerce-alternative-methods/create-paypal-commerce-alternative-methods-payment-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-alternative-methods/paypal-commerce-alternative-methods-payment-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-alternative-methods/paypal-commerce-alternative-methods-payment-strategy.ts, packages/paypal-commerce-utils/src/paypal-commerce-sdk.spec.ts, packages/paypal-commerce-utils/src/paypal-commerce-sdk.ts, packages/paypal-commerce-utils/src/paypal-commerce-types.ts
Added a new configuration for loading APMs related functionality
To avoid initializaing with wrong intent value
https://github.com/user-attachments/assets/2bef14e0-af8b-468e-935e-cb9710a4c9de
=> feat(payment): PAYPAL-4550 added force reload of paypal client to avoid initializaing with wrong intent value

.github/CODEOWNERS
Fixed apple pay package name in codeowners file
To be able to set right owner rules for apple-pay-integration package
There is nothing to test
=> fix(common): PAYPAL-000 fixed apple pay package name in codeowners file

packages/braintree-utils/src/braintree-script-loader.spec.ts, packages/braintree-utils/src/braintree-script-loader.ts
Updated braintree fastlane script with valid sha hash for 3.104.0 braintree sdk version
Because prev hash caused an issue when loading on script load
Unit tests
Manual tests
CI
=> fix(payment): PAYPAL-000 updated braintree fastlane script with valid sha hash for 3.104.0 braintree sdk version

packages/core/src/checkout/checkout-service.spec.ts, packages/core/src/checkout/checkout-service.ts, packages/core/src/checkout/create-checkout-service.ts, packages/core/src/payment-integration/create-payment-integration-service.ts, packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-strategy.spec.ts, packages/core/src/shipping/shipping-country-action-creator.spec.ts, packages/core/src/shipping/shipping-country-action-creator.ts, packages/core/src/shipping/shipping-country-request-sender.spec.ts, packages/core/src/shipping/shipping-country-request-sender.ts
- Add support for displaying available shipping countries based on shipping method channel associations.
To support this we need checkout to query the shipping/countries endpoint with a channel_id through as a query parameter.
With the checkout-sdk-js and checkout-js running locally, the channel_id is piped through from checkout-sdk to checkout. The following video shows that the shipping/countries endpoint now has the query parameter channel_id passed through to it.
https://github.com/user-attachments/assets/39db2078-e888-4479-95fd-15107d74f6e2
ping @bigcommerce/team-checkout ping @bigcommerce/team-integrations
=> feat(shipping): SHIPPING-3183 Add support for channel_ids to the load shipping countries action

packages/apple-pay-integration/src/apple-pay-button-strategy.spec.ts, packages/apple-pay-integration/src/apple-pay-button-strategy.ts, packages/apple-pay-integration/src/apple-pay-customer-strategy.spec.ts, packages/apple-pay-integration/src/apple-pay-customer-strategy.ts, packages/apple-pay-integration/src/apple-pay-payment-strategy.spec.ts, packages/apple-pay-integration/src/apple-pay-payment-strategy.ts, packages/apple-pay-integration/src/create-apple-pay-button-strategy.ts, packages/apple-pay-integration/src/create-apple-pay-customer-strategy.ts, packages/apple-pay-integration/src/create-apple-pay-payment-strategy.ts
Updated apple pay strategies with `BraintreeSdk` class instead of `BraintreeIntegrationService`
`BraintreeIntegrationService` is deprecated, so to be able to remove it in the future apple pay strategies should be updated
Manual tests:
- successfully payed with apple pay on PDP page;
- successfully payed with apple pay on mini cart;
- successfully payed with apple pay on cart page;
- successfully payed with apple pay using button on top of checkout page;
- successfully payed with apple pay on payment step of checkout page;
(can't share videos, because macOs doesn't give an ability to pay with Apple Pay when screen recording is on)
Unit tests
CI
=> refactor(payment): PAYPAL-4578 updated ApplePay strategies with BraintreeSdk

packages/core/src/checkout/checkout-action-creator.ts, packages/core/src/common/data-store/cache-action.spec.ts, packages/core/src/common/data-store/cache-action.ts, packages/core/src/config/config-action-creator.spec.ts
Fix the client-side cache for the `/api/storefront/checkout-settings` and `/api/storefront/form-fields` endpoints so that the cache is used when the CheckoutService#loadCheckout or CheckoutService#loadDefaultCheckout method is called multiple times.
The client-side cache isn't working properly because the input parameter for `ConfigActionCreator` and `FormFieldActionCreator` includes the `params` field, which may contain a nested object (i.e.: `{ params: { checkoutId: id } }` and `{ params: { include: ['categoryNames'] } })`. The nested object breaks the caching as `@cacheableAction` decorator only works on shallow objects. As a result, when `ExtensionCommandType.ReloadCheckout` command is issued by an extension, we end up making repeated calls to these endpoints instead of re-using the …
=> CHECKOUT-8300: Fix config and form field cache by ensuring input parameters are correctly compared

packages/core/src/checkout/checkout-action-creator.ts, packages/core/src/common/data-store/cache-action.spec.ts, packages/core/src/common/data-store/cache-action.ts, packages/core/src/config/config-action-creator.spec.ts
Restore https://github.com/bigcommerce/checkout-sdk-js/pull/2615
It was reverted due to unexpected test failures. I couldn't resolve the failures at the end of the day so I reverted the PR to avoid blocking teams working in other timezones.
See the original PR
=> Revert "Revert "CHECKOUT-8300: Fix config and form field cache by ensuring input parameters are correctly compared""

packages/core/src/checkout/checkout-service.spec.ts, packages/core/src/checkout/checkout-service.ts, packages/core/src/checkout/create-checkout-service.ts, packages/core/src/payment-integration/create-payment-integration-service.ts, packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-strategy.spec.ts, packages/core/src/shipping/shipping-country-action-creator.spec.ts, packages/core/src/shipping/shipping-country-action-creator.ts, packages/core/src/shipping/shipping-country-request-sender.spec.ts, packages/core/src/shipping/shipping-country-request-sender.ts
This is a revert of the revert. i.e. we are re-raising this [PR](https://github.com/bigcommerce/checkout-sdk-js/pull/2579) 
This adds support for displaying available shipping countries based on shipping method channel associations.
To support this we need checkout to query the shipping/countries endpoint with a channel_id through as a query parameter.
With the checkout-sdk-js and checkout-js running locally, the channel_id is piped through from checkout-sdk to checkout. The following video shows that the shipping/countries endpoint now has the query parameter channel_id passed through to it.
https://github.com/user-attachments/assets/39db2078-e888-4479-95fd-15107d74f6e2
ping @bigcommerce/team-checkout
=> Revert "Revert "feat(shipping): SHIPPING-3183 Add support for channel_ids to the load shipping countries action""

packages/bluesnap-direct-integration/src/bluesnap-direct-apm/bluesnap-direct-apm-payment-strategy.spec.ts, packages/bluesnap-direct-integration/src/bluesnap-direct-apm/bluesnap-direct-apm-payment-strategy.ts, packages/bluesnap-direct-integration/src/utils/is-bluesnap-direct-instrument.ts, packages/payment-integration-api/src/index.ts, packages/payment-integration-api/src/payment/index.ts, packages/payment-integration-api/src/payment/payment.ts
Pay By Bank is a supported payment method - [Pay by Bank (Open Banking)](https://developers.bluesnap.com/reference/pay-by-bank)
Allow shoppers to input IBAN in the Pay By Bank payment step
To allow shoppers to use Pay by Bank method
...
=> feat(payment): PI-2403 Pay by Bank integration

packages/hosted-form-v2/src/hosted-field.ts, packages/hosted-form-v2/src/iframe-content/hosted-input-manual-order-payment-handler.ts, packages/hosted-form-v2/src/payment/manual-order-payment-request-sender.ts
Throw error when the payments endpoint returns `type: error/failure` with status 200.
So that error can be better handled on manual order UI and appropriate message could be displayed.
- CI checks
=> feat(checkout): CHECKOUT-8587 Throw error when payment endpoint returns error/failure

packages/core/src/payment-integration/create-payment-integration-service.ts, packages/core/src/payment-integration/default-payment-integration-service.spec.ts, packages/core/src/payment-integration/default-payment-integration-service.ts, packages/core/src/payment/payment-strategy-action-creator.ts, packages/core/src/payment/payment-strategy-widget-action-creator.spec.ts, packages/core/src/payment/payment-strategy-widget-action-creator.ts, packages/payment-integration-api/src/payment-integration-service.ts
Make `widgetInteraction` action from `PaymentStrategyActionCreator` available for payment integration packages
Need this action for migration [AmazonPay payment strategy](https://github.com/bigcommerce/checkout-sdk-js/blob/master/packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-strategy.ts#L203) to integration package
https://github.com/user-attachments/assets/18497b06-fbe9-480c-b369-b32b20f817ae
=> feat(payment): PI-2551 make widgetInteraction action available for integration packages

packages/amazon-pay-integration/.eslintrc.json, packages/amazon-pay-integration/src/amazon-pay-v2-payment-initialize-options.ts, packages/amazon-pay-integration/src/amazon-pay-v2-payment-strategy.spec.ts, packages/amazon-pay-integration/src/amazon-pay-v2-payment-strategy.ts, packages/amazon-pay-integration/src/create-amazon-pay-v2-payment-strategy.spec.ts, packages/amazon-pay-integration/src/create-amazon-pay-v2-payment-strategy.ts, packages/amazon-pay-integration/src/index.ts, packages/amazon-pay-utils/jest.config.js, packages/amazon-pay-utils/src/amazon-pay-v2-payment-processor.spec.ts, packages/amazon-pay-utils/src/amazon-pay-v2-payment-processor.ts, packages/amazon-pay-utils/src/amazon-pay-v2-script-loader.spec.ts, packages/amazon-pay-utils/src/amazon-pay-v2.ts, packages/amazon-pay-utils/src/index.ts, packages/amazon-pay-utils/src/isAmazonPayAdditionalActionError.spec.ts, packages/amazon-pay-utils/src/isAmazonPayAdditionalActionError.ts, packages/amazon-pay-utils/src/isInternalCheckoutSelectors.spec.ts, packages/amazon-pay-utils/src/isInternalCheckoutSelectors.ts, packages/amazon-pay-utils/src/mocks/amazon-pay-v2.mock.ts, packages/core/src/shipping/strategies/amazon-pay-v2/amazon-pay-v2-shipping-strategy.spec.ts
Migrate Amazon Pay payment strategy to package
To update payment integration package logic for Amazon pay.
https://github.com/user-attachments/assets/3de8e861-bc82-4b2e-a2b0-532a03cc4456
https://github.com/user-attachments/assets/b18e9f2c-2050-461f-8af5-7df4334beb1d
=> feat(payment): PI-1617 Move AmazonPay payments strategy

packages/core/src/payment-integration/default-payment-integration-service.spec.ts, packages/core/src/payment-integration/default-payment-integration-service.ts, packages/payment-integration-api/src/payment-integration-service.ts, packages/payment-integrations-test-utils/src/test-utils/payment-integration-service.mock.ts
Make remoteCheckoutActionCreator.signOut available for integration packages
Will use this action for migration AmazonPay customer strategy to integration package.
Unit test
=> feat(payment): PI-2592 Make remoteCheckoutActionCreator.signOut available for integration packages

packages/google-pay-integration/src/gateways/google-pay-braintree-gateway.ts, packages/google-pay-integration/src/gateways/google-pay-gateway.ts, packages/google-pay-integration/src/google-pay-payment-processor.ts
Moved Braintree Google Pay request data params preparation from initialize to getPaymentGatewayParameters method.
The issue with Braintree Google Pay button for BuyNow flow occurs due to the issues with getting data from state cart object, since it was not created yet.
Unit tests
Manual tests
CI
Proof for order with digital item:
https://github.com/user-attachments/assets/fca6986e-13a1-4c87-825a-3ece4b9f7f5c
Proof for order with physical item:
https://github.com/user-attachments/assets/527bd95d-9237-44ee-a56d-2cb112e73293
=> fix(payment): PAYPAL-4649 fixed the issue with Braintree Google Pay button for Buy Now flow

packages/braintree-utils/src/types.ts, packages/braintree-utils/src/utils/get-fastlane-styles.ts
Fixed mapping of fastlane styles that comes from backend
To style fastlane component properly
=> fix(payment): PAYPAL-4594 fixed mapping of fastlane styles that comes from backend

packages/amazon-pay-integration/src/amazon-pay-v2-customer-initialize-options.ts, packages/amazon-pay-integration/src/amazon-pay-v2-customer-strategy.spec.ts, packages/amazon-pay-integration/src/amazon-pay-v2-customer-strategy.ts, packages/amazon-pay-integration/src/create-amazon-pay-v2-customer-strategy.spec.ts, packages/amazon-pay-integration/src/create-amazon-pay-v2-customer-strategy.ts, packages/amazon-pay-integration/src/index.ts, packages/amazon-pay-integration/src/mock/amazon-pay-v2-customer.mock.ts
Migrate AmazonPay to package
To keep payment integration strategies in separate package
https://github.com/user-attachments/assets/135198d1-34f9-4901-9e30-cdda223bbb9c
=> feat(payment): PI-2548 Move AmazonPay customer strategy

packages/paypal-commerce-utils/src/paypal-commerce-types.ts, packages/paypal-commerce-utils/src/utils/get-fastlane-styles.ts
Fixed  PPCP mapping of fastlane styles that comes from backend
To fixed fastlane styles
=> fix(payment): PAYPAL-4594 fixed  PPCP mapping of fastlane styles that comes from backend

packages/amazon-pay-integration/src/amazon-pay-v2-button-options.ts, packages/amazon-pay-integration/src/amazon-pay-v2-button-strategy.spec.ts, packages/amazon-pay-integration/src/amazon-pay-v2-button-strategy.ts, packages/amazon-pay-integration/src/amazon-pay-v2-request-sender.spec.ts, packages/amazon-pay-integration/src/amazon-pay-v2-request-sender.ts, packages/amazon-pay-integration/src/create-amazon-pay-v2-button-strategy.spec.ts, packages/amazon-pay-integration/src/create-amazon-pay-v2-button-strategy.ts, packages/amazon-pay-integration/src/errors/amazon-pay-v2-config-creation-error.spec.ts, packages/amazon-pay-integration/src/errors/amazon-pay-v2-config-creation-error.ts, packages/amazon-pay-integration/src/index.ts, packages/amazon-pay-integration/src/isWithBuyNowFeatures.spec.ts, packages/amazon-pay-integration/src/isWithBuyNowFeatures.ts, packages/amazon-pay-integration/src/mock/amazon-pay-v2-button.mock.ts, packages/amazon-pay-integration/src/mock/amazon-pay-v2-config-request-sender.mock.ts
Migrate Amazon Pay button strategy to integration package
To keep payment integration strategies in integration packages
Unit tests and manually tested
https://github.com/user-attachments/assets/efdf1877-b56a-4114-b468-a805c1c0ed15
https://github.com/user-attachments/assets/28c392cc-832d-4685-9a2e-5f69400db308
=> feat(payment): PI-2549 Move AmazonPay button strategy

packages/paypal-commerce-integration/src/paypal-commerce-fastlane/paypal-commerce-fastlane-payment-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-fastlane/paypal-commerce-fastlane-payment-strategy.ts
Avoiding redundant order creation requests
To avoid order request when card fields are invalid
https://github.com/user-attachments/assets/d034f65f-5324-449c-bebb-18a5a0a8bb98
=> fix(payment): PAYPAL-4610 Avoiding redundant order creation requests

packages/braintree-integration/src/braintree-venmo/braintree-venmo-button-strategy.ts
Added an ability to pass custom button height for Braintree Venmo button
To be able to make Braintree Venmo button style height the same as other buttons on product details page.
Unit tests
=> chore(payment): PAYPAL-4580 added an ability to pass custom button height for Braintree Venmo button

packages/braintree-integration/src/braintree-local-payment-methods/braintree-local-methods-payment-strategy.spec.ts, packages/braintree-integration/src/braintree-local-payment-methods/braintree-local-methods-payment-strategy.ts, packages/braintree-integration/src/is-phone-number-instrument-like.ts, packages/braintree-utils/src/types.ts, packages/core/src/order/order-request-body.ts, packages/core/src/payment/payment.ts, packages/payment-integration-api/src/index.ts, packages/payment-integration-api/src/order/order-request-body.ts, packages/payment-integration-api/src/payment/index.ts, packages/payment-integration-api/src/payment/payment.ts
Update Braintree LPMs strategy by adding functionality for Trustly
To be able place an order via Braintree Trustly payment method
=> feat(payment): PAYPAL-4611 Update Braintree LPMs strategy by adding functionality for Trustly

packages/paypal-commerce-integration/src/paypal-commerce-fastlane/paypal-commerce-fastlane-payment-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-fastlane/paypal-commerce-fastlane-payment-strategy.ts
This reverts commit 1336b4c4ad89c666a4171d82c8c72b9607ec735d.
Revert https://github.com/bigcommerce/checkout-sdk-js/pull/2632 PR
Because it brakes PayPal Commerce Fastlane flow for fastlane users with vaulted instruments
Manual tests
=> Revert "fix(payment): PAYPAL-4610 Avoiding redundant order creation requests (#2632)"

package-lock.json, package.json
Move `tslib` back to production dep
FIx `checout-js` test issue.
```
TypeError: (0 , u.__spreadArray) is not a function
```
CI.
=> fix(checkout): CHECKOUT-8653 Move tslib back to production dep

package-lock.json, package.json
Reverts bigcommerce/checkout-sdk-js#2664
Due to ` TypeError: (0 , u.__spreadArray) is not a function` issue in `checkout-js`.
=> Revert "fix(checkout): CHECKOUT-8653 Move tslib back to production dep"

packages/braintree-integration/src/braintree-paypal/braintree-paypal-payment-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-payment-strategy.ts
Updated error checking
We are getting an error message `Cannot read properties of undefined (reading 'privider_error')` because of a possible empty array. To avoid it we need to add an additional check.
Manual testing
=> feat(payment): PAYPAL-4681 Cannot read properties of undefined (reading 'provider__error")

packages/apple-pay-integration/src/apple-pay-button-strategy.spec.ts, packages/apple-pay-integration/src/apple-pay-customer-strategy.spec.ts, packages/apple-pay-integration/src/apple-pay-payment-strategy.spec.ts, packages/apple-pay-integration/src/mocks/apple-pay-payment.mock.ts, tsconfig.base.json
Fixed Typescript errors in apple-pay-integration package
Due to Typescript and Jest last updates
=> refactor(payment): PI-2678 fixed Typescript errors in apple-pay-integration package

packages/apple-pay-integration/src/apple-pay-payment-strategy.ts, packages/apple-pay-integration/src/apple-pay.ts
Fixed BT credit card duplicate when fastlane turned on
To fix issue
Without Fastlane
https://github.com/user-attachments/assets/adc8121c-4680-4b6d-b237-03f984f32118
With Fastlane
https://github.com/user-attachments/assets/122c5a85-48eb-4371-99b7-bd05f6c9fa94
=> fix(payment): PAYPAL-4704 fixed duplicate credit card payment

package-lock.json, package.json, packages/core/src/locale/language-config.ts, packages/core/src/locale/language-service.spec.ts, packages/core/src/locale/language-service.ts
Switch to using `intl-messageformat` instead of `messageformat` for translations, as the latter is incompatible with the CSP `script-src 'nonce-xxx' 'strict-dynamic'`  header used in checkout.
When translating messages at runtime, `messageformat` relies on `new Function` (similar to `eval`), which violates the `strict-dynamic` rule because it disallows any unsafe `eval` expressions (https://github.com/messageformat/messageformat/issues/180). In contrast, `intl-messageformat` does not use any unsafe `eval` expressions.
`intl-messageformat` can serve as a drop-in replacement for `messageformat`, as both libraries adhere to the [ICU MessageFormat](https://unicode-org.github.io/icu/userguide/format_parse/messages/) standards.
https://github.com/user-attachments/assets/1cd8f7c1-2df6-4f27-be88-1 …
=> CHECKOUT-8519: Switch messageformat library to be compatible with strict-dynamic CSP header

package-lock.json, package.json, packages/core/src/locale/language-config.ts, packages/core/src/locale/language-service.spec.ts, packages/core/src/locale/language-service.ts
It causes test failures because `init-messageformat` handles missing template variables and `'` single quote character differently compared to `messageformat`.
Reverts bigcommerce/checkout-sdk-js#2674
=> Revert "CHECKOUT-8519: Switch messageformat library to be compatible with strict-dynamic CSP header"

packages/hosted-form-v2/src/iframe-content/hosted-input-validator.spec.ts, packages/hosted-form-v2/src/iframe-content/hosted-input-validator.ts
Make hosted payment note field a required field for a payment.
Product requirement.
https://github.com/user-attachments/assets/26095fee-2d27-4b54-9d54-9d1ed027bf67
=> feat(checkout): CHECKOUT-8606 Make Payment Note Required

package-lock.json, package.json, packages/core/src/locale/language-config.ts, packages/core/src/locale/language-service.spec.ts, packages/core/src/locale/language-service.ts
Reverts bigcommerce/checkout-sdk-js#2682 and includes fixes to address the issues that led to the revert.
The problems were:
* The `translate` method throws an error if there are missing data for template variables.
* The `translate` method strips out `'` single quote character when used next to HTML tags because it is used as an [escape](https://unicode-org.github.io/icu/userguide/format_parse/messages/#quotingescaping) character.
This video shows that checkout works with `script-src` CSP header.
https://github.com/user-attachments/assets/aa5aeeed-2440-4571-9977-67aabcaa3c10
This screenshot shows that checkout can still be translated in a different language.
These are the new tests added to ensure that
* The `translate` method doesn't throw an error if there are missing data for template …
=> Restore "CHECKOUT-8519: Switch messageformat library to be compatible with strict-dynamic CSP header"

packages/google-pay-integration/src/gateways/google-pay-gateway.spec.ts, packages/google-pay-integration/src/gateways/google-pay-gateway.ts
Add opportunity to select recommended option by default if existed
To avoid situation with non-right selected option by default, when default shipping option exclude pick up
https://github.com/user-attachments/assets/9655ed03-d2c6-4a8f-81f8-7cdb807dba88
=> feat(payment): PAYPAL-4700 Google Pay defaulting to pickup in store option when checkout setting exclude it

packages/core/src/shipping/shipping-country-action-creator.spec.ts, packages/core/src/shipping/shipping-country-action-creator.ts, packages/core/src/shipping/shipping-country-request-sender.spec.ts, packages/core/src/shipping/shipping-country-request-sender.ts
- Allow for a default of `null` channel ID to be sent to the the `v1/shipping/countries` endpoint
Merchants who attempt to call the `loadShippingCountries` endpoint before initialising a checkout will run into issues with the existing `getCheckoutOrThrow()` behaviour because the checkout is not yet initialised.
With this updated code, if there is no checkout, we set the `channel id` to null and proceed to send no channel ID to the `v1/shipping/countries` endpoint. 
This will result in the existing behaviour before we introduced the `channel id` property. 
As a result of this, it will mean that merchants will view the country selector based on the shipping zone location and NOT have it be channel aware.
Existing Unit Test
ping @animesh1987 @bc-peng
=> feat(shipping): SHIPPING-3311 Update loadShippingCountries to allow for a default of no channel id

packages/apple-pay-integration/src/apple-pay-button-initialize-options.ts, packages/apple-pay-integration/src/apple-pay-button-strategy.spec.ts, packages/apple-pay-integration/src/apple-pay-button-strategy.ts, packages/apple-pay-integration/src/mocks/apple-pay-method.mock.ts
Added styling for Apple Pay button
To not use styling from strorefront and for consistency
https://github.com/user-attachments/assets/e0639db2-cddb-47fa-a974-dcf35063ee69
https://github.com/user-attachments/assets/88241155-1567-4e3d-822b-113c27fbe5b5
=> feat(payment): PAYPAL-4737 Apple Pay button style does not apply to storefront

packages/core/src/checkout-buttons/strategies/braintree/braintree-paypal-button-options.ts, packages/core/src/checkout-buttons/strategies/braintree/braintree-paypal-button-strategy.spec.ts, packages/core/src/checkout-buttons/strategies/braintree/braintree-paypal-button-strategy.ts, packages/core/src/checkout-buttons/strategies/braintree/braintree-paypal-credit-button-options.ts, packages/core/src/checkout-buttons/strategies/braintree/braintree-paypal-credit-button-strategy.spec.ts, packages/core/src/checkout-buttons/strategies/braintree/braintree-paypal-credit-button-strategy.ts
Added `onEligibilityFailure` callback for Braintree PayPal and PayLater button strategies
To be able to run related code on UI (for example: to remove html block created to contain PayPal button or console log anything and so on)
Manual tests (no errors in console related to current changes)
Unit tests
CI
=> feat(payment): PAYPAL-4698 added onEligibilityFailure callback for Braintree PayPal and PayLater button strategies

packages/paypal-commerce-integration/src/paypal-commerce-alternative-methods/paypal-commerce-alternative-methods-button-initialize-options.ts, packages/paypal-commerce-integration/src/paypal-commerce-alternative-methods/paypal-commerce-alternative-methods-button-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-alternative-methods/paypal-commerce-alternative-methods-button-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-button-initialize-options.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-button-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-button-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-venmo/paypal-commerce-venmo-button-initialize-options.ts, packages/paypal-commerce-integration/src/paypal-commerce-venmo/paypal-commerce-venmo-button-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-venmo/paypal-commerce-venmo-button-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-button-initialize-options.ts, packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-button-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-button-strategy.ts
Added `onEligibilityFailure` callback to paypal commerce buttons strategies
To be able to run related code on UI (for example: to remove html block created to contain PayPal button or console log anything and so on)
Manual tests (no errors in console related to current changes)
Unit tests
CI
=> feat(payment): PAYPAL-4697 added onEligibilityFailure callback to paypal commerce buttons strategies

packages/stripe-integration/src/index.ts, packages/stripe-integration/src/stripe-upe/create-stripe-ocs-payment-strategy.spec.ts, packages/stripe-integration/src/stripe-upe/create-stripe-ocs-payment-strategy.ts, packages/stripe-integration/src/stripe-upe/create-stripe-upe-customer-strategy.spec.ts, packages/stripe-integration/src/stripe-upe/create-stripe-upe-payment-strategy.spec.ts, packages/stripe-integration/src/stripe-upe/is-stripe-payment-event.spec.ts, packages/stripe-integration/src/stripe-upe/is-stripe-payment-event.ts, packages/stripe-integration/src/stripe-upe/stripe-ocs-payment-strategy.spec.ts, packages/stripe-integration/src/stripe-upe/stripe-ocs-payment-strategy.ts, packages/stripe-integration/src/stripe-upe/stripe-upe-initialize-options.ts, packages/stripe-integration/src/stripe-upe/stripe-upe-integration-service.mock.ts, packages/stripe-integration/src/stripe-upe/stripe-upe-integration-service.spec.ts, packages/stripe-integration/src/stripe-upe/stripe-upe-integration-service.ts, packages/stripe-integration/src/stripe-upe/stripe-upe-payment-strategy.spec.ts, packages/stripe-integration/src/stripe-upe/stripe-upe-payment-strategy.ts, packages/stripe-integration/src/stripe-upe/stripe-upe.mock.ts, packages/stripe-integration/src/stripe-upe/stripe-upe.ts
Add new payment strategy for Stripe OCS
To deploy new Stripe OCS accordion implementation
Regression:
Credit card
https://github.com/user-attachments/assets/07c660ee-5c72-431d-a972-970c26e88221
Credit card + 3ds
https://github.com/user-attachments/assets/20ef22f5-f6ca-4547-acf8-49795a59b32d
GPay
https://github.com/user-attachments/assets/8c3bb7cf-fdea-47f9-b4d5-c6cc69e2d2b7
With redirect:
https://github.com/user-attachments/assets/0b3644c5-5baa-43dc-b8e0-103f1dde109c
https://github.com/user-attachments/assets/a1ae6366-5bad-409f-9da3-5fd2696bf1cc
On page confirmation
https://github.com/user-attachments/assets/e7b1455f-0e89-46a8-8be3-ba57918346fc
New implementation:
https://github.com/user-attachments/assets/2d667fe4-4000-4f2f-b545-ab01e1a175d4
Uploading Screen Recording 2024-10-22 at …
=> feat(payment): STRIPE-461 New Stripe OCS strategy

packages/paypal-commerce-integration/src/paypal-commerce-ratepay/paypal-commerce-ratepay-payment-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-ratepay/paypal-commerce-ratepay-payment-strategy.ts
Updated PPCP Ratepay Payment strategy to pass polling timeout through constructor and updated related tests
To be able to set Polling timeout value in tests and reduce overall unit tests run on 24 seconds in checkout sdk project
Before:
After:
No need in manual testing
=> chore(payment): PAYPAL-4810 reduced test run duration for PPCP Ratepay Payment strategy from 24s to 70ms

packages/braintree-integration/src/braintree-local-payment-methods/braintree-local-methods-payment-strategy.spec.ts, packages/braintree-integration/src/braintree-local-payment-methods/braintree-local-methods-payment-strategy.ts
Fixes passing parameters
For data consistency
Before
After
=> feat(payment): PAYPAL-000 fixes passing parameters

packages/td-bank-integration/src/td-online-mart-payment-strategy.spec.ts, packages/td-bank-integration/src/td-online-mart-script-loader.spec.ts
Fixed types in the TD Online Mart integration packages test files
Due to Typescript and Jest last updates
=> refactor(payment): PI-2701 [checkout-sdk-js types] Clear checkout-sdk-js types errors in test files for the TD Bank related packages

packages/braintree-integration/src/braintree-paypal/braintree-paypal-payment-strategy.spec.ts, packages/braintree-integration/src/braintree-paypal/braintree-paypal-payment-strategy.ts, packages/braintree-utils/src/paypal.ts
Added buyer country as an option to Braintree PayPal messages config
To let shopper see PayPal Banner related to the billing country from billing address form
Unit tests
Manual tests
CI
=> feat(payment): PAYPAL-4813 added buyer country as an option to Braintree PayPal messages config

packages/stripe-integration/src/stripe-upe/is-stripe-error.spec.ts, packages/stripe-integration/src/stripe-upe/is-stripe-error.ts, packages/stripe-integration/src/stripe-upe/stripe-ocs-payment-strategy.spec.ts, packages/stripe-integration/src/stripe-upe/stripe-ocs-payment-strategy.ts, packages/stripe-integration/src/stripe-upe/stripe-upe.ts
New confirmation flow for Stripe OCS
To unify confirmation flow for stripe payment methods. For this implementation decision of redirect or non redirect flow makes on stripe side.
unit tests and manually tested
=> feat(payment): STRIPE-484 Stripe OCS confirmation flow

packages/braintree-integration/src/braintree-fastlane/braintree-fastlane-utils.spec.ts, packages/braintree-integration/src/braintree-fastlane/braintree-fastlane-utils.ts, packages/braintree-utils/src/braintree.ts
Added ability to skip shipping step
To skip shipping step
https://github.com/user-attachments/assets/e212a742-ae31-4398-a5f4-587658396810
https://github.com/user-attachments/assets/fe81911b-8766-4b3e-b3a2-78b7cfc45c0f
=> feat(payment): PAYPAL-4800 added ability to skip shipping step

packages/paypal-commerce-integration/src/paypal-commerce-fastlane/paypal-commerce-fastlane-customer-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-fastlane/paypal-commerce-fastlane-customer-strategy.ts, packages/paypal-commerce-utils/src/paypal-commerce-types.ts
Added shipping autoselect flag which affects skipping of shipping step when using fastlane
To create ability for customer to complete order without entering shipping information step because it is already set up
https://github.com/user-attachments/assets/b0d63f85-786b-4c80-9d38-c01207744dbd
https://github.com/user-attachments/assets/e1f73154-5595-46a4-b044-fca5d8bc23a2
=> feat(payment): PAYPAL-4783 added shipping autoselect flag

packages/stripe-integration/src/stripe-upe/stripe-ocs-payment-strategy.spec.ts, packages/stripe-integration/src/stripe-upe/stripe-ocs-payment-strategy.ts, packages/stripe-integration/src/stripe-upe/stripe-upe-integration-service.ts
Stripe OCS radio button size styling
To add customisation for Stripe OCS radio buttons styles. To make it similar to BC accordion radio buttons and add customisation ability for merchants with custom checkouts.
Before
After
=> feat(payment): STRIPE-496 Stripe OCS  radio button size

packages/stripe-integration/src/stripe-upe/create-stripe-ocs-payment-strategy.ts, packages/stripe-integration/src/stripe-upe/create-stripe-upe-payment-strategy.ts, packages/stripe-integration/src/stripe-upe/stripe-upe-integration-service.spec.ts, packages/stripe-integration/src/stripe-upe/stripe-upe-integration-service.ts, packages/stripe-integration/src/stripe-upe/stripe-upe-payment-strategy.spec.ts, packages/stripe-integration/src/stripe-upe/stripe-upe-script-loader.spec.ts, packages/stripe-integration/src/stripe-upe/stripe-upe-script-loader.ts
Update Stripe UI element after updates on BE side.
For some cases after BE synchronisation some options for Stripe payment state can be changed or can be changed PaymentIntent. And we need to update Stripe UI element as well to operate with actual stripe state data.
Unit test and manually tested.
###Before:
https://github.com/user-attachments/assets/62bc7942-409d-486c-aa80-0866252b81cd
###After:
https://github.com/user-attachments/assets/707d3b2b-90a1-46a3-828b-b96b253be564
With redirect
https://github.com/user-attachments/assets/1b98ecba-168d-4695-b48c-431b89a46a03
On page confirmation
https://github.com/user-attachments/assets/488cc67c-a703-4aba-b0e7-2a5560035be0
=> fix(payment): STRIPE-509 Update Stripe element on PI update

packages/core/src/extension/resizable-firame-creator.spec.ts, packages/core/src/extension/resizable-iframe-creator.ts
Fix the issue where the checkout extension in the selected shipping option fails to display after a page refresh, even though it works fine on the first run.
When an extension iframe is removed before it has finished loading, particularly in cases where there is an existing consignment, this action creates a pending extension rendering promise, which can only be resolved or rejected by either a 60-second timeout or a message from the iframe.
Related code:
https://github.com/bigcommerce/checkout-sdk-js/blob/2e6f95f3718a37ef48e1c479136a699e95e6db6f/packages/core/src/extension/resizable-iframe-creator.ts#L91
This PR resolves the issue by rejecting the promise upon detecting the removal of the iframe from the DOM.
https://github.com/user-attachments/assets/3a4e0ab1-ae51-4c0a-9b9f-892e3094b376 …
=> fix(extension): CHECKOUT-8869 Fix Display Issue after Page Refresh

packages/hosted-form-v2/src/hosted-field-type.ts, packages/hosted-form-v2/src/hosted-form-options.ts, packages/hosted-form-v2/src/hosted-input-validate-error-data.ts, packages/hosted-form-v2/src/iframe-content/hosted-input-manual-order-payment-handler.spec.ts, packages/hosted-form-v2/src/iframe-content/hosted-input-manual-order-payment-handler.ts, packages/hosted-form-v2/src/iframe-content/hosted-input-validate-error-data.ts, packages/hosted-form-v2/src/iframe-content/hosted-input.spec.ts, packages/hosted-form-v2/src/iframe-content/hosted-input.ts, packages/hosted-form-v2/src/iframe-content/map-to-accessibility-label.ts, packages/hosted-form-v2/src/payment/Instrument.ts, packages/hosted-form-v2/src/payment/index.ts, packages/hosted-form-v2/src/payment/manual-order-payment-request-sender.spec.ts, packages/hosted-form-v2/src/payment/manual-order-payment-request-sender.ts, packages/hosted-form-v2/src/utils/index.ts, packages/hosted-form-v2/src/utils/isOfflinePaymentMethodId.ts
Add offline payment method support to `hosted-form-v2` package.
Facilitating the creation of a manual order with offline payment methods.
Manual testing
https://github.com/user-attachments/assets/227fc02b-9a68-4a4e-9868-07609917b15a
=> feat(payment): CHECKOUT-7859 Add Offline Payment Method

packages/core/src/hosted-form/hosted-form-factory.ts, packages/core/src/hosted-form/hosted-form-options.ts, packages/core/src/hosted-form/hosted-form.spec.ts, packages/core/src/hosted-form/hosted-form.ts, packages/core/src/hosted-form/index.ts, packages/core/src/hosted-form/stored-card-hosted-form-service.spec.ts, packages/core/src/hosted-form/stored-card-hosted-form-service.ts, packages/core/src/payment/strategies/moneris/moneris-payment-initialize-options.ts, packages/core/src/payment/strategies/moneris/moneris-payment-strategy.ts
===> MERGE TOGETHER WITH CHECKOUT-JS PART https://github.com/bigcommerce/checkout-js/pull/2110
Rename `HostedFormOptions` in core for  `LegacyHostedFormOptions`
=> feat(checkout): PI-2943 Change HostedFormOptions interface name in core

packages/braintree-integration/src/braintree-fastlane/braintree-fastlane-utils.spec.ts, packages/braintree-integration/src/braintree-local-payment-methods/braintree-local-methods-payment-initialize-options.ts, packages/braintree-integration/src/braintree-local-payment-methods/braintree-local-methods-payment-strategy.spec.ts, packages/braintree-integration/src/braintree-local-payment-methods/braintree-local-methods-payment-strategy.ts, packages/braintree-integration/src/braintree-local-payment-methods/create-braintree-local-methods-payment-strategy.ts, packages/braintree-integration/src/index.ts, packages/braintree-integration/src/mocks/braintree.mock.ts, packages/braintree-utils/src/braintree-integration-service.spec.ts, packages/braintree-utils/src/braintree-integration-service.ts, packages/braintree-utils/src/braintree-script-loader.spec.ts, packages/braintree-utils/src/braintree-script-loader.ts, packages/braintree-utils/src/braintree-sdk.spec.ts, packages/braintree-utils/src/braintree-sdk.ts, packages/braintree-utils/src/braintree.ts, packages/braintree-utils/src/mocks/braintree.mock.ts, packages/braintree-utils/src/types.ts
This PR contains several major updates for Braintree LPMs payment strategy (next "strategy"):
- Braintree LMPs SDK implementation was removed from BraintreeIntegrationService class;
- Braintree LMPs SDK implementation was moved to BraintreeSDK class;
- BraintreeIntegrationService was switched with BraintreeSDK in "strategy";
- "strategy" was updated with new flow for instant LPMs (and covered with experiment) due to incoming webhooks implementation changes on BE side
There are several reasons:
- BraintreeIntegrationService is deprecated and should be removed in the future;
- BE is preparing braking changes, which may brake current LPMs implementation on FE side;
Lint and unit test run passed successfully
Test coverage of LPMs strategies is above 80%
Manual tests: …
=> feat(payment): PAYPAL-4884 send payment provider paymentId on payment start stage in Braintree LPMs payment strategy

packages/google-pay-integration/src/gateways/google-pay-braintree-gateway.spec.ts, packages/google-pay-integration/src/gateways/google-pay-braintree-gateway.ts, packages/google-pay-integration/src/types.ts
Get the [isNetworkTokenized ](https://braintree.github.io/braintree-web/current/GooglePayment.html#~tokenizePayload) property returned by Braintree sdk for GooglePay payments and pass to BC payment initializationData.
Skip 3D Secure if isNetworkTokenized is true
Fix issue https://github.com/bigcommerce/checkout-sdk-js/issues/2750 where payment fails when requesting 3D Secure lookup on network tokenized card from GooglePay
I'm unable to fully test on sandbox because all cards in the GooglePay sandbox return isNetworkTokenized: false, but see screenshots below where the isNetworkTokenized property is passed to the BC checkout and 3D Secure lookup is requested as the value is false.
=> fix(payment): PAYPAL-2750 Skip 3D Secure when GooglePay card network tokenized

packages/stripe-integration/src/stripe-upe/stripe-upe-payment-strategy.spec.ts, packages/stripe-integration/src/stripe-upe/stripe-upe-payment-strategy.ts
We shouldn't send shouldSaveInstrument: true if Link is authenticated
Before the fix:
https://github.com/user-attachments/assets/6269bf91-0254-4932-987c-06952625ae22
After the fix:
https://github.com/user-attachments/assets/2d0bac2b-fe00-4bf5-abec-2c91b501d9f3
=> feat(payment): STRIPE-528 Stripe UPE Link shouldSaveInstrument false if authenticated

packages/google-pay-integration/src/google-pay-stripe/google-pay-stripe-gateway.spec.ts
Stripe Google Pay test coverage branches increased
=> feat(payment): STRIPE-485 Stripe Google Pay test coverage branches increased

packages/stripe-integration/src/stripe-upe/stripe-ocs-payment-strategy.spec.ts, packages/stripe-integration/src/stripe-upe/stripe-ocs-payment-strategy.ts, packages/stripe-integration/src/stripe-upe/stripe-upe-integration-service.mock.ts, packages/stripe-integration/src/stripe-upe/stripe-upe-integration-service.spec.ts, packages/stripe-integration/src/stripe-upe/stripe-upe-integration-service.ts, packages/stripe-integration/src/stripe-upe/stripe-upe-payment-strategy.spec.ts, packages/stripe-integration/src/stripe-upe/stripe-upe-payment-strategy.ts, packages/stripe-integration/src/stripe-upe/stripe-upe.mock.ts, packages/stripe-integration/src/stripe-upe/stripe-upe.ts
Stripe UPE confirmation flow refactoring
To simplify confirmation logic and make it similar for different Stripe APMs
https://github.com/user-attachments/assets/7091b72b-fadd-439b-a57a-b63f2f65f67e
https://github.com/user-attachments/assets/b9539a74-5e7e-4160-826f-468517cfd3fb
https://github.com/user-attachments/assets/5a11a652-8b4c-4c57-93a4-ce7ce22c1457
https://github.com/user-attachments/assets/80b28934-c3b8-448e-9cef-fc86ad3863a5
https://github.com/user-attachments/assets/875bbf25-e3c0-4230-92f0-33929a37300b
https://github.com/user-attachments/assets/4df05eb1-ac13-4d43-b270-1787745c2296
https://github.com/user-attachments/assets/950bcf47-7c9c-4ca6-8646-7abb385a9b5d
https://github.com/user-attachments/assets/2539781b-01f2-4f03-8f6a-1cd788fd7aa1 …
=> feat(payment): STRIPE-525 Stripe UPE new confirmation flow

packages/google-pay-integration/src/gateways/google-pay-gateway.spec.ts, packages/google-pay-integration/src/gateways/google-pay-gateway.ts
Add `stateOrProvinceCode` field, if `locality` is empty.
Related PR:
https://github.com/bigcommerce/checkout-js/pull/2116
Because sometimes the `locality` field from GP is empty, we will add `stateOrProvinceCode` instead, and also allow the user to edit the billing address if needed.
Manual testing
=> feat(payment): STRIPE-546 allow billing address editing for all Google Pay providers

packages/hosted-form-v2/src/hosted-form-service.ts, packages/hosted-form-v2/src/iframe-content/hosted-input-events.ts, packages/hosted-form-v2/src/iframe-content/hosted-input-manual-order-payment-handler.spec.ts, packages/hosted-form-v2/src/iframe-content/hosted-input-manual-order-payment-handler.ts, packages/hosted-form-v2/src/payment/manual-order-payment-request-sender.spec.ts
Add async payment methods support by passing payment reponse to the UI side, such as `manual-order-ui`.
The UI side can react to an async order accordingly, such as displaying a modal.
https://github.com/user-attachments/assets/e65cc969-7e5e-4077-abae-fcb8b6097258
=> feat(payment): CHECKOUT-8901 Add Async Payment Methods

packages/google-pay-integration/src/gateways/google-pay-gateway.spec.ts, packages/google-pay-integration/src/gateways/google-pay-gateway.ts, packages/google-pay-integration/src/types.ts
Remove experiment for GooglePay shipping options
This feature was deployed on production for all stores. Experiment can be removed.
Unit tests and manually tested
https://github.com/user-attachments/assets/4ca7716f-169f-4eca-bbc9-aebb1e4c9380
https://github.com/user-attachments/assets/c8822d6b-9d7b-4408-9aee-fa7eff848f93
https://github.com/user-attachments/assets/3e44a1f8-56a1-40b7-bbc0-bf85064bf8a7
https://github.com/user-attachments/assets/9cc29ab3-dff4-4784-897b-ce7e2a4b4088
=> feat(payment): STRIPE-414 remove experiment for GPay shipping options

packages/paypal-commerce-integration/src/mocks/get-paypal-commerce-payment-method.mock.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-button-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-button-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-payment-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-payment-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-types.ts, packages/paypal-commerce-utils/src/paypal-commerce-types.ts, packages/paypal-commerce-utils/src/utils/get-fastlane-styles.ts, packages/paypal-commerce-utils/src/utils/get-paypal-messages-styles-from-bnpl-config.spec.ts, packages/paypal-commerce-utils/src/utils/get-paypal-messages-styles-from-bnpl-config.ts, packages/paypal-commerce-utils/src/utils/index.ts
Updated PayPal Commerce credit strategies with BNPL configuration implementation
So merchants PayPal BNPL Configurator changes in Control Panel will be reflected on storefront and checkout pages
Unit tests
Manual tests
CI
Checkout page grey logo styling:
Checkout page blue logo styling:
Cart page banner grey logo:
=> feat(payment): PAYPAL-4952 updated PayPal Commerce credit strategies with BNPL configuration implementation

packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-button-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-button-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-customer-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-customer-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-types.ts, packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-button-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-button-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-customer-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-customer-strategy.ts
Removed PAYPAL-4387.paypal_shipping_callbacks experiment form PPCP strategies
Experiment was rolled out a half a year ago, so its time to make some cleanup
Unit tests
Manual tests
CI
Placing order with PayPal with Pay Now feature on Cart page:
https://github.com/user-attachments/assets/a1fd187c-81fc-4261-a6be-246b34918219
Placing order with PayPal with Pay Now feature on Checkout page:
https://github.com/user-attachments/assets/ed75c5ac-a9e7-45d9-b3e2-e0e2d7b512d0
Placing order with PayPal Pay Later with Pay Now feature on Cart page:
https://github.com/user-attachments/assets/305fa316-c185-41a8-817a-443ae94b9bb9
Placing order with PayPal Pay Later with Pay Now feature on Checkout page:
https://github.com/user-attachments/assets/e38b2a95-eda4-4b62-b002-a81fd96edd4b
Placing order with …
=> refactor(payment): PAYPAL-4705 removed PAYPAL-4387.paypal_shipping_callbacks experiment form PPCP strategies

packages/core/src/shipping/strategies/braintree/braintree-fastlane-shipping-strategy.spec.ts, packages/core/src/shipping/strategies/braintree/braintree-fastlane-shipping-strategy.ts, packages/core/src/shipping/strategies/paypal-commerce/paypal-commerce-fastlane-shipping-strategy.spec.ts, packages/core/src/shipping/strategies/paypal-commerce/paypal-commerce-fastlane-shipping-strategy.ts
Removed PAYPAL-3996.paypal_fastlane_shipping_update experiment
It was rolled out a long time ago, so should be cleaned up
Unit tests
Manual tests
CI
https://github.com/user-attachments/assets/4c9f41f1-d0ef-4232-b275-e15d3dc098e6
=> refactor(payment): PAYPAL-4705 removed PAYPAL-3996.paypal_fastlane_shipping_update experiment

packages/core/src/payment/strategies/braintree/braintree-hosted-form.spec.ts, packages/core/src/payment/strategies/braintree/braintree-hosted-form.ts
Added check for teardown call in deinitialize method for avoiding **'teardown cannot be called after teardown.'** error message and for correct initialization of hosted fields in the Payment Step
To fix an issue
https://github.com/user-attachments/assets/87978eb2-a592-4f80-be0d-eb739684ffb9
=> feat(payment): PAYPAL-4995 Unable to Change Payment Methods With Braintree if Stored Payments are Used

packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-button-strategy.ts
Removed extra data attribute from PayPal Commerce credit banner
To let PayPal accept banner styles provided through messages config
Manual tests on int
https://github.com/user-attachments/assets/726486c2-0f91-498a-ba21-dd24905a2c86
=> fix(payment): PAYPAL-4952 removed extra data attribute from PayPal Commerce credit banner

packages/core/src/checkout/checkout-service.spec.ts, packages/core/src/checkout/checkout-service.ts, packages/core/src/extension/extension-messenger.spec.ts, packages/core/src/extension/extension-messenger.ts
Introduce a new checkout service method to clear outdated poster whenever an extension is unmounted.
Handle message post failures gracefully by clearing the poster cache and logging the loss message.
The event poster within the extension messenger is not cleared/rebuilt after an extension iframe is unmounted. 
Continuing to deliver messages through this outdated poster disrupts event broadcasting.
https://github.com/user-attachments/assets/83c132a2-b798-4a81-868a-6d7af2ee3866
=> fix(extension): CHECKOUT-8960 Fix Broadcast Interruption

packages/core/src/checkout/checkout-service.spec.ts, packages/core/src/checkout/checkout-service.ts, packages/core/src/extension/extension-commands.ts, packages/core/src/extension/extension-message.ts, packages/core/src/extension/extension-messenger.ts, packages/core/src/extension/index.ts
Introduce a new checkout extension command, `GetConsignments`
To pass consignment data to an extension.
=> feat(extension): CHECKOUT-8964 Introduce GetConsignment Extension Command

packages/adyen-utils/src/adyenv3/adyenv3-script-loader.spec.ts, packages/adyen-utils/src/adyenv3/adyenv3-script-loader.ts
Update Adyen SDK to remove iDEAL bank selection dropdown for Adyen
iDEAL have updated their central technical infrastructure.
[according to official documentation](https://docs.adyen.com/payment-methods/ideal/).
https://github.com/user-attachments/assets/30b901f6-dd8c-4cef-aa16-9cbb8b2ebd63
=> feat(payment): PI-3099 update Adyen SDK to Remove iDEAL bank selection dropdown

packages/core/src/bundles/checkout-sdk.ts, packages/core/src/checkout/checkout-service.spec.ts, packages/core/src/checkout/checkout-service.ts, packages/core/src/extension/errors/index.ts, packages/core/src/extension/errors/unsupported-extension-query-error.ts, packages/core/src/extension/extension-commands.ts, packages/core/src/extension/extension-message.ts, packages/core/src/extension/extension-messenger.spec.ts, packages/core/src/extension/extension-messenger.ts, packages/core/src/extension/extension-queries.ts, packages/core/src/extension/extension-service.spec.ts, packages/core/src/extension/extension-service.ts, packages/core/src/extension/index.ts, packages/core/src/extension/initialize-extension-service.ts
Introduce a new `query` concept that allows an extension to fetch any data from the checkout object by using a simple query key. 
An extension can fetch checkout data immediately.
After the extension service initialization, clicking the emoji will run:
```
console.log(await service.getConsignments(useCache));
```
`useCache` is set to `true` at first. On the second time of clicking the emoji, `useCache` will be `false`, therefore, a `GET` checkout call is made.
https://github.com/user-attachments/assets/8e87cdfb-103c-4338-bf1b-73bf2f1d2e28
=> feat(extension): CHECKOUT-8974 Introduce Extension Query

packages/core/src/spam-protection/google-recaptcha.spec.ts, packages/core/src/spam-protection/google-recaptcha.ts, packages/core/src/spam-protection/spam-protection-action-creator.spec.ts, packages/core/src/spam-protection/spam-protection-action-creator.ts
Reset recaptcha if recaptcha is instantiated twice instead of throwing an error.
If we validate recaptcha for apple pay button and if a shopper tries to create a new account, then an error is thrown regarding recaptcha client already created.
In order to fix this, reset recaptcha client and remove the element so recaptcha can be triggered again.
- CI 
https://github.com/user-attachments/assets/4a07fee8-d019-4c99-95ce-0220e61c3a78
https://github.com/user-attachments/assets/ace96df5-dc89-4317-bcd9-9a42b1e027d2
=> WIP chore(checkout): CHECKOUT-8264 Reset recaptcha if initialize is called twice

packages/core/src/checkout/checkout-service.ts, packages/core/src/extension/extension-commands.ts, packages/core/src/extension/extension-messenger.ts
Introduce a new checkout extension command.
To support the force re-rendering of the shipping form.
CI.
=> feat(extension): CHECKOUT-8974 Introduce ReRenderShippingForm Command

packages/core/src/hosted-form/iframe-content/hosted-input-validator.spec.ts, packages/core/src/hosted-form/iframe-content/hosted-input-validator.ts, packages/hosted-form-v2/src/iframe-content/hosted-input-validator.spec.ts, packages/hosted-form-v2/src/iframe-content/hosted-input-validator.ts
Payments team runs transaction journal audit job on a regular basis, which looks for possible PAN (Credit card numbers) stored in transaction journals. One of those reasons and one that we see quite commonly is where due to human mistake, shoppers are typing credit card number into Card holder name field. We want to add this validation BC hosted form fields.
For more credit cards security.
Unit tests
Screenshot
=> feat(payment): PAYMENTS-10280 Add validation on hosted form card holder name to not have PAN

packages/paypal-commerce-integration/src/mocks/get-billing-address-from-order-details.mock.ts, packages/paypal-commerce-integration/src/mocks/get-paypal-commerce-order-details.mock.ts, packages/paypal-commerce-integration/src/paypal-commerce-integration-service.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-integration-service.ts, packages/paypal-commerce-integration/src/paypal-commerce-types.ts
Added phone number to be displayed on CP order section
To give merchants ability to see phone number inside CP in orders section
**Before**
**After**
=> feat(payment): PAYPAL-5041 added phone to order

packages/apple-pay-integration/src/apple-pay-button-initialize-options.ts, packages/apple-pay-integration/src/apple-pay-button-strategy.spec.ts, packages/apple-pay-integration/src/apple-pay-button-strategy.ts, packages/apple-pay-integration/src/apple-pay-customer-strategy.spec.ts, packages/apple-pay-integration/src/apple-pay-customer-strategy.ts, packages/apple-pay-integration/src/apple-pay-script-loader.spec.ts, packages/apple-pay-integration/src/apple-pay-script-loader.ts, packages/apple-pay-integration/src/create-apple-pay-button-strategy.ts, packages/apple-pay-integration/src/create-apple-pay-customer-strategy.ts, packages/apple-pay-integration/src/mocks/apple-pay-button.mock.ts
Added Apple Pay SDK for supporting third party browsers
For be able to place an order using Apple Pay via third party browsers
Related PRs:
https://github.com/bigcommerce/bigcommerce/pull/61473
https://github.com/bigcommerce/terraform-launchdarkly/pull/2094
https://github.com/bigcommerce/checkout-js/pull/2154
_Safari | When the experiment is enabled/disabled_
_Chrome | When the experiment is enabled | Was tested by using prod store with prod environment with overwriting artefacts_
**We will only be able to finish testing it after all related changes have been deployed in Tier 1, especially this changes, we will turn on an experiment for test store**
Screen record of how it works with third party browsers:
https://github.com/user-attachments/assets/c30bbf25-11e7-41ef-b776-87e2b01040e8
Some …
=> feat(payment): PAYPAL-4324 added Apple Pay SDK for supporting third party browsers

packages/apple-pay-integration/src/apple-pay-customer-strategy.ts
Fixed creation of native button for apple pay
To fix e2e test in checkout-js
=> feat(payment): PAYPAL-4324 Fixed creation of native button for apple pay

packages/google-pay-integration/src/google-pay-button-strategy.spec.ts, packages/google-pay-integration/src/google-pay-button-strategy.ts, packages/google-pay-integration/src/google-pay-customer-strategy.spec.ts, packages/google-pay-integration/src/google-pay-customer-strategy.ts, packages/google-pay-integration/src/google-pay-payment-strategy.spec.ts, packages/google-pay-integration/src/types.ts
Added tests to cover google pay functionality related to error handling logic
To increase test coverage
=> feat(payment): PAYPAL-5044 Added tests to cover google pay functionality related to error handling logic

packages/core/src/shipping/consignment-action-creator.spec.ts, packages/core/src/shipping/consignment-action-creator.ts, packages/core/src/shipping/consignment.ts, packages/utility/src/index.ts, packages/utility/src/is-experiment-enabled/index.ts, packages/utility/src/is-experiment-enabled/is-experiment-enabled.spec.ts, packages/utility/src/is-experiment-enabled/is-experiment-enabled.ts
Avoid duplicate call for shipping option if shipping option id passed is same.
Avoid duplicate call for shipping option if shipping option id that is passed same as the one that is already selected. This can happen sometimes with various subscriptions on clients from SDK that watch for consignment changes.
- CI
- Screencast
https://github.com/user-attachments/assets/b651844d-8a1f-440c-b9f1-838933ad2900
https://github.com/user-attachments/assets/275fc799-e0b6-43bc-a0e1-0bad80980089
=> fix(shipping): CHECKOUT-8999 Remove duplicate call for shipping option

packages/braintree-integration/src/braintree-local-payment-methods/braintree-local-methods-payment-strategy.spec.ts, packages/braintree-integration/src/braintree-local-payment-methods/braintree-local-methods-payment-strategy.ts
Added BT fallback Url
To enable fallback to BT LPMs
Unit tests
=> feat(payment): PAYPAL-5187 added BT fallback Url

packages/core/src/shipping/strategies/stripe-upe/stripe-upe-shipping-initialize-options.ts, packages/core/src/shipping/strategies/stripe-upe/stripe-upe-shipping-strategy.spec.ts, packages/core/src/shipping/strategies/stripe-upe/stripe-upe-shipping-strategy.ts, packages/stripe-integration/src/stripe-upe/stripe-upe.ts
Disable state code mapping for Spain in Stripe Link Address component
Checkout-js: [https://github.com/bigcommerce/checkout-js/pull/2188](https://github.com/bigcommerce/checkout-js/pull/2188)
To fix issue with unavailable state specific shipping options for Spain shoppers
Unit tests
Available shipping options:
https://github.com/user-attachments/assets/6f83cc5a-ad22-4a2c-8960-216065d6fe37
Stripe dashboard:
BC control panel:
https://github.com/user-attachments/assets/01f265ac-697d-470b-b43d-eb1d259a78c3
Stripe dashboard:
BC control panel:
https://github.com/user-attachments/assets/eeac716f-5965-4ab0-ab62-ec45f8adec7a
Stripe dashboard:
BC control panel:
https://github.com/user-attachments/assets/b512d8b6-04a8-4f4c-a5cd-371e1000d355
Stripe dashboard:
BC control panel: …
=> fix(payment): STRIPE-660 Disable state code mapping for Spain in Stripe Link Address component

packages/braintree-integration/src/braintree-paypal-credit/braintree-paypal-credit-button-initialize-options.ts, packages/braintree-integration/src/braintree-paypal-credit/braintree-paypal-credit-button-strategy.spec.ts, packages/braintree-integration/src/braintree-paypal-credit/braintree-paypal-credit-button-strategy.ts
Added messages implementation to Braintree PayPal Credit button strategy
Braintree Messaging is available only when Braintree PayPal Credit is enabled, so the best place to hold this implementation is in Braintree PayPal Credit Button strategy to render banner on cart page. So as part one of messages implementation migration the implementation was duplicated from Braintree PayPal to Braintree PayPal Credit button strategy
Unit tests
Manual tests
CI
US VPN location:
Non US VPN location:
=> feat(payment): PAYPAL-5213 added messages implementation to Braintree PayPal Credit button strategy

packages/braintree-integration/src/braintree-paypal-credit/braintree-paypal-credit-button-strategy.spec.ts, packages/braintree-integration/src/braintree-paypal-credit/braintree-paypal-credit-button-strategy.ts, packages/braintree-integration/src/braintree-paypal-credit/create-braintree-paypal-credit-button-strategy.ts, packages/braintree-integration/src/braintree-paypal/braintree-paypal-payment-strategy.spec.ts, packages/braintree-integration/src/braintree-paypal/braintree-paypal-payment-strategy.ts, packages/braintree-integration/src/braintree-paypal/create-braintree-paypal-payment-strategy.ts, packages/braintree-integration/src/mocks/paypal.mock.ts, packages/braintree-utils/src/braintree-messages.spec.ts, packages/braintree-utils/src/braintree-messages.ts, packages/braintree-utils/src/braintree.ts, packages/braintree-utils/src/index.ts, packages/braintree-utils/src/map-to-legacy-billing-address.spec.ts, packages/braintree-utils/src/map-to-legacy-shipping-address.spec.ts, packages/braintree-utils/src/mocks/paypal.mock.ts, packages/braintree-utils/src/paypal.ts, packages/braintree-utils/src/utils/get-fastlane-styles.spec.ts
Created Braintree Messages class and added Braintree BNPL Configurator implementation
To be able to apply BNPL banner style changes on checkout payment paywall
Unit tests
Manual tests
=> feat(payment): PAYPAL-5097 created Braintree Messages class and added Braintree BNPL Configurator implementation

packages/braintree-integration/src/get-valid-button-style.spec.ts, packages/braintree-integration/src/get-valid-button-style.ts
Updated Braintree Button height validation with null and undefined coverage
Because when BE provides height as null, then current implementation returns minHeight (25px) instead of default
Unit tests
Manual tests
=> fix(payment): PAYPAL-4585 updated Braintree Button height validation with null and undefined coverage

packages/core/src/payment-integration/create-payment-integration-service.ts, packages/core/src/payment-integration/default-payment-integration-service.spec.ts, packages/core/src/payment-integration/default-payment-integration-service.ts, packages/google-pay-integration/src/gateways/google-pay-gateway.spec.ts, packages/google-pay-integration/src/gateways/google-pay-gateway.ts, packages/google-pay-integration/src/google-pay-button-strategy.spec.ts, packages/google-pay-integration/src/google-pay-button-strategy.ts, packages/google-pay-integration/src/google-pay-customer-strategy.spec.ts, packages/google-pay-integration/src/google-pay-customer-strategy.ts, packages/google-pay-integration/src/google-pay-payment-processor.spec.ts, packages/google-pay-integration/src/google-pay-payment-processor.ts, packages/google-pay-integration/src/google-pay-payment-strategy.spec.ts, packages/google-pay-integration/src/google-pay-payment-strategy.ts, packages/google-pay-integration/src/mocks/google-pay-processor-initialize.mock.ts, packages/google-pay-integration/src/types.ts, packages/payment-integration-api/src/payment-integration-service.ts, packages/payment-integrations-test-utils/src/test-utils/payment-integration-service.mock.ts
Added coupons handling on the Google Pay payment sheet.
Cart flow:
https://github.com/user-attachments/assets/2419842b-0807-4f87-9eec-c09add1ebc0f
Mini cart flow:
https://github.com/user-attachments/assets/8cd5c30d-c58c-4f96-b6a3-a7eeb0739985
PDP flow:
https://github.com/user-attachments/assets/78046f5f-c557-44b7-8a8e-5923780553d3
Customer step flow:
https://github.com/user-attachments/assets/20e16cb0-b400-4197-bf3e-69710c9907a4
Payment step flow:
https://github.com/user-attachments/assets/9e6ec42e-ff93-408e-9d6d-2b7ec834650e
Error showing:
https://github.com/user-attachments/assets/3a1bf300-8d5a-4221-83cc-9e1b29359a76
Removing Coupon:
https://github.com/user-attachments/assets/af332f2c-8f8e-4be9-b68f-c2ec320bd149
Because we don't handle coupons adding through the Google Pay payment pop …
=> feat(payment): PI-2875 Google Pay coupons handling

packages/core/src/order/errors/invalid-shipping-address-error.spec.ts, packages/core/src/order/errors/invalid-shipping-address-error.ts, packages/core/src/order/order-request-sender.spec.ts, packages/core/src/order/order-request-sender.ts
Map invalid shipping address error type to a custom error
To display a better and more informed error heading to shopper map api error to custom error
- CI
- Screenshot
=> chore(shipping): CHECKOUT-9114 Map invalid shipping address error type to a custom error

packages/core/src/order/order.ts, packages/core/src/order/orders.mock.ts, packages/payment-integration-api/src/index.ts, packages/payment-integration-api/src/order/index.ts, packages/payment-integration-api/src/order/order.ts, packages/payment-integrations-test-utils/src/test-utils/orders.mock.ts
Introduce OrderShippingConsignmentDiscount interface
To able read the field in checkout-js
- test
=> feat(checkout): CHECKOUT-8521 Introduce OrderShippingConsignmentDiscount interface

packages/core/src/config/config.ts, packages/core/src/config/configs.mock.ts
Exposing logoutLink into setting interface
To able to use the field in checkout-js
- CI
=> feat(checkout): CHECKOUT-9167 Exposing logoutLink into setting interface

packages/core/src/shipping/strategies/stripe-upe/stripe-upe-shipping-strategy.spec.ts, packages/core/src/shipping/strategies/stripe-upe/stripe-upe-shipping-strategy.ts, packages/stripe-integration/src/stripe-upe/stripe-upe.ts
Remove experiment for Stripe Link Spain state mapping
Prs:
checkout-js: [https://github.com/bigcommerce/checkout-js/pull/2253](https://github.com/bigcommerce/checkout-js/pull/2253)
Fix was successfully rolled out and experiment can be removed
Rollback this PR
Stripe Link add new address
https://github.com/user-attachments/assets/daef8aac-e8d5-4c1e-942a-5a03b63778c2
Stripe Link change existing address
https://github.com/user-attachments/assets/bcb6f646-b9a3-4e4a-a408-4a003e252544
Stripe Link pay with existing address
https://github.com/user-attachments/assets/79fc8fe8-82ec-49a6-85bb-c153a107b92f
=> feat(payment): STRIPE-667 remove experiment for Stripe Link Spain state mapping

packages/google-pay-integration/src/gateways/google-pay-gateway.spec.ts, packages/google-pay-integration/src/gateways/google-pay-gateway.ts
Added possibility to apply multiple coupons in the Google Pay modal.
Because we don't have the functionality to apply multiple coupons in the Google Pay modal.
Manual testing.
https://github.com/user-attachments/assets/508f12a5-5f5d-4e3b-9ad9-57fa0ce8a94d
=> feat(payment): PI-3669 apply multiple coupons in the Google Pay modal

packages/hosted-form-v2/src/hosted-field.spec.ts, packages/hosted-form-v2/src/hosted-field.ts
Added new link for the storefront hosted fields
Due to the new approach of hosted fields
=> feat(payment): PI-3825 Added new link for the storefront hosted fields

.circleci/config.yml, package-lock.json, package.json
- Update node to 22
- Drop validate commit CI step
Update to latest node version.
- CI
=> chore(common): update node to 22

packages/core/src/shipping/strategies/braintree/braintree-fastlane-shipping-strategy.ts, packages/core/src/shipping/strategies/paypal-commerce/paypal-commerce-fastlane-shipping-strategy.ts
`Consignments` can be an empty array, so in this case we get an error when trying to get `customFields`
To fix `undefined` properties cannot be read error
Can not be able to reproduce it via integration/local store. But the problem should be fixed after these changes. I will take a look at the Sentry logs after deployment.
[PAYPAL-5354]: https://bigcommercecloud.atlassian.net/browse/PAYPAL-5354?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(payment): PAYPAL-5354 Cannot read properties of undefined (reading 'customFields')

packages/google-pay-integration/src/google-pay-payment-initialize-options.ts, packages/google-pay-integration/src/google-pay-payment-strategy.spec.ts, packages/google-pay-integration/src/google-pay-payment-strategy.ts, packages/ui/src/index.ts, packages/ui/src/loading-indicator/index.ts, packages/ui/src/loading-indicator/loading-indicator.ts
Added Loading Indicator to the google-pay-payment-strategy
Because of the Sentry issue.
User clicks on the Place order button before our requests are done, so we have to show loader in this case.
Manual testing
=> feat(payment): Added loadingIndicator to the google-pay-payment-strategy

packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-button-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-customer-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-button-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-customer-strategy.spec.ts
Cleaned up paypal commerce tests from unused fastlane shipping callback experiment
As this experiment check was removed from production code a while ago
Unit tests
CI
=> refactor(payment): cleaned up paypal commerce tests from unused fastlane shipping callback experiment

packages/stripe-integration/src/stripe-upe/stripe-upe-script-loader.ts, packages/stripe-integration/src/stripe-upe/stripe-upe.ts
Upload Stripe client with custom options
Because we need to upload Stripe Link v2 with other options
Manual tests
=> feat(payment): upload Stripe client with custom options

packages/core/src/payment/strategies/braintree/braintree-payment-processor.ts, packages/core/src/payment/strategies/braintree/braintree-sdk-creator.spec.ts, packages/core/src/payment/strategies/braintree/braintree-sdk-creator.ts, packages/core/src/payment/strategies/braintree/braintree-venmo-payment-strategy.spec.ts, packages/core/src/payment/strategies/braintree/braintree-venmo-payment-strategy.ts, packages/core/src/payment/strategies/braintree/braintree.ts
Updated braintree venmo config
This parameter allows you to provide a web-based login experience for customers that don't have the Venmo app installed on their mobile device. When tokenization is initiated and the Venmo app is not installed, customers will see a popup to authenticate themselves by logging into their Venmo account.
Local testing
=> feat(payment): Updated braintree venmo config

packages/stripe-integration/src/stripe-upe/stripe-ocs-payment-strategy.ts, packages/stripe-integration/src/stripe-upe/stripe-upe-initialize-options.ts, packages/stripe-integration/src/stripe-upe/stripe-upe.ts
Add basic customization options for Stripe OCS accordion
checkout-js PR: [https://github.com/bigcommerce/checkout-js/pull/2289](https://github.com/bigcommerce/checkout-js/pull/2289)
To get ability for customization new Stripe accordion elememnt
https://github.com/user-attachments/assets/394a94bd-9d99-4239-b596-64f3190cf0e4
=> feat(payment): Stripe OCS accordion element styling

packages/stripe-integration/src/stripe-upe/stripe-ocs-payment-strategy.spec.ts, packages/stripe-integration/src/stripe-upe/stripe-ocs-payment-strategy.ts, packages/stripe-integration/src/stripe-upe/stripe-ocs.mock.ts, packages/stripe-integration/src/stripe-upe/stripe-upe-initialize-options.ts
Update Stripe OCS accordion state on initialization
Checkout-js PR: [https://github.com/bigcommerce/checkout-js/pull/2312](https://github.com/bigcommerce/checkout-js/pull/2312)
To synchronize Stripe accordion selected method with native BC accordion on initialization
Move layout configuration to checkout-js side  
OSC accordion on the last place
https://github.com/user-attachments/assets/2b8316b3-3eb5-44a5-a199-093e238e4c2e
OSC accordion on the first place
https://github.com/user-attachments/assets/79c5f1eb-7c58-4f57-b623-f66d81517ecd
=> feat(payment): Stripe OCS accordion state on initialization

packages/stripe-integration/src/stripe-upe/stripe-upe.ts
Sofort and Giropay constants removed
Because it is not supported by Stripe anymore
Manual testing
=> feat(payment): remove Sofort and Giropay enums from StripeUPE

packages/core/src/common/iframe/iframe-event-listener.ts, packages/core/src/common/iframe/index.ts, packages/core/src/common/worker/index.ts, packages/core/src/common/worker/worker-event-listener.test.ts, packages/core/src/common/worker/worker-event-listener.ts, packages/core/src/extension/extension-action-creator.ts
Add worker-event-listner.
To support handling life cycle of worker event listener.
Added unit tests.
- Two messages sent from a worker.
- The first message triggers the removal of one listener.
- Both messages trigger the message logger to show message in the console.
=> feat(checkout): Add worker-event-listener

packages/core/src/checkout/checkout-service.spec.ts, packages/core/src/checkout/checkout-service.ts, packages/core/src/checkout/create-checkout-service.ts, packages/core/src/common/worker/index.ts, packages/core/src/common/worker/worker-event-poster.spec.ts, packages/core/src/common/worker/worker-event-poster.ts, packages/core/src/extension/create-extension-web-worker.spec.ts, packages/core/src/extension/extension-action-creator.spec.ts, packages/core/src/extension/extension-action-creator.ts, packages/core/src/extension/extension-messenger.spec.ts, packages/core/src/extension/extension-messenger.ts, packages/core/src/extension/extension.mock.ts, packages/core/src/extension/extension.ts, packages/core/src/extension/index.ts, packages/core/src/extension/worker-extension-messenger.ts
Add worker-extension-messenger and worker-event-poster.
To support handling life cycle of worker event poster.
Added unit tests.
**Manually testing**
https://github.com/user-attachments/assets/2d7c5b20-ddb0-4047-805b-f65eaaa4ec6d
=> feat(checkout): Add worker extension messenger and worker-event-poster

packages/apple-pay-integration/src/apple-pay-button-strategy.spec.ts, packages/apple-pay-integration/src/apple-pay-button-strategy.ts, packages/apple-pay-integration/src/apple-pay-customer-strategy.spec.ts, packages/apple-pay-integration/src/apple-pay-customer-strategy.ts, packages/apple-pay-integration/src/apple-pay-session-factory.ts, packages/apple-pay-integration/src/mocks/apple-pay-payment.mock.ts
Added canMakePayments method as additional verification of payment capability
For additional check of apple pay payment capability
Manual testing
=> feat(payment): added canMakePayments method as additional verification of payment capability

packages/core/src/checkout/checkout-service.spec.ts, packages/core/src/common/worker/WorkerEvent.ts, packages/core/src/common/worker/worker-event-listener.ts, packages/core/src/extension/extension-action-creator.ts, packages/core/src/extension/extension-messenger.ts, packages/core/src/extension/worker-extension-messenger.spec.ts, packages/core/src/extension/worker-extension-messenger.ts
Implement listening methods for the worker extension messenger.
Enable worker extension to use command and query.
- The sample worker extension commands `checkout-js` to toggle the loading indication every second.
- The sample worker retrieves the current consignment details.
https://github.com/user-attachments/assets/345e312f-001b-44b5-be56-2f7291d32eb0
=> feat(checkout): Add listening methods to worker extension messenger

packages/stripe-integration/jest.config.js, packages/stripe-integration/src/index.ts, packages/stripe-integration/src/stripe-ocs/stripe-ocs-initialize-options.ts, packages/stripe-integration/src/stripe-ocs/stripe-ocs-payment-strategy.spec.ts, packages/stripe-integration/src/stripe-ocs/stripe-ocs-payment-strategy.ts, packages/stripe-integration/src/stripe-upe/stripe-upe-initialize-options.ts, packages/stripe-integration/src/stripe-utils/stripe.ts
Move all styling options for Stripe OCS to checkoput-js side.
Checkout-js PR: [https://github.com/bigcommerce/checkout-js/pull/2351](https://github.com/bigcommerce/checkout-js/pull/2351)
To make Stripe widget more flexible for merchants with custom checkout. 
https://github.com/user-attachments/assets/74fc3d46-48c9-4e0f-8dad-8bb69d8d1c11
=> feat(payment): Move all Stripe OCS styling configs to checkout-js side

packages/core/src/payment/payment-request-options.ts, packages/core/src/payment/strategies/braintree/braintree-sdk-creator.spec.ts, packages/core/src/payment/strategies/braintree/braintree-venmo-payment-initialize-options.ts, packages/core/src/payment/strategies/braintree/braintree-venmo-payment-strategy.spec.ts, packages/core/src/payment/strategies/braintree/braintree-venmo-payment-strategy.ts, packages/core/src/payment/strategies/braintree/index.ts
Updated `braintree-venmo-payment-strategy` with providing initialization options
To be able handle venmo auth flow based on `allowDesktop` option
Manual
=> feat(payment): updated braintree-venmo-payment-strategy with providing initialization options

packages/amazon-pay-utils/src/amazon-pay-v2-payment-processor.spec.ts, packages/amazon-pay-utils/src/amazon-pay-v2-payment-processor.ts
Removal of experiment INT-5826.amazon_relative_url from checkout-sdk-js
This experiment was only enabled for one store 1002086826. As customer is not using AmazonPay since 2024-04-15 we decided to rollout it.
https://github.com/user-attachments/assets/18b71ef6-1425-475f-815f-a53dfce06f82
=> feat(payment): PI-3946 Remove experiment: INT-5826.amazon_relative_url[checkout-js]

packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-payment-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-payment-strategy.ts, packages/paypal-commerce-utils/src/utils/index.ts, packages/paypal-commerce-utils/src/utils/is-redirect-action-error.spec.ts, packages/paypal-commerce-utils/src/utils/is-redirect-action-error.ts
Add error handling for redirect action
To be able redirect user if there is `PSD2` related error
Was testing with this PR https://github.com/bigcommerce/bigpay/pull/9096 on int store
=> feat(payment): PSD2 error handling

package-lock.json, package.json, packages/bigcommerce-payments-integration/src/bigcommerce-payments/bigcommerce-payments-button-initialize-options.ts, packages/bigcommerce-payments-integration/src/bigcommerce-payments/bigcommerce-payments-button-strategy.spec.ts, packages/bigcommerce-payments-integration/src/bigcommerce-payments/bigcommerce-payments-customer-initialize-options.ts, packages/bigcommerce-payments-integration/src/bigcommerce-payments/bigcommerce-payments-customer-strategy.spec.ts, packages/bigcommerce-payments-integration/src/bigcommerce-payments/bigcommerce-payments-payment-initialize-options.ts, packages/bigcommerce-payments-integration/src/bigcommerce-payments/create-bigcommerce-payments-button-strategy.spec.ts, packages/bigcommerce-payments-integration/src/bigcommerce-payments/create-bigcommerce-payments-button-strategy.ts, packages/bigcommerce-payments-integration/src/bigcommerce-payments/create-bigcommerce-payments-payment-strategy.ts
Updated rest of BigCommercePayments related names and updated bigcommerce-client-js to 5.28.1
1. To have proper access to BigCommercePayments interfaces with right naming;
2. To be able to map bigcommerce_payments related provider id to the id expected on BE side;
Unit tests
CI
=> chore(payment): updated rest of BigCommercePayments related names and updated bigcommerce-client-js to 5.28.1

packages/paypal-commerce-integration/src/paypal-commerce-fastlane/paypal-commerce-fastlane-payment-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-fastlane/paypal-commerce-fastlane-payment-strategy.ts, packages/paypal-commerce-utils/src/paypal-commerce-types.ts
Updated `authenticationState` statuses
To fix issue with fastlane success flow
`authenticationState` does not have `success` state, only `succeeded`
=> feat(payment): fastlane success flow fix

packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-button-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-button-strategy.ts
Hide banner implementation under the experiment in PPCP button strategy
To manage the logic of banner implementation using an experiment
Manual
Unit
=> feat(payment): Hide banner implementation under the experiment in PPCP button strategy

packages/bigcommerce-payments-integration/src/bigcommerce-payments-credit-cards/bigcommerce-payments-credit-cards-payment-strategy.ts
Fixed a typo in `bigcommerce_payments_creditcardscheckout` method name in BigCommercePaymentsCreditCardsPaymentStrategy
So the PayPal order creation will not be failed with 503 server error
Manual tests
CI
=> fix(payment): removed typo from bigcommerce_payments_creditcardsscheckout in BigCommercePaymentsCreditCardsPaymentStrategy

packages/core/src/payment/strategies/braintree/braintree-credit-card-payment-strategy.spec.ts, packages/core/src/payment/strategies/braintree/braintree-credit-card-payment-strategy.ts, packages/core/src/payment/strategies/braintree/braintree-hosted-form.spec.ts, packages/core/src/payment/strategies/braintree/braintree-hosted-form.ts, packages/core/src/payment/strategies/braintree/braintree-payment-options.ts, packages/core/src/payment/strategies/braintree/braintree-payment-processor.spec.ts, packages/core/src/payment/strategies/braintree/braintree-payment-processor.ts, packages/core/src/payment/strategies/braintree/is-braintree-supported-card-brand.spec.ts, packages/core/src/payment/strategies/braintree/is-braintree-supported-card-brand.ts
Added unsupported credit card brands initialization option for BraintreeCreditCardsPaymentStrategy
To prevent customers to use unsupported card brands Braintree hosted form will throw validation error and prevent order placement
Unit tests
Manual tests
CI
For example if visa was added as unsupported card brand, then validation error occurs when customer clicks on "Place order" button:
https://github.com/user-attachments/assets/bb3be346-8195-4a84-bff1-b72f7c24d95e
=> feat(payment): added unsupported credit card brands to braintree credit cards payment strategy

packages/paypal-commerce-integration/src/mocks/get-paypal-commerce-payment-method.mock.ts, packages/paypal-commerce-integration/src/mocks/get-paypal-commerce-ratepay-payment-method.mock.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-button-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-button-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-payment-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-payment-strategy.ts
Updated paypal commerce credit strategies with BNPL changes after experiment rollout
BNPL experiment was rolled out to 100% a while ago, so this changes should be applied by default 
Unit tests
Manual tests
CI
=> refactor(payment): updated paypal commerce credit strategies with BNPL changes after experiment rollout

packages/stripe-integration/src/stripe-ocs/stripe-link-v2-customer-strategy.spec.ts, packages/stripe-integration/src/stripe-ocs/stripe-link-v2-customer-strategy.ts, packages/stripe-integration/src/stripe-ocs/stripe-ocs-initialize-options.ts, packages/stripe-integration/src/stripe-ocs/stripe-ocs-payment-strategy.spec.ts, packages/stripe-integration/src/stripe-ocs/stripe-ocs-payment-strategy.ts, packages/stripe-integration/src/stripe-upe/stripe-upe-constants.ts, packages/stripe-integration/src/stripe-upe/stripe-upe-customer-strategy.ts, packages/stripe-integration/src/stripe-upe/stripe-upe-payment-strategy.ts, packages/stripe-integration/src/stripe-utils/stripe-script-loader.spec.ts, packages/stripe-integration/src/stripe-utils/stripe-script-loader.ts, packages/stripe-integration/src/stripe-utils/stripe.ts
• Add customer session token to stripe element.
• Stripe beta features per module.
To add stored curds on the stripe side.
TBD
=> feat(payment): Stripe OCS, broadcast customer token for stored cards

packages/braintree-utils/src/braintree-messages.spec.ts, packages/braintree-utils/src/braintree-messages.ts, packages/braintree-utils/src/braintree.ts
cleanup unused code in BraintreeMessages class
BNPL Configurator feature was rolled out a while ago, so the code that was created for it now is a default state for messages implementation
Unit tests
Manual tests
CI
Screenshots of banners rendered on cart and checkout pages:
=> refactor(payment): cleanup unused code in BraintreeMessages class

packages/stripe-integration/src/stripe-ocs/create-stripe-link-v2-customer-strategy.ts, packages/stripe-integration/src/stripe-ocs/stripe-link-v2-customer-strategy.spec.ts, packages/stripe-integration/src/stripe-ocs/stripe-link-v2-customer-strategy.ts, packages/stripe-integration/src/stripe-ocs/stripe-ocs-customer-initialize-options.ts, packages/stripe-integration/src/stripe-ocs/stripe-ocs.ts
Added onConfirm method handling. Spinner will be added in the next ticket.
Related PR:
https://github.com/bigcommerce/checkout-js/pull/2410
https://github.com/user-attachments/assets/13150cca-b97e-4926-b055-1014342625a8
=> feat(payment): Stripe Link v2 onConfirm method

packages/core/src/payment/instrument/supported-payment-instruments.ts
Added bigcommerce payment related instruments to a list of supported instruments
So vaulted instruments will be rendered in payment section of checkout page 
Manual tests
CI
=> feat(payment): added bigcommerce payment related instruments to a list of supported instruments

packages/bigcommerce-payments-utils/src/bigcommerce-payments-fastlane-utils.ts, packages/core/src/shipping/strategies/paypal-commerce/paypal-commerce-fastlane-shipping-strategy.spec.ts, packages/core/src/shipping/strategies/paypal-commerce/paypal-commerce-fastlane-shipping-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-fastlane/paypal-commerce-fastlane-customer-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-fastlane/paypal-commerce-fastlane-customer-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-fastlane/paypal-commerce-fastlane-payment-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-fastlane/paypal-commerce-fastlane-payment-strategy.ts, packages/paypal-commerce-utils/src/create-paypal-commerce-fastlane-utils.ts, packages/paypal-commerce-utils/src/paypal-commerce-fastlane-utils.spec.ts, packages/paypal-commerce-utils/src/paypal-commerce-fastlane-utils.ts, packages/paypal-commerce-utils/src/paypal-commerce-types.ts
Updated ppcp fastlane implementation to use cookies instead of local storage
Local storage solution is not quite good in terms of security, since it is not possible to set expiration date for temporary data
Unit tests
Manual tests
CI
Now session id that we use to manage Fastlane authentication check stored in cookies:
And as you can see, it is not present in local storage anymore:
=> refactor(payment): updated ppcp fastlane implementation to use cookies instead of local storage

packages/bigcommerce-payments-integration/src/bigcommerce-payments-ratepay/bigcommerce-payments-ratepay-payment-strategy.spec.ts, packages/bigcommerce-payments-integration/src/bigcommerce-payments-ratepay/bigcommerce-payments-ratepay-payment-strategy.ts
Updated provider id used for order creation in BCP Ratepay Payment strategy
So BE request will not fail due to wrong provider input
Manual tests
Unit tests
CI
=> fix(payment): updated provider id used for order creation in BCP Ratepay Payment strategy

packages/stripe-integration/src/stripe-ocs/stripe-ocs-payment-strategy.spec.ts, packages/stripe-integration/src/stripe-ocs/stripe-ocs-payment-strategy.ts, packages/stripe-integration/src/stripe-utils/stripe.ts
Add toggle for Stripe OCS Link logic on the payments step
To control Link flow availability on payments step from Control Panel 
Before:
https://github.com/user-attachments/assets/ee10ac9f-cb19-41fe-8647-7d1adfecd45e
After:
https://github.com/user-attachments/assets/aec4f9b4-bf6e-44d1-842c-bc2cbf51603c
=> feat(payment): Enable Stripe OCS Link from control panel

packages/core/src/customer/customer-action-creator.spec.ts, packages/core/src/customer/customer-action-creator.ts, packages/core/src/customer/internal-customer-responses.ts
Fetch updated checkout after carts are merged
If persistent cart is enabled, carts are merged on sign-in. We should reload checkout and settings for the new id.
https://github.com/user-attachments/assets/9aff308f-bac8-4345-b137-f03d5730c893
=> fix(customer): Fetch updated checkout after carts are merged

packages/bigcommerce-payments-integration/src/bigcommerce-payments-fastlane/bigcommerce-payments-fastlane-payment-initialize-options.ts, packages/bigcommerce-payments-integration/src/bigcommerce-payments-fastlane/bigcommerce-payments-fastlane-payment-strategy.spec.ts, packages/bigcommerce-payments-integration/src/bigcommerce-payments-fastlane/bigcommerce-payments-fastlane-payment-strategy.ts, packages/bigcommerce-payments-utils/src/index.ts, packages/bigcommerce-payments-utils/src/utils/is-bigcommerce-fastlane-request-error.spec.ts, packages/bigcommerce-payments-utils/src/utils/is-bigcommerce-fastlane-request-error.ts
Added BCP FL corresponding error for 422 payment status
To show more user friendly error text
Unit  tests
=> feat(payment): Added BCP FL corresponding error for 422 payment status

packages/stripe-integration/src/stripe-ocs/stripe-link-v2-customer-strategy.spec.ts, packages/stripe-integration/src/stripe-ocs/stripe-link-v2-customer-strategy.ts, packages/stripe-integration/src/stripe-utils/stripe.ts
Disable Klarna on the customer step
Because we don't need it to be rendered
Manual testing
=> fix(payment): Stripe Link v2 Klarna disable

packages/braintree-integration/src/braintree-fastlane/braintree-fastlane-customer-strategy.spec.ts, packages/braintree-integration/src/braintree-fastlane/braintree-fastlane-payment-strategy.spec.ts, packages/braintree-integration/src/braintree-fastlane/braintree-fastlane-payment-strategy.ts, packages/braintree-integration/src/braintree-fastlane/braintree-fastlane-utils.spec.ts, packages/braintree-integration/src/braintree-fastlane/braintree-fastlane-utils.ts, packages/braintree-integration/src/braintree-fastlane/create-braintree-fastlane-customer-strategy.ts, packages/braintree-integration/src/braintree-fastlane/create-braintree-fastlane-payment-strategy.ts, packages/braintree-integration/src/braintree-local-payment-methods/braintree-local-methods-payment-strategy.ts, packages/braintree-integration/src/braintree-request-sender.spec.ts, packages/braintree-integration/src/braintree-request-sender.ts, packages/braintree-integration/src/mocks/braintree.mock.ts, packages/core/src/shipping/strategies/braintree/braintree-fastlane-shipping-strategy.spec.ts, packages/core/src/shipping/strategies/braintree/braintree-fastlane-shipping-strategy.ts
Updated Braintree Fastlane to use cookies instead of local storage
Cookies or local storage used for Fastlane integration to keep cart/session id there, so it can be used to check if customer was authorised into Fastlane in current session to trigger Fastlane authorisation once again (it does not require customer interaction) to get Fastlane data and fill in checkout form. However when customer cancels Fastlane authorisation, then session id will not be set to browser memory and Fastlane authentication will not be triggered in this session anymore, until customer force it by clicking continue button in customer step.
Keeping session id somewhere in browser memory is crucial for Fastlane authentication to work properly and do not bother customers with annoying OTPs. However the best place …
=> refactor(payment): updated Braintree Fastlane to use cookies instead of local storage

packages/braintree-integration/src/braintree-venmo/braintree-venmo-button-strategy.spec.ts, packages/braintree-integration/src/braintree-venmo/braintree-venmo-button-strategy.ts
Updated venmo button strategy with providing `loadDefaultCheckout` to load store config
To manage correct braintree version need to get to store config before braintree client load.
Before
After
=> feat(payment): Updated venmo button strategy with providing loadDefaultCheckout to load store config

README.md
Update the storefront APIs documentation to use the correct link.
https://developer.bigcommerce.com/docs/storefront/cart-checkout/guide/rest-storefront
Improve developer experience.
CI.
=> fix(checkout): Update Storefront APIs Doc URL

packages/stripe-integration/src/stripe-ocs/stripe-ocs-payment-strategy.spec.ts, packages/stripe-integration/src/stripe-ocs/stripe-ocs-payment-strategy.ts, packages/stripe-integration/src/stripe-utils/stripe.ts
Add ACH vaulting token to second payment confirmation request
Need this change for ACH vaultings
Before:
After:
=> feat(payment): Stripe OCS ACH vaulting

packages/braintree-utils/src/braintree-script-loader.spec.ts, packages/braintree-utils/src/braintree-script-loader.ts, packages/braintree-utils/src/braintree-sdk-version-manager.spec.ts, packages/braintree-utils/src/braintree-sdk-version-manager.ts, packages/braintree-utils/src/isManageableBraintreeSDKVersion.spec.ts, packages/braintree-utils/src/isManageableBraintreeSDKVersion.ts
Added support for Braintree versions loaded from third-party resources.
To prevent braintree version mismatches when it was loaded third-party resources.
Downloaded Braintree version `3.112.0` from Script Manager for testing purposes.
Before
https://github.com/user-attachments/assets/9824ac94-d3a3-4d4a-a449-2b3f3305bc44
After
https://github.com/user-attachments/assets/fe6d7932-eedd-45b0-ba02-f98139eb058f
https://github.com/user-attachments/assets/4ffb3965-4ec4-4584-ac38-a8f9f37ad083
PDP and Cart Page were tested as well
=> feat(payment): PAYPAL-5712 Handle BraintreeSDK version mismatch caused by custom scripts added by merchants

packages/core/src/hosted-form/hosted-field.spec.ts, packages/core/src/hosted-form/hosted-field.ts, packages/core/src/hosted-form/hosted-form-factory.spec.ts, packages/core/src/hosted-form/hosted-form-factory.ts, packages/core/src/payment-integration/default-payment-integration-service.spec.ts, packages/core/src/payment-integration/default-payment-integration-service.ts
Pass checkout id as part of hosted form request
In order to initialize hosted form pass checkout id so they can be initialized correctly for buy now carts as well.
- CI
=> chore(payment): CHECKOUT-9448 Pass checkout id as part of hosted form request

packages/core/src/hosted-form/hosted-field.ts
Check for checkout id before attaching to iframe
if checkout id is undefined it can cause issues with 403
- CI
=> fix(payment): CHECKOUT-9448 check for checkout id before attaching to iframe

packages/braintree-integration/src/braintree-venmo/braintree-venmo-payment-strategy-initialize-options.ts, packages/braintree-integration/src/braintree-venmo/braintree-venmo-payment-strategy.spec.ts, packages/braintree-integration/src/braintree-venmo/braintree-venmo-payment-strategy.ts, packages/braintree-integration/src/braintree-venmo/create-braintree-venmo-payment-strategy.spec.ts, packages/braintree-integration/src/braintree-venmo/create-braintree-venmo-payment-strategy.ts, packages/braintree-integration/src/index.ts, packages/braintree-integration/src/mocks/braintree.mock.ts, packages/braintree-utils/src/braintree-integration-service.ts, packages/braintree-utils/src/braintree.ts
Moved Braintree Venmo payment strategy to packages
To use it from packages
https://github.com/user-attachments/assets/48ad52b3-ac92-490f-85ba-1c3b4f77cf9f
=> refactor(payment): Moved Braintree Venmo payment strategy to packages

packages/core/src/billing/billing-address-action-creator.spec.ts, packages/core/src/billing/billing-address-action-creator.ts, packages/core/src/checkout/checkout-action-creator.ts, packages/core/src/shipping/consignment-action-creator.spec.ts, packages/core/src/shipping/consignment-action-creator.ts, packages/core/src/spam-protection/spam-protection-action-creator.spec.ts, packages/core/src/spam-protection/spam-protection-action-creator.ts
Remove following rolled out experiments
- CHECKOUT-8183_set_shouldSaveAddress_false_for_existing_address
- CHECKOUT-8392_fix_billing_creation_in_checkout
- CHECKOUT-8264_recaptcha_error_fix
- CHECKOUT-8999.remove_duplicate_shipping_option_call
- revert this PR
- CI
=> chore(other): CHECKOUT-9469 Remove rolled out experiments

packages/braintree-integration/src/braintree-paypal/braintree-paypal-payment-strategy.spec.ts, packages/braintree-integration/src/braintree-paypal/braintree-paypal-payment-strategy.ts
Add condition for Braintree PayPal message render
...
We have situations when Pay Later method (and button) on checkout page is disabled but BNPL messaging is still enabled
...
Manual
Unit
...
=> feat(payment): PAYPAL-5660 add Braintree PayPal message render condition

packages/stripe-integration/src/stripe-upe/stripe-upe-payment-strategy.spec.ts, packages/stripe-integration/src/stripe-upe/stripe-upe-payment-strategy.ts, packages/stripe-integration/src/stripe-upe/stripe-upe.mock.ts, packages/stripe-integration/src/stripe-utils/stripe-integration-service.spec.ts, packages/stripe-integration/src/stripe-utils/stripe-integration-service.ts, packages/stripe-integration/src/stripe-utils/stripe.ts
Added `allow_redirect` field on stripe confirmation method.
Related PR:
https://github.com/bigcommerce/bigcommerce/pull/64783
To make possible to transfer vaulted cards from UPE to OCS.
Manual testing
=> feat(payment): Stripe Upe allow_redirect added

packages/core/src/payment/strategies/ppsdk/sub-strategies/card-sub-strategy.spec.ts, packages/core/src/payment/strategies/ppsdk/sub-strategies/card-sub-strategy.ts
Pass checkout id to hosted form form ppsdk providers
In order to support buy now carts we need to pass checkout id to hosted form initialisation call.
- CI 
=> fix(payment): CHECKOUT-9493 Pass checkout id to hosted form ppsdk providers

packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-button-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-button-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-customer-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-customer-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-button-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-button-strategy.ts, packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-customer-strategy.spec.ts, packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-customer-strategy.ts
Covered shipping callbacks with experiment to turn them off when appSwitch enabled
Revert
Unit tests
=> feat(payment): PAYPAL-5875 covered shipping callbacks with experiment

.circleci/config.yml, .eslintignore, package.json, packages/adyen-utils/src/index.ts, packages/adyen-utils/src/types.ts, packages/core/api-extractor/checkout-button.json, packages/core/api-extractor/checkout-sdk.json, packages/core/api-extractor/embedded-checkout.json, packages/core/api-extractor/internal-mappers.json, packages/core/auto-export.config.json, packages/core/project.json, packages/core/src/common/utility/set-prototype-of.spec.ts, packages/external-integration/src/external-payment-strategy.ts, packages/google-pay-integration/src/google-pay-payment-processor.ts, packages/google-pay-integration/src/google-pay-payment-strategy.ts, packages/hosted-form-v2/src/common/utility/set-prototype-of.spec.ts, packages/paypal-express-integration/src/paypal-express-button-initialize-options.ts, packages/squarev2-integration/src/create-squarev2-payment-strategy.ts, packages/workspace-tools/src/generators/auto-export/__snapshots__/auto-export.spec.ts.snap, packages/workspace-tools/src/generators/auto-export/auto-export-config.ts, packages/workspace-tools/src/generators/auto-export/auto-export.spec.ts, packages/workspace-tools/src/generators/auto-export/auto-export.ts, packages/workspace-tools/src/generators/auto-export/generator.ts, packages/workspace-tools/src/generators/auto-export/is-auto-export-config.ts, tsconfig.base.json, webpack-common.config.js, webpack.config.js
This PR was split from #2989 to make it easier for reviewers. It includes the following changes:
* Added a new export, @bigcommerce/checkout-sdk/essential, which excludes all payment, shipping, and checkout button strategies from the bundle.
* Added an ESM build, allowing the library to be fully tree-shakable.
For context on the purpose of this change, please refer to the parent PR.
Revert
See #2989
=> CHECKOUT-9450: Export ESM modules and separate payment integration strategies from core bundle

packages/stripe-integration/src/stripe-ocs/stripe-link-v2-customer-strategy.spec.ts, packages/stripe-integration/src/stripe-ocs/stripe-link-v2-customer-strategy.ts, packages/stripe-integration/src/stripe-ocs/stripe-ocs.mock.ts, packages/stripe-integration/src/stripe-ocs/stripe-ocs.ts, packages/stripe-integration/src/stripe-utils/stripe.ts
Passing captureMethod to the Stripe OCS Link configuration. To make possible perform auth only orders.
Revert this PR.
Manual testing.
https://github.com/user-attachments/assets/fe9cf731-f4c4-49df-963c-b79f88538c99
=> feat(payment): Stripe OCS Link captureMethod added

.circleci/config.yml
Increase the resource size for the `lint` job in CircleCI so it doesn't run out of resources.
Revert
CircleCI
=> CHECKOUT-9450: Increase resource class for linting task
