src/cart/cart-reducer.spec.js
src/cart/cart-reducer.ts
src/checkout/checkout-reducer.spec.ts
src/checkout/checkout-reducer.ts
src/checkout/checkout-service.ts
src/checkout/checkout-store-error-selector.spec.js
src/checkout/checkout-store-error-selector.ts
src/checkout/checkout-store-status-selector.spec.js
src/checkout/checkout-store-status-selector.ts
src/coupon/gift-certificate-reducer.spec.ts
src/coupon/gift-certificate-reducer.ts
src/shipping/consignment-action-creator.spec.ts
src/shipping/consignment-action-creator.ts
src/shipping/consignment-actions.ts
src/shipping/consignment-reducer.spec.ts
src/shipping/consignment-reducer.ts
src/shipping/consignment-request-sender.spec.ts
src/shipping/consignment-request-sender.ts
src/shipping/consignment-selector.spec.ts
src/shipping/consignment-selector.ts
src/shipping/consignment-state.ts
src/shipping/consignments.mock.ts

Delete consignment method
To allow clients to delete consignments

CHECKOUT-3393 Delete consignment

---

src/payment/payment-method-reducer.ts

https://jira.bigcommerce.com/browse/CHECKOUT-3398
Sentry

fix(payment): CHECKOUT-3398 Check payment method payload

---

src/checkout/create-internal-checkout-selectors.ts
src/shipping/consignment-selector.spec.ts
src/shipping/consignment-selector.ts

Adds `ConsignmentSelector#getUnassginedItems` method
Convenience method
unit

CHECKOUT-3461 Add ConsignmentSelector#getUnassignedItems method

---

src/order/order-request-sender.spec.ts
src/order/order-request-sender.ts

Include options for line items in OrderRequestSender

CHECKOUT-3437 Include options in line items for orders

---

.travis.yml

* Configure Code Climate coverage reporter.
* Display code coverage report in Code Climate.
* Manual

CHECKOUT-3541: Configure Code Climate coverage reporter

---

.codeclimate.yml

* Add Code Climate config
* To configure Code Climate
* Manual

CHECKOUT-3541: Add Code Climate config

---

src/config/config.ts
src/config/configs.mock.ts
src/coupon/coupon-action-creator.spec.ts
src/coupon/coupon-request-sender.spec.ts
src/coupon/coupon-selector.spec.ts

- Convert coupon tests to TS
- Add new checkout setting
https://github.com/bigcommerce/bigcommerce/pull/26158

Coupon code TS

---

src/currency/create-currency-service.ts
src/currency/currency-service.ts

Fix the config to storeConfig type in currency service
Because only the storeConfig is available externally.

CHECKOUT-3529 Fix createCurrencyService type

---

src/checkout/create-checkout-service.spec.ts
src/checkout/create-checkout-service.ts
src/config/config-reducer.ts
src/config/config-selector.spec.ts
src/config/config-selector.ts
src/config/config-state.ts
src/config/configs.mock.ts
src/order/internal-order-request-body.ts
src/order/internal-orders.mock.ts
src/order/order-action-creator.ts

As per above.
Identify if the request is from external partners
Unit test and manual testing.

feat(order): CHECKOUT-3563 Add External Source param when creating order

---

src/cart/carts.mock.ts
src/order/orders.mock.ts

CHECKOUT-1739 Fix mocks linting issues

---

src/checkout-buttons/checkout-button-actions.ts
src/checkout-buttons/checkout-button-error-selector.ts
src/checkout-buttons/checkout-button-initializer.spec.ts
src/checkout-buttons/checkout-button-initializer.ts
src/checkout-buttons/checkout-button-options.ts
src/checkout-buttons/checkout-button-reducer.spec.ts
src/checkout-buttons/checkout-button-reducer.ts
src/checkout-buttons/checkout-button-selector.spec.ts
src/checkout-buttons/checkout-button-selector.ts
src/checkout-buttons/checkout-button-state.ts
src/checkout-buttons/checkout-button-status-selector.ts
src/checkout-buttons/checkout-button-strategy-action-creator.spec.ts
src/checkout-buttons/checkout-button-strategy-action-creator.ts
src/checkout-buttons/create-checkout-button-registry.ts
src/checkout-buttons/strategies/braintree-paypal-button-options.ts
src/checkout-buttons/strategies/braintree-paypal-button-strategy.spec.ts
src/checkout-buttons/strategies/braintree-paypal-button-strategy.ts
src/checkout-buttons/strategies/checkout-button-method-type.ts
src/checkout-buttons/strategies/checkout-button-strategy.ts
src/checkout-buttons/strategies/index.ts
src/checkout-buttons/strategies/masterpass-button-options.ts
src/checkout-buttons/strategies/masterpass-button-strategy.spec.ts
src/checkout-buttons/strategies/masterpass-button-strategy.ts
src/common/registry/registry.ts
src/payment/payment-strategy-registry.ts

Allows rendering checkout buttons more than once.

CHECKOUT-3584 Allow rendering checkout buttons more than once

---

CHANGELOG.md

Amend changelog
Because forgot to properly format commit after squashing PR

CHECKOUT-3584 Amend changelog

---

src/order/order-action-creator.spec.ts
src/order/order-reducer.spec.ts

TypeScript 100% for `order` module

CHECKOUT-2934 Convert order tests into TypeScript

---

src/payment/strategies/googlepay/googlepay-braintree-initializer.ts
src/payment/strategies/googlepay/googlepay-stripe-initializer.ts
src/payment/strategies/googlepay/googlepay.mock.ts

As per described
In production environment we are getting this error
...

fix(payment): INT-1080 Round totalPrice to 2 decimals

---

README.md

Update the readme file with new links to the getting started tutorials in the new BC Dev Center.
To make it easier for Developers to get started with using the Checkout JS SDK by providing them with up to date  documentation.
...

CHECKOUT-3772  Update README with get starting guides

---

package-lock.json
package.json
src/billing/billing-address-action-creator.spec.ts
src/checkout/checkout-default-includes.ts
src/checkout/checkout-request-sender.ts
src/checkout/checkout-store-error-selector.ts
src/checkout/checkout-store-status-selector.ts
src/common/error/request-error-factory.ts
src/currency/currency-service.ts
src/customer/strategies/braintree-visacheckout-customer-strategy.ts
src/locale/language-service.ts
src/locale/messageformat.d.ts
src/payment/create-payment-client.ts
src/payment/is-nonce-like.spec.ts
src/payment/strategies/amazon-pay/amazon-pay-wallet.ts
src/payment/strategies/braintree/visacheckout-script-loader.spec.ts
src/payment/strategies/chasepay/chasepay-script-loader.spec.ts
src/payment/strategies/googlepay/googlepay-script-loader.spec.ts
src/payment/strategies/klarna/klarna-credit.ts
src/payment/strategies/masterpass/masterpass-payment-strategy.spec.ts
tslint.json

* Upgrade TSLint config.
* Remove some of the rules and overrides that are already covered by the latest config.
* To bring in the latest config.
* Travis

CHECKOUT-2900: Upgrade TSLint config

---

package-lock.json
src/common/registry/registry.ts
src/payment/create-payment-strategy-registry.spec.ts
src/payment/create-payment-strategy-registry.ts
src/payment/payment-strategy-action-creator.spec.ts
src/payment/payment-strategy-action-creator.ts
src/payment/payment-strategy-registry.spec.ts
src/payment/payment-strategy-registry.ts
src/payment/payment-strategy-type.ts

Use enums for PaymentStrategies
For more robust code / stricter types

CHECKOUT-3714 Convert payment strategies to enum

---

src/config/config.ts
src/config/configs.mock.ts
src/currency/currency-service.ts

Add isAnalyticsEnabled to checkout settings
Because it's missing

CHECKOUT-3914 Add isAnalyticsEnabled to checkout settings

---

package-lock.json
package.json

Bump BigPay client to v3.2.4.
https://github.com/bigcommerce/bigpay-client-js/pull/74
Travis

fix(payment): INT-1360 Bump BigPay client.

---

src/payment/create-payment-strategy-registry.ts
src/payment/strategies/masterpass/masterpass-payment-strategy.spec.ts
src/payment/strategies/masterpass/masterpass-payment-strategy.ts

- Fix masterpass payload to allow correct payment method & gateway tracking.
- Payments made through masterpass were tracked as stripe.
[BCAPP#29332](https://github.com/bigcommerce/bigcommerce/pull/29332) **Must be merged before this.**
https://drive.google.com/open?id=1KGg0zaIzvG_uavxNYfdWGZG5C6UCKxzf

fix(payment): INT-1412 Fix masterpass submitPayment payload

---

src/common/error/errors/missing-data-error.ts
src/payment/create-payment-strategy-registry.ts
src/payment/payment-methods.mock.ts
src/payment/payment-strategy-type.ts
src/payment/strategies/affirm/affirm-payment-strategy.spec.ts
src/payment/strategies/affirm/affirm-payment-strategy.ts
src/payment/strategies/affirm/affirm-script-loader.spec.ts
src/payment/strategies/affirm/affirm-script-loader.ts
src/payment/strategies/affirm/affirm.mock.ts
src/payment/strategies/affirm/affirm.ts
src/payment/strategies/affirm/affirmJs.ts
src/payment/strategies/affirm/index.ts

Create the Affirm modal Payment strategy and make it available in checkout.
New payment strategy is required to support Affirm
https://drive.google.com/file/d/1EJkoVmgfwltW3brQldGSUD07n7EzfY-Q/view?usp=sharing
Coverage
@bigcommerce/checkout @bigcommerce/payments @bigcommerce/integrations

feat(checkout): INT-1293 Affirm checkout strategy

---

src/payment/create-payment-strategy-registry.ts
src/payment/payment-methods.mock.ts
src/payment/payment-strategy-type.ts
src/payment/strategies/zip/index.ts
src/payment/strategies/zip/zip-payment-strategy.spec.ts
src/payment/strategies/zip/zip-payment-strategy.ts
src/payment/strategies/zip/zip-script-loader.spec.ts
src/payment/strategies/zip/zip-script-loader.ts
src/payment/strategies/zip/zip.mock.ts
src/payment/strategies/zip/zip.ts

[INT-1245](https://jira.bigcommerce.com/browse/INT-1245)
Create the Zip Payment strategy along with the required interfaces and tests
A payment strategy is required to support zip on the checkout
Pending Deploy(#)
Coverage: 
@cmedinilla 
@bigcommerce/checkout @bigcommerce/payments @bigcommerce/integrations

feat(checkout): INT-1245 Checkout Using Zip

---

src/shipping/consignment-reducer.ts

Make `ConsignmentReducer` return a new object when there is new data
So data store can trigger observables
N/A

CHECKOUT-4160 Return new object in reducer

---

README.md
package-lock.json
src/address/address.ts
src/address/index.ts
src/address/internal-address.ts
src/cart/cart.ts
src/cart/carts.mock.ts
src/checkout/checkout-service.ts
src/checkout/checkout-store-selector.spec.ts
src/config/config.ts
src/config/configs.mock.ts
src/customer/customer.ts
src/customer/customers.mock.ts
src/form/form-field.ts
src/form/form-selector.spec.ts
src/form/form-selector.ts
src/form/form.mocks.ts
src/shipping/shipping-strategy-action-creator.ts
src/shipping/strategies/shipping-strategy.ts

Update SDK types
To reflect better the real object structures.
N/A

CHECKOUT-4201 Match SDK types with API payloads

---

package-lock.json
package.json

* Bump Bigpay client version
* https://github.com/bigcommerce/bigpay-client-js/blob/master/CHANGELOG.md

INT-1577: Bump Bigpay client version

---

src/checkout/checkout-reducer.ts
src/checkout/checkout-selector.spec.ts
src/checkout/checkout-selector.ts
src/checkout/checkout-state.ts
src/checkout/create-internal-checkout-selectors.ts
src/checkout/index.ts

* Refactor `CheckoutSelector` to return new getters only when there are changes to relevant data.
* Update `checkoutReducer` to transform state only when it is necessary.
Unit

CHECKOUT-4272: Optimise checkout selector and reducer

---

README.md

As per above.
To document the spam protection feature
...

docs(order): CHECKOUT-4241 Add README for initializing spam protection

---

src/payment/strategies/stripev3/stripev3-payment-strategy.spec.ts
src/payment/strategies/stripev3/stripev3-payment-strategy.ts
src/payment/strategies/stripev3/stripev3.ts

[INT-1836](https://jira.bigcommerce.com/browse/INT-1836)
An issue was detected with Stripe V3 using vaulted instruments and 3DS is required by Stripe

fix(payment): INT-1836 Update strategy to support 3ds with vaulting

---

package-lock.json
package.json
src/payment/payment-request-sender.spec.ts
src/payment/payment-request-sender.ts

Upgrade `bigpay-client` version
https://github.com/bigcommerce/bigpay-client-js/blob/master/CHANGELOG.md
CircleCI

CHECKOUT-4418: Upgrade `bigpay-client` version

---

package-lock.json
package.json
src/address/internal-address.ts
src/address/map-to-internal-address.ts
src/cart/line-item.ts
src/common/data-store/cachable-action-decorator.ts
src/common/utility/bind-decorator.ts
src/common/utility/create-freeze-proxy.ts
src/common/utility/merge-or-push.spec.ts
src/customer/internal-customer.ts
src/embedded-checkout/iframe-content/iframe-embedded-checkout-messenger.ts
src/embedded-checkout/iframe-event-listener.ts
src/payment/strategies/afterpay/afterpay-script-loader.ts
src/payment/strategies/klarna/klarna-script-loader.ts
src/payment/strategies/square/square-script-loader.ts
src/payment/strategies/wepay/wepay-risk-client.ts

Upgrade to latest TS
We are one major version behind. This way we can use latest features
linter

CHECKOUT-4403 Upgrade to latest Typescript

---

.circleci/config.yml
.versionrc.json
package-lock.json
package.json

Build and publish new releases from CircleCI.
So we don't have to create releases locally.
CircleCI

CHECKOUT-4428: Build and publish release from CircleCI

---

src/payment/instrument/instrument-response-body.ts
src/payment/instrument/instrument.ts
src/payment/instrument/map-to-card-instrument.ts
src/payment/instrument/supported-payment-instruments.ts
src/payment/strategies/adyenv2/adyenv2-payment-strategy.ts
src/payment/strategies/adyenv2/adyenv2.mock.ts
src/payment/strategies/adyenv2/adyenv2.ts

As a requirement from David Aland, we need to add a new field in BigPay DB, so to support this change is needed all these changes
To support the new approach of vaulted instrument for Adyen V2
No test were affected

INT-1902 Update supported payment instrument

---

package-lock.json
package.json
src/hosted-form/iframe-content/card-expiry-date.ts
src/hosted-form/iframe-content/card-expiry-formatter.spec.ts
src/hosted-form/iframe-content/card-expiry-formatter.ts
src/hosted-form/iframe-content/card-number-formatter.spec.ts
src/hosted-form/iframe-content/card-number-formatter.ts

* Format credit card number and expiry date values.
* Originally the code lives in UCO. I've copied it across to this repo with some slight modifications.
We want to format the values for better user experience. Also, we need to preserve the existing behaviour.
CircleCI

CHECKOUT-4204: Format credit card field values

---

package-lock.json
package.json

Bump bigpay-client version
https://github.com/bigcommerce/bigpay-client-js/blob/master/CHANGELOG.md#540-2020-01-02
CircleCI
@bigcommerce/checkout @bigcommerce/intersys-integrations

chore(payment): INT-1780 INT-1997 Bump bigpay-client version

---

.circleci/config.yml
.eslintrc.json
.gitignore
api-extractor/checkout-sdk.json
package-lock.json
package.json
scripts/circleci/update-server.sh
scripts/webpack/index.js
scripts/webpack/transform-manifest.js
src/analytics/analytics-step-tracker.spec.ts
src/bundles/checkout-sdk.ts
src/common/types/webpack.d.ts
src/index.ts
src/loader.ts
tsconfig.json
webpack-common.config.js
webpack-server.config.js
webpack.config.js

Build distribution files for a static server.
We want to make the SDK available on CDN. In order to that, we'll need to set up a server and deploy the built files there. A separate private repository and build process have been set up to handle that part. Here, we just have to push the built files to the server repository so that it can handle the rest.
CircleCI

CHECKOUT-4187: Build distribution files for static server

---

jest-setup.js
package-lock.json
package.json
scripts/circleci/update-server.sh
scripts/standard-version/prebump.js
scripts/webpack/get-next-version.js
scripts/webpack/index.js
src/common/types/webpack.d.ts
src/hosted-form/hosted-field.spec.ts
src/hosted-form/hosted-field.ts
webpack-common.config.js
webpack-server.config.js
webpack.config.js

* Create a version-specific loader file and reference it in hosted payment form.
* Bonus: Added a command for releasing alpha versions
So that the version used in UCO can be aligned with the version used in the payment form. 
CircleCI

CHECKOUT-4669: Create version-specific loader file and reference it in hosted payment form

---

src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-strategy.spec.ts
src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-strategy.ts
src/payment/create-payment-strategy-registry.ts
src/payment/payment-methods.mock.ts
src/payment/payment-strategy-type.ts
src/payment/strategies/paypal-commerce/index.ts
src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.spec.ts
src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.ts
src/payment/strategies/paypal-commerce/paypal-commerce-script-loader.spec.ts

Create request for creation order in bcapp
Create request to bigpay for creation payment 
Payment order with PayPal Commerce

feat(payments): PAYPAL-200 Create order request to bcapp 

---

src/payment/create-payment-strategy-registry.ts
src/payment/payment-methods.mock.ts
src/payment/strategies/adyenv2/adyenv2-payment-strategy.spec.ts
src/payment/strategies/adyenv2/adyenv2-payment-strategy.ts
src/payment/strategies/adyenv2/adyenv2.mock.ts
src/payment/strategies/adyenv2/adyenv2.ts

refactor(payment): INT-2350 Use createFromAction for every payment method

---

src/checkout-buttons/checkout-button-options.ts
src/checkout-buttons/create-checkout-button-registry.ts
src/checkout-buttons/strategies/checkout-button-method-type.ts
src/checkout-buttons/strategies/googlepay/googlepay-authorizenet-button-strategy.spec.ts
src/checkout-buttons/strategies/googlepay/googlepay-button.mock.ts
src/customer/create-customer-strategy-registry.ts
src/customer/customer-request-options.ts
src/customer/strategies/googlepay/googlepay-authorizenet-customer-strategy.spec.ts
src/customer/strategies/googlepay/googlepay-customer-mock.ts
src/customer/strategies/googlepay/googlepay-customer-strategy.ts
src/payment/create-payment-strategy-registry.ts
src/payment/payment-request-options.ts
src/payment/payment-strategy-type.ts
src/payment/strategies/googlepay/googlepay-authorizenet-initializer.spec.ts
src/payment/strategies/googlepay/googlepay-authorizenet-initializer.ts
src/payment/strategies/googlepay/googlepay-payment-strategy.ts
src/payment/strategies/googlepay/googlepay.mock.ts
src/payment/strategies/googlepay/googlepay.ts
src/payment/strategies/googlepay/index.ts

- GooglePayAuthorizeNetInitializer
- Registered on Checkout button registry
- Registered on Customer strategy registry
- Registered on Payment strategy registry
To checkout using Google Pay on Auth.net
CircleCI

feat(payment): INT-1104 Add GooglePay on Auth.net

---

package-lock.json
package.json

As titled
To use the Jest tested, CircleCi build @bigcommerce/bigpay-client
Successful build

Bump @bigcommerce/bigpay-client

---

src/checkout-buttons/create-checkout-button-registry.ts
src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-strategy.spec.ts
src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-strategy.ts
src/payment/strategies/paypal-commerce/index.ts
src/payment/strategies/paypal-commerce/paypal-commerce-request-sender.spec.ts
src/payment/strategies/paypal-commerce/paypal-commerce-request-sender.ts
src/payment/strategies/paypal-commerce/paypal-commerce-script-loader.spec.ts
src/payment/strategies/paypal-commerce/paypal-commerce-script-loader.ts
src/payment/strategies/paypal-commerce/paypal-commerce-sdk.ts

Disable Credit/Debit card SPB
This button will not be available to merchants as part of PPCP BC integration

feat(payment): PAYPAL-288 Disable Credit/Debit card SPB

---

src/checkout-buttons/checkout-button-options.ts
src/checkout-buttons/create-checkout-button-registry.ts
src/checkout-buttons/strategies/amazon-maxo/amazon-maxo-button-options.ts
src/checkout-buttons/strategies/amazon-maxo/amazon-maxo-button-strategy.spec.ts
src/checkout-buttons/strategies/amazon-maxo/amazon-maxo-button-strategy.ts
src/checkout-buttons/strategies/amazon-maxo/amazon-maxo-button.mock.ts
src/checkout-buttons/strategies/amazon-maxo/index.ts
src/checkout-buttons/strategies/checkout-button-method-type.ts
src/customer/create-customer-strategy-registry.ts
src/customer/customer-request-options.ts
src/customer/strategies/amazon-maxo/amazon-maxo-customer-initialize-options.ts
src/customer/strategies/amazon-maxo/amazon-maxo-customer-strategy.spec.ts
src/customer/strategies/amazon-maxo/amazon-maxo-customer-strategy.ts
src/customer/strategies/amazon-maxo/amazon-maxo-customer.mock.ts
src/customer/strategies/amazon-maxo/index.ts
src/payment/payment-methods.mock.ts
src/payment/payment-request-options.ts
src/payment/strategies/amazon-maxo/amazon-maxo-payment-initialize-options.ts
src/payment/strategies/amazon-maxo/amazon-maxo-payment-processor.spec.ts
src/payment/strategies/amazon-maxo/amazon-maxo-payment-processor.ts
src/payment/strategies/amazon-maxo/amazon-maxo-script-loader.spec.ts
src/payment/strategies/amazon-maxo/amazon-maxo-script-loader.ts
src/payment/strategies/amazon-maxo/amazon-maxo.mock.ts
src/payment/strategies/amazon-maxo/amazon-maxo.ts
src/payment/strategies/amazon-maxo/create-amazon-maxo-payment-processor.ts
src/payment/strategies/amazon-maxo/index.ts

Add Button and customer Strategy for Amazon Maxo
To enable buttons for Amazon Maxo on Cart and customer checkout section

feat(payment): INT-2113 Checkout button and customer strategy

---

src/payment/strategies/klarnav2/klarnav2-payment-strategy.spec.ts

Fix unit testing for Klarna v2
It's necessary to complete the unit test in Klarna v2

fix(payment): INT-2452 fix testing in klarna v2

---

src/payment/strategies/credit-card/credit-card-payment-strategy.spec.ts
src/payment/strategies/credit-card/credit-card-payment-strategy.ts

Handle scenario where hosted fields are not available to be rendered.
If a merchant has configured vaulted cards with vaulted cvv code since there is no field expected to be filled out, the hosted form should not be rendered.
Refer PR https://github.com/bigcommerce/checkout-js/pull/261

fix(checkout): CHECKOUT-4774 Handle no hosted fields to be rendered scenario

---

src/cart/cart-selector.ts
src/checkout-buttons/checkout-button-options.ts
src/checkout-buttons/create-checkout-button-registry.ts
src/checkout-buttons/strategies/checkout-button-method-type.ts
src/checkout-buttons/strategies/paypal-commerce/index.ts
src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-options.ts
src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-strategy.spec.ts
src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-strategy.ts
src/common/overlay/index.ts
src/common/overlay/overlay-style.ts
src/common/overlay/overlay.spec.ts
src/common/overlay/overlay.ts
src/payment/create-payment-strategy-registry.ts
src/payment/payment-methods.mock.ts
src/payment/payment-request-options.ts
src/payment/payment-strategy-type.ts
src/payment/strategies/paypal-commerce/index.ts
src/payment/strategies/paypal-commerce/paypal-commerce-payment-initialize-options.ts
src/payment/strategies/paypal-commerce/paypal-commerce-payment-processor.spec.ts
src/payment/strategies/paypal-commerce/paypal-commerce-payment-processor.ts
src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.spec.ts
src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.ts
src/payment/strategies/paypal-commerce/paypal-commerce-request-sender.spec.ts
src/payment/strategies/paypal-commerce/paypal-commerce-request-sender.ts
src/payment/strategies/paypal-commerce/paypal-commerce-script-loader.spec.ts
src/payment/strategies/paypal-commerce/paypal-commerce-script-loader.ts
src/payment/strategies/paypal-commerce/paypal-commerce-sdk.ts
src/payment/strategies/paypal-commerce/paypal-commerce.mock.ts

Squashed copy of https://github.com/bigcommerce/checkout-sdk-js/tree/paypal_commerce + `@internal` tags 
Release Paypal Commerce for alpha/beta testing 
for the beta, we need to release a few more PRs
Manual testing / Unit tests 

feat(payment): PAYPAL COMMERCE squashed + @internal

---

README.md

* Update the instruction on spam protection checks.
* Add missing bullet points to README.
Better documentation.
None

CHECKOUT-4854: Update the instruction on spam protection checks and add missing bullet points to README

---

src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-strategy.spec.ts
src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-strategy.ts
src/payment/create-payment-strategy-registry.ts
src/payment/payment-strategy-type.ts
src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.ts
src/payment/strategies/paypal-commerce/paypal-commerce-request-sender.spec.ts
src/payment/strategies/paypal-commerce/paypal-commerce-request-sender.ts

Implement paypalcommercecredit provider
For credit option in PayPal Commerce

feat(payment): PAYPAL-293 Implement paypalcommercecredit provider

---

package-lock.json
package.json

Bump bigpay-client version to 5.6.0
To use paypal_commerce in payment method mapper

feat(payment): PAYPAL-293 Bump bigpay-client version to 5.6.0

---

src/payment/strategies/googlepay/googlepay-payment-strategy.spec.ts
src/payment/strategies/googlepay/googlepay-payment-strategy.ts

Expose Adyen as a valid Google Pay gategay
This code got lost while rebasing master before merging PR [#818](https://github.com/bigcommerce/checkout-sdk-js/pull/818)
- Manual
- Unit

fix(payment): INT-2690 Expose AdyenV2 as a valid GooglePay gateway

---

src/payment/strategies/zip/zip-payment-strategy.spec.ts
src/payment/strategies/zip/zip-payment-strategy.ts

[INT-2674](https://jira.bigcommerce.com/browse/INT-2674)
Change onCheckout event for zip strategy
to fix a issue where on checkout would be redirected to home
[INT-2674](https://drive.google.com/open?id=1K5mEXBf3ydJyCLdKBzYja6o7gA2ewlel)

fix(payment): INT-2674 Fix redirect to home on safari

---

src/payment/strategies/zip/zip-payment-strategy.spec.ts
src/payment/strategies/zip/zip-payment-strategy.ts

[INT-2726](https://jira.bigcommerce.com/browse/INT-2726)
Revert commit 661f50333f003af00ba1bc99d257988c21d71c54
Is causing some unexpected issues in zip's incomplete orders
Deploy ->  https://launchbay.bigcommerce.net/deployments/167109

revert(payment): INT-2726 Revert Fix redirect to home on safari

---

src/customer/strategies/braintree/braintree-visacheckout-customer-strategy.ts

[INT-2308](https://jira.bigcommerce.com/browse/INT-2308)
Align Visa Checkout button at checkout section.
The text is not placed correctly

fix(common): INT-2308 Align button Tell me more at checkout section

---

README.md
src/checkout/checkout-service.ts
src/checkout/checkout-store-error-selector.ts
src/checkout/checkout.ts
src/customer/customer.ts

Improve documentation for:
- Continue as guest
- Passwordless Login
Because it was missing/incomplete
n/a

CHECKOUT-4912 Documentation for continueAsGuest and sendSignInEmail

---

package-lock.json
package.json
src/hosted-form/hosted-field.spec.ts
src/hosted-form/hosted-field.ts
src/hosted-form/hosted-form-factory.spec.ts
src/hosted-form/hosted-form-factory.ts
src/hosted-form/iframe-content/get-hosted-input-storage.ts
src/hosted-form/iframe-content/hosted-input-factory.ts
src/hosted-form/iframe-content/hosted-input-initializer.spec.ts
src/hosted-form/iframe-content/hosted-input-initializer.ts
src/hosted-form/iframe-content/hosted-input-options.ts
src/hosted-form/iframe-content/hosted-input-payment-handler.spec.ts
src/hosted-form/iframe-content/hosted-input-payment-handler.ts
src/hosted-form/iframe-content/hosted-input-storage.spec.ts
src/hosted-form/iframe-content/hosted-input-storage.ts
src/hosted-form/iframe-content/initialize-hosted-input.ts
src/payment/payment-request-transformer.spec.ts
src/payment/payment-request-transformer.ts
src/payment/payment.ts
src/payment/strategies/credit-card-redirect/credit-card-redirect-payment-strategy.spec.ts
src/payment/strategies/credit-card/credit-card-payment-strategy.spec.ts
src/payment/strategies/credit-card/credit-card-payment-strategy.ts
src/spam-protection/payment-human-verification-handler.spec.ts
src/spam-protection/payment-human-verification-handler.ts

Initialise hosted payment fields within their own iframe.
We're changing the implementation to work with newer browsers and provide a better user experience.
Unit
@bigcommerce/checkout @bigcommerce/payments @abhijethbc

CHECKOUT-4973: Initialise hosted payment field within its iframe

---

src/payment/strategies/paypal-commerce/paypal-commerce-script-loader.spec.ts
src/payment/strategies/paypal-commerce/paypal-commerce-script-loader.ts
src/payment/strategies/paypal-commerce/paypal-commerce-sdk.ts

Reverts bigcommerce/checkout-sdk-js#924

Revert "feat(payment): PAYPAL-539 MerchantId does not required "

---

src/config/config.ts
src/config/configs.mock.ts

Added a new type to storeConfig for displayDateFormat and inputDateFormat.

fix(checkout): CHECKOUT-5006 added displayDateFormat type

---

src/payment/strategies/adyenv2/adyenv2-payment-strategy.spec.ts
src/payment/strategies/adyenv2/adyenv2-payment-strategy.ts
src/payment/strategies/adyenv2/adyenv2.ts

autopopulate billing with billing from checkout
To reduce shopper friction.
- Manual
- Unit

feat(payment): INT-2801 Pre-populate ACH Billing Info on AdyenV2

---

src/payment/create-payment-strategy-registry.ts
src/payment/instrument/supported-payment-instruments.ts
src/payment/payment-methods.mock.ts
src/payment/strategies/bolt/bolt-app-payment-strategy.spec.ts
src/payment/strategies/bolt/bolt-app-payment-strategy.ts
src/payment/strategies/bolt/bolt-payment-strategy.ts
src/payment/strategies/bolt/bolt-script-loader.spec.ts
src/payment/strategies/bolt/bolt-script-loader.ts
src/payment/strategies/bolt/bolt.mock.ts
src/payment/strategies/bolt/bolt.ts
src/payment/strategies/bolt/index.ts

[INT-2919](https://jira.bigcommerce.com/browse/INT-2919)
Create a strategy to use bolt's client script in the bigcommerce checkout.
So the Bolt's client script can be used to process the checkout.
(Pending)
bigcommerce/checkout bigcommerce/payments

feat(checkout): INT-2919 Create an strategy in order to use Bolt in Bigcommerce checkout

---

src/checkout-buttons/checkout-button-options.ts
src/checkout-buttons/strategies/checkout-button-method-type.ts
src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-options.ts
src/payment/payment-request-options.ts
src/payment/payment-strategy-type.ts
src/payment/strategies/paypal-commerce/paypal-commerce-sdk.ts

Add PPCP to SDK documentation
PPCP is not in alpha version and others can use it
...

feat(payment): PAYPAL-652 Add PPCP to SDK documentation

---

package-lock.json
package.json

Bump bigpay-client-js
Bumping dependencies. See https://github.com/bigcommerce/bigpay-client-js/pull/108
CircleCI

chore(payment): PAYMENTS-5833 Bump bigpay-client-js

---

src/payment/strategies/paypal-commerce/paypal-commerce-credit-card-payment-strategy.ts
src/payment/strategies/paypal-commerce/paypal-commerce-hosted-form.spec.ts
src/payment/strategies/paypal-commerce/paypal-commerce-hosted-form.ts
src/payment/strategies/paypal-commerce/paypal-commerce-payment-processor.spec.ts
src/payment/strategies/paypal-commerce/paypal-commerce-payment-processor.ts
src/payment/strategies/paypal-commerce/paypal-commerce-sdk.ts

Add checking 3ds for PayPal Commerce
https://www.loom.com/share/cd20ce2ddc7a4b1bbf68400135cd5fbd

feat(payment): PAYPAL-553 3ds for PayPal

---

FAQS.md
README.md

Add FAQs to Checkout SDK
To expand the documentation and address common issues.
n/a

docs(common): CHECKOUT-5168 Add FAQs to Checkout SDK

---

src/payment/strategies/paypal-commerce/paypal-commerce-hosted-form.ts
src/payment/strategies/paypal-commerce/paypal-commerce-payment-processor.spec.ts
src/payment/strategies/paypal-commerce/paypal-commerce-payment-processor.ts
src/payment/strategies/paypal-commerce/paypal-commerce-sdk.ts

Fix validation on credit cards
Credit cards had issues in validation
https://www.loom.com/share/38386a47ce44459e865bbf336269caa9

fix(payment): PAYPAL-202 fix validation

---

src/analytics/analytics-step-tracker.spec.ts
src/analytics/analytics-step-tracker.ts
src/analytics/analytics-tracker-window.ts

[DATA-6891](https://jira.bigcommerce.com/browse/DATA-6891)
This PR is trying to fix an issue with missing transactions and products in GA

fix(checkout): DATA-6891 missing transactions

---

src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-strategy.ts
src/payment/strategies/paypal-commerce/paypal-commerce-payment-processor.ts
src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.spec.ts
src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.ts
src/payment/strategies/paypal-commerce/paypal-commerce-sdk.ts
src/payment/strategies/paypal-commerce/paypal-commerce.mock.ts

Change credit to paylater
New implementation from PayPal
Manual, unit

feat(payment): PAYPAL-734 Change credit to paylater

---

src/payment/strategies/paypal-commerce/paypal-commerce-payment-initialize-options.ts
src/payment/strategies/paypal-commerce/paypal-commerce-payment-processor.spec.ts
src/payment/strategies/paypal-commerce/paypal-commerce-payment-processor.ts
src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.spec.ts
src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.ts
src/payment/strategies/paypal-commerce/paypal-commerce-sdk.ts

Add validate before using spb
Related task: https://github.com/bigcommerce/checkout-js/pull/427
We should validate form before submit
https://www.loom.com/share/94ffcc2a7bc04fb8942ad4732746fc4a

feat(payment): PAYPAL-706 Add validate before using spb

---

package-lock.json
package.json

Bump bigpay client
Released https://github.com/bigcommerce/bigpay-client-js/pull/109
Manual, unit

feat(payment): PAYPAL-702 Bump bigpay client

---

src/payment/payment-methods.mock.ts
src/payment/strategies/paypal-commerce/paypal-commerce-payment-initialize-options.ts
src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.spec.ts
src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.ts

Change style for sbp on checkout
The merchant should be able to change the styles in theme customization for spb on the checkout page
...

feat(payment): PAYPAL-746 Change style for sbp on checkout

---

src/config/config-selector.spec.ts
src/config/config.ts

It adds the property title 
The title is a property that we can change
https://drive.google.com/file/d/1ftq1CteeynosKSd1roKwBKE5_JGvtbHi/view?usp=sharing
https://github.com/bigcommerce/checkout-js/pull/429
https://github.com/bigcommerce/bigcommerce/pull/37501

feat(checkout): INT-3174 Added title as attribute of flashMessage

---

src/payment/payment-strategy-type.ts
src/payment/strategies/paypal-commerce/paypal-commerce-payment-initialize-options.ts

Add docs for initialize PPCP
Our documentation for PayPal commerce should be updated according to the most recent updates related to button initialization
...

feat(payment): PAYPAL-759 Add docs for initialize PPCP

---

src/checkout/checkout-service.spec.ts
src/checkout/checkout-service.ts
src/checkout/checkout-store-error-selector.spec.ts
src/checkout/checkout-store-error-selector.ts
src/checkout/checkout-store-status-selector.spec.ts
src/checkout/checkout-store-status-selector.ts
src/checkout/create-checkout-service.ts
src/customer/customer-account.ts
src/customer/customer-action-creator.spec.ts
src/customer/customer-action-creator.ts
src/customer/customer-actions.ts
src/customer/customer-reducer.spec.ts
src/customer/customer-reducer.ts
src/customer/customer-request-sender.spec.ts
src/customer/customer-request-sender.ts
src/customer/customer-selector.spec.ts
src/customer/customer-selector.ts
src/customer/customer-state.ts
src/customer/customers.mock.ts
src/customer/index.ts

Add Create Customer Account functionality.
So that customers can create an account during the checkout process.
unit

feat(customer): CHECKOUT-4941 Add Customer Creation functionality

---

package-lock.json
package.json

Upgrade BigPay client version.
https://github.com/bigcommerce/bigpay-client-js/blob/master/CHANGELOG.md
See https://github.com/bigcommerce/bigpay-client-js/pull/112

CHECKOUT-5324: Upgrade BigPay client version

---

src/payment/create-payment-strategy-registry.ts
src/payment/instrument/supported-payment-instruments.ts
src/payment/payment-methods.mock.ts
src/payment/payment-request-options.ts
src/payment/payment-strategy-type.ts
src/payment/strategies/mollie/index.ts
src/payment/strategies/mollie/mollie-initialize-options.ts
src/payment/strategies/mollie/mollie-payment-strategy.spec.ts
src/payment/strategies/mollie/mollie-payment-strategy.ts
src/payment/strategies/mollie/mollie-script-loader.ts
src/payment/strategies/mollie/mollie.mock.ts
src/payment/strategies/mollie/mollie.ts

Create strategy for Mollie payment method on checkout
In order to be able to purchase through Mollie
[Video](https://drive.google.com/file/d/1ZYGejKPOXk_jhI99w0pdcIA_vIFd7FwN/view?usp=sharing)
[JS](https://github.com/bigcommerce/checkout-js/pull/490)

feat(payments): INT-3610 added Mollie Checkout

---

src/common/error/errors/missing-data-error.ts
src/customer/customer-selector.ts
src/payment/create-payment-strategy-registry.spec.ts
src/payment/create-payment-strategy-registry.ts
src/payment/payment-request-options.ts
src/payment/payment-strategy-type.ts
src/payment/strategies/digitalriver/digitalriver-payment-initialize-options.ts
src/payment/strategies/digitalriver/digitalriver-payment-strategy.spec.ts
src/payment/strategies/digitalriver/digitalriver-payment-strategy.ts
src/payment/strategies/digitalriver/digitalriver-script-loader.spec.ts
src/payment/strategies/digitalriver/digitalriver-script-loader.ts
src/payment/strategies/digitalriver/digitalriver.mock.ts
src/payment/strategies/digitalriver/digitalriver.ts
src/payment/strategies/digitalriver/index.ts

Add Digital River strategy
A new payment strategy is required to support Digital River.
https://github.com/bigcommerce/checkout-js/pull/522

INT-3840 Create Digital River boilerplate

---

src/checkout-buttons/strategies/masterpass/masterpass-button-strategy.spec.ts
src/checkout-buttons/strategies/masterpass/masterpass-button-strategy.ts
src/customer/strategies/masterpass/masterpass-customer-strategy.spec.ts
src/customer/strategies/masterpass/masterpass-customer-strategy.ts
src/payment/strategies/masterpass/masterpass-payment-strategy.spec.ts
src/payment/strategies/masterpass/masterpass-payment-strategy.ts
src/payment/strategies/masterpass/masterpass-script-loader.ts

Added masterpass SRC experiment
Added Masterpass SRC experiment
1-  [Bigcommerce #40008](https://github.com/bigcommerce/bigcommerce/pull/40008)
2- [checkout-sdk-js #1094](https://github.com/bigcommerce/checkout-sdk-js/pull/1094)
3- [Checkout-js #540](https://github.com/bigcommerce/checkout-js/pull/540)

fix(payment): INT-3408 added masterpass SRC experiment

---

src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-strategy.ts
src/payment/strategies/paypal-commerce/paypal-commerce-sdk.ts

Pass BN code into the banners script
According to task PAYPAL-982
Tested on dev

feat(payment): PAYPAL-982 Pass BN code into the banners script

---

src/payment/strategies/paypal-commerce/paypal-commerce-payment-initialize-options.ts
src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.spec.ts

Improve the Checkout SDK documentation around PayPal Commerce
According to task PAYPAL-983
...

fix(payment): PAYPAL-983 Improve the Checkout SDK documentation around PayPal Commerce

---

src/payment/strategies/googlepay/googlepay-payment-strategy.spec.ts
src/payment/strategies/googlepay/googlepay-payment-strategy.ts

Reverts bigcommerce/checkout-sdk-js#1122
Reverts the fix which didn't seem to fix the issue in staging :(

Revert "fix(payment): INT-4266 Googlepay - fixing where nonce value is going …"

---

package-lock.json
package.json

Bump bigpay-client-js
To get https://github.com/bigcommerce/bigpay-client-js/pull/113 out
CircleCI

chore(payment): INT-4188 Bump bigpay-client-js

---

src/payment/create-payment-strategy-registry.spec.ts
src/payment/create-payment-strategy-registry.ts
src/payment/payment-methods.mock.ts
src/payment/payment-strategy-type.ts
src/payment/strategies/clearpay/clearpay-payment-strategy.spec.ts
src/payment/strategies/clearpay/clearpay-payment-strategy.ts
src/payment/strategies/clearpay/clearpay-script-loader.spec.ts
src/payment/strategies/clearpay/clearpay-script-loader.ts
src/payment/strategies/clearpay/clearpay-sdk.ts
src/payment/strategies/clearpay/clearpay-window.ts
src/payment/strategies/clearpay/clearpay.mock.ts
src/payment/strategies/clearpay/index.ts

Adding clearpay payment in the registry as external payment
enable the payment method from checkout page
https://drive.google.com/file/d/1PxBA4NdAhkWWVNQ3_bHal7-KmKoS10UG/view?usp=sharing
[https://github.com/bigcommerce/checkout-js/pull/565](https://github.com/bigcommerce/checkout-js/pull/565)

feat(payment): INT-4071 Clearpay - Create custom strategy

---

src/payment/strategies/paypal-commerce/paypal-commerce-funding-key-resolver.spec.ts
src/payment/strategies/paypal-commerce/paypal-commerce-funding-key-resolver.ts
src/payment/strategies/paypal-commerce/paypal-commerce-payment-initialize-options.ts
src/payment/strategies/paypal-commerce/paypal-commerce-payment-processor.spec.ts
src/payment/strategies/paypal-commerce/paypal-commerce-payment-processor.ts
src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.spec.ts
src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.ts
src/payment/strategies/paypal-commerce/paypal-commerce-sdk.ts
src/payment/strategies/paypal-commerce/paypal-commerce.mock.ts

Added Paypal APM fields on checkout
Due to https://jira.bigcommerce.com/browse/PAYPAL-976

feat(payment): PAYPAL-976 Order placement v2

---

src/payment/instrument/supported-payment-instruments.ts
src/payment/strategies/digitalriver/digitalriver-payment-strategy.spec.ts
src/payment/strategies/digitalriver/digitalriver-payment-strategy.ts

Added logic to support vaulted instruments
In order to show vaulted instruments on Digital River

feat(payment): INT-4310 Update DR strategy to support vaulted instruments

---

src/payment/payment-methods.mock.ts
src/payment/strategies/moneris/moneris-payment-strategy.spec.ts
src/payment/strategies/moneris/moneris-payment-strategy.ts
src/payment/strategies/moneris/moneris.ts

- Add labels to Moneris iframe creation process
-  Pass translated labels to Moneris iframe
- Labels must be translated
~~https://github.com/bigcommerce/bigcommerce/pull/41468~~
Unit Test

feat(payment): INT-4423 Set labels to Moneris iframe creation process

---

src/checkout-buttons/strategies/paypal/paypal-button-strategy.ts

Added size property for paypalexpress button
According to task https://jira.bigcommerce.com/browse/PAYPAL-1090
Tested  on int and dev

feat(payment): PAYPAL-1090 added size property for paypalexpress button

---

src/payment/strategies/zip/zip-payment-strategy.spec.ts
src/payment/strategies/zip/zip-payment-strategy.ts

Refactor in the zip-payment-strategy to get the `redirect_url` from the `initializeData` instead of the `additional_action_required.data ` response.
ticket[INT-4585](https://jira.bigcommerce.com/browse/INT-4585)
[Video](https://drive.google.com/file/d/1wvP2GrLgHZXhDRT7FnYqa8uZpfecXr77/view?usp=sharing)
[bigpay: INT-4585](https://github.com/bigcommerce/bigpay/pull/4091)
[Bigcommerce INT-4585](https://github.com/bigcommerce/bigcommerce/pull/42037)

feat(payment): INT-4585 - Refactor Zip uri data for redirect

---

src/payment/strategies/square/square-form.ts
src/payment/strategies/square/square-payment-strategy.spec.ts
src/payment/strategies/square/square-payment-strategy.ts
src/payment/strategies/square/square-script-loader.spec.ts
src/payment/strategies/square/square-script-loader.ts

Added VerifyBuyer from SquareV2 Script Client to SquareV2 Payment Strategy
In Order for SquareV2 to Support 3DS 
https://github.com/bigcommerce/bigcommerce/pull/42035

feat(payment): INT-4592 Added 3DS handler to SquareV2

---

src/payment/strategies/klarnav2/klarna-supported-countries.ts

https://jira.bigcommerce.com/browse/INT-4456
https://jira.bigcommerce.com/browse/INT-4712
Add FR/CA to klarna
To support them
...
https://github.com/bigcommerce/bigpay/pull/4067
https://github.com/bigcommerce/bigcommerce/pull/41800

feat(payment): INT-4456 Add CA/FR to klarna countries list

---

src/payment/strategies/afterpay/afterpay-payment-strategy.spec.ts
src/payment/strategies/afterpay/afterpay-payment-strategy.ts

Display the correct error message when trying to purchase with Afterpay and the amount is outside the limits provided by Afterpay (due to a Coupon code)
When trying to purchase with Afterpay and the amount is outside the limits provided by Afterpay (due to a Coupon code), the initialize on BIGPAY will return an error response, which is going to be interpreted by BCAPP and then the payment strategy will show a more readable message to the shopper.
BCAPP
[#42340](https://github.com/bigcommerce/bigcommerce/pull/42340)
https://drive.google.com/file/d/1kVV0eBRbDoQL9Ak66ciLrZdTonppKnd2/view?usp=sharing

fix(payment): INT-4594 [Afterpay] display correct error message when amount is out of limits

---

src/payment/strategies/googlepay/googlepay-payment-processor.ts

Fixed googlepay updates billing info by removing unnecessary customer email update
https://jira.bigcommerce.com/browse/ADYEN-260

fix(checkout): ADYEN-260 fixed googlepay updates billing info by removing customer email update

---

src/customer/create-customer-strategy-registry.ts
src/customer/strategies/braintree/braintree-visacheckout-customer-strategy.spec.ts
src/customer/strategies/braintree/braintree-visacheckout-customer-strategy.ts

Using postForm to checkout.php to get the customer mail and shipping data. I choose to do it this way because it's the same thing google pay strategy does to get the data
Customers have reported that when using Visa Checkout they are routed back to the checkout with the billing address completed but cannot make progress until refreshing the page.
After Visa Checkout before:
After Visa Checkout now: 

fix(payment): INT-4698 VISA Checkout load payment information

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Add issue templates
ping @bigcommerce/checkout

chore(common): CHECKOUT-0000 Add issue templates

---

src/payment/strategies/quadpay/quadpay-payment-strategy.spec.ts
src/payment/strategies/quadpay/quadpay-payment-strategy.ts

As requested on https://github.com/bigcommerce/checkout-sdk-js/pull/1267#discussion_r734126442
To keep both strategies similar
CircleCI
👉 https://github.com/bigcommerce/checkout-sdk-js/pull/1267
@bigcommerce/apex-integrations @bigcommerce/checkout @bigcommerce/payments

feat(payment): INT-4909 Quadpay: Homologate with Zip's strategy

---

src/payment/strategies/bolt/bolt-error.spec.ts
src/payment/strategies/bolt/bolt-error.ts
src/payment/strategies/bolt/bolt-payment-strategy.ts

Bolt 100 test

---

src/payment/strategies/googlepay/googlepay-adyenv2-payment-processor.ts
src/payment/strategies/googlepay/googlepay-payment-strategy.spec.ts
src/payment/strategies/googlepay/googlepay-payment-strategy.ts

Increase Code Coverage for googlepay-payment-strategy.ts
To increase code coverage

test(payment): INT-4926 increase code coverage for GooglePayStrategy

---

src/payment/strategies/paypal-commerce/paypal-commerce-payment-processor.spec.ts
src/payment/strategies/paypal-commerce/paypal-commerce-payment-processor.ts
src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.spec.ts
src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.ts
src/payment/strategies/paypal-commerce/paypal-commerce-sdk.ts
src/payment/strategies/paypal-commerce/paypal-commerce.mock.ts

Renamed paypal Fields to PaymentFields
According to task https://jira.bigcommerce.com/browse/PAYPAL-1208
...

feat(payment): PAYPAL-1208 renamed paypal Fields to PaymentFields

---

src/payment/strategies/googlepay/googlepay-payment-processor.spec.ts

Increase Code Coverage for googlepay-payment-processor.ts
To increase code coverage

test(payment): INT-4929 increase code coverage for GooglePayProcessor

---

src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.spec.ts
src/payment/strategies/paypal-commerce/paypal-commerce-sdk.ts

New style object for PayPal APMs
According to task https://jira.bigcommerce.com/browse/PAYPAL-1282
...

feat(payment): PAYPAL-1282 New style object for PayPal APMs

---

src/checkout-buttons/checkout-button-options.ts
src/checkout-buttons/create-checkout-button-registry.spec.ts
src/checkout-buttons/create-checkout-button-registry.ts
src/checkout-buttons/strategies/checkout-button-method-type.ts
src/checkout-buttons/strategies/googlepay/googlepay-button-strategy.ts
src/checkout-buttons/strategies/googlepay/googlepay-button.mock.ts
src/checkout-buttons/strategies/googlepay/googlepay-stripe-upe-button-strategy.spec.ts
src/customer/create-customer-strategy-registry.ts
src/customer/customer-request-options.ts
src/customer/strategies/googlepay/googlepay-customer-method-type.ts
src/customer/strategies/googlepay/googlepay-customer-mock.ts
src/customer/strategies/googlepay/googlepay-customer-strategy.ts
src/customer/strategies/googlepay/googlepay-stripe-upe-customer-strategy.spec.ts
src/payment/create-payment-strategy-registry.spec.ts
src/payment/create-payment-strategy-registry.ts
src/payment/payment-request-options.ts
src/payment/payment-strategy-type.ts
src/payment/strategies/googlepay/googlepay-payment-strategy.spec.ts
src/payment/strategies/googlepay/googlepay-payment-strategy.ts
src/payment/strategies/googlepay/googlepay-stripe-upe-initializer.spec.ts
src/payment/strategies/googlepay/googlepay-stripe-upe-initializer.ts
src/payment/strategies/googlepay/googlepay.mock.ts
src/payment/strategies/googlepay/index.ts

Created strategies for GooglePay with StripeUPE
To be able to pay using GooglePay via Stripe UPE

feat(payment): INT-5467 Stripe UPE GooglePay

---

src/checkout-buttons/strategies/braintree/braintree-paypal-button-strategy.spec.ts
src/checkout-buttons/strategies/braintree/braintree-paypal-button-strategy.ts
src/checkout-buttons/strategies/checkout-button-method-type.ts
src/payment/create-payment-strategy-registry.ts
src/payment/payment-methods.mock.ts
src/payment/payment-request-transformer.spec.ts
src/payment/payment-request-transformer.ts
src/payment/payment-strategy-type.ts
src/payment/strategies/braintree/braintree-script-loader.ts
src/payment/strategies/braintree/braintree-sdk-creator.ts
src/payment/strategies/braintree/braintree.mock.ts
src/payment/strategies/braintree/braintree.ts

Braintree venmo spb integration
According to task https://jira.bigcommerce.com/browse/PAYPAL-1151

feat(payment): PAYPAL-1151 braintree venmo spb integration

---

package-lock.json
package.json

Bump bigpay-client for this: https://github.com/bigcommerce/bigpay-client-js/pull/129
Browser info is required for stored cards
[proof](https://github.com/bigcommerce/bigpay-client-js/pull/129)

feat(payment): INT-4970 bump bigpay-client for Opayo stored cards

---

src/payment/create-payment-strategy-registry.ts
src/payment/instrument/supported-payment-instruments.ts
src/payment/payment-methods.mock.ts
src/payment/payment-request-options.ts
src/payment/payment-strategy-type.ts
src/payment/strategies/adyenv3/adyenv3-initialize-options.ts
src/payment/strategies/adyenv3/adyenv3-payment-strategy.spec.ts
src/payment/strategies/adyenv3/adyenv3-payment-strategy.ts
src/payment/strategies/adyenv3/adyenv3-script-loader.spec.ts
src/payment/strategies/adyenv3/adyenv3-script-loader.ts
src/payment/strategies/adyenv3/adyenv3.mock.ts
src/payment/strategies/adyenv3/adyenv3.ts
src/payment/strategies/adyenv3/index.ts

AdyenV3 module creation. This module mostly duplicates Adyen V2 integration, but has some improvements.
In future PRs we could possibly rewrite APMs integrations and make types cleaner.
It's better to review this PR comparing AdyenV3 strategy files to  AdyenV2. There are fewer changes.
Due to the Adyen new integration.
Units/tested manually

feat(checkout): ADYEN-378 AdyenV3 module creation 

---

src/checkout/checkout-service.ts
src/checkout/checkout-store-error-selector.ts
src/checkout/checkout-store-selector.ts
src/checkout/checkout-store-status-selector.ts
src/checkout/internal-checkout-selectors.ts
src/shipping/index.ts
src/shipping/pickup-option-reducer.ts

Fix issues discovered in testing pickup option implementation
While testing pickup options API figured out there are few implementation details that are missing. 
- Fix issue how key is created for encoding the option map
- Add getPickupOption to checkout selector that is used by checkout-js
- Tests
- Screenshot

fix(shipping): CHECKOUT-6003 Fix issues found in testing pickup options implementation

---

src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.ts
src/payment/strategies/stripe-upe/stripe-upe.ts

- Add support for Grabpay
- Merchant be able to support payments via Grabpay on StripeUPE

INT-5040 [StripeUPE] Add GrabPay

---

src/checkout-buttons/checkout-button-options.ts
src/checkout-buttons/create-checkout-button-registry.spec.ts
src/checkout-buttons/create-checkout-button-registry.ts
src/checkout-buttons/strategies/checkout-button-method-type.ts
src/checkout-buttons/strategies/googlepay/googlepay-adyenv3-button-strategy.spec.ts
src/checkout-buttons/strategies/googlepay/googlepay-button-strategy.ts
src/checkout-buttons/strategies/googlepay/googlepay-button.mock.ts
src/customer/create-customer-strategy-registry.ts
src/customer/customer-request-options.ts
src/customer/strategies/googlepay/googlepay-customer-method-type.ts
src/customer/strategies/googlepay/googlepay-customer-mock.ts
src/customer/strategies/googlepay/googlepay-customer-strategy.ts
src/payment/create-payment-strategy-registry.spec.ts
src/payment/create-payment-strategy-registry.ts
src/payment/payment-methods.mock.ts
src/payment/payment-request-options.ts
src/payment/payment-strategy-type.ts
src/payment/strategies/googlepay/googlepay-adyenv3-initializer.spec.ts
src/payment/strategies/googlepay/googlepay-adyenv3-initializer.ts
src/payment/strategies/googlepay/googlepay-adyenv3-payment-processor.spec.ts
src/payment/strategies/googlepay/googlepay-adyenv3-payment-processor.ts
src/payment/strategies/googlepay/googlepay-payment-strategy.ts
src/payment/strategies/googlepay/index.ts

AdyenV3 googlepay integration
Due to the https://jira.bigcommerce.com/browse/ADYEN-399
https://user-images.githubusercontent.com/79574476/158869219-46034ccb-9f97-4b79-b017-ace23d1fac1a.mov

feat(checkout): ADYEN-399 AdyenV3 googlepay

---

src/payment/strategies/adyenv2/adyenv2-initialize-options.ts
src/payment/strategies/adyenv2/adyenv2-payment-strategy.ts
src/payment/strategies/adyenv2/adyenv2.ts

AdyenV2 initialize interface fix
Due to the https://jira.bigcommerce.com/browse/ADYEN-454
Units

fix(checkout): ADYEN-454 AdyenV2 initialize interface fix

---

src/checkout/checkout-service.ts
src/payment/strategies/stripev3/stripev3-initialize-options.ts

Minor fixes to docblocks
Correctness - they're used to generate docs
CircleCI

docs(common): CHECKOUT-0 Minor fixes to docblocks

---

webpack-cdn.config.js
webpack.config.js

Reverts bigcommerce/checkout-sdk-js#1415

Revert "fix(common): CHECKOUT-6268 Check in array while loading config"

---

package-lock.json
package.json

Reverts bigcommerce/checkout-sdk-js#1413

Revert "chore(common): CHECKOUT-6268 Update to webpack 5"

---

package-lock.json
package.json
scripts/webpack/transform-manifest.js
webpack-cdn.config.js

Update webpack
Need to migrate to webpack 5 to get Nx supported
- Tests
- Circle 

feat(chore): CHECKOUT-6268 Update webpack

---

packages/core/src/payment/strategies/cba-mpgs/cba-mpgs-payment-strategy.spec.ts
packages/core/src/payment/strategies/cba-mpgs/cba-mpgs-payment-strategy.ts

Add a delay of 2 seconds between the retries of the `authenticatePayer` calls for CBA_MPGS
MPGS Documentation suggest waiting at around 10 seconds between the `initiateAuthentication` and `authenticatePayer`, this delay gives MPGS server enough time to run their processes and send a proper response for the authentication attempt.
Unit tests

fix(checkout): IINT-5126 [MPGS] Add delay between calls for 3ds

---

packages/core/src/order/index.ts
packages/core/src/order/order-request-body.ts
packages/core/src/payment/strategies/braintree/braintree-payment-processor.spec.ts
packages/core/src/payment/strategies/braintree/braintree-payment-processor.ts
packages/core/src/payment/strategies/braintree/is-credit-card-instrument-like.spec.ts
packages/core/src/payment/strategies/braintree/is-credit-card-instrument-like.ts

Added checking required fields
According to https://bigcommercecloud.atlassian.net/browse/PAYPAL-1368
In case we didn't pass the PP required fields

feat(payment): PAYPAL-1368 added checking required fields

---

.github/CODEOWNERS
packages/apple-pay/src/apple-pay-button-strategy.spec.ts
packages/apple-pay/src/apple-pay-button-strategy.ts
packages/apple-pay/src/create-apple-pay-payment-strategy.spec.ts
packages/apple-pay/src/create-apple-pay-payment-strategy.ts
packages/apple-pay/src/mocks/apple-pay-button.mock.ts
packages/payment-integration/src/button-options/checkout-button-initialize-options.ts
packages/payment-integration/src/button-options/checkout-button-method-type.ts
packages/payment-integration/src/button-options/index.ts
packages/payment-integration/src/index.ts
packages/payment-integration/src/strategy/checkout-button-initialize-options.ts/apple-pay-button-initialize-options.ts
packages/payment-integration/src/strategy/checkout-button-initialize-options.ts/index.ts
packages/payment-integration/src/strategy/checkout-button-strategy.ts
packages/payment-integration/src/strategy/index.ts

As above
Add checkout wallet button strategy.
- Circle

chore(common): CHECKOUT-6377 Move apple pay checkout button strategy

---

packages/core/src/payment/strategies/klarnav2/klarnav2-payment-strategy.ts

Dispatch the loadPaymentMethod action to get the current state and generate the Klarna Session Token correctly
Klarna strategy was affected when the session token is not generated and the session is not updated, so the transaction failed.
This issue was reported [INT-6276](https://bigcommercecloud.atlassian.net/browse/INT-6276)
Manual test on Integrations

feat(payment): INT-6276 Dispatch the thunk action to retrieve the payment method

---

.eslintrc.json
package-lock.json
package.json
packages/core/tslint.json
packages/payment-integration/tsconfig.json

Add `@bigcommerce/eslint-config` to the nx workspace
So we can have the same eslint rules applied to all checkout sdk js and tools

feat(checkout): CHECKOUT-6277 add eslint config to nx

---

packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-venmo-button-strategy.ts

Removed unnecessary method and class variable in PayPalCommerceVenmoButtonStrategy
Because it might be cleaner to avoid using global class variable and extra method for one use case. We should keep our code as clean as possible.
Unit tests
Manual tests

refactor(payment): PAYPAL-1567 removed unnecessary method and class variable in PayPalCommerceVenmoButtonStrategy

---

packages/core/extend-interface.config.json
packages/core/src/checkout-buttons/checkout-button-initializer.ts
packages/core/src/checkout-buttons/checkout-button-options-v2.ts
packages/core/src/checkout-buttons/index.ts
packages/core/src/checkout/checkout-service.ts
packages/core/src/customer/customer-request-options-v2.ts
packages/core/src/customer/index.ts
packages/core/src/payment/index.ts
packages/workspace-tools/src/generators/auto-export/generator.ts
packages/workspace-tools/src/generators/extend-interface/generator.ts

Apply various minor fixes to the workspace tools.
Otherwise, the initialisation options are not extracted and surfaced as expected.
Manual

CHECKOUT-6781: Apply various minor fixes to the workspace tools

---

packages/core/src/payment/strategies/mollie/mollie-initialize-options.ts
packages/core/src/payment/strategies/mollie/mollie-payment-strategy.spec.ts
packages/core/src/payment/strategies/mollie/mollie-payment-strategy.ts
packages/core/src/payment/strategies/mollie/mollie.mock.ts

Reverts bigcommerce/checkout-sdk-js#1510

Revert "fix(payment): INT-5854 [Mollie] Klarna is not available if cart contains digital products"

---

packages/core/src/payment/strategies/bluesnapv2/bluesnapv2-payment-strategy.spec.ts

Increase code coverage on BlueSnapV2PaymentStrategy
There’re a few missing lines on coverage to work with.
Before:
After:
Ping
@bigcommerce/apex-integrations  @bigcommerce/payments @bigcommerce/checkout

chore(payment): INT-6510 Increase code coverage on BlueSnapV2PaymentStrategy

---

packages/core/src/payment/strategies/worldpayaccess/worldpayaccess-payment-strategy.spec.ts
packages/core/src/payment/strategies/worldpayaccess/worldpayaccess-payment-strategy.ts

Adds flow to pay with hosted payment
the payment was failing when Feature_HostedPaymentForm was enabled
[Video](https://drive.google.com/file/d/1hv8EayUMZ80jKXQBJjnuz8n4tqL_yqRQ/view?usp=sharing)
[Coverage](https://drive.google.com/file/d/1KqhmRAV37w--hiCRf5LUbYbXK5PSuRMA/view?usp=sharing)
https://github.com/bigcommerce/checkout-js/pull/994

fix(payment): INT-6115 Payment with hosted credit card

---

packages/core/src/payment/strategies/stripev3/stripev3-payment-strategy.spec.ts
packages/core/src/payment/strategies/stripev3/stripev3-payment-strategy.ts

Added a catch in case an exception occurs when confirming the payment using 3DS2 and the client token is sent to try to confirm the payment in the backend.
Some cards with 3DS2 skip the 3ds verification https://site-admin.stripe.com/guides/strong-customer-authentication#exemptions-to-strong-customer-authentication  which is causing an error to occur on the frontend but the charges are being completed on Stripe's side.
https://user-images.githubusercontent.com/69487174/186690882-66cf367e-260c-4e02-87ba-72b7b43f439e.mov
https://github.com/bigcommerce/bigpay/pull/5853
ping @bigcommerce/payments @bigcommerce/apex-integrations @bigcommerce/kyiv-payments-team

fix(payment): STRIPE-106 Added a catch in case an exception occurs when confirming the payment using 3DS2

---

packages/core/src/payment/strategies/adyenv3/adyenv3-payment-strategy.ts
packages/core/src/payment/strategies/adyenv3/adyenv3-script-loader.spec.ts
packages/core/src/payment/strategies/adyenv3/adyenv3-script-loader.ts
packages/core/src/payment/strategies/adyenv3/adyenv3.ts
packages/core/src/payment/strategies/googlepay/googlepay-adyenv3-payment-processor.ts

Fixed ability to setup of the Adyenv3 3ds2 challenge window size by the updating adyen-web version
Due to the https://bigcommercecloud.atlassian.net/browse/ADYEN-545

fix(payment): ADYEN-545 bumped adyen-web version

---

packages/core/src/payment/strategies/worldpayaccess/worldpayaccess-payment-strategy.spec.ts
packages/core/src/payment/strategies/worldpayaccess/worldpayaccess-payment-strategy.ts

Test cases added to improve code coverage
Code coverage was fulfilling expectations for the strategy.
[Coverage](https://drive.google.com/file/d/1O0tF8jjPZ20upJIxyb-Y4uuYp-lH7gt-/view?usp=sharing)

INT-6554 Worldpay Access - Increase code coverage

---

packages/core/src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.spec.ts
packages/core/src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.ts

Added a catch in case an exception occurs when confirming the payment using 3DS2 and the client token is sent to try to confirm the payment in the backend.
Some cards with 3DS2 skip the 3ds verification https://site-admin.stripe.com/guides/strong-customer-authentication#exemptions-to-strong-customer-authentication  which is causing an error to occur on the frontend but the charges are being completed on Stripe's side.
- [Video](https://drive.google.com/file/d/1YrI4J_GK7c6Dpuzt6dk8egn5RPCJzaN7/view?usp=sharing)
https://github.com/bigcommerce/bigpay/pull/5899
ping @bigcommerce/payments @bigcommerce/apex-integrations @bigcommerce/kyiv-payments-team

fix(payment): STRIPE-131 Added a catch in case an exception occurs when confirming the payment using 3DS2

---

packages/core/src/payment/payment-strategy-action-creator.ts

Add gateway, type to object to resolve registry methods in realtime
- As of now we have an issue where strategies can only be resolved using method id, add gateway and type to the query as well
- circle

fix(payment): CHECKOUT-000 Update get params to get registeries

---

packages/core/src/checkout-buttons/checkout-button-options.ts
packages/core/src/checkout-buttons/create-checkout-button-registry.spec.ts
packages/core/src/checkout-buttons/create-checkout-button-registry.ts
packages/core/src/checkout-buttons/strategies/checkout-button-method-type.ts
packages/core/src/checkout-buttons/strategies/googlepay/googlepay-bnz-button-strategy.spec.ts
packages/core/src/checkout-buttons/strategies/googlepay/googlepay-button-strategy.ts
packages/core/src/checkout-buttons/strategies/googlepay/googlepay-button.mock.ts
packages/core/src/customer/create-customer-strategy-registry.ts
packages/core/src/customer/customer-request-options.ts
packages/core/src/customer/strategies/googlepay/googlepay-bnz-customer-strategy.spec.ts
packages/core/src/customer/strategies/googlepay/googlepay-customer-method-type.ts
packages/core/src/customer/strategies/googlepay/googlepay-customer-mock.ts
packages/core/src/customer/strategies/googlepay/googlepay-customer-strategy.ts
packages/core/src/payment/create-payment-strategy-registry.spec.ts
packages/core/src/payment/create-payment-strategy-registry.ts
packages/core/src/payment/payment-request-options.ts
packages/core/src/payment/payment-strategy-type.ts
packages/core/src/payment/strategies/googlepay/googlepay-bnz-initializer.spec.ts
packages/core/src/payment/strategies/googlepay/googlepay-bnz-initializer.ts
packages/core/src/payment/strategies/googlepay/googlepay-payment-strategy.spec.ts
packages/core/src/payment/strategies/googlepay/googlepay-payment-strategy.ts
packages/core/src/payment/strategies/googlepay/googlepay.mock.ts
packages/core/src/payment/strategies/googlepay/index.ts

Googlepay implementation for Bank of New Zealand
So that customers can pay with their google pay wallets
...

feat(payment): INT-6297 BNZ GooglePay

---

packages/core/src/checkout-buttons/create-checkout-button-registry.ts
packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-alternative-methods-button-strategy.spec.ts
packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-options.ts
packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-strategy.spec.ts
packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-strategy.ts
packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-credit-button-strategy.spec.ts
packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-venmo-button-strategy.spec.ts
packages/core/src/payment/strategies/paypal-commerce/paypal-commerce-sdk.ts

Added Shipping options for paypal and updated paypal callbacks
According to task https://bigcommercecloud.atlassian.net/browse/PAYPAL-1606

feat(payment): PAYPAL-1606 Added Shipping options for paypal and updated paypal callbacks

---

packages/core/src/checkout-buttons/create-checkout-button-registry.ts
packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-alternative-methods-button-strategy.ts
packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-credit-button-options.ts
packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-credit-button-strategy.spec.ts
packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-credit-button-strategy.ts
packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-venmo-button-strategy.ts
packages/core/src/payment/strategies/paypal-commerce/paypal-commerce-payment-processor.ts
packages/core/src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.ts
packages/core/src/payment/strategies/paypal-commerce/paypal-commerce-sdk.ts

Added shipping Options for paypal credit and updated paypal callbacks
According to task https://bigcommercecloud.atlassian.net/browse/PAYPAL-1607

feat(payment): PAYPAL-1607 added shipping Options for paypal credit and updated paypal callbacks

---

packages/core/src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.ts
packages/core/src/payment/strategies/stripev3/stripev3-payment-strategy.ts

Needs to add a flag to do a validation
Needs to add a flag to validate if the error show it is correct

feat(payment): STRIPE-99 Add flag to validate unmount

---

packages/core/src/checkout-buttons/create-checkout-button-registry.ts
packages/core/src/checkout-buttons/strategies/braintree/braintree-paypal-button-options.ts
packages/core/src/checkout-buttons/strategies/braintree/braintree-paypal-button-strategy.spec.ts
packages/core/src/checkout-buttons/strategies/braintree/braintree-paypal-button-strategy.ts

Quick payment button for BraintreePaypal provider
According to task [PAYPAL-1630](https://bigcommercecloud.atlassian.net/browse/PAYPAL-1630)
https://user-images.githubusercontent.com/99336044/194883965-de1cca2d-9d31-4515-8445-cfabaf18f82d.mov

feat(payment): PAYPAL-1630 BraintreePayPal on PDP

---

packages/core/src/checkout-buttons/create-checkout-button-registry.ts
packages/core/src/checkout-buttons/strategies/braintree/braintree-venmo-button-options.ts
packages/core/src/checkout-buttons/strategies/braintree/braintree-venmo-button-strategy.spec.ts
packages/core/src/checkout-buttons/strategies/braintree/braintree-venmo-button-strategy.ts

Quick payment button for BraintreeVenmo provider
According to task [PAYPAL-1629](https://bigcommercecloud.atlassian.net/browse/PAYPAL-1629)
https://user-images.githubusercontent.com/99336044/196911630-4b2a53ec-eea3-4f09-8360-dd321ce773b9.mov

feat(payment): PAYPAL-1629 BraintreeVenmo on PDP

---

packages/core/src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.spec.ts
packages/core/src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.ts

Change in the flow which would allow us, through successful notifications, to complete the order on our side in case something fails on the front and it is completed on the stripe side.
Broadly speaking, the flow would be:
1. The payment intent is created. 
2. We create the order and update the payment intent with the order id.
3. Stripe replies that the payment method is required. 
4. We throw an exception on the back side “`additional_action_requires_payment_method`” to be caught on the front.
5. Continue with the current flow.
6. If the `confirmPayment` fails on the front side and notifications are configured, the order will be completed when the successful notification arrives from stripe.
Some completed payments on the Stripe side no matching order exists in BigCommerce (incomplete …

fix(payment): STRIPE-160 Fixed no order created for successful Stripe payment

---

packages/core/src/payment/strategies/stripe-upe/stripe-upe-initialize-options.ts
packages/core/src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.ts
packages/core/src/payment/strategies/stripe-upe/stripe-upe.mock.ts
packages/core/src/payment/strategies/stripe-upe/stripe-upe.ts

Reverts bigcommerce/checkout-sdk-js#1662

Revert "feat(payment): STRIPE-178 Render Submit button after Stripe elements are loaded"

---

package-lock.json
package.json

Bump @bigcommerce/bigpay-client
See the [changelog](https://github.com/bigcommerce/bigpay-client-js/compare/v5.20.0...v5.20.2)
Keeping up to date
CI

chore(common): BIG-0 Bump @bigcommerce/bigpay-client

---

package-lock.json
package.json

Bump @bigcommerce/bigpay-client from v5.20.2 to v5.20.3
See the [changelog](https://github.com/bigcommerce/bigpay-client-js/compare/v5.20.2...v5.20.3)
Keeping up to date
CI

chore(common): BIG-0 Bump @bigcommerce/bigpay-client from v5.20.2 to v5.20.3

---

packages/core/src/checkout-buttons/create-checkout-button-registry.ts
packages/core/src/checkout-buttons/strategies/googlepay/googlepay-adyenv2-button-strategy.spec.ts
packages/core/src/checkout-buttons/strategies/googlepay/googlepay-adyenv3-button-strategy.spec.ts
packages/core/src/checkout-buttons/strategies/googlepay/googlepay-authorizenet-button-strategy.spec.ts
packages/core/src/checkout-buttons/strategies/googlepay/googlepay-bnz-button-strategy.spec.ts
packages/core/src/checkout-buttons/strategies/googlepay/googlepay-braintree-button-strategy.spec.ts
packages/core/src/checkout-buttons/strategies/googlepay/googlepay-button-options.ts
packages/core/src/checkout-buttons/strategies/googlepay/googlepay-button-strategy.ts
packages/core/src/checkout-buttons/strategies/googlepay/googlepay-button.mock.ts
packages/core/src/checkout-buttons/strategies/googlepay/googlepay-checkoutcom-button-strategy.spec.ts
packages/core/src/checkout-buttons/strategies/googlepay/googlepay-cybersourcev2-button-strategy.spec.ts
packages/core/src/checkout-buttons/strategies/googlepay/googlepay-orbital-button-strategy.spec.ts
packages/core/src/checkout-buttons/strategies/googlepay/googlepay-stripe-button-strategy.spec.ts
packages/core/src/checkout-buttons/strategies/googlepay/googlepay-stripe-upe-button-strategy.spec.ts
packages/core/src/payment/strategies/googlepay/googlepay-braintree-initializer.spec.ts
packages/core/src/payment/strategies/googlepay/googlepay-braintree-initializer.ts
packages/core/src/payment/strategies/googlepay/googlepay-payment-processor.spec.ts
packages/core/src/payment/strategies/googlepay/googlepay-payment-processor.ts
packages/core/src/payment/strategies/googlepay/googlepay.ts

feat(payment): PAYPAL-1633 added Buy Now feature for googlepaybraintree 

---

.github/CODEOWNERS

Updated kyiv-payments-team's packages names 
kyiv-payments-team prs requires checkout team review even if they have their updates in own packages only

fix(payment): PAYPAL-000 updated kyiv-payments-team codeowners data

---

packages/paypal-commerce-integration/src/index.ts
packages/paypal-commerce-integration/src/paypal-commerce-inline/create-paypal-commerce-inline-button-strategy.spec.ts
packages/paypal-commerce-integration/src/paypal-commerce-inline/create-paypal-commerce-inline-button-strategy.ts
packages/paypal-commerce-integration/src/paypal-commerce-inline/paypal-commerce-inline-button-initialize-options.ts
packages/paypal-commerce-integration/src/paypal-commerce-inline/paypal-commerce-inline-button-strategy.spec.ts
packages/paypal-commerce-integration/src/paypal-commerce-inline/paypal-commerce-inline-button-strategy.ts
packages/paypal-commerce-integration/src/paypal-commerce-types.ts
packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-customer-strategy.ts

Added PayPalCommerceInlineButton strategy to paypal-commerce integration package
To reduce amount of PayPal Commerce code in core js
Unit tests
Manual tests

feat(payment): PAYPAL-1890 added PayPalCommerceInlineButton strategy to paypal-commerce integration package

---

packages/core/src/checkout-buttons/strategies/amazon-pay-v2/amazon-pay-v2-button.mock.ts
packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-processor.spec.ts

Updated amazon pay specs with CartSource
To fix the issue with failed build in release process
Unit tests
CI build

fix(payment): PAYPAL-000 updated amazon pay specs with CartSource

---

packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-credit-button-strategy.spec.ts
packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-venmo-button-strategy.spec.ts

Updated paypal commerce tests to fix some issues with CI build in other pr
To fix build issues that we have in paypal commerce code migration prs:
https://github.com/bigcommerce/checkout-sdk-js/pull/1815
https://github.com/bigcommerce/checkout-sdk-js/pull/1813
Unit tests

fix(payment): PAYPAL-000 updated paypal commerce tests to fix some issues with CI build in other prs

---

packages/paypal-commerce-integration/src/index.ts
packages/paypal-commerce-integration/src/paypal-commerce-types.ts
packages/paypal-commerce-integration/src/paypal-commerce/create-paypal-commerce-button-strategy.spec.ts
packages/paypal-commerce-integration/src/paypal-commerce/create-paypal-commerce-button-strategy.ts
packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-button-initialize-options.ts
packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-button-strategy.spec.ts
packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-button-strategy.ts
packages/paypal-commerce-integration/src/utils/get-valid-button-style.spec.ts
packages/paypal-commerce-integration/src/utils/get-valid-button-style.ts
packages/paypal-commerce-integration/src/utils/index.ts

Added PayPalCommerceButtonStrategy to paypal-commerce-integration package
As part of PayPalCommerce code migration process
Unit tests
Manual tests

feat(payment): PAYPAL-1888 added PayPalCommerceButtonStrategy to paypal-commerce-integration package

---

packages/paypal-commerce-integration/src/index.ts
packages/paypal-commerce-integration/src/mocks/get-billing-address-from-order-details.mock.ts
packages/paypal-commerce-integration/src/mocks/get-paypal-commerce-order-details.mock.ts
packages/paypal-commerce-integration/src/mocks/get-shipping-address-from-order-details.mock.ts
packages/paypal-commerce-integration/src/paypal-commerce-common.spec.ts
packages/paypal-commerce-integration/src/paypal-commerce-common.ts
packages/paypal-commerce-integration/src/paypal-commerce-types.ts
packages/paypal-commerce-integration/src/paypal-commerce/create-paypal-commerce-button-strategy.ts
packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-button-initialize-options.ts
packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-button-strategy.spec.ts
packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-button-strategy.ts

Added PayPalCommerceCommon class with utils methods inside for paypal-commerce-integration package
To reduce amount of code duplication in different PayPal Commerce Strategies in paypal-commerce-integration package
Unit tests
Manual tests

feat(payment): PAYPAL-1919 added PayPalCommerceCommon class

---

packages/core/src/payment/strategies/klarnav2/klarnav2-payment-strategy.spec.ts
packages/core/src/payment/strategies/klarnav2/klarnav2.mock.ts

Increase code coverage for klarnav2-payment-strategy
Because there’re certain uses cases that must be covered.
[Code coverage report for core_src_payment_strategies_klarnav2_klarnav2-payment-strategy.ts.pdf](https://github.com/bigcommerce/checkout-sdk-js/files/10701121/Code.coverage.report.for.core_src_payment_strategies_klarnav2_klarnav2-payment-strategy.ts.pdf)
[INT-6312]: https://bigcommercecloud.atlassian.net/browse/INT-6312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(payment): INT-6312 klarnav2 increase code coverage

---

packages/payment-integration-api/src/hosted-form/hosted-form-options.ts
packages/payment-integration-api/src/hosted-form/iframe-content.ts
packages/payment-integration-api/src/hosted-form/index.ts
packages/payment-integration-api/src/index.ts

Added HostedForm exports to payment-integration-api index file
To be able to use Hosted form interfaces in other packages
Unit tests

feat(payment): PAYPAL-000 added HostedForm exports to payment-integration-api index file

---

packages/payment-integration-api/src/common/utility/index.ts
packages/payment-integration-api/src/common/utility/object-with-kebab-case-keys.spec.ts
packages/payment-integration-api/src/common/utility/object-with-kebab-case-keys.ts
packages/payment-integration-api/src/index.ts

Added objectWithKebabKeys utility function to payment-integration-api package
To make an ability to convert any object keys to kebab style if needed in other packages
Unit tests

feat(payment): PAYPAL-000 added objectWithKebabKeys utility function to payment-integration-api package

---

packages/adyen-integration/src/adyenv2/adyenv2-payment-strategy.spec.ts
packages/adyen-integration/src/adyenv2/adyenv2-payment-strategy.ts
packages/adyen-integration/src/adyenv2/adyenv2.ts
packages/adyen-integration/src/adyenv3/adyenv3-payment-strategy.spec.ts
packages/adyen-integration/src/adyenv3/adyenv3-payment-strategy.ts

Fixed iDeal validation issue for adyenv2/v3
Due to the absence of UI validation for iDeal provider
Units/manually

fix(payment): ADYEN-733 fix ideal validation issue for adyenv2/v3

---

packages/bolt-integration/src/bolt-button-initialize-options.ts
packages/bolt-integration/src/bolt-button-strategy.spec.ts
packages/bolt-integration/src/bolt-button-strategy.ts
packages/bolt-integration/src/bolt-script-loader.ts
packages/bolt-integration/src/bolt.ts
packages/bolt-integration/src/create-bolt-button-strategy.spec.ts
packages/bolt-integration/src/create-bolt-button-strategy.ts
packages/bolt-integration/src/index.ts

Create Bolt button strategy
New strategy for Bolt smart payment button on product details page
unit test and manual testing
https://user-images.githubusercontent.com/9430298/226911392-27efc1f9-aa9e-4559-8834-9fe73acefc23.mov

feat(payment): BOLT-483 Create Bolt button strategy

---

packages/paypal-commerce-integration/src/mocks/get-paypal-commerce-integration-service-mock.mock.ts
packages/paypal-commerce-integration/src/mocks/get-paypal-commerce-payment-method.mock.ts
packages/paypal-commerce-integration/src/mocks/get-paypal-sdk.mock.ts
packages/paypal-commerce-integration/src/mocks/index.ts
packages/paypal-commerce-integration/src/paypal-commerce-alternative-methods/paypal-commerce-alternative-methods-button-strategy.spec.ts
packages/paypal-commerce-integration/src/paypal-commerce-credit-card/paypal-commerce-credit-cards-strategy.spec.ts
packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-button-strategy.spec.ts
packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-customer-strategy.spec.ts
packages/paypal-commerce-integration/src/paypal-commerce-integration-service.spec.ts
packages/paypal-commerce-integration/src/paypal-commerce-script-loader.spec.ts
packages/paypal-commerce-integration/src/paypal-commerce-venmo/paypal-commerce-venmo-button-strategy.spec.ts
packages/paypal-commerce-integration/src/paypal-commerce-venmo/paypal-commerce-venmo-customer-strategy.spec.ts
packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-button-strategy.spec.ts
packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-customer-strategy.spec.ts

Added paypal commerce integration service mock to simplify test files
To keep paypal commerce integration package code as clean as possible
Unit tests

refactor(payment): PAYPAL-000 added paypal commerce integration service mock to simplify test files

---

packages/payment-integration-api/src/errors/index.ts
packages/payment-integration-api/src/errors/timeout-error.spec.ts
packages/payment-integration-api/src/errors/timeout-error.ts
packages/payment-integration-api/src/index.ts

Added timeout error to payment-integration-api package
To make an ability to use this error in different integration packages
CI tests

refactor(payment): PAYPAL-000 added timeout error to payment-integration-api package

---

packages/adyen-integration/src/adyenv2/adyenv2-script-loader.ts
packages/adyen-integration/src/adyenv3/adyenv3-script-loader.ts
packages/adyen-integration/src/adyenv3/adyenv3.ts
packages/core/src/payment/strategies/adyenv3/adyenv3-script-loader.ts
packages/core/src/payment/strategies/adyenv3/adyenv3.ts

Update of the AdyenV3 intialization due to the adyen documentation
[adyen documentation](https://docs.adyen.com/online-payments/web-drop-in#initialize-the-payment-session)
Units/manualy

feat(checkout): ADYEN-775 update of intialization interface for Adyenv3

---

docs/interfaces/PaypalCommercePaymentInitializeOptions.md

Updated PayPalCommercePaymentInitializeOptions.md file due to last changes
To avoid recursively generated files due to the conflict between core and paypal-commerce-integration packages
CI tests

refactor(payment): PAYPAL-000 updated PayPalCommercePaymentInitializeOptions.md file due to last changes

---

packages/bluesnap-direct-integration/src/bluesnap-direct-credit-card-payment-strategy.spec.ts
packages/bluesnap-direct-integration/src/bluesnap-direct-credit-card-payment-strategy.ts
packages/bluesnap-direct-integration/src/bluesnap-direct-hosted-form.spec.ts
packages/bluesnap-direct-integration/src/bluesnap-direct-hosted-form.ts
packages/bluesnap-direct-integration/src/bluesnap-direct-hosted-input-validator.ts
packages/bluesnap-direct-integration/src/is-bluesnap-direct-input-validation-error-description.ts
packages/bluesnap-direct-integration/src/mocks/bluesnap-direct-sdk.mock.ts
packages/bluesnap-direct-integration/src/types.ts
packages/payment-integrations-test-utils/src/test-utils/payment-integration-service.mock.ts

Implement [3DS in Hosted Payment Fields](https://developers.bluesnap.com/reference/3-d-secure-for-api#section-3-d-secure-in-hosted-payment-fields).
To reduce eCommerce fraud by verifying a cardholder’s identity in real-time.
https://user-images.githubusercontent.com/4843328/228607180-e3e5dc47-1926-490d-9871-dc90e151350b.mp4
---
👉 https://github.com/bigcommerce/bigcommerce/pull/51912
[INT-7557]: https://bigcommercecloud.atlassian.net/browse/INT-7557?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(payment): INT-7557 BlueSnapDirect: Implement 3DS 2

---

packages/bolt-integration/src/bolt-button-initialize-options.ts
packages/bolt-integration/src/bolt-button-strategy.spec.ts
packages/bolt-integration/src/bolt-button-strategy.ts
packages/bolt-integration/src/bolt.ts

feat(payment): BOLT-484 Add styling for Bolt Button on PDP [QA only]

---

packages/core/src/payment/instrument/index.ts
packages/core/src/payment/instrument/instrument.ts
packages/core/src/payment/instrument/supported-payment-instruments.ts
packages/payment-integration-api/src/payment/payment.ts

Added a new instrument for a new payment method
For the new Braintree ACH payment method

fix(payment): PAYPAL-2451 Braintree ACH instrument

---

.github/CODEOWNERS
packages/bluesnap-direct-integration/src/bluesnap-direct-constants.ts
packages/bluesnap-direct-integration/src/bluesnap-direct-credit-card-payment-strategy.spec.ts
packages/bluesnap-direct-integration/src/bluesnap-direct-credit-card-payment-strategy.ts
packages/bluesnap-direct-integration/src/bluesnap-direct-hosted-form.spec.ts
packages/bluesnap-direct-integration/src/bluesnap-direct-hosted-form.ts
packages/bluesnap-direct-integration/src/bluesnap-direct-hosted-input-validator.ts
packages/bluesnap-direct-integration/src/bluesnap-direct-name-on-card-input.spec.ts
packages/bluesnap-direct-integration/src/bluesnap-direct-name-on-card-input.ts
packages/bluesnap-direct-integration/src/is-hosted-stored-card-field-options-map.ts
packages/bluesnap-direct-integration/src/types.ts
packages/core/src/payment/instrument/supported-payment-instruments.ts

Bluesnap direct credit card vaulting
We have a request to develop such functionality
units/manually

feat(checkout): PI-42 bluesnap direct credit card vaulting

---

packages/core/src/payment/strategies/checkoutcom-custom/checkoutcom-custom-payment-strategy.spec.ts

Add missing test cases for the CheckoutCom custom strategy.
To increase code coverage.

test(payment): INT-7743 CheckoutCom: Add missing test cases

---

packages/braintree-integration/src/braintree-paypal-ach/braintree-paypal-ach-payment-strategy.spec.ts
packages/braintree-integration/src/braintree-paypal-ach/braintree-paypal-ach-payment-strategy.ts

Updated payment payload for ACH
To place an order correctly

fix(payment): PAYPAL-2618 Updated payment payload for ACH

---

packages/adyen-integration/src/adyenv3/adyenv3-payment-strategy.ts

adyen v3 stored card pay fix
Problem with stored cards appers after the klarna pay widget release
Manually

fix(checkout): PI-294 adyen v3 stored card pay fix, after adding klarna pay widget

---

packages/braintree-integration/src/braintree-script-loader.spec.ts
packages/braintree-integration/src/braintree-script-loader.ts

Bump Braintree sdk version.
All tests have been passed.

feat(payment): PAYPAL-2502 bump Braintree sdk version

---

packages/core/src/checkout/checkout-service.spec.ts
packages/core/src/checkout/checkout-service.ts
packages/core/src/checkout/checkout-store-error-selector.spec.ts
packages/core/src/checkout/checkout-store-error-selector.ts
packages/core/src/checkout/checkout-store-selector.spec.ts
packages/core/src/checkout/checkout-store-selector.ts
packages/core/src/checkout/checkout-store-state.ts
packages/core/src/checkout/checkouts.mock.ts
packages/core/src/checkout/create-checkout-service.ts
packages/core/src/checkout/create-checkout-store-reducer.ts
packages/core/src/checkout/create-internal-checkout-selectors.ts
packages/core/src/checkout/internal-checkout-selectors.ts
packages/core/src/extension/extension-action-creator.spec.ts
packages/core/src/extension/extension-action-creator.ts
packages/core/src/extension/extension-actions.ts
packages/core/src/extension/extension-reducer.ts
packages/core/src/extension/extension-reduer.spec.ts
packages/core/src/extension/extension-request-sender.spec.ts
packages/core/src/extension/extension-request-sender.ts
packages/core/src/extension/extension-selector.spec.ts
packages/core/src/extension/extension-selector.ts
packages/core/src/extension/extension-state.ts
packages/core/src/extension/extension.mock.ts
packages/core/src/extension/extension.ts
packages/core/src/extension/index.ts

- Retrieve all extension configurations on a store.
- Integrate them seamlessly into the existing checkout state.
Efficiently manage and utilize extensions.
- CI checks.
- Manual testing.

feat(checkout): CHECKOUT-7536 Load extensions

---

.github/PULL_REQUEST_TEMPLATE.md

Update github team name as suggested [here](https://bc-eng-docs.herokuapp.com/process/policies/pods-and-teams.html#communicating-with-teams) 
To improve discoverability
N/A
Ping @bigcommerce/checkout @bigcommerce/payments

chore(payment): Update github team name

---

packages/core/src/checkout/checkout.ts
packages/core/src/checkout/checkouts.mock.ts
packages/core/src/fee/fee.ts
packages/core/src/fee/index.ts
packages/core/src/payment/strategies/googlepay/googlepay.mock.ts

Introduce fees field for checkout 
Able to show the fees on the summary detail
CI checks.

feat(checkout): CHECKOUT-7534 Add fees field

---

.github/CODEOWNERS
packages/bluesnap-direct-integration/src/bluesnap-direct-apm-payment-strategy.spec.ts
packages/bluesnap-direct-integration/src/bluesnap-direct-apm-payment-strategy.ts
packages/bluesnap-direct-integration/src/bluesnap-direct-iframe-creator.spec.ts
packages/bluesnap-direct-integration/src/bluesnap-direct-iframe-creator.ts
packages/bluesnap-direct-integration/src/create-bluesnap-direct-apm-payment-strategy.ts
packages/bluesnap-direct-integration/src/index.ts
packages/bluesnap-direct-integration/src/is-bluesnap-direct-provider-data.ts
packages/bluesnap-direct-integration/src/types.ts

Bluesnapdirect APMs implementation
Due to the feature request
Units/manual
https://github.com/bigcommerce/checkout-sdk-js/assets/79574476/caf99ea3-12e7-45c1-a304-806ae43d279c

feat(checkout): PI-168 bluesnapdirect APMs

---

packages/bluesnap-direct-integration/src/bluesnap-direct-apm-payment-strategy.ts

Fix of the unnecessary browser alert before redirect
Before redirect browser alert appears, because there was pending promise in background I believe
Before fix:
After fix:
Redirect works without browser alert
@bigcommerce/team-payments

fix(checkout): PI-00 fix pending promise for bluesnapdirect APMs iframe

---

packages/braintree-integration/src/braintree-script-loader.spec.ts
packages/braintree-integration/src/braintree-script-loader.ts
packages/core/src/payment/strategies/braintree/braintree-credit-card-payment-strategy.spec.ts
packages/core/src/payment/strategies/braintree/braintree-credit-card-payment-strategy.ts
packages/core/src/payment/strategies/braintree/braintree-hosted-form.ts
packages/core/src/payment/strategies/braintree/braintree-payment-processor.spec.ts
packages/core/src/payment/strategies/braintree/braintree-payment-processor.ts
packages/core/src/payment/strategies/braintree/braintree-script-loader.spec.ts
packages/core/src/payment/strategies/braintree/braintree-script-loader.ts
packages/core/src/payment/strategies/braintree/braintree.mock.ts
packages/core/src/payment/strategies/braintree/braintree.ts

Bump Braintree SDK version
To use latest version of Braintree SDK

fix(payment): PAYPAL-2502 bump braintree sdk version

---

.github/CODEOWNERS
packages/fortis-integration/.eslintrc.json
packages/fortis-integration/README.md
packages/fortis-integration/jest.config.js
packages/fortis-integration/project.json
packages/fortis-integration/tsconfig.json
packages/fortis-integration/tsconfig.spec.json
tsconfig.base.json
workspace.json

New Fortis package
Create new package for future Fortis integration
unit tests

feat(payment): PI-502 Fortis package

---

packages/core/src/checkout-buttons/strategies/amazon-pay-v2/amazon-pay-v2-button-strategy.ts
packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-processor.spec.ts
packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-processor.ts

fix(payment): PAYPAL-2719 fix amazon pay button

---

packages/payment-integrations-test-utils/src/test-utils/payment-integration-service.mock.ts

Extended payment integration service state mock with extra methods
To have an ability to mock and spy on those methods that possibly can be used in integration package strategies
Unit tests
CI tests

test(payment): PAYPAL-000 extended payment integration service state mock with extra methods

---

packages/braintree-integration/src/braintree-local-payment-methods/braintree-local-methods-payment-strategy.ts

fixed cart amount for BT LPM
To submit BT LPM order properly
https://github.com/bigcommerce/checkout-sdk-js/assets/56301104/ff4eb62c-31eb-41c6-acfc-ecff1f90ca6e

feat(payment): PAYPAL-2744 fixed cart amount for BT LPM

---

packages/core/src/extension/extension-action-creator.ts
packages/core/src/extension/extension-client.ts
packages/core/src/extension/extension-command.ts
packages/core/src/extension/extension-iframe.spec.ts
packages/core/src/extension/extension-iframe.ts
packages/core/src/extension/extension.ts

- Update extension lib client interface
- Expose `SetIframeStyleCommand`
Update interface to pass extra params as payload and add iframe style command
- CI

feat(checkout): CHECKOUT-000 Update client side interfaces

---

packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-customer-strategy.spec.ts
packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-customer-strategy.ts
packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-payment-strategy.spec.ts
packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-payment-strategy.ts
packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-utils.spec.ts
packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-utils.ts
packages/braintree-integration/src/braintree-accelerated-checkout/create-braintree-accelerated-checkout-customer-strategy.ts
packages/braintree-integration/src/braintree-accelerated-checkout/create-braintree-accelerated-checkout-payment-strategy.ts

Created BraintreeAcceleratedCheckoutUtils class.
BraintreeAcceleratedCheckoutUtils class is a class that contains common PayPal Connect functionality like initialization PP Connect and authentication flow methods.
The class was created to reduce amount of duplications in different BraintreeAcceleratedCheckout strategies, to have one source of truth and to avoid maintenance mistakes in the future.
Unit tests
Manual tests

refactor(payment): PAYPAL-2813 created BraintreeAcceleratedCheckoutUtils class

---

package-lock.json
package.json
packages/core/src/payment/payment.ts
packages/payment-integration-api/src/payment/payment.ts

Bump bigpay-client-js dependency
To be able to provide tokenType data to bigpay
Unit tests
Manual tests

chore(payment): PAYPAL-2737 bump bigpay-client-js dependency

---

.github/CODEOWNERS
packages/braintree-utils/.eslintrc.json
packages/braintree-utils/README.md
packages/braintree-utils/jest.config.js
packages/braintree-utils/project.json
packages/braintree-utils/src/index.ts
packages/braintree-utils/src/sdk-verison.ts
packages/braintree-utils/tsconfig.json
packages/braintree-utils/tsconfig.lib.json
packages/braintree-utils/tsconfig.spec.json
tsconfig.base.json
workspace.json

Created braintree-utils package
To be able to use specific braintree implementation in other integration packages
CI

feat(payment): PAYPAL-2847 created braintree-utils package

---

packages/braintree-integration/src/braintree-script-loader.spec.ts
packages/braintree-integration/src/braintree-script-loader.ts
packages/core/src/payment/strategies/braintree/braintree-script-loader.spec.ts
packages/core/src/payment/strategies/braintree/braintree-script-loader.ts

Updated core and braintree packages with braintree sdk version from braintree-utils package
To have only one source of truth to make it easier to update and maintain in the future
Unit tests
CI

refactor(payment): PAYPAL-2855 updated core and braintree packages with braintree sdk version from braintree-utils package

---

packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-utils.spec.ts
packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-utils.ts
packages/braintree-integration/src/braintree.ts
packages/braintree-utils/src/sdk-verison.ts

Updated braintree sdk with new alpha version
To get PayPal Connect new features released by PayPal
Unit tests

feat(payment): PAYPAL-2854 updated braintree sdk with new alpha version

---

packages/apple-pay-integration/src/apple-pay-button-strategy.spec.ts
packages/apple-pay-integration/src/apple-pay-button-strategy.ts

Fixed applepay spb on PDP
To display applepay spb on PDP 

feat(payment): PAYPAL-2792 fixed applepay spb on PDP

---

packages/payment-integration-api/src/payment/payment.ts

Added PayPal Connect vaulting formatted payload interface
To be able to use those interface for payment payload in the future
CI tests

feat(payment): PAYPAL-2873 added formatted payload interface for PayPal Connect vaulting

---

packages/braintree-utils/src/braintree-integration-service.spec.ts
packages/braintree-utils/src/braintree-integration-service.ts

Updated BT AXO Credit card component style
Due to the recommendations from PayPal team
Unit tests
Manual tests

feat(payment): PAYPAL-2914 updated BT AXO Credit card component style

---

packages/apple-pay-integration/jest.config.js
packages/apple-pay-integration/src/apple-pay-payment-strategy.spec.ts
packages/apple-pay-integration/src/apple-pay-payment-strategy.ts
packages/apple-pay-integration/src/apple-pay.ts
packages/apple-pay-integration/src/create-apple-pay-payment-strategy.ts
packages/apple-pay-integration/src/mocks/apple-pay-button.mock.ts
packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-customer-strategy.spec.ts
packages/braintree-integration/src/braintree-paypal/braintree-paypal-customer-strategy.spec.ts
packages/braintree-integration/src/mocks/braintree.mock.ts
packages/braintree-utils/src/index.ts
packages/braintree-utils/src/mocks/braintree.mock.ts

Revert commits
Failed e2e test in checkout-js
https://github.com/bigcommerce/checkout-sdk-js/pull/2161
https://github.com/bigcommerce/checkout-sdk-js/pull/2131

Revert "feat(payment): PAYPAL-2843 captured device info for Braintree Apple Pay"

---

packages/paypal-commerce-integration/src/paypal-commerce-alternative-methods/paypal-commerce-ratepay-payment-strategy.spec.ts
packages/paypal-commerce-integration/src/paypal-commerce-alternative-methods/paypal-commerce-ratepay-payment-strategy.ts
packages/paypal-commerce-integration/src/paypal-commerce-integration-service.spec.ts
packages/paypal-commerce-integration/src/paypal-commerce-integration-service.ts
packages/paypal-commerce-integration/src/paypal-commerce-request-sender.spec.ts
packages/paypal-commerce-integration/src/paypal-commerce-request-sender.ts
packages/paypal-commerce-integration/src/paypal-commerce-types.ts

Added polling mechanism for ratepay
To fetch order status and submit order and payment

feat(payment): PAYPAL-2632 added polling mechanism for ratepay

---

packages/mollie-integration/src/mollie-payment-strategy.ts

Fixed error message that appears when user tries to place order using card (via Mollie) without filling in card data.
For better user experience.
Error message before fix:
Error message after fix:

feat(payment): PI-734 fix error message for empty card data in Mollie

---

.github/CODEOWNERS

- updated codeowners file with paypal team ownership
- added codeowners for shipping strategies
To make teams responsible for their code

chore(payment): PAYPAL-000 updated codeowners file with paypal team ownership

---

packages/core/src/order/order.ts

Added mandateText field to order mandate interface
To apply new feature
...

feat(payment): PAYPAL-2947 added fields to mandate interface

---

packages/adyen-integration/src/adyenv3/adyenv3-payment-strategy.spec.ts
packages/adyen-integration/src/adyenv3/adyenv3-payment-strategy.ts
packages/adyen-integration/src/adyenv3/adyenv3.mock.ts
packages/adyen-integration/src/adyenv3/adyenv3.ts

Updated Adyen component state for the Boleto implementation
Due to the adding Boleto Payment method
Tested manully/units

feat(checkout): PI-741 updated adyen component state for the Boleto implementation

---

packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-customer-strategy.spec.ts
packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-customer-strategy.ts

If the Accelerated Checkout feature is turned on we will loaded PayPal Connect scripts with the customer step initialisation process, so the script will be loaded before the customer clicks on “Continue” button. After the customer clicks on “Continue” button:
1. We make only 1 request to check if the BraintreeAcceleratedCheckout is on
- If it’s on, we check if the customer can use the feature due to the A/B test;
- If it’s off, then the customer will not be able to use the feature.
2. Call lookup method;
3. Call triggerAuthentication method to open OTP popup;
The amount of time that needed to show OTP popup reduced from 5-7 seconds to 2-3 seconds (2-3 times faster than in prev implementation).
Regarding to the A/B testing, PayPal Connect implementation was started right after customer …

feat(payment): PAYPAL-3099 updated BraintreeAcceleratedCheckout customer strategy to reduce customers waiting time

---

packages/core/src/payment/payment.ts
packages/core/src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.ts

Add single method for payment request payload
Refactoring and types fixes
Manually tested and unit test

feat(payment): PI-976 Stripe UPE payment payload refactoring

---

packages/paypal-commerce-integration/src/paypal-commerce-credit-card/paypal-commerce-credit-cards-payment-strategy.ts
packages/paypal-commerce-integration/src/paypal-commerce-credit-card/paypal-commerce-credit-cards-strategy.spec.ts

Updated payment payload to be able to vault instrument for PayPalCommerce Credit Card, to send valid "save instrument" checkbox value to BE.
It is a part of creating PayPalCommerce Credit Card vaulting feature. To make this feature works we should pass the data of "save instrument" checkbox value in payment payload. So the backend will know when to save vaulting instrument.
Unit tests
Manual tests

feat(payment): PAYPAL-3156 updated payment payload to be able to vault instrument for PayPalCommerce Credit Card

---

.github/CODEOWNERS
packages/td-bank-integration/.eslintrc.json
packages/td-bank-integration/README.md
packages/td-bank-integration/jest.config.js
packages/td-bank-integration/project.json
packages/td-bank-integration/tsconfig.json
packages/td-bank-integration/tsconfig.spec.json
tsconfig.base.json
workspace.json

New TD Bank package for future integration
For adding strategies for new TD Bank integration

feat(payment): PI-1004 Create a new package for TD Bank integration

---

packages/google-pay-integration/src/google-pay-paypal-commerce/google-pay-paypal-commerce-payment-strategy.spec.ts
packages/google-pay-integration/src/google-pay-paypal-commerce/google-pay-paypal-commerce-payment-strategy.ts
packages/google-pay-integration/src/google-pay-paypal-commerce/types.ts

PPCP Google Pay 3DSecure implementation

feat(payment): PAYPAL-3175 PPCP GooglePay 3DSecure

---

packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-customer-strategy.spec.ts
packages/braintree-integration/src/braintree-accelerated-checkout/braintree-accelerated-checkout-customer-strategy.ts
packages/core/src/analytics/braintree-connect-tracker/braintree-connect-tracker.spec.ts
packages/core/src/analytics/braintree-connect-tracker/braintree-connect-tracker.ts

- fixed the issue with braintree axo customer step initialisation;
- fixed data for BT AXO Analytics;
There was an issue when the customer from control group moved back to customer step to change the email. Also we the experiment treatment group had wrong data passed to BT SDK.
Unit tests
Manual tests
https://github.com/bigcommerce/checkout-sdk-js/assets/25133454/2c1fbcc3-58ce-4743-a76c-f974bfbe5522

fix(payment): PAYPAL-3360 fixed the issue with braintree axo customer step initialisation and fixed data for BT AXO Analytics

---

packages/braintree-utils/src/braintree.ts
packages/core/src/analytics/braintree-connect-tracker/braintree-connect-tracker.spec.ts
packages/core/src/analytics/braintree-connect-tracker/braintree-connect-tracker.ts

Covered braintree connect analytic with experiment
To be able to turn off/on the feature for different stores
Unit tests
Manual tests

feat(payment): PAYPAL-3382 covered braintree connect analytic with experiment

---

packages/core/src/payment/instrument/supported-payment-instruments.ts
packages/squarev2-integration/src/squarev2-payment-processor.spec.ts
packages/squarev2-integration/src/squarev2-payment-processor.ts
packages/squarev2-integration/src/squarev2-payment-strategy.spec.ts
packages/squarev2-integration/src/squarev2-payment-strategy.ts
packages/squarev2-integration/src/types.ts

Reverts bigcommerce/checkout-sdk-js#2278

Revert "feat(payment): PI-1076 add 3ds support for storing cards in square v2"

---

packages/td-bank-integration/src/create-td-online-mart-payment-strategy.ts
packages/td-bank-integration/src/isTdOnlineMartAdditionalAction.spec.ts
packages/td-bank-integration/src/isTdOnlineMartAdditionalAction.ts
packages/td-bank-integration/src/td-online-mart-payment-strategy.spec.ts
packages/td-bank-integration/src/td-online-mart-payment-strategy.ts
packages/td-bank-integration/src/td-online-mart.ts

TD Bank 3DS flow
Add 3DS challenge for TD Bank payment startegy

feat(payment): PI-1126 TD Bank 3DS flow implementation

---

.github/CODEOWNERS
packages/paypal-commerce-utils/.eslintrc.json
packages/paypal-commerce-utils/README.md
packages/paypal-commerce-utils/jest.config.js
packages/paypal-commerce-utils/project.json
packages/paypal-commerce-utils/src/index.ts
packages/paypal-commerce-utils/src/mocks/get-paypal-axo-sdk.mock.ts
packages/paypal-commerce-utils/src/mocks/get-paypal-commerce-payment-method.mock.ts
packages/paypal-commerce-utils/src/mocks/index.ts
packages/paypal-commerce-utils/src/paypal-commerce-sdk.spec.ts
packages/paypal-commerce-utils/src/paypal-commerce-sdk.ts
packages/paypal-commerce-utils/src/paypal-commerce-types.ts
packages/paypal-commerce-utils/tsconfig.json
packages/paypal-commerce-utils/tsconfig.lib.json
packages/paypal-commerce-utils/tsconfig.spec.json
tsconfig.base.json
workspace.json

Created paypal-commerce-utils package
To be able to use shared PPCP code in different packages
Unit tests
CI

feat(payment): PAYPAL-3418 created paypal-commerce-utils package

---

packages/paypal-commerce-integration/src/index.ts
packages/paypal-commerce-integration/src/paypal-commerce-accelerated-checkout/create-paypal-commerce-accelerated-checkout-customer-strategy.spec.ts
packages/paypal-commerce-integration/src/paypal-commerce-accelerated-checkout/create-paypal-commerce-accelerated-checkout-customer-strategy.ts
packages/paypal-commerce-integration/src/paypal-commerce-accelerated-checkout/paypal-commerce-accelerated-checkout-customer-initialize-options.ts
packages/paypal-commerce-integration/src/paypal-commerce-accelerated-checkout/paypal-commerce-accelerated-checkout-customer-strategy.spec.ts
packages/paypal-commerce-integration/src/paypal-commerce-accelerated-checkout/paypal-commerce-accelerated-checkout-customer-strategy.ts
packages/paypal-commerce-utils/src/create-paypal-commerce-sdk.spec.ts
packages/paypal-commerce-utils/src/create-paypal-commerce-sdk.ts
packages/paypal-commerce-utils/src/index.ts
packages/paypal-commerce-utils/src/mocks/get-paypal-axo-sdk.mock.ts
packages/paypal-commerce-utils/src/paypal-commerce-accelerated-checkout-utils.spec.ts
packages/paypal-commerce-utils/src/paypal-commerce-accelerated-checkout-utils.ts
packages/paypal-commerce-utils/src/paypal-commerce-sdk.ts
packages/paypal-commerce-utils/src/paypal-commerce-types.ts

Added PayPalCommerceAcceleratedCheckout customer strategy
As part of PayPal Connect implementation for PPCP
Unit tests
Manual tests

feat(payment): PAYPAL-3409 added PayPalCommerceAcceleratedCheckout customer strategy

---

packages/paypal-commerce-integration/src/paypal-commerce-ratepay/create-paypal-commerce-ratepay-payment-strategy.ts
packages/paypal-commerce-integration/src/paypal-commerce-ratepay/paypal-commerce-ratepay-initialize-options.ts
packages/paypal-commerce-integration/src/paypal-commerce-ratepay/paypal-commerce-ratepay-payment-strategy.spec.ts
packages/paypal-commerce-integration/src/paypal-commerce-ratepay/paypal-commerce-ratepay-payment-strategy.ts

Fixed ratepay loading indicator
To make loading indicator work properly
https://github.com/bigcommerce/checkout-sdk-js/assets/56301104/0a689fdf-a045-41be-9210-f3558b908b2e

feat(payment): PAYPAL-3390 fixed ratepay loading indicator

---

packages/paypal-commerce-utils/src/paypal-commerce-accelerated-checkout-utils.spec.ts
packages/paypal-commerce-utils/src/paypal-commerce-accelerated-checkout-utils.ts
packages/paypal-commerce-utils/src/paypal-commerce-types.ts

Placed paypal connect to the window object 
To avoid unnecessary PP AXO initialisation and get access to paypalConnect implementation in analytics class in the future
Unit tests

fix(payment): PAYPAL-000 placed paypal connect to the window object to avoid unnecessary PP AXO initialisation

---

packages/paypal-commerce-integration/src/paypal-commerce-accelerated-checkout/paypal-commerce-accelerated-checkout-customer-strategy.spec.ts
packages/paypal-commerce-integration/src/paypal-commerce-accelerated-checkout/paypal-commerce-accelerated-checkout-customer-strategy.ts

Reverts bigcommerce/checkout-sdk-js#2324
We do not need this changes anymore

Revert "fix(payment): PAYPAL-3466 load paypalcommerce payment method in initialization method of PPCP AXO customer strategy"

---

packages/adyen-integration/src/adyenv2/adyenv2-payment-strategy.spec.ts
packages/adyen-integration/src/adyenv2/adyenv2-payment-strategy.ts
packages/adyen-integration/src/adyenv3/adyenv3-payment-strategy.spec.ts
packages/adyen-integration/src/adyenv3/adyenv3-payment-strategy.ts

Reverts bigcommerce/checkout-sdk-js#2260
Credit card not working

Revert "feat(payment): PI-429 [Adyen] Improve FE validation for APMs on checkout"

---

packages/paypal-commerce-integration/src/paypal-commerce-script-loader.spec.ts
packages/paypal-commerce-integration/src/paypal-commerce-script-loader.ts

Cleanup ppcp axo implementation from generic paypal commerce script
We moved it in separate package and load paypal connect in different namespace
Unit tests
CI

fix(payment): PAYPAL-000 cleanup ppcp axo implementation from generic paypal commerce script

---

packages/squarev2-integration/src/squarev2-payment-strategy.spec.ts
packages/squarev2-integration/src/squarev2-payment-strategy.ts
packages/squarev2-integration/src/types.ts

3ds flow for Square V2 vaulted instruments
To add ability for shoppers to use saved Square credit cards with 3d secure challenge
Unit test & manually tested

feat(payment): PI-1309 SquareV2 - 3ds flow for vaulted instruments

---

packages/storage/src/cookie-storage.spec.ts
packages/storage/src/cookie-storage.ts
packages/storage/src/index.ts

Create a class to work with cookies
To work with cookies
Manual testing
Jest tests

feat(payment): PAYPAL-3113 Create a class to work with cookies

---

packages/squarev2-integration/src/squarev2-payment-strategy.spec.ts
packages/squarev2-integration/src/squarev2-payment-strategy.ts
packages/squarev2-integration/src/types.ts

Change payment submitting payload
To prevent multiple type guard checks and code duplications.
manually tested and unit test

feat(payment): PI-1368 SquareV2 - fix types for payment submit payload

---

packages/core/src/shipping/create-shipping-strategy-registry.spec.ts
packages/core/src/shipping/create-shipping-strategy-registry.ts
packages/core/src/shipping/strategies/paypal-commerce/index.ts
packages/core/src/shipping/strategies/paypal-commerce/paypal-commerce-accelerated-checkout-shipping-initialization-options.ts
packages/core/src/shipping/strategies/paypal-commerce/paypal-commerce-accelerated-checkout-shipping-strategy.spec.ts
packages/core/src/shipping/strategies/paypal-commerce/paypal-commerce-accelerated-checkout-shipping-strategy.ts

Added PayPalCommerceAcceleratedCheckout shipping strategy
To be able to authenticate user with PayPal Connect and get related data to use in checkout flow
Unit tests
Manual tests
CI

feat(payment): PAYPAL-3419 added PayPalCommerceAcceleratedCheckout shipping strategy

---

packages/bluesnap-direct-integration/src/bluesnap-direct-apm/bluesnap-direct-apm-payment-strategy.ts
packages/core/src/payment/instrument/supported-payment-instruments.ts
packages/payment-integration-api/src/payment/payment.ts

Implementation of the stored SEPA for Bluesnap Direct
[checkout-js PR](https://github.com/bigcommerce/checkout-js/pull/1686)
Due to the product requirements
https://github.com/bigcommerce/checkout-js/assets/79574476/7a48007a-f44d-4005-be96-18c05be36c85

feat(payment): PI-1355 stored sepa for bluesnap

---

packages/core/src/shipping/strategies/paypal-commerce/index.ts
packages/core/src/shipping/strategies/paypal-commerce/paypal-commerce-fastlane-shipping-initialization-options.ts
packages/core/src/shipping/strategies/paypal-commerce/paypal-commerce-fastlane-shipping-strategy.spec.ts
packages/core/src/shipping/strategies/paypal-commerce/paypal-commerce-fastlane-shipping-strategy.ts

Updated PayPal Commerce AXO shipping strategy to support PP Connect + Fastlane
As part of PayPal Connect rebranding to PayPal Fastlane. We should support both features until fastlane experiment will be rolled out to 100%
Unit tests
CI

feat(payment): PAYPAL-3575 updated paypal commerce AXO shipping strategy to support PP Connect + Fastlane

---

packages/core/src/analytics/paypal-commerce-connect-tracker/paypal-commerce-connect-tracker.ts
packages/core/src/shipping/strategies/paypal-commerce/paypal-commerce-accelerated-checkout-shipping-strategy.spec.ts
packages/core/src/shipping/strategies/paypal-commerce/paypal-commerce-accelerated-checkout-shipping-strategy.ts
packages/core/src/shipping/strategies/paypal-commerce/paypal-commerce-fastlane-shipping-strategy.spec.ts
packages/core/src/shipping/strategies/paypal-commerce/paypal-commerce-fastlane-shipping-strategy.ts
packages/paypal-commerce-integration/src/paypal-commerce-credit-card/paypal-commerce-credit-cards-payment-strategy.ts
packages/paypal-commerce-integration/src/paypal-commerce-credit-card/paypal-commerce-credit-cards-strategy.spec.ts
packages/paypal-commerce-integration/src/paypal-commerce-fastlane/paypal-commerce-fastlane-customer-strategy.spec.ts
packages/paypal-commerce-integration/src/paypal-commerce-fastlane/paypal-commerce-fastlane-customer-strategy.ts
packages/paypal-commerce-integration/src/paypal-commerce-fastlane/paypal-commerce-fastlane-payment-strategy.spec.ts
packages/paypal-commerce-integration/src/paypal-commerce-fastlane/paypal-commerce-fastlane-payment-strategy.ts
packages/paypal-commerce-utils/src/paypal-commerce-sdk.spec.ts
packages/paypal-commerce-utils/src/paypal-commerce-sdk.ts

Updated paypal fastlane analytic related code with modified sessionId and updated data-client-metadata-id with modified sessionId
To be able to match PayPal Fastlane analytic data and PayPal Fastlane user session on PayPal side
Unit tests
CI

feat(payment): PAYPAL-3646 updated paypal fastlane analytic related code with modified sessionId

---

package-lock.json
package.json

Bump form-poster version
To keep everything up-to-date

feat(payment): PAYPAL-3371 bump form-poster version

---

packages/core/src/payment/instrument/supported-payment-instruments.ts

Added a new payment instrument
Regarding the new implementation of PayPal's vault accounts

feat(payment): PAYPAL-3453 Added a new payment instrument

---

packages/paypal-commerce-integration/src/paypal-commerce-credit-card/paypal-commerce-credit-cards-payment-strategy.spec.ts
packages/paypal-commerce-integration/src/paypal-commerce-credit-card/paypal-commerce-credit-cards-payment-strategy.ts

Updated Credit Cards payment payload on checkout page

feat(payment): PAYPAL-3705 PPCP Card Fields payment payload updated

---

packages/braintree-utils/src/braintree-integration-service.spec.ts
packages/braintree-utils/src/braintree-integration-service.ts
packages/braintree-utils/src/braintree-script-loader.spec.ts
packages/braintree-utils/src/braintree-script-loader.ts
packages/braintree-utils/src/braintree.ts
packages/braintree-utils/src/mocks/braintree.mock.ts
packages/braintree-utils/src/sdk-verison.ts
packages/braintree-utils/src/utils/get-valid-braintree-fastlane-styles.spec.ts
packages/braintree-utils/src/utils/get-valid-braintree-fastlane-styles.ts
packages/braintree-utils/src/utils/index.ts

Added methoda that loads fastlane and all needed intefaces
To support fastlane script
Unit tests
CI

feat(payment): PAYPAL-3585 updated braintree scriptloader to load fastlane

---

package-lock.json
package.json

Update request sender to latest version
Release https://github.com/bigcommerce/request-sender-js/pull/70
- CI

chore(common): CHECKOUT-8092 Update request sender to latest version

---

packages/braintree-utils/src/braintree-script-loader.ts
packages/braintree-utils/src/braintree.ts

Removed duplications and created generic method in braintree-script-loader file
To keep our code as clean as possible
Unit tests
CI

refactor(payment): PAYPAL-000 removed duplications and created generic method in braintree-script-loader file

---

packages/core/src/payment/strategies/worldpayaccess/worldpayaccess-payment-strategy.spec.ts
packages/core/src/payment/strategies/worldpayaccess/worldpayaccess-payment-strategy.ts

Fixed 3ds challenge for WorldPay
Due to the CORS error with cardinal request
https://github.com/bigcommerce/checkout-sdk-js/assets/79574476/0f974b72-3b38-4b57-99ec-fd11781e6622

fix(payment): PI-1287 fixed 3ds challenge for WorldPay

---

packages/braintree-utils/src/sdk-verison.ts

revert BT SDK ALPHA version
To avoid errors

feat(payment): PAYPAL-0_BT_VERSION_HOTFIX revert BT SDK ALPHA version

---

packages/paypal-commerce-integration/src/paypal-commerce-fastlane/paypal-commerce-fastlane-payment-strategy.spec.ts
packages/paypal-commerce-integration/src/paypal-commerce-fastlane/paypal-commerce-fastlane-payment-strategy.ts

Update paypal card selection implementation for PayPal Commerce Fastlane component
There was an issue related to selected PayPal Commerce Fastlane instrument when user selects the instrument and then changes billing address (for example). So we should keep selected Fastlane instrument to avoid mistakes in the flow
Unit tests
Manual tests
CI
Before:
https://github.com/bigcommerce/checkout-sdk-js/assets/25133454/b7dc9c06-3970-498f-bbe3-a25c9b90a371
After:
https://github.com/bigcommerce/checkout-sdk-js/assets/25133454/e3f5a431-950d-4b3e-8b50-7b48dc8a8923

fix(payment): PAYPAL-3774 update paypal card selection implementation for PayPal Commerce Fastlane component

---

packages/klarna-integration/src/klarnav2/create-klarnav2-payment-strategy.ts
packages/klarna-integration/src/klarnav2/klarnav2-payment-strategy.spec.ts
packages/klarna-integration/src/klarnav2/klarnav2-payment-strategy.ts

Reverts bigcommerce/checkout-sdk-js#2447

Revert "fix(payment): PI-1823 Add shop path to the remote checkout request"

---

packages/braintree-utils/src/braintree-script-loader.spec.ts
packages/braintree-utils/src/braintree-script-loader.ts
packages/braintree-utils/src/braintree.ts
packages/braintree-utils/src/mocks/braintree.mock.ts

Update braintree scripts by passing additional `integrity` and `crossorigin` attributes to script tag that is loaded from the BraintreeScriptLoader
According to PCI v4.0
Braintree manual testing

feat(payment): PAYPAL-3850 Update braintree scripts by passing additional integrity and crossorigin attributes to script tag

---

packages/braintree-integration/src/braintree-ach/create-braintree-ach-payment-strategy.ts
packages/braintree-utils/src/create-braintree-sdk.spec.ts
packages/braintree-utils/src/create-braintree-sdk.ts
packages/braintree-utils/src/index.ts

Added createBraintreeSdk file
To hold all logic of BraintreeSdk class creation there and avoid duplication in all Braintree strategies creation files in the future
Unit tests
CI

refactor(payment): PAYPAL-000 added createBraintreeSdk file

---

packages/braintree-utils/src/braintree-script-loader.spec.ts
packages/braintree-utils/src/braintree-script-loader.ts
packages/braintree-utils/src/braintree.ts
packages/braintree-utils/src/sdk-verison.ts

Added fastlane compatible version
To integrate fastlane
Unit tests

feat(payment): PAYPAL-4048 added fastlane compatible version

---

packages/braintree-integration/src/braintree-fastlane/braintree-fastlane-payment-strategy.spec.ts
packages/braintree-integration/src/braintree-fastlane/braintree-fastlane-payment-strategy.ts
packages/braintree-integration/src/braintree-fastlane/braintree-fastlane-utils.ts
packages/braintree-integration/src/braintree-fastlane/is-braintree-connect-card-component.ts
packages/braintree-integration/src/braintree-fastlane/is-braintree-fastlane-card-component.ts
packages/braintree-utils/src/braintree-integration-service.ts
packages/braintree-utils/src/braintree-script-loader.spec.ts
packages/braintree-utils/src/braintree.ts
packages/braintree-utils/src/mocks/braintree.mock.ts
packages/paypal-commerce-integration/src/paypal-commerce-fastlane/paypal-commerce-fastlane-payment-strategy.spec.ts
packages/paypal-commerce-integration/src/paypal-commerce-fastlane/paypal-commerce-fastlane-payment-strategy.ts
packages/paypal-commerce-utils/src/mocks/get-paypal-fastlane.mock.ts
packages/paypal-commerce-utils/src/paypal-commerce-fastlane-utils.spec.ts
packages/paypal-commerce-utils/src/paypal-commerce-fastlane-utils.ts
packages/paypal-commerce-utils/src/paypal-commerce-types.ts

Updated fastlane payment strategies for braintree and paypal commerce:
- updated FastlaneCardComponent to FastlanePaymentComponent;
- fixed the issue with Fastlane sandbox switch;
- updated interfaces with related changes;
Fastlane implementation was broken and customer was not able to place order using Fastlane integration
Unit tests
Manual tests
CI
Both providers tested on integration store:
Gary flow:
https://github.com/bigcommerce/checkout-sdk-js/assets/25133454/ee93c8c0-6800-49aa-9d49-9c753a1b0c03
Ryan flow:
https://github.com/bigcommerce/checkout-sdk-js/assets/25133454/e2db5b55-11da-401d-8ce9-7e63ad4e6fef

feat(payment): PAYPAL-000 updated fastlane payment strategies for braintree and paypal commerce

---

packages/klarna-integration/src/klarnav2/klarnav2-payment-strategy.spec.ts
packages/klarna-integration/src/klarnav2/klarnav2-payment-strategy.ts

Update shipping and billing data before make Klarna authorisation request
We should use the latest data, which should be synchronised with Klarna Payment Intent, as payload for Klarna authorize request
https://github.com/bigcommerce/checkout-sdk-js/assets/9430298/a4d705ac-0d78-470f-a39f-796bba88b4b1

fix(payment): PI-1925 get actual data for Klarna authentication request

---

packages/core/src/shipping/create-shipping-strategy-registry.spec.ts
packages/core/src/shipping/create-shipping-strategy-registry.ts
packages/core/src/shipping/shipping-request-options.ts

Renamed braintree accelerated checkout shipping strategy files
To update naming
Unit tests

feat(payment): PAYPAL-4069 renamed braintree accelerated checkout shipping strategy files

---

packages/core/src/shipping/strategies/braintree/index.ts

Removed temporary import and export
No longer needed
Unit tests

feat(payment): PAYPAL-4069 removed temporary import and export

---

packages/braintree-integration/src/braintree-fastlane/braintree-fastlane-utils.spec.ts
packages/braintree-integration/src/braintree-fastlane/braintree-fastlane-utils.ts
packages/braintree-utils/src/braintree.ts
packages/braintree-utils/src/utils/index.ts
packages/braintree-utils/src/utils/is-braintree-connect-phone.spec.ts
packages/braintree-utils/src/utils/is-braintree-connect-phone.ts

Fixed phone number
To be able to preselect all required data

feat(payment): PAYPAL-4170 fixed phone number

---

packages/paypal-commerce-integration/src/paypal-commerce-fastlane/paypal-commerce-fastlane-customer-strategy.spec.ts
packages/paypal-commerce-integration/src/paypal-commerce-fastlane/paypal-commerce-fastlane-customer-strategy.ts

Added shipping option autoselect to PPCP Fastlane customer strategy
To speed up customer purchase experience by bypassing shipping and billing steps and land customer strait on payment step
Unit tests
Manual tests
CI
https://github.com/bigcommerce/checkout-sdk-js/assets/25133454/9c304548-d5fb-4f84-97a3-f863088282cc

feat(payment): PAYPAL-4142 added shipping option autoselect to PPCP Fastlane customer strategy

---

packages/klarna-integration/src/klarnav2/create-klarnav2-payment-strategy.ts
packages/klarna-integration/src/klarnav2/klarnav2-payment-strategy.spec.ts
packages/klarna-integration/src/klarnav2/klarnav2-payment-strategy.ts
packages/klarna-integration/src/klarnav2/klarnav2-token-updater.spec.ts
packages/klarna-integration/src/klarnav2/klarnav2-token-updater.ts

Adding call Klarna order initialization endpoint before showing Klarna pop-up window
To update Klarna checkout session.

feat(payment): PI-2132 Call Klarna order initialization endpoint befo… …re showing Klarna pop-up window

---

packages/braintree-integration/src/braintree-fastlane/braintree-fastlane-payment-strategy.spec.ts
packages/braintree-integration/src/braintree-fastlane/braintree-fastlane-payment-strategy.ts
packages/braintree-utils/src/braintree.ts

Prefilled cardholder name
To show cardholder name
https://github.com/bigcommerce/checkout-sdk-js/assets/56301104/1647a997-d3c7-4814-83e1-fdd2b35b5cc4

feat(payment): PAYPAL-4138 prefilled cardholder name

---

packages/braintree-integration/src/braintree-fastlane/braintree-fastlane-payment-strategy.spec.ts
packages/braintree-integration/src/braintree-fastlane/braintree-fastlane-payment-strategy.ts
packages/braintree-utils/src/types.ts

Added full name to getPaymentToken config
To show correct full name
Unit test

feat(payment): PAYPAL-4141 added full name to getPaymentToken config

---

packages/core/src/shipping/strategies/paypal-commerce/paypal-commerce-fastlane-shipping-strategy.spec.ts
packages/core/src/shipping/strategies/paypal-commerce/paypal-commerce-fastlane-shipping-strategy.ts
packages/paypal-commerce-integration/src/paypal-commerce-fastlane/paypal-commerce-fastlane-customer-strategy.spec.ts
packages/paypal-commerce-integration/src/paypal-commerce-fastlane/paypal-commerce-fastlane-customer-strategy.ts
packages/paypal-commerce-integration/src/paypal-commerce-fastlane/paypal-commerce-fastlane-payment-strategy.spec.ts
packages/paypal-commerce-integration/src/paypal-commerce-fastlane/paypal-commerce-fastlane-payment-strategy.ts
packages/paypal-commerce-utils/src/paypal-commerce-types.ts
packages/paypal-commerce-utils/src/utils/get-fastlane-styles.spec.ts
packages/paypal-commerce-utils/src/utils/get-fastlane-styles.ts
packages/paypal-commerce-utils/src/utils/index.ts

Added CP styles for Paypal fastlane
To be able to customise fastlane component

feat(payment): PAYPAL-4147 added CP styles for Paypal fastlane

---

packages/core/src/extension/extension.ts

Add 3 new checkout extension regions.
https://github.com/bigcommerce/bigcommerce/pull/58761
Business requirement.
CI checks.

feat(checkout): CHECKOUT-8281 Add 3 New Checkout Extension Regions

---

packages/adyen-integration/src/adyenv3/adyenv3-payment-strategy.spec.ts
packages/adyen-integration/src/adyenv3/adyenv3-payment-strategy.ts
packages/adyen-utils/src/types.ts

Adyen Credit Card installments implementation
Due to the feature request
https://github.com/user-attachments/assets/0835cb4f-5caa-46a2-890d-5c4f8a87b579

feat(checkout): PI-2290 Adyen Credit Card installments implementation

---

packages/google-pay-integration/jest.config.js
packages/google-pay-integration/src/gateways/google-pay-gateway.spec.ts
packages/google-pay-integration/src/gateways/google-pay-gateway.ts
packages/google-pay-integration/src/google-pay-button-strategy.spec.ts
packages/google-pay-integration/src/google-pay-button-strategy.ts
packages/google-pay-integration/src/google-pay-customer-strategy.spec.ts
packages/google-pay-integration/src/google-pay-customer-strategy.ts
packages/google-pay-integration/src/google-pay-payment-processor.ts
packages/google-pay-integration/src/types.ts
packages/payment-integration-api/src/currency/index.ts
packages/payment-integration-api/src/index.ts

Stripe 378 test

---

packages/braintree-utils/src/braintree-script-loader.spec.ts
packages/braintree-utils/src/braintree-script-loader.ts

Updated hash parameters to avoid failed resource loading
Manual

feat(payment): PAYPAL-000 updated hash parameters

---

packages/braintree-integration/src/braintree-fastlane/braintree-fastlane-payment-strategy.spec.ts
packages/braintree-integration/src/braintree-fastlane/braintree-fastlane-payment-strategy.ts

Fixed region for fastlane for Thailand
To avoid errors
https://github.com/user-attachments/assets/1bd54784-0e11-46c1-baff-140417d8c85f

feat(payment): PAYPAL-4497 fixed region for fastlane for Thailand

---

packages/adyen-utils/src/adyenv2/adyenv2.mock.ts
packages/adyen-utils/src/adyenv3/adyenv3.mock.ts

Removed ts-ignore and updated adyen mocks to fix the issue with ts-jest
This tech dept was created during jest dependency update. So to keep checkout sdk as clean as possible, we should do some work in this area. 
Lint & Test & Build commands passed locally
CI

refactor(payment): PAYPAL-4525 removed ts-ignore and updated adyen mocks to fix the issue with ts-jest

---

packages/core/src/common/iframe/iframe-event-listener.spec.ts
packages/core/src/common/iframe/iframe-event-poster.spec.ts

Removed ts-ignore and updated tests in core/src/common/iframe folder
This tech dept was created during jest dependency update. So to keep checkout sdk as clean as possible, we should do some work in this area.
Lint & Test & Build commands passed locally
CI

refactor(payment): PAYPAL-4526 removed ts-ignore and updated tests in core/src/common/iframe folder due to jest update tech debt

---

packages/core/src/coupon/gift-certificate-request-sender.spec.ts

Removed ts-ignore and updated tests in core/src/coupon folder
To reduce tech debt after updating jest to v26
Test & lint & build commands passed locally
CI

refactor(payment): PAYPAL-4531 removed ts-ignore and updated tests in core/src/coupon folder

---

packages/google-pay-integration/src/factories/button/create-google-pay-tdonlinemart-button-strategy.ts
packages/google-pay-integration/src/factories/customer/create-google-pay-tdonlinemart-customer-strategy.ts
packages/google-pay-integration/src/factories/payment/create-google-pay-tdonlinemart-payment-strategy.ts
packages/google-pay-integration/src/gateways/google-pay-tdonlinemart-gateway.spec.ts
packages/google-pay-integration/src/gateways/google-pay-tdonlinemart-gateway.ts
packages/google-pay-integration/src/guards/is-google-pay-td-online-mart-additional-action.spec.ts
packages/google-pay-integration/src/guards/is-google-pay-td-online-mart-additional-action.ts
packages/google-pay-integration/src/types.ts

- Added 3DS to GooglePay in TD Online Mart
- Modified payment request payload

feat(payment): PI-2428 Google Pay on TD Online Mart - check if FE is working correctly, adjust communication FE -> BE

---

packages/core/src/extension/create-extension-event-poster.spec.ts
packages/core/src/extension/extension-action-creator.spec.ts
packages/core/src/extension/extension-event-broadcaster.spec.ts
packages/core/src/extension/extension-iframe.spec.ts
packages/core/src/extension/extension-messenger.spec.ts
packages/core/src/extension/resizable-firame-creator.spec.ts

Removed ts-ignore tech debt after jest update in core/src/extension folder
As part of jest dependency update tech debt cleanup
Local lint & test & build commands passed successfully 
CI

refactor(payment): PAYPAL-4533 removed ts-ignore tech debt after jest update in core/src/extension folder

---

packages/stripe-integration/src/stripe-upe/stripe-upe-payment-strategy.spec.ts
packages/stripe-integration/src/stripe-upe/stripe-upe-payment-strategy.ts
packages/stripe-integration/src/stripe-upe/stripe-upe.ts

Reverts bigcommerce/checkout-sdk-js#2605

Revert "fix(payment): STRIPE-422 Fix saving  Stripe Link instrument"

---

packages/core/src/checkout/checkout-service.spec.ts
packages/core/src/checkout/checkout-service.ts
packages/core/src/checkout/create-checkout-service.ts
packages/core/src/payment-integration/create-payment-integration-service.ts
packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-strategy.spec.ts
packages/core/src/shipping/shipping-country-action-creator.spec.ts
packages/core/src/shipping/shipping-country-action-creator.ts
packages/core/src/shipping/shipping-country-request-sender.spec.ts
packages/core/src/shipping/shipping-country-request-sender.ts

Reverts bigcommerce/checkout-sdk-js#2579
ping @bigcommerce/team-checkout

Revert "feat(shipping): SHIPPING-3183 Add support for channel_ids to the load shipping countries action"

---

packages/paypal-commerce-integration/src/paypal-commerce-fastlane/paypal-commerce-fastlane-customer-strategy.spec.ts
packages/paypal-commerce-integration/src/paypal-commerce-fastlane/paypal-commerce-fastlane-customer-strategy.ts

Removed A/B testing implementation from PPCP Fastlane customer strategy
Fastlane is already in GA for US and does not need A/B testing implementation anymore, so we removed it to reduce amount for request, that we sent to BE.
Unit tests
Manual tests
CI
https://github.com/user-attachments/assets/2bb3a74f-ce6b-47bc-8142-f994c1ef3b31

refactor(payment): PAYPAL-4619 removed A/B testing implementation from PPCP Fastlane customer strategy

---

packages/google-pay-integration/src/gateways/google-pay-gateway.spec.ts
packages/google-pay-integration/src/gateways/google-pay-gateway.ts
packages/google-pay-integration/src/google-pay-button-strategy.spec.ts
packages/google-pay-integration/src/google-pay-button-strategy.ts
packages/google-pay-integration/src/google-pay-customer-strategy.spec.ts
packages/google-pay-integration/src/google-pay-customer-strategy.ts
packages/google-pay-integration/src/google-pay-payment-processor.spec.ts
packages/google-pay-integration/src/google-pay-payment-processor.ts
packages/google-pay-integration/src/google-pay-payment-strategy.spec.ts
packages/google-pay-integration/src/google-pay-payment-strategy.ts

Fix GPay shipping address and shipping options for digital products. Change GPay widget initialisation process.
We should not show Shipping address and shipping options for digital products.
Physical product:
https://github.com/user-attachments/assets/47c64a32-ab70-4376-998d-e3b5e5260fd9
Digital:
https://github.com/user-attachments/assets/84177b37-2b08-4d36-9b24-002f94d54de9
Physical
https://github.com/user-attachments/assets/97085fce-32b6-4675-b84b-8b5bc55a0722
Digital
https://github.com/user-attachments/assets/3b3e7681-8903-43e7-b853-00ca5006750e
Physical
https://github.com/user-attachments/assets/ed534e6e-a3e0-419e-8143-b61b3192a4ee
Digital
https://github.com/user-attachments/assets/9bef66d9-81dd-4aa8-b6a1-c8b8a18772c1
Physical …

fix(payment): STRIPE-426 fix gpay shipping for buy now flow

---

.github/CODEOWNERS
packages/amazon-pay-integration/.eslintrc.json
packages/amazon-pay-integration/README.md
packages/amazon-pay-integration/jest.config.js
packages/amazon-pay-integration/project.json
packages/amazon-pay-integration/tsconfig.json
packages/amazon-pay-integration/tsconfig.lib.json
packages/amazon-pay-integration/tsconfig.spec.json
tsconfig.base.json
workspace.json

Create AmazonPay package
To migrate Amazon pay strategies to integration package
Only package folder creation, no test needed

feat(payment): PI-2547 create AmazonPay package

---

.github/CODEOWNERS
packages/digitalriver-integration/src/digitalriver-payment-strategy.ts

Fixed submit payment for the Digital River
Due to the issue with Payment execution
Before the fix:
https://github.com/user-attachments/assets/abdbaf71-5cf1-4c56-9af2-f6fc56a3f850
After the fix:
https://github.com/user-attachments/assets/b96eb4d5-ca87-449f-92d9-9ba99fbc2f3c

fix(checkout): PI-2623 fixed submit payment for the Digital River

---

packages/paypal-commerce-integration/src/paypal-commerce-credit-card/paypal-commerce-credit-cards-payment-strategy.spec.ts
packages/paypal-commerce-integration/src/paypal-commerce-credit-card/paypal-commerce-credit-cards-payment-strategy.ts
packages/paypal-commerce-integration/src/paypal-commerce-types.ts

Added  PPCP Credit card 3ds check
To verify card
**Successful 3DS Flow**
https://github.com/user-attachments/assets/214365c1-b692-41b5-8672-223029f15e4f
**Failed 3DS Flow**
https://github.com/user-attachments/assets/e33c986f-64c5-486c-8d75-e0880cf09dc4
**Successful after Failed Flow**
https://github.com/user-attachments/assets/1eea1d6d-1222-45b8-8ebe-ed1edee3ce28

feat(payment): PAYPAL-4591 added 3ds check

---

packages/paypal-commerce-integration/src/paypal-commerce-credit-card/paypal-commerce-credit-cards-payment-strategy.spec.ts
packages/paypal-commerce-integration/src/paypal-commerce-credit-card/paypal-commerce-credit-cards-payment-strategy.ts
packages/paypal-commerce-integration/src/paypal-commerce-types.ts

Reverts bigcommerce/checkout-sdk-js#2654

Revert "feat(payment): PAYPAL-4591 added 3ds check"

---

packages/hosted-form-v2/src/hosted-field-type.ts
packages/hosted-form-v2/src/hosted-form-options.ts
packages/hosted-form-v2/src/iframe-content/hosted-input-validate-error-data.ts
packages/hosted-form-v2/src/iframe-content/hosted-input-validator.spec.ts
packages/hosted-form-v2/src/iframe-content/hosted-input-validator.ts
packages/hosted-form-v2/src/iframe-content/hosted-input-values.ts
packages/hosted-form-v2/src/iframe-content/hosted-input.spec.ts
packages/hosted-form-v2/src/iframe-content/hosted-input.ts
packages/hosted-form-v2/src/iframe-content/map-to-accessibility-label.ts
packages/hosted-form-v2/src/payment/Instrument.ts
packages/hosted-form-v2/src/payment/manual-order-payment-request-sender.ts

Add new HostedFieldType, `Note`.
Using manual payment in the new manual order UI.
https://github.com/user-attachments/assets/154eb17a-241e-419c-a69f-5f8eaeab4af0

feat(checkout): CHECKOUT-8606 Add Note HostedFiledType

---

packages/payment-integrations-test-utils/src/index.ts
packages/payment-integrations-test-utils/src/test-utils/index.ts
packages/stripe-integration/src/stripe-upe/stripe-upe-customer-strategy.spec.ts
packages/stripe-integration/src/stripe-upe/stripe-upe-customer.mock.ts
packages/stripe-integration/src/stripe-upe/stripe-upe-payment-strategy.spec.ts
packages/stripe-integration/src/stripe-upe/stripe-upe.mock.ts
packages/stripe-integration/src/stripev3/stripev3-payment-strategy.spec.ts
packages/stripe-integration/src/stripev3/stripev3.mock.ts

Types correction in Stripe spec files

feat(payment): STRIPE-473 types correction in Stripe spec files

---

packages/adyen-integration/.eslintrc.json
packages/adyen-utils/.eslintrc.json
packages/adyen-utils/src/adyenv3/adyenv3-script-loader.spec.ts
packages/cybersource-integration/.eslintrc.json
packages/humm-integration/.eslintrc.json
packages/klarna-integration/.eslintrc.json
packages/legacy-integration/.eslintrc.json
packages/payment-integrations-test-utils/src/test-utils/payment-integration-service.mock.ts

Clenup legacy integration spec error

refactor(checkout): PI-2691 clenup lagacy integration spec error

---

packages/affirm-integration/src/affirm-payment-strategy.spec.ts
packages/affirm-integration/src/affirm-payment-strategy.ts

Reverts bigcommerce/checkout-sdk-js#2688

Revert "fix(payment): PI-1647 [Affirm] When returning to a cart with digital …"

---

packages/affirm-integration/src/affirm-payment-strategy.spec.ts
packages/affirm-integration/src/affirm-payment-strategy.ts

Reverts bigcommerce/checkout-sdk-js#2708

Revert "Revert "fix(payment): PI-1647 [Affirm] When returning to a cart with digital …""

---

packages/google-pay-integration/.eslintrc.json
packages/google-pay-integration/src/gateways/google-pay-adyenv2-gateway.spec.ts
packages/google-pay-integration/src/gateways/google-pay-adyenv3-gateway.spec.ts
packages/google-pay-integration/src/gateways/google-pay-checkoutcom-gateway.spec.ts
packages/google-pay-integration/src/gateways/google-pay-cybersource-gateway.spec.ts
packages/google-pay-integration/src/gateways/google-pay-gateway.spec.ts
packages/google-pay-integration/src/google-pay-button-strategy.spec.ts
packages/google-pay-integration/src/google-pay-customer-strategy.spec.ts
packages/google-pay-integration/src/google-pay-payment-processor.spec.ts
packages/google-pay-integration/src/google-pay-payment-strategy.spec.ts
packages/google-pay-integration/src/google-pay-paypal-commerce/google-pay-paypal-commerce-gateway.spec.ts
packages/google-pay-integration/src/google-pay-paypal-commerce/google-pay-paypal-commerce-payment-strategy.spec.ts
packages/google-pay-integration/src/guards/is-google-pay-td-online-mart-additional-action.spec.ts
packages/google-pay-integration/src/mocks/google-pay-processor-initialize.mock.ts
packages/google-pay-integration/src/mocks/google-pay.mock.ts

Clenup GPay integration package spec errors

refactor(checkout): PI-2688 clenup GPay integration package spec errors

---

packages/braintree-integration/src/braintree-ach/braintree-ach-payment-strategy.spec.ts

Added tests for braintree-ach
For test coverage
Before
After

chore(payment): PAYPAL-00 Added tests for braintree-ach

---

packages/clearpay-integration/jest.config.js
packages/clearpay-integration/src/clearpay-script-loader.spec.ts
packages/cybersource-integration/src/cybersource/cybersource-payment-strategy.spec.ts
packages/cybersource-integration/src/cybersourcev2/cybersourcev2-payment-strategy.spec.ts
packages/klarna-integration/jest.config.js
packages/klarna-integration/src/klarnav2/klarnav2-token-updater.spec.ts
packages/klarna-integration/src/klarnav2/klarnav2-token-updater.ts

Fixed test coverage for Cybersource, Clearpay
Due to the wrong config, and absence of the some covered conditions
ci

chore(payment): PI-0 fixed test coverage for cybersource, clearpay

---

packages/core/src/common/dom/set-unique-element-id.spec.ts
packages/core/src/common/dom/set-unique-element-id.ts

ID creation updates
To avoid situation with duplicate buttons
Before
https://github.com/user-attachments/assets/8ad663a5-4f43-43b4-9d7d-262ebdf4a7b2
After
https://github.com/user-attachments/assets/ae586c9e-366a-4857-b837-8030a2371019

feat(payment): PAYPAL-5067 ID creation updates

---

packages/braintree-utils/jest.config.js
packages/braintree-utils/src/braintree-integration-service.spec.ts
packages/braintree-utils/src/map-to-legacy-billing-address.spec.ts
packages/braintree-utils/src/map-to-legacy-shipping-address.spec.ts
packages/braintree-utils/src/utils/get-fastlane-styles.spec.ts
packages/braintree-utils/src/utils/is-braintree-accelerated-checkout-customer.spec.ts

Added test coverage for braintree-utils
To increase test coverage

feat(payment): PAYPAL-5113 added test coverage for braintree-utils

---

packages/apple-pay-integration/src/apple-pay-script-loader.spec.ts
packages/apple-pay-integration/src/apple-pay-script-loader.ts

Removed integrity attribute because of dynamic script
To avoid integrity error
Local testing

feat(payment): PAYPAL-0 Removed integrity attribute because of dynamic script

---

packages/braintree-integration/src/braintree-paypal/braintree-paypal-customer-strategy.spec.ts
packages/braintree-integration/src/braintree-paypal/braintree-paypal-customer-strategy.ts
packages/google-pay-integration/src/gateways/google-pay-braintree-gateway.spec.ts
packages/google-pay-integration/src/gateways/google-pay-braintree-gateway.ts

Updates related to clientToken checking
To fix an issue with disappearing of PayPal Wallet Buttons on Checkout Page
https://github.com/user-attachments/assets/cc64df55-b445-4751-b4ab-55ceac17c723

feat(payment): PAYPAL-5201 PayPal Wallet Buttons Disappearing on Checkout 

---

packages/paypal-commerce-integration/src/paypal-commerce-script-loader.ts

Made PPCP Venmo button appear on cart page
Since the button does not renders on the page when PPCP PayNow feature is enabled
Manual tests
Unit tests

fix(payment): PAYPAL-5286 made PPCP Venmo button appear on cart page

---

packages/core/src/config/config.ts
packages/core/src/config/configs.mock.ts
packages/payment-integration-api/src/config/config.ts
packages/payment-integration-api/src/mocks/config.mock.ts
packages/payment-integrations-test-utils/src/test-utils/config.mock.ts

Add shouldRedirectToStorefrontLoginPage property to config interface
Add shouldRedirectToStorefrontLoginPage property to config interface, in order keep parity with the API
- CI

chore(checkout): CHECKOUT-9138 Add shouldRedirectToStorefrontLoginPage property to config interface

---

packages/core/src/config/config.ts
packages/core/src/config/configs.mock.ts
packages/payment-integration-api/src/config/config.ts
packages/payment-integration-api/src/mocks/config.mock.ts
packages/payment-integrations-test-utils/src/test-utils/config.mock.ts

Rename shouldRedirectToStorefrontLoginPage to shouldRedirectToStorefrontForAuth
To use for login and logout

feat(checkout): CHECKOUT-9138 Rename shouldRedirectToStorefrontLoginPage

---

packages/braintree-integration/src/braintree-fastlane/braintree-fastlane-payment-initialize-options.ts
packages/braintree-integration/src/braintree-fastlane/braintree-fastlane-payment-strategy.spec.ts
packages/braintree-integration/src/braintree-fastlane/braintree-fastlane-payment-strategy.ts
packages/braintree-integration/src/braintree-fastlane/braintree-fastlane-utils.ts
packages/braintree-integration/src/braintree-fastlane/create-braintree-fastlane-payment-strategy.ts
packages/braintree-integration/src/mocks/braintree.mock.ts
packages/braintree-utils/src/mocks/braintree-modules.mock.ts
packages/braintree-utils/src/types.ts

Added 3ds for BT FL
To be able to use 3ds for BT FL
**Fastlane Guest**
https://github.com/user-attachments/assets/6906b1fc-599e-4625-8088-914a229f275d
https://github.com/user-attachments/assets/7403c946-ac92-4e0b-90bc-df3caceb589a
**`3DS OFF`**
https://github.com/user-attachments/assets/9dddeded-c174-4dda-9eab-aa631f46e4cc
**Fastlane User**
https://github.com/user-attachments/assets/1b130065-6902-43be-8fbd-2bde225d9ab3
https://github.com/user-attachments/assets/267bc595-e147-4f14-acfc-88068d1a7b79

feat(payment): PAYPAL-5197 added 3ds verification for BT FL

---

.github/CODEOWNERS
packages/core/src/shipping/shipping-request-options.ts
packages/core/src/shipping/strategies/bigcommerce-payments/bigcommerce-payments-fastlane-shipping-initialization-options.ts
packages/core/src/shipping/strategies/bigcommerce-payments/bigcommerce-payments-fastlane-shipping-strategy.spec.ts
packages/core/src/shipping/strategies/bigcommerce-payments/bigcommerce-payments-fastlane-shipping-strategy.ts
packages/core/src/shipping/strategies/bigcommerce-payments/index.ts

This PR is clone the paypal-commerce-fastlane-shipping strategy, to a new payment provider bigcommerce-payments-integration. The changes include:
- Cloned existing paypal-commerce-fastlane-shipping strategy related files
- Updated all relevant file names and internal references to reflect the new payment provider (bigcommerce-payments).
These changes lay the base for further customization and integration of bigcommerce-payments into the payment flow.
To create separate package for BCP (bigcommerce payments) features
unit tests

feature(payment): clone paypal-commerce-fastlane-shipping strategy

---

packages/google-pay-integration/src/google-pay-payment-initialize-options.ts
packages/google-pay-integration/src/google-pay-stripe/create-google-pay-stripe-button-strategy.ts
packages/google-pay-integration/src/google-pay-stripe/create-google-pay-stripe-customer-strategy.ts
packages/google-pay-integration/src/google-pay-stripe/create-google-pay-stripe-payment-strategy.ts

Added Stripe OCS Google pay
Related PR:
https://github.com/bigcommerce/checkout-js/pull/2363
Customer step:
https://github.com/user-attachments/assets/5cddc6ba-6d77-4604-b0f3-0aeeb0acaaf6
PDP page:
https://github.com/user-attachments/assets/8cffe314-950c-458f-b4a9-912e88352bb4
Manual testing

feat(payment): Stripe OCS Google Pay added

---

packages/core/src/extension/extension.ts

Add a new extension region above the payment method list.
Improve extension capability.
CI.

feat(checkout): CHECKOUT-9322 Add New Extension Region

---

packages/core/src/extension/extension-commands.ts

Introduce a new checkout extension command.
To support the force re-rendering of the shipping step.
CI.

feat(extension): Introduce ReRenderShippingStep Command

---

packages/bigcommerce-payments-integration/src/bigcommerce-payments-paylater/bigcommerce-payments-paylater-payment-strategy.spec.ts
packages/bigcommerce-payments-integration/src/bigcommerce-payments-paylater/bigcommerce-payments-paylater-payment-strategy.ts
packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-payment-strategy.spec.ts
packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-payment-strategy.ts
packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-payment-strategy.spec.ts
packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-payment-strategy.ts

Added banner additional check
To fix Sentry issue 
Manual testing

feat(payment): added banner additional check

---

packages/paypal-commerce-integration/src/paypal-commerce-fastlane/paypal-commerce-fastlane-payment-strategy.spec.ts
packages/paypal-commerce-integration/src/paypal-commerce-fastlane/paypal-commerce-fastlane-payment-strategy.ts
packages/paypal-commerce-utils/src/utils/is-paypal-fastlane-request-error.spec.ts
packages/paypal-commerce-utils/src/utils/is-paypal-fastlane-request-error.ts

Fixed PPCP FL Request Error Message
To display user friendly message
https://github.com/user-attachments/assets/b978036d-1702-453f-9c6f-47e66bfc2850

fix(payment): Fix ppcp fl request error message

---

packages/bigcommerce-payments-integration/src/bigcommerce-payments-fastlane/bigcommerce-payments-fastlane-payment-strategy.ts
packages/bigcommerce-payments-utils/src/bigcommerce-payments-types.ts

Fixed threeDSVerification method assignment
To make 3ds work properly
Unit Tests

fix(payment): Fix threeDSVerification method assignment

---

packages/bigcommerce-payments-integration/src/bigcommerce-payments/bigcommerce-payments-payment-strategy.ts
packages/payment-integration-api/src/payment/instrument.ts
packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-payment-strategy.ts
packages/td-bank-integration/src/td-online-mart-payment-strategy.ts
packages/utility/src/index.ts
packages/utility/src/is-base-instrument/is-base-instrument.spec.ts
packages/utility/src/is-base-instrument/is-base-instrument.ts

Changed PaymentInstrument interface
To increase Payment instrument types coverage
Unit tests

feat(payment): Changed PaymentInstrument interface

---

packages/core/src/customer/customer-action-creator.spec.ts
packages/core/src/customer/customer-action-creator.ts
packages/core/src/customer/customer-credentials.ts
packages/core/src/customer/customer-request-sender.spec.ts
packages/core/src/customer/customer-request-sender.ts

Pass cart id in payload to sign in and sign out for customer
Pass cart id in payload for sign and sign out customer requests if the cart is buy now.
- CI

feat(customer): CHECKOUT-9403 Pass cart id in payload to sign in and sign out for customer

---

package-lock.json
package.json

See https://github.com/bigcommerce/data-store-js/pull/79
Revert
CircleCI

CHECKOUT-9450: Upgrade data-store to make it compatible with es6

---

packages/braintree-integration/src/braintree-credit-card/braintree-credit-card-payment-strategy.ts

The issue: Some customers attempting to pay through Braintree see error message "Unable to submit payment for the order because the payload is invalid. Make sure the following fields are provided correctly: instrumentId."
Fix: updated BT Credit Card Error Handling since it was set up incorrectly and did not cover all error cases properly
Revert
Before
https://github.com/user-attachments/assets/fafca7d3-2e92-4cd8-a513-8d1e2b5eee17
After
https://github.com/user-attachments/assets/cc69a182-9187-4583-9da4-55e68dab6554

feat(payment): PAYPAL-5730 BT Credit Card Error Handling Fix

---

packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-payment-strategy.ts
packages/paypal-commerce-integration/src/paypal-commerce-venmo/paypal-commerce-venmo-payment-strategy.ts
packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-payment-strategy.ts

Fix problem with payment validation in case when 'term and conditions' is a required field.
Revert
Before
https://github.com/user-attachments/assets/52f459b4-91ff-44bf-8111-c4d60d3511c3
After
https://github.com/user-attachments/assets/7e932a0e-652c-47bd-bd05-fc5e61c09ecf

feat(payment): PAYPAL-0 fix validation flow pp payment strategies
