bigcommerce/checkout-sdk-js

- src/checkout-button.ts
- src/checkout-buttons/strategies/braintree-paypal-button-options.ts
- src/checkout-buttons/strategies/braintree-paypal-button-strategy.spec.ts
- src/checkout-buttons/strategies/braintree-paypal-button-strategy.ts
* Process payment if `shouldProcessPayment` flag is passed. This is marked as `internal` because it is never intended to be used by external parties. It is only needed to support legacy checkout flow.
* Mark `CheckoutButtonInitializer` as `alpha` so that it is clear it is not ready for public consumption yet.
* Please see "what".
* Unit
> CHECKOUT-3011: Allow PayPal checkout button to process payment

- src/checkout-buttons/checkout-button-actions.ts
- src/checkout-buttons/checkout-button-initializer.spec.ts
- src/checkout-buttons/checkout-button-strategy-action-creator.spec.ts
- src/checkout-buttons/checkout-button-strategy-action-creator.ts
- src/checkout-buttons/create-checkout-button-initializer.ts
- src/checkout-buttons/create-checkout-button-registry.ts
- src/checkout-buttons/strategies/braintree-paypal-button-strategy.spec.ts
- src/checkout-buttons/strategies/braintree-paypal-button-strategy.ts
* For the Braintree PayPal button, load the default checkout object only when it is required.
* Previously, we load the checkout object before we render the button. However, we actually don't need the information until the shopper clicks on button and tries to check out.
* Unit
> CHECKOUT-3011: Load checkout object only when required

- src/order/order-action-creator.spec.js
- src/order/order-action-creator.ts
- src/payment/payment-strategy-action-creator.spec.ts
- src/payment/payment-strategy-action-creator.ts
1. Stop loading current order before executing payment strategy.
2. Directly pass `checkout.orderId` to load `order.payments` instead of trying to retrieve the value again.
1. We don't have to load the current order to get payment statuses. If the current checkout hasn't been converted into an order, payment status information is available in the checkout object. We could potentially run into an issue if we try load the order because `checkout.orderId` might not be the latest one (it could be invalidated if you try to check out using a different window). Instead, we only need to load the current order for the finalisation step.
2. We should always use the `orderId` from the checkout object when we finalise the order.
* Unit
> CHECKOUT-3401: Stop loading current order before executing payment strategy

- src/checkout/checkout-action-creator.spec.ts
- src/checkout/checkout-action-creator.ts
- src/common/error/index.ts
- src/common/error/throw-error-action.ts
- src/customer/customer-action-creator.spec.js
- src/customer/customer-action-creator.ts
- src/customer/customer-actions.ts
- src/order/order-action-creator.spec.js
- src/order/order-action-creator.ts
- src/order/order-actions.ts
- src/payment/payment-action-creator.spec.ts
- src/payment/payment-action-creator.ts
- src/payment/payment-actions.ts
- src/payment/payment-strategy-action-creator.spec.ts
- src/payment/payment-strategy-action-creator.ts
- src/payment/payment-strategy-actions.ts
- src/shipping/strategies/default-shipping-strategy.spec.ts
Emit the start of an asynchronous action as soon as it begins; and emit the end of it as soon as it ends.
Some asynchronous actions trigger other actions in order to complete. For example, previously, we emit the sub-actions in this order:
```
SIGN_IN_CUSTOMER_REQUESTED
SIGN_IN_CUSTOMER_SUCCEEDED
LOAD_CHECKOUT_REQUESTED
LOAD_CHECKOUT_SUCCEEDED
```
This means that the sign-in action could be marked as complete even though it could still be waiting for the checkout object to load. Instead, what we want is the following order:
```
SIGN_IN_CUSTOMER_REQUESTED
LOAD_CHECKOUT_REQUESTED
LOAD_CHECKOUT_SUCCEEDED
SIGN_IN_CUSTOMER_SUCCEEDED
```
This order ensures that `CheckoutStoreStatusSelector#isSigningIn` method returns the correct statuses while signing in.
* Unit …
> CHECKOUT-3449: Return correct status flags for actions that trigger other sub-actions

- src/checkout/checkout-client.spec.js
- src/checkout/checkout-client.ts
- src/checkout/checkout-service.spec.js
- src/checkout/create-checkout-client.ts
- src/checkout/create-checkout-service.ts
- src/customer/create-customer-strategy-registry.ts
- src/customer/customer-strategy-action-creator.spec.ts
- src/customer/strategies/amazon-pay-customer-strategy.spec.ts
- src/customer/strategies/braintree-visacheckout-customer-strategy.spec.ts
- src/customer/strategies/chasepay-customer-strategy.spec.ts
- src/payment/create-payment-strategy-registry.ts
- src/payment/payment-method-action-creator.spec.ts
- src/payment/payment-method-action-creator.ts
- src/payment/strategies/afterpay/afterpay-payment-strategy.spec.ts
- src/payment/strategies/braintree/braintree-credit-card-payment-strategy.spec.ts
- src/payment/strategies/braintree/braintree-visacheckout-payment-strategy.spec.ts
- src/payment/strategies/klarna/klarna-payment-strategy.spec.ts
- src/shipping/create-shipping-strategy-registry.ts
- src/shipping/shipping-strategy-action-creator.spec.ts
- src/shipping/strategies/amazon-pay-shipping-strategy.spec.ts
* Use `PaymentMethodRequestSender` directly to send requests related to payment methods.
* `CheckoutClient` is deprecated.
* Unit
> CHECKOUT-3457: Use `PaymentMethodRequestSender` directly to send requests

- package-lock.json
- package.json
* Update dependencies to remove Node requirement
* To address #377 
* Manual
> CHECKOUT-346:2 Update dependencies to remove Node requirement

- src/order/order-action-creator.spec.js
- src/order/order-action-creator.ts
- src/order/order-reducer.spec.js
- src/order/order-reducer.ts
* After order creation, use the order ID from the response to reload the current order using storefront API.
* Remove the reset after order submission because it's not needed anymore.
* Previously, we call `loadCurrentOrder`, using the store cache to determine the current order ID in order to reload the object using storefront API. However, since #376, we don't cache the order object until after reloading the order object. Therefore, we need to get the order ID from the submission response instead.
* We only need to reset the order (#327) if order rehydration happens after order submission. Now it's no longer the case so we don't need to the reset anymore.
* Unit
> CHECKOUT-3449: Use correct order ID when reloading current order after order creation

- src/cart/internal-carts.mock.ts
- src/cart/internal-line-item.ts
- src/cart/line-item.ts
- src/cart/line-items.mock.ts
- src/cart/map-to-internal-line-item.ts
- src/order/internal-orders.mock.ts
Add `addedByPromotion` to lineItems
https://github.com/bigcommerce/bigcommerce/pull/26000
> CHECKOUT-3493 Add `addedByPromotion` property to line items

- src/payment/strategies/index.ts
- src/payment/strategies/paypal/index.ts
- src/payment/strategies/paypal/paypal-express-payment-strategy.spec.ts
- src/payment/strategies/paypal/paypal-express-payment-strategy.ts
- src/payment/strategies/paypal/paypal-pro-payment-strategy.spec.ts
- src/payment/strategies/paypal/paypal-pro-payment-strategy.ts
* Move Paypal related strategies to Paypal folder
* Better organisation
* Unit
> CHECKOUT-3011: Move Paypal related strategies to Paypal folder

- src/billing/billing-address-action-creator.spec.ts
- src/billing/billing-address-action-creator.ts
- src/billing/billing-address-actions.ts
- src/billing/billing-address-reducer.ts
- src/billing/billing-address-selector.spec.js
- src/billing/billing-address-selector.ts
- src/billing/billing-address-state.ts
- src/billing/billing-address.ts
- src/billing/index.ts
- src/checkout/checkout-service.spec.js
- src/checkout/checkout-service.ts
- src/checkout/checkout-store-error-selector.spec.js
- src/checkout/checkout-store-error-selector.ts
- src/checkout/checkout-store-status-selector.spec.js
- src/checkout/checkout-store-status-selector.ts
- Add status/error selectors for `CheckutService#continueAsGuest`
- Update `CheckutService#continueAsGuest` signature
- Do not overwrite billing info when using `CheckutService#continueAsGuest`
> Billing Address enhancements

- src/payment/strategies/amazon-pay/amazon-pay-address-book.ts
- src/payment/strategies/amazon-pay/amazon-pay-payment-strategy.spec.ts
- src/payment/strategies/amazon-pay/amazon-pay-payment-strategy.ts
- src/payment/strategies/amazon-pay/amazon-pay-wallet.ts
- src/shipping/strategies/amazon-pay-shipping-strategy.spec.ts
- src/shipping/strategies/amazon-pay-shipping-strategy.ts
* Trigger `onReady` callback after order reference is passed to BC.
* Stop passing `onOrderReferenceCreate` because `onReady` has access to the same data.
* Otherwise, `onReady` callback and `initialize` method will not be resolved at the right moment.
* Unit
> CHECKOUT-3516: Trigger `onReady` callback after order reference is passed to BC

- src/checkout-buttons/strategies/braintree-paypal-button-options.ts
- src/checkout-buttons/strategies/braintree-paypal-button-strategy.spec.ts
- src/checkout-buttons/strategies/braintree-paypal-button-strategy.ts
- src/payment/strategies/paypal/paypal-sdk.ts
Add support for styling options and some funding sources to the Braintree/Paypal checkout button strategy.
First part of enabling merchants to be able to customize those properties.
Unit tested.
> feat(checkout-button): PAYMENTS-3071 Support more features of paypal checkout buttons

- src/payment/strategies/braintree/braintree-sdk-creator.spec.ts
- src/payment/strategies/braintree/braintree-sdk-creator.ts
- src/payment/strategies/braintree/braintree.mock.ts
Device data is not being sent as expected when checkout with PayPal, I have removed the transformation applied to the data collector in the getDataCollector method.
The `device_info` part of the deviceData should be sent as it is.
Before:
After:
> fix(payment) PAYMENTS-3288 Checking out with PayPal does not send device data

- src/cart/internal-carts.mock.ts
- src/cart/internal-line-item.ts
- src/cart/map-to-internal-line-item.ts
- src/order/internal-orders.mock.ts
Added the ProductId as one of the properties to the `internal line item` to have the ProductId as part of the checkout payload while sending the checkout started event to GA.
Checkout started event does not have the product id as part of payload. So, we need to add this to the original cart items. 
@bigcommerce/checkout @bigcommerce/cp-dt
> CP-3982 adding product-id to the cart item property for checkout process

- src/customer/create-customer-strategy-registry.ts
- src/customer/strategies/index.ts
- src/customer/strategies/square-customer-strategy.spec.ts
- src/customer/strategies/square-customer-strategy.ts
- src/payment/create-payment-strategy-registry.ts
- src/payment/index.ts
- src/payment/payment-methods.mock.ts
- src/payment/strategies/square/index.ts
- src/payment/strategies/square/square-form.ts
- src/payment/strategies/square/square-payment-initialize-options.ts
- src/payment/strategies/square/square-payment-strategy-mock.ts
- src/payment/strategies/square/square-payment-strategy.spec.ts
- src/payment/strategies/square/square-payment-strategy.ts
[INT-751](https://jira.bigcommerce.com/browse/INT-751)
- MasterPass button is displayed in the Square Form in the UCO page
- When the shopper clicks on the MasterPass button the MasterPass box is opened and the shopper can select a credit card
As a Shopper when Masterpass is enabled on Square I want to be able to use the MasterPass button to open the Master Pass box to select a credit card from my wallet
Dependency with PR for [INT-752](https://github.com/bigcommerce/bigcommerce/pull/25547) BCApp changes: 
[Cart](https://drive.google.com/drive/u/0/folders/1_CYuz2HMWpQlbq1N2saG3IemueRusaHd)
[`ng-checkout`](https://github.com/bigcommerce-labs/ng-checkout/pull/893)
> feat(payment): INT-751 Show Masterpass button in payments section into square form

- src/common/error/errors/missing-data-error.ts
- src/customer/customer-request-options.ts
- src/customer/strategies/chasepay-customer-strategy.spec.ts
- src/customer/strategies/chasepay-customer-strategy.ts
- src/payment/create-payment-strategy-registry.ts
- src/payment/payment-action-creator.ts
- src/payment/payment-request-options.ts
- src/payment/payment.ts
- src/payment/strategies/chasepay/chasepay-initialize-options.ts
- src/payment/strategies/chasepay/chasepay-payment-strategy.spec.ts
- src/payment/strategies/chasepay/chasepay-payment-strategy.ts
- src/payment/strategies/chasepay/chasepay.mock.ts
- src/payment/strategies/chasepay/chasepay.ts
- src/payment/strategies/chasepay/index.ts
- src/payment/strategies/index.ts
Extend full Chase Pay support to Checkout SDK
So that partners building custom checkout implementations can utilize  Chase Pay.
For bicommerce: [PR#26067](https://github.com/bigcommerce/bigcommerce/pull/26067)
For `ng-checkout`: [PR#914](https://github.com/bigcommerce-labs/ng-checkout/pull/914)
@bigcommerce/checkout @bigcommerce/payments @bigcommerce/integrations
> feat(payment): INT-616 Add Chase Pay wallet support

- src/customer/create-customer-strategy-registry.ts
- src/customer/customer-request-options.ts
- src/customer/strategies/chasepay-customer-strategy.spec.ts
- src/customer/strategies/index.ts
- src/customer/strategies/masterpass-customer-initialize-options.ts
- src/customer/strategies/masterpass-customer-strategy.spec.ts
- src/customer/strategies/masterpass-customer-strategy.ts
- src/payment/payment-methods.mock.ts
- src/payment/strategies/masterpass/index.ts
- src/payment/strategies/masterpass/masterpass-script-loader.ts
- src/payment/strategies/masterpass/masterpass.mock.ts
- src/payment/strategies/masterpass/masterpass.ts
[INT-775](https://jira.bigcommerce.com/browse/INT-775)
https://github.com/bigcommerce-labs/ng-checkout/pull/927
Add Masterpass button to the customer section on checkout
When Masterpass is enabled on Stripe, Masterpass button can be used from Customer section of checkout page.
@bigcommerce/checkout @bigcommerce/payments @bigcommerce/integrations
> feat(checkout): INT-775 Implement Masterpass button in customer section

- src/payment/strategies/offsite-payment-strategy.spec.ts
- src/payment/strategies/offsite-payment-strategy.ts
Add a check to pull correct data for CCAvenue MARS offsite payments.
Without this BigPay does not receive a value for `returnUrl` when processing the offsite initialization request.
Manual testing to verify successful payment initialization.
> feat(payments): INT-685 Correctly set up CCAvenue MARS return URL

- src/embedded-checkout/embedded-checkout-events.ts
- src/embedded-checkout/embedded-checkout-options.ts
- src/embedded-checkout/embedded-checkout.spec.ts
- src/embedded-checkout/embedded-checkout.ts
- src/embedded-checkout/iframe-content/embedded-checkout-messenger.spec.ts
- src/embedded-checkout/iframe-content/embedded-checkout-messenger.ts
- src/embedded-checkout/is-embedded-checkout-event.ts
- src/embedded-checkout/resizable-iframe-creator.spec.ts
- src/embedded-checkout/resizable-iframe-creator.ts
* Emit an error event if unable to embed the checkout form as an iframe.
* So you can catch and handle the error in case you can't embed the iframe for whatever reason. i.e.:
```ts
embedCheckout(config)
.catch(error => {
window.alert(error.message);
window.location.assign('/cart');
});
```
* Because most likely the iframe will be embedded across domains, so you can't listen for error events from the parent frame. Instead, you need to rely on the child frame to tell the parent frame when the checkout form cannot be loaded.
* Unit
> CHECKOUT-3475: Emit `FRAME_ERROR` event if unable to embed checkout in iframe

- src/embedded-checkout/__snapshots__/loading-indicator.spec.ts.snap
- src/embedded-checkout/embed-checkout.spec.ts
- src/embedded-checkout/embed-checkout.ts
- src/embedded-checkout/embedded-checkout-styles.ts
- src/embedded-checkout/embedded-checkout.spec.ts
- src/embedded-checkout/embedded-checkout.ts
- src/embedded-checkout/iframe-event-poster.ts
- src/embedded-checkout/loading-indicator.spec.ts
- src/embedded-checkout/loading-indicator.ts
1. Show a loading indicator while waiting for the iframe to load.
1. Reconfigure the iframe with styling information if it's reloaded again.
1. To tell the shopper that something is happening in the background.
2. Otherwise, we'd lose the styling configuration.
Unit
> CHECKOUT-3477: Show loading indicator while waiting for iframe to load

- src/embedded-checkout/iframe-content/create-embedded-checkout-messenger.spec.ts
- src/embedded-checkout/iframe-content/create-embedded-checkout-messenger.ts
- src/embedded-checkout/iframe-content/embedded-checkout-messenger-options.ts
- src/embedded-checkout/iframe-content/embedded-checkout-messenger.ts
- src/embedded-checkout/iframe-content/iframe-embedded-checkout-messenger.spec.ts
- src/embedded-checkout/iframe-content/iframe-embedded-checkout-messenger.ts
- src/embedded-checkout/iframe-content/noop-embedded-checkout-messenger.ts
* Return `NoopEmbeddedCheckoutMessenger` if `createEmbeddedCheckoutMessenger()` is not called inside an iframe.
* So it doesn't do anything if it's not used an iframe. Otherwise, we need to wrap every call inside an `if` statement.
* To address this comment: https://github.com/bigcommerce/checkout-sdk-js/pull/428#discussion_r223244992
* Unit
> CHECKOUT-3660: Create no-op `EmbeddedCheckoutMessenger` if not inside iframe

- src/payment/create-payment-strategy-registry.spec.ts
- src/payment/create-payment-strategy-registry.ts
- src/payment/payment-methods.mock.ts
- src/payment/payment-request-options.ts
- src/payment/strategies/braintree/braintree-script-loader.spec.ts
- src/payment/strategies/braintree/braintree-script-loader.ts
- src/payment/strategies/braintree/braintree-sdk-creator.spec.ts
- src/payment/strategies/braintree/braintree-sdk-creator.ts
- src/payment/strategies/braintree/braintree.mock.ts
- src/payment/strategies/braintree/braintree.ts
- src/payment/strategies/googlepay/googlepay-braintree-initializer.spec.ts
- src/payment/strategies/googlepay/googlepay-braintree-initializer.ts
- src/payment/strategies/googlepay/googlepay-initialize-options.ts
- src/payment/strategies/googlepay/googlepay-payment-processor.spec.ts
- src/payment/strategies/googlepay/googlepay-payment-processor.ts
- src/payment/strategies/googlepay/googlepay-payment-strategy.spec.ts
- src/payment/strategies/googlepay/googlepay-payment-strategy.ts
- src/payment/strategies/googlepay/googlepay-script-loader.spec.ts
- src/payment/strategies/googlepay/googlepay-script-loader.ts
- src/payment/strategies/googlepay/googlepay.mock.ts
- src/payment/strategies/googlepay/googlepay.ts
- src/payment/strategies/googlepay/index.ts
- src/payment/strategies/index.ts
Support Google Pay as a Wallet implementing a strategy. Google Pay needs to work with Braintree configuration and load the proper files.
I want to be able to open the Google Pay Wallet, select a car and get a nonce from Google Pay using Braintree configuration and after that checkout using Google Pay as a Wallet and Braintree as a Provider.
Video: https://drive.google.com/open?id=12WrpSCazOym9DnrjA3tfVXPLW3F4YdE9
https://jira.bigcommerce.com/browse/INT-835
> INT-835 Implement Google Pay + Braintree in Payments Section

- src/checkout/checkout-service.spec.js
- src/checkout/checkout-service.ts
- src/shipping/consignment-action-creator.spec.ts
- src/shipping/consignment-action-creator.ts
Allow method `CheckoutService#assignItemsToAddress` to take negative quantities or empty payloads.
So items can be un-assigned from addresses.
unit
manual
> CHECKOUT-3589 Allow un-assigning items from address

- src/checkout-buttons/checkout-button-options.ts
- src/checkout-buttons/create-checkout-button-registry.ts
- src/checkout-buttons/index.ts
- src/checkout-buttons/strategies/index.ts
- src/checkout-buttons/strategies/masterpass-button-options.ts
- src/checkout-buttons/strategies/masterpass-button-strategy.spec.ts
- src/checkout-buttons/strategies/masterpass-button-strategy.ts
- src/customer/strategies/masterpass-customer-strategy.ts
- src/payment/strategies/masterpass/masterpass-payment-strategy.ts
Create checkout-buttons masterpass strategy
&
Hide the shipping address in the customer section as requested in [INT-984](https://jira.bigcommerce.com/browse/INT-984)
We need this strategy to implement the cart and quick cart buttons for Masterpass
Due the delivery dates i made only one PR in order to simplify the process
> feat(checkout): INT-951 Implement Masterpass button in cart and quick

- webpack.config.js
* Prevent Lodash from leaking to the global scope.
* It's a side effect we want to avoid.
* Manual
> CHECKOUT-3688: Prevent Lodash from leaking to global scope

- src/embedded-checkout/iframe-event-listener.spec.ts
- src/embedded-checkout/iframe-event-listener.ts
- src/embedded-checkout/iframe-event-poster.spec.ts
- src/embedded-checkout/iframe-event-poster.ts
* When checking if `message` event comes from the expected origin, make sure the configured origin URL is without a trailing slash or other irrelevant information. 
* Otherwise, we'll ignore messages coming from `https://bc.wordpress.com` if the origin is configured to be `https://bc.wordpress.com/`.
* Unit
> CHECKOUT-3695: Ignore trailing slash and other irrelevant information when comparing event origin

- src/checkout-buttons/strategies/braintree-paypal-button-options.ts
- src/checkout-buttons/strategies/braintree-paypal-button-strategy.spec.ts
- src/checkout-buttons/strategies/braintree-paypal-button-strategy.ts
- src/payment/strategies/paypal/paypal-express-payment-strategy.spec.ts
- src/payment/strategies/paypal/paypal-sdk.ts
- src/payment/strategies/paypal/paypal.mock.ts
Support credit buttons by implementing funding sources.
Removes the need to have two separate strategies (to be removed later) to support credit buttons--it's just an option to the Braintree and Paypal button SDKs.
Add a product to your cart, open the cart page, see that with credit enabled you get two side-by-side (by default, changeable with Smart Buttons) buttons. With credit disabled, you get the standard braintree/paypal button.
> feat(checkout-buttons): PAYMENTS-3073 Support credit buttons by implementing funding sources

- src/cart/internal-carts.mock.ts
- src/cart/internal-line-item.ts
- src/cart/line-item.ts
- src/cart/line-items.mock.ts
- src/cart/map-to-internal-line-item.ts
- src/checkout/checkout-params.ts
- src/checkout/checkout-service.ts
- src/order/internal-orders.mock.ts
- src/shipping/consignment-action-creator.ts
Add Product Category information to Checkout payload.
Product category information is currently missing the in the checkout payload of all the line items. By this implementation, we will have the Prodcut category list of the given product in the checkout process. 
@bigcommerce/checkout @davidchin @lord2800
> CP-4020 Added Product Category to cart & checkout payload

- src/checkout-buttons/checkout-button-options.ts
- src/checkout-buttons/create-checkout-button-registry.ts
- src/checkout-buttons/strategies/braintree-paypal-button-strategy.spec.ts
- src/checkout-buttons/strategies/checkout-button-method-type.ts
- src/checkout-buttons/strategies/index.ts
- src/checkout-buttons/strategies/paypal-button-options.ts
- src/checkout-buttons/strategies/paypal-button-strategy.spec.ts
- src/checkout-buttons/strategies/paypal-button-strategy.ts
- src/payment/payment-methods.mock.ts
- src/payment/strategies/paypal/paypal-sdk.ts
Add support for the latest PayPal checkout button SDK.
Enables the use of smart buttons for payment options.
With a store that has PayPal Express enabled as a payment method, add an item to the cart via the quick view modal and observe that your buttons are customizable in the theme editor. Additionally, those same customizations apply to the cart page. Finally, you should be able to complete an order via all three flows: paypal button from the quick view modal, paypal button from the cart page, paypal payment option from the checkout page.
Also includes unit tests.
> feat(payment): PAYMENTS-3071 Support the Paypal checkout button strategy for smart buttons

- src/checkout-buttons/checkout-button-options.ts
- src/checkout-buttons/create-checkout-button-registry.ts
- src/checkout-buttons/strategies/checkout-button-method-type.ts
- src/checkout-buttons/strategies/googlepay/googlepay-button-options.ts
- src/checkout-buttons/strategies/googlepay/googlepay-button-strategy.ts
- src/checkout-buttons/strategies/googlepay/googlepay-button.mock.ts
- src/checkout-buttons/strategies/googlepay/googlepay-stripe-button-strategy.spec.ts
- src/checkout-buttons/strategies/googlepay/index.ts
- src/checkout-buttons/strategies/index.ts
- src/customer/create-customer-strategy-registry.ts
- src/customer/strategies/googlepay/googlepay-customer-mock.ts
- src/customer/strategies/googlepay/googlepay-customer-strategy.ts
- src/customer/strategies/googlepay/googlepay-stripe-customer-strategy.spec.ts
- src/customer/strategies/googlepay/index.ts
- src/customer/strategies/index.ts
- src/payment/create-payment-strategy-registry.ts
- src/payment/payment-request-options.ts
- src/payment/strategies/googlepay/create-googlepay-payment-processor.ts
- src/payment/strategies/googlepay/googlepay-braintree-initializer.ts
- src/payment/strategies/googlepay/googlepay-payment-strategy.spec.ts
- src/payment/strategies/googlepay/googlepay-payment-strategy.ts
- src/payment/strategies/googlepay/googlepay-stripe-initializer.spec.ts
- src/payment/strategies/googlepay/googlepay-stripe-initializer.ts
- src/payment/strategies/googlepay/googlepay.mock.ts
- src/payment/strategies/googlepay/googlepay.ts
- src/payment/strategies/googlepay/index.ts
Support Google Pay as a Wallet implementing a strategy. Google Pay needs to work with Stripe configuration and load the proper files.
I want to be able to open the Google Pay Wallet, select a car and get a nonce from Google Pay using Stripe configuration and after that checkout using Google Pay as a Wallet and Stripe as a Provider.
[INT-856](https://jira.bigcommerce.com/browse/INT-856)
[INT-857](https://jira.bigcommerce.com/browse/INT-857)
[INT-858](https://jira.bigcommerce.com/browse/INT-858)
> INT-856, INT-857, INT-858 Add Google Pay + Stripe Support

- src/checkout-buttons/create-checkout-button-initializer.ts
- src/checkout-buttons/create-checkout-button-registry.spec.ts
- src/checkout-buttons/create-checkout-button-registry.ts
- src/checkout-buttons/strategies/paypal-button-strategy.spec.ts
- src/checkout-buttons/strategies/paypal-button-strategy.ts
- src/payment/strategies/paypal/paypal-sdk.ts
Use the specified host from `createCheckoutButtonInitializer` options to send the request to create the payment method instead of a relative one.
CORS errors abound when using the relative host because of the double redirect.
Unit tested. Also:
> fix(checkout-button): PAYMENTS-3071 Use the specified host for the paypal payment creation endpoint

- src/checkout-buttons/create-checkout-button-initializer.ts
- src/checkout-buttons/create-checkout-button-registry.spec.ts
- src/checkout-buttons/create-checkout-button-registry.ts
- src/checkout-buttons/strategies/paypal-button-strategy.spec.ts
- src/checkout-buttons/strategies/paypal-button-strategy.ts
- src/payment/strategies/paypal/paypal-sdk.ts
Reverts bigcommerce/checkout-sdk-js#452
So @lord2800 reported there's still issue with the endpoint. We've decided to revert this PR until we can find a proper fix.
> Revert "fix(checkout-button): PAYMENTS-3071 Use the specified host for the paypal payment creation endpoint"

- src/embedded-checkout/embedded-checkout-events.ts
- src/embedded-checkout/embedded-checkout-options.ts
- src/embedded-checkout/embedded-checkout.spec.ts
- src/embedded-checkout/embedded-checkout.ts
- src/embedded-checkout/iframe-content/embedded-checkout-messenger.ts
- src/embedded-checkout/iframe-content/iframe-embedded-checkout-messenger.spec.ts
- src/embedded-checkout/iframe-content/iframe-embedded-checkout-messenger.ts
- src/embedded-checkout/iframe-content/noop-embedded-checkout-messenger.ts
* Add the ability to notify parent frame when customer signs out
* So the parent frame can hook into the callback and respond to the event. i.e.: WP can hook into the event and log out from WP session.
* Unit
> CHECKOUT-3677: Notify parent frame when customer signs out

- src/embedded-checkout/resizable-iframe-creator.spec.ts
- src/embedded-checkout/resizable-iframe-creator.ts
* Allow cross-origin iframes to invoke payment request API.
* Some payment methods use the payment request API, i.e.: Visa Checkout.
* Unit
> CHECKOUT-3481: Allow cross-origin iframe to invoke payment request API

- src/payment/instrument/instrument-response-body.ts
- src/payment/instrument/instrument-response-transformer.ts
- src/payment/instrument/instrument.mock.ts
- src/payment/instrument/instrument.ts
Support default instrument for stored instruments, whitelist property.
The credit card is editable and enables to default instrument functionality.
Payment Method List
Checkout Credit Card Default
> PAYMENTS-3663 enable default instrument property

- src/payment/payment-request-options.ts
- src/payment/strategies/index.ts
- src/payment/strategies/paypal/index.ts
- src/payment/strategies/paypal/paypal-express-payment-initialize-options.ts
- src/payment/strategies/paypal/paypal-express-payment-strategy.spec.ts
- src/payment/strategies/paypal/paypal-express-payment-strategy.ts
* Add the ability to opt into redirect flow for PayPal Express.
* For Embedded Checkout, we can't really use the in-context flow. This is because during the in-context flow, it does a redirect to PayPal and back. We want to be able to do the redirect in the parent frame. Otherwise when we're redirected back from PayPal, we'll be showing the checkout page within the child frame. But there's no way of controlling that. So a workaround is to use the redirect flow instead, which we can't control which window to do the redirect.
* Unit
> CHECKOUT-3481: Opt into redirect flow for PayPal Express

- src/embedded-checkout/embedded-checkout-error.ts
- src/embedded-checkout/embedded-checkout-events.ts
- src/embedded-checkout/iframe-content/create-embedded-checkout-messenger.ts
- src/embedded-checkout/iframe-content/embedded-checkout-messenger.ts
- src/embedded-checkout/iframe-content/embedded-content-options.ts
- src/embedded-checkout/iframe-content/handle-frame-loaded-event.spec.ts
- src/embedded-checkout/iframe-content/handle-frame-loaded-event.ts
- src/embedded-checkout/iframe-content/iframe-embedded-checkout-messenger.spec.ts
- src/embedded-checkout/iframe-content/iframe-embedded-checkout-messenger.ts
- src/embedded-checkout/resizable-iframe-creator.spec.ts
- src/embedded-checkout/resizable-iframe-creator.ts
* Switch to a different method to calculate the height of the iframe if `bodyId` is passed.
* You might want to exclude certain elements from the calculation. For example, you could have an element that's fixed to the bottom of the page. That could cause a problem if the calculation method is set to `lowestElement`. This is because when the page content shrinks, the fixed element will remain in the same position because its position is relative to the iframe rather than the content. Also, because it is the lowest element on the page, therefore the iframe itself won't reduce its height.
* Unit
> CHECKOUT-3706: Switch to different height calculation method if `contentId` is provided.

- src/checkout-buttons/strategies/braintree/braintree-paypal-button-options.ts
- src/checkout-buttons/strategies/braintree/braintree-paypal-button-strategy.spec.ts
- src/checkout-buttons/strategies/braintree/braintree-paypal-button-strategy.ts
- src/checkout-buttons/strategies/braintree/index.ts
- src/checkout-buttons/strategies/checkout-button-method-type.ts
- src/checkout-buttons/strategies/googlepay/googlepay-button.mock.ts
- src/checkout-buttons/strategies/index.ts
- src/checkout-buttons/strategies/masterpass/index.ts
- src/checkout-buttons/strategies/masterpass/masterpass-button-strategy.spec.ts
- src/checkout-buttons/strategies/masterpass/masterpass-button-strategy.ts
- src/checkout-buttons/strategies/paypal/index.ts
- src/checkout-buttons/strategies/paypal/paypal-button-options.ts
- src/checkout-buttons/strategies/paypal/paypal-button-strategy.spec.ts
- src/checkout-buttons/strategies/paypal/paypal-button-strategy.ts
* Group checkout button strategies in folders
* It's easier to look for files.
* Travis
> CHECKOUT-3747: Group checkout button strategies in folders

- package-lock.json
- package.json
- src/checkout-buttons/checkout-button-initializer.spec.ts
- src/checkout-buttons/create-checkout-button-initializer.spec.ts
- src/checkout-buttons/create-checkout-button-initializer.ts
- src/checkout-buttons/create-checkout-button-registry.spec.ts
- src/checkout-buttons/create-checkout-button-registry.ts
* Post form data to the specified host URL.
* Currently you can pass `host` option when you call `createCheckoutButtonInitializer`, and we use that value when making AJAX requests. We should also use that value when posting HTML form data to the server.
* Unit
> CHECKOUT-3747: Post form data to host URL

- package-lock.json
- package.json
* Bump `@bigcommerce/data-store` version
* Please see the [change log](https://github.com/bigcommerce/data-store-js/releases).
* Unit
> CHECKOUT-3462: Bump `@bigcommerce/data-store` version

- src/checkout-buttons/strategies/masterpass/masterpass-button-strategy.ts
- src/customer/strategies/masterpass-customer-strategy.ts
- src/payment/strategies/masterpass/masterpass-payment-strategy.spec.ts
- src/payment/strategies/masterpass/masterpass-payment-strategy.ts
[INT-1073](https://jira.bigcommerce.com/browse/INT-1073)
https://github.com/bigcommerce/bigcommerce/pull/27185
Set suppressShippingAddress to false when checking out using Masterpass and the customer can select the shipping address, so shipping info on checkout is auto-populated from Masterpass on Stripe.
So the customer can checkout without having to manually populate the shipping info.
> [DEMO](https://drive.google.com/open?id=12QokgkBQCDKbJIDIkUxYplA0ORLNVxVK) 
@bigcommerce/checkout @bigcommerce/integrations
> feat(checkout): INT-1073 Populate shipping info from Masterpass on Stripe

- src/payment/strategies/googlepay/googlepay-braintree-initializer.ts
- src/payment/strategies/googlepay/googlepay-braintree.ts
- src/payment/strategies/googlepay/googlepay.mock.ts
Braintree was sending googlePayMerchantId and in mapper of GooglePay it was received with merchantId
Because is needed to map correctly merchantId and merchantName for Google Pay request payload
https://github.com/bigcommerce/checkout-sdk-js/pull/463
> INT-1092 Braintree merchantId is sent with the wrong name

- src/checkout-buttons/checkout-button-initializer.spec.ts
- src/checkout-buttons/checkout-button-initializer.ts
* Allow checkout buttons with different container ID to initialize in parallel.
* This PR requires #475 in order to retain the behaviour of using cached payment method data if available.
* Some people could insert multiple buttons of the same type on the same page. We want to parallelize the load if possible.
* Unit
> CHECKOUT-3462: Allow checkout buttons with different container ID to initialize in parallel

- src/checkout/checkout-service.spec.ts
* Fix incorrect mock value for config requests.
* `ConfigRequestSender#loadConfig` should return the result of `getConfig()` rather than `getCheckout()`.
* Unit
> CHECKOUT-2934: Fix incorrect mock value for config requests

- src/checkout-buttons/strategies/googlepay/googlepay-button-strategy.ts
- src/checkout-buttons/strategies/masterpass/masterpass-button-strategy.ts
This fixes the issue created by now using the unique ids on the templates for GooglePay and MasterPass.
As per bigcommerce/bigcommerce#27267 we need to adjust both Masterpass & Google Pay checkout button strategies to consume unique ids
> fix(payments): INT-1119 Modify approach in Checkout Button Strategies to consume unique ids

- src/checkout/create-action-transformer.spec.ts
- src/checkout/create-action-transformer.ts
- src/payment/strategies/amazon-pay/amazon-pay-payment-strategy.spec.ts
- Surface response error details
- So consumers can display more meaningful errors
- Functional / Unit / Manual
> CHECKOUT-3768 Surface the error details for RequestErrors

- package-lock.json
- package.json
* Upgrade Webpack to the latest version - `4.27.0`
* It has some [improvements](https://github.com/webpack/webpack/releases).
* Travis
> CHECKOUT-3775: Upgrade Webpack to newer version

- src/checkout-buttons/strategies/masterpass/masterpass-button-strategy.ts
- src/customer/strategies/masterpass-customer-strategy.ts
- src/payment/strategies/masterpass/masterpass-payment-strategy.spec.ts
- src/payment/strategies/masterpass/masterpass-payment-strategy.ts
- src/payment/strategies/masterpass/masterpass.mock.ts
- src/payment/strategies/masterpass/masterpass.ts
When I click Masterpass button from the Quick Cart page, and then dismiss it,
I want to land back on the Quick Cart page, So that I can start where i left off.
As a merchant, when I click the MP button from the Quick Cart Page and dismiss, I land back on the Quick Cart page with no changes made to my cart.
DEPLOY => https://launchbay.bigcommerce.net/deployments/97603
> feat(payment): INT-1050 & 1051 Masterpass callback url post launch

- src/customer/customer-strategy-action-creator.spec.ts
- src/customer/customer-strategy-action-creator.ts
- src/customer/customer-strategy-reducer.spec.ts
- src/customer/customer-strategy-reducer.ts
- src/customer/customer-strategy-selector.spec.ts
- src/customer/customer-strategy-selector.ts
- src/customer/customer-strategy-state.ts
- src/customer/internal-customers.mock.ts
- src/customer/strategies/amazon-pay-customer-strategy.spec.ts
- src/customer/strategies/amazon-pay-customer-strategy.ts
- src/customer/strategies/braintree-visacheckout-customer-strategy.ts
- src/customer/strategies/chasepay-customer-strategy.ts
- src/customer/strategies/customer-strategy.ts
- src/customer/strategies/default-customer-strategy.ts
- src/customer/strategies/googlepay/googlepay-braintree-customer-strategy.spec.ts
- src/customer/strategies/googlepay/googlepay-customer-strategy.ts
- src/customer/strategies/googlepay/googlepay-stripe-customer-strategy.spec.ts
- src/customer/strategies/masterpass-customer-strategy.ts
- src/customer/strategies/square-customer-strategy.ts
1. Convert `CustomerStrategy` from an abstract class into a plain interface.
1. Check the `isInitialized` flag in a central location rather than checking it individually for every customer strategy.
1. Prefer not to keep the abstract class around because it usually encourages us to move shared behaviours up to the parent class rather than sharing behaviours via composition.
1. Strategies shouldn't have to perform the initialisation check themselves. Currently we do, but often we forget to implement the check. So it's better to move the check out to the upper layer.
* Unit
> CHECKOUT-3791: Convert customer strategy into plain interface

- src/checkout/checkouts.mock.ts
- src/shipping/shipping-strategy-action-creator.spec.ts
- src/shipping/shipping-strategy-action-creator.ts
- src/shipping/shipping-strategy-reducer.spec.ts
- src/shipping/shipping-strategy-reducer.ts
- src/shipping/shipping-strategy-selector.spec.ts
- src/shipping/shipping-strategy-selector.ts
- src/shipping/shipping-strategy-state.ts
- src/shipping/strategies/amazon-pay-shipping-strategy.spec.ts
- src/shipping/strategies/amazon-pay-shipping-strategy.ts
- src/shipping/strategies/default-shipping-strategy.ts
- src/shipping/strategies/shipping-strategy.spec.ts
- src/shipping/strategies/shipping-strategy.ts
1. Convert `ShippingStrategy` from an abstract class into a plain interface.
1. Check the `isInitialized` flag in a central location rather than checking it individually for every shipping strategy.
1. Prefer not to keep the abstract class around because it usually encourages us to move shared behaviours up to the parent class rather than sharing behaviours via composition.
1. Strategies shouldn't have to perform the initialisation check themselves. Currently we do, but often we forget to implement the check. So it's better to move the check out to the upper layer.
* Unit
> CHECKOUT-3791: Convert shipping strategy into plain interface

- src/checkout-buttons/checkout-button-actions.ts
- src/checkout-buttons/checkout-button-reducer.spec.ts
- src/checkout-buttons/checkout-button-reducer.ts
- src/checkout-buttons/checkout-button-selector.spec.ts
- src/checkout-buttons/checkout-button-selector.ts
- src/checkout-buttons/checkout-button-state.ts
- src/checkout-buttons/checkout-button-strategy-action-creator.spec.ts
- src/checkout-buttons/checkout-button-strategy-action-creator.ts
- src/checkout-buttons/checkout-buttons.mock.ts
- src/checkout-buttons/strategies/braintree/braintree-paypal-button-strategy.spec.ts
- src/checkout-buttons/strategies/braintree/braintree-paypal-button-strategy.ts
- src/checkout-buttons/strategies/checkout-button-strategy.ts
- src/checkout-buttons/strategies/googlepay/googlepay-button-strategy.ts
- src/checkout-buttons/strategies/masterpass/masterpass-button-strategy.spec.ts
- src/checkout-buttons/strategies/masterpass/masterpass-button-strategy.ts
- src/checkout-buttons/strategies/paypal/paypal-button-strategy.ts
- src/payment/strategies/masterpass/get-callback-url.ts
- src/payment/strategies/masterpass/index.ts
- src/payment/strategies/masterpass/masterpass-payment-initialize-options.ts
- src/payment/strategies/masterpass/masterpass-payment-strategy.ts
- src/payment/strategies/masterpass/masterpass.ts
1. Convert `CheckoutButtonStrategy` from an abstract class into a plain interface.
1. Check the `isInitialized` flag in a central location rather than checking it individually for every shipping strategy.
1. Prefer not to keep the abstract class around because it usually encourages us to move shared behaviours up to the parent class rather than sharing behaviours via composition.
1. Strategies shouldn't have to perform the initialisation check themselves. Currently we do, but often we forget to implement the check. So it's better to move the check out to the upper layer.
* Unit
> CHECKOUT-3791: Convert checkout button strategy into plain interface

- src/checkout-buttons/strategies/googlepay/googlepay-button-strategy.ts
- src/customer/strategies/googlepay/googlepay-customer-strategy.ts
[INT-1138](https://jira.bigcommerce.com/browse/INT-1138)
When checkout with Google Pay from the quick cart or cart page, then click edit cart on UCO and try to Sign In again on Google Pay from quick cart or cart page, Google pay will not redirect to UCO, then if go to UCO Google Pay session will be still there.
Google pay will not redirect to UCO if a shipping address is already set
BUG: https://drive.google.com/file/d/1oIg9jt_KcCYPbWkLS0PDj-PHq-U4okcz/view?usp=sharing
BUG FIXED: https://drive.google.com/file/d/1RpQOyJUEBXcUOIFWPxjrrSgBphOOek3a/view?usp=sharing
> feat(payment): INT-1138 Fix shipping address bug in google pay

- src/checkout-buttons/checkout-button-initializer.spec.ts
- src/checkout-buttons/checkout-button-initializer.ts
- src/common/dom/index.ts
- src/common/dom/is-element-id.spec.ts
- src/common/dom/is-element-id.ts
- src/common/dom/set-unique-element-id.spec.ts
- src/common/dom/set-unique-element-id.ts
* Set unique container ID if not provided by client.
* For example, you can now pass in a CSS selector instead of an element ID. If one or more elements can be found, each of them will be configured with an unique element ID and get initialised accordingly.
```js
initializer.initializeButton({
methodId: 'braintreepaypal',
containerId: '[data-braintree-paypal-container]',
});
```
* This is because some themes render `cart.additional_checkout_buttons` snippet multiple times. We can't generate a unique ID for each snippet on the server side because we only render the snippet once. For multiple occurrences of `cart.additional_checkout_buttons`, we simply reuse the same rendered output. Therefore, we need to generate unique element IDs on the client side instead.
* Unit
* Manual …
> CHECKOUT-3804: Set unique container ID if not provided by client

- src/config/config.ts
- src/config/configs.mock.ts
* Add missing properties to `StoreLinks` object.
* They exist in runtime. But they are not defined in the definition file, therefore not visible to the TS compiler.
* Manual
> CHECKOUT-3790: Add missing properties to `StoreLinks` object

- jest-config.js
- src/common/http-request/error-response-body.typedef.js
- src/common/utility/get-environment.spec.ts
* Adopt the Jest settings recommended by the newer version of `ts-jest`.
* We updated `ts-jest` few weeks ago, but didn't switch over to the new settings. By switching over, we can get rid of the deprecation warnings.
* Travis
> CHECKOUT-3790: Update Jest config

- package-lock.json
- package.json
- src/billing/billing-address-reducer.ts
- src/cart/cart-reducer.ts
- src/checkout/checkout-reducer.ts
- src/checkout/checkout-service.spec.ts
- src/checkout/checkout-service.ts
- src/checkout/create-checkout-service.ts
- src/common/error/clear-error-reducer.spec.ts
- src/common/error/clear-error-reducer.ts
- src/common/error/error-action-creator.spec.ts
- src/common/error/error-action-creator.ts
- src/common/error/error-actions.ts
- src/common/error/index.ts
- src/common/utility/omit-deep.ts
- src/config/config-reducer.ts
- src/coupon/coupon-reducer.ts
- src/coupon/gift-certificate-reducer.ts
- src/customer/customer-strategy-reducer.ts
- src/geography/country-reducer.ts
- src/order/order-reducer.ts
- src/payment/instrument/instrument-reducer.ts
- src/payment/payment-method-reducer.ts
- src/payment/payment-strategy-reducer.ts
- src/shipping/consignment-reducer.ts
- src/shipping/shipping-country-reducer.ts
- src/shipping/shipping-strategy-reducer.ts
* Add ability to clear error state. i.e.:
```js
service.clearError(error);
```
* Currently, we automatically clear an error if the action causing the error is successfully carried out after a retry. But sometimes the user might not attempt the action again and decide to do something else instead. For example, the user fails to sign in and decides to continue as a guest. Therefore, we want a way to manually clear errors to accommodate such scenario.
* Unit
> CHECKOUT-3790: Add ability to clear error state

- src/embedded-checkout/embed-checkout.ts
* It has been running in production for some time now so this label can be removed.
* Update documentation.
* None
> CHECKOUT-3783: Remove alpha label from documentation

- src/checkout/checkout-store-selector.ts
* Return correct type for billing addresses.
* It should be `BillingAddress` rather than `Address`.
* Travis
> CHECKOUT-3790: Return correct type for billing addresses

- src/order/internal-order.ts
- src/order/internal-orders.mock.ts
- src/order/map-to-internal-order.ts
- src/order/order.ts
- src/order/orders.mock.ts
This PR adds the object `taxTotal` to the `map-to-internal-order`(also we add the interfaces for `order` and `internal-order` and their corresponding mocks), so once the information reach `bigpay-client`, it will catch the `taxTotal` and map it correctly. Currently `checkout-sdk-js` is not sending `taxTotal` as part of the payload received by `bigpay-client` and this creates a bug in `bigpay`.
There was an issue where the transaction_rbits were not generated because `taxTotal` was not sent to `bigpay-client` and this creates a bug in `bigpay`. This fixes the issue on `checkout-sdk-js`.
[Video of a purchase using Chasepay+Wepay](https://drive.google.com/file/d/1GxGy0fU_u4amneDBVmfT6HUQ8L0dIUvf/view?usp=sharing)
This PR depends on bigcommerce/bigcommerce#27647
@vmparra @clopezh @cbandam …
> fix(payment): INT-1079 Add taxTotal in map to internal order

- src/checkout/checkout-service.ts
- src/payment/is-credit-card-like.ts
- src/payment/payment.ts
- src/payment/payments.mock.ts
* Remove `ccType` from order submission payload.
* We don't actually need to post `ccType`. Therefore, we should remove it from the TS interface.
* Travis
> CHECKOUT-3842: Remove `ccType` from order submission payload

- src/payment/payment-method-config.ts
* Add `requireCustomerCode` field in `PaymentMethodConfig` interface.
* It is missing in the interface but defined in the actual response.
* Travis
> CHECKOUT-3842: Add missing field in `PaymentMethodConfig` interface

- src/checkout/checkout-request-sender.ts
- src/checkout/index.ts
- src/common/http-request/index.ts
- src/common/http-request/join-includes.spec.ts
- src/common/http-request/join-includes.ts
- src/coupon/coupon-request-sender.spec.ts
- src/coupon/coupon-request-sender.ts
- src/coupon/gift-certificate-request-sender.ts
- src/shipping/consignment-reducer.spec.ts
- src/shipping/consignment-reducer.ts
* Include available shipping options when applying or removing coupons.
* We should rehydrate shipping options because coupons may affect shipping quotes.
* Unit
> CHECKOUT-3890: Rehydrate shipping options after applying coupon

- src/cart/line-item-map.ts
Make them optional
Because they are not always in the payload (order endpoint)
> CHECKOUT-3850 make customItems optional

- src/checkout/checkout-service.ts
- Fix the documentation
- It leads to confusion
- 👀 
> CHECKOUT-3060 Make `methodId` a propety of `payment` in `submitOrder`

- src/payment/payment.ts
* Fix type definition for `VaultedInstrument`
* To have the correct fields.
* Travis
> CHECKOUT-3843: Fix type definition for `VaultedInstrument`

- src/config/config.ts
- src/config/configs.mock.ts
- src/payment/payment.ts
* Add missing `isTrustedShippingAddressEnabled` and `ccCustomerCode` fields
* They exist but missing from the TS definitions.
* Travis
> CHECKOUT-3843: Add missing `isTrustedShippingAddressEnabled` and `ccCustomerCode` fields

- src/payment/payment.ts
* Like `CreditCardInstrument`, `ccNumber` and `ccCvv` should be string instead of number.
* They are defined as `number` by mistake.
* Travis
> CHECKOUT-3843: `ccNumber` and `ccCvv` should be string instead of number

- src/checkout-buttons/create-checkout-button-initializer.ts
- src/checkout-buttons/create-checkout-button-registry.ts
- src/checkout-buttons/strategies/paypal/paypal-button-strategy.spec.ts
- src/checkout-buttons/strategies/paypal/paypal-button-strategy.ts
- src/payment/strategies/paypal/paypal-sdk.ts
Use the specified host for paypal payment creation and provide the cart id to it along with the internal-only header.
The endpoint used to rely on the session to retrieve the current cart, which is a bad idea.
Unit tested.
> fix(checkout-button): PAYMENTS-3071 Use the specified host for paypal payment creation

- src/payment/strategies/square/square-payment-strategy-mock.ts
- src/payment/strategies/square/square-payment-strategy.spec.ts
- src/payment/strategies/square/square-payment-strategy.ts
catch error when the nonce request fail
the nonce return an error for wrong card details entered, the error gets lost and the submit button stuck in spinning state.
Coming...
> PAYMENTS-4034 catch error when nonce return 400, squarev2

- src/embedded-checkout/iframe-content/create-embedded-checkout-messenger.ts
- src/embedded-checkout/iframe-content/iframe-embedded-checkout-messenger.spec.ts
- src/embedded-checkout/iframe-content/iframe-embedded-checkout-messenger.ts
- src/embedded-checkout/iframe-event-poster.ts
* Post `frame_error` without a target origin so that parent window can receive it in case the error is due to an issue with the current cart.
* Otherwise, if we have a session issue, i.e.: (cart ID is missing), that prevents the iframe from being loaded, we won't be able to notify the parent window about such error.
* Unit
> CHECKOUT-3941: Post `frame_error` without target origin so that parent window can receive it in case the error is due to issue with current cart

- package-lock.json
- package.json
- src/common/storage/browser-storage.spec.ts
- src/common/storage/browser-storage.ts
- src/common/storage/index.ts
- src/embedded-checkout/embed-checkout.spec.ts
- src/embedded-checkout/embed-checkout.ts
- src/embedded-checkout/embedded-checkout.spec.ts
- src/embedded-checkout/embedded-checkout.ts
- src/embedded-checkout/errors/index.ts
- src/embedded-checkout/errors/not-embeddable-error.ts
- src/embedded-checkout/resizable-iframe-creator.ts
* Redirect users to the domain of Embedded Checkout so that cookie can be set for browsers that have a restrictive third party cookie setting.
* It is possible that this workaround won't work with Safari's latest [ITP 2.0 feature](https://webkit.org/blog/8311/intelligent-tracking-prevention-2-0/). But so far, I'm unable to replicate the potential problem so it's possible that it's not applicable. I'll do further testing on that. Regardless, this workaround is still required for older versions of Safari.
* This workaround is required for certain browsers (namely Safari) that prevent session cookies to be set for a third party website unless the user has recently visited such website. Therefore, before we attempt to login or set an active cart in the session, we need to first redirect the …
> CHECKOUT-3941: Redirect user to allow third party cookie to be set

- src/checkout/checkout-store-error-selector.ts
- src/common/error/errors/map-from-storefront-error-response.ts
- src/common/error/request-error-factory.ts
- src/coupon/coupon-selector.spec.ts
- src/coupon/coupon-selector.ts
- src/coupon/coupon-state.ts
- src/coupon/gift-certificate-actions.ts
- src/coupon/gift-certificate-selector.ts
- src/coupon/gift-certificate-state.ts
As per title
So consumers can access more information like why coupon failed
> CHECKOUT-3852 Expose proper error type for Coupon/GiftCertificates

- src/currency/currency-formatter.spec.ts
- src/currency/currency-formatter.ts
Make currency service round instead of truncate
It's a more accurate behaviour
Unit
> CHECKOUT-3967 Round properly when using CurrencyService

- src/cart/cart-comparator.spec.ts
- src/cart/cart-comparator.ts
* Ignore the order of line items when comparing cached cart content with the latest cart content.
* We are only interested in the the items themselves - not the order of them.
* Unit
> CHECKOUT-3844: Ignore order of line items when comparing cart content

- src/payment/is-credit-card-like.spec.ts
- src/payment/is-nonce-like.spec.ts
- src/payment/is-vaulted-instrument.spec.ts
- src/payment/payment-action-creator.spec.ts
- src/payment/payment-action-creator.ts
- src/payment/payment-request-body.ts
- src/payment/payment-strategy-action-creator.ts
- src/payment/payment.ts
- src/payment/payments.mock.ts
- src/payment/strategies/offsite/offsite-payment-strategy.spec.ts
- src/payment/strategies/offsite/offsite-payment-strategy.ts
* Don't throw an error if no payment data is passed for offsite payment methods.
* Because for offsite payment methods, we collect payment details from another website so we are not supposed to pass payment details via `submitOrder` method.
* Currently, we get around this issue by providing an empty object `i.e.: { paymentData: {} }`, which effectively prevents the error from being thrown. After this change, we won't require the workaround anymore.
* Unit
> CHECKOUT-3844: Don't throw error if no payment data is passed for offsite payment methods

- src/cart/cart-comparator.spec.ts
- src/cart/cart-comparator.ts
* Use `productId` and `variantId` to sort items in cart
* Because some products can be re-applied and therefore have a different ID even though they are the same.
* Unit
> CHECKOUT-4012: Use `productId` and `variantId` to sort items in cart

- src/checkout/checkout-selector.spec.ts
- src/checkout/checkout-selector.ts
- src/payment/payment-selector.ts
- src/payment/strategies/braintree/braintree-paypal-payment-strategy.spec.ts
- src/payment/strategies/braintree/braintree-paypal-payment-strategy.ts
* Pass amount inclusive of store credit to PayPal.
* Otherwise PayPal modal displays incorrect amount, which is confusing for the shopper.
* We can't create the order first because we can't perform any asynchronous actions before launching a popup window (otherwise it gets blocked by the browser). And we currently don't have a way to apply store credit before creating an order (that is a separate project which we plan to do soon). So as an interim solution, we have to deduct the store credit amount on the client-side.
* Unit
> PAYMENTS-1253: Pass store credit amount to PayPal

- src/payment/errors/payment-method-cancelled-error.ts
- src/payment/strategies/braintree/braintree-paypal-payment-strategy.spec.ts
- src/payment/strategies/braintree/braintree-paypal-payment-strategy.ts
- src/payment/strategies/braintree/braintree.ts
- src/payment/strategies/braintree/is-braintree-error.spec.ts
- src/payment/strategies/braintree/is-braintree-error.ts
* Throw a cancellation error when the shopper closes the PayPal popup before completing the authorisation flow.
* Client apps can choose to ignore the error by checking `type` property.
* Unit
> PAYMENTS-1253: Throw cancellation error when shopper closes PayPal popup

- src/common/overlay/index.ts
- src/common/overlay/overlay.spec.ts
- src/common/overlay/overlay.ts
- src/payment/strategies/braintree/braintree-payment-processor.spec.ts
- src/payment/strategies/braintree/braintree-payment-processor.ts
- src/payment/strategies/braintree/create-braintree-payment-processor.ts
* Show an overlay when PayPal modal is open.
* So shoppers can't interact with the UI while the modal is open.
* I remember previously PayPal is responsible for showing the overlay. But I think at some point in the past we upgraded the client SDK (to support Google Pay). And the new version doesn't show the overlay anymore - it's now the client's responsibility.
* Unit
> PAYMENTS-1253: Show overlay when Braintree PayPal modal is open

- src/payment/strategies/braintree/braintree-credit-card-payment-strategy.spec.ts
- src/payment/strategies/braintree/braintree-credit-card-payment-strategy.ts
* Pass the order amount to Braintree client when going through 3DS flow
* It appears a [similar issue](https://github.com/bigcommerce/checkout-sdk-js/pull/546) affects 3DS flow as well - where the store credit amount is not reflected in the 3DS modal.
* Unit
> PAYMENTS-1253: Pass order amount to Braintree client when going through 3DS flow

- src/config/config.ts
- src/config/configs.mock.ts
Fix types 
So they match current API payloads
> CHECKOUT-1289 Fix config and checkout types

- src/payment/strategies/klarna/klarna-credit.ts
- src/payment/strategies/klarna/klarna-payment-strategy.spec.ts
- src/payment/strategies/klarna/klarna-payment-strategy.ts
- src/payment/strategies/klarna/klarna.mock.ts
I added billing and shipping address to the payload of the `load` method for Klarna.
According to Legal Privacy and Europe laws, Klarna must not receive PII data from BC until shopper selects option at checkout or authorizes so we no longer send this info during the `create_session` call instead of that we update the session with the info before open the Klarna's widget 
Video: https://drive.google.com/open?id=1UWqsZfH08c3LSx9RqqZDDZ4Sn5ARWL7_
Sibling PRs:
[BigPay INT-1398](https://github.com/bigcommerce/bigpay/pull/1585)
> feat(payment): INT-1398 Add shipping and billing address before Klarna authorization

- README.md
Update to Readme
Described incorrect parameters required for `signInCustomer`
Update name of method to sign in guest from `signInCustomer` to `continueAsGuest`
Update `selectShippingOption` to no longer accept `address.id` as a paremeter.
Could only get it to work using named parameters.
> Update Readme: Customer signin actions require named parameters

- src/common/error/errors/map-from-payment-error-response.ts
- src/common/error/request-error-factory.spec.ts
- src/common/error/request-error-factory.ts
Expose all errors coming from BigPay, unless we have manually registered a specific error with a specific code.
https://github.com/bigcommerce/checkout-sdk-js/pull/499 aimed to fix surfacing payment errors that were not being properly exposed, by checking specific codes. We know that if BigPay surfaces error, they can be displayed to the shopper. Expose all these errors unless there is an override registered.
@bigcommerce/checkout 
ommerce/payments
> CHECKOUT-4062 Expose missing payment errors

- package-lock.json
- package.json
Lock `messageformat` to a specific minor `~2.0.1` instead of to a major.
Because a bug has been introduced in `2.1.0` 
We have reported the issue but we are don't know when it's gonna be solved https://github.com/messageformat/messageformat/issues/237
manual
> CHECKOUT-4062 Fix broken dep

- src/payment/create-payment-strategy-registry.spec.ts
- src/payment/create-payment-strategy-registry.ts
- src/payment/payment-strategy-type.ts
- src/payment/strategies/converge/converge-payment-strategy.spec.ts
- src/payment/strategies/converge/converge-payment-strategy.ts
- src/payment/strategies/converge/index.ts
port Elavon ng-checkout only implementation to checkout-sdk-js + ng-checkout
partners who use checkout-sdk-js + ng-checkout can use Elavon Converge
> feat(payment): INT-1464 Port Elavon ng-checkout only implementation to checkout-sdk-js + ng-checkout

- webpack.config.js
Restrict `ts-loader` to the `src` folder of the project
Packages linked using npm don't contain the `node_modules` string in
their path. This can cause problems if` ts-loader` tries to process non
es6 modules. It is more reliable to simply restrict `ts-loader` to files
within the `src` folder of the project.
- Unit / Manual
Before:
After:
> chore(common): CHECKOUT-4097 Restrict ts-loader to the src folder

- package-lock.json
- package.json
* Upgrade `messageformat` version to 2.2.1
* The issue with UglifyJS has been fixed: https://github.com/messageformat/messageformat/issues/237
* Manual
> CHECKOUT-4062: Upgrade `messageformat` version to 2.2.1

- src/payment/strategies/klarna/klarna-credit.ts
- src/payment/strategies/klarna/klarna-payment-strategy.spec.ts
- src/payment/strategies/klarna/klarna-payment-strategy.ts
- src/payment/strategies/klarna/klarna.mock.ts
[INT-1552](https://jira.bigcommerce.com/browse/INT-1552)
I modified the `klarna-payments-strategy` to map phone and address2 and send that information to Klarna.
Klarna requires that information to be send.
@bigcommerce/checkout @bigcommerce/payments @bigcommerce/integrations @bigcommerce/intersys-integrations
> feat(checkout): INT-1552 Sending phone number and optional address to Klarna

- src/payment/strategies/affirm/affirm-payment-strategy.spec.ts
- src/payment/strategies/affirm/affirm-payment-strategy.ts
- src/payment/strategies/affirm/affirm.ts
- Pass all amounts in cents for Affirm
- Add platform metadata for Affirm
- Pass billing address as shipping address when shipping address is not available (i.e digital products).
After Affirm's team reviewed the test store, this changes were required to complete validation on the payment provider integration.
https://drive.google.com/open?id=1tvHCItvS0R2hXR0phhQUA56rCie4S6Ph
> fix(payment): INT-1500 Pass all amounts in cents for Affirm & Platform metadata

- package-lock.json
- package.json
- webpack.config.js
* Include Babel polyfills to UMD bundles so they work in older browsers.
* We want the UMD bundles to be consumable directly in browsers. In order to do that, we have to include polyfills so they work in older browsers.
* On the other hand, we don't have that need for CJS bundles. This is because they get imported into apps instead of consumed directly in browsers. These apps have their own browser support requirements; also they might have their own polyfills. So it makes sense for CJS bundles to leave out browser polyfills.
* Manual
> CHECKOUT-4137: Include Babel polyfills to UMD bundles so they work in older browsers

- package-lock.json
- package.json
* Ran `npm audit fix --only=prod` to address a low severity security warning.
* To address a low severity security warning
* Travis
> CHECKOUT-4137: Upgrade dependencies

- package-lock.json
- package.json
- Update commit-validation@2.1.1
- `dependabot` doesn't allow to configure the commit format
- This PR should validate that the new version still runs
- As for dependabot commits: https://github.com/bigcommerce-labs/ng-checkout/pull/1234
> CHECKOUT-4143 Update validate-commits to v2.1.1

- src/payment/strategies/klarna/klarna-credit.ts
- src/payment/strategies/klarna/klarna-payment-strategy.spec.ts
- src/payment/strategies/klarna/klarna-payment-strategy.ts
Add the billing and shipping data during the call to authorize method in Klarna SDK
We need to meet the PII requirements for EU countries. According to Klarna´s requirements for EU countries, PII data has to be sent during the `authorize` transaction, after the shopper has explicitly selected Klarna as payment method. Currently in the scenario when Klarna is the only available payment method, it is auto selected and the the PII data is sent on widget load.
[Video](https://drive.google.com/open?id=1WRyrva0HINmS4Iq0ZbnwMpulxOluyosU)
> feat(payment): INT-1562 Add billing and shipping data in auth instead of load method calls in Klarna

- src/payment/create-payment-strategy-registry.ts
- src/payment/strategies/zip/zip-payment-strategy.spec.ts
- src/payment/strategies/zip/zip-payment-strategy.ts
Initialize payment sending the useStoreCredit flag
In order to can update the total amount according to that
https://drive.google.com/open?id=1A8p5EifpG3RRWN3HQjP86JiWQRdkHu2l
> feat(checkout): INT-1520 Pass useStoreCredit flag when initialize payment

- src/payment/errors/index.ts
- src/payment/errors/payment-method-declined-error.ts
- src/payment/strategies/zip/zip-payment-strategy.spec.ts
- src/payment/strategies/zip/zip-payment-strategy.ts
- src/payment/strategies/zip/zip.mock.ts
- src/payment/strategies/zip/zip.ts
Add a handler for a `cancelled order` case
Its possible for an Zip account application to be declined instantly and it needs a handler to show an error message [as seen here](https://zip-online.api-docs.io/v1/checkout-and-registration/checkout-with-registration-decline).
[Demo Video](https://drive.google.com/open?id=1PFETFnO7fkXJaJ_SLmZawarAd5ChYfLO)
> feat(payment): INT-1540 Zip Feedback, declined handler

- src/payment/strategies/klarna/klarna-payment-strategy.ts
- Remove reject(new PaymentMethodInvalidError())
In the scenario when the merchant does not support the shopper's billing country based on their merchant agreement with Klarna the checkout page should not throw an error, instead it should just show the widget showing that the country is not supported.
[BCApp INT-1573](https://github.com/bigcommerce/bigcommerce/pull/30174)
> fix(payments): INT-1573 Checkout load error when non-supported Klarna country is selected

- src/payment/create-payment-strategy-registry.ts
- src/payment/strategies/zip/zip-payment-strategy.spec.ts
- src/payment/strategies/zip/zip-payment-strategy.ts
- src/payment/strategies/zip/zip.mock.ts
- src/payment/strategies/zip/zip.ts
Added additional handlers for `declined` and `referred` responses from the zip Lightbox. 
Referred flow sends a request to clear the cart and save the externalId and then redirects to order confirmation page.
Zip referred registration flow requires the order to seem purchased and redirect to order confirmation page.
[Pending Deploy]
> feat(payment): INT-1247 Checkout using Zip Registration Referred

- src/cart/line-item.ts
- src/cart/line-items.mock.ts
- src/order/order-params.ts
- src/order/order-request-sender.spec.ts
- src/order/order-request-sender.ts
- src/payment/strategies/affirm/affirm-payment-strategy.spec.ts
- src/payment/strategies/affirm/affirm-payment-strategy.ts
- src/payment/strategies/affirm/affirm.ts
[INT 1503](https://jira.bigcommerce.com/browse/INT-1503)
- Include category names in each product added to an order.
After Affirm's team review in test store, this changes were required to complete validation on the payment provider integration
https://github.com/bigcommerce/bigcommerce/pull/29921
https://drive.google.com/file/d/18wCExeuKXw_QukQgVlA-idy5P3Nt1N6C/view?usp=sharing
> INT-1503 Changes in Affirm Strategy

- package-lock.json
- package.json
- As per title
The latest version of `messageformat` exports es6 in the `main` bundle.
We need to change our build to consume `browser` instead of `main`.
- Manual / Unit
> chore(common): CHECKOUT-4171 Revert messageformat to v2.1.0

- .github/CODEOWNERS
- As per title
- So the checkout team gets pinged on new PRs
- Manual
> CHECKOUT-4190 Add CODEOWNERS to github

- src/payment/create-payment-strategy-registry.ts
- src/payment/payment-methods.mock.ts
- src/payment/payment-request-options.ts
- src/payment/payment-strategy-type.ts
- src/payment/strategies/stripev3/index.ts
- src/payment/strategies/stripev3/stripev3-initialize-options.ts
- src/payment/strategies/stripev3/stripev3-payment-strategy.spec.ts
- src/payment/strategies/stripev3/stripev3-payment-strategy.ts
- src/payment/strategies/stripev3/stripev3-script-loader.spec.ts
- src/payment/strategies/stripev3/stripev3-script-loader.ts
- src/payment/strategies/stripev3/stripev3.mock.ts
- src/payment/strategies/stripev3/stripev3.ts
[INT-1450](https://jira.bigcommerce.com/browse/INT-1450)
Add support for Stripe V3 + 3DS that can handle stripe validations with stripe.js (handleCardPayment action)
To support 3DS on Stripe is needed to add a new strategy that use Stripe.js elements and actions to handle 3DS flow and confirm a payment intent that previously was created from back-end
- [BCAPP](https://github.com/bigcommerce/bigcommerce/pull/29991)
- [NGCheckout](https://github.com/bigcommerce-labs/ng-checkout/pull/1227)
- [NGPayments](https://github.com/bigcommerce-labs/ng-payments/pull/799)
- [BigPay](https://github.com/bigcommerce/bigpay/pull/1649)
**Ping** @bigcommerce/intersys-integrations @bigcommerce/payments  @bigcommerce/checkout
> INT-1450 Add support for Stripe V3 + 3DS using payment Intents

- src/cart/line-item.ts
As above
It's a requirement to iterate over lineItems and filter where parentId is null. Currently as it is not defined within the LineItem interface TS gives us an error
> feat(checkout): CHECKOUT-3670 adding parentId to LineItem interface

- src/payment/payment-strategy-action-creator.spec.ts
- src/payment/payment-strategy-action-creator.ts
* Throw `OrderFinalizationNotRequiredError` if the selected payment method for an order is no longer available for the shopper.
* It's a more suitable error to throw because order finalisation is actually not required if the payment method is no longer available for the shopper. That would allow shoppers to carry on as they can choose an alternative payment method to complete their order.
* This is required to fix an AfterPay bug, because the payment method has a special flow which could prevent the shopper from continuing unless they reset their checkout state.
* Unit
> CHECKOUT-4209: Throw `OrderFinalizationNotRequiredError` if payment method is no longer available for shopper

- src/payment/strategies/afterpay/afterpay-payment-strategy.spec.ts
- src/payment/strategies/afterpay/afterpay-payment-strategy.ts
- src/payment/strategies/afterpay/afterpay-sdk.ts
- As per title
- Eventually the display method will be unsupported 
- Unit / Manual
> CHECKOUT-3954 Use the redirect method instead of display when initialising AfterPay

- src/payment/create-payment-strategy-registry.ts
- src/payment/index.ts
- src/payment/payment-methods.mock.ts
- src/payment/payment-strategy-type.ts
- src/payment/payment.ts
- src/payment/strategies/cybersource/cardinal-client.spec.ts
- src/payment/strategies/cybersource/cardinal-client.ts
- src/payment/strategies/cybersource/cardinal-script-loader.spec.ts
- src/payment/strategies/cybersource/cardinal-script-loader.ts
- src/payment/strategies/cybersource/cardinal.mock.ts
- src/payment/strategies/cybersource/cardinal.ts
- src/payment/strategies/cybersource/cybersource-payment-strategy.spec.ts
- src/payment/strategies/cybersource/cybersource-payment-strategy.ts
- src/payment/strategies/cybersource/index.ts
Create the Cybersource's strategy and processors, also create a ThreeDSecure type and add it to the CreditCardInstrument payload: [Tech design](https://intranet.bigcommerce.com/display/IDT/Technical+Design+3-D+Secure+on+CyberSource#?lucidIFH-viewer-5f0ee3b2=1)
To be able to process payments with Cybersource using 3DS being care to not call anything about 3DS when it is disabled in the configuration page
[video](https://drive.google.com/file/d/1ndgU5RuHZqJebdxpLQMxeWVjDPE9WIhN/view?usp=sharing)
[bcapp](https://github.com/bigcommerce/bigcommerce/pull/29976)
[bigpay](https://github.com/bigcommerce/bigpay/pull/1652)
[bigpay-client-js](https://github.com/bigcommerce/bigpay-client-js/pull/76)
> feat(payment): Create Cybersource's strategy for 3DS

- src/checkout/checkout-store-selector.spec.ts
- src/checkout/checkout-store-selector.ts
- src/common/utility/clone-decorator.spec.ts
- src/common/utility/clone-decorator.ts
- src/common/utility/index.ts
- As per title
- The internal state of the `checkout-sdk` should be shield from changes to the exposed objects.
- Functional / Unit
Closes: #430 
Closes: #618 
> CHECKOUT-4254 Make sure changes to the public object don't affect the internal copies

- src/checkout/checkout-store-selector.spec.ts
- src/form/form-field.ts
- src/form/form-selector.spec.ts
- src/form/form-selector.ts
- src/form/form.mocks.ts
1. Unify `FormField` definition.
2. Use strings instead of enum
1.  Recently we improved `FormField` type https://github.com/bigcommerce/checkout-sdk-js/pull/635. However those different types are hard to consume. It requires you need to do type checks in order to access different properties.
2. Enums force a new type, causing breaking changes / requiring refactoring. Also enums dont seem to get exported as expected (they are undefined).
https://github.com/bigcommerce-labs/ng-checkout/pull/1311
> CHECKOUT-4201 Make FormField type easier to consume

- src/payment/payment-methods.mock.ts
- src/payment/strategies/amazon-pay/amazon-pay-confirmation-flow.ts
- src/payment/strategies/amazon-pay/amazon-pay-payment-strategy.spec.ts
- src/payment/strategies/amazon-pay/amazon-pay-payment-strategy.ts
- src/payment/strategies/amazon-pay/amazon-pay-script-loader.spec.ts
- src/payment/strategies/amazon-pay/amazon-pay-window.ts
[INT-1586](https://jira.bigcommerce.com/browse/INT-1586)
Add flow when 3DS is enabled on amazonpay strategy 
Because we want to to accept payment through Amazon Pay once the PSD2 European regulation takes effect on Sept 14, 2019.
[LINK TO DEMO](https://drive.google.com/file/d/145eThy7OW22zL8SUHrtrMJugj21m7NPj/view)
[INT-1616](https://github.com/bigcommerce/bigcommerce/pull/30507)
> INT-1586 [SDK] 3DS on Amazon Pay

- src/checkout-buttons/checkout-button-initializer.spec.ts
- src/checkout-buttons/checkout-button-initializer.ts
- src/checkout/checkout-service.spec.ts
- src/checkout/checkout-service.ts
- src/currency/currency-service.ts
- src/embedded-checkout/embedded-checkout.spec.ts
- src/embedded-checkout/embedded-checkout.ts
- src/embedded-checkout/iframe-content/iframe-embedded-checkout-messenger.spec.ts
- src/embedded-checkout/iframe-content/iframe-embedded-checkout-messenger.ts
- src/embedded-checkout/iframe-content/noop-embedded-checkout-messenger.ts
- src/locale/language-service.spec.ts
- src/locale/language-service.ts
Bind methods to object instances to allow destructing.
So you can destruct the objects, get hold of their methods and call them as if they are standalone functions. i.e.:
```ts
const { loadCheckout } = service;
loadCheckout();
```
It would be useful in cases where I want to pass the functions from one component into another component.
* Unit
> CHECKOUT-4272: Bind methods to object instances to allow destructing

- CHANGELOG.md
* Remove work in progress comments from the changelog
* So it is easier to understand the changelog
@bigcommerce/checkout @bigcommerce/intersys-integrations
> INT-1586: Remove work in progress comments from changelog

- src/payment/is-credit-card-like.spec.ts
- src/payment/is-nonce-like.spec.ts
- src/payment/is-vaulted-instrument.spec.ts
- src/payment/payment.ts
- src/payment/payments.mock.ts
- src/payment/strategies/braintree/braintree-credit-card-payment-strategy.spec.ts
- src/payment/strategies/cybersource/cardinal-client.spec.ts
- src/payment/strategies/cybersource/cardinal-client.ts
- src/payment/strategies/cybersource/cardinal.mock.ts
- src/payment/strategies/cybersource/cardinal.ts
- src/payment/strategies/cybersource/cybersource-payment-strategy.spec.ts
- src/payment/strategies/cybersource/cybersource-payment-strategy.ts
- src/payment/strategies/cybersource/index.ts
Adding BIN Number for vaulted credit cards in the form of the issuer_identification_number (iin), already stored in the BigPay database.
This iin value should be received by Checkout SDK strategy so it can be used in the Cardinal's BIN Detection step.
> feat(payment): INT-1650 Adding IIN field to vaulted instrument strategy

- package-lock.json
- package.json
- src/common/selector/create-selector.spec.ts
- src/common/selector/create-selector.ts
- src/common/selector/create-shallow-equal-selector.spec.ts
- src/common/selector/create-shallow-equal-selector.ts
- src/common/selector/index.ts
- src/common/selector/with-memoized-combiner.spec.ts
- src/common/selector/with-memoized-combiner.ts
- src/common/utility/cache-key-maps.ts
- src/common/utility/cache-key-resolver.spec.ts
- src/common/utility/cache-key-resolver.ts
- src/common/utility/index.ts
- src/common/utility/memoize.spec.ts
- src/common/utility/memoize.ts
Add `reselect` dependency.
This library can help us write more efficient selectors. Currently, we have selectors as objects; and we create them whenever there's a change in the state. But not all of the methods depend on the piece of state that's changed. i.e.:
```ts
@bind
class Selector {
constructor(private state: { a: string, b: string }) {}
getA() {
return this.state.a;
}
getB(message: string) {
return { value: this.state.b, message };
}
}
```
In the example above, 'getA' depends on `state.a` and `getB` depends on `state.b`. When `state` changes, there is no way of knowing whether or not the output of `getA` or `getB` has changed, besides actually calling the methods and comparing the output with the previous result. 
Ideally, what we want is to produce a new `getA` and `getB` if …
> CHECKOUT-4272: Add dependencies needed for refactoring selectors

- src/checkout/checkout-service.spec.ts
- src/order/order-action-creator.spec.ts
- src/order/order-action-creator.ts
- src/order/order-reducer.spec.ts
- src/order/order-reducer.ts
- src/order/spam-protection/index.ts
- src/payment/payment-strategy-action-creator.spec.ts
- src/payment/payment-strategy-action-creator.ts
As per above.
Paypal Express was initializing the modal before recaptcha is completed, and blocked the recaptcha challenge modal.
Added unit tests.
> fix(payment): CHECKOUT-4273 Fix PayPal Express modal does not load when recaptcha is enabled

- src/checkout/create-checkout-store.ts
- src/checkout/create-internal-checkout-selectors.ts
- src/checkout/index.ts
Add a function for creating internal checkout selectors factory.
We need this because we want to create a new set of memoized selectors per `store` instance. Without this, if memoized selectors are defined at the top level, they will be shared across instances, which could cause unexpected results.
Travis
> CHECKOUT-4272: Add function for creating internal checkout selectors factory

- src/checkout/create-internal-checkout-selectors.ts
- src/coupon/coupon-reducer.ts
- src/coupon/coupon-selector.spec.ts
- src/coupon/coupon-selector.ts
- src/coupon/coupon-state.ts
- src/coupon/gift-certificate-reducer.ts
- src/coupon/gift-certificate-selector.spec.ts
- src/coupon/gift-certificate-selector.ts
- src/coupon/gift-certificate-state.ts
- src/coupon/index.ts
* Refactor `CouponSelector` and `GiftCertificateSelector` to return new getters only when there are changes to relevant data.
* Update `couponReducer` and `giftCertificateSelector` to transform state only when it is necessary.
These changes allow us to keep track of changes more efficiently. Currently, in order to make sure we return the same object reference when there are no changes to the return value of a selector, we run a deep object comparison between the old and the new value when the selector is called every time. A better approach is to do a comparison when we write to the data store. This is because we write to store less frequently than we read from it. Also, this approach allows us to memoize the selectors, as we can easily detect whether or not there's a need to re-execute …
> CHECKOUT-4272: Optimise coupon / gift certificate selector and reducer

- src/billing/billing-address-reducer.ts
- src/billing/billing-address-selector.spec.ts
- src/billing/billing-address-selector.ts
- src/billing/billing-address-state.ts
- src/billing/index.ts
- src/checkout/create-internal-checkout-selectors.ts
* Refactor `BillingSelector` to return new getters only when there are changes to relevant data.
* Update `billingReducer` to transform state only when it is necessary.
These changes allow us to keep track of changes more efficiently. Currently, in order to make sure we return the same object reference when there are no changes to the return value of a selector, we run a deep object comparison between the old and the new value when the selector is called every time. A better approach is to do a comparison when we write to the data store. This is because we write to store less frequently than we read from it. Also, this approach allows us to memoize the selectors, as we can easily detect whether or not there's a need to re-execute the selectors. This is especially important for selectors …
> CHECKOUT-4272: Optimise billing selector and reducer

- src/checkout/create-internal-checkout-selectors.ts
- src/order/index.ts
- src/order/order-reducer.ts
- src/order/order-selector.spec.ts
- src/order/order-selector.ts
- src/order/order-state.ts
- src/payment/strategies/afterpay/afterpay-payment-strategy.spec.ts
* Refactor `OrderSelector` to return new getters only when there are changes to relevant data.
* Update `orderReducer` to transform state only when it is necessary.
These changes allow us to keep track of changes more efficiently. Currently, in order to make sure we return the same object reference when there are no changes to the return value of a selector, we run a deep object comparison between the old and the new value when the selector is called every time. A better approach is to do a comparison when we write to the data store. This is because we write to store less frequently than we read from it. Also, this approach allows us to memoize the selectors, as we can easily detect whether or not there's a need to re-execute the selectors. This is especially important for selectors that …
> CHECKOUT-4272: Optimise order selector and reducer

- src/cart/cart-reducer.ts
- src/cart/cart-selector.spec.ts
- src/cart/cart-selector.ts
- src/cart/cart-state.ts
- src/cart/index.ts
- src/checkout/create-internal-checkout-selectors.ts
- src/shipping/consignment-selector.spec.ts
* Refactor `CartSelector` to return new getters only when there are changes to relevant data.
* Update `cartReducer` to transform state only when it is necessary.
These changes allow us to keep track of changes more efficiently. Currently, in order to make sure we return the same object reference when there are no changes to the return value of a selector, we run a deep object comparison between the old and the new value when the selector is called every time. A better approach is to do a comparison when we write to the data store. This is because we write to store less frequently than we read from it. Also, this approach allows us to memoize the selectors, as we can easily detect whether or not there's a need to re-execute the selectors. This is especially important for selectors that …
> CHECKOUT-4272: Optimise cart selector and reducer

- src/payment/payment-request-sender.ts
- src/payment/strategies/stripev3/stripev3-payment-strategy.spec.ts
- src/payment/strategies/stripev3/stripev3-payment-strategy.ts
Remove action to create the Payment Intent needed for StripeV3, instead I'll use the existing `initializations` endpoint (BCApp - BigPay) to retrieve the payment intent
We received a comment from David Aland @IamDavidovich in a PR of BigPay (related with Stripe V3) in why we created a new endpoint to create payment intents, so we had a discussion related with it and we decided to update the approach and use the existing endpoint in BigPay, so that change affects some repos one of them is Checkout-sdk-js
[BCApp]()
[BigPay-Client-PHP](https://github.com/bigcommerce-labs/bigpay-client-php/pull/135)
[BigPay-Client-JS](https://github.com/bigcommerce/bigpay-client-js/pull/81)
[BigPay](https://github.com/bigcommerce/bigpay/pull/1730)
@bigcommerce/checkout @bigcommerce/intersys-integrations
> feat(payment): INT-1768 Payment Intent creation refactor

- src/checkout-buttons/checkout-button-reducer.ts
- src/checkout-buttons/checkout-button-selector.spec.ts
- src/checkout-buttons/checkout-button-selector.ts
- src/checkout-buttons/checkout-button-state.ts
- src/checkout-buttons/index.ts
- src/checkout/create-internal-checkout-selectors.ts
* Refactor `CheckoutButtonSelector` to return new getters only when there are changes to relevant data.
* Update `checkoutButtonReducer` to transform state only when it is necessary.
These changes allow us to keep track of changes more efficiently. Currently, in order to make sure we return the same object reference when there are no changes to the return value of a selector, we run a deep object comparison between the old and the new value when the selector is called every time. A better approach is to do a comparison when we write to the data store. This is because we write to store less frequently than we read from it. Also, this approach allows us to memoize the selectors, as we can easily detect whether or not there's a need to re-execute the selectors. This is especially important …
> CHECKOUT-4272: Optimise checkout button selector and reducer

- src/checkout/create-internal-checkout-selectors.ts
- src/config/config-reducer.ts
- src/config/config-selector.spec.ts
- src/config/config-selector.ts
- src/config/config-state.ts
- src/config/index.ts
- src/form/form-selector.spec.ts
- src/form/form-selector.ts
- src/form/index.ts
* Refactor `ConfigSelector` and `FormSelector` to return new getters only when there are changes to relevant data.
* Update `configReducer` to transform state only when it is necessary.
Unit
> CHECKOUT-4272: Optimise config / form selector and reducer

- src/checkout/create-internal-checkout-selectors.ts
- src/geography/country-reducer.ts
- src/geography/country-selector.spec.ts
- src/geography/country-selector.ts
- src/geography/country-state.ts
- src/geography/index.ts
- src/shipping/index.ts
- src/shipping/shipping-country-reducer.ts
- src/shipping/shipping-country-selector.spec.ts
- src/shipping/shipping-country-selector.ts
- src/shipping/shipping-country-state.ts
* Refactor `CountrySelector` and `ShippingCountrySelector` to return new getters only when there are changes to relevant data.
* Update `countryReducer` and `shippingCountryReducer` to transform state only when it is necessary.
Unit
> CHECKOUT-4272: Optimise country / shipping country selector and reducer

- src/checkout/create-internal-checkout-selectors.ts
- src/customer/customer-reducer.ts
- src/customer/customer-selector.spec.ts
- src/customer/customer-selector.ts
- src/customer/customer-state.ts
- src/customer/customer-strategy-reducer.ts
- src/customer/customer-strategy-selector.spec.ts
- src/customer/customer-strategy-selector.ts
- src/customer/index.ts
* Refactor `CustomerSelector` and `CustomerStrategySelector` to return new getters only when there are changes to relevant data.
* Update `customerReducer` and `customerStrategyReducer` to transform state only when it is necessary.
Unit
> CHECKOUT-4272: Optimise customer / customer strategy selector and reducer

- src/checkout/create-internal-checkout-selectors.ts
- src/shipping/consignment-reducer.ts
- src/shipping/consignment-selector.spec.ts
- src/shipping/consignment-selector.ts
- src/shipping/consignment-state.ts
- src/shipping/index.ts
- src/shipping/shipping-address-selector.spec.ts
- src/shipping/shipping-address-selector.ts
- src/shipping/shipping-strategy-reducer.ts
- src/shipping/shipping-strategy-selector.spec.ts
- src/shipping/shipping-strategy-selector.ts
* Refactor `ShippingSelector` and `ShippingStrategySelector` to return new getters only when there are changes to relevant data.
* Update `shippingReducer` and `shippingStrategyReducer` to transform state only when it is necessary.
Unit
> CHECKOUT-4272: Optimise shipping / shipping strategy selector and reducer

- src/checkout/create-internal-checkout-selectors.ts
- src/payment/instrument/index.ts
- src/payment/instrument/instrument-actions.ts
- src/payment/instrument/instrument-reducer.ts
- src/payment/instrument/instrument-selector.spec.ts
- src/payment/instrument/instrument-selector.ts
- src/payment/instrument/instrument-state.ts
* Refactor `InstrumentSelector` to return new getters only when there are changes to relevant data.
* Update `instrumentReducer` to transform state only when it is necessary.
Unit
> CHECKOUT-4272: Optimise instrument selector and reducer

- src/checkout/create-internal-checkout-selectors.ts
- src/payment/index.ts
- src/payment/payment-method-reducer.ts
- src/payment/payment-method-selector.spec.ts
- src/payment/payment-method-selector.ts
- src/payment/payment-method-state.ts
* Refactor `PaymentMethodSelector` to return new getters only when there are changes to relevant data.
* Update `paymentMethodReducer` to transform state only when it is necessary.
Unit
> CHECKOUT-4272: Optimise payment method selector and reducer

- src/checkout/create-internal-checkout-selectors.ts
- src/payment/index.ts
- src/payment/payment-selector.spec.ts
- src/payment/payment-selector.ts
- src/payment/payment-strategy-reducer.ts
- src/payment/payment-strategy-selector.spec.ts
- src/payment/payment-strategy-selector.ts
* Refactor `PaymentSelector` and `PaymentStrategySelector` to return new getters only when there are changes to relevant data.
* Update `paymentStrategyReducer` to transform state only when it is necessary.
Unit
> CHECKOUT-4272: Optimise payment / payment strategy selector and reducer

- src/checkout/create-internal-checkout-selectors.ts
- src/remote-checkout/index.ts
- src/remote-checkout/remote-checkout-reducer.ts
- src/remote-checkout/remote-checkout-selector.spec.ts
- src/remote-checkout/remote-checkout-selector.ts
- src/remote-checkout/remote-checkout-state.ts
* Refactor `RemoteCheckoutSelector` to return new getters only when there are changes to relevant data.
* Update `remoteCheckoutReducer` to transform state only when it is necessary.
Unit
> CHECKOUT-4272: Optimise remote checkout selector and reducer

- package-lock.json
- package.json
- src/checkout/checkout-service.spec.ts
- src/checkout/checkout-service.ts
- src/checkout/checkout-store-error-selector.spec.ts
- src/checkout/checkout-store-error-selector.ts
- src/checkout/checkout-store-selector.spec.ts
- src/checkout/checkout-store-selector.ts
- src/checkout/checkout-store-status-selector.spec.ts
- src/checkout/checkout-store-status-selector.ts
- src/checkout/create-checkout-selectors.ts
- src/checkout/index.ts
- src/common/utility/clone-result.ts
- src/common/utility/index.ts
Refactor `CheckoutSelectors` to return new getters only when there are changes to relevant data.
Unit
> CHECKOUT-4272: Optimise checkout external selectors

- src/common/utility/array-replace.spec.ts
- src/common/utility/array-replace.ts
Keep two counters - one for counting the number of new items, another one for counting the number of original items. Return the new array if all items in the mapped array are new items from the new array. Return the original array if all items in the mapped array are original items from the original array. Otherwise, return the mapped array, which could contain either merged item, new item or original item.
The current condition before this change would return the original array if both the original and new array contains the same set of entities but differ in some of their properties. This is because it cannot distinguish between what is new versus what is merged. Basically, to achieve what's described above, we need to be sure that the items in the mapped array exactly match the …
> CHECKOUT-4272: Fix immutable array replacer as it returns original array instead of merged array

- src/payment/strategies/cybersource/cardinal-client.spec.ts
- src/payment/strategies/cybersource/cardinal-client.ts
- src/payment/strategies/cybersource/cardinal.mock.ts
- src/payment/strategies/cybersource/cardinal.ts
- src/payment/strategies/cybersource/cybersource-payment-strategy.spec.ts
- src/payment/strategies/cybersource/cybersource-payment-strategy.ts
[INT-1736](https://jira.bigcommerce.com/browse/INT-1736)
Add Reference Id in the jwt token used to initialize the Cardinal client and use the same Reference Id in the check_enrollment request to CyberSource. Also prevent that the Cardinal client is initialized multiple time with different tokens. According to the Cardinal documentation the `Cardinal.setup` method must only be called once in the page.
For CyberSource's Hybrid Flow, the response received from Cardinal after the User is Authenticated with 3DS will not have an "ActionCode" value. So we need to update the logic to handle this response so that "ActionCode" is NOT the primary value to verify the status of the transaction.
Cardinal requires a reference Id value to be included in the JWT token when initializing the cardinal …
> feat(payment): INT-1736 Add ReferenceId in the jwt to initialize the Cardinal client

- src/checkout/checkout-service.spec.ts
- src/common/utility/clone-result.spec.ts
- src/common/utility/clone-result.ts
Fix the problem where getters are not returning previous cloned objects even when they are unchanged. This problem affects objects that are nested inside another. For example.: `Checkout` object has several child objects, such as `payments`, `consignments`, `billingAddress` etc... 
The intention is for the references to these sub-objects to remain unchanged unless the value of their properties changes. In other words, if `consignments` collection changes because the shopper has selected a different shipping option, the reference to `billingAddress` should remain the same; only `consignments` and the top-level `checkout` object should have a different reference (a new reference because all objects are immutable). 
The change detection mechanism all works fine internally after the the …
> CHECKOUT-4321: Fix getters not returning previous cloned objects that are nested inside another even when they are unchanged.

- src/payment/strategies/cybersource/cybersource-payment-strategy.spec.ts
- src/payment/strategies/cybersource/cybersource-payment-strategy.ts
[INT-1811](https://jira.bigcommerce.com/browse/INT-1811)
Fix enrolled card Issue on Cybersource
The issue was introduced in a PR for PayPal Pro since Cybersource and PayPal Pro will be using the same component for Cardinal.
[INT-1620](https://github.com/bigcommerce/bigpay/pull/1724)
@bigcommerce/checkout @bigcommerce/payments @bigcommerce-labs/intersys-integrations
> INT-1811 Cannot place order with CyberSource 3DS

- src/payment/create-payment-strategy-registry.ts
- src/payment/payment-methods.mock.ts
- src/payment/strategies/cardinal/cardinal-client.spec.ts
- src/payment/strategies/cardinal/cardinal-client.ts
- src/payment/strategies/cardinal/cardinal-script-loader.spec.ts
- src/payment/strategies/cardinal/cardinal-script-loader.ts
- src/payment/strategies/cardinal/cardinal-three-d-secure-flow.spec.ts
- src/payment/strategies/cardinal/cardinal-three-d-secure-flow.ts
- src/payment/strategies/cardinal/cardinal.mock.ts
- src/payment/strategies/cardinal/cardinal.ts
- src/payment/strategies/cardinal/index.ts
- src/payment/strategies/cybersource/cybersource-payment-strategy.spec.ts
- src/payment/strategies/cybersource/cybersource-payment-strategy.ts
- src/payment/strategies/cybersource/index.ts
- src/payment/strategies/paypal/paypal-pro-payment-strategy.spec.ts
- src/payment/strategies/paypal/paypal-pro-payment-strategy.ts
Transform the existing Cybersource's stategy to be the Cardinal's one and also modify the existing Paypal's strategy to be extended from Cardinal's strategy
Existing Cybersource's strategy contains all of the logic for Cardinal flow and it is totally transparent for other strategies who want to use it so we renamed it to Cardinal strategy and also extended Paypal Payments Pro's strategy from it
[video | authorize](https://drive.google.com/open?id=14Wr6-X3cgo5V8Q9c8opUeyWY9ilQA3ew)
[video | purchase](https://drive.google.com/open?id=1LcC67x4A-PIeLTnap_V6FvHPKfETrg8W)
[bigpay](https://github.com/bigcommerce/bigpay/pull/1711)
[bcapp](https://github.com/bigcommerce/bigcommerce/pull/30475)
[bigpay](https://github.com/bigcommerce/bigpay/pull/1724) …
> feat(payment): INT-1608 Modify Paypal Payments Pro's strategy for 3DS

- src/common/iframe/iframe-resizer.spec.ts
- src/common/iframe/iframe-resizer.ts
- src/common/iframe/index.ts
- src/embedded-checkout/embedded-checkout.spec.ts
- src/embedded-checkout/embedded-checkout.ts
- src/embedded-checkout/resizable-iframe-creator.spec.ts
- src/embedded-checkout/resizable-iframe-creator.ts
Only set up event listeners for the iframe resizer when it is in use.
Otherwise, the event listeners (window resize etc...) will take up CPU resources and affect performance.
CircleCI
> CHECKOUT-4272: Only set up event listeners for iframe resizer when it is in use

- src/payment/strategies/cardinal/cardinal-client.spec.ts
- src/payment/strategies/cardinal/cardinal-client.ts
Remove an error validation prior to resolve a promise if no action code is present in the `payments.validated` event
Cybersource needs to validate the `jwt` by itself even if an error is present
https://drive.google.com/open?id=1-4fJAJlRwQ6b3bHSiqqf3azJsSIaw1mU
> fix(payment): INT-1829 Remove error validation if no action code is present

- src/common/iframe/iframe-resizer.ts
- src/embedded-checkout/iframe-content/create-embedded-checkout-messenger.ts
- src/embedded-checkout/iframe-content/index.ts
Mark the index file of Embedded Checkout as a file with side effects.
* Otherwise, `iframeResizer.contentWindow`, which is used in the index file, gets stripped out.
* It appears the file has been stripped out since the beginning. But the problem doesn't affect anything because the file is also exported in the index file of `iframeResizer` package. When the package gets imported, it also imports `iframeResizer.contentWindow`, which performs some side effect calls (i.e.: setting up event listeners). But since the change introduced by #679, we no longer require `iframeResizer` inside the iframe, which means `iframeResizer.contentWindow` from `iframeResizer` also doesn't get required and executed.
* The workaround for this problem is simply to require `iframeResizer.contentWindow` in …
> CHECKOUT-4388: Mark index file of Embedded Checkout as file with side effect

- src/order/spam-protection/google-recaptcha.spec.ts
- src/order/spam-protection/google-recaptcha.ts
As per above.
After we got the spam protection token from Google for the first failed attempt to place an order, the callback will not be called the second time, and this caused it to get stuck. After this fix, we will reset after we got the token, so that if the first attempt failed, callback will still be called for the second attempt, also Google does not allow to reuse the token
Manual testing. Placed an order successfully after failing the a few attempt:
> fix(order): CHECKOUT-4393 Fix could not resubmit order after failed attempt

- src/common/url/parse-url.ts
- src/embedded-checkout/loading-indicator.ts
* Get the origin of URL by constructing it manually. IE11 doesn't support `HTMLHyperlinkElementUtils#origin` according to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/HTMLHyperlinkElementUtils/origin). So we can't use it to get the origin of URL. Also, we can't get it by creating `URL` instance because IE11 doesn't support it as well.
* Provide an index position when inserting CSS rule. According to the [doc](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/insertRule), the index parameter is not optional for IE11.
Otherwise, Embedded Checkout won't load in IE11.
Manual
> CHECKOUT-4427: Fix IE11 issues for Embedded Checkout

- src/order/map-to-internal-order.ts
- src/shipping/consignment-action-creator.ts
Use lodash `find` instead of `Array.protoype.find`
To avoid need of polyfills. https://github.com/bigcommerce/checkout-sdk-js/issues/681
unit
> #681 Use Lodash find

- src/checkout/checkout-default-includes.ts
- src/checkout/checkout-request-sender.spec.ts
- src/coupon/coupon-request-sender.spec.ts
- src/coupon/gift-certificate-request-sender.spec.ts
- src/customer/customer.ts
- src/customer/customers.mock.ts
- src/customer/internal-customers.mock.ts
- src/customer/map-to-internal-customer.ts
- src/store-credit/store-credit-request-sender.spec.ts
Fixing ticket CHECKOUT-4415: After CHECKOUT-4405 (API and checkoutSDK to support Customer Group) has been merged, Checkout SDK needs to be updated to retrieve the customer group as part of the customer information by requesting `customer.customerGroup`
e.g. https://my-dev-store-574230549.store.bcdev/api/storefront/checkout/08efed69-92fd-41c5-ba58-60a9aa0313e7?include=customer.customerGroup
Mainly to fix the issue PAYMENTS-4691: CyberSource Field 90 (Customer Group) Does Not Get Passed on UCO
Unit Testing
Screenshots
ping @bigcommerce-labs/payments
ping @bigcommerce/checkout 
ping @bigcommerce/payments
> fix(shopper): CHECKOUT-4415 Add Customer Group to Customer object in payments payload

- src/customer/customer.ts
- src/customer/map-to-internal-customer.ts
Check if `customerGroup` is defined before accessing it.
It can be undefined (i.e.: a guest shopper always doesn't belong to a group; also a returning shopper may not belong to a group).
Manual
> CHECKOUT-4415: Check if `customerGroup` is defined before accessing it

- src/order/order.ts
- src/order/orders.mock.ts
- src/payment/strategies/amazon-pay/amazon-pay-payment-strategy.spec.ts
- src/payment/strategies/amazon-pay/amazon-pay-payment-strategy.ts
[INT-1759](https://jira.bigcommerce.com/browse/INT-1759)
We started retrieving the orderReferenceId from order to use the same value when InvalidPaymentMethod or MFA-Abandoned occurs we do not want to generate another orderReferenceId in this cases
We do not want to hit the amazon endpoint for generating another orderReferenceId because we already have one
[INT-1744 BCAPP](https://github.com/bigcommerce/bigcommerce/pull/31095)
> INT-1759 Using same order reference ID when an error occurs

- src/checkout-buttons/strategies/braintree/braintree-paypal-button-options.ts
- src/checkout-buttons/strategies/braintree/braintree-paypal-button-strategy.spec.ts
- src/checkout-buttons/strategies/braintree/braintree-paypal-button-strategy.ts
Allow to pass a shipping address when initialising Braintree PayPal.
For backwards compatibility, if none is provided, we would still pick the first customer address.
https://github.com/bigcommerce/checkout-sdk-js/issues/640
Give more control to the SDK client and allow them to decide what value should be passed. 
unit
> 640 Add shippingAddress initial param for Braintree PayPal

- CONTRIBUTING.md
Update the instruction on how to release a new version.
To keep it up-to-date.
None
> CHECKOUT-4428: Update instruction on releasing new version

- src/embedded-checkout/embedded-checkout.spec.ts
- src/embedded-checkout/embedded-checkout.ts
- src/embedded-checkout/iframe-content/iframe-embedded-checkout-messenger.spec.ts
- src/embedded-checkout/iframe-content/iframe-embedded-checkout-messenger.ts
Only redirect to `/embedded-checkout/allow-cookie` (which is a workaround for setting third-party cookies) if sufficient time has passed since the last redirect.
You could receive an error from the iframe of Embedded Checkout if there's no cart ID associated with your session. You could also receive the same type of error if your browser is unable to store your session ID in cookies. For the first scenario, you could end up in a redirect loop, because you will never be able to load EC if there's no cart. Unfortunately, there's no way to differentiate between the two. So to work around this problem, we should first check to see if we have recently redirected before doing the redirect. If we have and still can't load EC page, then we know the problem is due to the fact that you don't have …
> CHECKOUT-4462: Handle scenario where there is no cart ID in session versus unable to store session ID in cookies due to browser setting

- src/order/spam-protection/google-recaptcha.spec.ts
- src/order/spam-protection/google-recaptcha.ts
As per above
When the browser language is set to german, the iframe title is different, but coming from the same source.
Updated unit test and manual testing.
Able to place order after the changes:
> fix(order): CHECKOUT-4450 Fix recaptcha iframe not found for german language

- src/checkout/checkout-store-status-selector.spec.ts
- src/checkout/checkout-store-status-selector.ts
- src/order/order-reducer.spec.ts
- src/order/order-reducer.ts
- src/order/order-selector.spec.ts
- src/order/order-selector.ts
- src/order/order-state.ts
- src/order/spam-protection/errors/index.ts
- src/order/spam-protection/errors/spam-protection-not-loaded-error.spec.ts
- src/order/spam-protection/errors/spam-protection-not-loaded-error.ts
- src/order/spam-protection/google-recaptcha.spec.ts
- src/order/spam-protection/google-recaptcha.ts
As per above.
Previously, when the shopper is on slow connection, the recaptcha challenge window might not finish loading when the shopper place an order. This will cause the checkout-sdk to throw an error and the UI will stop working, but there is no indication to the shopper on that is happening.
With this fix, we will handle this situtation gracefully. We will retry multiple times within a 7 second timeframe when the user place an order. If after 7 seconds the recaptcha challenge window has yet to finish loading, we will throw an error, but not block the UI. Shopper can then retry by trying to place order again.
Added unit tests and manual testing.
Place an order on slow 3g connection:
> fix(order): CHECKOUT-4450 Handle recaptcha challenge not finish loading on slow connection

- src/payment/create-payment-strategy-registry.ts
- src/payment/strategies/adyenv2/adyenv2-initialize-options.ts
- src/payment/strategies/adyenv2/adyenv2-payment-strategy.spec.ts
- src/payment/strategies/adyenv2/adyenv2-payment-strategy.ts
- src/payment/strategies/adyenv2/adyenv2-script-loader.ts
- src/payment/strategies/adyenv2/adyenv2.mock.ts
- src/payment/strategies/adyenv2/adyenv2.ts
3DS 2.0 should show in a modal and you should not be able to do anything else. As well the loading icon keeps showing see screenshot.
AdyenV2 Feedback
[UCO](https://github.com/bigcommerce/checkout-js/pull/120)
> feat(payment): INT-1901 Use modal to handle 3DS

- src/common/utility/array-replace.spec.ts
- src/common/utility/array-replace.ts
- Make sure the default matcher takes into account objects without id
- When objects in an array don't contain an `id` key, the default matcher
will think they are the same object causing incorrect merges.
- Unit
> fix(common): PAYMENTS-4802 Fix ArrayReplace default comparison

- package-lock.json
- package.json
- src/payment/create-payment-strategy-registry.ts
- src/payment/strategies/adyenv2/adyenv2-payment-strategy.spec.ts
- src/payment/strategies/adyenv2/adyenv2-script-loader.spec.ts
- src/payment/strategies/adyenv2/adyenv2-script-loader.ts
- src/payment/strategies/amazon-pay/amazon-pay-script-loader.ts
Upgrade `script-loader` version.
The newer version can load stylesheets, so we can remove the `loadStylesheet` method in `AdyenV2ScriptLoader`.
CircleCI
> CHECKOUT-4455: Upgrade `script-loader` version

- package-lock.json
- package.json
- src/common/data-store/cache-action.spec.ts
- src/embedded-checkout/embedded-checkout.spec.ts
Upgrade `rxjs` version
Dependabot is unable to [upgrade](https://github.com/bigcommerce/checkout-sdk-js/pull/586) due to incompatibility.
CircleCI
> CHECKOUT-4499: Upgrade `rxjs` version

- src/shipping/shipping-option.ts
- src/shipping/shipping-options.mock.ts
Extend ShippingOption interface
Add `additionalDescription` to shipping-option interface, so we can use the field in checkout-js to be displayed to customers.
- Unit / Functional / Manual
> fix(shipping): SHIPPING-1384 Extend shipping option interface

- src/cart/cart-reducer.spec.ts
- src/cart/cart-reducer.ts
- src/checkout/checkout-reducer.spec.ts
- src/checkout/checkout-reducer.ts
Update the Cart summary on the checkout page if the user's cart is updated on a different tab or window. 
Existing Behavior: 
User changes quantity in a different tab (cart page)
User is prompted with an error on checkout page but quantity and price is not updated.
User selects the shipping address and the update to the cart summary is reflected.
New Behavior: 
User Changes quantity in a different tab(cart page)
User is prompted with an error on checkout page and the quantity is updated keeping the previous shipping address.
If user updates the shipping address the cart summary is changed accordingly else remains the same.
The error message provides a feedback to the shopper that the cart has been updated. However the updated summary is displayed only after he/she confirms the shipping …
> fix(checkout): CHECKOUT-3365 Update cart and checkout state when shipping options are loaded

- package-lock.json
- package.json
- src/checkout/checkout-store-selector.ts
- src/payment/errors/index.ts
- src/payment/errors/payment-instrument-not-valid-error.spec.ts
- src/payment/errors/payment-instrument-not-valid-error.ts
- src/payment/instrument/instrument-reducer.spec.ts
- src/payment/instrument/instrument-response-body.ts
- src/payment/instrument/instrument-response-transformer.spec.ts
- src/payment/instrument/instrument-response-transformer.ts
- src/payment/instrument/instrument-selector.spec.ts
- src/payment/instrument/instrument-selector.ts
- src/payment/instrument/instrument.mock.ts
- src/payment/instrument/instrument.ts
- src/payment/instrument/map-to-account-instrument.spec.ts
- src/payment/instrument/map-to-account-instrument.ts
- src/payment/instrument/map-to-card-instrument.spec.ts
- src/payment/instrument/map-to-card-instrument.ts
- src/payment/instrument/supported-payment-instruments.ts
- src/payment/strategies/cardinal/cardinal-three-d-secure-flow.spec.ts
- src/payment/strategies/cardinal/cardinal-three-d-secure-flow.ts
- Add support for account instruments
- Add support to filter instruments based on payment method type
- We want to support account-type instruments required for paypal vaulting
- We would like to future proof the SDK so new instruments added to the API don't break old copies of the Checkout SDK.
- **From now onwards:** In order to instrument types that are not of type `card` you need to provide the `paymentMethod` to `getAllInstruments`
- Unit / Functional
> PAYMENTS-4759 Add support to get and filter instruments

- src/checkout/checkout-store-selector.spec.ts
- src/checkout/checkout-store-selector.ts
- src/payment/instrument/index.ts
- src/payment/instrument/instrument-reducer.ts
- src/payment/instrument/instrument-response-body.ts
- src/payment/instrument/instrument-response-transformer.ts
- src/payment/instrument/instrument-selector.spec.ts
- src/payment/instrument/instrument-selector.ts
- src/payment/instrument/instrument-state.ts
- src/payment/instrument/instrument.mock.ts
- src/payment/instrument/instrument.ts
- src/payment/instrument/supported-payment-instruments.ts
- src/payment/strategies/cardinal/cardinal-three-d-secure-flow.spec.ts
- src/payment/strategies/cardinal/cardinal-three-d-secure-flow.ts
Make sure new instrument types stay backward compatible.
My previous commits in https://github.com/bigcommerce/checkout-sdk-js/pull/730 broke backward compatibility, this PR aims to fix that.
We overloaded the `getInstruments` method so it is backward compatible. It returns `CardInstrument` when you don't specify a payment method and all types (PaymentInstrument) if you ask for a specific instrument type.
- Unit / Functional / Manual
I've checked in `checkout-js` master and both `npm run build` & `npm run test` run without problems using this version of the checkout.
The only changed required is adjusting the `Instrument` mock.
> fix(payment): PAYMENTS-4759 Make Instrument types backward compatible

- src/payment/payment.ts
- src/payment/strategies/braintree/braintree-payment-processor.spec.ts
- src/payment/strategies/braintree/braintree-payment-processor.ts
- src/payment/strategies/braintree/braintree-paypal-payment-strategy.spec.ts
- src/payment/strategies/braintree/braintree-paypal-payment-strategy.ts
- src/payment/strategies/braintree/braintree.ts
- Use an object to configure `BraintreePaypal`
- Support for paying with `BraintreePaypal` vaulted accounts
- Support for vaulting `BraintreePaypal` accounts
- Bump `@bigcommerce/bigpay-client` to support `formattedPayload`
- Paypal Vaulting Support
- Unit / Functional
> PAYMENTS-4616 Allow vaulting and paying with BraintreePaypal accounts

- src/payment/instrument/supported-payment-instruments.ts
- As per title
- In order to read instruments from braintree.paypal, we need the instrument type to be whitelisted
> PAYMENTS-4616 Add braintree.paypal as a supported instrument

- src/checkout/checkout-params.ts
- src/checkout/checkout-request-sender.ts
- src/checkout/checkout-service.ts
- src/checkout/index.ts
- src/common/http-request/index.ts
- src/common/http-request/join-includes.ts
- src/common/http-request/join-or-merge-includes.ts
- src/common/http-request/merge-includes.ts
- src/shipping/consignment-action-creator.ts
- src/shipping/consignment-request-sender.spec.ts
- src/shipping/consignment-request-sender.ts
- src/shipping/shipping-request-options.ts
Add param to optionally exclude shipping options
At the moment we always include shipping options when shipping address is updated. Sometimes we want to update fields that we know won't affect shipping, so it's savy not to fetch shipping options in this scenario.
unit
Coverage:
> CHECKOUT-4509 Optional param to exclude shippings options

- src/payment/payment-strategy-registry.ts
- src/payment/strategies/offsite/offsite-payment-strategy.ts
Add barclaycard to offsite strategy and payment strategy registry validations.
To make barclaycard compatible with the offsite-payment-strategy.
https://github.com/bigcommerce/checkout-js/pull/143
> feat(checkout): INT-1916 Make barclaycard compatible with offsite strategy

- src/form/form-selector.spec.ts
- src/form/form-selector.ts
- src/geography/countries.mock.ts
- src/geography/country-reducer.spec.ts
- src/geography/country.ts
- src/shipping/shipping-countries.mock.ts
- src/shipping/shipping-country-reducer.spec.ts
The backend would now return list of countries along with a flag for each country that specifies if the state or province is required for that country. The functionality is currently guarded by an experiment, value for which is also part of the country response. 
Based on the experiment toggle and the value of the requireState flag the state/province field will be made required/optional in both the billing and shipping address.
Certain countries don't need the state/province as a mandatory field to uniquely identify billing or shipping address. For these countries shopper should be allowed to save his/her billing and shipping address without selecting the state or province. 
Unit test cases updated accordingly and pass. Values verified in DB and behaviour toggles with change in DB values. …
> feat(checkout): CHECKOUT-4465 Make state/province optional for certain countries based on requireState flag

- package-lock.json
- package.json
- src/checkout-buttons/strategies/paypal/paypal-button-strategy.spec.ts
- src/checkout-buttons/strategies/paypal/paypal-button-strategy.ts
- src/payment/strategies/paypal/paypal-script-loader.spec.ts
- src/payment/strategies/paypal/paypal-script-loader.ts
Add merchant ID on PayPal button script for PayPal Express Checkout
**Note**: we are going refactor this solution later: move some part of implemented here JS logic to https://github.com/bigcommerce/script-loader-js library but we need to make sure first that merchant ID is received on PayPal side.
The PayPal Shopping feature should know which merchants to target for PayPal Store Cash
[Video with STR](https://drive.google.com/file/d/1Tm6pURoteWNBYMh2J8_2j8x9VB3V7T7-/view?usp=sharing)
> feat(payments): PAYPAL-7 Pass in merchant ID on PayPal button script for PayPal Express Checkout

- src/cart/line-item.ts
- src/cart/line-items.mock.ts
Add type to SDK
Expose extendedComparisonPrice to checkout and fix the inc/ex tax strike-through issue.
price inc tax, show ex tax (no discount):
Before:
After:
price ex tax, show in tax (no discount):
Before:
After:
> fix(checkout): CHECKOUT-4513 Add extendedComparisonPrice from API

- src/common/selector/create-shallow-equal-selector.ts
- src/common/utility/cache-key-resolver.ts
- src/embedded-checkout/embed-checkout.spec.ts
- src/locale/language-service.ts
- tsconfig-jest.json
- tsconfig.json
Allow synthetic default imports.
So it is easier import CommonJS packages that don't have a default export, as I'll soon need to import and use `card-validator` and `credit-card-type` packages. They both don't have a default export.
CircleCI
> CHECKOUT-4203: Allow synthetic default imports

- src/hosted-form/hosted-field.ts
- src/hosted-form/iframe-content/hosted-input-aggregator.spec.ts
- src/hosted-form/iframe-content/hosted-input-aggregator.ts
- src/hosted-form/iframe-content/hosted-input-validator.spec.ts
- src/hosted-form/iframe-content/hosted-input-validator.ts
- src/hosted-form/iframe-content/hosted-input-window.ts
- src/hosted-form/iframe-content/hosted-input.spec.ts
- src/hosted-form/iframe-content/hosted-input.ts
Add `HostedInput` class, which is responsible for accepting user inputs inside an iframe.
It is intended to be loaded and initialised inside a hosted field iframe. It also acts as a base class for specialised fields, such as card number and expiry field.
CircleCI
> CHECKOUT-4203: Add text input element responsible for accepting user input inside iframe

- package-lock.json
- package.json
Bump bigpay-client-js version to send transit times where applicable
https://jira.bigcommerce.com/browse/PROJECT-3123 - transit time will be used by Cybersource for fraud scoring
Manual testing: 
https://github.com/bigcommerce/bigpay-client-js/pull/90
Manual and unit tests: 
https://github.com/bigcommerce/bigpay/pull/2009
@jvpcode @bigcommerce/payments
> PAYMENTS-4848 

- src/hosted-form/iframe-content/index.ts
- src/hosted-form/index.ts
- src/payment/create-payment-strategy-registry.ts
- src/payment/payment-request-options.ts
- src/payment/payment-strategy-action-creator.spec.ts
- src/payment/strategies/credit-card/credit-card-payment-initialize-options.ts
- src/payment/strategies/credit-card/credit-card-payment-strategy.spec.ts
- src/payment/strategies/credit-card/credit-card-payment-strategy.ts
- src/payment/strategies/credit-card/index.ts
- src/payment/strategies/wepay/wepay-payment-strategy.spec.ts
- src/payment/strategies/wepay/wepay-payment-strategy.ts
Use a hosted payment form to accept credit card details if the feature is enabled.
This allows us to roll out the feature gradually.
CircleCI
> CHECKOUT-4203: Use hosted payment form for credit card payment if feature is enabled

- src/common/iframe/iframe-event-poster.ts
- src/hosted-form/errors/index.ts
- src/hosted-form/errors/invalid-hosted-form-value-error.ts
- src/hosted-form/hosted-field-events.ts
- src/hosted-form/hosted-field.ts
- src/hosted-form/hosted-form-factory.ts
- src/hosted-form/hosted-form-options.ts
- src/hosted-form/hosted-form.spec.ts
- src/hosted-form/hosted-form.ts
- src/hosted-form/iframe-content/hosted-input-events.ts
- src/hosted-form/iframe-content/hosted-input-initializer.ts
- src/hosted-form/iframe-content/hosted-input-payment-handler.spec.ts
- src/hosted-form/iframe-content/hosted-input-payment-handler.ts
- src/hosted-form/iframe-content/hosted-input-validate-results.ts
- src/hosted-form/iframe-content/hosted-input-validator.spec.ts
- src/hosted-form/iframe-content/hosted-input-validator.ts
- src/hosted-form/iframe-content/hosted-input.spec.ts
- src/hosted-form/iframe-content/hosted-input.ts
- src/hosted-form/iframe-content/index.ts
- src/payment/strategies/credit-card/credit-card-payment-strategy.spec.ts
- src/payment/strategies/credit-card/credit-card-payment-strategy.ts
* Change `onValidateError` callback to `onValidate`. It is now called every time the hosted fields are validated instead of only when an error is detected. It is better this way because not only we need to tell the caller when a validation error occurs so it can display an error message to the end user; we also have to tell the caller when it is fixed so it can remove the error message from the UI.
* Pass the error `type` to the caller when a validation error occurs, i.e.: `invalid_card_number`. The caller can then check the `type` property and display a translated error message accordingly.
* Add a `validate` method to `HostedForm` so it is possible to validate the hosted fields before submitting an order.
Without these changes, it's more difficult for the client app to handle validation …
> CHECKOUT-4205: Improve the way validation errors are returned to the caller

- README.md
Remove the CircleCI badge.
Ever since we've changed our release process, the badge has been showing up as "failed". I think it's because our tag commit is marked as "skipped". As it doesn't get run, it shows up as "failed". I don't really want to spend time figuring out why the badge doesn't show up properly so I'm just going to remove it.
None
> CHECKOUT-4205: Remove CircleCI badge

- src/checkout/checkout-store-selector.spec.ts
- src/checkout/checkout-store-selector.ts
Preselect billing country when billing address has not been set
So customers don't have to manually preselect country in billing section. This way, if merchant has google autocomplete feature, customers will get suggestions as they type address line 1 in billing section, without having to select a country first.
unit
> CHECKOUT-4421 Preselect billing country when billing address has not been set

- src/analytics/analytics-step-tracker.spec.ts
- src/analytics/analytics-step-tracker.ts
- src/analytics/analytics-tracker-window.ts
- src/analytics/create-step-tracker.spec.ts
- src/analytics/create-step-tracker.ts
- src/analytics/index.ts
- src/analytics/is-analytics-step-tracker-window.ts
- src/analytics/noop-step-tracker.ts
- src/analytics/step-tracker.ts
- src/cart/internal-carts.mock.ts
- src/cart/line-items.mock.ts
- src/checkout/checkouts.mock.ts
- src/config/index.ts
- src/index.ts
Adds step tracker service. This has been extracted from https://github.com/bigcommerce/checkout-js/tree/master/src/app/analytics with the difference that the backfill is off by default, and a custom step order can be passed.
So custom checkouts built using Checkout SDK can benefit from enhance e-commerce.
unit
> CHECKOUT-4571 Add StepTracker service

- src/checkout/checkout-store-selector.spec.ts
- src/checkout/checkout-store-selector.ts
Return the billing address if it is partially complete and the geo IP of the shopper can't be determined.
Otherwise, if the geo IP can't be determined, `getBillingAddress` will always returned undefined even if `email` is already provided for the billing address.
Unit
> CHECKOUT-4421: Return billing address if it is partially complete

- src/payment/instrument/supported-payment-instruments.ts
Change how barclaycard's supported Instruments are mapped.
After https://github.com/bigcommerce/checkout-sdk-js/pull/743 was merged, supported Instruments mapping method changed while barclaycard was in development, it must be changed to match with the new mapping method used so the vaulted cards can be displayed.
> fix(payments): INT-2195 Fix barclaycard supported instrument mapping

- src/payment/strategies/adyenv2/adyenv2-initialize-options.ts
- src/payment/strategies/adyenv2/adyenv2-payment-strategy.spec.ts
- src/payment/strategies/adyenv2/adyenv2-payment-strategy.ts
- src/payment/strategies/adyenv2/adyenv2-script-loader.spec.ts
- src/payment/strategies/adyenv2/adyenv2-script-loader.ts
- src/payment/strategies/adyenv2/adyenv2.mock.ts
- src/payment/strategies/adyenv2/adyenv2.ts
Added support fort encrypted information for vaulted instruments and TSV on AdyenV2
According to PCI compliance on Adyen, we need to also encrypt cvv and credit card number for TSV vaulted instruments
Ping @bigcommerce/payments @bigcommerce/intersys-integrations
> refactor(provider): Use AdyenV2 custom card components for TSV and vaulting

- package-lock.json
- package.json
Bump bigpay-client version to 5.4.1
https://github.com/bigcommerce/checkout-sdk-js/blob/master/CHANGELOG.md
CircleCI
> fix(payment): PAYMENTS-5037 Bump bigpay-client version to 5.4.1

- src/payment/instrument/map-to-card-instrument.ts
Unpatch method mapToCardInstrument to remove _instrument.method === 'card' ? 'credit_card' : instrument.method_ and just keep _instrument.method_
This change is already agreed with @icatalina & @IamDavidovich to keep the code clean.
No tests affected
@bigcommerce/checkout @bigcommerce/intersys-integrations
> fix(payment): INT-2140 Unpatch mapToCardInstrument

- src/hosted-form/hosted-field.spec.ts
- src/hosted-form/hosted-field.ts
- src/hosted-form/hosted-form-factory.ts
Reload the checkout page if, for some reason, the form expires or invalidates after the initial page load.
This error scenario can potentially happen. This is a measure to prevent it from happening. By reloading the page, the shopper can generate a new payment form and recover from the error.
I've also added in a check to make sure the shopper won't get into a redirect loop - just in case if there's anything unexpected that prevents the recovery attempt from working.
CircleCI
> CHECKOUT-4205: Reload checkout page if for some reason form expires or invalidates after initial page load

- src/coupon/coupon-reducer.spec.ts
- src/coupon/coupon-reducer.ts
Update coupon state when shipping option is updated successfully.
Because some coupon codes are linked to specific shipping options. If a coupon linked to a shipping option was added, but then a different shipping option was selected, the API automatically removes the coupon code. We need to reflect this in the checkout state otherwise it will cause problems preventing checking out.
unit
> CHECKOUT-3818 Update coupon state when shipping option is updated

- scripts/circleci/update-server.sh
Push branch to static server repo instead
For now, we can't make PRs directly.
None
> CHECKOUT-4187: Push branch to static server repo instead

- src/common/browser-info/browser-info.ts
- src/common/browser-info/get-browser-info.spec.ts
- src/common/browser-info/get-browser-info.ts
- src/common/browser-info/index.ts
- src/payment/is-vaulted-instrument.ts
- src/payment/payment-request-transformer.ts
- src/payment/payment.ts
- src/payment/strategies/adyenv2/adyenv2-payment-strategy.ts
BrowserInfo values are now sent from frontEnd to backEnd, this variable send this info: 
```
{
userAgent,
acceptHeader,
language,
colorDepth,
screenHeight,
screenWidth,
timeZoneOffset,
javaEnabled
}
```
Adyen V2 needs browserInfo values direct from the browser to the backend to handle 3DS validations
> feat(payment): INT-1990 Resolve browser info for Adyen v2

- src/payment/strategies/sage-pay/sage-pay-payment-strategy.spec.ts
- src/payment/strategies/sage-pay/sage-pay-payment-strategy.ts
The target value for SagePay's 3DS form submission should be `_top` instead of `top`.
Otherwise, it's not a valid value. The browser will perform the form submission redirect in a new window instead of the topmost window.
CircleCI
> CHECKOUT-4655: Fix SagePay form post target value

- src/payment/instrument/supported-payment-instruments.ts
Rename supported payment instrument to `credit_card`.
To match with the new naming convention, so the stored credit cards are able to be  displayed and used.
https://github.com/bigcommerce/bigpay/pull/2181
https://github.com/bigcommerce/bigcommerce/pull/33239
> feat(payment): INT-2286 Use credit_card as payment method instead of card

- src/billing/billing-address-selector.ts
- src/checkout/checkout-selector.ts
- src/common/utility/guard.spec.ts
- src/common/utility/guard.ts
- src/common/utility/index.ts
- src/hosted-form/hosted-form.spec.ts
- src/hosted-form/hosted-form.ts
- src/hosted-form/iframe-content/hosted-card-number-input.spec.ts
- src/hosted-form/iframe-content/hosted-card-number-input.ts
- src/hosted-form/iframe-content/hosted-input-aggregator.spec.ts
- src/hosted-form/iframe-content/hosted-input-aggregator.ts
- src/hosted-form/iframe-content/hosted-input-events.ts
- src/order/order-selector.ts
- src/payment/create-payment-strategy-registry.ts
- src/payment/payment-method-selector.ts
- src/payment/strategies/cardinal/cardinal-client.spec.ts
- src/payment/strategies/cardinal/cardinal-client.ts
- src/payment/strategies/cardinal/cardinal-three-d-secure-flow.spec.ts
- src/payment/strategies/cardinal/cardinal-three-d-secure-flow.ts
- src/payment/strategies/cybersource/cybersource-payment-strategy.spec.ts
- src/payment/strategies/cybersource/cybersource-payment-strategy.ts
- src/payment/strategies/paypal/paypal-pro-payment-strategy.spec.ts
- src/payment/strategies/paypal/paypal-pro-payment-strategy.ts
Make Cardinal 3DS flow for Cybersource and PayPal Pro work with hosted payment form.
Currently, we're including CC details in `Cardinal.continue` call - which is a call to prompt the shopper to complete the authentication required by the issuer of their card. But because we're using the Hybrid integration approach, it seems we don't have to do that because we are already passing the order and payment details to Cardinal when we make a lookup request to check the enrolment of the card. However, we do need to pass the BIN number to Songbird (Cardinal's client library) so that it can collect the device data required for the card issuer.
Based on the above, I had to change the code so that credit card details can be sent within the hosted payment iframes, while allowing Songbird work as …
> CHECKOUT-4655: Make Cardinal 3DS work with hosted payment form

- src/shipping/shipping-addresses.mock.ts
- src/shipping/strategies/amazon/amazon-pay-shipping-strategy.spec.ts
- src/shipping/strategies/amazon/amazon-pay-shipping-strategy.ts
Provide support to save custom fields for shipping address when using amazon pay
At the moment the custom form fields are not submitted to the API when using amazon pay account.
> fix(checkout): CHECKOUT-4245 handle custom fields for amazon pay

- scripts/webpack/get-next-version.js
Convert buffer to string before comparing with package version
Otherwise the comparison will always fail
Manual
> CHECKOUT-4669: Convert buffer to string before comparing with package version

- src/payment/create-payment-strategy-registry.spec.ts
- src/payment/create-payment-strategy-registry.ts
- src/payment/payment-action-creator.spec.ts
- src/payment/payment-action-creator.ts
- src/payment/payment-methods.mock.ts
- src/payment/payment-request-options.ts
- src/payment/payment-request-sender.spec.ts
- src/payment/payment-request-sender.ts
- src/payment/payment-strategy-type.ts
- src/payment/strategies/bluesnapv2/bluesnapv2-payment-options.ts
- src/payment/strategies/bluesnapv2/bluesnapv2-payment-strategy.spec.ts
- src/payment/strategies/bluesnapv2/bluesnapv2-payment-strategy.ts
- src/payment/strategies/bluesnapv2/bluesnapv2.ts
- src/payment/strategies/bluesnapv2/index.ts
Create the BlueSnap V2 payment strategy and make it available in checkout.
A new payment strategy is required to support BlueSnap V2.
[4] [bigcommerce/checkout-js](https://github.com/bigcommerce/checkout-js/pull/155) depends on:
[3] THIS PR depends on:
[2] [bigcommerce/bigpay-client-js](https://github.com/bigcommerce/bigpay-client-js/pull/88) depends on:
[1] [bigcommerce/form-poster-js](https://github.com/bigcommerce/form-poster-js/pull/9)
You can watch the video [here](https://drive.google.com/open?id=1unL57CIRZ-KRZK6SvJc-ZNH3Grxgpm0w)
> feat(payments): INT-1997 Integrate BlueSnap V2 strategy

- src/billing/billing-address-action-creator.spec.ts
- src/billing/billing-address-action-creator.ts
- src/billing/errors/index.ts
- src/billing/errors/update-customer-error.ts
- src/checkout/checkout-service.spec.ts
- src/checkout/create-checkout-service.ts
- src/config/config.ts
- src/config/configs.mock.ts
- src/customer/customer-actions.ts
- src/customer/customer-request-sender.ts
- src/customer/customer.ts
- src/customer/guest-credentials.ts
- src/payment/create-payment-strategy-registry.ts
- src/payment/strategies/amazon-pay/amazon-pay-payment-strategy.spec.ts
- src/payment/strategies/googlepay/create-googlepay-payment-processor.ts
- src/payment/strategies/googlepay/googlepay-payment-processor.spec.ts
Add support for marketing emails consent for guest shoppers
GDPR compliance
unit
> CHECKOUT-4640 Add support for marketing emails consent

- src/payment/strategies/adyenv2/adyenv2-initialize-options.ts
- src/payment/strategies/adyenv2/adyenv2-payment-strategy.spec.ts
- src/payment/strategies/adyenv2/adyenv2-payment-strategy.ts
- src/payment/strategies/adyenv2/adyenv2-script-loader.spec.ts
- src/payment/strategies/adyenv2/adyenv2-script-loader.ts
- src/payment/strategies/adyenv2/adyenv2.mock.ts
- src/payment/strategies/adyenv2/adyenv2.ts
[INT-2062](https://jira.bigcommerce.com/browse/INT-2062)
Support iDEAL APM through AdyenV2 gateway
As a merchant I want to be able to support online back transfers using iDEAL as APM if store country is Netherlands and selected currency for the order is Euro.
Unit Testing
[BigPay](https://github.com/bigcommerce/bigpay/pull/2169)
> feat(payment): INT-2062 Support iDEAL payment provider through Adyen V2 gateway

- src/billing/billing-address-reducer.spec.ts
- src/billing/billing-address-reducer.ts
- src/customer/index.ts
Update billing state when updating customer (so far it's only consent).
Because if updating consent failed, it would get stuck in a "loading" state
unit
> CHECKOUT-4640 Fix state when consent is provided

- src/shipping/consignment-action-creator.spec.ts
- src/shipping/consignment-action-creator.ts
Include custom items IDs when in payload when calling `updateShippingAddress`
In case a cart only has custom items, `updateShippingAddress` would fail since there were no items ids in the payload.
Reported in https://github.com/bigcommerce/checkout-sdk-js/issues/701
unit
> CHECKOUT-4416 Include custom items IDs when calling updateShippingAddress

- src/payment/create-payment-strategy-registry.ts
- src/payment/payment-request-options.ts
- src/payment/payment-strategy-registry.ts
- src/payment/payment-strategy-type.ts
- src/payment/strategies/klarnav2/index.ts
- src/payment/strategies/klarnav2/klarna-payments.ts
- src/payment/strategies/klarnav2/klarnav2-payment-initialize-options.ts
- src/payment/strategies/klarnav2/klarnav2-payment-strategy.spec.ts
- src/payment/strategies/klarnav2/klarnav2-payment-strategy.ts
- src/payment/strategies/klarnav2/klarnav2-script-loader.spec.ts
- src/payment/strategies/klarnav2/klarnav2-script-loader.ts
- src/payment/strategies/klarnav2/klarnav2-window.ts
- src/payment/strategies/klarnav2/klarnav2.mock.ts
[INT-1434](https://jira.bigcommerce.com/browse/INT-1434)
KlarnaV2 strategy has been created and keep Klarna V1 working as well
Klarna wants to display each  category as a payment method and load a specific widget for them on the checkout page
[VIDEO DEMO](https://drive.google.com/file/d/1tOaap_EP3JY-WRSOd0ckgGk2c3Ldh3cW/view?usp=sharing)
[INT-1434 CHECKOUT-JS](https://github.com/bigcommerce/checkout-js/pull/165)
[INT-2301 NG-PAYMENTS](https://github.com/bigcommerce-labs/ng-payments/pull/959)
> INT-1434 Support for Klarna V2

- src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-strategy.spec.ts
- src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-strategy.ts
- src/payment/payment-methods.mock.ts
- src/payment/strategies/paypal-commerce/index.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-script-loader.spec.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-sdk.ts
Pass all needed params to paypal SDK on the frontend side
According to docs on PayPal https://developer.paypal.com/docs/checkout/reference/customize-sdk/
> [WIP] feat(payment): PAYPAL-221 Pass all needed params to paypal SDK

- src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-options.ts
- src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-strategy.spec.ts
- src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-strategy.ts
- src/payment/strategies/paypal-commerce/index.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-sdk.ts
Get theme settings and pass it to PayPal buttons initialization script
Edit currency - now form cart (not from config)
For changing styles smart-buttons
> feat(payment): PAYPAL-227 Pass theme settings to PP script

- src/payment/strategies/adyenv2/adyenv2.ts
Change safeguard to validate against SecurityCode rather that card number as this isn't present in case no TSV validation is fired.
If there's no TSV involved safeguard returns false and payment gets processed as it was regular credit card payment.
..
Revert this PR
> fix(payment): INT-2418 Use SecurityNumber as a safeguard

- src/payment/strategies/adyenv2/adyenv2.ts
[INT-2427](https://jira.bigcommerce.com/browse/INT-2427)
Use ExpiryDate while paying with a vaulted Bancontact card rather than CVV
Bancontact cards do not have CVV
Revert this PR
> INT-2427 Use ExpiryDate while paying with a vaulted Bancontact card rather than CVV

- src/payment/create-payment-strategy-registry.ts
- src/payment/payment-strategy-type.ts
- src/payment/strategies/credit-card-redirect/credit-card-redirect-payment-strategy.spec.ts
- src/payment/strategies/credit-card-redirect/credit-card-redirect-payment-strategy.ts
- src/payment/strategies/credit-card-redirect/index.ts
- src/payment/strategies/credit-card/credit-card-payment-strategy.ts
Create a payment strategy to support redirect when using a credit card form, and register checkout.com with this strategy.
So redirecting to pages such as checkout.com's 3DS challenge is possible.
[Demo Video](https://drive.google.com/open?id=1JorF1Z5HE_2ASfpcJj0MG81kkA0UTk4P)
@bigcommerce/checkout @bigcommerce/payments @bigcommerce @bigcommerce/intersys-integrations
> feat(payment): INT-2279 Create a strategy for credit cards with redirect and add support to Checkout.com

- src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-strategy.spec.ts
- src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-strategy.ts
Change header to 'Content-Type': 'application/json' in createOrder request
The body should be passed in as a JsonBody as an argument for the controller action
> feat(payment): PAYPAL-276 Change header in createOrder request

- src/payment/strategies/adyenv2/adyenv2-payment-strategy.ts
- src/payment/strategies/adyenv2/adyenv2-script-loader.spec.ts
- src/payment/strategies/adyenv2/adyenv2-script-loader.ts
- src/payment/strategies/adyenv2/adyenv2.ts
I want to be able to offer my United States shoppers ACH payment method and my Norse shoppers Vipps payment method respectively through Adyen
So that I can give them alternative methods to pay so that they are more likely to purchase.
> feat(payment): INT-1710 Add support for ACH & Vipps on Adyen

- .circleci/config.yml
Use `bigcommerce/internal-node` orb to install npm dependencies in CircleCI.
Previously we define our own installation command within this project because the installation command provided by our internal node orb didn't use `npm ci`. Now it does. It also fixes other issues, such as our dependency cache doesn't get updated when we update our package lock file.
CircleCI
> CHECKOUT-4777: Use bigcommerce/internal-node orb to install npm dependencies in CircleCI

- src/payment/strategies/klarna/klarna-payment-strategy.spec.ts
- src/payment/strategies/klarna/klarna-payment-strategy.ts
- src/payment/strategies/klarnav2/klarnav2-payment-strategy.spec.ts
- src/payment/strategies/klarnav2/klarnav2-payment-strategy.ts
[INT-2001](https://jira.bigcommerce.com/browse/INT-2001)
Enabling the store credit support feature
Klarna payment method now supports store credit so we want to enable that functionality
[DEMO](https://drive.google.com/file/d/1xfE5JMXO-mLMmoUprw2QvkHzUq8WHsUx/view?usp=sharing)
[BIGPAY](https://github.com/bigcommerce/bigpay/pull/2365)
[BIGPAY_CLIENT](https://github.com/bigcommerce-labs/bigpay-client-php/pull/160)
[BCAPP](https://github.com/bigcommerce/bigcommerce/pull/34301)
[BIGPAY](https://github.com/bigcommerce/bigpay/pull/2365)
[BIGPAY_CLIENT](https://github.com/bigcommerce-labs/bigpay-client-php/pull/160)
[BCAPP](https://github.com/bigcommerce/bigcommerce/pull/34301)
> INT-2001 Enable support for Store Credit on both versions of Klarna

- src/payment/payment.ts
- src/payment/strategies/adyenv2/adyenv2-payment-strategy.spec.ts
- src/payment/strategies/adyenv2/adyenv2-payment-strategy.ts
Validate Expiry Date when using a vaulted Bancontact instrument as they don't use CVV
Expiration Date is not validated when checking out with a vaulted instrument in Bancontact.
- Manual
> fix(payment): INT-2431 Adds expiration date for Bancontact payments

- webpack-common.config.js
- webpack-server.config.js
- webpack.config.js
Apply polyfills to external dependencies for targeted environments
Before this change, `babel-env` doesn't apply to `node_modules` dependencies (it only applies to our own code). As a result, the UMD bundle doesn't work on its own in IE11 if some of those dependencies use features that need to be polyfilled.
Right now this problem only affects payment buttons in PDP and cart page because they are provided by the UMD bundle. I believe it has been a problem since October last year when we bumped the version from 1.21.0 to 1.41.0 (however, I'm surprised that we haven't had any support ticket regarding it 🤔). 
On the other hand, UCO uses the CJS bundle and has a different way of applying the `babel-env` so it doesn't get affected by this problem (it applies the entire `core-js` library for …
> CHECKOUT-4789: Apply polyfills to external dependencies for targeted environments

- src/payment/strategies/klarna/klarna-payment-strategy.spec.ts
- src/payment/strategies/klarna/klarna-payment-strategy.ts
- src/payment/strategies/klarna/klarna.mock.ts
- src/payment/strategies/klarnav2/index.ts
- src/payment/strategies/klarnav2/klarna-supported-countries.ts
- src/payment/strategies/klarnav2/klarnav2-payment-strategy.spec.ts
- src/payment/strategies/klarnav2/klarnav2-payment-strategy.ts
- src/payment/strategies/klarnav2/klarnav2.mock.ts
I added billing and shipping when the country is AU/NZ
Because we want to send billing and shipping when the country is AU/NZ
[Video](https://drive.google.com/file/d/1n91rq9tI50MpXqcuu9aA77__MJ9BKB8P/view?usp=sharing)
> feat(payments): INT-2452 Add billing and shipping for klarna

- src/payment/strategies/stripev3/stripev3-payment-strategy.spec.ts
- src/payment/strategies/stripev3/stripev3-payment-strategy.ts
- src/payment/strategies/stripev3/stripev3-script-loader.spec.ts
- src/payment/strategies/stripev3/stripev3-script-loader.ts
- src/payment/strategies/stripev3/stripev3.ts
Add stripe account when Stripe V3 script is loaded
Stripe is requiring to add Stripe Account to identify each merchant
> feat(payment): INT-2410 Add stripe account as configuration

- src/bundles/embedded-checkout.ts
Export `createEmbeddedCheckoutMessenger` function in embedded-checkout bundle.
So it can be used as a part of that sub-bundle.
None
> CHECKOUT-4789: Export `createEmbeddedCheckoutMessenger` function in embedded-checkout bundle

- .circleci/config.yml
Update CircleCI config to use `validate-commits` command provided by our internal orb.
I thought I did it before but I didn't (I only did it for `npm-install`).
CircleCI
@bigcommerce/checkout @icatalina
> CHECKOUT-4842: Update CircleCI config to use `validate-commits` command provided by our internal orb

- src/payment/instrument/supported-payment-instruments.ts
Add checkout.com to the list of supported payment instruments.
So vaulted cards with checkout.com can be selected.
> feat(checkout): INT-2274 Add vaulting support for Checkout.com

- src/hosted-form/hosted-form-factory.ts
- src/hosted-form/hosted-form-options.ts
- src/hosted-form/hosted-form.spec.ts
- src/hosted-form/hosted-form.ts
- src/hosted-form/iframe-content/hosted-autocomplete-fieldset.spec.ts
- src/hosted-form/iframe-content/hosted-autocomplete-fieldset.ts
- src/hosted-form/iframe-content/hosted-card-expiry-input.spec.ts
- src/hosted-form/iframe-content/hosted-card-expiry-input.ts
- src/hosted-form/iframe-content/hosted-card-number-input.spec.ts
- src/hosted-form/iframe-content/hosted-card-number-input.ts
- src/hosted-form/iframe-content/hosted-input-events.ts
- src/hosted-form/iframe-content/hosted-input-factory.spec.ts
- src/hosted-form/iframe-content/hosted-input-factory.ts
- src/hosted-form/iframe-content/hosted-input-initializer.spec.ts
- src/hosted-form/iframe-content/hosted-input-initializer.ts
- src/hosted-form/iframe-content/hosted-input.spec.ts
- src/hosted-form/iframe-content/hosted-input.ts
Trigger `onEnter` event callback when "enter" key is pressed in one of the hosted payment fields. With this callback, the client application can submit an order when it is triggered.
With this change, shoppers can use their keyboard to place an order after filling in their credit card details.
CircleCI
> CHECKOUT-4842: Trigger event when "enter" key is pressed in one of hosted payment fields

- src/checkout/checkout-service.spec.ts
- src/checkout/checkout-service.ts
- src/checkout/checkout-store-error-selector.spec.ts
- src/checkout/checkout-store-error-selector.ts
- src/checkout/checkout-store-selector.spec.ts
- src/checkout/checkout-store-selector.ts
- src/checkout/checkout-store-state.ts
- src/checkout/checkout-store-status-selector.spec.ts
- src/checkout/checkout-store-status-selector.ts
- src/checkout/checkouts.mock.ts
- src/checkout/create-checkout-service.ts
- src/checkout/create-checkout-store-reducer.ts
- src/checkout/create-internal-checkout-selectors.ts
- src/checkout/internal-checkout-selectors.ts
- src/signin-email/index.ts
- src/signin-email/signin-email-action-creator.spec.ts
- src/signin-email/signin-email-action-creator.ts
- src/signin-email/signin-email-actions.ts
- src/signin-email/signin-email-reducer.spec.ts
- src/signin-email/signin-email-reducer.ts
- src/signin-email/signin-email-request-sender.spec.ts
- src/signin-email/signin-email-request-sender.ts
- src/signin-email/signin-email-selector.spec.ts
- src/signin-email/signin-email-selector.ts
- src/signin-email/signin-email-state.ts
- src/signin-email/signin-email.ts
- src/subscription/subscriptions-request-sender.spec.ts
Add sign-in via email support (passwordless login).
To provide a facade to `login.php` API and keep state of sent emails.
unit
> CHECKOUT-4799 Add Sign-in via Email support (passwordless login)

- README.md
Add instructions on how to load the library through a CDN URL.
We want to document how developers can use the package by loading it through CDN URL.
None
> CHECKOUT-4827: Add instructions on how to load library through CDN URL

- src/cart/cart-selector.ts
- src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-strategy.ts
- src/common/overlay/index.ts
- src/common/overlay/overlay-style.ts
- src/common/overlay/overlay.spec.ts
- src/common/overlay/overlay.ts
- src/payment/create-payment-strategy-registry.ts
- src/payment/payment-request-options.ts
- src/payment/strategies/paypal-commerce/index.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-payment-initialize-options.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-payment-processor.spec.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-payment-processor.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.spec.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.ts
For markup flow (flow when we start PayPal commerce flow on the checkout page, not on cart page), we need to implement logic that will send a request to `api/storefront/payment/paypalcommerce/`
after customer has chosen PayPal Commerce method and clicked Place Order.
After FE received a link from 
`api/storefront/payment/paypalcommerce/`, we need to forward customer to url based on the link
After approving in the paypal payment should continue 
Paying in checkout page
> feat(payment): PAYPAL-265 Markup flow

- src/checkout/checkout-service.spec.ts
- src/checkout/checkout-service.ts
- src/spam-protection/google-recaptcha.spec.ts
- src/spam-protection/google-recaptcha.ts
- src/spam-protection/spam-protection-action-creator.spec.ts
- src/spam-protection/spam-protection-action-creator.ts
1. Rethrow `SpamProtectionChallengeNotCompletedError` instead of converting it into the more general `SpamProtectionFailedError`.
1. Make sure `isExecutingSpamCheck` returns true as soon as `executeSpamCheck` is called, by taking consideration of the time that's required to load and render the reCaptcha widget.
1. Otherwise, the client application can't tell the difference between an actual application error versus an error thrown due to the end user choosing not the complete the reCaptcha challenge.
1. Otherwise, `isExecutingSpamCheck` won't immediately return `true` even though the asynchronous action is already being executed.
CircleCI
> CHECKOUT-4852: Rethrow spam protection cancellation error and make sure spam protection execution status is accurate

- src/checkout/checkout-store-selector.spec.ts
- src/checkout/checkout-store-selector.ts
- src/config/config-selector.spec.ts
- src/config/config-selector.ts
- src/config/config.ts
- src/config/index.ts
Expose error FlashMessage via `data.getFlashMessages()`
So clients using Sign-in Email Link feature can access the error when the link is invalid.
unit
> CHECKOUT-4879 Expose flash messages

- src/payment/strategies/klarnav2/klarnav2-payment-strategy.ts
[INT-2611](https://jira.bigcommerce.com/browse/INT-2611)
Hitting an endpoint to update the klarna session
Because we want to avoid mismatch between bigcommerce order and klarna order
[INT-2611 BCAPP](https://github.com/bigcommerce/bigcommerce/pull/34949)
> INT-2611 Update the klarna session before the widget is loaded (Klarna V2)

- src/payment/instrument/supported-payment-instruments.ts
[INT-2497](https://jira.bigcommerce.com/browse/INT-2497)
MyVirtualMerchant (Elavon) added to supported instruments whitelist
Because we want to support vaulting
[DEMO](https://drive.google.com/file/d/1-f5wN2CGlFIWV-EXZUJtt6zAiey4OWAM/view?usp=sharing)
[BIGPAY](https://github.com/bigcommerce/bigpay/pull/2462)
[BCAPP](https://github.com/bigcommerce/bigcommerce/pull/34813)
> INT-2497 Add elavon to supported instruments whitelist

- src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.ts
Checkout order after approval issue
The issue is when checkout is started with SPB, interrupted and general checkout flow started
> fix(payment): PAYPAL-406 Checkout order after approval issue

- src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-strategy.spec.ts
- src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-strategy.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-sdk.ts
Choses paypalcommercecredit method on the checkout page
Merchant should see paypalcommercecredit method on the checkout page after chosen this method in the spb
> feat(payment): PAYPAL-365 choses paypalcredit method on the checkout

- src/payment/strategies/adyenv2/adyenv2-initialize-options.ts
- src/payment/strategies/adyenv2/adyenv2-payment-strategy.spec.ts
- src/payment/strategies/adyenv2/adyenv2-payment-strategy.ts
- src/payment/strategies/adyenv2/adyenv2.mock.ts
Add support to Vault Bank accounts of SEPA
To show saved bank instruments for SEPA, pay and delete instruments.
[INT-2437](https://github.com/bigcommerce/checkout-sdk-js/pull/818)
> INT-2612 Vault SEPA accounts

- src/customer/customer-reducer.spec.ts
- src/customer/customer-reducer.ts
- src/customer/customer.ts
- src/customer/customers.mock.ts
Update customer object when continuing as guest
Because when continuing as guest, we might set `shouldEncourageSignIn` flag
unit
> CHECKOUT-4742 Update customer object when continuing as guest

- src/checkout/checkout-service.spec.ts
- src/checkout/checkout-service.ts
- src/signin-email/index.ts
- src/signin-email/signin-email-action-creator.spec.ts
- src/signin-email/signin-email-action-creator.ts
- src/signin-email/signin-email-request-sender.spec.ts
- src/signin-email/signin-email-request-sender.ts
- src/signin-email/signin-email.ts
Add redirect_to to sign in email request payload.
Because by default it redirects to account page. We want this to redirect to checkout.
Unit
> CHECKOUT-4897 Add redirect_to to SignInEmail

- src/payment/strategies/amazon-pay/amazon-pay-payment-strategy.spec.ts
- src/payment/strategies/amazon-pay/amazon-pay-payment-strategy.ts
Don't assume `useStoreCredit:false` if not provided.
Because there are other ways to set store credit. If this is not passed, shouldn't be assumed false as it could overwrite the value set using the store credit endpoint.
unit
> CHECKOUT-4904 Pass useStoreCredit: undefined to amazonpay if not provided

- src/order/order-request-body.ts
- src/payment/create-payment-strategy-registry.ts
- src/payment/payment-strategy-type.ts
- src/payment/strategies/bolt/bolt-payment-strategy.spec.ts
- src/payment/strategies/bolt/bolt-payment-strategy.ts
- src/payment/strategies/bolt/index.ts
Create a payment strategy for bolt that allows a `nonce` to be submitted as payment.
Bolt is a provider consumes checkout-sdk in its marketplace app, currently it submits orders and payments via the offline payment strategy and using other provider as its gateway, this strategy will allow the bolt app to submit the orders and payments to the corresponding bolt gateway .
Unit testing.
@bigcommerce/checkout  @bigcommerce/payments  @bigcommerce/apex-integrations
> INT-2577 Create a strategy for Bolt

- src/payment/strategies/stripev3/stripev3-payment-strategy.ts
- src/payment/strategies/stripev3/stripev3.mock.ts
remove receipt_email in stripe-strategy
because I'm validating the receipt_email in big pay and the functionality is controlled by a toggle in the settings page
https://github.com/bigcommerce/bigcommerce/pull/35006
https://github.com/bigcommerce/bigpay/pull/2522
https://github.com/bigcommerce-labs/ng-payments/pull/1021
Toggle settings page 
When Toggle Add receipt_email in settings page is on
When Toggle Add receipt_email in settings page is off
> feat(payment): INT-2613 remove receipt_email in stripe-strategy

- src/payment/strategies/adyenv2/adyenv2-script-loader.spec.ts
- src/payment/strategies/adyenv2/adyenv2-script-loader.ts
- src/payment/strategies/adyenv2/adyenv2.mock.ts
Upgrade Adyen Components Library to v3.8.0
To expose cumulative improvements and fixes provided by [this](https://docs.adyen.com/checkout/release-notes?tab=%23us_b5b6b1ec_3#web-components-3-8-0) new release.
- Unit
> refactor(payment): INT-2684 Upgrade Adyen Component Library

- src/address/address.ts
- src/address/map-from-internal-address.spec.ts
- src/billing/billing-addresses.mock.ts
- src/checkout/checkout-store-selector.ts
- src/payment/strategies/amazon-pay/amazon-pay-payment-strategy.spec.ts
- src/shipping/shipping-addresses.mock.ts
- src/shipping/strategies/amazon/amazon-pay-shipping-strategy.spec.ts
Expose `shouldSaveAddress` attribute
So clients can opt-out from the automatic behaviour that saves addresses.
n/a
> CHECKOUT-4760 Update address type to include shouldSaveAddress attribute

- src/payment/strategies/adyenv2/adyenv2-script-loader.spec.ts
- src/payment/strategies/adyenv2/adyenv2-script-loader.ts
- src/payment/strategies/adyenv2/adyenv2.mock.ts
Remove attributes as they seem to be blocking Adyen components suite from been loaded.
It is blocking merchants from loading Adyen Components
...
> fix(payment): INT-2691 Remove integrity & crossorigin attributes for AdyenV2

- src/checkout/create-checkout-service.ts
- src/config/config-selector.ts
- src/config/config-state.ts
- src/config/config-window.ts
- src/config/configs.mock.ts
- src/config/index.ts
- src/order/order-action-creator.spec.ts
- src/order/order-action-creator.ts
- src/order/order-request-sender.spec.ts
- src/order/order-request-sender.ts
Send an additional header to provide information about the checkout variant that is used to pay for an order.
It's an optional parameter that can help us identify whether the default checkout or a custom checkout is used to complete a checkout process.
Unit
> CHECKOUT-4754: Send an additional header to provide information about the checkout variant that is used to pay for an order

- src/payment/create-payment-strategy-registry.ts
- src/payment/payment-strategy-type.ts
- src/payment/strategies/laybuy/index.ts
- src/payment/strategies/laybuy/laybuy-payment-strategy.spec.ts
- src/payment/strategies/laybuy/laybuy-payment-strategy.ts
Add Laybuy strategy
A new payment strategy is required to support Laybuy.
[Video](https://drive.google.com/file/d/1Mnkg1hPXa9zG1CweNys8czFBb-B-KW1k/view?usp=sharing)
> feat(payment): INT-2541 Add Laybuy strategy

- src/payment/strategies/klarnav2/klarnav2-payment-strategy.spec.ts
- src/payment/strategies/klarnav2/klarnav2-payment-strategy.ts
[INT-2001](https://jira.bigcommerce.com/browse/INT-2001)
We are reloading the widget each time the apply store credit checkbox state changes
We need to update the klarna session with the final amount to pay
[DEMO](https://drive.google.com/file/d/1RZMjQds1ZZJoGIDZpZvKBtqP24ZK43Zw/view?usp=sharing)
> INT-2001 Reload widget when apply store credit checkbox state changes

- src/payment/strategies/googlepay/googlepay-braintree-initializer.spec.ts
- src/payment/strategies/googlepay/googlepay-stripe-initializer.spec.ts
- src/payment/strategies/googlepay/googlepay-stripe-initializer.ts
- src/payment/strategies/googlepay/googlepay.mock.ts
As a merchant I do want to have a frictionless migration from Stripe to StripeV3.
I want to use platform level tokens associated with my merchant account.
- Unit
- Manual
> feat(payment): INT-2629 Relate stripeConnectedAccount while initilaling GooglePay

- package-lock.json
- package.json
Bump `script-loader-js` version.
https://github.com/bigcommerce/script-loader-js/blob/master/CHANGELOG.md
CircleCI
Ping @bigcommerce/checkout
> chore(payment): CHECKOUT-4909 Bump script-loader-js

- src/payment/strategies/adyenv2/adyenv2-script-loader.spec.ts
- src/payment/strategies/adyenv2/adyenv2-script-loader.ts
Upgrade Adyen Components Library to v3.8.1
To expose cumulative improvements and fixes provided by [this](https://docs.adyen.com/checkout/release-notes?tab=%23us_b5b6b1ec_3#web-components-3-8-1) new release.
- Unit
> feat(payment): INT-2722 Upgrade Adyen component library

- src/analytics/analytics-step-tracker.spec.ts
- src/analytics/analytics-step-tracker.ts
Convert coupon codes to upper case before sending to analytics.
Coupon codes are case insensitive, so `foo` and `FOO` are handled the same by our system, but are being counted as unique entries by downstream analytics consumers, confusing merchants.
Unit test updated.
@bigcommerce/checkout @bigcommerce/orders
> feat(common): ORDERS-3323 Ensure coupon codes are upper case.

- src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-strategy.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-script-loader.spec.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-script-loader.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-sdk.ts
Pass merchant ID on PayPal button for PPCP
This is needed so that the PayPal Shopping feature knows which merchants to target for PayPal Store Cash
> feat(payment): PAYPAL-483 Pass merchant ID on PayPal button for PPCP

- src/payment/strategies/adyenv2/adyenv2-payment-strategy.spec.ts
- src/payment/strategies/adyenv2/adyenv2-payment-strategy.ts
Edited the order on the switch of the initialization for the APM's for Adyen v2, because GiroPay needed to be initializated as AliPay does to not show the Button on the checkout page and just select GyroPay and click Place order
to initialize Giropay correctly and can pay with it
> fix(payment): INT-2759 Do not mount GiroPay component while initializing payment strategy

- src/payment/strategies/braintree/braintree-credit-card-payment-strategy.spec.ts
- src/payment/strategies/braintree/braintree-credit-card-payment-strategy.ts
- src/payment/strategies/braintree/braintree-script-loader.spec.ts
- src/payment/strategies/braintree/braintree-script-loader.ts
Updated version of braintree's script to 3.59
Moved loading braintree's script to the `initialize`. In other case data of device data may not have time to sending
Device data not being submitted to Braintree / Kount
Manual tested placing order with braintree credit card / paypal / paypal credit
> fix(payment): PAYPAL-453 Submit device data to Braintree/Kount

- src/checkout-buttons/checkout-button-options.ts
- src/checkout-buttons/strategies/amazon-pay-v2/amazon-pay-v2-button-options.ts
- src/checkout-buttons/strategies/checkout-button-method-type.ts
- src/customer/customer-request-options.ts
- src/customer/strategies/amazon-pay-v2/amazon-pay-v2-customer-initialize-options.ts
- src/payment/payment-request-options.ts
- src/payment/payment-strategy-type.ts
- src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-initialize-options.ts
- src/payment/strategies/amazon-pay-v2/amazon-pay-v2.ts
- src/shipping/shipping-request-options.ts
- src/shipping/strategies/amazon-pay-v2/amazon-pay-v2-shipping-initialize-options.ts
- Improved documentation.
- Added the `@alpha` modifier to all the new introduced params.
To indicate that Amazon Pay V2 is in an early stage of development.
CircleCI
> docs(payment): INT-2119 Add the @alpha modifier to AmazonPayV2

- src/checkout/checkout-service.ts
Fix links in documentation
Because they are broken
https://github.com/capsula4/checkout-sdk-js/blob/fix-doc-links-dist/docs/classes/checkoutservice.md#continueasguest
>  CHECKOUT-4912 Fix links to interfaces

- src/payment/create-payment-strategy-registry.ts
- src/payment/payment-strategy-type.ts
- src/payment/strategies/external/external-payment-strategy.spec.ts
- src/payment/strategies/external/external-payment-strategy.ts
- src/payment/strategies/external/index.ts
- src/payment/strategies/laybuy/index.ts
Adding sezzle payment in the registry as external payment 
It does a laybuy's refactoring because sezzle and laybuy are similar and both are mapped as external payments, it's required to support sezzle, using the same strategy
@bigcommerce/apex-integrations
> feat(payments): INT-2748 Adding sezzle strategy

- src/payment/payment-request-transformer.spec.ts
- src/payment/payment-request-transformer.ts
Pass additional action data to hosted forms.
We're not passing it to the form at the moment. If it's not passed, it can't be sent to complete the human verification process.
Unit
> CHECKOUT-4995: Pass additional action data to hosted forms

- src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.ts
Mark up flow additional params
As we do not use PayPal SDK on the front end on markup flow, we do not pass commit=true in SDK params, but PayPal backend still needs to know which mode are going with, in order to show buyer proper info on PayPal side.
> feat(payments): PAYPAL-508 Mark up flow additional params

- package-lock.json
- package.json
This upgrades typescript. Will help using rollup for ESM
Will unblock ESM support when using rollup
CircleCI should be a good proof of this.
> feat(common): Update Typescript

- src/payment/strategies/paypal-commerce/paypal-commerce-script-loader.spec.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-script-loader.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-sdk.ts
MerchantId does not required for progressive onboarding
Added filter for options for paypal script, because script doesn't work if option is null or undefined 
It will be new implementation for progressive onboarding
...
> feat(payment): PAYPAL-539 MerchantId does not required 

- src/payment/create-payment-strategy-registry.ts
- src/payment/strategies/converge/converge-payment-strategy.spec.ts
- src/payment/strategies/converge/converge-payment-strategy.ts
Make `ConvergePaymentStrategy` inherit `CreditCardPaymentStrategy` strategy.
So that it can utilise hosted payment forms.
Unit / Manual
> CHECKOUT-5025: Fix Elavon Converge strategy so that it can utilise hosted payment form

- src/common/dom/detachment-observer.spec.ts
- src/common/dom/detachment-observer.ts
- src/common/dom/errors/index.ts
- src/common/dom/errors/unexpected-detachment-error.ts
- src/common/dom/index.ts
- src/hosted-form/hosted-field.spec.ts
- src/hosted-form/hosted-field.ts
- src/hosted-form/hosted-form-factory.ts
Return an error if a hosted field iframe is removed during an asynchronous call.
Otherwise, the promise of the asynchronous call won't get resolved or rejected. As a result, callers that subscribe to the promise would be waiting indefinitely for a result.
Unit
> CHECKOUT-5029: Return error if hosted field iframe is removed during asynchronous call

- src/shipping/strategies/amazon-pay-v2/amazon-pay-v2-shipping-strategy.spec.ts
- src/shipping/strategies/amazon-pay-v2/amazon-pay-v2-shipping-strategy.ts
Provide support to save custom fields for the shipping address when using Amazon Pay V2.
Because it's not possible to place the order using AmazonPayV2 with custom address fields defined by merchants. Almost the same as #793.
CircleCI
[checkout-js/pull/333](https://github.com/bigcommerce/checkout-js/pull/333) depends on this PR.
> fix(shipping): INT-2832 Handle custom fields for AmazonPayV2

- src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-strategy.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-script-loader.spec.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-script-loader.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-sdk.ts
MerchantId does not required for progressive onboarding
Added filter for options for paypal script, because script doesn't work if option is null or undefined
It will be new implementation for progressive onboarding
> feat(payment): PAYPAL-539 MerchantId does not required

- src/payment/create-payment-strategy-registry.ts
- src/payment/instrument/supported-payment-instruments.ts
- src/payment/payment-methods.mock.ts
- src/payment/strategies/stripev3/stripev3-initialize-options.ts
- src/payment/strategies/stripev3/stripev3-payment-strategy.spec.ts
- src/payment/strategies/stripev3/stripev3-payment-strategy.ts
- src/payment/strategies/stripev3/stripev3-script-loader.spec.ts
- src/payment/strategies/stripev3/stripev3-script-loader.ts
- src/payment/strategies/stripev3/stripev3.mock.ts
- src/payment/strategies/stripev3/stripev3.ts
Accept iDEAL & SEPA payments on StripeV3
I want merchants to offer iDEAL & SEPA APM support over my StripeV3 gateway implementation
- Unit
- Manual
[#911](https://github.com/bigcommerce/checkout-sdk-js/pull/911)
> feat(payment): INT-2532, INT-2533 Accept payments through StripeV3 using iDEAL & SEPA

- src/payment/strategies/braintree/braintree-hosted-form.spec.ts
- src/payment/strategies/braintree/braintree-hosted-form.ts
- src/payment/strategies/braintree/braintree-payment-options.ts
- src/payment/strategies/braintree/braintree-regular-field.ts
- src/payment/strategies/braintree/braintree-script-loader.spec.ts
- src/payment/strategies/braintree/braintree-script-loader.ts
- src/payment/strategies/braintree/braintree-sdk-creator.spec.ts
- src/payment/strategies/braintree/braintree-sdk-creator.ts
- src/payment/strategies/braintree/braintree.mock.ts
- src/payment/strategies/braintree/braintree.ts
- src/payment/strategies/braintree/is-braintree-form-fields-map.ts
Introduce an object responsible for initialising and using Braintree hosted fields.
We want an abstraction so that it is easier for our code to interact with the Braintree hosted fields module. It acts as a facade that bridges the difference between the interface we want to offer to our clients and the interface Braintree offers to us.
CircleCI
> CHECKOUT-4947: Introduce object responsible for initialising and using Braintree hosted fields

- src/payment/strategies/stripev3/stripev3-payment-strategy.spec.ts
- src/payment/strategies/stripev3/stripev3-payment-strategy.ts
- src/payment/strategies/stripev3/stripev3-script-loader.ts
- src/payment/strategies/stripev3/stripev3.mock.ts
- src/payment/strategies/stripev3/stripev3.ts
Accept Alipay payments on StripeV3
I want merchants to offer Alipay APM support to Chinese shoppers over my StripeV3 gateway implementation
- Unit
- Manual
[#322](https://github.com/bigcommerce/checkout-js/pull/322)
> feat(payment): INT-2653 Accept payments through StripeV3 using Alipay

- package-lock.json
- package.json
- src/payment/payment-action-creator.spec.ts
- src/payment/payment-action-creator.ts
- src/payment/payment.ts
- src/payment/strategies/adyenv2/adyenv2-payment-strategy.spec.ts
- src/payment/strategies/adyenv2/adyenv2-payment-strategy.ts
- src/payment/strategies/bluesnapv2/bluesnapv2-payment-strategy.spec.ts
- src/payment/strategies/bluesnapv2/bluesnapv2-payment-strategy.ts
- src/payment/strategies/braintree/braintree-paypal-payment-strategy.spec.ts
- src/payment/strategies/braintree/braintree-paypal-payment-strategy.ts
- src/payment/strategies/offsite/offsite-payment-strategy.spec.ts
- src/payment/strategies/offsite/offsite-payment-strategy.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.spec.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.ts
- src/payment/strategies/stripev3/stripev3-payment-strategy.spec.ts
- src/payment/strategies/stripev3/stripev3-payment-strategy.ts
…g vaulting or vaulted payments
Refactoring the silly signature of `initializeOffsitePayment` to make it more extensible. (arguably should have been in a different PR)
Adding support for a new `setAsDefaultInstrument` field for vaulted and vault-able payloads
To allow for vaulted instruments to be set set as the default during payment
Unit and manual
> feat(payment): PAYMENTS-5513 add setAsDefaultInstrument feature during vaulting or vaulted payments

- src/payment/payment-method-config.ts
- src/payment/strategies/credit-card-redirect/credit-card-redirect-payment-strategy.spec.ts
- src/payment/strategies/credit-card/credit-card-payment-strategy.spec.ts
- src/payment/strategies/credit-card/credit-card-payment-strategy.ts
- src/payment/strategies/wepay/wepay-payment-strategy.spec.ts
Inspect `PaymentMethod` object to determine whether a payment method supports hosted payment form. 
At the moment, we inspect the checkout settings object to check if the feature is enabled or not. However, it is not sufficient because the availability of the feature also depends on individual payment methods. To address this problem, we'll introduce a flag at the payment method level so that it can differ between different methods.
Unit
> CHECKOUT-4947: Inspect payment method object to determine whether hosted payment form is enabled for payment method

- src/hosted-form/iframe-content/hosted-input-aggregator.spec.ts
- src/hosted-form/iframe-content/hosted-input-aggregator.ts
Catch  "permission denied" error when attempting to gather adjacent hosted inputs to support IE11.
It's possible that the checkout page has iframes other than the hosted fields (i.e.: tracking iframes, live chat widgets). When attempting to gather hosted fields, we have to loop through every iframe that exists on the page and filter out the ones that are not hosted fields. We know which one to filter out because iframes that are not hosted fields come from a different origin and will throw an exception when trying to access them. Unfortunately, IE11 doesn't throw the standard `DOMException` error - it throws an `Error` instance with "Permission denied" message instead. As a result, our filtering logic fails.
Unit + Manual
**Before**
**After**
> CHECKOUT-5089: Catch "permission denied" error when attempting to gather adjacent hosted inputs to support IE11

- package-lock.json
- package.json
- src/payment/payment.ts
- src/payment/strategies/braintree/braintree-credit-card-payment-strategy.spec.ts
- src/payment/strategies/braintree/braintree-credit-card-payment-strategy.ts
- src/payment/strategies/braintree/braintree-payment-processor.spec.ts
- src/payment/strategies/braintree/braintree-payment-processor.ts
- src/payment/strategies/braintree/create-braintree-payment-processor.ts
Modify `BraintreeCreditCardStrategy` to use `BraintreeHostedForm` (introduced in #939) when the feature is enabled and the required options are passed.
So we can accept credit card details using Braintree's hosted payment form.
Unit
> CHECKOUT-4947: Modify Braintree credit card strategy to use hosted form service when feature is enabled

- src/payment/instrument/instrument-selector.ts
When calling getInstruments on a checkout app built around the Checkout SDK, the results are duplicated in the array returned
Because previously we filter the instrument to determine if there are card instruments or account instruments, but we determine that getInstruments need to return all the instruments and if we need only account instruments or card instruments then use the methods getCardInstruments or in case of account create it.
> feat(payment): INT-2907 Avoid returns duplicate vaulted instruments

- package-lock.json
- package.json
bump bigpay-client to 5.12
released https://github.com/bigcommerce/bigpay-client-js/pull/107
unit / manual
> feat(payments): bump bigpay-client to 5.12

- src/config/config.ts
- src/config/configs.mock.ts
Remove the unused key `isHostedPaymentFormEnabled` from `Config` object.
It's no longer needed after this https://github.com/bigcommerce/checkout-sdk-js/pull/938
Unit
> CHECKOUT-5099: Remove unused key from settings object

- src/payment/strategies/adyenv2/adyenv2-script-loader.spec.ts
- src/payment/strategies/adyenv2/adyenv2-script-loader.ts
Upgrade Adyen Components Library to v3.10.1
To expose cumulative improvements and fixes provided by [this](https://docs.adyen.com/checkout/release-notes#web-components-3-10-1) new release.
- Manual
- Unit
> refactor(payment): INT-2922 Upgrade Adyen Component Library

- src/payment/create-payment-strategy-registry.ts
- src/payment/strategies/zip/zip-payment-strategy.spec.ts
- src/payment/strategies/zip/zip-payment-strategy.ts
Restore the `remoteCheckoutActionCreator` calls for Zip
This call stores the `useStoreCredit` on the backend, so when loading the payment method, the store credit can still be applied. 
Apply Store Credit unsets this variable in the backend, but is later required in the `loadPaymentMethod`call.
[Demo Video](https://drive.google.com/file/d/1ZH8JuYecxlImYbYcI8abkxvpvHHS8khD/view?usp=sharing)
> fix(payment): INT-3010 Fix Zip store credit implementation

- src/payment/strategies/stripev3/stripev3-payment-strategy.spec.ts
- src/payment/strategies/stripev3/stripev3-payment-strategy.ts
- src/payment/strategies/stripev3/stripev3.mock.ts
- src/shipping/ShippableItem.ts
- src/shipping/findConsignment.ts
- src/shipping/getLineItemsCount.spec.ts
- src/shipping/getLineItemsCount.ts
- src/shipping/getShippableItemsCount.spec.ts
- src/shipping/getShippableItemsCount.ts
- src/shipping/getShippableLineItems.ts
- src/shipping/index.ts
remove phone number parameter in request if phone number field is empty in Stripe v3.
If phone it is not provided on checkout it throws an error, with this change it is not going to failed even if phone it is not provided.
[Testing proof Video](https://drive.google.com/file/d/1a4odPJv0wl-bxmPcrFkJWOKUtUSej0wI/view?usp=sharing)
> feat(payment): INT-3016 remove phone number parameter in request if field is empty in Stripev3

- src/payment/create-payment-strategy-registry.ts
- src/payment/strategies/stripev3/stripev3-payment-strategy.spec.ts
- src/payment/strategies/stripev3/stripev3-payment-strategy.ts
I want my merchants to be able to apply store credit for shoppers on StripeV3
- Manual
- Unit
[#36590](https://github.com/bigcommerce/bigcommerce/pull/36590)
> fix(payment): INT-3043 Apply store credit on StripeV3

- src/payment/strategies/affirm/affirm-script-loader.spec.ts
- src/payment/strategies/affirm/affirm-script-loader.ts
- src/payment/strategies/affirm/affirmJs.ts
Changed the Affirm.js initialization approach to avoid calling `Function()`. Please refer to Affirm documentation: https://docs.affirm.com/Integrate_Affirm/Direct_API#1._Add_Affirm.js
Because #928 
CircleCI
> refactor(payment): INT-2995 Avoid setting up Affirm.js from string code

- src/checkout-buttons/strategies/googlepay/googlepay-adyenv2-button-strategy.spec.ts
- src/checkout-buttons/strategies/googlepay/googlepay-authorizenet-button-strategy.spec.ts
- src/checkout-buttons/strategies/googlepay/googlepay-braintree-button-strategy.spec.ts
- src/checkout-buttons/strategies/googlepay/googlepay-button-strategy.ts
- src/checkout-buttons/strategies/googlepay/googlepay-checkoutcom-button-strategy.spec.ts
- src/checkout-buttons/strategies/googlepay/googlepay-stripe-button-strategy.spec.ts
- src/customer/strategies/googlepay/googlepay-authorizenet-customer-strategy.spec.ts
- src/customer/strategies/googlepay/googlepay-braintree-customer-strategy.spec.ts
- src/customer/strategies/googlepay/googlepay-checkoutcom-customer-strategy.spec.ts
- src/customer/strategies/googlepay/googlepay-customer-strategy.ts
- src/customer/strategies/googlepay/googlepay-stripe-customer-strategy.spec.ts
Validate if cart has physical items before attempting to update shipping address and avoid it of not necessary.
Updating the shipping address is not necessary when there are only digital products, attempting to create a consignment with  only digital products causes the request to fail and thus the checkout cant be completed.
[Demo video Cart Step](https://drive.google.com/file/d/1YD42g3ivzJ3vFqUQM6a9U1qHq7H10wjv/view?usp=sharing)
[Demo video customer step](https://drive.google.com/file/d/1_Md51j4cJxzCr4XEC4oTX6LmZ8JE388_/view?usp=sharing)
> fix(checkout): INT-3041 Fix GooglePay updating shipping address when purchasing digital items only

- src/payment/create-payment-strategy-registry.ts
- src/payment/strategies/bolt/bolt-app-payment-strategy.spec.ts
- src/payment/strategies/bolt/bolt-app-payment-strategy.ts
Use `storeCreditActionCreator` on bolt
To allow bolt to accept store credit
https://github.com/bigcommerce/bigcommerce/pull/36460
[Demo Video](https://drive.google.com/file/d/1rv3P9eXVmzmD_roLiFoiIQaitZsEcAta/view?usp=sharing)
> feat(checkout): INT-2992 Make store credit usable with bolt

- src/hosted-form/iframe-content/hosted-card-number-input.spec.ts
- src/hosted-form/iframe-content/hosted-card-number-input.ts
- src/hosted-form/iframe-content/hosted-input-factory.spec.ts
- src/hosted-form/iframe-content/hosted-input-factory.ts
Set the correct `type` for card number verification fields.
Before this change, it is set to `CardNumber`. It should be set to `CardNumberVerification` instead. If it's not set correctly, we won't be sending the expected `credit_card_number_confirmation` value to the server when paying with a stored credit card for an order that ships to an untrusted shipping address.
Unit
> CHECKOUT-5115 CHECKOUT-5116 CHECKOUT-5117: Set correct type for card number verification field

- src/checkout-buttons/create-checkout-button-registry.spec.ts
- src/checkout-buttons/create-checkout-button-registry.ts
- src/checkout-buttons/strategies/amazon-pay-v2/amazon-pay-v2-button-options.ts
- src/checkout-buttons/strategies/amazon-pay-v2/amazon-pay-v2-button-strategy.spec.ts
- src/checkout-buttons/strategies/amazon-pay-v2/amazon-pay-v2-button-strategy.ts
- src/checkout-buttons/strategies/amazon-pay-v2/amazon-pay-v2-button.mock.ts
- src/config/config-selector.ts
- src/customer/create-customer-strategy-registry.ts
- src/customer/strategies/amazon-pay-v2/amazon-pay-v2-customer-strategy.spec.ts
- src/customer/strategies/amazon-pay-v2/amazon-pay-v2-customer-strategy.ts
- src/payment/create-payment-strategy-registry.ts
- src/payment/payment-methods.mock.ts
- src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-processor.spec.ts
- src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-processor.ts
- src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-strategy.spec.ts
- src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-strategy.ts
- src/payment/strategies/amazon-pay-v2/amazon-pay-v2-script-loader.spec.ts
- src/payment/strategies/amazon-pay-v2/amazon-pay-v2.mock.ts
- src/payment/strategies/amazon-pay-v2/create-amazon-pay-v2-payment-processor.ts
- src/shipping/create-shipping-strategy-registry.ts
- src/shipping/strategies/amazon-pay-v2/amazon-pay-v2-shipping-strategy.spec.ts
- src/shipping/strategies/amazon-pay-v2/amazon-pay-v2-shipping-strategy.ts
- Prevents `AmazonPayV2PaymentProcessor` from calling payments/amazonpay, strategies are now in charge of that.
- ~~`AmazonPayV2ButtonStrategy` is initialized entirely with data from bcapp when the template is rendered.~~
- `AmazonPayV2ButtonStrategy` is initialized from BC App template data if available, otherwise I make the required API calls.
- I did some clean up on `AmazonPayV2` strategies and tests.
Because the Amazon team noticed a slight delay loading their buttons in our end.
CIrcleCI and...
**BEFORE** / **AFTER**
~~This PR depends on [bigcommerce/pull/36413](https://github.com/bigcommerce/bigcommerce/pull/36413)~~
This PR partially depends on [bigcommerce/pull/36413](https://github.com/bigcommerce/bigcommerce/pull/36413)
> perf(payment): INT-2926 Avoid unnecessary calls to payments/amazonpay

- README.md
- Updating the "Getting started" section to link to the correct tutorials.
- Making note to say the example checkout app is not Production ready.
Improve Checkout JS SDK documentation to make it easier for developers to get started using the SDK.
...
@bigcommerce/checkout @bigcommerce/payments @capsula4
> docs(common): CHECKOUT-5136 Updating the links in Getting started section

- src/payment/strategies/adyenv2/adyenv2-payment-strategy.spec.ts
- src/payment/strategies/adyenv2/adyenv2-payment-strategy.ts
I want my merchants to offer their shoppers less friction while checking out with ACH APM.
- Unit
- Manual
> feat(payments): [AdyenV2] INT-3084 Autopopulate card holder name

- src/payment/strategies/braintree/braintree-credit-card-payment-strategy.spec.ts
- src/payment/strategies/braintree/braintree-credit-card-payment-strategy.ts
Adding `setAsDefaultInstrument` to the nonce mapping function's white list for Braintree
Currently it is being stripped out before it can reach the API and therefor the user's request to default that instrument is not honoured 
Unit tests
> feat(payment): PAYMENTS-5513 add setAsDefaultInstrument to the nonce mapping white list

- src/checkout-buttons/checkout-button-options.ts
- src/checkout-buttons/strategies/checkout-button-method-type.ts
- src/customer/customer-request-options.ts
- src/customer/strategies/amazon-pay-v2/amazon-pay-v2-customer-initialize-options.ts
- src/payment/payment-request-options.ts
- src/payment/payment-strategy-type.ts
- src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-initialize-options.ts
- src/payment/strategies/amazon-pay-v2/amazon-pay-v2.mock.ts
- src/payment/strategies/amazon-pay-v2/amazon-pay-v2.ts
- src/shipping/shipping-request-options.ts
- src/shipping/strategies/amazon-pay-v2/amazon-pay-v2-shipping-initialize-options.ts
- Improved documentation.
- Removed the `@alpha` modifier to all the new introduced params. (See #910)
To indicate that Amazon Pay V2 has been officially released.
CircleCI
> docs(payment): INT-3089 Remove the @Alpha modifier to AmazonPayV2

- src/payment/strategies/klarnav2/klarna-supported-countries.ts
- Add ES/EUR support to Klarna
As a merchant based in Spain, with an EU Klarna account, I want to be able to accept payment in EUR.
https://github.com/bigcommerce/bigpay/pull/2919
https://github.com/bigcommerce/bigcommerce/pull/36826
> feat(payment): INT-3032 Add ES/EUR support to Klarna

- src/payment/payment-methods.mock.ts
- src/payment/strategies/adyenv2/adyenv2-payment-strategy.ts
- src/payment/strategies/adyenv2/adyenv2.mock.ts
- src/payment/strategies/adyenv2/adyenv2.ts
Added client key to authenticate requests from the web environment according to https://docs.adyen.com/development-resources/client-side-authentication
As a a merchant that has a subdomains BC stores, when I enable configure AdyenV2
I want to be able to accept payment from through any of my subdomains that have my AdyenV2 account configured,
So that I can accept payment through them with my same AdyenV2 account.
[bigcommerce/bigcommerce#36823](https://github.com/bigcommerce/bigcommerce/pull/36823)
[bigcommerce/ng-payments#1119](https://github.com/bigcommerce/ng-payments/pull/1119)
[bigcommerce/bigpay#2913](https://github.com/bigcommerce/bigpay/pull/2913)
ping @bigcommerce/checkout @bigcommerce/payments @bigcommerce/apex-integrations.
> feat(payments): INT-3027 Implementing client key

- src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-strategy.spec.ts
- src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-strategy.ts
- src/payment/create-payment-strategy-registry.ts
- src/payment/payment-strategy-type.ts
- src/payment/strategies/paypal-commerce/index.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-credit-card-payment-strategy.spec.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-credit-card-payment-strategy.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-hosted-form.spec.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-hosted-form.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-payment-initialize-options.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-regular-field.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-script-loader.spec.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-script-loader.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-sdk.ts
- src/payment/strategies/paypal-commerce/paypal-commerce.mock.ts
Implement `PaypalCommerceCreditCardPaymentStrategy` with PayPal sdk
Related task https://github.com/bigcommerce/checkout-js/pull/375
Accept credit card details using PayPal's hosted payment form
I'll add tests later
> feat(payment): PAYPAL-202 Hosted Credit Card

- src/payment/payment-methods.mock.ts
- src/payment/strategies/adyenv2/adyenv2-payment-strategy.ts
- src/payment/strategies/adyenv2/adyenv2.mock.ts
- src/payment/strategies/adyenv2/adyenv2.ts
Reverts bigcommerce/checkout-sdk-js#968
It got merged before dependencies got bumped
> Revert "feat(payments): INT-3027 Implementing client key"

- src/payment/payment-methods.mock.ts
- src/payment/strategies/adyenv2/adyenv2-payment-strategy.ts
- src/payment/strategies/adyenv2/adyenv2-script-loader.spec.ts
- src/payment/strategies/adyenv2/adyenv2.mock.ts
- src/payment/strategies/adyenv2/adyenv2.ts
Added client key to authenticate requests from the web environment according to https://docs.adyen.com/development-resources/client-side-authentication
As a a merchant that has a subdomains BC stores, when I enable configure AdyenV2
I want to be able to accept payment from through any of my subdomains that have my AdyenV2 account configured,
So that I can accept payment through them with my same AdyenV2 account.
[bigcommerce/bigcommerce#36823](https://github.com/bigcommerce/bigcommerce/pull/36823)
[bigcommerce/ng-payments#1119](https://github.com/bigcommerce/ng-payments/pull/1119)
[bigcommerce/bigpay#2913](https://github.com/bigcommerce/bigpay/pull/2913)
ping @bigcommerce/checkout @bigcommerce/payments @bigcommerce/apex-integrations.
> feat(payment): INT-3027 Implementing client key

- src/order/order.ts
Added mandate field on order interface
In order to show mandate on order on checkout confirmation Page.
[Checkout JS #404](https://github.com/bigcommerce/checkout-js/pull/404)
[Bigpay #2906](https://github.com/bigcommerce/bigpay/pull/2906)
[BigCommerce #36755](https://github.com/bigcommerce/bigcommerce/pull/36755)
> feat(payment): INT-3061 added mandate field on order interface

- src/payment/errors/index.ts
- src/payment/errors/payment-invalid-form-error.ts
- src/payment/strategies/braintree/braintree-hosted-form.spec.ts
- src/payment/strategies/braintree/braintree-hosted-form.ts
- src/payment/strategies/braintree/braintree-regular-field.ts
- src/payment/strategies/braintree/braintree.ts
Fix `onValidate` callback not getting called with the correct error type and not getting called when `tokenize` returns a validation error.
Related PR: https://github.com/bigcommerce/checkout-js/pull/408
Otherwise, the client doesn't get notified with the correct error type, therefore cannot display errors correctly to the end user.
CircleCI + Manual
> CHECKOUT-5135: Fix `onValidate` callback not getting called with correct error type and not getting called when tokenize returns validation error

- src/payment/strategies/braintree/braintree-credit-card-payment-strategy.spec.ts
- src/payment/strategies/braintree/braintree-credit-card-payment-strategy.ts
Set `isHostedFormInitialized` flag back to false when `deinitialize` is called.
The user can be switching between using a form vs not using a form. For example, you switch from using a stored credit card that requires verification vs a card that doesn't required verification. If this flag is not reset to false accordingly, we'll always try to submit with the hosted form, which may already be cleaned up / teared down.
CircleCI + Manual
> CHECKOUT-5135: Reset Braintree hosted form initialisation state

- src/payment/instrument/supported-payment-instruments.ts
[INT-2779](https://jira.bigcommerce.com/browse/INT-2779): Add vaulting feature for Orbital.
To display vaulted cards with Orbital at checkout screen.
Vaulted credit card on Orbital at checkout:
* [Bigpay # 2938](https://github.com/bigcommerce/bigpay/pull/2938)
> feat(checkout): INT-2779 Add vaulting support for Orbital

- src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-options.ts
- src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-strategy.spec.ts
- src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-strategy.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-payment-processor.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-sdk.ts
- src/payment/strategies/paypal-commerce/paypal-commerce.mock.ts
Adding banners initialization to the buttons renderer
Implement banner with the dynamic prices on cart page
> feat(payment): PAYPAL-705 add messaging for PayPal banners

- src/payment/payment-methods.mock.ts
- src/payment/strategies/stripev3/stripev3-initialize-options.ts
- src/payment/strategies/stripev3/stripev3-payment-strategy.spec.ts
- src/payment/strategies/stripev3/stripev3-payment-strategy.ts
- src/payment/strategies/stripev3/stripev3.mock.ts
- src/payment/strategies/stripev3/stripev3.ts
I want to offer my merchants the ability to display single card component or independent for each field.
-- Unit
-- Manual
[checkout-js](https://github.com/bigcommerce/checkout-js/pull/420)
[bcapp](https://github.com/bigcommerce/bigcommerce/pull/37309)
> feat(payments): INT-3086 Support mounting individual card fields on StripeV3

- src/payment/strategies/braintree/braintree-payment-processor.spec.ts
- src/payment/strategies/braintree/braintree-payment-processor.ts
- src/payment/strategies/braintree/braintree-sdk-creator.spec.ts
- src/payment/strategies/braintree/braintree-sdk-creator.ts
- src/payment/strategies/braintree/braintree.ts
Update Braintree to 3DS v2
https://developers.braintreepayments.com/guides/3d-secure/migration/javascript/v3
Because of right now we are supporting v1 only 
3DS v1
3DS v2
> feat(payment): PAYPAL-675 Upgrade to 3DS v2 Braintree

- src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-strategy.spec.ts
- src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-strategy.ts
- src/payment/create-payment-strategy-registry.ts
- src/payment/strategies/paypal-commerce/index.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-credit-card-payment-strategy.spec.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-credit-card-payment-strategy.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-hosted-form.spec.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-hosted-form.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-payment-processor.spec.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-payment-processor.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.spec.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-script-loader.spec.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-script-loader.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-sdk.ts
Fix bug, when buyer can't switch on the checkout between payment methods
Add one script for different methods (https://github.com/paypal/paypal-js)
Script changed each time when buyer changed method
I call `createPaypalCommercePaymentProcessor` separately for each method, because in this case we can `close` PayPal buttons for the method that was closed. In previous case (one `createPaypalCommercePaymentProcessor` for all methods) I had errors, because `deinitialize` was called after `initialize` and close button
https://www.loom.com/share/c54ef8c4859e48c1a201f6b5ef281836
> fix(payment): PAYPAL-726 Switch payment methods

- src/payment/strategies/adyenv2/adyenv2-initialize-options.ts
- src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-initialize-options.ts
- src/payment/strategies/amazon-pay/amazon-pay-payment-initialize-options.ts
- src/payment/strategies/bluesnapv2/bluesnapv2-payment-options.ts
- src/payment/strategies/bolt/bolt-payment-initialize-options.ts
- src/payment/strategies/braintree/braintree-payment-options.ts
- src/payment/strategies/braintree/braintree-visacheckout-payment-initialize-options.ts
- src/payment/strategies/chasepay/chasepay-initialize-options.ts
- src/payment/strategies/credit-card/credit-card-payment-initialize-options.ts
- src/payment/strategies/googlepay/googlepay-initialize-options.ts
- src/payment/strategies/klarna/klarna-payment-initialize-options.ts
- src/payment/strategies/klarnav2/klarnav2-payment-initialize-options.ts
- src/payment/strategies/masterpass/masterpass-payment-initialize-options.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-payment-initialize-options.ts
- src/payment/strategies/paypal/paypal-express-payment-initialize-options.ts
- src/payment/strategies/square/square-payment-initialize-options.ts
- src/payment/strategies/stripev3/stripev3-initialize-options.ts
Add examples on how to initialize various payment methods.
They serve as reference materials. It's easier to understand the API doc when there are examples to refer to.
None
> CHECKOUT-5098: Add examples on how to initialize various payment methods

- src/order/order.ts
Renamed mandate field to mandateUrl on order interface
In order to match the persistence and communicate the intended usage.
[Checkout-JS #435](https://github.com/bigcommerce/checkout-js/pull/435)
@bigcommerce/apex-integrations
> feat(payment): INT-3061 renamed mandate field to mandateUrl on order interface

- src/checkout/checkout-service.ts
Add documentation for CheckoutService#signOut, when "cross cart retrieval" is enabled
It seems to be a common issue across a few merchants, not handling this error properly.
ci
> CHECKOUT-4871 Add documentation for CheckoutService#signOut

- src/payment/strategies/paypal-commerce/paypal-commerce-credit-card-payment-strategy.spec.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-credit-card-payment-strategy.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-hosted-form.spec.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-hosted-form.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-payment-processor.spec.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-payment-processor.ts
Validate credit cards before submit order
Validation should be performed right after a buyer clicked place order (without allowing call for POST internalapi/v1/checkout/order)
https://www.loom.com/share/2154e46c3f584fd3aaa7b8e27ba6690e
> fix(payment): PAYPAL-766 Validate cc before submit order

- src/payment/strategies/klarna/klarna-payment-strategy.ts
- src/payment/strategies/klarnav2/klarnav2-payment-strategy.ts
[INT-3311](https://jira.bigcommerce.com/browse/INT-3311) Klarna Payments: Unable to checkout with a coupon
Fix an issue that prevents that a coupon is used when trying to checkout with Klarna and a coupon is added
The issue don't let customers use coupon codes in the checkout with klarna
https://drive.google.com/file/d/1ErQeEAaaqbQrnHZd1q5kDN49-mOFZOBG/view?usp=sharing
https://drive.google.com/file/d/1ZY9Tr93AgNr14kKZD_iE3sQQy1xYdhhG/view?usp=sharing
> fix(payment): INT-3311 klarna can checkout with coupons

- src/payment/create-payment-strategy-registry.spec.ts
- src/payment/create-payment-strategy-registry.ts
- src/payment/instrument/supported-payment-instruments.ts
- src/payment/payment-methods.mock.ts
- src/payment/payment-strategy-type.ts
- src/payment/strategies/barclays/barclays-payment-strategy.spec.ts
- src/payment/strategies/barclays/barclays-payment-strategy.ts
- src/payment/strategies/barclays/index.ts
- src/payment/strategies/cardinal/cardinal-client.spec.ts
- src/payment/strategies/cardinal/cardinal-client.ts
- src/payment/strategies/cardinal/cardinal-three-d-secure-flow-v2.spec.ts
- src/payment/strategies/cardinal/cardinal-three-d-secure-flow-v2.ts
- src/payment/strategies/cardinal/cardinal.ts
- src/payment/strategies/cardinal/index.ts
1. Creates 'Barclays' payment strategy and makes it available in checkout.
2. Creates a new version of Cardinal 3DS Flow to be used in this integration and planned to be used in future ones.
A new payment strategy is required to support Barclays with Cardinal 3DS v2
CircleCI
Ping @bigcommerce/apex-integrations @bigcommerce/checkout @bigcommerce/payments
> feat(payment): INT-3438 Integrate Barclays strategy

- src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-strategy.spec.ts
- src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-strategy.ts
As a GB sellers
I want to enable Pay-in-3 option
So that I can increase my sales volume
We need to extend logic to enable Pay-in-3 banners on Card
Tests updated
Manual testing
> feat(payments): PAYPAL-800 PPCP: Pay-in-3

- src/payment/strategies/paypal-commerce/paypal-commerce-hosted-form.spec.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-hosted-form.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-payment-processor.spec.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-payment-processor.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-sdk.ts
Submit cardholder name to PayPal
We need to send cardholder name to PayPal when the order is placed through the credit card method of PPCP.
Manual, unit
> feat(payment): PAYPAL-837 Submit cardholder name to PayPal

- src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.spec.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.ts
Move method_id in execute
During the implementation of APMs, we implemented it they it reflects the name of the provider for each order PayPal commerce.
However, in order to calculate GMV per each particular APM we have to reflect each APM name in the order in the way like - payment method - PayPal (Sofort).
We need to pass `method_id` in request to bigpay for purchase
Manual, unit
> feat(payments): PAYPAL-839 Move method_id in execute

- src/payment/strategies/cardinal/cardinal-client.spec.ts
- src/payment/strategies/cardinal/cardinal-client.ts
Allow reconfiguration of the Cardinal SDK and avoid throwing an error if the consumer cancels the challenge.
For cardinal flow v2 we need to be able to run the configuration step each time a new `ReferenceId` is generated (this happens each time the user is challenged). Otherwise, browser data won't be collected for the new `ReferenceId` and auth will downgrade to 3DS v1
Manual, Unit / [Demo Video](https://drive.google.com/file/d/1sRMIcIOp9-cJcSElMic-EjtSktQanL_a/view?usp=sharing)
> feat(payment): INT-3237 Prevent Cardinal downgrade to 3DSv1

- src/analytics/create-step-tracker.ts
- src/currency/create-currency-service.ts
Remove alpha tags from stable functionality
Functionality has been in use for a long period and proven to be stable.
CI
> CHECKOUT-4571 Remove alpha tags from stable functionality

- src/payment/create-payment-strategy-registry.ts
- src/payment/strategies/adyenv2/adyenv2-payment-strategy.spec.ts
- src/payment/strategies/adyenv2/adyenv2-payment-strategy.ts
Replaced browser language instead locale variable on adyenv2
In order to the merchant has the ability to translate adyenv2 components labels with browser language.
> feat(payments): INT-3538 Replaced browser language instead locale variable on Adyenv2

- src/payment/create-payment-strategy-registry.ts
- src/payment/payment-methods.mock.ts
- src/payment/strategies/googlepay/googlepay-adyenv2-initializer.ts
- src/payment/strategies/googlepay/googlepay-adyenv2-payment-processor.spec.ts
- src/payment/strategies/googlepay/googlepay-adyenv2-payment-processor.ts
- src/payment/strategies/googlepay/googlepay-payment-strategy.spec.ts
- src/payment/strategies/googlepay/googlepay-payment-strategy.ts
- src/payment/strategies/googlepay/index.ts
Create a new strategy for googlepay Adyen where 3DS could be handle
In order to have 3DS working for google pay on AdyenV2
[BigCommerce PR](https://github.com/bigcommerce/bigcommerce/pull/38152)
[BigPay PR](https://github.com/bigcommerce/bigpay/pull/3190)
[Checkout-JS](https://github.com/bigcommerce/checkout-js/pull/470)
> feat(payment): INT-2816 Added 3DS to googlepay adyenv2

- src/payment/payment-methods.mock.ts
- src/payment/strategies/googlepay/googlepay-adyenv2-payment-processor.spec.ts
mockReturn to getStoreConfig in order to make the processor work
Unit test were broken
> fix(payments): INT-2816 fix unit test for googlepay adyenv2 payment processor

- src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-strategy.spec.ts
- src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-strategy.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-script-loader.spec.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-script-loader.ts
Add `messages` to `components` in PayPal script always in the PaypalCommerceButtonStrategy
It needs for credit banners. PayPal recommends us to use SDK for banners in the way it is implemented on the cart page
Related task https://github.com/bigcommerce/content/pull/615
https://www.loom.com/share/252298feb82047f388deb0f55a9a95d6
> feat(payment): PAYPAL-848 Add messages to script

- src/checkout/checkout-service.spec.ts
- src/checkout/checkout-service.ts
- src/checkout/create-checkout-service.ts
Load form fields when loading order
Because now the order confirmation page retrieves the form fields from the new endpoint, rather than from checkout-settings endpoint, causing an error.
> CHECKOUT-4941 Load form fields when loading order

- src/payment/strategies/googlepay/googlepay-payment-strategy.spec.ts
Fix unit test for googlepay-adyenv2-payment. Removes time-offset assertion.
It depends on what machine is being executed, it could fail.
unit
> INT-2816 Fix unit test for googlepay-adyenv2-payment

- src/payment/strategies/braintree/braintree-credit-card-payment-strategy.spec.ts
- src/payment/strategies/braintree/braintree-credit-card-payment-strategy.ts
- src/payment/strategies/braintree/braintree-hosted-form.spec.ts
- src/payment/strategies/braintree/braintree-hosted-form.ts
- src/payment/strategies/braintree/braintree-payment-processor.ts
Fixed the issue with collection device data and sending it to Braintree when buyer uses credit cards vaulting.
Changes:
- don't initialize Braintree Hosted Fields SDK when there are no fields on the credit card form
When buyer uses stored credit cards device data isn't sent to Braintree and transactions are rejected by anti-fraud mechanisms.
The issue is that Hosted Fields Braintree JS SDK requires non empty `fields` option to initialize Hosted Fields ([documentation](https://braintree.github.io/braintree-web/current/module-braintree-web_hosted-fields.html#.create), [source](https://github.com/braintree/braintree-web/blob/3.59.0/src/hosted-fields/external/hosted-fields.js#L418)) and to declare credit card fields which are precent on the form. But there are some cases when there is no any …
> fix(provider): PAYPAL-767 Fix device data collection for Braintree stored credit cards

- src/checkout/checkout-reducer.ts
- src/checkout/checkout-service.spec.ts
- src/checkout/checkout-service.ts
- src/checkout/create-checkout-service.ts
- src/config/config.ts
- src/config/configs.mock.ts
- src/customer/create-customer-strategy-registry.ts
- src/customer/customer-account.ts
- src/customer/customer-action-creator.spec.ts
- src/customer/customer-action-creator.ts
- src/customer/customer-actions.ts
- src/customer/customer-request-sender.ts
- src/customer/customer-strategy-action-creator.spec.ts
- src/customer/strategies/default/default-customer-strategy.spec.ts
- src/payment/payment-strategy-action-creator.spec.ts
- src/payment/payment-strategy-action-creator.ts
- src/spam-protection/create-spam-protection.ts
- src/spam-protection/index.ts
- src/spam-protection/is-spam-protection-succeeded-action.ts
- src/spam-protection/spam-protection-action-creator.spec.ts
- src/spam-protection/spam-protection-action-creator.ts
- src/spam-protection/spam-protection-actions.ts
Add support for recaptcha for customer account creation
Because when Storefont recaptcha is enabled, it's required for customer account creation
unit
> CHECKOUT-5418 Add support for recaptcha for customer account creation

- src/payment/payment-methods.mock.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.spec.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-sdk.ts
Add mechanism for testing of the APMs for different countries
By default Paypal connect appropriate APMs, depending on the country of the buyer, which Paypal determine by location and other factors, however, to check any APM in the test mode without using VPN, we force-pushed the country if the test mode is enabled.
Tested on dev
> feat(payments): PAYPAL-830 Add mechanism for testing of the APMs for different countries

- src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.ts
TypeError: Cannot read property 'orderId' of null
According to task PAYPAL-787
tested on dev
> feat(payment): PAYPAL-787 TypeError: Cannot read property 'orderId' of null

- src/checkout/checkout.ts
- src/checkout/checkouts.mock.ts
- src/order/order.ts
- src/order/orders.mock.ts
- src/payment/strategies/googlepay/googlepay.mock.ts
Add gift wrapping total
Because API will expose this new attribute
unit / ci
> CHECKOUT-2322 Add gift wrapping total

- src/payment/strategies/stripev3/stripev3-payment-strategy.spec.ts
- src/payment/strategies/stripev3/stripev3-payment-strategy.ts
- src/payment/strategies/stripev3/stripev3.mock.ts
[INT-3655](https://jira.bigcommerce.com/browse/INT-3655): Stripe V3 - Some customers unable to checkout with Stripe
This issue hasn't been reproduced, at least without forcing it to happen, it seems that sometimes the nonce token is not loaded and is sent as null to BigPay, the strategy should not allow this, so we are checking it before sending the payload to BigPay
Customers are presenting issues that prevent them to finishing the payment when using Stripe as payment method, which end in bad user experience 
Tests
Message that the client will see
> fix(provider): INT-3655 Avoid passing null nonce token to StripeV3

- src/payment/create-payment-strategy-registry.spec.ts
- src/payment/create-payment-strategy-registry.ts
- src/payment/payment-strategy-type.ts
- src/payment/strategies/cybersourcev2/cybersourcev2-payment-strategy.spec.ts
- src/payment/strategies/cybersourcev2/cybersourcev2-payment-strategy.ts
- src/payment/strategies/cybersourcev2/index.ts
I want to offer merchants the possibility to migrate from previous Cybersource integration reducing friction while configuring and adding features not existing on previous.  
Ping @bigcommerce/apex-integrations
> feat(payments): INT-3537 Add CYBS One Platform Payment Strategy

- src/hosted-form/iframe-content/get-hosted-input-storage.ts
- src/hosted-form/iframe-content/hosted-input-storage.spec.ts
- src/hosted-form/iframe-content/hosted-input-storage.ts
Set the nonce of a hosted form in memory instead of local storage.
We don't need to set it in local storage anymore with the changes proposed in https://github.com/bigcommerce/bigpay/pull/3415.
Unit
@bigcommerce/checkout @bigcommerce/payments @bigcommerce/security
> CHECKOUT-5324: Set nonce in memory instead of local storage

- src/payment/create-payment-strategy-registry.ts
- src/payment/index.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-payment-initialize-options.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-payment-processor.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.spec.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-request-sender.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-sdk.ts
Implement polling mechanism on front-end
When we create order we can have drop off scenario, and we need to implement polling mechanism that sends request and ask for status and proceed with succeed flow if order status 'approved'
Tested on Dev
> feat(payments): PAYPAL-876 implement polling mechanism on front-end

- src/payment/create-payment-strategy-registry.spec.ts
- src/payment/create-payment-strategy-registry.ts
- src/payment/payment-strategy-registry.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-payment-processor.spec.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-payment-processor.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.spec.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-request-sender.spec.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-request-sender.ts
Implement logic for APM to always work in Authorize and Capture transaction type on frontend part
According to task PAYPAL-883
Tested on dev
> feat(payments): PAYPAL-883 Implement logic for APM to always work in Authorize and Capture transaction type on frontend part

- src/payment/instrument/supported-payment-instruments.ts
Added cybersourcev2 to supported payments instruments
In order to show vaulted instruments on cybersource V2
> feat(payment): INT-3831 enable vaulting on cybersource v2

- src/order/order-request-body.ts
- src/payment/create-payment-strategy-registry.spec.ts
- src/payment/create-payment-strategy-registry.ts
- src/payment/index.ts
- src/payment/instrument/supported-payment-instruments.ts
- src/payment/payment-response-body.ts
- src/payment/payment-strategy-registry.ts
- src/payment/payment-strategy-type.ts
- src/payment/payment.ts
- src/payment/strategies/checkoutcom-apm/checkoutcom-apm-payment-strategy.spec.ts
- src/payment/strategies/checkoutcom-apm/checkoutcom-apm-payment-strategy.ts
- src/payment/strategies/checkoutcom-apm/index.ts
Create a payment strategy that will handle the APMs on checkout.com.
This strategy will handle `additional actions` when submitting payment  such as a redirect and submit special fields as part of the formatted payload such as `document`.
This PR establishes the base for the future APM implementation.
This PR has only been tested on development environment to work as expected, and on integrations to keep checkout.com working as is until the new functionality is developed and tested
> feat(checkout): INT-2544 Create strategy For redirect flow on checkout.com APMs

- src/checkout/checkout-service.spec.ts
- src/checkout/checkout-service.ts
- src/checkout/checkout-store-error-selector.ts
- src/checkout/checkout-store-status-selector.ts
- src/customer/customer-account.ts
- src/customer/customer-action-creator.spec.ts
- src/customer/customer-action-creator.ts
- src/customer/customer-actions.ts
- src/customer/customer-reducer.spec.ts
- src/customer/customer-reducer.ts
- src/customer/customer-request-sender.spec.ts
- src/customer/customer-request-sender.ts
- src/customer/customer-selector.spec.ts
- src/customer/customer-selector.ts
- src/customer/customer-state.ts
- src/customer/index.ts
Allow creating customer address. Alpha functionality.
To allow creating customer addresses during checkout, which can be used for the multishipping UI.
unit
> CHECKOUT-4726 Allow creating customer address

- src/payment/strategies/paypal-commerce/paypal-commerce-request-sender.spec.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-request-sender.ts
Fixed endpoint from paypalcommercealternativemethods to paypalcommercealternativemethodscheckout
To fix polling mechanism
...
> feat(payment): PAYPAL-876 fixed paypalcommerce initialization endpoint

- src/payment/payment.ts
- src/payment/strategies/stripev3/stripev3-payment-strategy.spec.ts
- src/payment/strategies/stripev3/stripev3-payment-strategy.ts
- src/payment/strategies/stripev3/stripev3.mock.ts
- src/payment/strategies/stripev3/stripev3.ts
I changed the code of PaymentIntent confirmation in the frontend with the creation of a paymentMethod with credit card details. This change is to create and process the PaymentIntent in BigPay and only keep the credit card details actions in checkout-sdk.
Multiple paymentIntents are created with the current approach and kept as incomplete, and with this approach we also help to avoid different order amounts when the paymentIntent is created and when the transaction is processed in BigPay.
Manual testing along with this PR: [INT-3660](https://github.com/bigcommerce/bigpay/pull/3339)
Unit testing: 
**Note**: We need to merge first https://github.com/bigcommerce/bigpay/pull/3339 to won't affect any merchant
> feat(provider): INT-3659 Add payment method flow to Stripe v3

- src/checkout-buttons/checkout-button-options.ts
- src/checkout-buttons/create-checkout-button-registry.spec.ts
- src/checkout-buttons/create-checkout-button-registry.ts
- src/checkout-buttons/strategies/checkout-button-method-type.ts
- src/checkout-buttons/strategies/googlepay/googlepay-button.mock.ts
- src/checkout-buttons/strategies/googlepay/googlepay-cybersourcev2-button-strategy.spec.ts
- src/customer/create-customer-strategy-registry.ts
- src/customer/customer-request-options.ts
- src/customer/strategies/googlepay/googlepay-customer-mock.ts
- src/customer/strategies/googlepay/googlepay-customer-strategy.ts
- src/customer/strategies/googlepay/googlepay-cybersourcev2-customer-strategy.spec.ts
- src/payment/create-payment-strategy-registry.spec.ts
- src/payment/create-payment-strategy-registry.ts
- src/payment/payment-methods.mock.ts
- src/payment/payment-request-options.ts
- src/payment/payment-strategy-type.ts
- src/payment/strategies/googlepay/googlepay-cybersourcev2-initializer.spec.ts
- src/payment/strategies/googlepay/googlepay-cybersourcev2-initializer.ts
- src/payment/strategies/googlepay/googlepay-payment-strategy.ts
- src/payment/strategies/googlepay/googlepay.mock.ts
- src/payment/strategies/googlepay/index.ts
Added googlepay on cybersourcev2
In order to show google pay like an option when cybersource is enabled on checkout.
> feat(payment): INT-3418 Added googlepay on cybersourcev2

- src/payment/strategies/braintree/braintree-paypal-payment-strategy.spec.ts
- src/payment/strategies/braintree/braintree-paypal-payment-strategy.ts
Refresh the values in store
when the backend delete the **nonce** value in the front-end is not refreshed, then every time we want to pay we are using the same nonce value
https://drive.google.com/file/d/126Y8zs07T9h5KelzlH7lTC4if85KwBem/view?usp=sharing
> fix(payment): INT-3611 Refresh the state in Braintree

- src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.spec.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-sdk.ts
Stop polling mechanism when error occurs
According to task PAYPAL-876
Tested on dev
> feat(payment): PAYPAL-876 stop polling mechanism when error occurs

- src/payment/strategies/braintree/braintree-payment-processor.ts
- src/payment/strategies/braintree/braintree.mock.ts
- src/payment/strategies/braintree/braintree.ts
Fix the 3D Secure in Braintree because sometimes the nonce is not created correctly and the flow process must be break to doesn't show 3D Secure dialog.
Because the transaction is declined after the 3D Secure dialog is showed without any kind of message that what was wrong
[Video](https://drive.google.com/file/d/1rwQ6O5C0JrSHkeAqrndgE3z4gtGgVRXu/view?usp=sharing)
The issue can't be reproduced locally, but we know that the creation of the nonce is the problem, so if the nonce is not created we break the flow of the payment process to doesn't show 3D Secure dialog.
Ping @bigcommerce/payments @bigcommerce/apex-integrations
> fix(checkout): INT-3665 3D Secure is declining the transaction in Braintree without any reason in some stores

- src/payment/strategies/bolt/bolt-script-loader.spec.ts
- src/payment/strategies/bolt/bolt-script-loader.ts
Load Bolt's `track.js` when using Bolt's Fraud option along with lightbox's script.
To make Bolt able to collect data for the best checkout experience.
QA review
> feat(checkout): INT-3675 Add Bolt's tracking script to checkout

- src/checkout-buttons/strategies/masterpass/masterpass-button-strategy.spec.ts
- src/checkout-buttons/strategies/masterpass/masterpass-button-strategy.ts
- src/customer/strategies/masterpass/masterpass-customer-strategy.spec.ts
- src/customer/strategies/masterpass/masterpass-customer-strategy.ts
- src/payment/strategies/masterpass/masterpass-payment-strategy.spec.ts
- src/payment/strategies/masterpass/masterpass-payment-strategy.ts
- src/payment/strategies/masterpass/masterpass-script-loader.ts
Added new URL script and source button on masterpass
In order to be able to continue using Masterpass (now "SRC") when shoppers checkout
So that they can continue accepting payment via Masterpass (SRC).
1# [BIGCOMMERCE #39508](https://github.com/bigcommerce/bigcommerce/pull/39508)
2#[CHECKOUT-SDK-JS #1072](https://github.com/bigcommerce/checkout-sdk-js/pull/1072)
3#[CHECKOUT-JS #1072](https://github.com/bigcommerce/checkout-js/pull/515)
[TESTING PROOF VIDEO](https://drive.google.com/file/d/13DRZY92NnGDP1q-_t9hHnetXGfgZmVak/view?usp=sharing)
@bigcommerce/apex-integrations  @bigcommerce/payments
> feat(payment): INT-3408 migrate masterpass to SRC

- src/payment/strategies/bolt/bolt-payment-strategy.spec.ts
- src/payment/strategies/bolt/bolt-payment-strategy.ts
- src/payment/strategies/bolt/bolt-script-loader.spec.ts
- src/payment/strategies/bolt/bolt-script-loader.ts
- src/payment/strategies/bolt/bolt.ts
Update Bolt's script loader to load scripts from different environments depending on the settings configured in the control panel.
So Bolt's developers can configure their custom development URL on the store for testing purposes.
https://github.com/bigcommerce/ng-payments/pull/1225
https://github.com/bigcommerce/bigcommerce/pull/39355
https://github.com/bigcommerce/bigpay/pull/3447
[Demo Video](https://drive.google.com/file/d/154VVMjyYwEXNBZ_PbAhejZcDjIyXJIBP/view?usp=sharing)
> feat(checkout): INT-3700 Load Bolt Scripts from different environments

- src/payment/strategies/zip/zip-payment-strategy.spec.ts
- src/payment/strategies/zip/zip-payment-strategy.ts
Return the checkouId as nonce value if it's referred payment
we need bigpay save the transaction and the order as pending.
https://drive.google.com/file/d/1QPapnhi3-k68zEq1PyFlFvjpITU0qsJZ/view?usp=sharing
This PR has dependency with [feat(payments): INT-3896 [Zip] getInitializationData indicates if deferred flow experiment is enabled](https://github.com/bigcommerce/bigcommerce/pull/39599)
1. [feat(payment): INT-3896 [Zip] getInitializationData indicates if deferred flow experiment is enabled](https://github.com/bigcommerce/bigcommerce/pull/39599) 
2. This PR
> feat(payment): INT-3896 [Zip] it returns the nonce value when it's a referred payment

- src/payment/strategies/checkoutcom-apm/checkoutcom-apm-payment-strategy.ts
Add Ideal as document supported APM
Ideal requires an additional field to be sent for the payment to proceed
https://github.com/bigcommerce/checkout-js/pull/519
On Sibling PR
> fix(checkout): INT-2546 Add ideal to document supported apms

- package-lock.json
- package.json
- src/payment/strategies/braintree/braintree-payment-processor.spec.ts
- src/payment/strategies/braintree/braintree-payment-processor.ts
- Use Braintree's own `supportsPopups` method to determine if or not to add a dark overlay to our checkout page 
- Without it we are adding our dark overlay on top of the PayPal modal. Braintree/PayPal chooses to use a modal when the current browser does not support a new window (or popup) journey.
Extended unit tests now covering this scenario, plus:
1. Emulated mobile experience where the browser supports new windows (unchanged)
https://user-images.githubusercontent.com/56807262/111715736-9a53d280-88a8-11eb-8c87-05587889f4bd.mov
2. Emulated mobile experience where the browser does **not support** new windows (now without dark overlay obscuring the PayPal form)
https://user-images.githubusercontent.com/56807262/111715754-a50e6780-88a8-11eb-9efa-3cb08a3e29f7.mov …
> fix(payment): PAYMENTS-6642 Make Paypal overlay modal/new window aware

- src/payment/strategies/digitalriver/digitalriver-payment-strategy.ts
- src/payment/strategies/digitalriver/digitalriver.ts
Suppress PayPal and Klarna for DigitalRiver from being renderer. Digital provides us a new param called `disabledPaymentMethods` to do that.
Because Digital River needs to obtain permission from PayPal and Klarna before BigCommerce can support any of these payment methods within our Digital River integration
https://github.com/bigcommerce/checkout-js/pull/537
**Before:**
**After:**
> feat(payment): INT-3947 Suppress PayPal and Klarna

- src/payment/create-payment-strategy-registry.ts
- src/payment/strategies/digitalriver/digitalriver-payment-strategy.spec.ts
- src/payment/strategies/digitalriver/digitalriver-payment-strategy.ts
Add execute logic for Digital River
we want to support in DropIn for Credit Cards 
> feat(payment): INT-3905 creating execute for digital river and creditCard

- src/payment/strategies/googlepay/googlepay-payment-processor.ts
- src/payment/strategies/googlepay/googlepay.mock.ts
The Billing address is missing when payment with google pay in Stripe V3
We are validating the billing address when is retrieving for first time and throw a exception if does not exist
Ping @bigcommerce/payments
> fix(provider): INT-3571 Google Pay [StripeV3] - Billing address is missing

- src/common/iframe/iframe-event-listener.spec.ts
- src/common/iframe/iframe-event-listener.ts
- src/common/iframe/iframe-event-poster.ts
- src/common/url/append-www.spec.ts
- src/common/url/append-www.ts
- src/common/url/index.ts
- src/hosted-form/hosted-field-events.ts
- src/hosted-form/hosted-field.spec.ts
- src/hosted-form/hosted-field.ts
- src/hosted-form/iframe-content/hosted-input-factory.spec.ts
- src/hosted-form/iframe-content/hosted-input-factory.ts
- src/hosted-form/iframe-content/hosted-input-initializer.spec.ts
- src/hosted-form/iframe-content/hosted-input-initializer.ts
Post to and receive messages from `www` subdomain.
Before this change, hosted payment forms do not load for stores that have WWW redirect setting set as "no preference" (meaning it doesn't do any kind of redirect to force shoppers to be on the `ShopPath` domain).
Unit + manual
The test store is set up with WWW redirect setting as "no preference"
> CHECKOUT-5740: Post to and receive messages from `www` subdomain

- src/payment/create-payment-strategy-registry.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.spec.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.ts
Don't show loading indicator if checkout form hasn't passed validation
Due to [PAYPAL-970](https://jira.bigcommerce.com/browse/PAYPAL-970)
> fix(payment): PAYPAL-970 don't show loading indicator if checkout form hasn't passed validation

- src/payment/strategies/digitalriver/digitalriver-payment-strategy.spec.ts
- src/payment/strategies/digitalriver/digitalriver-payment-strategy.ts
- src/payment/strategies/digitalriver/digitalriver-script-loader.spec.ts
- src/payment/strategies/digitalriver/digitalriver-script-loader.ts
- src/payment/strategies/digitalriver/digitalriver.ts
Add support to update drop-in component when coupons or card codes are changed
Because when the Payment step and the drop in component is loaded in Checkout page, we need to reload the drop-in component and create the Digital River checkout object with the most recent cart data to support shoppers updates
https://user-images.githubusercontent.com/42154828/114103626-17161300-988f-11eb-86bc-d977f4ae62fc.mov
> Support coupons & gift cards codes when the Drop-in component is already loaded for Digital River

- src/order/order-request-body.ts
- src/payment/create-payment-strategy-registry.ts
- src/payment/index.ts
- src/payment/payment-strategy-registry.ts
- src/payment/payment-strategy-type.ts
- src/payment/payment.ts
- src/payment/strategies/checkoutcom-custom/checkoutcom-ideal/checkoutcom-ideal-payment-strategy.spec.ts
- src/payment/strategies/checkoutcom-custom/checkoutcom-ideal/checkoutcom-ideal-payment-strategy.ts
- src/payment/strategies/checkoutcom-custom/index.ts
Create a payment strategy for ideal that sends the bic to the backend.
This field is mandatory for Ideal payment to be processed
https://github.com/bigcommerce/checkout-js/pull/541
Pending
> feat(payment): INT-4021 Add strategy for iDeal APM

- src/payment/instrument/supported-payment-instruments.ts
- src/payment/strategies/mollie/mollie-initialize-options.ts
- src/payment/strategies/mollie/mollie-payment-strategy.spec.ts
- src/payment/strategies/mollie/mollie-payment-strategy.ts
- src/payment/strategies/mollie/mollie.mock.ts
- src/payment/strategies/mollie/mollie.ts
added vaulted methods in order to save cc, added vault_payment_intrument variables, and create conditions to mount or not mount mollie components 
We want the user to be able to save cc and use them later when logged in 
> feat(payment): INT-3702 added vaulted cc

- src/payment/instrument/supported-payment-instruments.ts
- src/payment/strategies/mollie/mollie-initialize-options.ts
- src/payment/strategies/mollie/mollie-payment-strategy.spec.ts
- src/payment/strategies/mollie/mollie-payment-strategy.ts
- src/payment/strategies/mollie/mollie.mock.ts
- src/payment/strategies/mollie/mollie.ts
Reverts bigcommerce/checkout-sdk-js#1056
Seems to break checkout-js - see https://github.com/bigcommerce/checkout-js/pull/554
> Revert "feat(payment): INT-3702 added vaulted cc for Mollie"

- src/order/order-request-body.ts
- src/payment/create-payment-strategy-registry.ts
- src/payment/index.ts
- src/payment/payment-strategy-registry.ts
- src/payment/payment-strategy-type.ts
- src/payment/payment.ts
- src/payment/strategies/checkoutcom-custom/checkoutcom-sepa/checkoutcom-fawry-payment-strategy.spec.ts
- src/payment/strategies/checkoutcom-custom/checkoutcom-sepa/checkoutcom-fawry-payment-strategy.ts
- src/payment/strategies/checkoutcom-custom/index.ts
Create a payment strategy for fawry that sends the mobile number and email to the backend.
These two fields are required for Fawry in order to process a payment.
https://github.com/bigcommerce/checkout-js/pull/528
https://github.com/bigcommerce/checkout-sdk-js/pull/1079
Pending...
> feat(payment): INT-2503 Add strategy for checkout.com with Fawry

- src/cart/errors/cart-changed-error.spec.ts
- src/cart/errors/cart-changed-error.ts
- src/checkout/checkout-store-error-selector.ts
- src/checkout/checkout-validator.spec.ts
- src/checkout/checkout-validator.ts
- src/checkout/index.ts
- src/embedded-checkout/iframe-content/iframe-embedded-checkout-messenger.spec.ts
Provide the previous and updated cart as part of `CartChangedError`
So that we can log the contents in case of issues to related to this error.
unit
Tested also in combination with Checkout JS changes
> feat(cart): CHECKOUT-5747 Add cart changed error data

- src/payment/instrument/supported-payment-instruments.ts
- src/payment/strategies/mollie/mollie-initialize-options.ts
- src/payment/strategies/mollie/mollie-payment-strategy.spec.ts
- src/payment/strategies/mollie/mollie-payment-strategy.ts
- src/payment/strategies/mollie/mollie.mock.ts
- src/payment/strategies/mollie/mollie.ts
added vaulted methods in order to save cc, added vault_payment_intrument variables, and create conditions to mount or not mount mollie components 
We want the user to be able to save cc and use them later when logged in 
> feat(payment): INT-3702 Add vaulted credit card support for Mollie

- src/payment/strategies/zip/zip-payment-strategy.spec.ts
- src/payment/strategies/zip/zip-payment-strategy.ts
Parent ticket: [INT-3825](https://jira.bigcommerce.com/browse/INT-3825)
[INT-4150](https://jira.bigcommerce.com/browse/INT-4150)
In order to implement new refactor for zip flow I added a new validation to submit payment and let backend handles the verification of payment status.
Due to security concerns previously discussed this refactor is needed.
Demo:
https://drive.google.com/file/d/1IJaeEQxmunYbUaI9XTNmNsTqmQMER_fU/view?usp=sharing
Sibling PR CheckoutJS: https://github.com/bigcommerce/checkout-js/pull/560
> feat(payments): INT-4150 changing zip strategy flow

- src/payment/strategies/stripev3/stripev3-payment-strategy.spec.ts
- src/payment/strategies/stripev3/stripev3-payment-strategy.ts
- src/payment/strategies/stripev3/stripev3.ts
Handle RequestError's `required_field` code in order to show a more descriptive [message](https://stripe.com/docs/api/errors#errors-message) to the shopper instead of the generic one provided by bigpay.
To improve UX and error tracing.
_Before:_
_After:_
https://github.com/bigcommerce/bigpay/pull/3736
> feat(payment): INT-4258 StripeV3: Improve error handling

- src/payment/create-payment-strategy-registry.spec.ts
- src/payment/create-payment-strategy-registry.ts
- src/payment/payment-methods.mock.ts
- src/payment/payment-strategy-registry.spec.ts
- src/payment/payment-strategy-registry.ts
- src/payment/payment-strategy-type.ts
- src/payment/strategies/ppsdk/index.ts
- src/payment/strategies/ppsdk/ppsdk-strategy.ts
https://jira.bigcommerce.com/browse/PAYMENTS-6806
BCApp Experiment PR: https://github.com/bigcommerce/bigcommerce/pull/40715
- Add the start of a PPSDK Strategy behind an experiment flag: `PAYMENTS-6806.enable_ppsdk_strategy`
- The initial strategy is just a dummy class with no functionality
- To safely begin building out the ability to consume PPSDK payment methods
- Passing tests
- No outward changes - due to work in progress being gated behind flag
> feat(payment): PAYMENTS-6806 add dummy PPSDK strategy

- src/order/order-request-body.ts
- src/payment/index.ts
- src/payment/payment.ts
- src/payment/strategies/klarnav2/klarna-supported-countries.ts
- src/payment/strategies/mollie/mollie-payment-strategy.spec.ts
- src/payment/strategies/mollie/mollie-payment-strategy.ts
- src/payment/strategies/mollie/mollie.mock.ts
List Issuing Banks In Dropdown on Payment Step, adding  IssuerInstrument to Mollie on strategy and payment
Adding BE and IT to the `klarna-supported-countries.ts` in order for Klarna to Suppport these countries
Some APMs such as Ideal have bank from where to choose, 
[JS](https://github.com/bigcommerce/checkout-js/pull/566)
[BCAPP](https://github.com/bigcommerce/bigcommerce/pull/40630)
[BIGPAY](https://github.com/bigcommerce/bigpay/pull/3748)
> feat(payment): INT-4237 Add issuer for Mollie APMs

- src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-strategy.ts
[INT-3941](https://jira.bigcommerce.com/browse/INT-3941)
- When you create a cart that contains a channel id, the amazon pay button in the checkout takes from bcapp a path that brings null, So if that channel id does not have a linked site, it comes with null. But that shouldn't affect the remote-checkout button so the path was changed to redirect to the correct domain of the store.
- It uses a path that should not use because it would be a different domain than the BigCommerce Store and it is a requirement of Amazon Pay. (Only one BigCommerce store can be linked to a single Seller Central account).
There are 3 ways to initialize the payment button of amazon pay and only one of them did not work, so we changed the path like the others and now it works.
1) createCheckoutSession: {
url: …
> fix(checkout): INT-3941 Updated remote-checkout path on button initialization

- src/payment/payment-method.ts
- src/payment/ppsdk-initialisation-strategies.ts
- Extend the SDK's notion of `PaymentMethod`s that will come over the wire to include a new, optional `initializationStrategy` attribute
- `initializationStrategy` will be a union of all future PPSDK 'initialisation strategies', each with their own schema
- In future work these extra details can be used by the `PPSDKStrategy` for it to init correctly (https://github.com/bigcommerce/checkout-sdk-js/blob/d57e3ba074a16a8f4fed4aa3389ebcbcd374c5bb/src/payment/strategies/ppsdk/ppsdk-strategy.ts currently a wip, behind an experiment flag)
- So this new `PaymentMethod` shape is inherited by `checkout-js`, where it can be used to render the correct PPSDK UIs (https://github.com/bigcommerce/checkout-js/pull/586)
- None: this is an additive, optional attribute on an existing type …
> feat(payment): PAYMENTS-6813 extend Payment Method type to cover PPSDK variants

- src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.spec.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.ts
Removed geolocation restrictions for PAYPAL APMs. Now we will check what APM is available on billing address
Due to https://jira.bigcommerce.com/browse/PAYPAL-1024
Tested manually.
Now on initialisation of Paypal we added funding-eligibility component and added enable-funding field where we're passing  APM id. this payment method will be eligible after these modifications.
> feat(checkout): PAYPAL-1024 make APM work regardless of  geolocation

- src/checkout-buttons/checkout-button-options.ts
- src/checkout-buttons/strategies/googlepay/googlepay-adyenv2-button-strategy.spec.ts
- src/checkout-buttons/strategies/googlepay/googlepay-authorizenet-button-strategy.spec.ts
- src/checkout-buttons/strategies/googlepay/googlepay-braintree-button-strategy.spec.ts
- src/checkout-buttons/strategies/googlepay/googlepay-button-strategy.ts
- src/checkout-buttons/strategies/googlepay/googlepay-button.mock.ts
- src/checkout-buttons/strategies/googlepay/googlepay-checkoutcom-button-strategy.spec.ts
- src/checkout-buttons/strategies/googlepay/googlepay-cybersourcev2-button-strategy.spec.ts
- src/checkout-buttons/strategies/googlepay/googlepay-stripe-button-strategy.spec.ts
- src/customer/strategies/googlepay/googlepay-customer-initialize-options.ts
- src/customer/strategies/googlepay/googlepay-customer-strategy.ts
In order to change UI button experience it was  passed type an color parameters to createbutton method
[TESTING PROOF VIDEO](https://drive.google.com/file/d/1MO5iRPADbiICc1qyWlI_RbYnHjIOmcFG/view?usp=sharing)
> feat(payment): INT-4197 added type and color parameters on googlepay checkout button

- src/payment/create-payment-strategy-registry.ts
- src/payment/payment-methods.mock.ts
- src/payment/payment-request-options.ts
- src/payment/payment-strategy-type.ts
- src/payment/strategies/moneris/index.ts
- src/payment/strategies/moneris/moneris-payment-initialize-options.ts
- src/payment/strategies/moneris/moneris-payment-strategy.spec.ts
- src/payment/strategies/moneris/moneris-payment-strategy.ts
- src/payment/strategies/moneris/moneris.ts
Create Moneris payment strategy which mounts an iframe and sends events to the iframe and listens to evens sent from the iframe
This is the way its implementation works and its based on [their documentation](https://developer.moneris.com/Documentation/NA/E-Commerce%20Solutions/Hosted%20Solutions/Hosted%20Tokenization) for the Hosted tokenization 
https://github.com/bigcommerce/checkout-js/pull/563
> feat(payment): INT-4205 Add Moneris strategy

- src/checkout-buttons/create-checkout-button-registry.ts
- src/checkout-buttons/index.ts
- src/checkout-buttons/strategies/braintree/braintree-paypal-button-strategy.spec.ts
- src/checkout-buttons/strategies/braintree/braintree-paypal-button-strategy.ts
- src/checkout-buttons/strategies/paypal/paypal-button-strategy.spec.ts
- src/payment/strategies/braintree/braintree-script-loader.spec.ts
- src/payment/strategies/braintree/braintree-script-loader.ts
- src/payment/strategies/braintree/braintree-sdk-creator.ts
- src/payment/strategies/braintree/braintree.ts
- src/payment/strategies/paypal/paypal-express-payment-strategy.spec.ts
- src/payment/strategies/paypal/paypal-sdk.ts
- src/payment/strategies/paypal/paypal.mock.ts
Upgrading Braintree version SDK 3.59.0 => 3.70.0
Documentation for migration : https://developers.braintreepayments.com/guides/paypal/paypal-sdk-migration-guide/javascript/v3
According to task PAYPAL-863.  To show Pay Later smart button and to be consistent with PPC integration.
Tested on dev
Before
After
@bigcommerce/checkout @bigcommerce/payments @davidchin @vneutrino @capsula4
> feat(payment): PAYPAL-863 Braintree: PayPal JS SDK Smart Buttons

- src/payment/payment-methods.mock.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-funding-key-resolver.spec.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-funding-key-resolver.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.spec.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.ts
PAYPAL-1055 changed expected methodId from przelewy24 to p24 at paypal commerce
Removed buyer-country property from paypal commerce initialization because it's not used anymore.
due to the https://jira.bigcommerce.com/browse/PAYPAL-1055
> fix(checkout): PAYPAL-1055 changed expected methodId from przelewy24 to p24 at paypal commerce

- src/payment/create-payment-strategy-registry.ts
- src/payment/strategies/mollie/mollie-initialize-options.ts
- src/payment/strategies/mollie/mollie-payment-strategy.spec.ts
- src/payment/strategies/mollie/mollie-payment-strategy.ts
- src/payment/strategies/mollie/mollie.mock.ts
What? INT-4170
Added hosted fields on verification fields on Mollie. 
Why?
Currently, we have some payment methods that are not using hosted credit card fields for stored instrument verifications (card number and CVV). This presents a security vulnerability as malicious JS can easily scrape credit card information.
> feat(payment): INT-4170 added hosted fields on Mollie verification field

- src/payment/strategies/googlepay/googlepay-payment-strategy.spec.ts
- src/payment/strategies/googlepay/googlepay-payment-strategy.ts
Renew the nonce when the payment fails for GooglePay
If the payment fails we don't renew the nonce so the user used the same nonce to pay and never can pay again until the user delete his order and create a new one with a new nonce.
> fix(payments): Renew the nonce for Google Payment when the payment fails.

- scripts/circleci/copy-previous-releases.sh
Don't copy the `public` folder itself, instead copy its content.
Otherwise we'll end up with the wrong destination path.
Manual (here listing all the files that are copied over as a part of the CircleCI job)
> CHECKOUT-5873: Fix path to copy previous releases from

- src/locale/language-config.ts
- src/locale/language-service.spec.ts
- src/locale/language-service.ts
Specify a locale for default and fallback translations.
At the moment, it is defaulted as `en`. But default translations can be in a language other than English. We can't just default to English because that'd break locale-aware formatting (i.e.: pluralisation)
Unit
> CHECKOUT-5892: Specify locale for default and fallback translations

- src/checkout-buttons/checkout-button-options.ts
- src/checkout-buttons/create-checkout-button-registry.spec.ts
- src/checkout-buttons/create-checkout-button-registry.ts
- src/checkout-buttons/strategies/checkout-button-method-type.ts
- src/checkout-buttons/strategies/googlepay/googlepay-button-strategy.ts
- src/checkout-buttons/strategies/googlepay/googlepay-button.mock.ts
- src/checkout-buttons/strategies/googlepay/googlepay-orbital-button-strategy.spec.ts
- src/customer/create-customer-strategy-registry.ts
- src/customer/customer-request-options.ts
- src/customer/strategies/googlepay/googlepay-customer-mock.ts
- src/customer/strategies/googlepay/googlepay-customer-strategy.ts
- src/customer/strategies/googlepay/googlepay-orbital-customer-strategy.spec.ts
- src/payment/create-payment-strategy-registry.spec.ts
- src/payment/create-payment-strategy-registry.ts
- src/payment/payment-methods.mock.ts
- src/payment/payment-request-options.ts
- src/payment/payment-strategy-type.ts
- src/payment/strategies/googlepay/googlepay-adyenv2-initializer.ts
- src/payment/strategies/googlepay/googlepay-authorizenet-initializer.ts
- src/payment/strategies/googlepay/googlepay-orbital-initializer.spec.ts
- src/payment/strategies/googlepay/googlepay-orbital-initializer.ts
- src/payment/strategies/googlepay/googlepay-payment-strategy.ts
- src/payment/strategies/googlepay/googlepay.mock.ts
- src/payment/strategies/googlepay/googlepay.ts
- src/payment/strategies/googlepay/index.ts
Added Google Pay on Orbital
So that merchants can offer Google Pay as Payment Method using Orbital (CMS) integration
[Checkout-JS 612](https://github.com/bigcommerce/checkout-js/pull/612)
bigcommerce/checkout 
bigcommerce/payments
> feat(payment): INT-4342 added google pay on orbital

- src/payment/strategies/digitalriver/digitalriver-payment-strategy.spec.ts
- src/payment/strategies/digitalriver/digitalriver-payment-strategy.ts
- src/payment/strategies/digitalriver/digitalriver.mock.ts
- src/payment/strategies/digitalriver/digitalriver.ts
I update the payment strategy to support additional actions from BigPay and to call the authenticationSource method from Digital River JS.
Digital River requires to call AuthenticateSource method from the DR.js when a vaulted card is in use, this since it invokes SCA which is PSD2 compliancy
[Demo](https://drive.google.com/file/d/1BDHaRsnnbJk-urR_lP1x1TAuPYdu4i5f/view?usp=sharing)
> INT 4309 Adding support to Vaulted Cards that requires 3DS and 3DS2 in Digital River

- src/payment/strategies/braintree/braintree-hosted-form.spec.ts
- src/payment/strategies/braintree/braintree-hosted-form.ts
1. Validate event.cards length according to [the example](https://braintree.github.io/braintree-web/3.70.0/HostedFields.html#cardTypeChange-examples).
2. Replace `master-card` with `mastercard` in order to get MC logo highlighted.
-- [Braintree's card types](https://braintree.github.io/braintree-web/3.70.0/HostedFields.html#~hostedFieldsCard) vs [checkout supported card types](https://github.com/bigcommerce/checkout-js/blob/a17741168f05d11b6d8e6a773b999dde6bd0a123/src/app/payment/creditCard/CreditCardIconList.tsx#L6)
1. To highlight all logos when the CC field is empty.
2. To support MC logo highlighting.
> fix(payment): INT-4448 Braintree cardTypeChange event

- src/payment/strategies/ppsdk/step-handler/failed.spec.ts
- src/payment/strategies/ppsdk/step-handler/failed.ts
**N.B.** This work is protected behind a WIP feature toggle
- Map PPSDK payments API error responses into the format expected by `RequestError`
- Consistency with current error reporting
- To enable specific translated error messages to be used in `checkout-js`'s current error modal (no changes required to `checkout-js`)
- Extended test
> feat(payment): PAYMENTS-6811 map failure codes to RequestError format

- src/payment/strategies/ppsdk/payment-processors/none-payment-processor.spec.ts
- src/payment/strategies/ppsdk/ppsdk-payment-processor.ts
- Add missing test to the `NonePaymentProcessor`
- Ensures the payments endpoint it called correctly
- Ensures that the result of that result is passed to the `stepHandler`
- Ensures that the `stepHandler`'s result is returned from the processor's `process` method
- New test
> feat(payment): PAYMENTS-6814 add NonePaymentProcessor test

- src/checkout-buttons/strategies/braintree/braintree-paypal-button-options.ts
- src/checkout-buttons/strategies/braintree/braintree-paypal-button-strategy.spec.ts
- src/checkout-buttons/strategies/braintree/braintree-paypal-button-strategy.ts
- src/payment/strategies/paypal/paypal-sdk.ts
Fixed button height for Braintree payment provider
According to task https://jira.bigcommerce.com/browse/PAYPAL-1026
Tested on dev and integration
> fix(payment): PAYPAL-1026 fixed button height

- src/payment/strategies/stripev3/stripev3-payment-strategy.spec.ts
- src/payment/strategies/stripev3/stripev3-payment-strategy.ts
[INT-4087](https://jira.bigcommerce.com/browse/INT-4087)
- Send back the client token to bigpay to update the related payment intent when place a order using a credit card
- Update the payment intent instead to create a new one to prevent to left a incomplete payment intent
> INT-4087 Send the client token back to update the payment intent related for StripeV3

- src/payment/strategies/moneris/moneris-payment-strategy.spec.ts
- src/payment/strategies/moneris/moneris-payment-strategy.ts
https://jira.bigcommerce.com/browse/INT-4141
- Make iframe border and background transparent
Be consistent with the merchant's theme
with changes
without changes
> feat(payment): INT-4141 Make iframe border and background transparent

- src/payment/strategies/paypal-commerce/paypal-commerce-funding-key-resolver.spec.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-funding-key-resolver.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.spec.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-sdk.ts
- src/payment/strategies/paypal-commerce/paypal-commerce.mock.ts
Added Venmo payment method to paypal commerce integration. 
Added shouldRenderFields flag on APM initialization to prevent apm fields render for Venmo. It doesn't need apm fields.
connected PR: https://github.com/bigcommerce/checkout-js/pull/641
Due to the https://jira.bigcommerce.com/browse/PAYPAL-1057
tested manually, units
> feat(checkout): PAYPAL-1057 added Venmo APM to paypal commerce

- src/payment/strategies/afterpay/afterpay-payment-strategy.spec.ts
- src/payment/strategies/afterpay/afterpay-payment-strategy.ts
Get the countryCode from the  shopperCurrency instead from the store country, so Afterpay will redirect to the correct portal
In the current state, Afterpay gets the countryCode from the storeCountry, which causes an error while using multicurrency, if the store was in NZ and the shopper was purchasing in CAD or USD, Afterpay would redirect this merchant to the NZ portal, which is not the intended behavior.
https://drive.google.com/file/d/1lJr5NCaFU4HCipKyg7e6QEkOWwYR_85D/view?usp=sharing
> fix(payment): INT-4661 [Afterpay] get countryCode by shopperCurrency

- src/payment/strategies/digitalriver/digitalriver-payment-strategy.spec.ts
- src/payment/strategies/digitalriver/digitalriver-payment-strategy.ts
added showSavePaymentAgreement dynamically instead of hardcoded on JS then evaluated if It's true on SDK
It's a bug that could affect future DigitalRiver users
https://github.com/bigcommerce/checkout-js/pull/632
> fix(payment): INT-4598 handle vaulting Enable checkbox

- src/hosted-form/hosted-form-options.ts
- src/hosted-form/index.ts
- src/payment/create-payment-strategy-registry.ts
- src/payment/instrument/supported-payment-instruments.ts
- src/payment/payment-methods.mock.ts
- src/payment/strategies/moneris/moneris-payment-initialize-options.ts
- src/payment/strategies/moneris/moneris-payment-strategy.spec.ts
- src/payment/strategies/moneris/moneris-payment-strategy.ts
- src/payment/strategies/moneris/moneris.mock.ts
Update strategy to support vaulted instruments and add Moneris to supported instruments.
So vaulted instruments can be used with Moneris.
UInit Testing
> feat(payment): INT-4222 Add vaulting compatibility to Moneris

- src/checkout-buttons/create-checkout-button-registry.ts
create-checkout-button-registry.ts fixed to reference the correct Orbital initializer.
GooglePay in Orbital was not sending the proper google pay token due to a wrong reference.
Ping @bigcommerce/checkout  @bigcommerce/payments @bigcommerce/apex-integrations
> fix(payment): INT-4685 Orbital initializer added properly

- src/payment/strategies/googlepay/googlepay-get-first-and-last-name.spec.ts
- src/payment/strategies/googlepay/googlepay-get-first-and-last-name.ts
- src/payment/strategies/googlepay/googlepay-payment-processor.spec.ts
- src/payment/strategies/googlepay/googlepay-payment-processor.ts
Changes the way to get the first name
When the credit/debit card hasn't the last name the error was happening
**Before:** https://drive.google.com/file/d/1seY1J_tMoYWe6PA7AQYjZxiUu7bg44GA/view?usp=sharing
**After:** https://drive.google.com/file/d/1jiB8BW8eUM_20wDmuQ8KAPCGyw4ADMKX/view?usp=sharing
> fix(payment): INT-4481 GooglePay: Fix issue when attempting to pay without a last name provided in the billing address

- src/payment/strategies/stripev3/stripev3-payment-strategy.spec.ts
- src/payment/strategies/stripev3/stripev3-payment-strategy.ts
- src/payment/strategies/stripev3/stripev3.ts
Throws stripe error when user closes the auth modal on Stripe V3
Sentry reported a lot number of errors at checkout using Stripe V3.  “_We are unable to authenticate your payment method. Please choose a different payment method and try again._” [CHECKOUT-JS-4AG](https://sentry.io/organizations/bigcommerce/issues/2392691077/?referrer=jira_integration)
This error is caused by some authentication failure in 3Ds or because the user canceled the purchase. 
This PR handles the cancellation exception separately from the one generated by authentication failure. 
- [Video](https://drive.google.com/file/d/1BDiUc-AxKf4Jyq2hf-fMayzCRFSrVVWc/view?usp=sharing)
> fix(provider): INT-4480 Throws stripe error when user closes the auth modal on Stripe V3

- src/payment/payment-methods.mock.ts
- src/payment/strategies/quadpay/quadpay-payment-strategy.spec.ts
- src/payment/strategies/quadpay/quadpay-payment-strategy.ts
Refactor in the `quadpay-payment-strategy` to get the `redirect_url `from the `initializePayment` instead of the `additional_action_required.data` response.
to avoid getting the `uri` data from the get calls because the endpoint will not longer send the `uri` data 
ticket:
[INT-4584](https://jira.bigcommerce.com/browse/INT-4584)
[Video](https://drive.google.com/file/d/10V1UoQlnsgGCSyk8Md6hQyNDEud9yGXi/view?usp=sharing)
https://github.com/bigcommerce/bigcommerce/pull/42068
[bigpay: INT-4584](https://github.com/bigcommerce/bigpay/pull/4097)
> feat(payment): INT-4584 - Refactor Quadpay uri data for redirect

- src/payment/strategies/digitalriver/digitalriver-payment-initialize-options.ts
updated Digital River documentation
As a Third-party developer, I want to be able to use the Checkout SDK within the context of Digital River so that I can build my own checkout and understand how Digital River payment integration will work.
> fix(payment): INT-4438 update SDK documentation for Digital River

- src/payment/strategies/bolt/bolt-payment-strategy.spec.ts
- src/payment/strategies/bolt/bolt-payment-strategy.ts
- src/payment/strategies/bolt/bolt-script-loader.ts
- src/payment/strategies/bolt/bolt.mock.ts
- src/payment/strategies/bolt/bolt.ts
Updated executeBoltFullCheckout method for Bolt payment strategy.
From current implementation the fact that an order is created after the Bolt Payment happens in some cases (issue on Bolt side or slow connection) cause of the issues with orphan orders on Bolt side. For minimising this issues we some changes to executeBoltFullCheckout method more useful and Bolt will send us transaction reference. When Bolt creates transaction reference the are understand that we have an order created and I they will have some troubles on their side, we will throw an error to let user know, that something went wrong.
All unit tests passed locally:
> feat(payment): BOLT-30 updated finalize method for Bolt payment strategy

- src/analytics/analytics-step-tracker.spec.ts
- src/analytics/analytics-step-tracker.ts
- src/analytics/analytics-tracker-ga.spec.ts
- src/analytics/analytics-tracker-ga.ts
- src/analytics/analytics-tracker-window.ts
Fix bug with Segment + GAEE.
When the experiment `DATA-6891.missing_orders_within_GA` is ON there are issues with data being sent to Google Analytics when a merchant is using Segment.com to setup Google Analytics.
Manually / Unit tests 
1) 34 items in the Cart, $850 total
2) now we send large orders in a transaction mode (each line_item per request)
3) proof from Google Analytics
> fix(analytics): DATA-7883 Fix Segment + GAEE issue

- src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-strategy.spec.ts
- src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-strategy.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.spec.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-sdk.ts
Added paylater to enable-funding field on paypalcommerce checkout and buttons
Due to https://jira.bigcommerce.com/browse/PAYPAL-1100
Previously Paylater didn't work outside US
Units, manually
> feat(checkout): PAYPAL-1100 added paylater to enable-funding field on paypalcommerce checkout and buttons

- src/payment/strategies/braintree/braintree-payment-options.ts
- src/payment/strategies/braintree/braintree-regular-field.ts
Adding optional field "accessibilityLabel" to BraintreeFormField Options and setting aria-label attribute on card name input.
Currently Braintree does not make use of the accessibility label made available [here](https://github.com/bigcommerce/checkout-js/pull/512)
This means that currently users relying on screen readers to checkout have a hard time understanding what part of the credit card form they are currently in.
Before:
After:
> feat(payment): CHECKOUT-5906 Payment step "Name on Card" of checkout requires label for screen readers

- src/payment/strategies/ppsdk/payment-processors/none-payment-processor.spec.ts
- src/payment/strategies/ppsdk/payment-processors/none-payment-processor.ts
- src/payment/strategies/ppsdk/ppsdk-payment-resumer.spec.ts
- src/payment/strategies/ppsdk/ppsdk-payment-resumer.ts
**N.B.** The PPSDK is behind a work in progress feature toggle
- Disable `withCredentials` setting when posting/getting to the BigPay payments endpoints
- Cookies are not required
- The default value of `true` conflicts with the `Access-Control-Allow-Origin` value of `*` returned by BigPay, creating a CORS issues
- Passing tests
> fix(payment): disable withCredentials on PPSDK xhr requests to BigPay

- README.md
Updates to the the README file in the Checkout JS SDK:
- Point to the Checkout JS rep as the reference implementation.
- Add links to updated dev documentation in the "Getting started" section
Developers were getting the impression that the legacy sample app which was never intended to be used in production (https://github.com/bigcommerce/checkout-sdk-js-example) is the reference implementation.
...
> docs(common): CHECKOUT-5976 Updated Checkout SDK repo: Checkout JS should be the reference implementation

- src/order/errors/index.ts
- src/order/errors/order-finalization-not-completed-error.spec.ts
- src/order/errors/order-finalization-not-completed-error.ts
- src/payment/create-payment-strategy-registry.ts
- src/payment/strategies/afterpay/afterpay-payment-strategy.spec.ts
- src/payment/strategies/afterpay/afterpay-payment-strategy.ts
- src/remote-checkout/remote-checkout-request-sender.spec.ts
- src/remote-checkout/remote-checkout-request-sender.ts
Add a new error type, **OrderFinalizationNotCompletedError** and modify the Afterpay strategy to catch any errors during the order finalization, within the **finalize** method, and reject the promise with an OrderFinalizationNotCompletedError.
Add support for the **forgetProvider** endpoint, and use it to forget the remote checkout provider which is applied when shoppers initialize a purchase by using an offsite provider.
Modify the Afterpay strategy to apply the necessary changes to fix the issue: catch the error from the order completion, forget the provider and refresh the state with all the supported payment methods.
Currently if we get an error after calling the **finalize** method in the strategy and the error is other than **OrderFinalizationNotRequiredError** then shoppers see a …
> fix(payment): INT-4672 Allow shoppers to change payment method when order finalization fails

- src/payment/payment-methods.mock.ts
- src/payment/strategies/ppsdk/initialization-strategies/none.ts
**N.B.** The PPSDK is behind a work in progress feature toggle
- Fix casing of expected PPSDK initialisation strategy value from BE
- BE will be sending lowercase rather than all caps
- Passing tests
> fix(payment): PAYMENTS-7214 fix PPSDK initialisation strategy casing

- src/payment/strategies/moneris/moneris-payment-strategy.spec.ts
- src/payment/strategies/moneris/moneris-payment-strategy.ts
- src/payment/strategies/moneris/moneris.ts
-  Improve look and feel injecting CSS to the iframe
- The Moneris iframe only allows inject CSS in the iframe creation
https://developer.moneris.com/Documentation/NA/E-Commerce%20Solutions/Hosted%20Solutions/Hosted%20Tokenization
New 
Old
> feat(payment): INT-4141 Improve css look and feel

- src/payment/strategies/ppsdk/payment-processors/none-payment-processor.spec.ts
- src/payment/strategies/ppsdk/payment-processors/none-payment-processor.ts
- src/payment/strategies/ppsdk/ppsdk-payment-processor.ts
- src/payment/strategies/ppsdk/ppsdk-payment-resumer.spec.ts
- src/payment/strategies/ppsdk/ppsdk-payment-resumer.ts
- src/payment/strategies/ppsdk/ppsdk-strategy.spec.ts
- src/payment/strategies/ppsdk/ppsdk-strategy.ts
**N.B.** The PPSDK is behind a work in progress feature toggle
- For PPSDK requests to the BigPay `/payments` endpoint: 
- Add `AUTHORIZATION` header populated by the order token
- Null out `X-XSRF-TOKEN` header (as not to have its value set by default: https://github.com/bigcommerce/request-sender-js/pull/27)
- BigPay need the `AUTHORIZATION` JWT value to work with the order
- The endpoint is not designed to use `X-XSRF-TOKEN` value, so its default inclusion is unnecessary and potentially misleading
- Updated tests
> fix(payment): PAYMENTS-7221 fix the PPSDK BigPay Payments request headers

- src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-strategy.spec.ts
- src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-strategy.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-funding-key-resolver.spec.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-funding-key-resolver.ts
- src/payment/strategies/paypal-commerce/paypal-commerce-sdk.ts
- src/payment/strategies/paypal-commerce/paypal-commerce.mock.ts
1) Added SEPA apm to paypalcommerce.
2) Implemented explicit passing of APMs to enable and disable fundings for Paypalcommerce button integration.
Thats is needed for showing smart buttons only for activated APMs and PayLater(Credit).
Due to the https://jira.bigcommerce.com/browse/PAYPAL-1111
Tested manually/units
This screenshot  shows that checkout passing explicitly enabled/disabled APMs and credit/paylater to disable/enable-funding params on paypal initialization.
> feat(checkout): PAYPAL-1111 Added APM check to paypalcommerce button integration and integrated SEPA

- src/payment/create-payment-strategy-registry.ts
- src/payment/strategies/adyenv2/adyenv2-payment-strategy.spec.ts
- src/payment/strategies/adyenv2/adyenv2-payment-strategy.ts
Fixed Adyen checkout form localization
Due to the [ADYEN-231](https://jira.bigcommerce.com/browse/ADYEN-231)
> fix(checkout): ADYEN-231 fixed adyen checkout form localization

- src/customer/strategies/bolt/bolt-customer-strategy.spec.ts
- src/customer/strategies/bolt/bolt-customer-strategy.ts
- src/payment/payment.ts
- src/payment/strategies/bolt/bolt-payment-initialize-options.ts
- src/payment/strategies/bolt/bolt-payment-strategy.spec.ts
- src/payment/strategies/bolt/bolt-payment-strategy.ts
- src/payment/strategies/bolt/bolt-script-loader.spec.ts
- src/payment/strategies/bolt/bolt-script-loader.ts
- src/payment/strategies/bolt/bolt.mock.ts
- src/payment/strategies/bolt/bolt.ts
Added Bolt embedded fields implementation into Bolt payment strategy.
Because of the task: https://jira.bigcommerce.com/browse/BOLT-23
Here is test result:
> feat(payment): BOLT-23 embedded Bolt payment method

- src/payment/strategies/clearpay/clearpay-payment-strategy.spec.ts
- src/payment/strategies/clearpay/clearpay-payment-strategy.ts
Display the correct error message when trying to purchase with Clearpay and the amount is outside the limits provided by Afterpay (due to a Coupon code)
When the amount is outside limits Clearpay will respond with an error code when trying to fetch the client Token for the transaction, we are catching that error to display a custom error message
Unit test
Video https://drive.google.com/file/d/15jMDT0uv4SsSrSgy62sfKWRMKyJt4lLb/view?usp=sharing
BCAPP
[#42128](https://github.com/bigcommerce/bigcommerce/pull/42128)
Revert this PR
@bigcommerce/apex-integrations
> fix(payment): INT-4705 [Clearpay] display correct error message when amount is out of limits

- src/payment/strategies/ppsdk/payment-processors/none-payment-processor.spec.ts
- src/payment/strategies/ppsdk/payment-processors/none-payment-processor.ts
- src/payment/strategies/ppsdk/ppsdk-payment-processor.ts
- src/payment/strategies/ppsdk/ppsdk-strategy.ts
**N.B. this work is protected by a WIP feature toggle**
- Transparently pass on `methodId` to PPSDK, rather than constructing it out of `${paymentMethod.id}.${paymentMethod.method}`
- The BE is now sending the id value in the `this.that` format, so the client no longer needs to assemble it
- Passing unit tests
- Manual test of WIP PPSDK functionality 
> fix(payment): PAYMENTS-7252 pass methodIds on to PPSDK endpoint without transformation

- src/payment/strategies/braintree/braintree-script-loader.spec.ts
- src/payment/strategies/braintree/braintree-script-loader.ts
Update Braintree web SDK version
According to task https://jira.bigcommerce.com/browse/PAYPAL-954
...Tested on Dev and Int
> feat(payment): PAYPAL-954 Update Braintree web SDK version

- src/payment/strategies/ppsdk/payment-processors/none-payment-processor.spec.ts
- src/payment/strategies/ppsdk/payment-processors/none-payment-processor.ts
- src/payment/strategies/ppsdk/ppsdk-payment-processor.ts
- src/payment/strategies/ppsdk/ppsdk-strategy.ts
Reverts bigcommerce/checkout-sdk-js#1233
**N.B.** this work is behind a WIP PPSDK feature toggle 
Unfortunately, the Payment Method ID is awkwardly renamed, rebuilt and deconstructed throughout many different code bases and APIs. 
As such, standardising it is a much bigger task than anticipated. For now the BE requires the FE to construct the PPSDK notion of Payment ID manually (as before this reverted PR).
> Revert "fix(payment): PAYMENTS-7252 pass methodIds on to PPSDK endpoint without transformation"

- src/payment/create-payment-strategy-registry.ts
- src/payment/strategies/clearpay/clearpay-payment-strategy.spec.ts
- src/payment/strategies/clearpay/clearpay-payment-strategy.ts
Modify the Clearpay strategy to apply the necessary changes to fix the issue: catch the error from the order completion, forget the provider, and refresh the state with all the supported payment methods.
Related to https://github.com/bigcommerce/checkout-sdk-js/pull/1192
By applying these changes we can make the checkout-sdk catch the error and refresh the payment method lists to allow shoppers to select another payment method.
https://drive.google.com/file/d/1HK7VFfw1mTwT-NV4ieohCMfvsTVX7KBd/view?usp=sharing
> fix(payment): INT-4810 Forget checkout provider and reload payment methods - Clearpay

- src/customer/strategies/bolt/bolt-customer-strategy.ts
- src/order/order-request-body.ts
- src/payment/index.ts
- src/payment/payment.ts
- src/payment/strategies/bolt/bolt-payment-initialize-options.ts
- src/payment/strategies/bolt/bolt-payment-strategy.spec.ts
- src/payment/strategies/bolt/bolt-payment-strategy.ts
- src/payment/strategies/bolt/bolt.ts
- src/payment/strategies/braintree/braintree-paypal-payment-strategy.ts
- src/payment/with-account-creation.ts
Added account creation flag to Bolt Embedded One Click execution payment payload.
Because of the task: https://jira.bigcommerce.com/browse/BOLT-24
Unit tests
Manual test
Here is a screenshot of the checkbox:
checkout-js: https://github.com/bigcommerce/checkout-js/pull/690
> feat(payment): BOLT-24 added account creation flag for Bolt Embedded One Click execution

- src/payment/strategies/moneris/moneris-payment-strategy.spec.ts
- src/payment/strategies/moneris/moneris-payment-strategy.ts
[INT-4802](https://jira.bigcommerce.com/browse/INT-4802)
Validate if the response is formatted as expected 
The handler can be triggered before the response is send by Moneris 
> fix(payment): INT-4802 Moneris Validate response before resolve

- src/customer/create-customer-strategy-registry.ts
- src/customer/strategies/amazon-pay-v2/amazon-pay-v2-customer-strategy.spec.ts
- src/customer/strategies/amazon/amazon-pay-customer-strategy.spec.ts
- src/customer/strategies/braintree/braintree-visacheckout-customer-strategy.spec.ts
- src/customer/strategies/chasepay/chasepay-customer-strategy.spec.ts
- src/customer/strategies/googlepay/googlepay-adyenv2-customer-strategy.spec.ts
- src/customer/strategies/googlepay/googlepay-authorizenet-customer-strategy.spec.ts
- src/customer/strategies/googlepay/googlepay-braintree-customer-strategy.spec.ts
- src/customer/strategies/googlepay/googlepay-checkoutcom-customer-strategy.spec.ts
- src/customer/strategies/googlepay/googlepay-customer-strategy.ts
- src/customer/strategies/googlepay/googlepay-cybersourcev2-customer-strategy.spec.ts
- src/customer/strategies/googlepay/googlepay-orbital-customer-strategy.spec.ts
- src/customer/strategies/googlepay/googlepay-stripe-customer-strategy.spec.ts
- src/customer/strategies/masterpass/masterpass-customer-strategy.spec.ts
- src/customer/strategies/square/square-customer-strategy.spec.ts
- src/payment/create-payment-strategy-registry.ts
- src/payment/strategies/amazon-pay/amazon-pay-payment-strategy.spec.ts
- src/payment/strategies/klarna/klarna-payment-strategy.spec.ts
- src/payment/strategies/klarnav2/klarnav2-payment-strategy.spec.ts
- src/payment/strategies/quadpay/quadpay-payment-strategy.spec.ts
- src/payment/strategies/zip/zip-payment-strategy.spec.ts
- src/remote-checkout/remote-checkout-action-creator.spec.ts
- src/remote-checkout/remote-checkout-action-creator.ts
- src/remote-checkout/remote-checkout-actions.ts
- src/shipping/create-shipping-strategy-registry.ts
- src/shipping/strategies/amazon/amazon-pay-shipping-strategy.spec.ts
Using the forgetCheckout action instead of the signOut action when clicking sign out on Google Pay
Using the signOut action was deleting all the checkout data
After signing out
> fix(payment): INT-4674 Using  forgetCheckout instead of signOut on Google Pay

- src/payment/strategies/googlepay/googlepay-payment-processor.ts
Reverts bigcommerce/checkout-sdk-js#1244
is causing [INT-4900](https://jira.bigcommerce.com/browse/INT-4900)
> Revert "fix(checkout): ADYEN-260 fixed googlepay updates billing info by removing customer email update"

- src/payment/create-payment-strategy-registry.ts
- src/payment/payment-methods.mock.ts
- src/payment/strategies/stripev3/stripev3-initialize-options.ts
- src/payment/strategies/stripev3/stripev3-payment-strategy.spec.ts
- src/payment/strategies/stripev3/stripev3-payment-strategy.ts
- src/payment/strategies/stripev3/stripev3.mock.ts
Added hosted fields on verification fields on StripeV3
Currently, we have some payment methods that are not using hosted credit card fields for stored instrument verifications (card number and CVV). This presents a security vulnerability as malicious JS can easily scrape credit card information.
[Checkout #637](https://github.com/bigcommerce/checkout-js/pull/637)
- Manual
- Unit
https://www.loom.com/share/3cdac217e2b14282a3e7af6373e5ee01
@bigcommerce/apex-integrations @bigcommerce/checkout
> feat(payment): INT-4170 added hosted fields on verification fields

- src/payment/create-payment-strategy-registry.ts
- src/payment/strategies/braintree/braintree.ts
- src/payment/strategies/googlepay/googlepay-payment-strategy.spec.ts
- src/payment/strategies/googlepay/googlepay-payment-strategy.ts
- src/payment/strategies/googlepay/googlepay.ts
Added threeDSecure check for googlepaybraintree
According to task https://jira.bigcommerce.com/browse/PAYPAL-972
> feat(payment): PAYPAL-972 added threeDSecure check for googlepaybraintree

- src/payment/instrument/supported-payment-instruments.ts
- src/payment/payment-strategy-registry.ts
Add alias mapping for credit_card as card
Because method will change name from credit_card to card on Bigpay, both names will be keep to be able to merge without issues
[Demo](https://drive.google.com/file/d/1EmTIw2wTqmYpYERm_a4GIWqjivYbNlt6/view?usp=sharing)
https://github.com/bigcommerce/checkout-js/pull/656
https://github.com/bigcommerce/bigpay/pull/4109
> fix(payment): INT-4489 cko add supported method 'card'

- src/payment/payment-methods.mock.ts
- src/payment/strategies/stripev3/stripev3-payment-strategy.spec.ts
- src/payment/strategies/stripev3/stripev3-payment-strategy.ts
[INT-4087](https://jira.bigcommerce.com/browse/INT-4087)
- Catch exception when try to  execute the handle card action to execute the confirm card peyment when 3ds auth is required on stripev3
To prevent duplicate payment intent entries, we reuse the payment intent created on the initialization step and update its data and confirm on the backend.
When use a 3ds card the response of that confirmation tell us that need a 3ds auth and send that action to the front  where we use the  handleCardAction to process it, but it will try a exception with the its message say that use confirmCardPayment  instead.
This is the two case that covers this changes:
1.- With new payment Intent: 
- Use handleCardAction to resolve 3ds
- Send to the back confirm=true
2.- With payment intent udpated and …
> fix(payment): INT-4087 Catch stripe exception to process 3ds when payment intent is updated on the backend - StripeV3

- src/payment/strategies/ppsdk/payment-processors/none-payment-processor.spec.ts
- src/payment/strategies/ppsdk/payment-processors/none-payment-processor.ts
- src/payment/strategies/ppsdk/ppsdk-payment-processor.ts
- src/payment/strategies/ppsdk/ppsdk-strategy.ts
Reverts bigcommerce/checkout-sdk-js#1238
Reverting a revert 😄 
We have decided to bite the bullet and to standardise PPSDK Payment Method IDs from the BE.
After some investigation, it seems to be the lesser evil compared to trying to manage its construction in the view.
**N.B. this work is protected by a WIP feature toggle**
- Transparently pass on `methodId` to PPSDK, rather than constructing it out of `${paymentMethod.id}.${paymentMethod.method}`
- The BE is now sending the id value in the `this.that` format, so the client no longer needs to assemble it
- Passing unit tests
- Manual test of WIP PPSDK functionality 
> Revert "Revert "fix(payment): PAYMENTS-7252 pass methodIds on to PPSDK endpoint without transformation""

- src/checkout-buttons/strategies/braintree/braintree-paypal-button-options.ts
- src/checkout-buttons/strategies/braintree/braintree-paypal-button-strategy.ts
- src/payment/strategies/braintree/braintree-sdk-creator.ts
- src/payment/strategies/braintree/braintree.ts
- src/payment/strategies/paypal/paypal-express-payment-strategy.spec.ts
- src/payment/strategies/paypal/paypal-sdk.ts
- src/payment/strategies/paypal/paypal.mock.ts
Added pay later messaging on cart
According to task https://jira.bigcommerce.com/browse/PAYPAL-1103
> feat(payment): PAYPAL-1103 added pay later messaging on cart

- src/payment/strategies/googlepay/googlepay-payment-processor.ts
Fixed googlepay updates billing info, removed update of customer email.
If customer is doing payment via googlepay cart button, system will pass googlepay email as customer email.
Changes ware made after this issue https://jira.bigcommerce.com/browse/INT-4900 and after revert of the previous PR related to the ADYEN-260
Due to the https://jira.bigcommerce.com/browse/ADYEN-260
https://user-images.githubusercontent.com/79574476/135050738-d1ce6282-bec2-4413-bb16-378cfd46bb8c.mov
https://user-images.githubusercontent.com/79574476/135050753-43a4a90e-e812-4a66-8d91-6f3dd54c1ec2.mov
> fix(checkout): ADYEN-260 fixed googlepay updates billing info, removed update of customer email

- src/payment/strategies/ppsdk/ppsdk-strategy.spec.ts
- src/payment/strategies/ppsdk/ppsdk-strategy.ts
**N.B** this PPSDK work is behind a WIP feature toggle
- Resolve PPSDK strategy finalization method when the current order is already completed
- `finalize` is invoked when checkout finds loads an order with an existing order payment. In the case that the order is already complete (i.e. payment has been successfully authorised in full offsite) we can skip reaching out to BigPay and honour the order's status of completed. 
- Unit
> feat(payment): PAYMENTS-7270 skip PPSDK finalization when order is marked complete

- .circleci/config.yml
Update node image in circle
There was an issue building the container and it was recommended that we update the node version to 10-buster.
- Circle
> chore(common): Update node image in circle CI

- src/payment/strategies/ppsdk/ppsdk-payment-resumer.spec.ts
- src/payment/strategies/ppsdk/ppsdk-payment-resumer.ts
- src/payment/strategies/ppsdk/ppsdk-strategy.spec.ts
- src/payment/strategies/ppsdk/ppsdk-strategy.ts
**N.B.** this PPSDK work is behind a WIP feature flag
- Make use of the new `/api/storefront/payments/auth-token` (https://github.com/bigcommerce/bigcommerce/pull/42774) endpoint within the PPSDK strategy's `finalize` method
- To allow the strategy to resume authenticated communication over the BigPay `/payments` endpoint
- Manual
- Unit
> feat(payment): PAYMENTS-7269 allow PPSDK payment methods to finalise in progress payments

- src/payment/strategies/ppsdk/ppsdk-payment-resumer.spec.ts
- src/payment/strategies/ppsdk/ppsdk-payment-resumer.ts
- src/payment/strategies/ppsdk/ppsdk-strategy.spec.ts
- src/payment/strategies/ppsdk/ppsdk-strategy.ts
Reverts bigcommerce/checkout-sdk-js#1252
PR cause build error due to accidental redeclaration of block-scoped variable.
Will rebase and add minor refactor to avoid this.
> Revert "feat(payment): PAYMENTS-7269 allow PPSDK payment methods to finalise in progress payments"

- src/payment/strategies/googlepay/googlepay-payment-strategy.ts
Disabled showing error modal on Adyen GooglePay 3ds.
I fond out that after refactoring checkout started to show modal [on this line in PR](https://github.com/bigcommerce/checkout-sdk-js/pull/1082/files#diff-ffa8fb97c784b953d53f6ae3923e8869b16c410016854e84f3fd4dd0c6e153b7R112)
I've made changes to return to the previous version at that line.
Due to the https://jira.bigcommerce.com/browse/ADYEN-253
**Before:**
https://user-images.githubusercontent.com/79574476/135474660-f61f6843-b3c0-4841-b572-627a04c521db.mov
**After:**
https://user-images.githubusercontent.com/79574476/135474728-63f097a6-1946-4a9d-be30-fe01c0f8560a.mov
> fix(payment): ADYEN-253 Disabled showing error modal on Adyen GooglePay 3ds

- README.md
- fixes incorrect README instructions for getSelectedShippingOption
- These docs misled me, so let's fix it!
> docs(shipping): fixes incorrect README instructions for getSelectedShippingOption

- src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-strategy.spec.ts
- src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-strategy.ts
- src/shipping/strategies/amazon-pay-v2/amazon-pay-v2-shipping-strategy.spec.ts
- src/shipping/strategies/amazon-pay-v2/amazon-pay-v2-shipping-strategy.ts
[INT-4231](https://jira.bigcommerce.com/browse/INT-4231)
I changed payment strategy to reject the promise that triggers the spinner in amazonpay payment step.
Amazonpay team changed US region script to open a modal instead of performing a full redirect to their hosted page, this causes an infinite spinner running if shopper closes the modal.
The change covers US considering that is the only region using the modal, for the other regions (UK and EU) we will keep the same functionality as before.
Demo issue to resolve:
https://drive.google.com/file/d/1nXrKE0YsvSFxsxjHED1CyFZSnE6vJC-q/view?usp=sharing
Demo US:
https://drive.google.com/file/d/1L8pXznmXBrfPZ6dTz91CWqSNij6O7HpY/view?usp=sharing
Demo UK:
https://drive.google.com/file/d/1Onur_lY6gkVD0oxFzWMbZ919c3XmnL9O/view?usp=sharing
Demo EU: …
> feat(payment): INT-4231 deleting spinner functionality in amazonpay

- src/checkout/checkout-service.spec.ts
- src/global.d.ts
- src/payment/payment-method-action-creator.spec.ts
- src/payment/payment-method-action-creator.ts
- src/payment/payment-methods.mock.ts
- src/payment/strategies/apple-pay/index.ts
- src/payment/strategies/apple-pay/is-apple-pay-window.ts
Filter apple pay based on the brower
Since applepay only works in safari, therefore filter apple pay from the list of payment methods that are sent to checkout if the browser used is not safari.
- Update the interface of `ApplePaySession` on window object as per what is defined by apple.
- There is more filtering of payment methods that is done in checkout-js, move that logic slowly to SDK as well
- Unit tests
- Screenshot
> feat(payment): CHECKOUT-6067 Filter applepay based on browser

- src/payment/create-payment-strategy-registry.ts
- src/payment/strategies/ppsdk/ppsdk-completed-payments.spec.ts
- src/payment/strategies/ppsdk/ppsdk-completed-payments.ts
- src/payment/strategies/ppsdk/ppsdk-strategy.spec.ts
- src/payment/strategies/ppsdk/ppsdk-strategy.ts
- When trying to resume a PPSDK payment which has failed or errored: re-throw the original error once, then fallback to throwing only `OrderFinalizationNotRequiredError` if repeated
- The 'repeated' nature is deduced by storing payment IDs which have resulting in errors or failure in local storage (via the `BrowserStorage` class)
- To consider the consumer 'notified' with the first error thrown
- In practice (with `checkout-js`) this leads to only one error modal being displayed (rather than the same one over and over with refreshes or repeated attempts to finalise the payment)
- Updated tests
> fix(payment): PAYMENTS-7408 suppress repeated thrown errors when resuming a PPSDK payment

- src/payment/create-payment-strategy-registry.spec.ts
- src/payment/create-payment-strategy-registry.ts
- src/payment/payment-methods.mock.ts
- src/payment/payment-strategy-type.ts
- src/payment/strategies/opy/index.ts
- src/payment/strategies/opy/opy-payment-strategy.spec.ts
- src/payment/strategies/opy/opy-payment-strategy.ts
- src/payment/strategies/opy/opy.ts
Create an **Openpay** payment strategy and make it available at checkout.
A new payment strategy is required to support **Openpay**.
Watch the video [>>here<<](https://drive.google.com/file/d/1gW1DynaEpqWtI72pKFTEcu-r-qoxKVbh/view?usp=sharing)
👉 https://github.com/bigcommerce/checkout-js/pull/692
👉 https://github.com/bigcommerce/bigcommerce/pull/43424 to load the Openpay page ➡️
👉 https://github.com/bigcommerce/bigpay/pull/4495 to purchase 🤑
👉 https://github.com/bigcommerce/bigcommerce/pull/43457 to go back to the confirmation page ↩️
> feat(payment): INT-4646 Add Openpay payment strategy

- src/payment/strategies/ppsdk/ppsdk-strategy.spec.ts
- src/payment/strategies/ppsdk/ppsdk-strategy.ts
- src/payment/strategies/ppsdk/ppsdk-sub-strategy.ts
- src/payment/strategies/ppsdk/sub-strategies/none-sub-strategy.spec.ts
- src/payment/strategies/ppsdk/sub-strategies/none-sub-strategy.ts
- rename PPSDK subStrategy method from `process` to `execute`
- to better replicate current strategy method naming conventions
- (will be joined by `deinitialise` in a future commit, furthering similarities)
- Passing tests
> chore(payment): PAYMENTS-7402 rename PPSDK subStrategy method from process to execute

- src/payment/create-payment-strategy-registry.spec.ts
- src/payment/create-payment-strategy-registry.ts
- src/payment/payment-methods.mock.ts
- src/payment/payment-strategy-type.ts
- src/payment/strategies/humm/humm-payment-strategy.spec.ts
- src/payment/strategies/humm/humm-payment-strategy.ts
- src/payment/strategies/humm/index.ts
Adding humm payment in the registry as external payment
it's required to support humm
> feat(payment): INT-4897 Humm - Add Humm strategy as external payment

- src/payment/strategies/apple-pay/apple-pay-payment-strategy.ts
RemoveZero Width Space (U+200B) characters added in apple pay strategy
Remove Zero Width Space (U+200B) characters added in apple pay strategy, by the editor
- Tests
@bigcommerce/checkout @bigcommerce/payments @TomA-R
> fix(payment): CHECKOUT-6066 Remove Zero Width Space (U+200B) characters

- src/payment/strategies/adyenv2/adyenv2-payment-strategy.ts
Made reseting adyen component state on deinitialize
Due to the fix of https://jira.bigcommerce.com/browse/ADYEN-320
https://user-images.githubusercontent.com/79574476/143884017-3b7d56ae-7c99-4f40-a74d-3084a8ed8364.mov
> fix(checkout): ADYEN-320 reset adyen component state on deinitialize

- src/payment/strategies/digitalriver/digitalriver-error.spec.ts
- src/payment/strategies/digitalriver/digitalriver-error.ts
- src/payment/strategies/digitalriver/digitalriver-payment-strategy.spec.ts
- src/payment/strategies/digitalriver/digitalriver-payment-strategy.ts
[INT-5000](https://jira.bigcommerce.com/browse/INT-5000)
I added a validation when the payment method isn't available to explain the shopper what is happening, instead of do nothing
Digital River requested it because the shopper doesn't know what happened if the drop in element isn't rendered
https://github.com/bigcommerce/checkout-js/pull/748
> feat(payment): INT-5000 Throw error when payment method isn't available

- src/payment/strategies/bolt/bolt-error.spec.ts
- src/payment/strategies/bolt/bolt-error.ts
- src/payment/strategies/bolt/bolt-payment-strategy.ts
Add validation errors mapping for Bolt embedded fields
Because of task: [https://jira.bigcommerce.com/browse/BOLT-100](https://jira.bigcommerce.com/browse/BOLT-100)
Before:
After:
German:
Ihre Kartendaten konnten nicht verifiziert werden. Bitte überprüfen Sie Ihre Angaben noch einmal ganz genau und versuchen Sie es erneut. -- Your card details could not be verified. Please double-check your details carefully and try again.
French:
Impossible de confirmer les informations de votre carte. Veuillez les vérifier à nouveau et réessayer. -- Unable to confirm your card information. Please check them again and try again.
Tests:
> feat(payment): BOLT-100 add error mesages for Bolt fields

- src/payment/strategies/bolt/bolt-payment-strategy.spec.ts
- src/payment/strategies/bolt/bolt-payment-strategy.ts
- src/payment/strategies/bolt/bolt.mock.ts
Added extra check for transaction reference what comes from Bolt for safety
To prevent the issue when we get empty transaction reference and passing it to nonce payment object before submit.
Due the task: https://jira.bigcommerce.com/browse/BOLT-109
Manual tests
Unit tests
Screen recording: 
https://user-images.githubusercontent.com/25133454/145768738-e91f25a7-60eb-4eb4-8639-187875281d87.mov
Screenshot of the error:
> feat(payment): BOLT-109 added extra check for transaction reference what comes from Bolt

- src/payment/create-payment-strategy-registry.ts
- src/payment/errors/index.ts
- src/payment/errors/payment-execute-error.spec.ts
- src/payment/errors/payment-execute-error.ts
- src/payment/strategies/humm/humm-payment-strategy.spec.ts
- src/payment/strategies/humm/humm-payment-strategy.ts
Retrieve additional data related to the method before start processing the payment
We need the processable value to be able to start the payment process, it will be determined by some configuration set by the merchant in the settings page
ping @bigcommerce/apex-integrations @bigcommerce/payments
> feat(payment): INT-4893 Retrieve initialization data from Humm

- src/payment/instrument/supported-payment-instruments.ts
Set cko card method mapping to card instead of credit_card
BigPay will now vault it, as card, so its required so storefront shows correctly the stored instrument
none
[BigPay](https://github.com/bigcommerce/bigpay/pull/4641)
> fix(payment): INT-5166 CKO mapping for vaulted instrument

- src/order/errors/index.ts
- src/order/errors/order-tax-provider-unavailable-error.spec.ts
- src/order/errors/order-tax-provider-unavailable-error.ts
- src/order/order-request-sender.spec.ts
- src/order/order-request-sender.ts
* Parent ticket: [CHECKOUT-6174](https://jira.bigcommerce.com/browse/CHECKOUT-6174).
* When a tax service is unavailable, `checkout-sdk-js` throws a custom error.
https://github.com/bigcommerce/bigcommerce/pull/43996
The back-end response is expected to be:
```
{
"status":500,
"code":10000,
"title":"The tax provider is unavailable.",
"type":"tax_provider_unavailable"
}
```
https://github.com/bigcommerce/checkout-js/pull/761
When a merchant wants to be able to block transactions if the automated tax provider cannot be accessed, we want Checkout to stop customers from placing orders.
https://user-images.githubusercontent.com/88361607/146317182-a09fd3f1-c92e-46ee-9abf-863efc528587.mov
> feat(checkout): CHECKOUT-6248 Throw Custom Error When Tax Service Unavailable

- src/payment/strategies/adyenv2/adyenv2-initialize-options.ts
- src/payment/strategies/adyenv2/adyenv2-payment-strategy.spec.ts
- src/payment/strategies/adyenv2/adyenv2-payment-strategy.ts
- src/payment/strategies/adyenv2/adyenv2.mock.ts
- src/payment/strategies/adyenv2/adyenv2.ts
Fix validation for Adyen card fields
because of task: [https://jira.bigcommerce.com/browse/ADYEN-296](https://jira.bigcommerce.com/browse/ADYEN-296)
Tests:
> fix(payment): ADYEN-296 Card fields validation

- src/payment/strategies/adyenv2/adyenv2-payment-strategy.spec.ts
- src/payment/strategies/adyenv2/adyenv2-payment-strategy.ts
- src/payment/strategies/adyenv2/adyenv2.ts
Fix bug that iDEAL button does not direct to bank login at checkout
Because of task: [https://jira.bigcommerce.com/browse/ADYEN-373](https://jira.bigcommerce.com/browse/ADYEN-373)
> fix(payments): ADYEN-373 fix iDEAL payment

- src/payment/strategies/bolt/bolt-payment-strategy.ts
- src/payment/strategies/bolt/bolt.ts
Replace Bolt single line payment component to the multi-field component
Because of task: [https://jira.bigcommerce.com/browse/BOLT-135](https://jira.bigcommerce.com/browse/BOLT-135)
Before:
After:
Tests:
> feat(payment): BOLT-135 multi-field component

- src/payment/strategies/afterpay/afterpay-script-loader.spec.ts
- src/payment/strategies/afterpay/afterpay-script-loader.ts
Replace the SDK URL to the newest one and modify the unit tests
Afterpay has deprecated the current URL without any previous notice so tests started to fail.
ping @bigcommerce/apex-integrations @bigcommerce/payments
> fix(payment): INT-5402 Afterpay - Change the SDK URL to the newest one

- src/payment/payment-methods.mock.ts
- src/payment/strategies/stripev3/stripev3-payment-strategy.spec.ts
- src/payment/strategies/stripev3/stripev3-payment-strategy.ts
From these 3 files the experiment INT-4087.stripe.v3.enable_reuse_payment_intent  was deleted 
The functionality will be implemented permanently
[VIDEO PROOF](https://drive.google.com/file/d/1ClgwdLSVk8-tFtBh8HLbZZ-DpuxzAA5p/view)
[STRIPE Dashboard](https://drive.google.com/file/d/1yom3N_G7dZ7aws5rXu0VtSDCNnFMv0Xy/view)
[BCAPP PR](https://github.com/bigcommerce/bigcommerce/pull/43815)
ping @bigcommerce/apex-integrations
> feat(payment): INT-5150 Delete experiment StripeV3 enable_reuse_payment_intent experiment

- src/checkout/checkout-service.spec.ts
- src/checkout/create-checkout-service.ts
- src/customer/create-customer-strategy-registry.ts
- src/customer/customer-request-options.ts
- src/customer/customer-strategy-action-creator.spec.ts
- src/customer/strategies/apple-pay/apple-pay-customer-initialize-options.ts
- src/customer/strategies/apple-pay/apple-pay-customer-mock.ts
- src/customer/strategies/apple-pay/apple-pay-customer-strategy.spec.ts
- src/customer/strategies/apple-pay/apple-pay-customer-strategy.ts
- src/customer/strategies/apple-pay/index.ts
- src/customer/strategies/braintree/braintree-visacheckout-customer-strategy.spec.ts
- src/payment/strategies/apple-pay/apple-pay-payment.mock.ts
- src/payment/strategies/apple-pay/index.ts
Add apple pay customer strategy
Add wallet button for apple pay, so shoppers can checkout using a wallet button in customer step.
- Screencast
https://user-images.githubusercontent.com/7134802/146874158-8d39a584-d572-4f9f-b4e5-77117ee67673.mov
> feat(payments): CHECKOUT-6070 Add apple pay customer strategy

- src/shipping/consignment-request-sender.ts
- src/shipping/consignment.ts
- src/shipping/pickup-option.ts
Add pickup options and address to consignment interface
As we introduce MLI, we need to add pickup options and address to consignment. 
- Tests
> feat(shipping): CHECKOUT-6004 Add pick up options to consignment interface

- src/payment/strategies/opy/opy-payment-error.spec.ts
- src/payment/strategies/opy/opy-payment-error.ts
- src/payment/strategies/opy/opy-payment-strategy.spec.ts
- src/payment/strategies/opy/opy-payment-strategy.ts
When trying to modify a cart for an order already paid, an error message
is shown informing the user that payment method is not available.
This modifies the message in order to be more verbose with the customer,
as the error occurs due to missing cart information or if the order has
already been paid.
https://user-images.githubusercontent.com/92743730/150851576-75ef50f3-f8bc-4cfa-a536-d97b08f688ab.mov
> fix(checkout) INT-5409: Change error message when payment data is unavailable

- package-lock.json
- package.json
Bump bigpay-client dependency to add browser info for Opayo
See https://github.com/bigcommerce/bigpay-client-js/pull/125
Opayo requires browser info to be passed along
See the above PR
> feat(payment): INT-4969 Bump bigpay-client dependency to add browser info for Opayo

- src/customer/strategies/apple-pay/apple-pay-customer-strategy.ts
As above
The current implementation of wallet button for apple pay doesn't resemble the wallet button in cart page. As part of experience make the customer step button similar to cart page.
- Screenshot
> fix(payment): CHECKOUT-6070 Update style of apple pay customer step button

- src/checkout-buttons/checkout-button-initializer.spec.ts
- src/checkout-buttons/checkout-button-options.ts
- src/checkout-buttons/create-checkout-button-initializer.ts
- src/checkout-buttons/create-checkout-button-registry.spec.ts
- src/checkout-buttons/create-checkout-button-registry.ts
- src/checkout-buttons/strategies/apple-pay/apple-pay-button-initialize-options.ts
- src/checkout-buttons/strategies/apple-pay/apple-pay-button-mock.ts
- src/checkout-buttons/strategies/apple-pay/apple-pay-button-strategy.spec.ts
- src/checkout-buttons/strategies/apple-pay/apple-pay-button-strategy.ts
- src/checkout-buttons/strategies/apple-pay/index.ts
- src/checkout-buttons/strategies/checkout-button-method-type.ts
- src/checkout-buttons/strategies/checkout-button-strategy.ts
Replace ApplePay in cart with the new code from `checkout-sdk-js`. Most code is based on [ApplePay customer strategy](https://github.com/bigcommerce/checkout-sdk-js/pull/1307) . 
Also:
- Allow a developer to initialize the button with a cutom class name.
- Default button styles `apple-pay-checkout-button` are defined in [BCapp/templates/__master/Styles/styles.css](https://github.com/bigcommerce/bigcommerce/blob/60c07dcbe0fd98f7af293f1059817e79090163e6/templates/__master/Styles/styles.css#L570). Developers might already use this class name to create their own ApplePay button.
https://github.com/bigcommerce/bigcommerce/pull/44819
Consolidate BigCommerce's digital wallet experience for developers and shopers.
https://user-images.githubusercontent.com/88361607/151727538-bc946483-e555-4b50-aad5 …
> feat(checkout): CHECKOUT-6071 Update Apple Pay in Cart

- src/order/order.ts
- src/order/orders.mock.ts
Update `Order` Interface to document the new `consignments` property.
`consignments`'s back-end documentation is [here](https://github.com/bigcommerce/api-specs/blob/master/reference/orders.sf.yml).
_* leave `pickup` consignments for future work._ 
[ORDERS-4432](https://jira.bigcommerce.com/browse/ORDERS-4432) introduced a new `consignments` property to responses from the Storefront [Order](https://github.com/bigcommerce/checkout-sdk-js/blob/55edbb9e8f7ad895517809ed10bef6750a8914c2/docs/interfaces/order.md) API. 
The Order object returned by [getOrder](https://github.com/bigcommerce/checkout-sdk-js/blob/55edbb9e8f7ad895517809ed10bef6750a8914c2/docs/interfaces/checkoutstoreselector.md#getorder) already has a new `consignments` property, but it is not yet documented.
> docs(checkout): CHECKOUT-6260 Update Order Interface Documentation

- src/order/order.ts
Add mandate and methodId  property to the gateway Order Payments.
So they can be accessed in the Order Status page.
[Demo Videos](https://drive.google.com/drive/folders/1VcyX_5nMpL3Ri0nMPOcgDqWWBq0Kmzvx?usp=sharing)
https://github.com/bigcommerce/bigcommerce/pull/42364
https://github.com/bigcommerce/bigpay/pull/4234
https://github.com/bigcommerce/checkout-js/pull/674
1) https://github.com/bigcommerce/checkout-sdk-js/pull/1220
2) https://github.com/bigcommerce/bigcommerce/pull/42364
https://github.com/bigcommerce/bigpay/pull/4234
https://github.com/bigcommerce/checkout-js/pull/674
> feat(order): INT-4776 Create a new field for the mandate reference ID

- src/payment/strategies/square/square-form.ts
- src/payment/strategies/square/square-payment-initialize-options.ts
- src/payment/strategies/square/square-payment-strategy-mock.ts
- src/payment/strategies/square/square-payment-strategy.spec.ts
- src/payment/strategies/square/square-payment-strategy.ts
remove Masterpass support for square
The project has been canceled and will not be developed or launched.
https://github.com/bigcommerce/bigpay/pull/4470
https://github.com/bigcommerce/bigcommerce/pull/43061
https://github.com/bigcommerce/ng-payments/pull/1437
https://github.com/bigcommerce/checkout-js/pull/718
Based on tests, the order to merge the PR’s avoiding problems should be the following:
1.- Ng-payments https://github.com/bigcommerce/ng-payments/pull/1437 and bump
2.- Bcapp: https://github.com/bigcommerce/bigcommerce/pull/43061
3.- SDK and bump  
4.- JS using SDK bump
5.- bump JS into BCAPP
6.- Bigpay https://github.com/bigcommerce/bigpay/pull/4470
> feat(payment): INT-4282 removing masterpass logic for square

- src/checkout/checkout-service.spec.ts
- src/checkout/checkout-service.ts
- src/checkout/checkout-store-state.ts
- src/checkout/checkouts.mock.ts
- src/checkout/create-checkout-service.ts
- src/checkout/create-checkout-store-reducer.ts
- src/checkout/create-internal-checkout-selectors.ts
- src/common/utility/index.ts
- src/common/utility/object-flatten.spec.ts
- src/common/utility/object-flatten.ts
- src/common/utility/object-with-sorted-keys.spec.ts
- src/common/utility/object-with-sorted-keys.ts
- src/shipping/consignment.ts
- src/shipping/index.ts
- src/shipping/pickup-option-action-creator.spec.ts
- src/shipping/pickup-option-action-creator.ts
- src/shipping/pickup-option-actions.ts
- src/shipping/pickup-option-reducer.spec.ts
- src/shipping/pickup-option-reducer.ts
- src/shipping/pickup-option-request-sender.spec.ts
- src/shipping/pickup-option-request-sender.ts
- src/shipping/pickup-option-selector.spec.ts
- src/shipping/pickup-option-selector.ts
- src/shipping/pickup-option-state.ts
- src/shipping/pickup-option.mock.ts
- src/shipping/pickup-option.ts
Add implementation to fetch available shipping options.
We have an endpoint to fetch available shipping options as part of MLI project. Hence adding methods so partners can leverage that functionality via SDK
- Tests
@bigcommerce/checkout @bigcommerce/shipping
> feat(shipping): CHECKOUT-6003 Add method to fetch available shipping options

- src/payment/strategies/klarnav2/klarna-supported-countries.ts
Add support for poland(PL), portugal(PT) and ireland(IE) on klarna eu
So shoppers can pay using klarna from poland with PLN, from portugal and ireland with EUR
https://github.com/bigcommerce/bigpay/pull/4974
> feat(payment): INT-5156 Klarna add support for poland, portugal, ireland

- src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.spec.ts
- src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.ts
- src/payment/strategies/stripe-upe/stripe-upe.ts
Added a function to handle 'redirect required' methods
To be able to pay using sofort via Stripe UPE
https://drive.google.com/file/d/1-AspMwus-uDN_950-SjAtN_w9_pVRBtN/view?usp=sharing
> feat(payment): INT-5090 Stripe UPE add return url for SOFORT support

- .metadata_rules.yml
Work in Progress
Add loader.js to .metadata_rules.yml with `cache_control: 'no-cache, max-age=0'`
Allow CDNs to respect origin headers for loader.js.
Pending
> Don't cache loader.js

- src/checkout/checkout-service.ts
- src/shipping/pickup-option.mock.ts
- src/shipping/pickup-option.ts
As above
As linked to https://github.com/bigcommerce/bigcommerce/pull/45161 the interface for radius has been defined to be more explicit and readable.
Hence making the corresponding change to what SDK has to offer
- Unit tests
@bigcommerce/checkout @bc-luke
> feat(shipping): CHECKOUT-6003 Add radius unit type and update interface

- src/payment/instrument/supported-payment-instruments.ts
Adding sagepay to supported instruments
In order to see vaulted cc on checkout
[BCAPP](https://github.com/bigcommerce/bigcommerce/pull/44922)
[BIGPAY](https://github.com/bigcommerce/bigpay/pull/4969)
> feat(payment): INT-4970 Sagepay Stored Credit Cards

- src/payment/strategies/opy/opy-payment-error.spec.ts
- src/payment/strategies/opy/opy-payment-error.ts
- src/payment/strategies/opy/opy-payment-strategy.spec.ts
- src/payment/strategies/opy/opy-payment-strategy.ts
Change the `OpyError` message for an invalid cart.
The Openpay team wants us to use the following messages:
- For AU/UK/NZ: "Cart price is different to Openpay plan amount."
- For US merchants: "Cart price is different to Opy plan amount."
https://github.com/bigcommerce/checkout-js/pull/825
> fix(payment): INT-5645 Openpay: Change `OpyError` message

- src/payment/strategies/mollie/mollie-payment-strategy.spec.ts
- src/payment/strategies/mollie/mollie-payment-strategy.ts
change the way to delete elements of the dom when it is deinitialized.
Mollie payment gateway's credit card information form is not interactable when switching to Mollie APM then returning to   credit card.
[VIDEO](https://drive.google.com/file/d/13pAjWm9TdAhF2pyTitF4QwXvOt-4DX9e/view?usp=sharing)
> fixing deinitialize logic for mollie strategy

- src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.ts
- src/payment/strategies/stripe-upe/stripe-upe.ts
Add Support for EPS payment Method on StripeUpe
As a customer, when the currency is EUR and the country is Austria, I want to be able to pay with EPS
[https://drive.google.com/file/d/1yM7BMqOZHpBlmnnUQSfm3DPL75y_6aaY/view?usp=sharing](https://drive.google.com/file/d/1yM7BMqOZHpBlmnnUQSfm3DPL75y_6aaY/view?usp=sharing)
INT-5090
INT-5035
Ping @bigcommerce/apex-integrations @bigcommerce/kyiv-payments-team @bigcommerce/payments
> feat(payment): INT-5034 StripeUPE Add support for EPS

- src/payment/strategies/stripev3/stripev3-payment-strategy.spec.ts
- src/payment/strategies/stripev3/stripev3-payment-strategy.ts
Fix an issue that makes customers with saved credit cards unable to checkout when 3DS is enabled.
Payment attempts using Stripev3 with 3D Secure are failing on the checkout page.
> fix(payment): INT-5723 StripeV3 fix vaulted cards with 3ds on 

- src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.ts
- src/payment/strategies/stripe-upe/stripe-upe.ts
Add support for Bancontact & iDeal as a payment methods on StripeUPE.
As a Shopper
I want to be able to pay for my order using BANCONTACT or IDEAL
So that I can complete my purchase.
- [Video](https://drive.google.com/file/d/1ukxScnqYRweHE2XK7bIiQ8oSbl6bv1PI/view?usp=sharing)
- [Video](https://drive.google.com/file/d/1uYhervsyDjCxsP89-EOopzSyxNLo9wz3/view?usp=sharing)
> feat(payment): INT-5042 [Stripe UPE] Add support for Bancontact & iDeal

- src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.ts
- src/payment/strategies/stripe-upe/stripe-upe.ts
Added Giropay and Alipay experiments and options to enable it on Stripe UPE settings page.
To enable and use Giropay and Alipay with Stripe UPE.
Manual tests
https://github.com/bigcommerce/checkout-sdk-js/pull/1348
@bigcommerce/checkout @bigcommerce/payments @bigcommerce/apex-integrations @bigcommerce/kyiv-payments-team
> feat(payment): INT-5033 - INT-5053 [Stripe UPE] Add support for Giropay and Alipay

- src/payment/strategies/googlepay/googlepay-checkoutcom-initializer.spec.ts
- src/payment/strategies/googlepay/googlepay-checkoutcom-initializer.ts
Increase Code Coverage for googlepay-checkoutcom-initializer.ts
To increase code coverage
> test(payment): INT-4928 Increase code coverage for GooglePayCheckoutCom

- src/checkout-buttons/strategies/apple-pay/apple-pay-button-strategy.ts
- src/customer/strategies/apple-pay/apple-pay-customer-strategy.ts
Throw error if no shipping options present
At the moment if there are no shipping options returned for a particular address, then apple pay sheet breaks and errors out. 
Catch and throw the exception instead of the code erroring out.
- Unit tests 
- Screencast
https://user-images.githubusercontent.com/7134802/160533270-7a32000e-f1c1-47d9-8371-7be1f54b7389.mov
@bigcommerce/checkout @BC-ISilva
> fix(shipping): CHECKOUT-0000 Throw error if no shipping options present

- src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.spec.ts
- src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.ts
- src/payment/strategies/stripe-upe/stripe-upe.ts
Stripe Payment Element hides the following fields that are required earlier in the checkout flow: **email**, **address**, **city**, **postal code/zip code**, **country**, **state/province** for all supported Stripe UPE payment methods.
These fields are collected from the billing data and provided to stripe in the confirm step
To avoid having my shopper re-enter any information in the payment step that was collected earlier in the checkout flow
So that I can allow them to checkout faster
Before
After
Card element without Country/postal code fields
Before
After (name is not on the list of fields to hide)
> feat(payment): INT-5572 Stripe UPE Hide Fields

- src/customer/strategies/googlepay/googlepay-customer-strategy.ts
- Fix redirect in googlepay using embedded checkout on customer section
- When a client clicks Gpay button on the customer section using embedded Checkout page, the application redirects to BC store to continue the payment process instead of the current page
[VIDEO](https://drive.google.com/file/d/16ySUzMdSAlvUtFFE6MyoFkZNGAKxsZkd/view?usp=sharing)
https://github.com/bigcommerce/bigcommerce/pull/44273
> fix(payment): INT-5175 fixing redirect in googlepay using embedded checkout on customer section

- src/payment/create-payment-strategy-registry.ts
- src/payment/strategies/checkoutcom/checkoutcom-token.ts
- src/payment/strategies/googlepay/googlepay-adyenv2-payment-processor.ts
- src/payment/strategies/googlepay/googlepay-adyenv3-payment-processor.ts
- src/payment/strategies/googlepay/googlepay-checkoutcom-initializer.spec.ts
- src/payment/strategies/googlepay/googlepay-checkoutcom-initializer.ts
- src/payment/strategies/googlepay/googlepay-checkoutcom-payment-processor.spec.ts
- src/payment/strategies/googlepay/googlepay-checkoutcom-payment-processor.ts
- src/payment/strategies/googlepay/googlepay-payment-processor.ts
- src/payment/strategies/googlepay/googlepay-payment-strategy.spec.ts
- src/payment/strategies/googlepay/googlepay-payment-strategy.ts
- src/payment/strategies/googlepay/googlepay.ts
- src/payment/strategies/googlepay/index.ts
Create a payment processor for GooglePay on Checkout.com that handles the redirection to the 3DS challenge page.
Update the GooglePay payment strategy to receive a generic payment processor for specific provider instead of directly expecting the Adyen payment processor.
Also send the token_format in the Checkout.com's Google Pay initializer so it can be stored in the session.
GooglePay on  Checkout.com will be implementing 3DS starting March 30th, the current implementation does not support the 3DS redirection and throws an error, these changes are made to support the redirection to the challenge page and proceed with the payment.
The new strategy interface will allow to pass any processor in the constructor so It will be able to support different providers.
Passing the token format to …
> fix(checkout): INT-5543 [CKO] Update to 3ds on Googlepay

- src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.spec.ts
- src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.ts
- src/payment/strategies/stripe-upe/stripe-upe.mock.ts
- src/payment/strategies/stripe-upe/stripe-upe.ts
Support for using vaulted cards with Stripe UPE
To allow shoppers to save their credit card and use it in future purchases
> feat(payment): INT-5057 STRIPE UPE use vaulted card

- src/payment/create-payment-strategy-registry.spec.ts
- src/payment/create-payment-strategy-registry.ts
- src/payment/instrument/supported-payment-instruments.ts
- src/payment/payment-methods.mock.ts
- src/payment/payment-response-body.ts
- src/payment/payment-strategy-type.ts
- src/payment/strategies/cba-mpgs/cba-mpgs-payment-strategy.spec.ts
- src/payment/strategies/cba-mpgs/cba-mpgs-payment-strategy.ts
- src/payment/strategies/cba-mpgs/cba-mpgs-script-loader.spec.ts
- src/payment/strategies/cba-mpgs/cba-mpgs-script-loader.ts
- src/payment/strategies/cba-mpgs/cba-mpgs.mock.ts
- src/payment/strategies/cba-mpgs/cba-mpgs.ts
- src/payment/strategies/cba-mpgs/index.ts
Create a payment strategy for CBA-MPGS that implement MPGS' ThreeDsJs and allows the redirection to the challenge site.
So Payments with 3DS for MPGS are supported.
Demo Video:
https://drive.google.com/file/d/1RKs3W7-oRx5pP0XAa9JCX_VxqcWyEQpQ/view?usp=sharing
https://github.com/bigcommerce/checkout-js/pull/822
https://github.com/bigcommerce/bigcommerce/pull/45233
https://github.com/bigcommerce/bigpay/pull/5055
> feat(checkout): INT-5126 [MPGS] Add 3DS support to MPGS

- src/payment/strategies/mollie/mollie-payment-strategy.spec.ts
- src/payment/strategies/mollie/mollie-payment-strategy.ts
- src/payment/strategies/moneris/moneris-payment-strategy.spec.ts
- src/payment/strategies/moneris/moneris-payment-strategy.ts
- src/payment/strategies/stripev3/stripev3-payment-strategy.spec.ts
- src/payment/strategies/stripev3/stripev3-payment-strategy.ts
Added `detach` function to deinitialize event on Stripe, Moneris and Mollie as they have TS Verfication hosted fields 
As a shopper i dont want to see the hosted verification fields being repeated 
> feat(payment): INT-5498 add detach function to deinitialize

- src/common/data-store/create-data-store-projection.ts
- src/common/error/errors/missing-data-error.ts
- src/core/payment-integration/create-payment-integration-selectors.spec.ts
- src/core/payment-integration/create-payment-integration-selectors.ts
- src/core/payment-integration/default-payment-integration-service.spec.ts
- src/core/payment-integration/default-payment-integration-service.ts
- src/core/payment-integration/index.ts
- src/core/payment-integration/payment-integration-selectors.ts
- src/core/payment-integration/payment-integration-service.ts
- src/core/payment-integration/payment-integration-store-projection-factory.spec.ts
- src/core/payment-integration/payment-integration-store-projection-factory.ts
- src/order/order-action-creator.ts
- src/order/order-request-sender.ts
- src/payment/instrument/instrument-selector.ts
- src/payment/payment-selector.ts
- src/shipping/consignment-selector.ts
- src/shipping/index.ts
- src/shipping/shipping-address-selector.ts
- src/shipping/shipping-address.ts
Add `PaymentIntegrationService` to be used in payment strategies according to [this proposal](https://github.com/bigcommerce/documentation/pull/707).
So that payment strategies, which will be extracted into their own packages, can depend on an established API contract implemented by the checkout team.
Unit
@bigcommerce/checkout @bigcommerce/payments @bigcommerce/apex-integrations @bigcommerce/kyiv-payments-team
> CHECKOUT-6264: Add payment integration service

- src/checkout/checkout-service.spec.ts
- src/checkout/checkout-store-selector.ts
- src/shipping/consignment-action-creator.spec.ts
- src/shipping/consignment-action-creator.ts
- src/shipping/consignment-request-sender.spec.ts
- src/shipping/consignment.ts
- src/shipping/consignments.mock.ts
- src/shipping/shipping-address-selector.ts
- Add address field as an alias to ShippingAddress
- Update shipping selector methods to return details for first shipping consignment rather than the first consignment.
Due to changes to consignment API add changes to interface.
Also address selector methods related to shipping consignment to return details from first shipping consignment
- Tests
> feat(shipping): CHECKOUT-6422 Add address property to consignment interface

- src/checkout-buttons/strategies/apple-pay/apple-pay-button-strategy.spec.ts
- src/checkout-buttons/strategies/apple-pay/apple-pay-button-strategy.ts
Add `loadDefaultCheckout()` to the Apple Pay checkout button.
Apple Pay throws a `MissingDataError` error on the cart page.
The bugfix is currently on the intergration stage.
Demo: https://ivansilva1649702646-testsworthy.my-integration.zone/.
> fix(checkout): CHECKOUT-6563 Apple Pay on Cart Page Loads Checkout Settings

- src/payment/strategies/stripe-upe/stripe-upe-initialize-options.ts
- src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.spec.ts
- src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.ts
- src/payment/strategies/stripe-upe/stripe-upe.mock.ts
- src/payment/strategies/stripe-upe/stripe-upe.ts
Gets the store theme checkout styles to change the appearance of the Stripe UPE
To have the payment element style match with the store style
https://github.com/bigcommerce/checkout-js/pull/832
> feat(payment): INT-5060 Stripe UPE Look and Feel - map theme styles to stripe appearance API

- src/shipping/consignment-action-creator.ts
- src/shipping/consignment.ts
Use union type for consignment assignment interface
As part of interface update it causes a breaking change which is not out intention at this point. So implement a union interface with a type guard so custom checkouts can update sdk without having build issues for their checkout
- Test
> fix(shipping): CHECKOUT-6422 Use union type for consignment assignment interface

- src/payment/payment-methods.mock.ts
- src/payment/payment.ts
- src/payment/strategies/mollie/mollie-payment-strategy.spec.ts
- src/payment/strategies/mollie/mollie-payment-strategy.ts
- src/payment/strategies/mollie/mollie.mock.ts
[INT-5573](https://jira.bigcommerce.com/browse/INT-5573): Add shopper locale to Mollie strategy.
Payment methods are not displaying in the correct language when merchant selects _Enable automatic translation based on shopper’s browser language_ at Store Profile. We need this parameter to determine the locale on Mollie payments in BigPay.
Mollie payment method redirection using shopper's browser language settings:
* https://github.com/bigcommerce/bigcommerce/pull/45854
* https://github.com/bigcommerce/bigpay/pull/5223
> feat(payment): INT-5573 Add shopper locale to Mollie strategy

- src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.spec.ts
- src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.ts
Fix for redirect payments with hidden fields
Confirming redirect based methods was failing because the hidden fields were not being added to the confirm parameters
https://drive.google.com/file/d/1_fgvCNJRsaKHDKoTz1u78P2ikguWonII/view?usp=sharing
> fix(payment): INT-5821 Error on the Checkout related to Hide some fields using APM's

- package-lock.json
- package.json
Update to webpack 5
Since we want to add Nx for monorepo tooling, it requires us to be on webpack v5. 
Plus 
- get faster builds 
- Slightly smaller bundle size (without any config change)
- Tests
- Circle
> chore(common): CHECKOUT-6268 Update to webpack 5

- webpack-cdn.config.js
- webpack.config.js
Fix build process for cdn-deploy
As a config-name args has a type of string[], due to which the build for cdn was failing. Apply the fix.
> fix(common): CHECKOUT-6268 Check in array while loading config

- scripts/webpack/transform-manifest.js
As above
With the upgrade of the dependant plugin now `Assets for an entrypoint are now included in an assets property`
Reference https://www.npmjs.com/package/webpack-assets-manifest
- Manifest from integration deploy
> fix(common): CHECKOUT-6268 Update asset path

- package.json
Update node version requirements in the package.json from `14.18` to `>=14.18`
Currently cannot install this SDK on any project unless it is explicitly node v 14.18
IMO this is a short-term fix and the node version should be upgraded to the current stable version, `16.14` at the time of this PR.
> Update node version requirement to >=14.18

- src/payment/strategies/adyenv3/adyenv3-payment-strategy.spec.ts
- src/payment/strategies/adyenv3/adyenv3-payment-strategy.ts
- src/payment/strategies/adyenv3/adyenv3.mock.ts
- src/payment/strategies/adyenv3/adyenv3.ts
In this PR was implemented AdyenV3 component state fix.
Previously data was received directly from the adyen sdk componentState object but it was a mistake because Adyen SDK modifies this data before submitting. ComponentState data gets on onChange event via Adyen SDK API.
Due to the fix of https://jira.bigcommerce.com/browse/ADYEN-431
Manually/Units
> fix(checkout): ADYEN-431 AdyenV3 component state fix

- src/checkout-buttons/strategies/apple-pay/apple-pay-button-strategy.spec.ts
- src/checkout-buttons/strategies/apple-pay/apple-pay-button-strategy.ts
- src/customer/strategies/apple-pay/apple-pay-customer-strategy.spec.ts
- src/customer/strategies/apple-pay/apple-pay-customer-strategy.ts
When a shopper selects a non-default shipping method on the cart page, updates shipping, and then clicks the express pay button for Apple Pay, the shipping method is not persisted into the Apple Pay modal. 
The shipping option/method that the shopper selects on the cart page should be automatically selected within the Apple Pay modal. 
The expected behavior should occur on all Apple Pay compatible providers:
- Adyen
- Authorize.Net
- Bolt Payments
- Checkout.com
- Stripe
- PayPal powered by Braintree
- Chase Merchant Services (beta)
- Moneris (beta)
[Demo Video](https://drive.google.com/file/d/1-N8MHvMqA0XXYB_dhJ8ArOwgKHsLnVID/view?usp=sharing)
Revert PR
ping @bigcommerce/apex-integrations @bigcommerce/checkout @bigcommerce/payments
> feat(checkout): INT-5273 Non-Default Shipping Method Selection On Cart Page Is Not Persisted to Apple Pay

- src/payment/payment.ts
- src/payment/strategies/braintree/braintree-credit-card-payment-strategy.spec.ts
- src/payment/strategies/braintree/braintree-credit-card-payment-strategy.ts
- src/payment/strategies/braintree/braintree-hosted-form.spec.ts
- src/payment/strategies/braintree/braintree-hosted-form.ts
- src/payment/strategies/braintree/braintree-payment-processor.spec.ts
- src/payment/strategies/braintree/braintree-payment-processor.ts
- src/payment/strategies/braintree/braintree.ts
- added implementation to handle 3DS required error for stored credit card;
- added extra check on 3DS regulation for credit card (not stored);
- added extra test coverage for Braintree strategy, payment processor and hosted form functionality;
Some EU merchants are having the issue with payments made with stored credit cards. When the customer tried to pay with store credit card the Braintree had an error with "Authentication Required: The customer’s bank declined the transaction because a 3D Secure authentication was not performed during checkout" message.
The main point is in our implementation of 3DS verification for Braintree, or specifically in the fact that 3DS is skipped for stored credit card payments.
This behaviour seems to be by design, but the receiving banks are now …
> feat(payment): PAYPAL-1177 added implementation to handle 3DS required error from backend

- src/payment/payment-method-action-creator.spec.ts
- src/payment/payment-method-action-creator.ts
Fix Sentry Issue: [CHECKOUT-JS-4WG](https://sentry.io/organizations/bigcommerce/issues/2782844130/?referrer=jira_integration).
When this happens, I'm guessing a shopper gets a message like this.
The reason for `t.filter is not a function` could be that `methods` within `methods.filter()` is an empty string. This bugfix provides a readable error message and instructs the shopper to try again.
After applying the fix.
> fix(checkout): CHECKOUT-6631 Sentry issue bugfix

- src/payment/strategies/stripe-upe/stripe-upe-initialize-options.ts
- src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.spec.ts
- src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.ts
Use a subscriber to update the payment intent amount whenever the customer changes payment method or a coupon or store credit is used with stripe UPE
So the customer is charged the correct amount and the price in the order is matching
https://drive.google.com/file/d/1AAsEr5KsNoS6WgeY_fAvR-z43j6b_TSh/view?usp=sharing
https://github.com/bigcommerce/checkout-js/pull/836
https://github.com/bigcommerce/bigcommerce/pull/45506
https://github.com/bigcommerce/bigpay/pull/5145
https://github.com/bigcommerce/bigpay-client-php/pull/244
> feat(payment): INT-5754 Stripe UPE update payment intent

- src/payment/payment-methods.mock.ts
- src/payment/strategies/cba-mpgs/cba-mpgs-payment-strategy.spec.ts
- src/payment/strategies/cba-mpgs/cba-mpgs-payment-strategy.ts
Use the feature flag value to decide which version of ThreeDS script to load instead of `testMode`
To stop dependency in testMode, so `test` transaction can be made using the production environment script.
- [With the feature flag off ](https://drive.google.com/file/d/1kPYKZf6t6Mxrv0Q5Ylt09kw9b3EMflmw/view?usp=sharing)
- [With the feature flag on](https://drive.google.com/file/d/1s1Fm0i0VrT_uG6gzXon9oWsDl-1-pXNM/view?usp=sharing)
> feat(checkout): INT-5963 Check for feature flag when loading threeDS Script

- src/config/config.ts
- src/config/configs.mock.ts
Adds type of checkoutBillingSameAsShipping check for shopper during the checkout process
Needs as part of Checkout JS so we can do checks for checkout store setting
N/A
> chore(checkout): CHECKOUT-updated types for checkout StoreSetting

- packages/core/src/checkout-buttons/create-checkout-button-registry.ts
- packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-strategy.spec.ts
- packages/core/src/payment/create-payment-strategy-registry.ts
- packages/core/src/payment/strategies/paypal-commerce/create-paypal-commerce-payment-processor.ts
- packages/core/src/payment/strategies/paypal-commerce/paypal-commerce-credit-card-payment-strategy.spec.ts
- packages/core/src/payment/strategies/paypal-commerce/paypal-commerce-funding-key-resolver.spec.ts
- packages/core/src/payment/strategies/paypal-commerce/paypal-commerce-funding-key-resolver.ts
- packages/core/src/payment/strategies/paypal-commerce/paypal-commerce-hosted-form.spec.ts
- packages/core/src/payment/strategies/paypal-commerce/paypal-commerce-payment-processor.spec.ts
- packages/core/src/payment/strategies/paypal-commerce/paypal-commerce-payment-processor.ts
- packages/core/src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.spec.ts
- packages/core/src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.ts
- packages/core/src/payment/strategies/paypal-commerce/paypal-commerce-sdk.ts
- packages/core/src/payment/strategies/paypal-commerce/paypal-commerce.mock.ts
POC of new order creation process for PayPal OXXO APM
OXXO APM requires PayPal order patching before popup is opened. We need to implement the next flow:
-> click
--> PayPal order create
--> BC order create
--> patch PayPal order
--> return order id
-----> popup opens (order becomes COMPLETE)
-------->  order approve
Existing approach for other APMs
-> click
--> PayPal order create   
----> popup opens (order becomes CREATE)
------> order approve
------> BC order create
------> patch PayPal order
------> return order id
After popup is opened on checkout page the PayPal OXXO order becomes COMPLETE. PayPal order can not be patched with COMPLETED status  
https://github.com/bigcommerce/bigpay/pull/5305
https://github.com/bigcommerce/interfaces/pull/2089 …
> feat(payment): PAYPAL-1420 POC of new order creation process for PayPal oxxo APM

- packages/core/src/payment/strategies/braintree/braintree-payment-processor.spec.ts
- packages/core/src/payment/strategies/braintree/braintree-payment-processor.ts
Added extra check on 'unavailable' authenticationInsight to trigger braintree 3DS for this type of transactions.
Because some of the transactions with 'unavailable' authenticationInsight can require 3DS verification
Unit tests
> feat(payment): PAYPAL-1465 added extra check for braintree 3DS verification

- packages/core/src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.ts
Make stripe UPE decide when to show the state field
Because we are currently getting the state value from the billing info and, depending on the selected country, bigcommerce might not require the customer to fill the state field or stripe might need the state field on a different format
Before: https://drive.google.com/file/d/1UDlFZ760W0AZQoQd_xxTD9fMtrOifvNL/view?usp=sharing
Now: 
> fix(payment): INT-5949 Stripe UPE Don't hide state field

- packages/core/src/payment/payment.ts
- packages/core/src/payment/strategies/adyenv2/adyenv2-payment-strategy.spec.ts
- packages/core/src/payment/strategies/adyenv2/adyenv2-payment-strategy.ts
- packages/core/src/payment/strategies/adyenv3/adyenv3-payment-strategy.spec.ts
- packages/core/src/payment/strategies/adyenv3/adyenv3-payment-strategy.ts
Passed origin in bigpay_token for adyen v2/v3 vaulted card checkout
Due to https://bigcommercecloud.atlassian.net/browse/ADYEN-480
> fix(checkout): ADYEN-480 adyen vaulting fix

- packages/core/src/checkout-buttons/strategies/braintree/braintree-paypal-button-strategy.ts
Fixed default currency issue for Braintree SPB
According to task https://bigcommercecloud.atlassian.net/browse/PAYPAL-1466
> feat(payment): PAYPAL-1466 fixed currency issue

- packages/core/src/checkout-buttons/strategies/amazon-pay-v2/amazon-pay-v2-button-strategy.spec.ts
- packages/core/src/checkout-buttons/strategies/amazon-pay-v2/amazon-pay-v2-button-strategy.ts
- packages/core/src/customer/strategies/amazon-pay-v2/amazon-pay-v2-customer-strategy.spec.ts
- packages/core/src/customer/strategies/amazon-pay-v2/amazon-pay-v2-customer-strategy.ts
- packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-strategy.spec.ts
- packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-strategy.ts
for `createCheckoutSession.url`
As per [Amazon's Docs](https://developer.amazon.com/docs/amazon-pay-checkout/v1-add-the-amazon-pay-button.html#3-render-the-button):
> The Amazon Pay script will make an AJAX request using the configuration provided for the createCheckoutSession button parameter.
With that in mind, I decided to pass a relative URL instead for `createCheckoutSession.url` and let the `XMLHttpRequest` object resolve the URL of the request, which will be the URL of the document that contains the Amazon Pay script (our checkout page).
This way we cover special cases for stores using [Weglot](https://weglot.com/integrations/translate-bigcommerce-website/), which uses specific subdomains for each language. Therefore, subdomains are trying to hit the main `StoreProfile.shopPath`, …
> fix(payment): INT-5826 AmazonPayV2: Provide a relative URL

- packages/core/src/order/internal-order-request-body.ts
- packages/core/src/order/internal-orders.mock.ts
- packages/core/src/order/order-action-creator.ts
- packages/core/src/order/order-request-sender.spec.ts
Added Cart Id as a required parameter for order creation API endpoint when creating an order.
To support buy-now cart, we will need to pass cart id for order creation API endpoint when creating an order.
Will be merged after https://github.com/bigcommerce/bigcommerce/pull/46390 release to T3
> feat(checkout): CHECKOUT-6703 post cartid for order creation API endpoint

- packages/core/src/checkout-buttons/checkout-button-options.ts
- packages/core/src/checkout-buttons/checkout-button-strategy-action-creator.ts
- packages/core/src/checkout-buttons/create-checkout-button-registry.spec.ts
- packages/core/src/checkout-buttons/create-checkout-button-registry.ts
- packages/core/src/checkout-buttons/strategies/braintree/braintree-paypal-credit-button-options.ts
- packages/core/src/checkout-buttons/strategies/braintree/braintree-paypal-credit-button-strategy.spec.ts
- packages/core/src/checkout-buttons/strategies/braintree/braintree-paypal-credit-button-strategy.ts
- packages/core/src/checkout-buttons/strategies/braintree/index.ts
- packages/core/src/checkout-buttons/strategies/checkout-button-method-type.ts
Added braintreepaypalcredit checkout button strategy
To separate Braintree PayPal Credit/Paylater functionality from braintreepaypal strategy to its own.
Unit tests
Manual tests
> feat(payment): PAYPAL-1382 added braintreepaypalcredit checkout button strategy

- packages/core/src/checkout-buttons/checkout-button-strategy-action-creator.ts
- packages/core/src/checkout-buttons/create-checkout-button-registry.spec.ts
- packages/core/src/checkout-buttons/create-checkout-button-registry.ts
- packages/core/src/checkout-buttons/strategies/braintree/braintree-paypal-button-options.ts
- packages/core/src/checkout-buttons/strategies/braintree/braintree-paypal-button-strategy.spec.ts
- packages/core/src/checkout-buttons/strategies/braintree/braintree-paypal-button-strategy.ts
- packages/core/src/checkout-buttons/strategies/braintree/index.ts
- packages/core/src/checkout-buttons/strategies/checkout-button-method-type.ts
Added braintreepaypal checkout button strategy
To contain Braintree Paypal specific code in its own file.
Unit tests
Manual tests
> feat(payment): PAYPAL-1382 added braintreepaypal checkout button strategy

- packages/core/src/checkout-buttons/checkout-button-options.ts
- packages/core/src/checkout-buttons/create-checkout-button-registry.spec.ts
- packages/core/src/checkout-buttons/create-checkout-button-registry.ts
- packages/core/src/checkout-buttons/strategies/braintree/braintree-venmo-button-options.ts
- packages/core/src/checkout-buttons/strategies/braintree/braintree-venmo-button-strategy.spec.ts
- packages/core/src/checkout-buttons/strategies/braintree/braintree-venmo-button-strategy.ts
- packages/core/src/checkout-buttons/strategies/braintree/index.ts
Added braintreevenmo checkout button strategy
To separate braintree venmo functionality from braintreepaypal strategy to its own.
Manual tests
Unit tests
> feat(payment): PAYPAL-1381 added braintreevenmo checkout button strategy

- packages/core/src/payment/payment-method-request-sender.spec.ts
- packages/core/src/payment/payment-method-request-sender.ts
- packages/core/src/payment/strategies/afterpay/afterpay-payment-strategy.spec.ts
- packages/core/src/payment/strategies/afterpay/afterpay-payment-strategy.ts
- packages/core/src/payment/strategies/clearpay/clearpay-payment-strategy.spec.ts
- packages/core/src/payment/strategies/clearpay/clearpay-payment-strategy.ts
- packages/core/src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.ts
- packages/core/src/payment/strategies/stripev3/stripev3-payment-strategy.ts
To pass `method` as params, instead of as bundle string of gatewayId like this `${gatewayId}?method=${methodId}`
For adding additional parameter when calling loadPaymentMethod in the future.   
@bigcommerce/checkout @bigcommerce/payments @josesonora @BC-AOrtiz
> refactor(common): CHECKOUT-6752 Refactor payment strategies to pass method as params

- package-lock.json
- package.json
- packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-strategy.spec.ts
- packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-strategy.ts
- packages/core/src/payment/create-payment-strategy-registry.ts
- packages/core/src/payment/payment-strategy-registry.ts
- packages/core/src/payment/payment-strategy-type.ts
- packages/core/src/payment/strategies/paypal-commerce/paypal-commerce-funding-key-resolver.ts
- packages/core/src/payment/strategies/paypal-commerce/paypal-commerce-payment-processor.spec.ts
- packages/core/src/payment/strategies/paypal-commerce/paypal-commerce-payment-processor.ts
- packages/core/src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.spec.ts
- packages/core/src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.ts
- packages/core/src/payment/strategies/paypal-commerce/paypal-commerce-request-sender.ts
- packages/core/src/payment/strategies/paypal-commerce/paypal-commerce-sdk.ts
A separate module was created for the Venmo payment method on the backend side. The common button strategy for all PPCP SPBs has now been expanded. In the future, a separate strategy will be created for each spb, including for Venmo. These tasks are already planned.
We need a module for the Venmo payment method to create separate button strategy for it
https://github.com/bigcommerce/bigpay/pull/5495
https://github.com/bigcommerce/bigcommerce/pull/46631
https://github.com/bigcommerce/bigpay-client-js/pull/132
https://github.com/bigcommerce/checkout-js/pull/891
New approach
Old approach
> feat(payment): PAYPAL-1487 Add paypalcommercevenmo module

- packages/core/src/payment/strategies/braintree/braintree-credit-card-payment-strategy.spec.ts
- packages/core/src/payment/strategies/braintree/braintree-credit-card-payment-strategy.ts
- packages/core/src/payment/strategies/braintree/braintree-hosted-form.spec.ts
- packages/core/src/payment/strategies/braintree/braintree-hosted-form.ts
- packages/core/src/payment/strategies/braintree/braintree-payment-processor.spec.ts
- packages/core/src/payment/strategies/braintree/braintree-payment-processor.ts
- packages/core/src/payment/strategies/braintree/braintree.ts
Removed authentication insight 3DS pre check on Braintree
It should help us to reduce issues with 3DS verification on Braintree, because we will challenge 3DS verification for all transaction (accept 'unregulated') if 3DS is enabled in Braintree settings form on CP
Unit tests
Manual tests
> feat(payment): PAYPAL-1508 removed authentication insight to force trigger 3DS check on Braintree

- packages/core/src/checkout/checkout-service.spec.ts
- packages/core/src/payment/payment-method-action-creator.spec.ts
- packages/core/src/payment/payment-method-action-creator.ts
- packages/core/src/payment/payment-method-request-sender.spec.ts
- packages/core/src/payment/payment-method-request-sender.ts
- packages/core/src/payment/strategies/klarnav2/klarnav2-payment-strategy.ts
Added Cart Id as a required parameter for GET payments API endpoint. 
To support buy-now cart, we will need to pass cart id for GET payments API endpoint to return the list payment providers against the cart
@bigcommerce/checkout @bigcommerce/payments @josesonora @BC-AOrtiz
> feat(checkout): CHECKOUT-6722 pass cart Id to SF/payments API endpoint

- packages/core/src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.ts
- packages/core/src/payment/strategies/stripe-upe/stripe-upe.ts
Add support for Klarna as a payment method on StripeUPE.
To enable and use Klarna with Stripe UPE.
As a Merchant, I want to be able to enable or disable Klarna within the Stripe configuration settings page so that I can control whether Klarna is available to my shoppers or not.
- [Authorize Only](https://drive.google.com/file/d/1QTni4ZiwHSKCOwgodiYBbLIlA87SoJbC/view?usp=sharing)
- [Purchase](https://drive.google.com/file/d/1Y-6b6MlE2Y8FJfOhPlr8vkQ3u_nLyXJl/view?usp=sharing)
- [Capture](https://drive.google.com/file/d/1HH-O7eKoWN1mfULEdxXKF99b7vtnuo8M/view?usp=sharing)
- [Refund](https://drive.google.com/file/d/1n8PBKG6MEvXndZkmYHcBpuqquDWqq0_m/view?usp=sharing)
- [Void](https://drive.google.com/file/d/1eg8qTgDgvEMntF9-0W_3fIJ4p95Jn4pr/view?usp=sharing)
ping @bigcommerce/payments …
> feat(payment): STRIPE-9 [Stripe UPE] Add support for Klarna

- packages/core/src/checkout/checkout-action-creator.ts
- packages/core/src/config/config-request-sender.spec.ts
- packages/core/src/config/config-request-sender.ts
pass checkout Id to checkout settings api as query string in the checkout loading action: `/api/storefront/checkout-settings?checkoutId=<cart_id>`
> didn't change `loadDefaultCheckout` action, since buy-now cart checkout never use it.
storefront checkout settings changes to allow passing cart id:
https://github.com/bigcommerce/bigcommerce/pull/46795
to support buy-now cart checkout, to get checkout settings of buy-now cart.
1) checkout page with buy-now cart id in page url `/checkout/b316955c-2e73-40a4-92d4-50541331aa34`
call checkout settings with buy-now cart id in query string: `/api/storefront/checkout-settings?checkoutId=b316955c-2e73-40a4-92d4-50541331aa34&include=cart.lineItems.physicalItems.categoryNames&include=cart.lineItems.digitalItems.categoryNames`
2) checkout page without …
> feat(checkout): CHECKOUT-6765 pass checkout Id to checkout settings api as query string

- packages/core/src/payment/payment-methods.mock.ts
- packages/core/src/payment/payment-request-transformer.spec.ts
- packages/core/src/payment/payment-request-transformer.ts
Check if BOPIS is enabled and send `null` as the shipping address to Stripe if the shopper selects to pick up the entire order.
When the shopper selects to pick up the entire order, nothing is passed in for shipping to Stripe.
_**BC Control Panel:**_
_**Stripe Control Panel:**_
~👉 https://github.com/bigcommerce/bigcommerce/pull/46057 to get the `isBopisEnabled` flag.~
👉 https://github.com/bigcommerce/bigcommerce/pull/47101 to get the BOPIS data.
> feat(payment): INT-3925 StripeV3: BOPIS

- packages/core/src/checkout-buttons/strategies/apple-pay/apple-pay-button-strategy.ts
- packages/core/src/customer/strategies/apple-pay/apple-pay-customer-strategy.ts
Apple Pay order initiated from Cart are missing phone number on billing address
Support received calls around billing address phone number missing for apple pay orders created initiated from cart.
- tests
> fix(payment): CHECKOUT-6790 Pass phone number as part of billing address for apple pay wallet buttons

- packages/core/src/checkout-buttons/checkout-button-options.ts
- packages/core/src/checkout-buttons/create-checkout-button-registry.spec.ts
- packages/core/src/checkout-buttons/create-checkout-button-registry.ts
- packages/core/src/checkout-buttons/strategies/checkout-button-method-type.ts
- packages/core/src/checkout-buttons/strategies/paypal-commerce/get-valid-button-style.spec.ts
- packages/core/src/checkout-buttons/strategies/paypal-commerce/get-valid-button-style.ts
- packages/core/src/checkout-buttons/strategies/paypal-commerce/index.ts
- packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-venmo-button-options.ts
- packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-venmo-button-strategy.spec.ts
- packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-venmo-button-strategy.ts
- packages/core/src/payment/strategies/paypal-commerce/paypal-commerce-request-sender.ts
- packages/core/src/payment/strategies/paypal-commerce/paypal-commerce-script-loader.spec.ts
- packages/core/src/payment/strategies/paypal-commerce/paypal-commerce-script-loader.ts
- packages/core/src/payment/strategies/paypal-commerce/paypal-commerce-sdk.ts
Added PayPalCommerce Venmo button strategy
It is a part of PayPalCommerce button strategy separation what we need to initialise and render PayPalCommerce buttons separately in different containers.
Unit tests
> feat(payment): PAYPAL-1383 added PayPalCommerce Venmo button strategy

- packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-strategy.ts
- packages/core/src/payment/strategies/paypal-commerce/paypal-commerce-payment-processor.spec.ts
- packages/core/src/payment/strategies/paypal-commerce/paypal-commerce-payment-processor.ts
Removed Paypal Commerce apms visibility on cart page
Because they should not be visible for paypal sdk with 'commit false' param.
Due the task: https://bigcommercecloud.atlassian.net/browse/PAYPAL-1560
Unit tests
Manual tests
Before:
After:
> fix(payment): PAYPAL-1560 removed paypal commerce apms visibility on cart page

- packages/core/src/payment/payment.ts
- packages/core/src/payment/strategies/bolt/bolt-payment-strategy.spec.ts
- packages/core/src/payment/strategies/bolt/bolt-payment-strategy.ts
- packages/payment-integration/src/payment/payment.ts
Remove experiment `BOLT-203.Bolt_string_type_of_token_card_data` for last four digits type
Because of task: [https://bigcommercecloud.atlassian.net/browse/BOLT-255](https://bigcommercecloud.atlassian.net/browse/BOLT-255)
BCapp PR: https://github.com/bigcommerce/bigcommerce/pull/47329
> feat(payment): BOLT-255 remove experiment for last four digits type

- packages/core/src/checkout-buttons/checkout-button-options.ts
- packages/core/src/checkout-buttons/create-checkout-button-registry.ts
- packages/core/src/checkout-buttons/strategies/checkout-button-method-type.ts
- packages/core/src/checkout-buttons/strategies/paypal-commerce/index.ts
- packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-alternative-methods-button-options.ts
- packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-alternative-methods-button-strategy.spec.ts
- packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-alternative-methods-button-strategy.ts
- packages/core/src/payment/strategies/paypal-commerce/paypal-commerce-request-sender.ts
Added new checkout button strategy for paypal commerce apms
To separate APM functionality from PayPal Commerce common strategy and to make an ability to render PayPal APM buttons in their own containers
Unit tests
> feat(payment): PAYPAL-1532 added PayPalCommerceAlternativeMethods checkout button strategy

- packages/core/project.json
Run `npx nx run core:generate` before running `build-cdn` command.
Otherwise, the build will fail as it won't have the generated files to build with.
> CHECKOUT-6780: Add missing dependency for CDN build

- package-lock.json
- package.json
- packages/core/api-extractor/checkout-button.json
- packages/core/api-extractor/checkout-sdk.json
- packages/core/api-extractor/embedded-checkout.json
- packages/core/api-extractor/internal-mappers.json
Upgrade API extractor library from v6 to v7
The new version has a couple of improvements. Please note that all the warnings are disabled at the moment because they need to be fixed individually.
CircleCI
> CHECKOUT-6781: Upgrade API extractor

- package-lock.json
- package.json
- packages/core/api-extractor/checkout-button.json
- packages/core/api-extractor/checkout-sdk.json
- packages/core/api-extractor/embedded-checkout.json
- packages/core/api-extractor/internal-mappers.json
Reverts bigcommerce/checkout-sdk-js#1525
For some reason most of the types went missing when the build task was executed in CircleCI.
> Revert "CHECKOUT-6781: Upgrade API extractor"

- packages/core/project.json
- packages/core/src/checkout/checkout-service.spec.ts
- packages/core/src/checkout/create-checkout-service.ts
- packages/core/src/payment/create-payment-strategy-registry.spec.ts
- packages/core/src/payment/create-payment-strategy-registry.ts
- packages/core/src/payment/index.ts
- packages/core/src/payment/payment-strategy-action-creator.spec.ts
- packages/core/src/payment/payment-strategy-action-creator.ts
- packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-strategy.spec.ts
- packages/core/src/payment/strategies/braintree/braintree-visacheckout-payment-strategy.spec.ts
- packages/core/src/payment/strategies/chasepay/chasepay-payment-strategy.spec.ts
- packages/core/src/payment/strategies/googlepay/googlepay-payment-strategy.spec.ts
- packages/core/src/payment/strategies/square/square-payment-strategy.spec.ts
- webpack-cdn.config.js
- webpack-common.config.js
- Load payment methods from automatic v2 strategy registry as priority and use v1 as fallback
- Update webpack config to process packages with ts-loader 
As we move towards payment strategy packages, we want to register strategies as part of build process. 
Also process packages with ts-loader, we need to have a rule per package for now [issue](https://github.com/TypeStrong/ts-loader/issues/647). 
- tests
> chore(common): CHECKOUT-6855 Load payment strategies from V2 as priority

- packages/core/src/payment/strategies/ppsdk/step-handler/continue-handler/redirect/redirect.spec.ts
- packages/core/src/payment/strategies/ppsdk/step-handler/continue-handler/redirect/redirect.ts
Change `formFields` parameter name to `form_fields` in PPSDK redirect (offsite) payment method, so it executes correctly with the `POST` method.
To fix the issue.
Unit tests
Screenshots
**Before**
**After**
> fix(payment): PAYMENTS-8045 Fix form fields parameter name for PPSDK redirect

- packages/core/src/payment/strategies/adyenv2/adyenv2-initialize-options.ts
- packages/core/src/payment/strategies/adyenv2/adyenv2-payment-strategy.ts
- packages/core/src/payment/strategies/adyenv2/adyenv2.ts
- packages/core/src/payment/strategies/adyenv3/adyenv3-initialize-options.ts
- packages/core/src/payment/strategies/adyenv3/adyenv3-payment-strategy.spec.ts
- packages/core/src/payment/strategies/adyenv3/adyenv3-payment-strategy.ts
- packages/core/src/payment/strategies/adyenv3/adyenv3.ts
Added custom Adyen validation for saved card validation, comparison of last 4 symbols entered and saved card.
checkout-js pr: https://github.com/bigcommerce/checkout-js/pull/935
Due to the https://bigcommercecloud.atlassian.net/browse/ADYEN-539
https://user-images.githubusercontent.com/79574476/180739964-1cdbb97a-4202-4b7c-a161-944cd86818bc.mov
> feat(payment): ADYEN-539 added vaulting card validation

- packages/apple-pay/src/apple-pay-customer-initialize-options.ts
- packages/apple-pay/src/apple-pay-payment-initialize-options.ts
- packages/core/extend-interface.config.json
- packages/core/project.json
- packages/core/src/checkout-buttons/checkout-button-options-v2.ts
- packages/core/src/checkout-buttons/checkout-button-options.ts
- packages/core/src/checkout-buttons/index.ts
- packages/core/src/checkout-buttons/strategies/checkout-button-method-type.ts
- packages/core/src/customer/customer-request-options-v2.ts
- packages/core/src/customer/customer-request-options.ts
- packages/core/src/customer/index.ts
- packages/core/src/payment/index.ts
- packages/core/src/payment/payment-request-options-v2.ts
- packages/core/src/payment/payment-request-options.ts
- packages/workspace-tools/src/generators/extend-interface/__fixtures__/foobar-interface/foobar-interface.ts
- packages/workspace-tools/src/generators/extend-interface/__fixtures__/foobar-interface/index.ts
- packages/workspace-tools/src/generators/extend-interface/__fixtures__/interface-a/index.ts
- packages/workspace-tools/src/generators/extend-interface/__fixtures__/interface-a/interface-a.ts
- packages/workspace-tools/src/generators/extend-interface/__fixtures__/interface-b/index.ts
- packages/workspace-tools/src/generators/extend-interface/__fixtures__/interface-b/interface-b.ts
- packages/workspace-tools/src/generators/extend-interface/__snapshots__/extend-interface.spec.ts.snap
- packages/workspace-tools/src/generators/extend-interface/extend-interface-config.ts
- packages/workspace-tools/src/generators/extend-interface/extend-interface.spec.ts
- packages/workspace-tools/src/generators/extend-interface/extend-interface.ts
- packages/workspace-tools/src/generators/extend-interface/is-extend-interface-config.ts
Use interfaces extracted from various payment integration packages.
This is the second attempt. We reverted the [last attempt](https://github.com/bigcommerce/checkout-sdk-js/pull/1526) because the generated types ended up clashing with the hand-written types. As a result, we ended up exporting multiple types with the same name, and they were automatically renamed with numeric suffixes (e.g.: `_2`, `_3`) when they were rolled up into a single `.d.ts` file. This attempt addresses the name collision so we can safely export the generated types.
CircleCI + Manual
|initializeButton|initializeCustomer|initializePayment|
|---|---|---|
|<img width="799" alt="Screen Shot 2022-08-03 at 10 35 34 AM" src="https://user-images.githubusercontent.com/667603/182499751-79559b6a-2e05-4971-a193-c0b38e23ca42.pn …
> CHECKOUT-6781: Point to interfaces extracted from integration packages

- packages/core/src/payment/payment.ts
- packages/core/src/payment/strategies/mollie/mollie-payment-strategy.ts
- packages/core/src/payment/strategies/stripev3/stripev3-payment-strategy.spec.ts
- packages/core/src/payment/strategies/stripev3/stripev3-payment-strategy.ts
Add `shouldSetAsDefaultInstrument` method to the `formattedPayload`  
In order to have stored card as default during checkout.
https://user-images.githubusercontent.com/67211919/178614708-732edf9e-226d-4438-8f2f-e3103c7bb617.mov
> fix(payment): STRIPE-51 set a stored card as default during checkout

- packages/core/src/checkout-buttons/strategies/amazon-pay-v2/amazon-pay-v2-button-options.ts
- packages/core/src/checkout-buttons/strategies/amazon-pay-v2/amazon-pay-v2-button-strategy.spec.ts
- packages/core/src/checkout-buttons/strategies/amazon-pay-v2/amazon-pay-v2-button-strategy.ts
- packages/core/src/customer/strategies/amazon-pay-v2/amazon-pay-v2-customer-strategy.spec.ts
- packages/core/src/customer/strategies/amazon-pay-v2/amazon-pay-v2-customer-strategy.ts
- packages/core/src/payment/payment-methods.mock.ts
- packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-processor.spec.ts
- packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-processor.ts
- packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-strategy.spec.ts
- packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-strategy.ts
- packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2.mock.ts
- packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2.ts
1. Refactored duplicated blocks of code.
2. Upgrade to the new Amazon Pay Checkout version.
The button should now render faster because our `/payment-session` endpoint is not called anymore to create the checkout session.
🎬🍿 [>>video<<](https://drive.google.com/file/d/11ZneWUspg65cm7DNFMScr1ft0nIMRb0C/view?usp=sharing)
> feat(payment): INT-6128 AmazonPayV2: Introduce the new API V2 config

- packages/core/src/checkout/checkout-service.spec.ts
- packages/core/src/checkout/create-checkout-service.ts
- packages/core/src/customer/create-customer-strategy-registry.ts
- packages/core/src/customer/customer-request-options.ts
- packages/core/src/customer/customer-strategy-action-creator.spec.ts
- packages/core/src/customer/customer-strategy-action-creator.ts
- packages/core/src/customer/customer-strategy-registry-v2.ts
- packages/core/src/customer/index.ts
- packages/core/src/customer/strategies/braintree/braintree-visacheckout-customer-strategy.spec.ts
Load customer methods from automatic v2 strategy registry as priority and use v1 as fallback
As we move towards customer strategy packages, we want to register strategies as part of build process.
- circle
> chore(common): CHECKOUT-6855 Load customer strategies from V2 as priority

- packages/core/src/order/order.ts
- packages/core/src/order/orders.mock.ts
- packages/payment-integration/src/order/order.ts
Update order consignment interface
The interface for order response is outdated. Have updated it as per https://developer.bigcommerce.com/api-reference/f40f1f75f3e00-get-order 
Issue - https://github.com/bigcommerce/checkout-sdk-js/issues/1547
- Circle
> fix(order): CHECKOUT-000 Update order consignments interface

- packages/core/src/config/config.ts
- packages/core/src/config/configs.mock.ts
- https://github.com/bigcommerce/bigcommerce/pull/47777
Added **hidePriceFromGuests** to StoreConfig interface for checkouts.
STRF-9829 will move the "Hide price for guests" functionality to BigCommerce instead of themes, so we should ensure that this value is available to the Checkout SDK since it will now be returned by the **checkout-settings** endpoint.
This setting needs to be exposed so that if a user signs out mid-checkout while prices are restricted to login, they will be redirected to the cart page.
**note: screenshot is outdated slightly. Variable has changed to hidePriceFromGuests**
> feat(checkout): STRF-9829 Add hidePriceFromGuests to StoreConfig interface

- packages/core/src/payment/strategies/mollie/mollie-initialize-options.ts
- packages/core/src/payment/strategies/mollie/mollie-payment-strategy.spec.ts
- packages/core/src/payment/strategies/mollie/mollie-payment-strategy.ts
- packages/core/src/payment/strategies/mollie/mollie.mock.ts
I want to hide any Klarna Pay Later and Klarna Slice It from shoppers if their cart contains digital products
So that I can prevent shoppers from trying to pay for an ineligible cart and getting an error
Before
https://user-images.githubusercontent.com/104527753/180102690-63e27651-3e1d-466b-bc3d-24f71aaf2b78.mov
After
https://user-images.githubusercontent.com/104527753/180099759-592b8826-6aea-4258-a53c-4835332259d4.mov
> fix(payment): INT-5854 [Mollie] Klarna is not available if cart contains digital products

- packages/core/src/customer/strategies/braintree/braintree-visacheckout-customer-strategy.ts
Change VCO button size from `154` to `178x32`
To allow the discover card icon to be displayed, and to be consistent with other similar checkout buttons
bigcommerce/checkout bigcommerce/payments bigcommerce/apex-integrations
> feat(customer): INT-6023 Resize VCO button for Discover cards
